### ISSUE TITLE
Do I need paket installed?

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1001]
### Description

I'm trying to play with fable dotnet cli but I having an issue with restoring packages.

### Repro code

```
> dotnet new -i Fable.Template::*
> dotnet new fable
> dotnet restore
```

### Expected and actual results

```
C:\temp\FableInterop\.paket\Paket.Restore.targets(17,5): error MSB3073: The command ""C:\temp\FableInterop\.paket\paket.exe" restore --project "C:\temp\FableInterop\FableInterop.fsproj" --target-framework netstandard1.6" exited with code 1. [C:\temp\FableInterop\FableInterop.fsproj]
```

I do not have paket installed globally. Nor do I have the fable compiler as global npm package.
It is a bit confusing whether I still need those installed upfront.

### Related information 

* fable-compiler version: not sure
* fable-core version: not sure
* Operating system: Windows 7

```
 <DotNetCliToolReference Include="dotnet-fable" Version="1.0.4" />
 "fable-loader": "^1.0.0",
```

**Comment by nojaf** [comment]
Gosh, I just noticed that my problem is related to our company proxy.

```dotnet restore -v diag``` shows

```
EXEC : The remote server returned an error : (407) Proxy Authentication Required. (Github - cached) [C:\temp\FableIntrop\FableInterop.fsproj]
C:\temp\FableInterop\.paket\Paket.Restore.targets(17,5): error MSB3073: The command ""C:\temp\FableInterop\.paket\pakt.exe" restore --project "C:\temp\FableInterop\FableInterop.fsproj" --target-framework netstandard1.6" exited with coe -1. [C:\temp\FableInterop\FableInterop.fsproj]
```
Where should I specify proxy settings?

**Comment by MangelMaxime** [comment]
Can you try doing:

`.paket\paket.exe update` and then `dotnet restore` ?

**Comment by nojaf** [comment]
After I set 
```set HTTPS_PROXY=https://user:password@proxy.company.com:port/``` paket was able to download everything.
