### ISSUE TITLE
Auto compilation not working on the default installed example

### ISSUE THREAD

**Issue by caxelrud** [fable-compiler/Fable#1004]
I followed the instructions given at "getting started" for Fable 1.0
(https://github.com/fable-compiler/Fable/blob/master/docs/pages/getting-started.md)
I started the Webpack developement server.
But, making changes to the App.fs and saving make no effect in the browser page.
I ran "dotnet fable npm-run build" in another terminal successfully. But no changes in the browser page.
The only way to browser page for changes of the App.fs is to stop the Webpack development server and restart it.

### Related information 

* fable-compiler version: don't know where to find this info
* fable-core version: don't know where to find this info
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
@caxelrud Hello, how did you start the Webpack devlopement server ?

**Comment by caxelrud** [comment]
Following the getting-started, I tried both options without success:
Option 1: "dotnet fable npm-run start"
Option 2: "dotnet fable start" and "npm run start"

**Comment by caxelrud** [comment]
Following the getting-started, I tried both options without success:
Option 1: "dotnet fable npm-run start"
Option 2: "dotnet fable start" and "npm run start"

**Comment by alfonsogarciacaro** [comment]
The documentation, samples and Fable.Template have been updated so hopefully everything should be working now 😄 Please reopen if you still have problems after upgrading.
