### ISSUE TITLE
Sequence yield + Zero() throws `Exception 1`

### ISSUE THREAD

**Issue by haf** [fable-compiler/Fable#1006]
### Description

In view code:

```
      dl
        [ ]
        [
          yield dd
            []
            [ str "Total taxes"]
          yield dt
            []
            [ input [] ]
          if Option.defaultValue 0m model.totalTaxes > 0m then
            yield rateSubcomponents model dispatch
          else
            ()
        ] ]
```

Works. But this crashes:

```
      dl
        [ ]
        [
          yield dd
            []
            [ str "Total taxes"]
          yield dt
            []
            [ input [] ]
          if Option.defaultValue 0m model.totalTaxes > 0m then
            yield rateSubcomponents model dispatch
        ] ]
```

### Repro code

Please provide the F# code to reproduce the problem.
Ideally, it should be possibe to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information 

* fable-compiler version: 1.0.8
* fable-core version:
* Operating system: OS X

**Comment by Zaid-Ajaj** [comment]
Simplified issue
```fs
[ if 1m > 0m then yield 5] 
|> Seq.length
|> printfn "%d"
```
[Dotnet fiddle](https://dotnetfiddle.net/Ui46Pq) => prints 1
[Fable Repl](http://fable.io/repl#?code=%5B%20if%201m%20%3E%200m%20then%20yield%205%5D%20%0A%7C%3E%20Seq.length%0A%7C%3E%20printfn%20%22%25d%22) => prints 0
Fable seems unable to generate the correct values for decimals:
```js
toList(delay(function () {
  return 0 > 0 ? singleton(5) : empty();
}))
```
Also:
```fs
let x = 5m
```
compiles to 
```js
export const x = 0;
```

**Comment by ncave** [comment]
@Zaid-Ajaj The decimal issue above is a Fable JS (REPL) issue, not a Fable issue, so it's probably unrelated to the OP, do you mind moving it to a separate issue? Proper decimal support is not available in Fable REPL yet, and only partially supported in Fable (as float).

**Comment by haf** [comment]
I knew it would have compiled to floats and that would have been fine with me.

**Comment by alfonsogarciacaro** [comment]
I tried to repro with the following code:

```fsharp
let mkSeq x = seq {
  if x > 5
  then yield "foo"
  else ()
}

let mkSeq2 x = seq {
  if x > 5
  then yield "bar"
}

mkSeq 6 |> printfn "SEQ: %A"
mkSeq 4 |> printfn "SEQ: %A"
mkSeq2 6 |> printfn "SEQ2: %A"
mkSeq2 4 |> printfn "SEQ2: %A"
```

But I didn't see any problem. Would it be possible to have some code to repro the problem without dependencies? Thanks!

**Comment by haf** [comment]
It's not  seq, it's a list with a yield in it, so it doesn't go through a workflow builder.

I appreciate it can be hard to reproduce bugs, but I'm myself lacking in time right now and this was just me going *let's see how mature the toolchain is and see if I can port something into it*. I'm closing this issue due to lack of a repro.

**Comment by MangelMaxime** [comment]
For info, I am using list with yield keyword without problem.
It's probably an edge case encounter here.

**Comment by haf** [comment]
Btw, here's the repro https://github.com/haf/temporary-fable-bugrepro but I'm not going to invest more time into this issue.

**Comment by alfonsogarciacaro** [comment]
I also tried with lists but I didn't see any problem. Actually, lists and array comprehensions just go through the sequence workflow and then are converted to the proper collection, at least in the F# compiler AST.

Thanks for the report and the repro @haf, I'll try to go though it when I have a moment.
