### ISSUE TITLE
Docs: usage of npm vs yarn is confusing

### ISSUE THREAD

**Issue by haf** [fable-compiler/Fable#1008]
### Description

When getting started, npm and yarn are both "used" in the sense that `dotnet fable npm-run` uses npm but the templates are installing yarn.

Either alias `yarn-run` to `npm-run` or make it explicit (for those who don't know what npm/yarn is), that we're "executing javascript" via `js-run` or similar.

A suggestion. Feel free to close if you don't agree.

**Comment by MangelMaxime** [comment]
We had something similar with elmish template.

Finally we used the command: `dotnet fable shell-run "yarn start"`

Do you find it less confusing ?

**Comment by alfonsogarciacaro** [comment]
We can also add a `yarn-run` command, that's an easy one, so @MangelMaxime suggestion becomes `dotnet fable yarn-run start`.

JS cannot be run by itself so I'd rather mention the tool explicitly. We also have a `dotnet fable node-run` command to run a JS file directly.

**Comment by MangelMaxime** [comment]
Problem with adding `yarn-run` is we would end up adding more and more alias command. I already heard of 3-4 npm like commands (welcome in JS worlds :trollface: )

**Comment by haf** [comment]
I'm for `yarn-run` since it follows the principle of least surprise and mentions the tool it'll call thereby making it explicit.

**Comment by mike-morr** [comment]
In this case ```yarn run``` may not be accurate, as what you are actually running is an npm script.  Even if you use yarn to execute, you are still running an NPM script under the hood.

**Comment by alfonsogarciacaro** [comment]
Latest fable version (1.1.1) adds a `yarn-run` command. Even if it's a new command, it shouldn't be difficult to remember as it follows the same pattern as for the others: npm-run, node-run, shell-run.

I don't know exactly how `yarn run` executes, I'm not sure either if scripts in package.json are exclusively considered npm scripts. Yarn has an interesting features as it can run local modules like `yarn run webpack`.

Also, for both npm and yarn, Fable 1.1.1 allows a shortcut following the pattern `dotnet fable yarn-run start` ->  `dotnet fable yarn-start`.

**Comment by alfonsogarciacaro** [comment]
I tried to make it so the use of `yarn` and `npm` keywords are exchangeable in the commands to give the choice to the user. This is explained in [a note here](http://fable.io/docs/getting-started.html#tl-dr) but please feel free to send a PR if that's not clear enough :+1:
