### ISSUE TITLE
Support Webpack 3

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#1017]
Webpack 3 was released and supports things like rollup style scope hoisting:

https://medium.com/webpack/webpack-3-official-release-15fd2dd8f07b

This is a placeholder issue to ensure fable-loader works well with webpack 3.

**Comment by alfonsogarciacaro** [comment]
@jgrund Did you try Fable with Webpack 3 yet? I tried to update the template to Webpack but yarn was giving me conflicts with some Webpack plugins so I gave up.

**Comment by alfonsogarciacaro** [comment]
Previous versions gave errors, but I just tested and latest one (Webpack 3.3.0) is working with Fable in a medium-size project without problems :tada:
