### ISSUE TITLE
Repl: Use ionide web for F# code

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1021]
someone should bribe @Krzysztof-Cieslak to do that ;-)

**Comment by alfonsogarciacaro** [comment]
@ncave already FSAC compilable by Fable, we need to continue the work on that. Though the first step is to make FCS+Fable a pure JS npm package so the F# compiler can be embedded in any web page. We're also waiting for netstandard2.0 to reduce the size of core libraries to reduce the download size.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, the auto-complete and tooltips have been available for [quite some time](https://github.com/fable-compiler/Fable/issues/727#issuecomment-288747072) in [FCS-Fable](https://github.com/ncave/FSharp.Compiler.Service/blob/fable/src/fsharp/fcs-fable/test/app.fs#L69-L79). I have a placeholder for a [fable-repl](https://github.com/ncave/fable-repl) repo using monaco, but unfortunately real life and other projects get in a way so progress is slow. Maybe we can get an official repo going so more people can contribute.

**Comment by alfonsogarciacaro** [comment]
The new Fable REPL is already available :)
