### ISSUE TITLE
Docs: integrate elmish docs

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1022]
or at least add BIG link to it

**Comment by alfonsogarciacaro** [comment]
I'd vote to keep both projects independent for the time being, but I'm all for promoting Elmish like the standard way to do apps in fable.io. I'd also like to have Fable's web itself made with Elmish too and make it very easy to add new samples.

**Comment by MangelMaxime** [comment]
The solution could be a page dedicated to the community work. Listing the all the "important" project to know for example.

We could also add a link to Fable Awesome because if don't know it exist you never see it :)

**Comment by alfonsogarciacaro** [comment]
There are now several links to fable-awesome in the web. Also in the Productivity section of the samples page, there's a note (with a link to Elmish documentation) saying Elmish is the recommended way to creating SPAs with Fable. Please feel free to send a PR if you want it to be more prominent :wink:
