### ISSUE TITLE
Repl: Create a Repl that is especially nice to show elmish

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1025]
I have no idea how that would look like. But please do ;-)

**Comment by alfonsogarciacaro** [comment]
The first step is allow the REPL to do some graphics or DOM manipulation. That shouldn't be difficult, just exposing a canvas or some elements in the page.

**Comment by et1975** [comment]
Technically, elmish does not require UI, the [elmish basics](https://fable-elmish.github.io/elmish/basics.html) on the docs site can run with nothing but console.log. Wether or not it would provide necessary insights is another question :)

**Comment by alfonsogarciacaro** [comment]
We already have the UI REPL, now we need to be able to load libraries in it. Discussed here: https://github.com/fable-compiler/fable-repl/issues/5#issuecomment-355780693
