### ISSUE TITLE
 Arguments of auto-generated lambdas conflicting with outer variables

### ISSUE THREAD

**Issue by coolya** [fable-compiler/Fable#1028]
### Description

Using the cons operator doesn't work correctly. Nothing is prepended to the list. Instead the original list is returned. 

### Repro code

```
let modifyList current x =
    let contains = current |> List.contains x
    match contains with
        | true -> current |> (List.filter (fun a -> a <> x))
        | false -> x::current
        
        

let l = [1;2;3;4]

printfn "%A" l

printfn "%A" (modifyList l 1)

printfn "%A" (modifyList l 5)
```

### Expected and actual results

[REPL](http://fable.io/repl.html#?astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2&code=let%20modifyFilterList%20current%20x%20%3D%0A%20%20%20%20let%20contains%20%3D%20current%20%7C%3E%20List.contains%20x%0A%20%20%20%20match%20contains%20with%0A%20%20%20%20%20%20%20%20%7C%20true%20-%3E%20current%20%7C%3E%20(List.filter%20(fun%20a%20-%3E%20a%20%3C%3E%20x))%0A%20%20%20%20%20%20%20%20%7C%20false%20-%3E%20x%3A%3Acurrent%0A%20%20%20%20%20%20%20%20%0A%20%20%20%20%20%20%20%20%0A%0Alet%20l%20%3D%20%5B1%3B2%3B3%3B4%5D%0A%0Aprintfn%20%22%25A%22%20l%0A%0Aprintfn%20%22%25A%22%20(modifyFilterList%20l%201)%0A%0Aprintfn%20%22%25A%22%20(modifyFilterList%20l%205)) prints:

```
"[1; 2; 3; 4]"
"[2; 3; 4]"
"[1; 2; 3; 4]"
```

While FSI prints correctly:

```
[1; 2; 3; 4]
[2; 3; 4]
[5; 1; 2; 3; 4]
```

### Related information

* Fable version (`dotnet fable --version`): 1.1.4
* Operating system: OSX

**Comment by coolya** [comment]
The actual problem is not the cons operator it's a name clash between the `x` parameter and the `x` parameter of the generated closure. 

```
  const contains = function (source) {
    return exists(x => equals(x, x), source);
  }(current);
```

**Comment by alfonsogarciacaro** [comment]
Fixed by #1029 and published in 1.1.5. Thanks @coolya!
