### ISSUE TITLE
Docs: Samples links to github are broken

### ISSUE THREAD

**Issue by justinjstark** [fable-compiler/Fable#1031]
### Description

The samples moved to their own repository and the links in the docs need updated.

### Expected and actual results

Examples:
- http://fable.io/samples.html
    - Any "raw source on github" is a 404
- http://fable.io/samples/mario/index.html
    - "Full source code on github" is a 404

**Comment by alfonsogarciacaro** [comment]
Sorry for replying so late! This should have been fixed after the web update. Well now we only have a generic link to the samples-browser repo but we'll add later automatic generation of links to each sample source :+1:
