### ISSUE TITLE
Docs: Provide guidance for fable nuget publish

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1056]
### Description
We should provide explanations on how to create a nuget package.

- Source files under `fable` folder when we provide code in the package. (Ex: not needing if we only provide bindings)
- DLL always required
- etc.

**Comment by inosik** [comment]
XML docs should also be included in the NuGet package, I think. Although the majority of the current bindings and libraries doesn't seem to have docs, it'd be pretty nice. Adding `<GenerateDocumentationFile>true</GenerateDocumentationFile>` to the project file is enough.

**Comment by alfonsogarciacaro** [comment]
True! We also need to update ts2fable so it also takes the comments from the declaration files.

**Comment by alfonsogarciacaro** [comment]
Closing this as we have https://github.com/TheAngryByrd/Fable.Template.Library now :)
