### ISSUE TITLE
Performance issue

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1062]
### Description

When people use Fable.Elmish.Bulma, the file [BulmaClasses](https://github.com/MangelMaxime/Fable.Elmish.Bulma/blob/master/src/BulmaClasses.fs) take a lot of time to build.

@alfonsogarciacaro I created this issue to make us think of checking the situation. As this could lead to global perf improvements :)

**Comment by alfonsogarciacaro** [comment]
Ok, I add some extra project files so Fable can be compiled for NET Framework (see #1064) and I can profile the app. To my surprise [these lines](https://github.com/fable-compiler/Fable/blob/3fdfec3e740516bb0bbdb60f2e341a2845c6671e/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1000-L1006) were taking most of CPU time 😮 [A bit of refactoring](https://github.com/fable-compiler/Fable/commit/19ff181de9bd71478c08d648da926987b0e7c849) and now Fable is even faster than using the cache :wink:

**Comment by MangelMaxime** [comment]
I confirm :)
14sec now 🍾

**Comment by forki** [comment]
![kbs](https://user-images.githubusercontent.com/57396/28121758-62580d4e-671c-11e7-9100-7bf339cf7dc9.gif)
