### ISSUE TITLE
broken link to RELEASE_NOTES link in README.md

### ISSUE THREAD

**Issue by fbehrens** [fable-compiler/Fable#1074]
[RELEASE NOTES](https://github.com/fable-compiler/Fable/blob/master/RELEASE_NOTES.md)

Seem like the release notes are split up into many.
If you let me know how you like to have, i will create a PR for that

**Comment by alfonsogarciacaro** [comment]
Good point, @fbehrens! I need to update the README, but it you can you can fix the link to point to the RELEASE_NOTES in `src/dotnet/dotnet-fable`. Cheers!

**Comment by fbehrens** [comment]
-> #1077
