### ISSUE TITLE
Missing Option.flatten implementation

### ISSUE THREAD

**Issue by irium** [fable-compiler/Fable#1076]
### Description

Option.flatten method implementation is missing.

### Repro code

See #1075 

* Fable version (`dotnet fable --version`): 1.1.11
* Operating system:
Windows 10, x64

**Comment by alfonsogarciacaro** [comment]
As options are erased and nested options are also erased, I implement `Option.flatten` by also erasing it :wink:

**Comment by irium** [comment]
Thanks! :)
