### ISSUE TITLE
Equals is not a function error when comparing records

### ISSUE THREAD

**Issue by whitebear-gh** [fable-compiler/Fable#1081]
### Description

Hello, when I'm trying to compare records I get following error: 

> x.Equals is not a function

The workaround is to use one field to compare but comparing records works in F# itself. Is it possible to have it working in Fable? 

### Repro code

`records |> List.filter (fun r -> r = record2)`

**Comment by alfonsogarciacaro** [comment]
Hi @whitebear-gh! I tried something like the following but it's working for me:

```fsharp
type R = { foo: string }

let test() =
    let records = [{foo = "foo"}; {foo = "bar"}]
    let record2 = {foo = "foo"}
    let records2 = records |> List.filter (fun r -> r = record2)
    printfn "%A" records2
    List.length records2 |> equal 1

test()
```

Could you please provide a full repro code (including type definitions, etc) that fails with latest Fable version? Thanks a lot for your help!
