### ISSUE TITLE
Fable compiler should trace date/time when it compiles in watch mode

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1086]
I often find myself in watch mode wondering if it actually compile.
Note: I'm in watch mode all the time so I'm changing a file 20 times then it's hard to see in console if something happended.

**Comment by forki** [comment]
now it traces the timestamp - but not how long it took ;-)

**Comment by alfonsogarciacaro** [comment]
I think this is already implemented in fable-splitter, so let's close this. If you need extra logging, could you please send a PR? Thanks!
