### ISSUE TITLE
Possible to restrict type to POJO?

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#1088]
### Description

Many JS libs expect a POJO. Is there a way to type a JS lib signature such that only a POJO is accepted at compile time?

**Comment by alfonsogarciacaro** [comment]
Hi @jgrund! Yes, this is possible. You can add the `Pojo` attribute to a generic argument. In that case, Fable will fail if you don't instantiate the generic argument with a Pojo, an interface or `obj`. React helpers do this, for example [here](https://github.com/fable-compiler/fable-react/blob/e264802652cc4c8b5945d4dfb8151da873ac7815/Fable.Helpers.React.fs#L581) and [here](https://github.com/fable-compiler/fable-react/blob/e264802652cc4c8b5945d4dfb8151da873ac7815/Fable.Import.React.fs#L65).

I hope this helps!

**Comment by jgrund** [comment]
Hey @alfonsogarciacaro,

I'm not sure if I'm doing something incorrectly, but it seems like other param types are still accepted.

```
open Fable.Core

let fn<[<Pojo>]'P> (props:'P) = props

let r = fn "bar"
```

**Comment by alfonsogarciacaro** [comment]
@jgrund When I try to compile your code I get this message, is that not your case?

```
ERROR in ./QuickTest.fsx
/Users/alfonsogarciacaronunez/dev/Fable/src/tools/QuickTest.fsx(36,8): (36,16) error FABLE: Type String passed as generic param 'P must be decorated with Fable.Core.PojoAttribute or be `obj`/interface
```

This is with Webpack. Please note with Rollup the Fable plugins doesn't output errors, only warnings. This is because Rollup stops the compilation when it encounters an error so the dependencies are not read and watch compilations won't work.

> However with latest dotnet-fable version, the problem of F# errors reported in the .fsproj instead of the actual file has been fixed, maybe we could try [outputting actual errors with rollup-plugin-fable](https://github.com/fable-compiler/Fable/blob/65b7a425a08f81421be82d470a5040009f7dec02/src/js/rollup-plugin-fable/index.js#L90-L94).

**Comment by alfonsogarciacaro** [comment]
@jgrund I published a new version of the rollup plugin (1.1). Could you please give it a try with latest dotnet-fable (1.1.16)?

**Comment by jgrund** [comment]
Ah, I was looking in Ionide, where there was no error.

I'm actually using webpack, I'll check rollup shortly.

**Comment by alfonsogarciacaro** [comment]
This a Fable error so Ionide won't show it by default, but it's still possible to show Fable errors on Ionide, check: https://github.com/fable-compiler/Fable/blob/master/src/templates/simple/Content/README.md#building-and-running-the-app
