### ISSUE TITLE
dotnet fable template: dotnet restore fails

### ISSUE THREAD

**Issue by TomKemperNL** [fable-compiler/Fable#1095]
### Description

Please provide a succinct description of your issue.

### Repro code

mkdir some-app
cd some-app
dotnet new fable
cd src
dotnet restore

### Expected and actual results

I was expecting this to actually restore the packages, however it errors with:
```
/home/tom/Dev/klooien/fable-hello/.paket/Paket.Restore.targets(16,5): error MSB3073: The command " --runtime=v4.0.30319 "" restore --project "/home/tom/Dev/klooien/fable-hello/src/fable-hello.fsproj" --target-framework netstandard1.6" exited with code 127
```

if I manually edit the .paket/Paket.Restore.targets and add `<PaketRootPath>` and `<MonoPath>` elements, then it will work fine.

### Related information

* Fable version (`dotnet fable --version`):
1.1.9 (after applying the manual workaround)
* Cli version (`dotnet --version`):
2.0.0-preview2-006497
* Mono version
5.0.1.1
* Operating system:
Ubuntu 16.04

**Comment by TomKemperNL** [comment]
After posting this issue, I figured I'd take a teensy quick look at the template source, and I noticed major differences between the src/templates/simple/Content/.paket/Paket.Restore.Targets at the current head and what was actually in my .paket folder.

I'm guessing I had an old version of the template installed?
(which is sort of weird since I installed it Wednesday the 26th of July)

**Comment by MangelMaxime** [comment]
Hello @TomKemperNL , this is a bug due the `dotnet template engine`.

We recommand users to use `dotnet 1.0.4` with Fable is they can because `preview2` have a lot of bugs.

**Comment by TomKemperNL** [comment]
Well, then I'm happy to report that the template now works fine on preview2 after reinstalling the template.

**Comment by MangelMaxime** [comment]
Yes because we fixed the issue [manually](https://github.com/fable-compiler/Fable/blob/master/src/templates/simple/Content/.paket/Paket.Restore.targets#L2) for the template engine atm. :)

Good journey with Fable :)

But that's great if you got it working for you :)
