### ISSUE TITLE
Different behaviour for decimals in REPL and compiler

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1096]
@eiriktsarpalis has reported [in Twitter](https://twitter.com/eiriktsarpalis/status/890915006811959296) that `let incr x = x + 1M` in the REPL is compiled as:

```js
export function incr(x) {
  return x + 0;
}
```

While the compiler actually transforms it to:

```js
function incr(x) {
  return applyOperator(x, 1, "op_Addition");
}
```

 @ncave I think we already talked about the differences when dealing with decimal in the REPL, do you know why `1M` gets converted to `0` here?

BTW, maybe it's time to have a proper type for decimal. We could do something similar as with Long and use a external library like [decimal.js](https://github.com/MikeMcl/decimal.js) to support decimals with arbitrary precision. However, I haven't found anything with a five-argument constructor to translate [MakeDecimal](https://github.com/fsharp/fsharp/blob/c39fdbf671bc0aebc5644ee1c422f751fdad798b/src/fsharp/FSharp.Core/prim-types.fsi#L1104). Any ideas?

**Comment by ncave** [comment]
@alfonsogarciacaro The REPL just needs to be built (`build repl`) and redeployed, as it's running an old version of the Fable compiler. Then the decimal behavior will be the same. There are pros and cons to decimal as JS object instead of float, performance being one, but yeah, that constructor will have to be added as it's not there. Another option is using something like BigRational from the F# Powerpack.

**Comment by alfonsogarciacaro** [comment]
Unfortunately this seems to still be happening after updating the REPL :/

**Comment by ncave** [comment]
@alfonsogarciacaro It's something different, now I'm getting this:
`FSharp.Compiler.Service cannot yet return this kind of constant at stdin.fsx (1,17--1,19) IsSynthetic=false (stdin.fsx)`

**Comment by alfonsogarciacaro** [comment]
Let's call it a step forward :wink:

**Comment by ncave** [comment]
@alfonsogarciacaro Fixed in [this](https://github.com/fable-compiler/fable-compiler.github.io/pull/10), can be closed after it's merged (see also [this](https://github.com/Microsoft/visualfsharp/pull/3575)).

**Comment by alfonsogarciacaro** [comment]
This is fantastic, thank you! Pinging @vasily-kirichenko who also reported this in Twitter.
