### ISSUE TITLE
Made with Fable

### ISSUE THREAD

**Issue by ncthbrt** [fable-compiler/Fable#1098]
### Description

Ionide is just one example of a complex application which has been "made with fable". It would be really nice to see other featured examples of fable being used seriously in the wild.

**Comment by alfonsogarciacaro** [comment]
Hi Nick! You're right, this would be a good addition to the web page. Actually, I'm working now in an update of the site to make it easier to update the docs and the sample, and this is already in my list of the things I want to add (together with logos of companies using Fable and some testimonials) 😸

**Comment by alfonsogarciacaro** [comment]
A Made with Fable section has been added to the web :)
