### ISSUE TITLE
Compilation with ${entryDir} works strange

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1101]
let inline localImage image = localImage (@"${entryDir}/../images/" + image)
    localImage "myImage.png"

compiles to

    require("../../images" + "myImage.png")

the trailing slash after images is gone.

**Comment by forki** [comment]
I found a workaround:

    let inline localImage image = localImage (@"${entryDir}/../images" + "/"  + image)
    localImage "myImage.png"

this compiles properly to

    require("../../images/myImage.png")

The interesting thing is that a) the slash is there and b) even the + get's optimized away. Which is awesome.

@dsyme ..NET version of F# compiler doesn't optimize + away if both sides are consts. Is there a reason?

**Comment by forki** [comment]
I tried to repro in a test (see https://github.com/fable-compiler/Fable/pull/1102) - but of course that was stupid since it doesn't use the fable splitter ;-)

**Comment by forki** [comment]
Is there a a solution? Can you repro?

**Comment by alfonsogarciacaro** [comment]
Sorry, I thought you'd have a look at the commit. The solution is already published ;)
