### ISSUE TITLE
Docs: Need a better version of "Interacting with JavaScript"

### ISSUE THREAD

**Issue by WilliamOckham** [fable-compiler/Fable#1106]
### Description
The documentation page on interacting with JavaScript is woefully outdated. Fortunately one of the awesome members of the Fable community has done a great job updating the information to v1. Let's ask him for permission to use his content to completely replace the official page. Or at least link to it prominently on the official page.

### Repro code

Navigate to http://fable.io/docs/interacting.html. 
Try to follow the instructions to interact with any moderately complex JavaScript library. 
Fail miserably. 
Turn to your favorite search engine. 
Find this brilliant page on Medium: https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f
Ahh, that works and it all makes sense.

### Expected and actual results

Expected: Official documentation keeps up with the pace of development on this project.
Actual: Official documentation is wrong in many places.

### Related information

* Fable version 1.1.17
* Operating system: Windows 10

**Comment by Zaid-Ajaj** [comment]
@WilliamOckham Thanks for kind words :heart: appreciate it a lot! permission granted to use the article however the community wants. You can also find great resources (other articles, libraries, etc) at [awesome-fable](https://github.com/kunjee17/awesome-fable) as well

**Comment by WilliamOckham** [comment]
The new site looks great. I'm closing this issue.
