### ISSUE TITLE
How can I setup and use fable with the new tool chain of dotnet core 2 preview ?

### ISSUE THREAD

**Issue by mrkaspa** [fable-compiler/Fable#1108]

**Comment by alfonsogarciacaro** [comment]
There should not be many differences with dotnet SDK 1, but please note we're not supporting yet the dotnet SDK 2 preview as it's not stable and there are several problems with it (though some uses have reported they successfully use Fable + dotnet SDK 2 **latest bits**, that is, the latest build you download directly from dotnet SDK repository).

**Comment by ncave** [comment]
@alfonsogarciacaro netcore 2.0 not in preview anymore.

**Comment by alfonsogarciacaro** [comment]
😮 Oh! Is that right? When dit it happen? I guess we must start converting Fable to netcore 2.0 then :wink:

**Comment by robob4him** [comment]
@alfonsogarciacaro, I actually wanted to try out fable but am halted due to the issues. As someone who literally just heard about fable for the first time there may be some confusion when the getting started steps don't work! :D

**Comment by alfonsogarciacaro** [comment]
Fable 1.2 supports dotnet SDK 2 now :tada:
