### ISSUE TITLE
Need to republish fable-splitter

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1109]
### Description

On Linux Mint (and probably others unix), if we try to use fable-splitter I got this error: 

`[1] /usr/bin/env: ‘node\r’: No such file or directory`

This is caused because the end of line used in the `cli.js` file is windows specific. (From my research).
If I convert the file using `dos2unix` then I can use fable-splitter

      
> The Dos2unix package includes utilities "dos2unix" and "unix2dos" to
>        convert plain text files in DOS or Mac format to Unix format and vice
>        versa.
> 
> In DOS/Windows text files a line break, also known as newline, is a
>        combination of two characters: a Carriage Return (CR) followed by a
>        Line Feed (LF). In Unix text files a line break is a single character:
>        the Line Feed (LF). In Mac text files, prior to Mac OS X, a line break
>        was single Carriage Return (CR) character. Nowadays Mac OS uses Unix
>        style (LF) line breaks.

I checked the version of the file in the Github repo and it's looks like to have the right end of line. I suppose it's a problem when one of you published the fable-splitter version on npm.
 @ncave @alfonsogarciacaro

**Comment by ncave** [comment]
@MangelMaxime Try it now.

**Comment by agrcrobles** [comment]
I got the same issue on `ubuntu` v16.0.4 and `fable-compiler` v0.1.7 and was fixed after updating to v0.1.9. :+1:

**Comment by MangelMaxime** [comment]
@ncave Thanks you the fix work now :)

**Comment by alfonsogarciacaro** [comment]
Argh, sorry! That hit me in the past as well, I think I published it from Windows (the git configuration commits with unix endings that's why it was correct in the repo). I need to find a way to avoid this in the future.

**Comment by alfonsogarciacaro** [comment]
@ncave Did you just bumped the version in the package.json? Would you mind pushing the change to the repo (and maybe also editing the fable-splitter RELEASE_NOTES) to avoid confusion in the future?

**Comment by alfonsogarciacaro** [comment]
@ncave Sorry, scratch that ☝️ I hadn't seen your PR 😅
