### ISSUE TITLE
List.nth

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1111]
### Description
[List.nth](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/list.nth%5B't%5D-function-%5Bfsharp%5D) cannot be parsed.

### Repro code

```fsharp
["a";"b";"c"] |> List.nth 1
```

### Expected and actual results

nth element, `"b"`

### Related information

* Fable version (`dotnet fable --version`): 1.1.7
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
Also, this construction is deprecated according to compiler warning.

> This construct is deprecated. please use List.item

So you should used something like:

```fs
["a";"b";"c"] 
|> List.item 1
```

@alfonsogarciacaro Should Fable support `List.nth` even if deprecated ?

**Comment by alfonsogarciacaro** [comment]
The method is deprecated, it doesn't appear in the autocompletion and the signature is confusing (the list is the first argument unlike most of the other List functions) so I too recommend using `List.item` instead as @MangelMaxime suggests :+1:

**Comment by nojaf** [comment]
Ok, could something be added to the fable output to tell users that `List.item` should be used?

**Comment by alfonsogarciacaro** [comment]
There should be already the warning from the F# compiler.

<img width="868" alt="screen shot 2017-08-21 at 8 19 34 am" src="https://user-images.githubusercontent.com/8275461/29505959-8243d6be-8649-11e7-9b87-5d23a280b3ea.png">

**Comment by nojaf** [comment]
Apologies, I must have misted that.
