### ISSUE TITLE
Set union of {1, 2} and {3, 4, 5} gives {2, 4, 5}

### ISSUE THREAD

**Issue by kasper-laursen** [fable-compiler/Fable#1113]
### Description

The `Set.union` fails to produce the correct union of `(Set.union (set [1; 2]) (set [3; 4; 5]))`. 

### Repro code
Create new project
```
$ mkdir foo
$ cd foo  
$ dotnet new fable
```

Edit `src/App.fs` to 
```
module foo

open Fable.Core
open Fable.Core.JsInterop
open Fable.Import

printfn "%s" ((Set.union (set [1; 2]) (set [3; 4; 5])).ToString())
```

Install dependencies, and run
```
$ dotnet restore
$ yarn install
$ dotnet fable npm-run start
```

Open the browser on http://localhost:8080/ and go to the JavaScript console.

### Expected and actual results

Expected result in console:
```
set [1; 2; 3; 4; 5]
```

Actual result in console:
```
set [2; 4; 5]
```

### Related information

* Fable version (`dotnet fable --version`): 1.0.4 (also found in version 1.1.14)
* Operating system: OS X El Capitan 10.11.6

**Comment by alfonsogarciacaro** [comment]
Ups, I wonder how this has been off the radar for so long. It'll be fixed in the next release, thanks a lot for the report!

**Comment by alfonsogarciacaro** [comment]
New version published, you should be able to get it just by running `mono .paket/paket.exe update`. Could you please check if the problem is fixed?

**Comment by kasper-laursen** [comment]
Yes, problem is fixed. Thanks.
