### ISSUE TITLE
Following "Getting started guide" - dotnet restore fails

### ISSUE THREAD

**Issue by flq** [fable-compiler/Fable#1115]
### Description

Running the instructions from http://fable.io/pages/getting-started.html , I fail at the step 

```
cd src
dotnet restore
```

with the following error:

```
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : Package dotnet-fable 1.2.0-beta-002 is not compatible with netcoreapp1.0 (.NETCoreApp,Version=v1.0). Package dotnet-fable 1.2.0-beta-002 supports: netcoreapp2.0 (.NETCoreApp,Version=v2.0) [C:\dev\own_oss\Forse\src\Forse.fsproj]
C:\Program Files\dotnet\sdk\1.0.4\NuGet.targets(97,5): error : One or more packages are incompatible with .NETCoreApp,Version=v1.0. [C:\dev\own_oss\Forse\src\Forse.fsproj]
  Restore failed in 99.57 ms for C:\dev\own_oss\Forse\src\Forse.fsproj.
```
Consequently, `dotnet-fable` is not callable

### Repro code

Not applicable

### Expected and actual results

Expected: successful completion of the "getting started"-guide

Please provide the expected and actual results.

### Related information

dotnet --version : 1.0.4
yarn --version: 0.27.5

* Fable version (`dotnet fable --version`): Not callable as it didn't get restored
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hi @flq, please note that latest template (1.2.0) requires dotnet SDK 2. We recommend updating to dotnet SDK 2 now that's officially released, but if you prefer to keep using dotnet SDK 1, you can use Fable.Template 1.1.11 instead: `dotnet new -i "Fable.Template::1.1.11"`

**Comment by flq** [comment]
I had a feeling it would have to do with that - in that case the getting started guide would need an update as following the guides for the SDK <2 path leads to this issue. Maybe replacing 

`dotnet new -i "Fable.Template::*"` with `dotnet new -i "Fable.Template::1.1.11"` would be enough?

**Comment by alfonsogarciacaro** [comment]
Now we're recommending dotnet SDK 2 for Fable so I think we can close this issue, but please feel free to reopen if there's a strong reason to keep support for dotnet SDK 1 :)
