### ISSUE TITLE
Support ability for dotnet-fable to parse *.fsproj during startup

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#1116]
Currently `dotnet-fable` will start a server that subsequently needs to be fed a `*.fsproj` file.

There are use cases where someone may want to load the proj file into the server, but they are not concerned about the output.

Some examples of this:

  - a test pre-processor where we'd like to transpile tests as needed, but the test runner is responsible for running tests in parallel.
  - A project with multiple non-overlapping directories, where someone would like to have multiple transpiled outputs while referencing a single `*.fsproj`.

We can achieve this today by sending the request to parse a fsproj file, but instead we could optionally provide the *.fsproj on the command line when invoking `dotnet fable`.

**Comment by alfonsogarciacaro** [comment]
I guess you want to do this with fable-splitter (with Webpack is not possible to control the output of individual files)? In that case, it may be easier to just add an option to fable-splitter to prevent compilation of .fsproj dependent files.

Actually, there's not much difference between loading a project and producing an output in Fable server. The daemon will just [create a fake JS file pointing to the last file in the project](https://github.com/fable-compiler/Fable/blob/616a9f3a964b3d50da50828a1fa7ed09f693f729/src/dotnet/dotnet-fable/StateUtil.fs#L187-L189) so the JS client knows what's the next request to do.

**Comment by jgrund** [comment]
> I guess you want to do this with fable-splitter (with Webpack is not possible to control the output of individual files)? 

I'm currently doing this with both a [pre-processor](https://github.com/jgrund/jest-fable-preprocessor) for [jest](http://facebook.github.io/jest/) and compiling rollup (with multiple rollup configs).

The way I'm doing it currently is to [use](https://github.com/intel-hpdd/device-scanner/blob/update-matching/package.json#L13) [a](https://github.com/intel-hpdd/device-scanner/blob/update-matching/package.json#L11) [bin script](https://github.com/jgrund/jest-fable-preprocessor/blob/master/source/send-proj-file.js) that seeds the fable server with the proj file. 
Instead of having that bin script,

**Comment by MangelMaxime** [comment]
But how would you pass option to the Fable server ? Like compilation symbol, babels options, etc.
This would need `fableconfig.json` back or something like that no ?

**Comment by jgrund** [comment]
@MangelMaxime Yes, I suppose it would. Perhaps it's worth doing that anyway so multiple tools can share the same config?

**Comment by MangelMaxime** [comment]
As `fableconfig.json` is a static file you can really share it with multiple tools. I mean, my rollups file contains some logic to include one symbol or another depending on the environment being built for example. But for simple case perhaps this would work.

**Comment by jgrund** [comment]
Sure, so many js tools allow a ```.js``` variant as well so you can do custom logic in your config, extend them in other configs.

For example, I am doing [this](https://github.com/intel-hpdd/device-scanner/blob/update-matching/IML/DeviceScannerDaemon/rollup-config.js) where I extend a base rollup config.

Actually, I wonder if the base file parsing needs the config, or just when you send  the *.fs files to be parsed later on?

**Comment by alfonsogarciacaro** [comment]
Thanks for the explanations, @jgrund. Now I understand the context much better 😄 

I've been having a look and it could be possible to add an extra argument to fable like `--load` so you can preload a project on server start. However, there may be some issues as the server wasn't designed this way. For example, how to specify compiler directives (like `DEBUG`, etc)? We could add an extra `--define` CLI argument but then it may not be clear if this is only for preloaded projects or also for projects received from JS clients (and in that case, how to solve potential conflicts with the `define` field of messages from JS clients). Error reporting would also require some work.

Actually, I think your script is a good solution. Another option I'm considering is accepting a `projLocation` field or similar from the messages of Fable JS clients (as you do in your preprocessor), so Fable can parse a file even if the .fsproj wasn't sent previously. What do you think?

**Comment by jgrund** [comment]
> Actually, I think your script is a good solution. Another option I'm considering is accepting a projLocation field or similar from the messages of Fable JS clients (as you do in your preprocessor), so Fable can parse a file even if the .fsproj wasn't sent previously. What do you think?

How would this work when:

1. A user sends the `projLocation` when compiling a file.
2. The *.proj get's a new file added or removed.
3. Another file get's sent with `projLocation`.

Would the server be able to update the project it parsed each time a file was sent?

If so, I think this would be an ideal solution for pre-processors and such that are responsible for transpiling code as they run, but still need the help of the server to do so.

**Comment by alfonsogarciacaro** [comment]
I think it should be fine in that case too :) I've just published dotnet-fable 1.2.0-beta-003 finally with the `extra.projectFile` option available (I'm using `extra` so it's not necessary to update the JS clients). Can you please give it a try and see if it fits your purposes? BTW, these are [the lines handling the projectFile option](https://github.com/fable-compiler/Fable/blob/cc657ffe6d3482ee1872ddf8dbe3464ab3364c91/src/dotnet/dotnet-fable/StateUtil.fs#L122-L128), it just replaces normal project file location :+1:

**Comment by jgrund** [comment]
Thanks for implementing that so quickly. Just tried it out and looks like I can drop the bin script :).
