### ISSUE TITLE
IDictionary.Clear calls wrong method

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#1120]
Consider:

```
open Fable.Core
open Fable.Import.JS
open System.Collections.Generic
open Fable.Core.JsInterop

let private deviceMap:IDictionary<string, string> = dict[]

deviceMap.Clear()
```

this compiles to:

```
import List from "fable-core/List";
const deviceMap = new Map(new List());
deviceMap.splice(0);
```

JS `Map` does not have a `splice` method. Instead we should call [`clear`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Map/clear).

**Comment by alfonsogarciacaro** [comment]
Unfortunately, it was `ICollection.Clear` being called so I had to add a runtime check to see if the collection is an array or a Map/Set. It'll be fixed in next Fable 1.2 beta release :+1:
