### ISSUE TITLE
Generic type alias causing edge case issue with curried lambda optimisation

### ISSUE THREAD

**Issue by IanJCoombs** [fable-compiler/Fable#1121]
### Description

A function which takes a function parameter typed using a generic type alias doesn't seem to apply the uncurrying optimisation. 

### Repro code

We hit this when trying to write a State computation builder using the type alias:

```
type State<'TState, 'a> = 'TState -> ('a * 'TState)
```

Here's a simpler repro we found with `bind` for the string environment monad. The only difference between the following two test cases is that the first uses a type alias whereas the second doesn't. The first test fails with the error `TypeError: f(...) is not a function.`. The second test runs successfully.

```
type StringEnvironment<'a> = string -> 'a

[<Test>]
let ``failing test`` () : unit =
    let zero = fun _ -> ()

    let bind (x : StringEnvironment<'a>) (f : 'a -> StringEnvironment<'b>) : StringEnvironment<'b> =
        fun environment ->
            f (x environment) environment

    bind zero (fun () -> zero) "environment"


[<Test>]
let ``passing test`` () : unit =
    let zero = fun _ -> ()

    let bind (x : string -> 'a) (f : 'a -> string -> 'b) : string -> 'b =
        fun environment ->
            f (x environment) environment

    bind zero (fun () -> zero) "environment"
```

Here is Fable's output JS of these tests. 
In the failing test the call to `f` assumes `f` is curried whereas in the passing test it assumes it's uncurried.

```
    it("failing test", function () {
        var zero = function zero(_arg1) {};

        var bind = function bind(x, f, environment) {
            return f(x(environment))(environment);
        };

        bind(zero, Object(__WEBPACK_IMPORTED_MODULE_9__packages_fable_Fable_Core_fable_core_CurriedLambda__["a" /* default */])(function () {
            return zero;
        }), "environment");
    });

    it("passing test", function () {
        var zero = function zero(_arg1) {};

        var bind = function bind(x, f, environment) {
            return f(x(environment), environment);
        };

        bind(zero, Object(__WEBPACK_IMPORTED_MODULE_9__packages_fable_Fable_Core_fable_core_CurriedLambda__["a" /* default */])(function () {
            return zero;
        }), "environment");
    });
```

### Related information

* Fable version (`dotnet fable --version`): 1.2.0-beta-002 (but same issue right back to 1.1.7 it seems)
* Operating system: Windows 10 -x64

**Comment by alfonsogarciacaro** [comment]
Good catch, thank you! I guess Fable is being deceived by the type alias and doesn't calculate the number of parameters correctly. I'll have a look, thanks!

**Comment by IanJCoombs** [comment]
Oh wow! Such a fast turn around! Thank you @alfonsogarciacaro
