### ISSUE TITLE
unit option hack doesn't work with generic functions

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#1135]
### Description

It seems like in certain scenarios `(Some ()).IsNone` is actually true (kind of).
I've tested this particular expression and it is `false` but when logic gets a little bit more complicated it becomes `true` (as I said: kind of, see example).
I guess the problem is cause by combination of erased `Option` and `unit` as `()` is kind of `null` therefore erased `Some ()` looks like `None`.

On a side, shouldn't `unit` value be `(void 0)`, fits slightly better.

### Repro code

As there is no tail recursion I wrote myself a trampoline:

```
module Trampoline =
    type Result<'a, 'b> = 
        | Continue of 'a 
        | Break of 'b
    let run func arg = 
        let mutable state = arg
        let mutable result = None
        while result.IsNone do
            match func state with
            | Continue r -> state <- r
            | Break r -> result <- Some r
        result.Value
```

(Note, I know I can rewrite it without Option, I just think it is worth addressing anyway).

I used three different scenarios to test it:

```
Trampoline.run (fun _ -> Trampoline.Break "hello") () |> printfn "%A"
Trampoline.run (fun _ -> Trampoline.Break 42) () |> printfn "%A"
Trampoline.run (fun _ -> Trampoline.Break ()) () |> printfn "%A"
```

### Expected results

prints `"hello"`, `42` and `()` (`null`, `unassigned`, `{}`, etc)

### Actual results

prints `"hello"`, `42` and... spins forever.

### Related information

* Fable version (`dotnet fable --version`): 1.1.20
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
This is an unfortunate consequence of the combined facts that Fable erases options, and that it doesn't make a distinction among `None`, `unit`, `null` or JS `undefined`. Actually, I just made [`Some ()` translate as JS `{}`](https://github.com/fable-compiler/Fable/blob/1763660ec1312038db11dee213853bb20ab90494/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L146-L148) as I quick hack to make active patterns work. But this can be improved for sure, I'll have a look. Thanks a lot for the code to reproduce the problem!

About using `void 0` (aka `undefined`) to translate F# `unit`, right now Fable AST has no special entry for it, so it just translates `unit` as `Null`. In fact, in the F# AST, the last expression of functions returning `unit` is a `null`. Fable just deletes these when sending them to JS for optimization.

**Comment by alfonsogarciacaro** [comment]
Ups, wrong issue number, reopening...
