### ISSUE TITLE
Side effects executed twice on [| ... |] |> Array.map

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#1140]
### Description

Seems like code generated by array initialization may executed side effects twice, when followed by `Array.map` (possibly others)

When array initialization is: `[| a (); b (); c () |] |> Array.map id` I would expect each of those function executed once. Unfortunately, Fable generates something like: `new Int32Array([a(), b(), c()]), new Array(new Int32Array([a(), b(), c()]).length)))`

NOTE: each of a, b and c are executed twice
NOTE: problem disappears when using temporary variable

### Repro code

```
let mutable c = 0
let i () = c <- c + 1; c
[| i (); i (); i () |] |> Array.map string |> ignore
printfn "c: %d" c
```

### Expected results

```
c: 3
```

### Actual results

```
c: 6
```

### Related information

* Fable version (`dotnet fable --version`): 1.1.20
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
Ah, damn! We made a pass to the replacements module to make sure there were not inline functions repeating an argument twice, but I modified this one recently and forgot about that, sorry! 😅 

Thanks for the report, it'll be fixed in next release :+1:
