### ISSUE TITLE
Rollup plugin doesn't generate source maps

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#1141]
### Description

When using the Rollup plugin, Rollup generates a warning about broken source maps. The [condition][condition] in the plugin seems to be incorrect, when I change it to `if (true)`, the warning described below disappears. The [Rollup wiki][wiki] says that plugins that transform source code should generate source maps automatically, so I wonder if we should remove the condition altogether.

  [condition]: https://github.com/fable-compiler/Fable/blob/542a34c379eb41577b53df72d1dc557703a50bdb/src/js/rollup-plugin-fable/index.js#L100 
  [wiki]: https://github.com/rollup/rollup/wiki/Plugins#conventions

### Repro code

Clone my [VS Code extension sample repo][repo], restore the packages and build it with `dotnet fable yarn-run build`.

  [repo]: https://github.com/inosik/fable-vscode-rollup-sample

### Expected and actual results

```
(!) Broken sourcemap
https://github.com/rollup/rollup/wiki/Troubleshooting#sourcemap-is-likely-to-be-incorrect
Plugins that transform code (such as 'fable') should generate accompanying sourcemaps
```

### Related information

* Fable version (`dotnet fable --version`): 1.2.0
* Rollup plugin version: 1.1.0

**Comment by alfonsogarciacaro** [comment]
You're right, probably it's a good idea to remove the condition for the Rollup plugin, could you please send a PR? Thanks a lot in advance!

**Comment by inosik** [comment]
See #1142.

**Comment by alfonsogarciacaro** [comment]
rollup-plugin-fable 1.1.1 published :+1:

**Comment by inosik** [comment]
Yes, I already updated my packages and the warning is gone. Thanks!
