### ISSUE TITLE
Seq.cache is not implemented

### ISSUE THREAD

**Issue by johngalambos** [fable-compiler/Fable#1143]
### Description

It doesn't look like Seq.cache is implemented.  When attempting to use Seq.cache, the following warning is shown when compiling:
`WARNING in ./src/App.fs
3:6-11 "export 'cache' was not found in '../../../../.nuget/packages/fable.core/1.2.0/fable-core/Seq'`

### Repro code
`     { 1 .. 10}
      |> Seq.cache
      |> ignore `

### Expected and actual results

There is one reference to the function in a  disabled unit test:
https://github.com/fable-compiler/Fable/blob/f6555e62c7e38ada8be985b46a86b70609c77bd4/tests/Main/SeqTests.fs#L585-L595
 
I believe this test should be written as:

```
 let ``Seq.cache works``() = 
     let count = ref 0 
     let xs = 
        1 |> Seq.unfold(fun i -> 
           count := !count + 1 
           if i <= 10 then Some(i, i+1) 
           else None)
           |> Seq.cache
     xs |> Seq.length |> ignore 
     xs |> Seq.length |> ignore 
     !count 
     |> equal 11 
```
### Related information

* Fable version 1.2.0
* Operating system: Windows 10

Thanks for the fantastic project!

**Comment by alfonsogarciacaro** [comment]
Good catch, thank you! ⚾️ Also thank you for the kind words ❤️ I've implemented the missing function by just transforming the iterable into an array. Until the next release you can just use `Seq.toArray` with the same effect, sorry for the inconvenience!
