### ISSUE TITLE
Watch mode for REPL

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1147]
Instead of the "COMPILE" button we should use a watch mode ;-)

/cc @ncave

**Comment by alfonsogarciacaro** [comment]
A watch mode for every change may be a bit too much, especially for big scripts. We probably should allow a shortcut like Ctrl+Enter, but I like the button distracts the user a bit about the compile times ;)

**Comment by ncave** [comment]
@forki It was there in the beginning, but it was intentionally taken out. As @alfonsogarciacaro says, the compile times are still not where they need to be for a watch mode to work without irritating the user.

**Comment by forki** [comment]
Thanks
