### ISSUE TITLE
A recursive loop sometimes doesn't work

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#1150]
### Description

I have hit a problem with some real world code so sorry about the repro code but it's the closest I could make that breaks.  It seems to be `current.parentElement` is the problem.  Changing it to just `current` works.

### Repro code

Using the Repl

``` F#
open Fable.Import
open Fable.Core
open Fable.Core.JsInterop

[<Emit("document.body.children[0].children[0]")>]
let getElementsByClassName () : Browser.Element = jsNative

let resize () =
  let rec loop (current : Browser.Element) count width height = 
    printfn "starting loop"

    let w = if count = 1 then current.clientWidth else width
    let h = if count = 1 then current.clientHeight else height

    if w > 0. && h > 0. then
      printfn "found"
      w, h
    else
      printfn "not found... looping"
      let a = loop current.parentElement (count+1) w h // This should loop but it doesn't!
      Browser.console.log("What is this?", a)
      a
  
  let element = getElementsByClassName ()
  let result = loop element 0 0. 0.
  
  printfn "Result = %A" result
    
resize()     
```

### Results

"starting loop"
"not found... looping"
"What is this?" [Function anonymous] <-- This should not be a function
"Result = undefined" <-- the end result is wrong

### Related information

* Fable version: from the Repl: Fable v1.2.0, FCS v14.0.2, Babel v6.26.0

**Comment by davidtme** [comment]
In fact changing `Browser.Element` to `Browser.HTMLElement` also works (which is what `parentElement` is).  Odd that the compiler isn't error on this?

Still would like to know why this `Function anonymous` is creeping in. Could this an underlying problem?

**Comment by alfonsogarciacaro** [comment]
This is really weird if you put the code above in the REPL you get a lot of closures generated by the F# compiler:

```fsharp
      const a = function (arg00) {
        const clo1 = ($var1, $var2, $var3) => {
          return loop(arg00, $var1, $var2, $var3);
        };

        return function (arg10) {
          const clo2 = ($var4, $var5) => {
            return clo1(arg10, $var4, $var5);
          };

          return function (arg20) {
            const clo3 = $var6 => {
              return clo2(arg20, $var6);
            };

            return function (arg30) {
              return clo3(arg30);
            };
          };
        };
      }(current.parentElement)(count + 1, w, h);
```

This happens sometimes and I'm not sure why. Seems to be an issue with the signature of `parentElement` because, as you say, when you change it to `HTMLElement` the closures disappear:

```fsharp
const a = loop(current.parentElement, count + 1, w, h);
```

I need to investigate this... 😕

**Comment by davidtme** [comment]
@alfonsogarciacaro As always many thanks.

**Comment by alfonsogarciacaro** [comment]
Weird, GH didn't add a link to the relevant commit. Here it is: https://github.com/fable-compiler/Fable/commit/176d132bff72ad75e6f5c3853f100740e191220e

I will push a new version today. Your sample should already work in the REPL :)
