### ISSUE TITLE
Regex.Replace not replacing characters

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#1155]
### Description

Seems like `Regex.Replace` has some issues.

### Repro code

```fsharp
open System.Text.RegularExpressions
let s = Regex.Replace("1234567890", ".{2}", "$0-")
printfn "%s" s
// $0-$0-$0-$0-$0-
```

### Expected and actual results

> open System.Text.RegularExpressions;;
> Regex.Replace("1234567890", ".{2}", "$0-");;
val it : string = "12-34-56-78-90-"
> 

### Related information

* Fable version (`dotnet fable --version`): Fable v1.2.0, FCS v14.0.2, Babel v6.26.0
* Operating system: ???
* Can be reproduced on the fable REPL: http://fable.io/repl/#?code=open%20System.Text.RegularExpressions%0D%0Alet%20s%20%3D%20Regex.Replace(%221234567890%22%2C%20%22.%7B2%7D%22%2C%20%22%240-%22)%0D%0Aprintfn%20%22%25s%22%20s%0D%0A&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2

**Comment by alfonsogarciacaro** [comment]
Good catch! Interesting, I didn't know [`$0` doesn't work as replace placeholder with JS Regex](https://stackoverflow.com/a/4002341/3922220)
