### ISSUE TITLE
Server Response message not part of Exception

### ISSUE THREAD

**Issue by sandeepc24** [fable-compiler/Fable#1164]
### Description

When making a Http call to Suave server the exception does not contain response message. 

### Repro code

Using Fable-Suave add following to a get function in Suave project.
```
return! RequestErrors.NOT_ACCEPTABLE "Sample error message." ctx
```

Call it from Fable app and the exception does not contain response body. Sample code
```
let update (msg:WishListMsg) model : WishListVM*Cmd<WishListMsg> = 
    match msg with
    | FetchError ex -> Browser.console.info ex.Message
```

### Expected and actual results

The exception IMO should also contain the response body text.

### Related information

* Fable version (`dotnet fable --version`): This command didn't work, but I know I am on latest version of Fable.
* Operating system: Windows 10

**Comment by inosik** [comment]
You have to implement this yourself, because the `fetch` API doesn't do this. 

You could modify the [current code][code] to something like this:

``` fsharp
let fetch (url: string) (init: RequestProperties list) : Promise<Response> =
  GlobalFetch.fetch(RequestInfo.Url url, requestProps init)
  |> Fable.PowerPack.Promise.bind (fun response ->
    if response.Ok then
      Fable.PowerPack.Promise.lift response
    else
      response.text ()
      |> Fable.PowerPack.Promise.map failwith)
```

  [code]: https://github.com/fable-compiler/fable-powerpack/blob/3481e59f9cfd111e5b0c32561545f6f79e5bb331/src/Fetch.fs#L345-L353

**Comment by sandeepc24** [comment]
I tried using this, but I do not get the body text. Could someone please look into this.

**Comment by alfonsogarciacaro** [comment]
Can you please link to your current code @sandeepc24? It looks as if `response.text()` were run twice.

BTW, this is probably not related to Fable compiler itself. If necessary it should be fixed in [Fable.PowerPack](https://github.com/fable-compiler/fable-powerpack) repo.
