### ISSUE TITLE
ran `dotnet fable npm-start` and got `Invalid configuration object.` webpack-dev-server error

### ISSUE THREAD

**Issue by BryanWilhite** [fable-compiler/Fable#1166]
### Description

From the `src/` folder I ran `dotnet fable npm-start` from PowerShell, following the [Getting Started](http://fable.io/docs/getting-started.html) guide ([my stuff is on GitHub](https://github.com/BryanWilhite/dotnet-core/tree/master/dotnet-fable-minimal)).

```ps1
PS ..\dotnet-core\dotnet-fable-minimal\src> dotnet fable npm-start
Fable (1.2.3) daemon started on port 61225
CWD: ..\dotnet-core\dotnet-fable-minimal
cmd /C npm run start

> @ start ..\dotnet-core\dotnet-fable-minimal
> webpack-dev-server

Bundling for development...
Invalid configuration object. webpack-dev-server has been initialised using a configuration object that does not match the API schema.
 - configuration has an unknown property 'error'. These properties are valid:
   object { hot?, hotOnly?, lazy?, bonjour?, host?, allowedHosts?, filename?, publicPath?, port?, socket?, watchOptions?, headers?, clientLogLevel?, overlay?, progress?, key?, cert?, ca?, pfx?, pfxPassphrase?, requestCert?, inline?, disableHostCheck?, public?, https?, contentBase?, watchContentBase?, open?, useLocalIp?, openPage?, features?, compress?, proxy?, historyApiFallback?, staticOptions?, setup?, stats?, reporter?, noInfo?, quiet?, serverSideRender?, index?, log?, warn? }
```

![image](https://user-images.githubusercontent.com/5226627/30885895-e68f86da-a2c9-11e7-9b39-e18dd676d285.png)

### Environment

Globally, I have installed `webpack` and `webpack-dev-server` (in that order) and updated npm to 5.4.2. Locally I ran `npm install` and `dotnet restore` according to the instructions.

* Fable version (`dotnet fable --version`): 1.2.3
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hmm, not sure exactly. But maybe the webpack and webpack-dev-server global installations are causing problems. You shouldn't need it because these tools are already installed locally. In fact, it's not recommended to install webpack globally so you can use different versions for other projects.

Can you uninstall the global versions and try again? `npm un -g webpack webpack-dev-server`

**Comment by BryanWilhite** [comment]
Okay. Will try it again soon. Glad to hear that using `npm` is not discouraged. Not quite ready for `yarn`.

**Comment by BryanWilhite** [comment]
Okay this issue is resolved: no global `webpack` packages.

Detailed [notes](https://github.com/BryanWilhite/dotnet-core/tree/master/dotnet-fable-minimal) available.
