### ISSUE TITLE
Async throws error in repl

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/Fable#1170]
http://fable.io/repl/#?code=open%20System%0Aopen%20Fable.Core%0A%0Alet%20mutable%20result%20%3D%200%0Aasync%20%7B%0A%20%20%20%20while%20result%20%3C%2010%20do%0A%20%20%20%20%20%20%20%20result%20%3C-%20result%20%2B%201%0A%7D%20%7C%3E%20Async.StartImmediate%0A

The code are copied from test folder, but got an error:

```sh
stdin.fsx(1,0): (1,0) error FSHARP: internal error: Converting circular structure to JSON
```

**Comment by alfonsogarciacaro** [comment]
Indeed, this shouldn't happen with Fable CLI. This is interesting, the error seems to be raised [on this line](https://github.com/fable-compiler/fable-compiler.github.io/blob/644d36ee3e2c856e7306a686a781163d1d4369a9/public/repl/worker.js#L85) but I don't know why the F# compiler is doing any JSON serialization, this should happen later. Do you have any idea @ncave?

BTW, the error disappears when removing `Async.StartImmediate` (copying the code below for convenience).

```fsharp
open System
open Fable.Core

let mutable result = 0
async {
    while result < 10 do
        result <- result + 1
} |> Async.StartImmediate
```

**Comment by ncave** [comment]
See #1172.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the fix, @ncave! I'll update the REPL :+1:
