### ISSUE TITLE
Repl doesn't contain builtin Result type

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/Fable#1173]
[repl link](http://fable.io/repl/#?code=open%20FSharp.Reflection%0Aopen%20FSharp.Core%0Aopen%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Atype%20Result%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20%7C%20Ok%20of%20'T%0A%20%20%20%20%7C%20Error%20of%20'TError%0A%0Atype%20Validator%3C'T%2C%20'TError%3E%20%3D%20'T%20-%3E%20Result%3C'T%2C%20'TError%20list%3E%0Atype%20ValidatorCombinator%3C'T%2C%20'TError%3E%20%3D%20Validator%3C'T%2C%20'TError%3E%20-%3E%20Validator%3C'T%2C%20'TError%3E%0A%0Alet%20inline%20ifInvalid%3C'T%2C%20'TError%3E%20test%20(error%3A%20'TError)%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%3A%20Validator%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20let%20validator'%20(input%3A%20'T)%20%3D%0A%20%20%20%20%20%20%20%20let%20lastResult%20%3D%20validator%20input%0A%20%20%20%20%20%20%20%20match%20lastResult%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Error%20(error%3A%3Aerrors)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20errors%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20input%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Ok%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20%5Berror%5D%0A%20%20%20%20in%0A%20%20%20%20%20%20%20%20validator'%0A%0Alet%20ifBlank%3C'TError%3E%20%3D%0A%20%20ifInvalid%3Cstring%2C%20'TError%3E%20String.IsNullOrWhiteSpace%0A%0Alet%20ifNotGt%20min%20%3D%0A%20%20ifInvalid%20(fun%20input%20-%3E%20input%20%3E%20min)%0A%0Atype%20A%20%3D%0A%20%20%20%20%7C%20Name%0A%20%20%20%20%7C%20Value%0A%0Alet%20any%3A%20obj%20%3D%20Object()%0A%0Alet%20all%3C'T%2C%20'TError%2C%20'L%20when%20'L%20%3A%20comparison%3E%0A%20%20%20%20(rules%3A%20'T%20-%3E%20('L%20*%20Validator%3C%23obj%2C%20'TError%3E)%20list)%0A%20%20%20%20input%20%3D%0A%20%20%20%20%20%20%20%20let%20mutable%20msgMap%20%3D%20Map%3C'L%2C%20'TError%20list%3E%20Seq.empty%0A%20%20%20%20%20%20%20%20rules%20input%20%7C%3E%20List.iter%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20fun%20(key%2C%20validator)%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20match%20(validator%20any)%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20_%20-%3E%20()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(msgMap%20%3C-%20Map.add%20key%20errors%20msgMap))%0A%20%20%20%20%20%20%20%20if%20Map.count%20msgMap%20%3C%3E%200%20then%0A%20%20%20%20%20%20%20%20%20%20%20%20Error%20msgMap%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20Ok%20input%0Alet%20inline%20test%20input%20inp%20%3D%20Ok(input)%0A%0Alet%20inline%20endTest%3C'T%2C%20'TError%3E%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%20%3D%20((validator%20%3A%3E%20obj)%20%3A%3F%3E%20Validator%3Cobj%2C%20'TError%3E)%0A%0Alet%20ret%20%3D%20test%20%22%22%20%7C%3E%20ifBlank%20%22%22%20%7C%3E%20ifBlank%20%22%22%0A%0Atype%20People%20%3D%20%7B%0A%20%20%20%20name%3A%20string%0A%20%20%20%20age%3A%20int%0A%7D%0A%0Amodule%20A%20%3D%0A%20%20%20%20let%20aa%20%3D%201%0A%0A%0Alet%20a%20f%20m%20%3D%20f%20m%0Alet%20b%20f%20m%20%3D%20f%20%3C%3C%20m%0A%0Alet%20result%20%3D%0A%20%20%20%20all%20(fun%20t%20-%3E%0A%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22name%22%2C%20test%20t.name%20%7C%3E%20ifBlank%20%22Name%20shouldn't%20be%20empty%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22age%22%2C%20test%20t.age%20%7C%3E%20ifNotGt%2018%20%22Age%20should%20greater%20then%2018%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%5D)%20%7Bname%20%3D%20%22%22%3B%20age%20%3D%2015%7D%0A%0A%0A)

And if I added manually, it raised strange error: [repl link](http://fable.io/repl/#?code=open%20FSharp.Reflection%0Aopen%20FSharp.Core%0Aopen%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Atype%20Result%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20%7C%20Ok%20of%20'T%0A%20%20%20%20%7C%20Error%20of%20'TError%0A%0Atype%20Validator%3C'T%2C%20'TError%3E%20%3D%20'T%20-%3E%20Result%3C'T%2C%20'TError%20list%3E%0Atype%20ValidatorCombinator%3C'T%2C%20'TError%3E%20%3D%20Validator%3C'T%2C%20'TError%3E%20-%3E%20Validator%3C'T%2C%20'TError%3E%0A%0Alet%20inline%20ifInvalid%3C'T%2C%20'TError%3E%20test%20(error%3A%20'TError)%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%3A%20Validator%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20let%20validator'%20(input%3A%20'T)%20%3D%0A%20%20%20%20%20%20%20%20let%20lastResult%20%3D%20validator%20input%0A%20%20%20%20%20%20%20%20match%20lastResult%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Error%20(error%3A%3Aerrors)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20errors%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20input%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Ok%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20%5Berror%5D%0A%20%20%20%20in%0A%20%20%20%20%20%20%20%20validator'%0A%0Alet%20ifBlank%3C'TError%3E%20%3D%0A%20%20ifInvalid%3Cstring%2C%20'TError%3E%20String.IsNullOrWhiteSpace%0A%0Alet%20ifNotGt%20min%20%3D%0A%20%20ifInvalid%20(fun%20input%20-%3E%20input%20%3E%20min)%0A%0Atype%20A%20%3D%0A%20%20%20%20%7C%20Name%0A%20%20%20%20%7C%20Value%0A%0Alet%20any%3A%20obj%20%3D%20Object()%0A%0Alet%20all%3C'T%2C%20'TError%2C%20'L%20when%20'L%20%3A%20comparison%3E%0A%20%20%20%20(rules%3A%20'T%20-%3E%20('L%20*%20Validator%3C%23obj%2C%20'TError%3E)%20list)%0A%20%20%20%20input%20%3D%0A%20%20%20%20%20%20%20%20let%20mutable%20msgMap%20%3D%20Map%3C'L%2C%20'TError%20list%3E%20Seq.empty%0A%20%20%20%20%20%20%20%20rules%20input%20%7C%3E%20List.iter%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20fun%20(key%2C%20validator)%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20match%20(validator%20any)%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20_%20-%3E%20()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(msgMap%20%3C-%20Map.add%20key%20errors%20msgMap))%0A%20%20%20%20%20%20%20%20if%20Map.count%20msgMap%20%3C%3E%200%20then%0A%20%20%20%20%20%20%20%20%20%20%20%20Error%20msgMap%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20Ok%20input%0Alet%20inline%20test%20input%20inp%20%3D%20Ok(input)%0A%0Alet%20inline%20endTest%3C'T%2C%20'TError%3E%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%20%3D%20((validator%20%3A%3E%20obj)%20%3A%3F%3E%20Validator%3Cobj%2C%20'TError%3E)%0A%0Alet%20ret%20%3D%20test%20%22%22%20%7C%3E%20ifBlank%20%22%22%20%7C%3E%20ifBlank%20%22%22%0A%0Atype%20People%20%3D%20%7B%0A%20%20%20%20name%3A%20string%0A%20%20%20%20age%3A%20int%0A%7D%0A%0Amodule%20A%20%3D%0A%20%20%20%20let%20aa%20%3D%201%0A%0A%0Alet%20a%20f%20m%20%3D%20f%20m%0Alet%20b%20f%20m%20%3D%20f%20%3C%3C%20m%0A%0Alet%20result%20%3D%0A%20%20%20%20all%20(fun%20t%20-%3E%0A%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22name%22%2C%20test%20t.name%20%7C%3E%20ifBlank%20%22Name%20shouldn't%20be%20empty%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22age%22%2C%20test%20t.age%20%7C%3E%20ifNotGt%2018%20%22Age%20should%20greater%20then%2018%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%5D)%20%7Bname%20%3D%20%22%22%3B%20age%20%3D%2015%7D%0A%0A%0A)

**Comment by alfonsogarciacaro** [comment]
Ups, probably we're using an old FSharp.Core assembly which doesn't contain the new Result type. @ncave What was the way again to generate the assemblies only with metadata, if I take a normal FSharp.Core build (for .NET framework) is too big: around 2.5MB vs 804KB for the current one being used in the REPL.

**Comment by ncave** [comment]
@alfonsogarciacaro It's not 800k, more like 1.32 MB (still needs the sigdata), but I get your point. Let me see if I can rebase the export branch to the current FCS so it can be used again, as there have been quite a lot of changes in FCS.

**Comment by alfonsogarciacaro** [comment]
That'd be awesome, @ncave, thank you! BTW, @zaaack you should be able to use the custom `Result`. It seems the FSharp.Core used in the REPL is also missing `Map.count`, if you replace L55 with `if msgMap.Count <> 0 then` [it works](http://fable.io/repl/#?code=open%20FSharp.Reflection%0Aopen%20FSharp.Core%0Aopen%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Aopen%20System%0Aopen%20System.Text.RegularExpressions%0A%0Atype%20Result%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20%7C%20Ok%20of%20'T%0A%20%20%20%20%7C%20Error%20of%20'TError%0A%0Atype%20Validator%3C'T%2C%20'TError%3E%20%3D%20'T%20-%3E%20Result%3C'T%2C%20'TError%20list%3E%0Atype%20ValidatorCombinator%3C'T%2C%20'TError%3E%20%3D%20Validator%3C'T%2C%20'TError%3E%20-%3E%20Validator%3C'T%2C%20'TError%3E%0A%0Alet%20inline%20ifInvalid%3C'T%2C%20'TError%3E%20test%20(error%3A%20'TError)%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%3A%20Validator%3C'T%2C%20'TError%3E%20%3D%0A%20%20%20%20let%20validator'%20(input%3A%20'T)%20%3D%0A%20%20%20%20%20%20%20%20let%20lastResult%20%3D%20validator%20input%0A%20%20%20%20%20%20%20%20match%20lastResult%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Error%20(error%3A%3Aerrors)%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20errors%0A%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20input%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20if%20test%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20then%20Ok%20input%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20else%20Error%20%5Berror%5D%0A%20%20%20%20in%0A%20%20%20%20%20%20%20%20validator'%0A%0Alet%20ifBlank%3C'TError%3E%20%3D%0A%20%20ifInvalid%3Cstring%2C%20'TError%3E%20String.IsNullOrWhiteSpace%0A%0Alet%20ifNotGt%20min%20%3D%0A%20%20ifInvalid%20(fun%20input%20-%3E%20input%20%3E%20min)%0A%0Atype%20A%20%3D%0A%20%20%20%20%7C%20Name%0A%20%20%20%20%7C%20Value%0A%0Alet%20any%3A%20obj%20%3D%20Object()%0A%0Alet%20all%3C'T%2C%20'TError%2C%20'L%20when%20'L%20%3A%20comparison%3E%0A%20%20%20%20(rules%3A%20'T%20-%3E%20('L%20*%20Validator%3C%23obj%2C%20'TError%3E)%20list)%0A%20%20%20%20input%20%3D%0A%20%20%20%20%20%20%20%20let%20mutable%20msgMap%20%3D%20Map%3C'L%2C%20'TError%20list%3E%20Seq.empty%0A%20%20%20%20%20%20%20%20rules%20input%20%7C%3E%20List.iter%20(%0A%20%20%20%20%20%20%20%20%20%20%20%20fun%20(key%2C%20validator)%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20match%20(validator%20any)%20with%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Ok%20_%20-%3E%20()%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%7C%20Error%20errors%20-%3E%0A%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20%20(msgMap%20%3C-%20Map.add%20key%20errors%20msgMap))%0A%20%20%20%20%20%20%20%20if%20msgMap.Count%20%3C%3E%200%20then%0A%20%20%20%20%20%20%20%20%20%20%20%20Error%20msgMap%0A%20%20%20%20%20%20%20%20else%0A%20%20%20%20%20%20%20%20%20%20%20%20Ok%20input%0Alet%20inline%20test%20input%20inp%20%3D%20Ok(input)%0A%0Alet%20inline%20endTest%3C'T%2C%20'TError%3E%20(validator%3A%20Validator%3C'T%2C%20'TError%3E)%20%3D%20((validator%20%3A%3E%20obj)%20%3A%3F%3E%20Validator%3Cobj%2C%20'TError%3E)%0A%0Alet%20ret%20%3D%20test%20%22%22%20%7C%3E%20ifBlank%20%22%22%20%7C%3E%20ifBlank%20%22%22%0A%0Atype%20People%20%3D%20%7B%0A%20%20%20%20name%3A%20string%0A%20%20%20%20age%3A%20int%0A%7D%0A%0Amodule%20A%20%3D%0A%20%20%20%20let%20aa%20%3D%201%0A%0A%0Alet%20a%20f%20m%20%3D%20f%20m%0Alet%20b%20f%20m%20%3D%20f%20%3C%3C%20m%0A%0Alet%20result%20%3D%0A%20%20%20%20all%20(fun%20t%20-%3E%0A%20%20%20%20%20%20%20%20%5B%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22name%22%2C%20test%20t.name%20%7C%3E%20ifBlank%20%22Name%20shouldn't%20be%20empty%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%20%20%20%20(%22age%22%2C%20test%20t.age%20%7C%3E%20ifNotGt%2018%20%22Age%20should%20greater%20then%2018%22%20%7C%3E%20endTest)%0A%20%20%20%20%20%20%20%20%5D)%20%7Bname%20%3D%20%22%22%3B%20age%20%3D%2015%7D%0A%0A%0A&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2).

**Comment by ncave** [comment]
@alfonsogarciacaro Export and netcore 2.0 metadata support added, see repl [issue 2](https://github.com/fable-compiler/fable-repl/issues/2#issuecomment-334367505).

**Comment by alfonsogarciacaro** [comment]
This is working now :)
