### ISSUE TITLE
Is it possible to emit an error when RegexOptions.Singleline is used?

### ISSUE THREAD

**Issue by ovatsus** [fable-compiler/Fable#1181]
Is it possible to emit an error when RegexOptions.Singleline is used? JavaScript doesn't have an equivalent, and it's easy to forget that causing very hard to debug bugs

**Comment by alfonsogarciacaro** [comment]
Done! In the next version when you use a non-compatible RegexOptions you'll get the following warning:

```
WARNING in ./QuickTest.fs
C:/Users/Alfonso/dev/Fable/src/tools/QuickTest.fs(33,23): (33,44) warning FABLE: Multiline and IgnoreCase are the only RegexOptions available
```

Would that be enough? Would you prefer an error instead?

**Comment by ovatsus** [comment]
I would prefer an error, but a warning is fine as well. Thanks!
