### ISSUE TITLE
Incorrect handling of String.Join when the argument is a string array

### ISSUE THREAD

**Issue by object** [fable-compiler/Fable#1182]
### Description

String.Join(",", [|"ab"|]) results in a string "a,b"

### Repro code

String.Join(",", [|"ab"|])

### Expected and actual results

It should produce a string "ab". It actually does if I use a list instead of an array:
String.Join(",", ["ab"]) results in a string "a,b"

### Related information

* Fable version 1.2.4
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Good catch, thank you! ⚾️
