### ISSUE TITLE
Fable 1.2.4 broke importMember function

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#1185]
### Description

I updated my [VSCode extension sample][sample] to Fable 1.2.4 from 1.2.3 and this broke the `importMember` function. If I change my code to use the `import` function or the `Import`-Attribute it works.

  [sample]: https://github.com/inosik/fable-vscode-rollup-sample

### Repro code

Clone the repository from above and checkout the `fable-broken-import-member` branch. Then follow the instructions from the readme.

### Expected and actual results

This is what I get:

``` shell
./src/wordcount.fsproj → ./out/extension.js...
fable: Compiled src\wordcount.fsproj
[!] (fable plugin) Error: D:/projects/experiments/fable/vscode-rollup-sample/src/extension.fs(1,1): error FABLE: `importMember` must be assigned to a variable
 Make sure Fable server is running on port 61225
src\extension.fs
Error: D:/projects/experiments/fable/vscode-rollup-sample/src/extension.fs(1,1): error FABLE: `importMember` must be assigned to a variable
 Make sure Fable server is running on port 61225
    at error (D:\projects\experiments\fable\vscode-rollup-sample\node_modules\rollup\dist\rollup.js:185:14)
    at Promise.resolve.then.catch.err (D:\projects\experiments\fable\vscode-rollup-sample\node_modules\rollup\dist\rollup.js:9182:6)
```

### Related information

* Fable version (`dotnet fable --version`): 1.2.4
* Operating system: Windows 7 x64

**Comment by inosik** [comment]
I just tried to import a string with `importMember`, and it worked. Looks like importing (curried?) functions is broken.

**Comment by inosik** [comment]
> Looks like importing (curried?) functions is broken.

Doing this change makes it work again:

``` diff
diff --git a/src/extension.fs b/src/extension.fs
index d532c07..eff85ce 100644
--- a/src/extension.fs
+++ b/src/extension.fs
@@ -8,7 +8,7 @@ open Fable.Import.vscode
 [<Emit("$0.match(/\w+/g)")>]
 let wordsIn (str : string) : obj = jsNative
 
-let formatCount : int -> string = importMember "./formatter"
+let formatCount : System.Func<int, string> = importMember "./formatter"
 
 let activate (context : ExtensionContext) =
   let sb = window.createStatusBarItem StatusBarAlignment.Left
@@ -23,7 +23,7 @@ open Fable.Import.vscode
     | Some e ->
       let d = e.document
       if d.languageId = "markdown" then
-        sb.text <- d |> wordCount |> formatCount
+        sb.text <- d |> wordCount |> formatCount.Invoke
         sb.show ()
       else
         sb.hide ()
```

**Comment by Zaid-Ajaj** [comment]
@inosik What about the following? (havn't testsed it tho)
```fsharp
let formatCount (n: int) : string = importMmeber "./formatter"
```

**Comment by inosik** [comment]
@Zaid-Ajaj Yes, that works as well. But I'd still consider this a regression, because that caused existing code to break.

**Comment by alfonsogarciacaro** [comment]
Though it's true that `let formatCount (n: int) : string = importMember "./formatter"` is the preferred way now as @Zaid-Ajaj points out, it's also true this is indeed a regression. Thanks for pointing out that it happened after updating to 1.2.4 @inosik, this probably means [this commit](https://github.com/fable-compiler/Fable/commit/431f6ff660c5d3e7915f8390fcc50b5e34dec52a) or [this one](https://github.com/fable-compiler/Fable/commit/7df326e87c955c61525a62394a6ac214fda5714a) are the culprits, I'll check :+1: Actually I hit something like that in one of my projects though, weird enough, I wasn't using 1.2.4.

**Comment by inosik** [comment]
I don't remember why I did `int -> string` in the first place :smile: And I agree that giving names to the arguments is probably more user-friendly, at least in this case.

**Comment by alfonsogarciacaro** [comment]
Sorry @inosik, can you please check if this is fixed with Fable 1.3?

**Comment by inosik** [comment]
No, unfortunately it's still the same with 1.3.0.

The transformation which happens in [this `else` block](https://github.com/fable-compiler/Fable/blob/41b5d942b905a18924e966c8e1a9ec9e29b3154e/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1119-L1123) is missing in the `then` block above. I think I fixed it, let me wrap it up cleanly and create a PR.

**Comment by inosik** [comment]
See #1239.
