### ISSUE TITLE
List.truncate returning one-too-many elements

### ISSUE THREAD

**Issue by stkb** [fable-compiler/Fable#1187]
[Demo code on Fable.io](http://fable.io/repl/#?code=%5B1%3B%202%3B%203%5D%0A%20%20%7C%3E%20Seq.truncate%202%0A%20%20%7C%3E%20printfn%20%22%25A%22%0A%0A%5B1%3B%202%3B%203%5D%0A%20%20%7C%3E%20List.truncate%202%0A%20%20%7C%3E%20printfn%20%22%25A%22%0A)

Hi,

Seq.truncate is working correctly:
- F#: `[1;2;3] |> Seq.truncate 2`
- Generated JS: `truncate(2, ofArray([1, 2, 3]))`
- Output: `[1,2]`

But **List.truncate** (which should give the same result) is using a different JS function, `slice` where the 2nd argument (index upper-bound) is *inclusive*, so one-too-many items are returned:
- F#: `[1;2;3] |> List.truncate 2`
- Generated JS: `slice(0, 2, ofArray([1, 2, 3]))`
- Output: `[1;2;3] // Expected: [1;2]`

Repros in versions ~0.7.5 to 1.2.4.

Thanks for all your hard work!

**Comment by alfonsogarciacaro** [comment]
Ups, there was actually a test for this but the problem remain unnoticed because I forgot to add the `[<Test>]` attribute 😅 It will be fixed in the next version, thanks a lot for the catch and the kind words! ⚾️
