### ISSUE TITLE
sprintf or function call regression in 1.3.0-*

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1193]
```
let spr = sprintf "%s"

[<EntryPoint>]
let main argv =
    printfn "%s" (spr "a")
    0
```

gets compiled to:
```
const spr = exports.spr = (0, _CurriedLambda2.default)((0, _String.toText)((0, _String.printf)("%s", 1)));

(function (argv) {
  (0, _String.toConsole)((0, _String.printf)("%s", 1))(spr("a"));
  return 0;
})(process.argv.slice(2));
```
which results in a runtime error:
```
const spr = exports.spr = (0, _CurriedLambda2.default)((0, _String.toText)((0, _String.printf)("%s", 1)));
                                                      ^
TypeError: (0 , _CurriedLambda2.default) is not a function
```

**Comment by alfonsogarciacaro** [comment]
Damn, I'm getting many similar issues, like #1190 or #1185, apparently there was a regression between 1.2.3 and 1.2.4 and the test set wasn't enough to spot it. At least I have a couple of suspects (aka commits) so hopefully the problem can be narrowed down soon.

Thanks a lot for the repro code!

**Comment by alfonsogarciacaro** [comment]
This is weird, I get exactly the same JS code when compiling with latest build and fable-splitter. However, when I run the result it doesn't throw any errors, it correctly prints `a` 🤔

**Comment by ncave** [comment]
@alfonsogarciacaro it may not be the generated code but the fable-core js lib.

**Comment by alfonsogarciacaro** [comment]
Hmm, but still I don't get the runtime error reported above 😕

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I was having the same problem with sprintf when releasing the updated version of Fulma docs site.

If this can help, [this version](https://github.com/MangelMaxime/Fulma/tree/6959e23f0668c74b5ca9831b4587e1c4dc1f9182) fail at runtime.

[Here](https://github.com/MangelMaxime/Fulma/blob/6959e23f0668c74b5ca9831b4587e1c4dc1f9182/paket.lock#L4-L26) you can see, the versions of the fable dependencies used when the runtime is failling due to sprintf.

**Comment by ncave** [comment]
@alfonsogarciacaro basically what comes back from (0, _String.toText)((0, _String.printf)("%s", 1)) is a string, not a function.

**Comment by ncave** [comment]
@alfonsogarciacaro Here is the full generated code:
```
var _CurriedLambda = require("../fable-core/CurriedLambda");
var _CurriedLambda2 = _interopRequireDefault(_CurriedLambda);
var _String = require("../fable-core/String");
function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }
const spr = exports.spr = (0, _CurriedLambda2.default)((0, _String.toText)((0, _String.printf)("%s", 1)));
(function (argv) {
  (0, _String.toConsole)((0, _String.printf)("%s", 1))(spr("a"));
  return 0;
})(process.argv.slice(2));
```
If I change `(0, _CurriedLambda2.default)(...)` to `(0, _CurriedLambda2.default)(...)` it start to work, so the problem is that `interopRequireDefault` returns something invalid (an object with a single default property).

**Comment by alfonsogarciacaro** [comment]
Still cannot reproduce the error, I've done the following with [current master](https://github.com/fable-compiler/Fable/tree/03bc8e46f0fc94c70d2ae89d533784d10cf84d58):

```
git clean -xfd
sh build.sh FableCoreJS
sh build.sh FableCLI
```

I replace `src/tools/QuickTest.fs` with the following code:

```fsharp
module QuickTest

let spr = sprintf "%s"

[<EntryPoint>]
let main argv =
    printfn "%s" (spr "a")
    0
```

Then:

```
cd src/tools
dotnet restore
dotnet ../../build/fable/dotnet-fable.dll yarn-splitter
node temp/QuickTest.js
```

And `a` is printed on screen, as expected. This is the generated `src/tools/temp/QuickTest.js`:

```js
"use strict";

Object.defineProperty(exports, "__esModule", {
  value: true
});
exports.spr = undefined;

var _CurriedLambda = require("./fable-core/CurriedLambda");

var _CurriedLambda2 = _interopRequireDefault(_CurriedLambda);

var _String = require("./fable-core/String");

function _interopRequireDefault(obj) { return obj && obj.__esModule ? obj : { default: obj }; }

const spr = exports.spr = (0, _CurriedLambda2.default)((0, _String.toText)((0, _String.printf)("%s", 1)));

(function (argv) {
  (0, _String.toConsole)((0, _String.printf)("%s", 1))(spr("a"));
  return 0;
})(process.argv.slice(2));
```

@ncave Do you still get the same error even when following the same steps? Are you using latest master? Is the [fable-splitter configuration](https://github.com/fable-compiler/Fable/blob/03bc8e46f0fc94c70d2ae89d533784d10cf84d58/src/tools/splitter.config.js) different in your case?

Sorry for being so picky and thanks a lot for your help!

**Comment by ncave** [comment]
@alfonsogarciacaro I don't have this in my generated code:
```
Object.defineProperty(exports, "__esModule", {
  value: true
});
```
so the `interopRequireDefault `returns `{ default: obj }` instead of `obj`, and that does not work.

**Comment by ncave** [comment]
@alfonsogarciacaro otherwise I'm using 1.3.0-* as dependency, which is the latest.

**Comment by alfonsogarciacaro** [comment]
> I don't have `Object.defineProperty(exports, "__esModule", {` in my generated code

This is strange, which version of the babel plugin are you using? This is what I have:

```
~/d/Fable ❯❯❯ npm ls babel-plugin-transform-es2015-modules-commonjs
/Users/alfonsogarciacaronunez/dev/Fable
└─┬ babel-preset-es2015@6.24.1
  ├─┬ babel-plugin-transform-es2015-modules-amd@6.24.1
  │ └── babel-plugin-transform-es2015-modules-commonjs@6.26.0  deduped
  └── babel-plugin-transform-es2015-modules-commonjs@6.26.0
```

**Comment by ncave** [comment]
@alfonsogarciacaro You were right, I narrowed it down to the splitter config:
```
const babelOptions = fableUtils.resolveBabelOptions({
  plugins: [
    ["transform-es2015-modules-commonjs", { strict: true }],
  ],
});
```
It's the `{ strict: true }` that seems to cause the `__esModule` property to not be generated. If I take it out, it works in this particular case (which I guess was masking the real issue), but unfortunately it still doesn't work in the general case. I'll try to extract a different repro, although it is a bit deep.

Still, is `interopRequireDefault` returning the correct object in the case `__esModule` is missing?

**Comment by ncave** [comment]
@alfonsogarciacaro Here is a better repro:
```
module App

let spr fmt =
    let fmt = Printf.StringFormat<_>(fmt)
    sprintf fmt

[<EntryPoint>]
let main argv =
    printfn "%s" ((spr "answer: %s") "42")
    0
```
results in this error:
```
  (0, _String.toConsole)((0, _String.printf)("%s", 1))(spr("answer: %s")("42"));
                                                                        ^
TypeError: spr(...) is not a function
```
Just to clarify, this used to work before.

**Comment by MangelMaxime** [comment]
Also, I was having this error even with webpack and I am not using the `strict` option.

**Comment by ncave** [comment]
@alfonsogarciacaro @MangelMaxime Yes, the last repro I posted happens regardless of strict mode.

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks, that works. There is still a runtime error in the REPL, but now it's a different one, I'll open another issue when I get a repro.

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot for the latest test to reproduce the problem and for the quick confirmation @ncave 😄
