### ISSUE TITLE
error FABLE: Cannot find replacement for System.Char::ToUpper

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1201]
I'm working on https://github.com/fable-compiler/ts2fable/pull/19 and was surprised that `Char.ToUpper`. Good news is that string.ToUpper is, so easy work-a-round. May be close as won't fix.

``` fs
let upperFirstLetter (s: string): string =
    // sprintf "%c%s" (Char.ToUpper s.[0]) (s.Substring 1)
    sprintf "%s%s" (s.Substring(0,1).ToUpper()) (s.Substring 1)
```

**Comment by ncave** [comment]
@ctaggart We won't won't fix, we'll fix, we'll fix ;)
