### ISSUE TITLE
add U7 and U8 union types

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1211]
I'm working on https://github.com/fable-compiler/ts2fable/issues/25. typescript.d.ts has a need for a U7 and U8. Any chance we can get those added? Any reason not to?

https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Core/Fable.Core.fs

``` fs
    type CompilerOptionsValue =
        U7<string, float, bool, ResizeArray<obj>, ResizeArray<string>, MapLike<ResizeArray<string>>, ResizeArray<PluginImport>>

    type FlowNode =
        U8<AfterFinallyFlow, PreFinallyFlow, FlowStart, FlowLabel, FlowAssignment, FlowCondition, FlowSwitchClause, FlowArrayMutation>

    type FunctionLikeDeclaration =
        U7<FunctionDeclaration, MethodDeclaration, ConstructorDeclaration, GetAccessorDeclaration, SetAccessorDeclaration, FunctionExpression, ArrowFunction>

    type FunctionLike =
        U7<FunctionLikeDeclaration, FunctionTypeNode, ConstructorTypeNode, IndexSignatureDeclaration, MethodSignature, ConstructSignatureDeclaration, CallSignatureDeclaration>
```

**Comment by MangelMaxime** [comment]
I think just didn't need them until now :)

**Comment by alfonsogarciacaro** [comment]
There's no special reason, although something like `U7` or `U8` can be a bit difficult to handle in F#. At that point it may be easier for both the user and binding creator to just use `obj`. But if you do need `U7`and `U8` I'm not opposed to adding them, so please feel free to PR them [into Fable.Core.fs](https://github.com/fable-compiler/Fable/blob/4a55e602779cd8e2c06bec5900fd2ff9eb262046/src/dotnet/Fable.Core/Fable.Core.fs#L103-L117) :)
