### ISSUE TITLE
Should [<Literal>] value be removed from the generated JS ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1213]
When using:

```fs
let [<Literal>] Container = "button";
```

In the generated JS we got: 

```js
export const Container = "button";
```

I was thinking that `[<Literal>]` were not included into the generated JS as their occurrence are replaced by the compiler. But I can be wrong :)

I was expected to have the same behavior as for `[<StringEnum>]` which are complete erase from generated JS

**Comment by MangelMaxime** [comment]
I just found a way to have this behavior but I don't know if this is dangerous or no: 

```fs
let [<Erase;Literal>] test = "max"

let t2 = test
```

Give this JS:

```js
export const t2 = "max";
```

**Comment by alfonsogarciacaro** [comment]
Ah, interesting. I had the impression `Literal` members were removed from the AST, not sure if my impression was wrong or FCS/Fable has changed. Anyway, I agree the member should be erased, I'll do it :+1:
