### ISSUE TITLE
Printf.sprintf issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1216]
As already mentioned [here](https://github.com/fable-compiler/fable-repl/issues/6), there is a strange `Printf.sprintf` issue that only happens in master and repl (or at least I cannot reproduce it with the latest beta):
```
module App

[<EntryPoint>]
let main argv =
    let res = Printf.sprintf "%s" "abc"
    printfn "res: %A" res
    0
```
Here is the build error:
```
error FABLE: Cannot find replacement for Microsoft.FSharp.Core.PrintfModule::PrintFormatToStringThen
```
so it results in this invalid call: `null("abc");`
```
"use strict";
var _String = require("./fable-core/String");
(function (argv) {
  const res = null("abc");
  (0, _String.toConsole)((0, _String.printf)("res: %A"))(res);
  return 0;
})(process.argv.slice(2));
```

**Comment by alfonsogarciacaro** [comment]
Interesting, this seems to happen only when qualifying the module `Printf`. I found the way to fix this case, let's hope there are not many more...

> Too many of my latest comments end with "let's hope" :wink:
