### ISSUE TITLE
create AppVeyor team account

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1220]
Current the builds are using `alfonsogarciacaro` AppVeyor account. It would be a good to create a `fable-compiler` team account and switch to it.

https://ci.appveyor.com/project/alfonsogarciacaro/fable/build/1.0.2984
https://www.appveyor.com/docs/team-setup/

I just automated the [build for ts2fable](https://github.com/fable-compiler/ts2fable/pull/51) and it would be cool if there was a:
https://ci.appveyor.com/project/fable-compiler/ts2fable

**Comment by alfonsogarciacaro** [comment]
I agree :+1: You're right, we're still using Appveyor as it was configured when Fable repo was in my GH profile. Would you mind creating the Appveyor fable-compiler account and giving me access? I tried to do it but Appveyor is giving me some funny options. For some reasons is letting me log in as @matthid 😆

<img width="383" alt="screen shot 2017-11-07 at 5 50 53 pm" src="https://user-images.githubusercontent.com/8275461/32506664-77f2ed38-c3e5-11e7-8434-e291e7b90606.png">

**Comment by matthid** [comment]
@alfonsogarciacaro AppVeyor is kind of weird. For the FAKE repository I setup a build and gave access to a particular group (I think some github organization). I guess you are member there as well. That is why you see my account there. If you login you should see only the FAKE build (probably FSharp.Formatting).

Login in AppVeyor is its own science but after a while it makes a bit of sense ;)

**Comment by ctaggart** [comment]
I'll try to create this now.

**Comment by ctaggart** [comment]
Who else needs to be an admin?
![image](https://user-images.githubusercontent.com/80104/32602358-99c9056a-c524-11e7-818d-0e1a6277df46.png)

![image](https://user-images.githubusercontent.com/80104/32602538-24d54966-c525-11e7-8e04-670e56ef9b74.png)

I don't have owner/admin rights on the repositories. @alfonsogarciacaro (or someone who does) Please add the ts2fable project.

![image](https://user-images.githubusercontent.com/80104/32602632-92ba2ba4-c525-11e7-8e1d-dc2ed4c6bec7.png)

**Comment by ctaggart** [comment]
Select "fable-compiler" when logging in.
![image](https://user-images.githubusercontent.com/80104/32602722-eec196f8-c525-11e7-973f-1b4b3f9862d1.png)

**Comment by MangelMaxime** [comment]
Can you add me please ? @ctaggart 

I don't know the info needed.

Email: mangel.maxime@protonmail.com
Name: MangelMaxime

**Comment by ctaggart** [comment]
@MangelMaxime, added you. If you have admin access in GitHub, can you add ts2fable?

**Comment by MangelMaxime** [comment]
@ctaggart Thanks you. 

Done: https://ci.appveyor.com/project/fable-compiler/ts2fable

**Comment by alfonsogarciacaro** [comment]
Awesome, thank you all for your help!
