### ISSUE TITLE
TypeError: (0 , _Async.runSynchronously) is not a function

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1226]
I would like to wait for Node to write the files to disk, but I'm getting the error `TypeError: (0 , _Async.runSynchronously) is not a function` when I try to use Async.RunSynchronously. This is for ts2fable. The code and error details are here:

https://github.com/fable-compiler/ts2fable/pull/60

**Comment by MangelMaxime** [comment]
I am on my phone so I can't check it but take a look at the compatibility docs of fable. I think the method you use isn't supported.

**Comment by ctaggart** [comment]
It says it is not supported in http://fable.io/docs/compatibility.html under caveats. Any idea ho

**Comment by ctaggart** [comment]
(Mobile phone issues.) Any idea how I can wait for the files to write to disk?

**Comment by MangelMaxime** [comment]
Can't you use a promise ?

Something like that:

```
let writeFile fileName content =
  promise {
   // doStuff here
  }


promise {
  do! writeFile "file1.txt" "content1"
  do! writeFile "file2.txt" "content2"
  do! writeFile "file3.txt" "content3"
  do! writeFile "file4.txt" "content4"
} 
|> Promise.Start
|> Promise.bind (fun _ ->
  // Everything has been done
)

```

I didn't test the code but you get the idea.

**Comment by ctaggart** [comment]
I just tried, but I'm stuck with a Fable build error of:
```
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(85,4): (85,11) error FABLE: Cannot find replacement for Fable.PowerPack.Promise.PromiseBuilder::Delay
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(85,4): (85,11) error FABLE: Cannot find replacement for Fable.PowerPack.PromiseImpl::promise
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(95,4): (95,11) error FABLE: Cannot find replacement for Fable.PowerPack.Promise.PromiseBuilder::Delay
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(95,4): (95,11) error FABLE: Cannot find replacement for Fable.PowerPack.PromiseImpl::promise
```

**Comment by ctaggart** [comment]
Ugh, that error was `Fable.Powerpack` instead of `Fable.PowerPack` in `paket.references.
https://github.com/fable-compiler/ts2fable/pull/60/commits/0b7e4ae50373fd032f271422c391d7d8185d232a

**Comment by MangelMaxime** [comment]
Ah :) Is it working ? :)

**Comment by ctaggart** [comment]
Turns out the original code works fine when it isn't piped through the splitter postBuild(). The splitter postBuild() is very useful for `watch` though. I'm guessing it has something to do with "Callback is Not Queued" https://stackoverflow.com/a/8636001/23059. I'm out of this rabbit hole.
