### ISSUE TITLE
Fable can't find replacements if capitalization is wrong in paket.references

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1227]
From https://github.com/fable-compiler/Fable/issues/1226#issuecomment-343292058

If you use the wrong case such as  Fable.Powerpack instead of Fable.PowerPack in `paket.references` Fable can't find find the replacements.
fable-compiler/ts2fable@0b7e4ae

```
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(85,4): (85,11) error FABLE: Cannot find replacement for Fable.PowerPack.Promise.PromiseBuilder::Delay
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(85,4): (85,11) error FABLE: Cannot find replacement for Fable.PowerPack.PromiseImpl::promise
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(95,4): (95,11) error FABLE: Cannot find replacement for Fable.PowerPack.Promise.PromiseBuilder::Delay
C:/Users/camer/fs/ts2fable/src/ts2fable.fs(95,4): (95,11) error FABLE: Cannot find replacement for Fable.PowerPack.PromiseImpl::promise
```

**Comment by MangelMaxime** [comment]
For reference, [nuget package](https://github.com/fsprojects/Paket/issues/2847#issuecomment-336810367) are insensitive. 

But I think the F# namespace are case-sensitive here probably.

**Comment by alfonsogarciacaro** [comment]
Thanks for the info @ctaggart! I managed to reproduce the problem. The commit above should fix it (I tested it locally), please give it a try with latest Fable 1.3 beta... which I will release tomorrow morning :wink:
