### ISSUE TITLE
Seq.singleton returns empty after first use

### ISSUE THREAD

**Issue by amieres** [fable-compiler/Fable#1230]
### Description

Seq.singleton returns empty after first use

### Repro code
Running this in the REPL
```
let a  = "HELLO" |> Seq.singleton

a |> printfn "%A"
a |> printfn "%A"
```
produces this output
```
["HELLO"]
[]
```

### Expected and actual results

running the same code in FSI produces this output
```
seq ["HELLO"]
seq ["HELLO"]
```

**Comment by alfonsogarciacaro** [comment]
Nice catch ⚾️  Thanks for the report!
