### ISSUE TITLE
function is translate to IIFE in a particular case

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/Fable#1234]
### Description

A function is translate to IIFE and cause `f is not function error`

### Repro code

[repl](http://fable.io/repl/#?code=module%20test.bug%0A%0Aopen%20Fable.Core%0A%0A%0A%2F%2F%20working%0A%0Alet%20mutable%20lastModel%3A%20int%20option%20%3D%20None%0Alet%20inline%20notEqual%20a%20%3D%20not%20%3C%7C%20obj.ReferenceEquals%20(1%2C%20a)%0Alet%20hasUpdate%20%3D%20Option.map%20notEqual%20lastModel%20%7C%3E%20Option.defaultValue%20true%0Aprintfn%20%22%25A%22%20hasUpdate%0A%0A%2F%2F%20error%0Alet%20mutable%20private%20setInternalState%3A%20(obj%20-%3E%20unit)%20option%20%3D%20None%0Alet%20withReact%20()%20%3D%0A%20%20let%20mutable%20lastModel%20%3D%20None%0A%0A%20%20let%20setState%20()%20%3D%0A%20%20%20%20let%20inline%20notEqual%20a%20%3D%20not%20%3C%7C%20obj.ReferenceEquals%20(1%2C%20a)%0A%20%20%20%20match%20setInternalState%20with%0A%20%20%20%20%7C%20Some%20setState%20-%3E%0A%20%20%20%20%20%20%20%20let%20hasUpdate%20%3D%20Option.map%20notEqual%20lastModel%20%7C%3E%20Option.defaultValue%20true%0A%20%20%20%20%20%20%20%20printfn%20%22%25A%22%20hasUpdate%0A%20%20%20%20%7C%20None%20-%3E%0A%20%20%20%20%20%20%20%20failwith%20%22withReact%20init%20failed.%22%0A%20%20%0A%20%20setState() )

```js
import { createAtom } from "fable-core/Util";
import { getValue, defaultArg } from "fable-core/Option";
import { printf } from "fable-core/String";
export let lastModel = createAtom(null);
export const hasUpdate = defaultArg(defaultArg(lastModel(), null, function (a) {
  return !(1 === a);
})/* function */, true);
replLog(printf("%A"))(hasUpdate);
let setInternalState = createAtom(null);
export function withReact() {
  let lastModel_1 = null;

  const setState_1 = function () {
    if (setInternalState() == null) {
      throw new Error("withReact init failed.");
    } else {
      const setState = getValue(setInternalState());
      const hasUpdate_1 = defaultArg(defaultArg(lastModel_1, null, function (a) {
        return !(1 === a);
      }())/* IIFE */, true);
      replLog(printf("%A"))(hasUpdate_1);
    }
  };

  setState_1();
}
```

### Expected and actual results

Function should alway be a function.  :)

### Related information

* Fable version (`dotnet fable --version`):1.3.0
* Operating system: macOS sierra

**Comment by alfonsogarciacaro** [comment]
The linked code is working with latest REPL (based on Fable 1.3), can you please check again if it works with CLI version? Thanks!

**Comment by zaaack** [comment]
@alfonsogarciacaro  The linked code is not working, the generated code might not easy to read... I can confirm it's the same in dotnet-fable 1.3 with fable-splitter.

![image](https://user-images.githubusercontent.com/5233940/32986195-bcccd646-cd07-11e7-83e4-3ab0c13cf7e6.png)

**Comment by alfonsogarciacaro** [comment]
Ah, thanks! I got indeed confused by the code 😅 Interestingly the problem here was the inline local function. If you remove `inline` from `notEqual` it will work. In any case hopefully the problem should have been fixed with the commit linked above ☝️

**Comment by zaaack** [comment]
@alfonsogarciacaro Thanks for your quick fix! Sorry that I should describe it more clear at first time,  this problem makes me a little confused at that time. 🤦‍♂️

**Comment by alfonsogarciacaro** [comment]
No worries, I know sometimes it's difficult to isolate the problem, but it does help a lot to have code without dependencies to reproduce the issue, thank you! 👍
