### ISSUE TITLE
Cannot find replacement for System.Char::IsUpper

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1236]
### Description

Follow up to #1201 
C:/Users/camer/fs/ts2fable/src/naming.fs(10,28): (10,51) error FABLE: Cannot find replacement for System.Char::IsUpper

### Repro code

``` fs
Char.IsUpper
```

### Related information

* Fable version (`dotnet fable --version`): 1.3.0
* Operating system:

**Comment by ctaggart** [comment]
Will need `Char.IsLetter` too.

**Comment by alfonsogarciacaro** [comment]
`Char.IsLetter` should already be supported (though it only works for European alphabets). I implemented now `IsUpper` and `IsLower` :+1:
