### ISSUE TITLE
Cannot find replacement for System.Char::IsNumber

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1237]
### Description

Continuing from #1236 
C:/Users/camer/fs/ts2fable/src/naming.fs(21,27): (21,50) error FABLE: Cannot find replacement for System.Char::IsNumber

### Repro code
``` fs
Char.IsNumber
```

### Related information

* Fable version (`dotnet fable --version`): 1.3.0
* Operating system:

**Comment by alfonsogarciacaro** [comment]
I've implemented `IsDigit` and added a warning when using `IsNumber` to let the user know it will be converted to `IsDigit`. Is that OK? If that's enough for you, I'll release a new Fable version :+1:

**Comment by ctaggart** [comment]
I don't need a version. I can wait for one to come out. Not sure I understand the warning ( at least from my phone).

**Comment by alfonsogarciacaro** [comment]
`Char.IsNumber` gives positive results for more characters than `IsDigit` which only works for 0-9 ([MSDN docs](https://msdn.microsoft.com/en-us/library/yk2b3t2y(v=vs.110).aspx#Anchor_1)) and I'm not sure how to reproduce the full semantics in JS so I hope for now it's just enough to compile `IsNumber` as `IsDigit` 😕
