### ISSUE TITLE
Cannot find replacement for System.Collections.Generic.List::RemoveRange

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1242]
### Description

C:/Users/camer/fs/ts2fable/src/write.fs(216,8): (216,43) error FABLE: Cannot find replacement for System.Collections.Generic.List::RemoveRange

### Related information

* Fable version (`dotnet fable --version`): 1.3.1
* Operating system:

**Comment by Zaid-Ajaj** [comment]
Lemme give this a try :smile:
