### ISSUE TITLE
"unexpected end of JSON input"

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1247]
### Description

I see "unexpected end of JSON input" in my app. but it doesn't give details.
I think we should also print the json that was wrong

**Comment by alfonsogarciacaro** [comment]
Is this when running `ofJson`. If so, I guess we can surround [this line](https://github.com/fable-compiler/Fable/blob/e126bfe73b705a7e514708489385cd714099730e/src/js/fable-core/Serialize.ts#L298) with a try...catch.

**Comment by forki** [comment]
Yes please. Please please.

Am 24.11.2017 13:25 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by alfonsogarciacaro** [comment]
Until a new Fable.Core version is published you can shadow it in your app:

```fsharp
[<PassGenerics>]
let ofJson<'a> json =
   try
      Fable.Core.JsInterop.ofJson<'a> json
   with ex ->
      failwithf "Cannot parse JSON (%s): %s" ex.Message json
```

**Comment by forki** [comment]
thanks!

2017-11-24 13:42 GMT+01:00 Alfonso Garcia-Caro <notifications@github.com>:

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/33211474-fb81d43e-d11e-11e7-907e-07bff99610a4.png)

^^ this is what chrome says that fails line 104

**Comment by alfonsogarciacaro** [comment]
What's the error message? Can you post the JSON (or send it to me)?

**Comment by forki** [comment]
I don't see the error message. I replace the one location of ofJson in my code with the snippet above. but it seems it's not it

**Comment by alfonsogarciacaro** [comment]
Would it be possible to have some code to reproduce or a failing test?

**Comment by forki** [comment]
No the problem is that don't see any trace of where it goes wrong and with
what data. I think a prerelease version (or dot release) which adds more
output around these places would help me to nail it down and to get proper
repro

Am 25.11.2017 11:08 schrieb "Alfonso Garcia-Caro" <notifications@github.com

**Comment by alfonsogarciacaro** [comment]
If this affects the fable-core JS files there's a faster way to do this:

1 - Clone Fable repo
2 - Make the modifications you want in `Fable/src/js/fable-core`
3 - Run `FableCoreJs` FAKE target
4 - Add `fableCore` to your fable-loader options with value `resolve("./path/to/Fable/build/fable-core")` [as in here](https://github.com/fable-compiler/Fable/blob/38df179e3bec8fcf60c51bd8df39c6e679506950/tests/webpack.config.js#L32)
5 - Start your Webpack dev server (usually `dotnet fable yarn-start`). Check results and if necessary repeat 2) and 3). Your page should refresh automatically after changes.

**Comment by alfonsogarciacaro** [comment]
Continued in https://github.com/fable-compiler/fable-powerpack/pull/34
