### ISSUE TITLE
error FABLE: Cannot find replacement for System.Enum::HasFlag

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#1255]
### Description

``` fs
let isConst (nd: Node): bool =
    nd.flags.HasFlag NodeFlags.Const
```

C:/Users/camer/fs/ts2fable/src/read.fs(163,4): (163,36) error FABLE: Cannot find replacement for System.Enum::HasFlag

Not urgent. Workaround is not bad:
``` fs
let isConst (nd: Node): bool =
    (int nd.flags) ||| (int NodeFlags.Const) <> 0
```

### Related information

* Fable version (`dotnet fable --version`): 1.3.2
* Operating system:

**Comment by alfonsogarciacaro** [comment]
This one should be easy and we can probably just inline the code, I'll take it... unless @Zaid-Ajaj is faster ;)

**Comment by Zaid-Ajaj** [comment]
Hold my :beer:
