### ISSUE TITLE
Compare and Equal is broken for Value types and IE11

### ISSUE THREAD

**Issue by SCullman** [fable-compiler/Fable#1286]
### Description
``compare`` and ``equals`` from ``fable-core/Util`` are both using ``Object.getPrototypeOf``. As
[Object.getPrototypeOf](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) throws an "TypeError" for valuetypes in ES5, it is a source for a lot of errors within Internet Explorer.

### Repro code

Please provide the F# code to reproduce the problem.
```
[5;4;3;2;1]
|> List.sort 
|> printfn "%O"

let equals a b = (a = b)
equals "Apples" "Pears"
|> printfn "%b"
```

### Expected results (and actual fine in most browsers)
[1; 2; 3; 4; 5]
false

### Actual results in Internet Explorer
TypeError: Object.getPrototypeOf: 'this' is no object.

### Related information

* Fable version (`dotnet fable --version`): 1.3.4
* Operating system: Windows 10

**Comment by SCullman** [comment]
I wasted a lot of time because I thought it was an polyfill issue. It is not. Object.getPrototypeOf is build in and just behaves different than in Chrome.

**Comment by alfonsogarciacaro** [comment]
Is this because of [this](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/getPrototypeOf) (see "Notes" section)?

> In ES5, it will throw a TypeError exception if the obj parameter isn't an object. In ES2015, the parameter will be coerced to an Object.

Interesting, so they changed the behavior in ES2015. Anyway, it should be fine with your PR, thanks a lot for the time spent researching and fixing this! :clap: :clap:
