### ISSUE TITLE
Fable-splitter error about namespace in watch mode 

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1288]
### Description

I am using fable-splitter watch mode to generate static website.

And I often have this error:

> /home/maxime/Workspace/Github/MangelMaxime/Thot/docs/src/Components/Navbar.fs(1,0): (1,1) error FSHARP: Files in libraries or multiple-file applications must begin with a namespace or module declaration, e.g. 'namespace SomeNamespace.SubNamespace' or 'module SomeNamespace.SomeModule'. Only the last source file of an application may omit such a declaration.

Triggering several times, a change in a file without changing anything made the error disappear or simple killing the process and restarting again works too.

### Expected and actual results

Don't have this error.

### Related information

* Fable version (`dotnet fable --version`): 1.3.4
* Operating system: Ubuntu 17.10 x64
* fable-splitter version: 0.1.20

Any idea what's causing this problem ?

**Comment by alfonsogarciacaro** [comment]
Hmm, that's weird. All FSHARP errors are coming directly from the F# compiler, but I don't understand why sometimes you see it and sometimes don't. Maybe changing this:

```fsharp
namespace Components

[<RequireQualifiedAccess>]
module Navbar =
```

...to the following helps?

```fsharp
[<RequireQualifiedAccess>]
module Components.Navbar
```

**Comment by MangelMaxime** [comment]
Will try it thanks for the suggestion, yes I still use `namespace` when it's not need sometimes... :) 

I probably should forget the `namespace` keyword at some point. In general, I find it a bad idea later :D

**Comment by MangelMaxime** [comment]
I can't generate again the error. Will consider that your solution fix it :)

And if it happen again will try to produce a reproduction case.
