### ISSUE TITLE
GetUnionCases

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#1297]
Hi!
I would like to get an array of union cases in fable to check if I can find a value inside.
I found some doc regarding the dotnet code: It seems we can use `FSharpType.GetUnionCases(t)`.
Is there a Fable counterpart?
Thanks!

**Comment by alfonsogarciacaro** [comment]
There's some limited support for reflection in Fable and `FSharpType.GetUnionCases(t)` is indeed supported 😄 Usually the easiest way to see what's supported and what not is to check [the Reflection tests](https://github.com/fable-compiler/Fable/blob/f1d12b73ef5f36f8b06dff4e0cb00b82da6ff914/tests/Main/ReflectionTests.fs#L272-L301).

**Comment by whitetigle** [comment]
Thanks for the hint!
