### ISSUE TITLE
Stackoverflow trying to deserialize int64

### ISSUE THREAD

**Issue by eugene-g** [fable-compiler/Fable#1306]
### Description

First of all, I'm talking about using Fable.JsonConverter only, which we're using without Fable.

There is inconsistency in handling Int32 and Int64 values. Int32 values are being mapped just fine, while Int64 values cause stackoverflow.

### Repro code

DTO under test:
```
type Record = {
    Prop1 : string
    Prop2 : int
    Prop3 : int option
    Prop4 : int64 // new property added, compared to current master branch
}
```

Repro (note Prop4 added to input):
```
    [<Fact>]
    let ``Record deserialization from raw json works``() =
        let serialized = """{ "Prop1": "value","Prop2":5,"Prop3":null,"Prop4":42}"""
        let deserialized = deserialize<Record> serialized
        Assert.Equal("value", deserialized.Prop1)
        Assert.Equal(5, deserialized.Prop2)
        match deserialized.Prop3 with
        | None -> ()
        | _ -> Assert.True(false, "Should not happed")
        Assert.Equal(42L, deserialized.Prop4)
```

### Expected and actual results

I'd expect Prop4, being int64 value, correctly mapped to the value from json.
Actually we get a stackoverflow. Looking at the code, I've noticed that Int32 and Int64 values are being handled differently. Newtonsoft.Json makes no difference between 32 and 64 values, leading to infamous int64 reduction to 53 bits (IEEE 754). Fable.JsonConverter serializes 64 bit values properly. but violates principle of least astonishment: int64 values in serialized code are strings with mandatory sign (e.g. "+42") and trying to provide integer value for deserialization leads to stackoverflow.

Not sure how "open" Fable.JsonConverter is to the world outside of Fable, so probably it is "not an issue", but I think that stackoverflow, that is so easy to cause and not so easy to debug, should be addressed.

### Workarounds

Some workarounds discussed at #1104.
Another workaround is to remove `Kind.Long` from converters (keeping in mind precision reduction).

**Comment by alfonsogarciacaro** [comment]
Hi @eugene-g! Thanks for taking the time to investigate and report the issue. Weird, we're defaulting to Newtonsoft.Json serialization when the int64 is not serialized as a string, and I would expect it to work for your use case 🤔 In any case, the fix in the commit above ☝️ seems to fix the problem... or at least the test you kindly provided. Can you please try with 1.0.4? Please note that I'm not on Windows now and cannot build for net45, so I've published this version only for netstandard1.6.

**Comment by eugene-g** [comment]
@alfonsogarciacaro colleagues reported that it works perfectly now. Thank you :)
