### ISSUE TITLE
Allow optimization of "dummy" union and record types

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1308]
### Context

One of the benefits of F# is the lightweight declaration of types. This is an incentive to create many types, especially records and unions. These are actual types in .NET and besides inheritance and constructors, they can have all the features of _standard_ classes: properties, static and instance methods, reflection. In Fable we tried to keep most of the semantics and because of this unions and records are compiled as ES6 classes with reflection info that can be consulted at runtime. However, I find myself showing resistance to create many types in Fable projects because I know they're going to increase the bundle size when in many cases I don't need the extra features.

A solution would be to use the [`PojoAttribute`](http://fable.io/docs/interacting.html#plain-old-javascript-objects) which turns records into plain old JS objects. This attribute was designed to interact with React which doesn't allow typed objects (see #157). I had the suspicions devs could abuse it and that's why I haven't promoted it much, but now I think we may abuse it to reduce bundle sizes 😅 
 
> BTW, it's also possible to use the `PojoAttribute` with unions ([example](http://fable.io/repl/#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0A%5B%3CPojo%3E%5D%0Atype%20DU%20%3D%0A%20%20%7C%20Foo%20of%20money%3Afloat%0A%20%20%7C%20Bar%20of%20name%3Astring%20*%20age%3Aint%0A%20%20%0Alet%20x%20%3D%20Foo%205.%0Alet%20y%20%3D%20Bar(%22John%22%2C%2054)&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2)). I did it for compatibility with [TypeScript new Discriminated Unions (aka tagged unions)](https://www.typescriptlang.org/docs/handbook/advanced-types.html) and also for [interacting with Redux](https://github.com/fable-compiler/samples-browser/blob/3854509edcaf5c69af611e359f7ef9c08b000daf/src/redux-todomvc/App.fs#L76-L83), but I think nobody is using it.

### Proposal

The proposal would be to make it easier to erase types (converting them into pojos), probably by **adding an attribute to the module containing the types** (that would also make it easier to share domains between server and client using a simple `#if` directive).

This should benefit records but I'm thinking also in unions. The idea would be to deprecate the behaviour mentioned above :point_up: (as, hopefully, nobody is relying on it) and compile pojo unions more or less as (I think) BuckleScript does:

- If no case contains data, compile it as an integer. This is basically how enumerations work, but enumerations are cumbersome in F# (you have to assign a number to all cases, always qualify it, pattern matching is not comprehensive) so few people use them. This would [benefit Fulma](https://github.com/MangelMaxime/Fulma/issues/92) for example.
- If there are cases with data, compile it as a JS array. The first element would be the tag integer and the others would contain the data fields.
- Bonus? For single case unions (a common pattern to protect primitive values like `type Address = Address of string`) we could erase the union completely and leave only the data value.

### Debate

Before starting some work on this, I'd like to get some feedback to see if this feature is desirable. We need to be careful in identifying the cons and making sure they don't outweigh the pros.

- **Pros**: May increase performance (we actually need to measure this), will reduce bundle size.
- **Cons**: It's another _fork_ of standard F# (something I promised myself I would stop doing). It may create confusion about types with different runtime semantics, we can try to spot potential conflicts at compile time but maybe we cannot catch'em all.

Another question is what attribute should we use for this? `PojoAttribute` or create a new one like `OptimizeTypes` / `EraseTypes`?

**Comment by MangelMaxime** [comment]
Having different generation depending on what the DU contains seems *dangerous*. 

For example, how will we detect the difference between a simple string and the bonus case ?

```fs
let myString = "maxime"
// const mySgtring = "maxime"

type Address = Address of string

let du = Address "maxime"
// const du = "maxime"
```

I am in favor of optimization 1 and 2, 
but not the optimization 3.

Also, it's important to note that author of js library written with Fable should not expose DUs decorated with `[<OptimizeType>]`, just wanted to mention it.

**Comment by alfonsogarciacaro** [comment]
Yes, you're right. Actually after sleeping this over I realized this can open the door to many edge cases and problems (there're several things depending on reflection already: JSON deserialization, keyValueList, etc) and we should focus on stabilization now. There are also other issues open to optimize the code, we should close them first.

I'll close the issue for now, we may revisit it later. Thanks a lot for your feedback!
