### ISSUE TITLE
Cannot find replacement for Microsoft.FSharp.Core.Operators::Sign

### ISSUE THREAD

**Issue by jetimms** [fable-compiler/Fable#1311]
### Description

Using sign on a float or integer gives the "cannot find replacement error." So, I'm guessing that operator hasn't been implemented in Fable yet.

### Repro code

`
sign 1
sign 1.
sign 0
sign 0.
sign -1
sign -1.
`

### Expected results

`
1
1
0
0
-1
-1
`
### Actual results

I received the error: Cannot find replacement for Microsoft.FSharp.Core.Operators::Sign

### Related information

* Fable version 1.2.3
* Operating system: Ubuntu 16.04
* Mono version: Mono JIT compiler version 5.4.1.6

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! The fix will be included in the next version of Fable :+1:

**Comment by jetimms** [comment]
That's great! Thanks!
