### ISSUE TITLE
Importing value as mutable makes the value a function when accessing it

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1314]
### Description
When importing a value from some javascript module and annotating it with `mutable`, the value becomes a function when you want to access it. 

### Repro code
The following works:
```fs
open Fable.Core
open Fable.Core.JsInterop

let someValue : string = import "someValue" "someModule"
let value = someValue
```
Compiles to JS
```js
import { someValue as someValue_1 } from "someModule";
export const someValue = someValue_1;
export const value = someValue;
```
But as soon as you make the imported value mutable:
```fs
open Fable.Core
open Fable.Core.JsInterop

let mutable someValue : string = import "someValue" "someModule"
let value = someValue
```
The compilation is incorrect:
```js
import { someValue as someValue_1 } from "someModule";
export let someValue = someValue_1;
export const value = someValue();
```
Giving me all kinds of `someValue is not a function` errors
This error happens regardless of using `import` or `importMember`

* Fable version (`dotnet fable --version`): 1.3.7
* Operating system: Linux Ubuntu 17

**Comment by alfonsogarciacaro** [comment]
This is intended as it was necessary to fix #986 but I didn't take into account importing values, I'll take a look. Thanks for the report!

**Comment by alfonsogarciacaro** [comment]
Latest Fable will throw an error when trying to make an imported (or global) value both mutable and public, asking the user to make it private. Do you think this is enough @Zaid-Ajaj or should we try to enable mutable public imported values too?

**Comment by Zaid-Ajaj** [comment]
I personally don't mind but I think users will expect this to just work the same way it does with normal F# on dotnet

**Comment by alfonsogarciacaro** [comment]
Well, in F# dotnet you cannot import values from a JS library :)

**Comment by Zaid-Ajaj** [comment]
Oh sorry my bad, I read "mutable public value" hahah. Yes, a warning is the best solution, I guess as a workaround you can import some js function that does that mutation :smile:

**Comment by alfonsogarciacaro** [comment]
You can still mutate imported/global values, you just need to make the value private. I think this is safer to prevent too much exposure to mutation from JS libraries. Cool, let's close then and maybe we can revisit if some users need the feature for any reason.
