### ISSUE TITLE
Reference of record field is being delegated to copies of newly created records

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1315]
### Mutable state strikes again

The following repro sample demonstrates the issue:

```fs
open Fable.Core
open Fable.Core.JsInterop

type IOptions = 
    abstract title : string with get, set

type Msg = { Content : string; Options: IOptions }

let defaultMsg = { Content = ""; Options = createEmpty<IOptions> }

let fstMsg = { defaultMsg with Content = "First Message" }
fstMsg.Options.title <- "First message title"

let sndMsg = { defaultMsg with Content = "Second Message" }

printfn "%A" defaultMsg 
// Error 
// Expected: { Content: "", Options: {} }
// Actual: { Content: ""; Options = { "title" : "First message title" }}

printfn "%A" fstMsg 
// Passed
// Expected { Content: "First Message", Options: { title: "First message title" } }
// Actual { Content: "First Message", Options: { title: "First message title" } }

printfn "%A" sndMsg 
// Error
// Expected: { Content = "Second Message", Options: {} }
// Actual: {  Content = "Second Message", Options: { title: "First message title"  } }
```
### Workaround
Make `defaultMsg` a function, then call the it when creating copies
```fs
let defaultMsg() = { Content = ""; Options = createEmpty<IOptions> }

let fstMsg = { defaultMsg() with Content = "First Message" }
fstMsg.Options.title <- "First message title"

let sndMsg = { defaultMsg() with Content = "Second Message" }
```

* Fable version (`dotnet fable --version`): 1.3.7
* Operating system:

**Comment by Zaid-Ajaj** [comment]
This issue does *not* happen with `mutable` fields, output is the same for both F# on dotnet and with Fable
```fs
type Msg = { Content : string; mutable Title: string }

let defaultMsg = { Content = ""; Title = "" }

let fstMsg = { defaultMsg with Content = "First message" }
fstMsg.Title <- "first message title"

let sndMsg = { defaultMsg with Content = "Second message" }

printfn "%A" defaultMsg 
// { Content = ""; Title = "" }

printfn "%A" fstMsg 
// { Content = "First message"; Title = "first message title" }

printfn "%A" sndMsg 
// { Content = "Second message"; Title = "" }
```

**Comment by Zaid-Ajaj** [comment]
OK this is actually all expected behaviour as F# on dotnet gives the same output

[Dotnetfiddle sample](https://dotnetfiddle.net/z18DPy)

What a shame that you still can shoot yourself in the foot in F#, but I guess no way the compiler could gaurd against that type of situation. 

Closing...

**Comment by vasily-kirichenko** [comment]
Yes, F# isn’t Rust, "with" does shallow copy, after which Options points to the same object in the heap. Having mutable objects as a part of "immutable" records is strange at best, but that’s how .net works.

**Comment by Zaid-Ajaj** [comment]
@vasily-kirichenko I guess it was dump from me to assume that F# just implicitly makes deep copies whenever you `with` a record.

**Comment by alfonsogarciacaro** [comment]
Deep copies are expensive, that's why immutable structures keep references to the unchanged previous elements (like F# lists, maps or sets). But yeah, the problem comes when the structure contains references to mutable objects.

It could be possible to implement a deep copy function if necessary.
