### ISSUE TITLE
Inline code produce many calls to function with side effects that should be called only once

### ISSUE THREAD

**Issue by amieres** [fable-compiler/Fable#1321]
This is actually part of Issue #1238 

### Repro code

```fs


let counter =
    let mutable i = 0
    fun () ->
        i <- i + 1
        i
    
type Type = {
    a     : int
    b     : int
    c     : int
    d     : int
    count : int
}
  with
    static member New(n) = {
        a     = n
        b     = n * 2
        c     = n * 3
        d     = n * 4
        count = counter()  // <== should only be called once per invocation
      }
      
    member        this.MethodN (v:bool) = { this with a = this.a * if v then 2 else 3 }
    member inline this.MethodI (v:bool) = { this with a = this.a * if v then 2 else 3 }
    member        this.MethodN ()       = { this with a = this.a * 10                 }
    member inline this.MethodI ()       = { this with a = this.a * 10                 }

Type.New(5).MethodN(false).MethodN(true).MethodN() |> printfn "not inline: %A"    
Type.New(5).MethodN(false).MethodN(true).MethodN() |> printfn "not inline: %A"    
Type.New(5).MethodI(false).MethodI(true).MethodI() |> printfn "inline: %A"
Type.New(5).MethodI(false).MethodI(true).MethodI() |> printfn "inline: %A"
```
### Expected and actual results
Output from FSI:
```
not inline: {a = 300; b = 10; c = 15; d = 20; count = 1;}
not inline: {a = 300; b = 10; c = 15; d = 20; count = 2;}
inline: {a = 300; b = 10; c = 15; d = 20; count = 3;}
inline: {a = 300; b = 10; c = 15; d = 20; count = 4;}
```
Output from Fable:
```
not inline: {"a":300,"b":10,"c":15,"d":20,"count":1}
not inline: {"a":300,"b":10,"c":15,"d":20,"count":2}
inline: {"a":300,"b":10,"c":15,"d":20,"count":127}
inline: {"a":300,"b":10,"c":15,"d":20,"count":252}
```

### Related information

Tested on Fable REPL

**Comment by amieres** [comment]
The generted code is highly repetitive:

toConsole(printf("not inline: %A"))(Type.New(5).MethodN_0(false).MethodN_0(true).MethodN_1());

compared with

toConsole(printf("inline: %A"))(new Type(new Type(new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).a * (true ? 2 : 3), new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).b, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).c, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).d, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).count).a * 10, new Type(new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).a * (true ? 2 : 3), new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).b, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).c, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).d, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).count).b, new Type(new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).a * (true ? 2 : 3), new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).b, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).c, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).d, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).count).c, new Type(new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).a * (true ? 2 : 3), new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).b, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).c, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).d, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).count).d, new Type(new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).a * (true ? 2 : 3), new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).b, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).c, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).d, new Type(Type.New(5).a * (false ? 2 : 3), Type.New(5).b, Type.New(5).c, Type.New(5).d, Type.New(5).count).count).count));

**Comment by alfonsogarciacaro** [comment]
Thanks again for the report @amieres! Hmm, this is weird. It seems to be the same code as for #1238 and we already have a test for it which is passing. I also quickly tried with Fable CLI and it's working so apparently it's a problem specific to the REPL which is again weird because it should already contain latest Fable code. Maybe something is not working when translating to JS...? I'll try to investigate.

**Comment by alfonsogarciacaro** [comment]
Hi @amieres! Sorry for taking so long to reply. This is working with latest Fable (added test [here](https://github.com/fable-compiler/Fable/commit/3740c799bbd36d2769efe1b0400fdce482b863d3)), so we can finally close the issue :+1:

**Comment by amieres** [comment]
Fantastic!, it is working much better now.
