### ISSUE TITLE
Can't install Fable template on Linux with .NET Core 2.1.4

### ISSUE THREAD

**Issue by bratfizyk** [fable-compiler/Fable#1322]
### Description
I've tried to follow the instructions here: http://fable.io/blog/Introducing-1-0-beta.html to create a Fable sample project. However, after typing "dotnet new fable" nothing happens.

### Repro code

* Operating System: Linux Mint 18.2
* .NET Core version: 2.1.4
* Fable version: "dotnet fable --version" returns a shell error "No executable found matching "dotnet-fable". Though the template is installed:

![image](https://user-images.githubusercontent.com/10075099/34911260-2bda5cbc-f8c7-11e7-8e61-f41374fa5163.png)

After typing "dotnet new fable" I get:

![image](https://user-images.githubusercontent.com/10075099/34911264-4cb65058-f8c7-11e7-9be0-9d00f32a0da6.png)

and no files are created.

**Comment by bratfizyk** [comment]
Scratch that - I googled for "fable F# tutorial" and that was one of the first results. I've noticed that the proper place to go would be "http://fable.io/".

Though I must admit that the lack of info in the command line was misleading, as it says "no parameters". Actually it turned out that the proper way to create a project is to type:

```
dotnet new fable -n FableApp -lang F#
```

Is there a way to provide user with the right command if they type ```dotnet new fable``` ? I'd expect this to work, as e.g. ```dotnet new mvc``` works just fine.

**Comment by MangelMaxime** [comment]
The "no parameters" issue of `dotnet new fable` is a known issue of dotnet template engine. Not much we can do on our side ATM.

For the second error, I don't know. Perhaps @forki know more about it.

**Comment by inosik** [comment]
The first issue (re: `-lang f#`) was fixed in dotnet/templating#1375. No idea when it's going to be released.

**Comment by bratfizyk** [comment]
OK, I've had a chat with someone on Slack and he suggested this might be a dotnet-related issue. TBH not sure if he was right, but the suggested solution brought the project back to life.

1. (Tested) Install dotnet-sdk-2.0.0 and work with it.
2.) (Not tested) Here's a description of an issue: https://github.com/fsprojects/Paket/issues/2894. It suggests adding some packages to the deps file. This might work as a sort of walkaround, but I haven't really tried it out.

**Comment by alfonsogarciacaro** [comment]
It seems this is not actionable in this repo so let's close the issue. Please reopen if you have further questions.
