### ISSUE TITLE
Allow Fable to works without PAKET

### ISSUE THREAD

**Issue by y2k** [fable-compiler/Fable#1334]
### Description
(discussion)

Right now Fable hardcoded to use `PAKET`
https://github.com/fable-compiler/Fable/blob/master/src/dotnet/dotnet-fable/ProjectCracker.fs#L37

Maybe we need to add some flag to fable-complie, that allow fable to load information about dependencies from another sources?

For example we can compute order of dependensies from `targets/.NETStandard,Version=v2.0/.../dependencies` in file `project.assets.json`

It's will be alternative for rookies to creating simple/example projects.

**Comment by alfonsogarciacaro** [comment]
I love Paket but I agree that ideally developers should be free to use just Nuget if they want. However, unfortunately I'm working right now on Fable 2.0 and don't have much time to have a look at how dependencies could be resolved from project.assets.json. If you could help with that it should be ok to remove the Paket dependency.

**Comment by inosik** [comment]
> I love Paket but I agree that ideally developers should be free to use just Nuget if they want.

:+1: on this.

> Maybe we need to add some flag

We can simply fall back to `project.assets.json` if we don't find `{project}.{tfm}.paket.resolved` or `{project}.references`.

Is there any official documentation about `project.assets.json`?

**Comment by alfonsogarciacaro** [comment]
Not sure if there are specs for project.assets.json or it's considered as Nuget internals and subject to change any time, which would make it dangerous to rely on it. Maybe @enricosada knows more?

**Comment by y2k** [comment]
> If you could help with that it should be ok to remove the Paket dependency
OK, I try to write some prototype and test it

**Comment by enricosada** [comment]
`project.assets.json` is pratically internal. you cannot rely on it.

But what's the issue there? you want to support what exactly without paket? the package ref order for project references?

**Comment by inosik** [comment]
This can be closed right? Fable 2 doesn't use `*.paket.resolved` anymore.

**Comment by alfonsogarciacaro** [comment]
Yes, Fable 2 can be used without Paket. Although I've noticed Nuget is extremely unreliable to specify a version in `DotnetCliToolReference` so we will keep recommending to use Paket in Fable projects.
