### ISSUE TITLE
Failed to inline static method

### ISSUE THREAD

**Issue by robkuz** [fable-compiler/Fable#1339]
### On (generic?) types inlining fails

Has anybody seen this error

```fsharp
module A

    let inline empty () : ^T = (^T: (static member GetEmpty: Unit -> ^T) () )

    type AbstractSomething<'st> =
        {
            something: 'st
        }
        with
            static member inline GetEmpty() =
                {
                    something = empty()
                }

module B
    type SomethingValue =
        | Zero
        | One of int
        with
            static member inline GetEmpty() = Zero

    type DefaultSomething = AbstracSomething<SomethingValue> 

module C

    let x: DefaultSomething = empty()
```
I get an error in `module C` saying : `Module build failed: Error: Cannot find inline method AbstractSomething.GetEmpty`

### Expected and actual results

This compiles with F# on dotnet

### Related information

* Fable version (`dotnet fable --version`): 1.3.8
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! I think I know what may be the cause of this, let me investigate.

**Comment by alfonsogarciacaro** [comment]
`empty` and `GetEmpty` being inlined and referencing each other recursively are causing a stackoverflow exception :/

**Comment by MangelMaxime** [comment]
I just stumble on this issue by searching for another one.

And I tried the code in the REPL, with some adaption with there were typos in it. And it seems to be working in the REPL (Fable 3):

[Live demo](https://fable.io/repl/#?code=LYewJgrgNgpgBAFRgZwC5wFAdJWcCCcAvFnGXLOgJYB2Ut8MwADqgJ5wAUAlHAFxwAegmJdhAzmgCGqKgGM4wJgCMYAJzgBxGKgCiLdgICqNKugC0APiEJePON1Ll2zePmVo1UuagDKIJVQAC1oAcwAeAHI0axJyeLgAbwwE1LhkAJ0QmlCBaNQUtIBfQtSAdzMg0rSyaVkFJWBVDVp6GnhtPQM2eziatOT+ofTM4LDRJlYex2GEkuxwaHgAIWJql3h-QOzQgDUpKAh4PtSAHzgALXUQavjzgHl2uBAAMzhaApqK4Nu0uvlFCp1O86AwtDp9FNepdrk4yBs4AARGAvKTQPyjHaifAAOncnm8GO2YXCWyyYX2hxg1iwOCWcAAwmtqpQ4AAPATLHHI1HosljHLYnGTdg8IA&html=Q&css=Q)

```fs
module Test 

module A =

    let inline empty () : ^T = (^T: (static member GetEmpty: Unit -> ^T) () )

    type AbstractSomething<'st> =
        {
            something: 'st
        }
        with
            static member inline GetEmpty() =
                {
                    something = empty()
                }

module B =
    type SomethingValue =
        | Zero
        | One of int
        with
            static member inline GetEmpty() = Zero

    type DefaultSomething = A.AbstractSomething<SomethingValue> 

module C =

    let x: B.DefaultSomething = A.empty()
```

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! You made me realize the code is actually not endless-recursive, I probably made a mistake when trying to reproduce it 😅
