### ISSUE TITLE
List.tail [] yields undefined instead throwing an error

### ISSUE THREAD

**Issue by robkuz** [fable-compiler/Fable#1341]
### Description

    let x = List.tail []

should throw an error like in .NET. instead yields an `undefined` which yields a RT error at a later in unrelated code.

### Expected and actual results

Throw the same error as .NET

### Related information

* Fable version (`dotnet fable --version`): 1.3.8
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
@inosik Fixed this :+1:
