### ISSUE TITLE
REPL regression in 1.3.8

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1351]
@alfonsogarciacaro There seems to be a repl regression in 1.3.8 (but 1.3.7 is fine). Just mentioning it so you would know about it when merging into 2.0.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! Well, at the end there'll be so many changes in 2.0 that new bugs we'll probably eat up any regression :wink: Of course, I'll make sure all tests pass before trying to compile the REPL with 2.0.

**Comment by ncave** [comment]
@alfonsogarciacaro Happy hunting!

**Comment by ncave** [comment]
The issue is still there in v1.3.12, so the last working version is 1.3.7.

**Comment by alfonsogarciacaro** [comment]
Do you mean the fact that the REPL is not building right now or is it something else?

**Comment by ncave** [comment]
@alfonsogarciacaro No, it builds, but there is some regression introduced in 1.3.8 that breaks list iterators. This is just FYI, in case you need to build REPL in the mean time (use 1.3.7), and v2.0 is probably very different.

**Comment by ncave** [comment]
@alfonsogarciacaro What I mean is, compile latest Fable REPL (master) using Fable 1.3.7. 
I have only compiled FCS this way, not Fable+FCS, but it should work (1.3.8+ definitely does not work).

**Comment by alfonsogarciacaro** [comment]
Ah, ok! Now I understand 😅 Hmm, this is weird, I do get an SO error when trying to build Fable locally, but latest commit from master [successfully built the REPL in Appveyor](https://ci.appveyor.com/project/fable-compiler/fable/build/22.0.3-b495) using Fable 1.3.14 🤔

**Comment by ncave** [comment]
@alfonsogarciacaro As already mentioned above, building with v1.3.8+ will build fine, but the resulting javascript code throws a runtime error, something about list iterators.

**Comment by alfonsogarciacaro** [comment]
Thanks again @ncave! I finally [followed your advice properly](https://github.com/fable-compiler/Fable/commit/f17547bc093468b1d2d577b9e201cac55f7cbcd0) and now the tooltips in the REPL are working much better (still some errors here and there) 😸

**Comment by TheAngryByrd** [comment]
Yeah I'm hitting the SO issue too 😿 

```
Process is terminating due to StackOverflowException.
ERROR: Unexpected end of JSON input
```

**Comment by alfonsogarciacaro** [comment]
Where are you getting that @TheAngryByrd? Are you trying to build the REPL too?

**Comment by TheAngryByrd** [comment]
@alfonsogarciacaro I'm basically hitting the point with fantasy that I'll need to compile @ncave 's fork on the F# Compiler to get access to certain APIs instead of just relying directly on the precompiled REPL bits. I tried building the REPL too as a comparison and it gave the same result.

**Comment by alfonsogarciacaro** [comment]
We've stopped work on the REPL as we're focusing on Fable 2. When it's ready will try to compile the REPL and if we've done a good job, hopefully it'll be easier to solve these problems :)

**Comment by alfonsogarciacaro** [comment]
Closing a REPL is using Fable 2 for a while now :)
