### ISSUE TITLE
window / Option inconvenience

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#1358]
### Description

This line:
```fsharp
let window = Browser.window
```
meant to eliminate repeating `Browser.window` get translated to `var window = window` which leaves us with local variable `window` set to `undefined` (I believe due to hoisting this assignment reference itself not a global `window`).

This line:
```fsharp
open Fable.Import.Browser
```
overrides (annoyingly) `Option` type, as there is actually `Fable.Import.Browser.Option`, so:

```fsharp
open Fable.Import.Browser
Some 7 |> Option.iter ignore
```

is a compilation error.

### Repro code

```fsharp
open Fable.Import
let window = Browser.window
window.addEventListener_load (fun _ -> box ())
Some 7 |> Option.iter ignore
```
fails on runtime with (`addEventListener is not a member of undefined`).
NOTE: this code is valid if F# but `window` is a special name. It hits by surprise though. You cannot have a  local variable called `window` and use `Browser.window` in the same scope.

```fsharp
open Fable.Import.Browser
window.addEventListener_load (fun _ -> box ())
Some 7 |> Option.iter ignore
```
does not compile.

### Actual results

Runtime or compile time error.

### Expected results

Both cases working fine :-)

### Related information

* Fable version (`dotnet fable --version`): 1.3.8
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
Does this work? In that case, we can just add `window` to the [list of JS keywords](https://github.com/fable-compiler/Fable/blob/e7bc954c6e863f6ae76e77ee21faad5e284215b4/src/dotnet/Fable.Core/Util.fs#L165-L187) so Fable mangles it (actually it's already there but with the first letter in upper case):

```fsharp
open Fable.Import
let window = Browser.window
window.addEventListener_load (fun _ -> box ())
Some 7 |> Option.iter ignore
```

**Comment by MiloszKrajewski** [comment]
No. This part:
```fsharp
open Fable.Import
let window = Browser.window
window.addEventListener_load (fun _ -> box ())
```
gets translated to:
```javascript
var window = window;
window.addEventListener("load", function (_arg1) {
  return null;
});
```
and fails to `addEventListener` as window is `undefined`.
`var window = window` causes `window` to be local not global and hoisted so it exists event before it's own declaration, so how javascript understands it is:
```
var window;
window = window;
```
This probably explains it better.

Anyway, yes: it should a mangled name (I guess `global` also deserves it then).

**Comment by inosik** [comment]
I ran into this today as well with `let console = Fable.Import.JS.console`.

**Comment by MangelMaxime** [comment]
I have a naive question, why do you create alias like that ?

I agree it's a bug and should be address just trying to understand the motivation :)

**Comment by MiloszKrajewski** [comment]
Because I have CDO (it's a OCD, but alphabetically). 
I found it polishing some code for presentation to make it more readable and fluent (subjective I know). 
I had a `button` and a `canvas` so I wanted a `window` (not a `Browser.window`). So I've added `open Fable.Import.Browser` but all my `Option.xxx` stopped compiling at this point.

**Comment by alfonsogarciacaro** [comment]
I guess it's because opening `Fable.Import.Browser` shadows F# `Option` but it's painful to type `Browser.window` all the time.

I personally like to alias the module to a letter like `module B = Fable.Import.Browser` so you can do `B.window` and you have autocompletion, but I know it's not everybody's cup of tea :)

**Comment by MangelMaxime** [comment]
Thanks for the explanation and I understand them :)

**Comment by MiloszKrajewski** [comment]
Can I ask for `document` and `global`? :-)

**Comment by alfonsogarciacaro** [comment]
@MiloszKrajewski Sure! Can you please send a PR?
