### ISSUE TITLE
`ignore` is ignored 

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#1360]
### Description

This is definitely a minor issue and I can't think about any real-life scenario when it can become serious. It is a discrepancy though between F#@.NET and Fable.

### Repro code

```fsharp
let producer () = 7
let consumer x = printfn "%A" x
() |> producer |> ignore |> consumer
```

### Expected results

`()`

### Actual results

`7`

### Related information

* Fable version (`dotnet fable --version`): fable.io/repl @ 1.3.7

**Comment by MangelMaxime** [comment]
I think it's because `ignore` function is erased at compile time.

Result JavaScript:

```js
import { printf, toConsole } from "fable-core/String";
export function producer() {
  return 7;
}
export function consumer(x) {
  toConsole(printf("%A"))(x);
}
consumer(producer());
```

**Comment by MiloszKrajewski** [comment]
If it is FSC then... tough luck. This is definitelly not the most important issue.

**Comment by MangelMaxime** [comment]
I don't knowif it's FCS, I think it's fable doing that will wait @alfonsogarciacaro answser.

I really need to take a look at FCS, one day...
