### ISSUE TITLE
ofJson cannot parse "NaN" to double/float

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#1362]
### Description

A `double` encoded by Fable.JsonConverter as "NaN" cannot be deserialized.

### Repro code

```fsharp
   type ARecWithDouble = {
       ADouble: double
   }

    try 
        let as_serialized_by_Fable_JsonConverter_1_0_7 = """{"ADouble": "NaN"}"""
        let a:ARecWithDouble = ofJson as_serialized_by_Fable_JsonConverter_1_0_7
        ()
    with ex -> console.log("Deserialization error: ", ex)
```

### Expected and actual results

Expected the the field `ADouble` contains a proper JS `NaN` value.
Actual results: exception:
```
Deserialization error:  Error: Cannot deserialize into Boot.ARecWithDouble - Error (inflate): "NaN" (ADouble) is not of type number - Data: '{"ADouble": "NaN"}'
    at raise (Subscriptions.fs:307)
    at ofJson (Subscriptions.fs:321)
```

### Related information

* Fable version (`dotnet fable --version`): 1.3.10
* Operating system: Windows 10. IE 11, Edge, and Chrome.

**Comment by Zaid-Ajaj** [comment]
Hmm interesting, FYI `NaN` is actually not permitted as valid JSON as per the [RFC](https://tools.ietf.org/html/rfc4627):
> Numeric values that cannot be represented as sequences of digits (such as Infinity and NaN) are not permitted.

**Comment by michaelsg** [comment]
I did not know that. Learned something new.
I've switched to `double option` so I no longer have to rely on `NaN`s.
Thank you.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for checking that @Zaid-Ajaj and I'm happy to hear the workaround worked for you @michaelsg. Should we close this?

**Comment by michaelsg** [comment]
Ah yes. Sorry to take so long to get back to it. Closed :)
