### ISSUE TITLE
Current examples for Fable.Import.Node ?

### ISSUE THREAD

**Issue by bilkusg** [fable-compiler/Fable#1363]
After some trial and error, I've managed to get a small fable program which works with Node standalone, and I eventually worked out that by accessing the values in Fable.Import.Node.Exports I can 
find the objects which implement the various interfaces.

There appear to be no working examples against the latest fable build, and the examples in the old website
don't compile...

But there appears to be no documentation or currently working examples?

Is this the case? If so, do you need some, or is there a reason why ( like things changing too rapidly )

Thanks,
Gary

**Comment by MangelMaxime** [comment]
We just didn't have time for creating an Node example.

The latest example who use `Fable.Import.Node` is:
- the [electron sample](https://github.com/fable-compiler/samples-electron/blob/master/src/Renderer/Renderer.fs)

At the time, I created the https://github.com/fable-compiler/samples-node repo but I never push an example to it. Do you have a Node application example in mind ?

**Comment by bilkusg** [comment]
Well I was actually thinking of an up-to-date version of Fable to produce a client-server app with  express on the backend instead of something like the SAFE stack. 

One of the projects I'm interested in using Fable for involves automatic GUI generation from an arbitrary existing relational database schema enhanced with extra metadata. 

My intention is to use elmish for the front-end, and I'm trying to decide whether to use F# natively on the backend or fable and node.  

(And the recent discussion about remoting/json/typeof &c is of particular interest to me also)

But googling for fable and express just brings up what I think is the old archived version of fable at 
tpetricek.github.io/Fable/

**Comment by MangelMaxime** [comment]
You can see an example of Fable + Express [here](https://github.com/fable-compiler/fableconf-workshops/tree/master/elmish)

It's using Elmish on the front-end and Express on the backend.  If you take the repo at this commit https://github.com/fable-compiler/fableconf-workshops/commit/d53f54d1a190a36039c1fc3147d3d5a3e961ca10 the Elmish app is complete. I removed some part of the code because it's was an exercise.

With some custom helpers, you can archieve this kind of code for the backend: https://github.com/fable-compiler/fableconf-workshops/blob/master/elmish/src/Server/App.fs

**Comment by bilkusg** [comment]
Thanks @MangelMaxime. That looks very useful. 
Gary

**Comment by bilkusg** [comment]
Having now spent some time with the example of express mentioned, I have a couple of comments.
1 - The application doesn't compile at the moment, even after I upgrade the version of paket. The failure is during the compile phase:
````
ERROR: parsing resolved p2p refs, expected properties not found (in Shared.fsproj) 
````
2 -  Maybe it's just me, but it took quite a long time to work out how to go from the interface definition in Fable.Import.Express to the kind of code below. Even after I knew what would work, it took me quite a lot of staring at the code of the import module to work through the definitions and understand why it looks like that. By comparison, it took only a couple of minutes for me to naively import Express from the javascript as an object.
For comparison, my 5 minute version looks like this:
````
module MainProgram
    open System
    open Fable.Import
    open Fable.Import.Node
    open Fable.Core
    open Fable.Core.JsInterop
    open Fable.Import.Express
    [<Import("default", from="express")>]
    let express: obj = jsNative
    [<EntryPoint>]
    let main argv =
       let app = express$()

       app?get("/",fun req (res:obj)->
        res?send("Working now")
       ) |>ignore

       app?listen(3000,fun _ ->
          printfn "Server started"
       ) |> ignore
       0
````
compared with
````
    open System
    open Fable.Import.Express
    open Fable.Core
    open Fable.Core.JsInterop
    [<EntryPoint>]
    let main argv =
        let app = express.Invoke ()

        app.get(U2.Case1 "/",
            (fun req (res:express.Response) _ ->
                ( (res.send("Working now"))|>box )
            )
        ) |> ignore

        app.listen(3000,
            !!(fun _ ->
              printfn "Server started: http://localhost:%i" 3000
            )
        ) |> ignore


        0 // return an integer exit code

````
(this last based on the wrappers in the Sugar module of the example code)

The bit I still don't really understand is why app.get takes a function and forces its result to be boxed, while listen takes an unboxed function instead...


Now obviously in a real situation one would want to encapsulate the low-level stuff in some nice helper module, but it seems potentially easier to write such a helper module from the obj-based code, since what you write can look much closer to the documentation of the original javascript.

I'm not underestimating the difficulties here - and I think Fable so far has done an amazing job of making what it does possible. But given the current state of play, might one be better advised to go directly to helpers from dynamic code, and bypass the import process, at least in some cases?

Gary

**Comment by MangelMaxime** [comment]
The benefit of using the bindings as entry point for the low level stuff is they are directly generate from the d.ts files so they are type safe.

Also, upgrading the binding is much easier because it's automated. Otherwise, you would need to do it manually and it can be very large. 

Binding used, in the code is using an old version of ts2fable and that's why you see some difference in the callback (some boxed and other unboxed)

**Comment by jgrund** [comment]
@bilkusg if It's of any use, here is a production usage of Fable + Node: https://github.com/intel-hpdd/device-scanner

It's using the bindings from https://github.com/fable-compiler/fable-import/tree/master/Node + automated integration / unit testing with: https://github.com/jgrund/fable-jest.

Depending on your need with a HTTP server, express may not be necessary, you could get away with a plain HTTP server, i.e:

https://github.com/intel-hpdd/device-aggregator/blob/master/IML.DeviceAggregatorDaemon/src/Handlers.fs#L30-L63

+ 

https://github.com/intel-hpdd/device-aggregator/blob/master/IML.DeviceAggregatorDaemon/src/Server.fs#L12-L18
