### ISSUE TITLE
Cannot find replacement for System.Decimal::TryParse

### ISSUE THREAD

**Issue by jptarqu** [fable-compiler/Fable#1365]
### Description

When using System.Decimal.TryParse in F#, I get the following error from the fable compiler: 

error FABLE: Cannot find replacement for System.Decimal::TryParse

### Repro code

```
module ConversionHelpers =
    let tryParseWith tryParseFunc = tryParseFunc >> function
        | true, v    -> Some v
        | false, _   -> None

    let tryParseDecimal = tryParseWith System.Decimal.TryParse
```

### Expected and actual results

I was expecting fable to convert it to parseFloat or something like that. 

### Related information

* Fable version (`dotnet fable --version`): 1.3.3
* Operating system: Windows 10 Pro

**Comment by jptarqu** [comment]
Never mind. After doing a "paket update" ( upgrading dotnet-fable to 1.3.11 ), the error went away. I should have known better and do that first, sorry.

**Comment by alfonsogarciacaro** [comment]
No worries! Yes, probably it was added in one of the latest versions, don't remember which. Thanks for checking!
