### ISSUE TITLE
No executable found matching command "dotnet-fable"

### ISSUE THREAD

**Issue by Rizary** [fable-compiler/Fable#1367]
### Description

No executable found matching command "dotnet-fable".

note: i have seen other issue that closed, and still got the same error.

### Repro code

```
D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts
λ dotnet restore
  Restore completed in 8,43 ms for D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src\FableTuts.fsproj.
  Restore completed in 8,09 ms for D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\tools\DotnetCLI.fsproj.
  Restore completed in 47,46 ms for D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\tools\DotnetCLI.fsproj.

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts
λ cd src\

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src
λ dotnet restore
  Restore completed in 14,48 ms for D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src\FableTuts.fsproj.

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src
λ cd ..\

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts
λ dotnet fable
No executable found matching command "dotnet-fable"

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts
λ cd src

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src
λ dotnet fab
No executable found matching command "dotnet-fab"

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src
λ dotnet fable
No executable found matching command "dotnet-fable"

D:\Engineer\ProgLang\F#\FSharp Tutorial\FableTuts\src
λ
```
### Expected and actual results

expected as in tutorials

### Related information

* Operating system:
windows 10

* I use both Powershell and Cmderr
* I use yarn

**Comment by MangelMaxime** [comment]
Hello @Rizary , I suppose you used the Fable template.

The buildings steps change since we wrote the tutorial. 
You can find more info in the [README.md](https://github.com/fable-compiler/fable-templates/tree/master/simple/Content#building-and-running-the-app) file.

You should be able to run: `yarn` and then `yarn start` from the root folder.

@alfonsogarciacaro We probably need to update the docs about this fact, it's been several time I helped people on this subject.

**Comment by Rizary** [comment]
ah that's why. At first i'm afraid to just run yarn start. Anyway, thanks for the help.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Ah, you're right, I forgot the latest template included that change 🤦‍♂️  Yes we need to update that in the web... the warning about checking the README doesn't seem to be enough :wink:
