### ISSUE TITLE
What

### ISSUE THREAD

**Issue by zaaack** [fable-compiler/Fable#1371]
### Description

Please provide a succinct description of your issue.

### Repro code

Please provide the F# code to reproduce the problem.
Ideally, it should be possible to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version (`dotnet fable --version`):
* Operating system:

**Comment by alfonsogarciacaro** [comment]
![whaaat](https://media.giphy.com/media/l2JhEYWETxE0h4uxq/giphy.gif)
