### ISSUE TITLE
No executable found matching command "dotnet-fable"

### ISSUE THREAD

**Issue by runefs** [fable-compiler/Fable#1373]
### Description

following the [guide](http://fable.io/docs/getting-started.html) at I'm unable to start the sample application. I get "No executable found matching command "dotnet-fable" when I try to run from ./src both in docker (xtuc/fable) or directly on my mac

### Repro code
no changes to the sample application

### Expected and actual results

I would expect the application to start but all I get is: "No executable found matching command "dotnet-fable""

**Comment by Zaid-Ajaj** [comment]
Please try `dotnet restore` first from the same directory where you ran `dotnet fable ...`

**Comment by MangelMaxime** [comment]
Hello @runefs please see this https://github.com/fable-compiler/Fable/issues/1367#issuecomment-373702903

**Comment by runefs** [comment]
I'd suggest closing this issue when the getting started guide is accurate. The solution is the above comment however having a faulty "getting started guide" is a potential very high barrier of entry

**Comment by alfonsogarciacaro** [comment]
Ok, I've updated the web. I tried to make the "please check the template README" note more prominent 😄
