### ISSUE TITLE
bigint 0 times anything yields NaN

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#1376]
Consider

```
0I * 1I
```

I would expect this to yield `0I`. Instead, it yields `NaN`.

**Comment by jgrund** [comment]
The above code compiles to:

```js
applyOperator(zero, one, "op_Multiply");
```

`applyOperator` expects at least one of the operands to have `op_Multiply`. If it doesn't (as in this case) it then just tries to perform the op as if both operands where plain number types. neither `0I` or `1I` have an `op_multiply` method which is why we get `NaN` as it tries to multiply two `bigint` object representations.

https://github.com/fable-compiler/Fable/blob/a8d4213e7c3edba82685da95680545c6c363338c/src/js/fable-core/Util.ts#L503-L556

**Comment by jgrund** [comment]
It seems like `op_Multiply(zero, one);` would work here. Is that what should be emitted?

**Comment by alfonsogarciacaro** [comment]
Thanks for catching this, should be fixed in Fable 1.3.14 👍
