### ISSUE TITLE
Stopify 

### ISSUE THREAD

**Issue by ShalokShalom** [fable-compiler/Fable#1378]
I am very curious if this can help the project directly:
http://www.stopify.org/faq.html

**Comment by alfonsogarciacaro** [comment]
Thanks for the link @ShalokShalom. Seems interesting, though a quick look at the web wasn't enough to see how it could fit with Fable. Apparently one of the main advantages is it allows to stop/cancel long running operations, a feature F#/Fable already has with `Async` (though the programmer needs to use it explicitly).

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm closing this as we're trying to avoid dependencies in Fable. Feel free to open a new issue if you think there's any aspect of Stopify that we could benefit from by porting it to Fable.
