### ISSUE TITLE
Fable doesn't compile the project

### ISSUE THREAD

**Issue by CodEFouR** [fable-compiler/Fable#1380]
### Description

Fable doesn't compile the project. It just hangs and nothing happens.

<img width="561" alt="jietu20180328-221105" src="https://user-images.githubusercontent.com/594939/38034474-f16b8702-32d4-11e8-85ba-f3c4271773ce.png">

My `package.json` is like:
```
{
  "private": true,
  "devDependencies": {
    "babel-core": "^6.26.0",
    "babel-loader": "^7.1.4",
    "babel-preset-env": "^1.6.1",
    "fable-loader": "^1.1.6",
    "fable-utils": "^1.0.6",
    "webpack": "3.8.1",
    "webpack-dev-server": "^3.1.1"
  },
  "scripts": {
    "build": "webpack --config webpack.config.js"
  }
}
```
And my `webpack.config.js` is like
```
var path = require("path");
var fableUtils = require("fable-utils");

function resolve(relativePath) {
    return path.join(__dirname, relativePath);
}

var babelOptions = fableUtils.resolveBabelOptions({
  presets: [
    ["env", {"modules": false}]]
});

module.exports = {
  entry: resolve('./web.fsproj'),
  output: {
    filename: 'bundle.js',
    path: resolve('./build')
  },
  resolve: {
    modules: [resolve("./node_modules")]
  },
  module: {
    rules: [
      {
        test: /\.fs(proj|x)?$/,
        use: {
          loader: "fable-loader",
          options: {
            define: ["DEBUG"],
            babel: babelOptions
          }
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: babelOptions
        }
      }
    ]
  }
};
```
The project structure is like
<img width="237" alt="jietu20180328-221358" src="https://user-images.githubusercontent.com/594939/38034661-580bd764-32d5-11e8-8fe9-dcca5d1d07e6.png">

I'm running `dotnet fable yarn-run build`.

### Expected and actual results

Should show `parse web.fsproj` and compile the project.

### Related information
* Fable version (`dotnet fable --version`): 1.3.12
* Operating system: Reproducible on Windows 10 as well as Mac High Sierra

**Comment by MangelMaxime** [comment]
Is it possible to share your project ?

**Comment by CodEFouR** [comment]
Sure the zip file contains the project but not `node_modules/packages/.paket`. 
[web.zip](https://github.com/fable-compiler/Fable/files/1856500/web.zip)

**Comment by inosik** [comment]
I can build this project on my MacBook with this .NET SDK:

```
$ dotnet --info 
.NET Command Line Tools (2.1.101)

Product Information:
 Version:            2.1.101
 Commit SHA-1 hash:  6c22303bf0

Runtime Environment:
 OS Name:     Mac OS X
 OS Version:  10.13
 OS Platform: Darwin
 RID:         osx.10.12-x64
 Base Path:   /usr/local/dotnet/sdk/2.1.101/

Microsoft .NET Core Shared Framework Host

  Version  : 2.0.6
  Build    : 74b1c703813c8910df5b96f304b0f2b78cdf194d
```

The only thing I changed was to add `storage: none` to `paket.dependencies` and `paket.lock`, but that shouldn't matter.

I can try to build it on my Windows 10 workstation in the office tomorrow, but it actually looks correct to me. In the meantime, can you try to build it with `dotnet fable yarn-run build --verbose`?

**Comment by CodEFouR** [comment]
Tried 
```
  "scripts": {
    "build": "webpack --verbose --config webpack.config.js"
  }
```
and `dotnet fable yarn-run build --verbose` but no more info shows.

**Comment by CodEFouR** [comment]
I had some another try and collected some information.
In console 1, `dotnet fable start --verbose --timeout 30000` starts the Fable daemon. In console 2, `yarn run build` starts webpack. Before 30s timeout, console 2 doesn't show anything. After 30s, console 2 shows the following: 
<img width="1087" alt="jietu20180329-134113" src="https://user-images.githubusercontent.com/594939/38071983-e13405ee-3356-11e8-9b44-4744cb82ab53.png">
`Unexpected end of JSON input`, what does that mean?

**Comment by humhei** [comment]
If i doesn't run `fable daemon`, I will get same error
![image](https://user-images.githubusercontent.com/25994449/38072419-bc2d5ab4-3358-11e8-8413-d4ff9cdbccfa.png)
Can you show your fable daemon start image
Something like below
![image](https://user-images.githubusercontent.com/25994449/38072467-f5ea3218-3358-11e8-92fb-34d168344bbc.png)

**Comment by humhei** [comment]
I wonder if [fable.template](https://github.com/fable-compiler/fable-templates) worked for ?

**Comment by CodEFouR** [comment]
@humhei Your error is not same with mine which says "Unexpected end of JSON input". I show you my console 1's output:
<img width="566" alt="jietu20180329-135912" src="https://user-images.githubusercontent.com/594939/38072582-934ddabe-3359-11e8-8642-f9a07a128973.png">
Yes the template works but I don't see why my configuration doesn't run.

**Comment by humhei** [comment]
It's really strange 😕 
I tested [web.zip](https://github.com/fable-compiler/Fable/files/1856500/web.zip) in my win10
It worked fine for me.

> The only thing I changed was to add storage: none to paket.dependencies and paket.lock, but that shouldn't matter.

**Comment by inosik** [comment]
Can you try to sprinkle some `console.log` statements in the `fable-loader` and `fable-utils` modules? These lines are probably the most relevant:

https://github.com/fable-compiler/Fable/blob/5af0f44cb4b04c76ede416dded3e92ef1205f493/src/js/fable-utils/client.js#L38-L64

https://github.com/fable-compiler/Fable/blob/5af0f44cb4b04c76ede416dded3e92ef1205f493/src/js/fable-loader/index.js#L64

The error message is raised by `JSON.parse` in `fable-loader`, so I would first check what the actual string looks like.

Sorry for the inconvenience, but I have no idea how we could fix this without being able to reproduce this.

**Comment by CodEFouR** [comment]
I have added something in `client.js`:
```
exports.send = function(port, msg) {
  console.log("Msg = " + msg);
  return new Promise((resolve, reject) => {
    var buffer = "";
    var client = new net.Socket(), resolved = false;

    client.connect(port, HOST, function() {
      console.log("Connect: " + msg);
      client.write(msg);
    });

    client.on('error', function(err) {
      console.log("Error: " + err);
      if (!resolved) {
        resolved = true;
        reject(err);
      }
    });

    client.on('data', function(data) {
      console.log("Data: " + data);
      buffer += data.toString();
    });

    client.on('close', function() {
      console.log("Close");
      if (!resolved) {
        resolved = true;
        resolve(buffer);
      }
    });
  });
}
```
and `index.js` now is:
```
    fableUtils.client.send(port, JSON.stringify(msg)).then(r => {
        console.log("JSON = " + r);
        var data = JSON.parse(r);
        console.log("Parsed JSON = " + r);
        if (data.error) {
            callback(new Error(data.error));
        }
.....
```
And I start `dotnet fable start --timeout 30000`, then in another console `yarn run build`. In 30s console 2 shows the error like the picture below. I guess this is the expected output, maybe this is not why fable-loader hangs. 
![image](https://user-images.githubusercontent.com/594939/38076126-459935a8-3367-11e8-882c-53f25af065d8.png)

**Comment by CodEFouR** [comment]
I think the issue could be closed. I did `.paket\paket clear-cache` and everything works like a charm. Thank you all.

**Comment by inosik** [comment]
Maybe some referenced package/DLL got corrupted somehow? I just tried to reproduce that by removing a bunch of characters from `Fable.Core.dll` and got something similar to what @CodEFouR describes: No output from Fable daemon and Webpack hanging.

I think the `MailboxProcessor` in the daemon throws an exception which we don't catch. `MailboxProcessor`s don't crash the process but publish exceptions on their [`Error` event][error-event]. We probably should handle it.

  [error-event]: https://msdn.microsoft.com/visualfsharpdocs/conceptual/mailboxprocessor.error%5b%27msg%5d-property-%5bfsharp%5d
