### ISSUE TITLE
FABLE translates unsigned long integer ranges into infinite loops

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/Fable#1383]
### Description

The F# code `[0UL..10UL]` when translated via FABLE leads to an infinite loop

### Repro code

Please provide the F# code to reproduce the problem.
Ideally, it should be possible to easily turn this code into a unit test.

```
let main(argv[])=
    printfn "%A" [0UL..10UL]
```

### Expected and actual results

Expected: list of 11 numbers
Actual: loops forever

### Related information

fable.io does this. Also FABLE 1.0.6

* Fable version (`dotnet fable --version`):
* Operating system: win 10  (translating to .Net Core 2.1.101)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the report, I will look into this :+1:

**Comment by tomcl** [comment]
On a related matter. I had a whole load of code simulating ALU ops using uint32 as a base type, with a few type conversions. I got into lots of trouble because JS and F# do these differently. Specifically:

`(-1 |> int64 |> uint32)` is 0 in JS and 4294967295 in F#. 
`(-1 |> int32 |> uint64)` similar.

Conversions of  negative signed numbers to unsigned saturate (at 0) in JS but truncate higher order bits in F# if the number sizes are different.

If the number sizes are the same:

`(-1 |> uint32 |> int32)`

F# and JS both do the same thing (no change in numeric representation bits).

I'd guess that this might be the reason for the loop going wrong...

**Comment by tomcl** [comment]
And another related issue: System.Int32.TryParse (and therefore also Parse) are wrong in one way:
When parse fails in tryParse the return is Nil, not (false, initial) (if line 40 int32.ts needs a then part)

**Comment by alfonsogarciacaro** [comment]
Hi @tomcl, thanks a lot for the reports. It'd be great if you could send a PR with a fix (if possible) and/or a failing test. About longs, most of numeric types are translated to JS number by Fable (even `decimal`, which we need to change), except for longs and big integers. We have several tests for number conversions but there may still be some rough edges. We're currently working on the next major version, but I'm also investigating to release a fix for Fable 1 as soon as possible.

**Comment by tomcl** [comment]
@alfonsogarciacaro 

The long range lock-up issue remains with 2.0.0-beta-003

A simple range of longs, anywhere in code, creates an infinite loop in the CLI and also REPL2

```
let y = [0L..10L]
```

* The REPL2 code is: `ofseq(range( starting long, end long)` 
* the start/end longs are correct.

I could probably PR this if I knew whether the compiler uses the same JS translation, and if so where ofseq and range are located? I'm still not good at finding my way round the compiler internals!

It would be nice to deal with as many as possible of the integer corner cases...

**Comment by alfonsogarciacaro** [comment]
Sorry, I just noticed the range function didn't deal with longs so I created a specialized one for them. Should be fixed in the next release :+1:
