### ISSUE TITLE
print AST

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1384]
This is a question rather than an actual problem.
I'm currently working on a presentation about Fable and I'd like to show the intermediate steps of how Fable compiles the F# to JS.

I took an easy example

```fsharp
let add a b = a + b
```

And now I want to show how the Fable AST looks like.
To compare with the Babel AST later on.

I'm also showing in a slide how the FCS AST looks like to illustrate the differences.

```fsharp
[Let
 (false,
  [Binding
     (None,NormalBinding,false,false,[],
      PreXmlDoc
        (Microsoft.FSharp.Compiler.Range+pos,
         Microsoft.FSharp.Compiler.Ast+XmlDocCollector),
      SynValData
        (None,
         SynValInfo
           ([[SynArgInfo ([],false,Some a)];
             [SynArgInfo ([],false,Some b)]],
            SynArgInfo ([],false,None)),None),
      LongIdent
        (LongIdentWithDots ([add],[]),None,None,
         Pats
           [Named
              (Wild Program.fs (2,8--2,9) IsSynthetic=false,a,false,
               None,Program.fs (2,8--2,9) IsSynthetic=false);
            Named
              (Wild Program.fs (2,10--2,11) IsSynthetic=false,b,
               false,None,Program.fs (2,10--2,11) IsSynthetic=false)],
         None,Program.fs (2,4--2,11) IsSynthetic=false),None,
```

What functions do I use to print the AST?

**Comment by alfonsogarciacaro** [comment]
We had some rough Fable AST printers but I [commented them out because they were causing problems](https://github.com/fable-compiler/Fable/blob/f17547bc093468b1d2d577b9e201cac55f7cbcd0/src/dotnet/dotnet-fable/Printers.fs#L115-L116). We could try uncommenting it and see if it works with the quicktest, by [uncommenting also this line](https://github.com/fable-compiler/Fable/blob/f17547bc093468b1d2d577b9e201cac55f7cbcd0/src/tools/rollup.config.js#L19).

**Comment by nojaf** [comment]
Thanks Alfonso, I was able to print the Fable AST with those changes.
```fsharp
Entity
  (QuickTest,
   [MemberOrFunctionOrValue
      (val add,[[val a]; [val b]],
       Call
  (None,val op_Addition,[],
   [type Microsoft.FSharp.Core.int; type Microsoft.FSharp.Core.int;
    type Microsoft.FSharp.Core.int],[Value val a; Value val b]))])
```

As for the Babel AST, I'm guessing I want to print something in [Fable2Babel](https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/Fable2Babel.fs#L1272)?
I'm expecting the Babel AST is just some json right?

**Comment by alfonsogarciacaro** [comment]
Ah, great! Sometimes printing the type name gave me some issues but hopefully is fixed now. In the next version I will uncomment those lines (you still have to opt-in the AST printer, so it shouldn't affect anybody else). About the Babel AST, it is converted to JSON before sending it to the JS client yest. Whenever I had to check, I either print it in the JS client (fable-splitter, fable-loader) or [right before sending the json](https://github.com/fable-compiler/Fable/blob/f17547bc093468b1d2d577b9e201cac55f7cbcd0/src/dotnet/dotnet-fable/StateUtil.fs#L122) over the TCP channel.

**Comment by nojaf** [comment]
Thanks, changed some code in the rollup-loader and got the babel ast.
