### ISSUE TITLE
Use https for fable.io

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1396]
### Description

Since the 1 May, Github now support [Http for custom domain over Github Pages](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/).

Would be nice to activate https support for http://fable.io

**Comment by alfonsogarciacaro** [comment]
That's a great idea. I guess we need a certificate for that, do you know hot to get it? (never have tried it myself).

**Comment by MangelMaxime** [comment]
I have no idea... the links i provided seems to speak only about IP address don't know why.

Perhpas @whitetigle know something about it. I know he used Let’s Encrypt recently.

**Comment by whitetigle** [comment]
Hi!
Basically there are two ways to get the certificate:

1. you buy it from your registrar
2. you generate it using let's Encrypt

But, regarding GitHub, I don't know if anything is needed:

> If you are using CNAME or ALIAS records for your custom domain, you’re all set and your site should be accessible over HTTPS

( source: https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)

**Comment by whitetigle** [comment]
So the best thing would be... to check ;)

**Comment by alfonsogarciacaro** [comment]
[We do use CNAME](https://github.com/fable-compiler/fable-compiler.github.io/tree/dev/public) but apparently it's not enough :/ I'd have to dig into this deeper:

![image](https://user-images.githubusercontent.com/8275461/39531826-5eb7f102-4e2c-11e8-83a3-8e38641acd35.png)

**Comment by whitetigle** [comment]
Ok on GitLab, I needed to add a certificate which I managed to create using Let's Encrypt and then it would serve the pages using https.

I'll check how it works for github. 👍

**Comment by whitetigle** [comment]
Ok it works on my side:

![image](https://user-images.githubusercontent.com/883207/39533055-652f1b58-4e2e-11e8-877d-d758bf9767b0.png)

**Comment by whitetigle** [comment]
Regarding ([CNAME](https://github.com/fable-compiler/fable-compiler.github.io/blob/dev/public/CNAME)) was that some special feature with github pages?

Now [it seems](https://help.github.com/articles/setting-up-a-www-subdomain/) you'll have to create a CNAME record for your domain.

**Comment by bzuu** [comment]
Looking at the DNS records it seems fable.io is not set up using CNAME but A records instead, e.g. using DNS lookup on MXToolbox.com I find these:

Type | Domain Name | IP Address | TTL
-- | -- | -- | --
A | fable.io | 192.30.252.153 | 24 hrs
A | fable.io | 192.30.252.154 | 24 hrs

As far as I can tell the A records need to be updated with new IP addresses in order to support enabling HTTPS. The exact steps to be followed are documented [here](https://help.github.com/articles/setting-up-an-apex-domain/#configuring-a-records-with-your-dns-provider). In particular step 4 seems important.

**Comment by alfonsogarciacaro** [comment]
Thanks @bzuu! We're having some trouble at the moment because we're not the owners of the domain, we're just "borrowing" it. But I contacted the owner to see if it's possible to make this change. Let's see.

**Comment by bzuu** [comment]
Thanks @alfonsogarciacaro for the update! Just want to let you know I tried the steps I linked to on my own domain and it seems to work just as expected. So updating the IP addresses on the DNS server should probably be enough.

**Comment by alfonsogarciacaro** [comment]
We're a bit in trouble now because the original owner says he didn't renovate but the domain is taken so I don't know if someone else has taken it :/ Although I guess in that case it shouldn't be working now for the Fable site 🤔

**Comment by whitetigle** [comment]
Zut!

```
Domain Name: FABLE.IO 
Registry Domain ID: D503300000040542996-LRMS 
Registrar WHOIS Server: whois.101domain.com 
Registrar URL: https://www.101domain.com 
Updated Date: 2018-02-08T11:29:45Z 
Creation Date: 2012-02-09T11:26:31Z 
Registry Expiry Date: 2019-02-09T11:26:31Z 
Registrar Registration Expiration Date: 
Registrar: 101domain GRS Ltd 
Registrar IANA ID: 1011 
Registrar Abuse Contact Email: abuse@101domain.com 
Registrar Abuse Contact Phone: +1.8582954626 
Reseller: 
Domain Status: clientTransferProhibited https://icann.org/epp#clientTransferProhibited 
Registrant Organization: Digital Privacy Corporation 
Registrant State/Province: CA 
Registrant Country: US
```

**Comment by alfonsogarciacaro** [comment]
Closing in favor of https://github.com/fable-compiler/fable-compiler.github.io/issues/27
