### ISSUE TITLE
dotnet fable returns No executable found matching command "dotnet-fable"

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#1408]
See below image:

![image](https://user-images.githubusercontent.com/4114592/40527118-aa62706a-5ffb-11e8-9f28-5a8ae788fe00.png)

**Comment by MangelMaxime** [comment]
@OnurGumus You just installed the template but didn't create a project using it.

Follow the instruction on this page: 
http://fable.io/docs/getting-started.html

**Comment by OnurGumus** [comment]
@MangelMaxime  I am following those instructions already. If you look at the bottom of the page start and --help commands are mentioned they also fail similiarly.

PS D:\Projects\FSharp> dotnet fable start
No executable found matching command "dotnet-fable"
PS D:\Projects\FSharp> dotnet fable --help
No executable found matching command "dotnet-fable"
PS D:\Projects\FSharp>

**Comment by OnurGumus** [comment]
This also fails :
PS D:\Projects\Fable> dotnet new fable -n FableApp -lang F#
Usage: new [options]

Options:
  -h, --help          Displays help for this command.
  -l, --list          Lists templates containing the specified name. If no name is specified, lists all templates.
  -n, --name          The name for the output being created. If no name is specified, the name of the current directory is used.
  -o, --output        Location to place the generated output.
  -i, --install       Installs a source or a template pack.
  -u, --uninstall     Uninstalls a source or a template pack.
  --nuget-source      Specifies a NuGet source to use during install.
  --type              Filters templates based on available types. Predefined values are "project", "item" or "other".
  --force             Forces content to be generated even if it would change existing files.
  -lang, --language   Filters templates based on language and specifies the language of the template to create.


Unable to determine the desired template from the input template name: fable.
The following templates partially match the input. Be more specific with the template name and/or language.


Perhaps it has to do with the .NET SDK version I am using.

**Comment by Nhowka** [comment]
The `dotnet-fable` is a CLI tool that will be installed from nuget on your project when you restore it, it's not something you can normally use globally outside of the project context.

**Comment by OnurGumus** [comment]
@Nhowka See the above post. Even  `dotnet new fable -n FableApp -lang F#`  command fails.

**Comment by OnurGumus** [comment]
Thanks for clarifications. Now everything works. I will close the issue now. Perhaps it was my misunderstanding.

**Comment by alfonsogarciacaro** [comment]
Happy to hear you solved it, thanks a lot @Nhowka and @MangelMaxime for you help!

**Comment by hlizard** [comment]
choose a version from https://www.nuget.org/packages/Fable#versions-body-tab
make a file ```.\.config\dotnet-tools.json```
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "fable": {
      "version": "4.0.0-snake-island-alpha-012",
      "commands": [
        "fable"
      ]
    }
  }
}
```
```
dotnet tool restore
dotnet fable MyScript.fsx --lang python
```
