### ISSUE TITLE
Fable compiled as netcoreapp2.1 is failing

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1413]
I upgraded Fable 2 (`dev2.0` branch) to netcore2.1. It was easy and it worked fine when running the tool locally [as in this script](https://github.com/fable-compiler/Fable/blob/ac61fce3b4ebe5a6551f6d48a60142bc5953cffe/src/tools/quicktest.sh#L38-L42). However, when distributing it as a Nuget package (version 2.0.0-alpha-008, [commit reference](https://github.com/fable-compiler/Fable/commit/28e07de2a4e33835a2bc2b7a8ed0377f01b6a8b0#diff-1715577b9f0a4893c7db757910fc247a)), it fails with the following error:

```
~/d/f/s/r/src ❯❯❯ dotnet fable fable-splitter
Fable (2.0.0-alpha-008) daemon started on port 49195
CWD: /Users/alfonsogarciacaronunez/dev/fable/samples/react-todomvc
/Users/alfonsogarciacaronunez/dev/fable/samples/react-todomvc/node_modules/.bin/fable-splitter
fable: Compilation started at 01:23:27
CWD: /Users/alfonsogarciacaronunez/dev/fable/samples/react-todomvc/src
dotnet restore
  Restore completed in 23.93 ms for /Users/alfonsogarciacaronunez/dev/fable/samples/react-todomvc/src/React.TodoMVC.fsproj.
  Restore completed in 47.51 ms for /Users/alfonsogarciacaronunez/dev/fable/samples/react-todomvc/src/React.TodoMVC.fsproj.

Parsing ./React.TodoMVC.fsproj...
ERROR: Could not load file or assembly 'Fable.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

   at Fable.CLI.Agent.compile(Compiler com, Project project)
   at Fable.CLI.Agent.loop@223-7.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncBuilderImpl.callA@522.Invoke(AsyncParams`1 args)
ERROR: Could not load file or assembly 'Fable.Core, Version=2.0.0.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.

Closing Fable daemon...
~/d/f/s/r/src ❯❯❯
```

Any ideas? @ncave @enricosada 

> Note the Fable.Core package still target **netstandard2.0**

**Comment by ncave** [comment]
@alfonsogarciacaro idk, some version mismatch? perhaps increment the minor version? or clear packages?

**Comment by ncave** [comment]
@alfonsogarciacaro I feel your pain, I can't compile FSharp.Core with netcore 2.1 too for some reason (FCS is ok though). Let me know if you want me to switch FCS-Fable back to netcore 2.0 (2.1.201 is the latest).

**Comment by alfonsogarciacaro** [comment]
Yeah, it's weird. It may be some obscure assembly loading issue. I wonder why it works locally and why it fails when referenced as a package (exactly at that point). I replaced all `netcoreapp2.1` to `netcoreapp2.0` in all .fsproj files in the repo, so hopefully it should be fine now.

dotnet-fable 2.0.0-alpha-009 nuget pkg is working :)

**Comment by kunjee17** [comment]
@alfonsogarciacaro I guess you hit this issue. https://github.com/dotnet/sdk/issues/2171#issuecomment-389018042 . I normally switch `global.json` to other sdk version to make it work. Currently with 2.1.300 it is working... as per last status.

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip @kunjee17! Hmm, IIRC I did set global.json to 2.1.300 when check but I'll give it a new try just in case :)

**Comment by alfonsogarciacaro** [comment]
@ncave I did this a new try by using dotnet SDK 2.1.401 (I changed global.json) and changing the TargetFramework to `netcoreapp2.1`. Then I created a .nupkg (using Release config) and installed it in another project using local sources). However when I tried to run `dotnet fable` in the test project I got SO exceptions during the compilation :(

**Comment by ncave** [comment]
@alfonsogarciacaro Bummer, why does it work locally on 2.1.401 then (tests/bench are passing), what's the difference?

**Comment by alfonsogarciacaro** [comment]
No idea, I will create a branch to reproduce and open an issue in visualfsharp repo.

**Comment by alfonsogarciacaro** [comment]
Damn, now I'm trying to reproduce and I can't 😬 Maybe I did something wrong before? If possible, could you please have a look [at this commit](https://github.com/fable-compiler/Fable/commit/a4ee32184606f02f2829e5302aabc9bb5a3cc1cc) and tell me if I'm doing something wrong? In theory it should allow you to use the package by following these steps:

```
git clean -xfd
sh build.sh Bootstrap
cd samples/react-todomvc
yarn
yarn build-pkg
```

This gives me `No executable found matching command "dotnet-fable"`, but Nuget doesn't complain when running `dotnet restore src` (it's a postinstall script in package.json). Also, `yarn build-local` (which calls `build/fable/dotnet-fable.dll` works).

**Comment by ncave** [comment]
@alfonsogarciacaro Yeah, I get the same thing on Windows.
Perhaps there is something wrong with the tool package, here is what I get trying to install it:
```
cd Fable
dotnet tool install --global dotnet-fable --version 2.0.0-beta-100
error NU1212: Invalid project-package combination for dotnet-fable 2.0.0-beta-100.
DotnetToolReference project style can only contain references of the DotnetTool type
The tool package could not be restored.
Tool 'dotnet-fable' failed to install.
```

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm trying to follow this tutorial (basically it says you only need to add `<PackAsTool>true</PackAsTool>` to the .fsproj) but still no luck. Maybe @enricosada can help?

**Comment by enricosada** [comment]
Let me check tomorrow morning

From mobile

--
Enrico Sada
@enricosada
________________________________

**Comment by nojaf** [comment]
So what happens if you install fable global tool as a local tool?
`dotnet tool install fable --tool-path .\fable-compiler`.
`fable.exe` would be installed in the `fable-compiler` folder in the project.
Would that solve anything?

**Comment by alfonsogarciacaro** [comment]
I think that's possible @nojaf. But from what I understand from [this comment from MSFT](https://github.com/dotnet/cli/issues/7715#issuecomment-417082227) is that it's still unclear how to specify the version of the tool in the repo (as we do with Paket now). That's why I'd prefer to wait and see before making the move to local tools.

**Comment by alfonsogarciacaro** [comment]
Fable 2.1 will fix this as we don't have restrictions on the binary target framework when putting it in an npm package.
