### ISSUE TITLE
Unable to try out Fable (2.0.0-alpha-009) because of missing rootDir argument => incompatible fable-loader

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1414]
I wanted to give the latest update a go and try out a few things but it when I run my project using Fable 2.0.0-alpha-009, I get the following error: 
```
ERROR: Missing argument rootDir
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Fable.CLI.Parser.parse(String msg)
   at Fable.CLI.Agent.loop@205-5.Invoke(Tuple`2 _arg1)
```
Where `rootDir` is a new field in the [Message](https://github.com/fable-compiler/Fable/blob/dev2.0/src/dotnet/Fable.Compiler/CLI/Parser.fs#L9-L16) type that Fable daemon expects from fable-loader to send but latest published fable-loader (1.1.6) does not send that information.

Looking at the source code of dev2.0 it seems that the current fable-loader there *does* send the `rootDir` information but it isn't published yet. 

Can you please either: 
 - Publish the new fable-loader
 - Provide a fallback to get the root directory from the CLI using something like;

```fs
let rec findRoot dir =
    let paketDeps = Path.Combine(dir, "paket.dependencies") 
    if File.Exists paketDeps then dir
    else
        let parent = Directory.GetParent(dir)
        if isNull parent then failwith "Couldn't find root directory"            
        findRoot parent.FullName

let rootDir = findRoot (Environment.GetCurrentDirectory()) 
``` 
> Assuming that the root directory is the solution level directory next to paket.dependencies

* Fable version (`dotnet fable --version`): 2.0.0-alpha-009
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj You need to use the alpha version of fable-loader: https://github.com/MangelMaxime/fulma-demo/pull/5/files#diff-b9cfc7f2cdf78a7f4b91a753d10865a2R29

**Comment by Zaid-Ajaj** [comment]
Thanks a lot @MangelMaxime, I did search npm but didn't find the alpha version of fable-loader. Updated and the loader is working, but I now get another error that seem to come from outdated babel config:
```
Module build failed: Error: unknown: You must pass a scope and parentPath unless traversing a Program/File. Instead of that you tried to traverse a "Identifier" node without passing scope and parentPath.
    at traverse (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\index.js:73:13)
    at File.buildCodeFrameError (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\index.js:432:35)
    at Scope.checkBlockScopedCollisions (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\scope\index.js:398:27)
    at Scope.registerBinding (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\scope\index.js:592:16)
    at Scope.registerDeclaration (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\scope\index.js:496:14)
    at Object.BlockScoped (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\scope\index.js:244:28)
    at Object.newFn (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\visitors.js:318:17)
    at NodePath._call (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\path\context.js:76:18)
    at NodePath.call (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\path\context.js:44:14)
    at NodePath.visit (C:\projects\Fable.SimpleJson\node_modules\babel-traverse\lib\path\context.js:105:12)
```
Do I need to update babel loader/preset/config as well?

**Comment by MangelMaxime** [comment]
Probably yes, I never ported a project Fable 2 yet.

**Comment by Zaid-Ajaj** [comment]
Then only one man knows da wae . . . @alfonsogarciacaro please help 😄 (No rush though, I am just interested in testing out the new stuff)

**Comment by alfonsogarciacaro** [comment]
Hi @Zaid-Ajaj! Sorry, please hold on a bit, I found out some nasty bugs in Fable 2 this weekend and I'm trying to fix them. As soon as this is ready I'll push a new version and publish a post on how to upgrade (for you can see [this PR](https://github.com/MangelMaxime/fulma-demo/pull/5) and clone [this branch](https://github.com/alfonsogarciacaro/fulma-demo/tree/fable2)).

I will also try to fix #1411 for Fable 1.3 :)

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro A post for upgrading (and the compilation differences) would be just great amazing, I look forward to it :smile:

> I found out some nasty bugs in Fable 2 this weekend and I'm trying to fix them. 

Are these bugs that us mortals can do something about? 

I was trying to get a minimal repro of the config of the upgraded fulma-demo but it was a bit complicated using too many stuff, instead I am upgrading to Fable 2 on one of my little libraries like [SimpleJson](https://github.com/Zaid-Ajaj/Fable.SimpleJson) because it only needs the minimal loaders (fable/babel)

For reference, here is config (that doesn't work):

### package.json
```json
{
  "private": true,
  "scripts": {
    "build": "webpack -p",
    "start": "webpack-dev-server",
    "test": "node ./node_modules/qunitjs/bin/qunit public/bundle.js"
  },
  "devDependencies": {
    "@babel/runtime": "^7.0.0-beta.49",
    "@babel/core": "^7.0.0-beta.48",
    "@babel/polyfill": "^7.0.0-beta.49",
    "@babel/preset-env": "^7.0.0-beta.48",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.0-beta",
    "fable-loader": "^2.0.0-alpha-002",
    "fable-utils": "^1.0.6",
    "loglevel": "^1.6.0",
    "qunitjs": "^2.4.1",
    "webpack": "^4.8.1",
    "webpack-cli": "^3.0.1",
    "webpack-dev-server": "^2.9.7"
  }
}
```
### webpack.config.js
```js
var path = require("path");
var webpack = require("webpack");
var fableUtils = require("fable-utils");


function resolve(filePath) {
  return path.join(__dirname, filePath)
}

var babelOptions = {
  presets: [
    ["@babel/preset-env", {
        "modules": true,
        "useBuiltIns": "usage",
    }]
  ]
};

var isProduction = process.argv.indexOf("-p") >= 0;
console.log("Bundling for " + (isProduction ? "production" : "development") + "...");

module.exports = {
  devtool: "source-map",
  entry: resolve('./test/Tests.fsproj'),
  output: {
    filename: 'bundle.js',
    path: resolve('./public'),
  },
  resolve: {
    modules: [resolve("./node_modules/")]
  },
  devServer: {
    contentBase: resolve('./public'),
    port: 8080
  },
  module: {
    rules: [
      {
        test: /\.fs(x|proj)?$/,
        use: {
          loader: "fable-loader",
          options: {
            babel: babelOptions,
            define: isProduction ? [] : ["DEBUG"]
          }
        }
      },
      {
        test: /\.js$/,
        exclude: /node_modules/,
        use: {
          loader: 'babel-loader',
          options: babelOptions
        },
      }
    ]
  }
};
```
### paket.dependencies
```
group Main
    source https://api.nuget.org/v3/index.json
    storage:none
    
    nuget FSharp.Core
    nuget Fable.Core >= 2.0.0-alpha-006
    nuget Fable.Parsimmon
    clitool dotnet-fable ~> 2.0.0-alpha-009

group Build
  source https://api.nuget.org/v3/index.json

  nuget FAKE
```
and the weird error I get from building
```
Module build failed: Error: Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel. (While processing preset: "C:\\projects\\Fable.SimpleJson\\node_modules\\@babel\\preset-env\\lib\\index.js")
    at throwVersionError (C:\projects\Fable.SimpleJson\node_modules\@babel\helper-plugin-utils\lib\index.js:65:11)
    at Object.assertVersion (C:\projects\Fable.SimpleJson\node_modules\@babel\helper-plugin-utils\lib\index.js:13:11)
    at _default (C:\projects\Fable.SimpleJson\node_modules\@babel\preset-env\lib\index.js:150:7)
    at C:\projects\Fable.SimpleJson\node_modules\@babel\helper-plugin-utils\lib\index.js:19:12
    at C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\options\option-manager.js:317:46
    at Array.map (<anonymous>)
    at OptionManager.resolvePresets (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\options\option-manager.js:275:20)
    at OptionManager.mergePresets (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\options\option-manager.js:264:10)
    at OptionManager.mergeOptions (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\options\option-manager.js:249:14)
    at OptionManager.init (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\options\option-manager.js:368:12)
    at File.initOptions (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\index.js:212:65)
    at new File (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\file\index.js:135:24)
    at Pipeline.transformFromAst (C:\projects\Fable.SimpleJson\node_modules\babel-core\lib\transformation\pipeline.js:69:16)
    at transformBabelAst (C:\projects\Fable.SimpleJson\node_modules\fable-loader\index.js:36:18)
    at Loader.fableUtils.client.send.then.r (C:\projects\Fable.SimpleJson\node_modules\fable-loader\index.js:96:35)
```

**Comment by alfonsogarciacaro** [comment]
> Are these bugs that us mortals can do something about?

You probably could have fixed faster than me but I took a long time to identify them ;) The new in-demand reflection system I'm trying for Fable 2 (generating type info whenever you do `typeof<Foo>` instead of attaching it to every type) was conflicting with recursive types (like `type MyList<'T> = Cons of 'T * MyList<'T> | Nil`) but it seems I managed to fix it in 2.0.0-alpha-011 :)

> BTW, that version also uses a default value for `rootDir` so in theory it should be compatible with current fable-loader (I published the alpha version using tag `next` to prevent people installing it accidentally), but I haven't tested it.

About the error:

```Requires Babel "^7.0.0-0", but was loaded with "6.26.3". If you are sure you have a compatible version of @babel/core, it is likely that something in your build process is loading the wrong version. Inspect the stack trace of this error to look for the first entry that doesn't mention "@babel/core" or "babel-core" to see what is calling Babel.```

I've seen it too. I'm not sure but I think you may be able to fix it if you change the following lines in your config:

```js
      {
        test: /\.fs(x|proj)?$/,
        use: {
          loader: "fable-loader",
          options: {
            babel: babelOptions,
            define: isProduction ? [] : ["DEBUG"]
          }
        }
      },
```

to:

```js
          {
              test: /\.fs(proj)?$/,
              use: "fable-loader"
          },
```

> fable-loader 2 alpha will define `DEBUG` automatically if Webpack mode is "development".

The important part is not passing `babelOptions` to fable-loader (this is ok because will be transformed by the babel-loader in the next step). fable-loader is still using the _old_ `babel-core` 6 (vs the _new_ `@babel/core` 7) to parse the AST and to apply a couple of custom plugins, but if you pass presets or plugins meant for Babel 7, the error will be thrown.

> I have to update fable-loader to Babel 7 but it's tricky because I couldn't find type definitions or documentation for the new API, and just replacing `require("babel-core")` with `require("@babel/core")` didn't work.

**Comment by Zaid-Ajaj** [comment]
Injecting type information only at call site looks very promising! Simplifying the options of fable-loader did solve the the weird babel error but now the error is just a duplicate of #1415 So I will just wait for that :smile:

**Comment by alfonsogarciacaro** [comment]
Hmm, unfortunately that kind of error is not general and must be fixed in each situation. Do you have a branch I can clone to reproduce it?

**Comment by Zaid-Ajaj** [comment]
[Here is the repro](https://github.com/Zaid-Ajaj/simple-json-repro) I also got some warning about not finding an exported function from .js file when importing it (from the Fable.Parsimmon library) 

running `./build.sh RunTests` on a fresh clone should get you all the warnings and errors

**Comment by alfonsogarciacaro** [comment]
Awesome @Zaid-Ajaj! Thanks to the repro and the tests I managed to fix some issues in Fable 2 and finally Simple.Json is working with dotnet-fable 2.0.0-alpha-15. I sent a PR to update the dependencies and also make the webpack config a bit simpler :) https://github.com/Zaid-Ajaj/simple-json-repro/pull/1
