### ISSUE TITLE
DateTime parsing

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1422]
### Description

This code is running over .Net but not Fable 2.

```fs
let dateString = "05/01/2008 +1:00"
let offsetDate = DateTimeOffset.Parse(dateString)
```

**Comment by alfonsogarciacaro** [comment]
Should be fixed in dotnet-fable 2.0.0-alpha-018

**Comment by MangelMaxime** [comment]
When try to execute:

`System.DateTimeOffset.Parse("27/6/2018 -02:00")` 

I got an exception:

```shel
RangeError: Invalid time value
      at Date.toISOString (<anonymous>)
      at toStringWithOffset (tests/bin/fable-core.2.0.0-alpha-020/Date.js:125:14)
      at toString (tests/bin/fable-core.2.0.0-alpha-020/Date.js:167:32)
      at toString (tests/bin/fable-core.2.0.0-alpha-020/Util.js:178:57)
      at str2.replace (tests/bin/fable-core.2.0.0-alpha-020/String.js:182:34)
      at String.replace (<anonymous>)
      at formatOnce (tests/bin/fable-core.2.0.0-alpha-020/String.js:164:15)
      at args (tests/bin/fable-core.2.0.0-alpha-020/String.js:206:17)
      at /Users/maximemangel/Workspaces/Github/MangelMaxime/Thot/tests/bin/Tests.Json.Decode.js:266:52
      at /Users/maximemangel/Workspaces/Github/MangelMaxime/Thot/tests/bin/Util.js:18:5
      at Context.<anonymous> (tests/bin/Main.js:30:15)
```

**Comment by alfonsogarciacaro** [comment]
I'm getting an error when parsing this in .NET too. Probably depends on the culture which unfortunately we cannot set up with Fable. If you try something like "1/6/2018 -02:00" it should work.

**Comment by alfonsogarciacaro** [comment]
Using the format `yyyy-MM-dd` works too (what the HTML date input elements give).

**Comment by MangelMaxime** [comment]
Hum, does this mean we assume an English culture by default ? 

`X/Y/Z` where

- `X` -> month
- `Y` -> day
- `Z` -> year

**Comment by MangelMaxime** [comment]
No worries I am not asking for the Globalization, I just want the tests to pass in Thoth.Json.

For the `DateTime`, in the error I mention the fact that if the parser failed then we encourage them to use the format `ISO 8601` which works on both side. Date manipulation is really messy... :)

**Comment by Alxandr** [comment]
IMHO; the best way would be to only allow ISO dates `YYYY-MM-DD` (optionally with times). This could easily be enforced with a regex, and will always yield the same result. Will likely also prevent people from shooting themselves in the foot.

**Comment by alfonsogarciacaro** [comment]
Let's close this for now, as the first sample is working and the second doesn't work in .NET either. I know date parsing is not perfect but in order to improve it we would need much more code or to import a library, and I'm not sure if the gain will compensate the increase in bundle size.

If you find other examples that work on .NET but doesn't in JS (and don't depend on the culture) please feel free to reopen.

**Comment by 0x53A** [comment]
I really agree with Alxandr that anything except ISO should be explicitly disallowed. Anything else will cause people to have wrong expectations.

**Comment by alfonsogarciacaro** [comment]
It's a tricky balance, for example in #1637 users are asking to **not* comply with ISO ;)

**Comment by 0x53A** [comment]
Yeah, its never easy.

My opinion would be to restrict to ISO dates here, because the rest isn't guaranteed to work.

In the Guid case I would NOT follow ISO, because .NET doesn't, Guid.Empty breaks, and I don't think there are any failures from doing so.

**Comment by Alxandr** [comment]
I agree. Also, the guid parsing will not be system specific.

**Comment by alfonsogarciacaro** [comment]
Closing in favor or #2126 which has a discussion about adding CultureInfo.
