### ISSUE TITLE
[Q] What is correct: Some null or None when deserializing optional null strings from JSON?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1423]
Given the following 
```fs
type Record = { value : Option<string> }
```
What is the correct behavior when deserializing this JSON string:
```js
{ value: null }
```
Should be become 
```fs
// there is no value 
{ value = None }
``` 
or 
```fs
// there is a value for the string and it is null 
{ value = Some null }
```

Personally I think it should be `{ value = None }` because communicating the nothingness of something in F# is done with `None` what do you think?

cc @MangelMaxime  @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Tricky... if you want to fully comply with semantics it should be `Some null`, but I agree `None` is probably more intuitive in this case. Fable does use `null` to represent `None` at runtime so it easy that a record like `{ value = None }` becomes `{ "value": null }` in JSON representation.

**Comment by Zaid-Ajaj** [comment]
I will close this issue and use it later for reference if people ask about this, what is most important to know is that, at runtime, `Some null` will *behave* like `None`, the following test passes
```fs
testCase "Optional null strings" <| fun test ->
    Some null 
    |> function 
        | Some value -> "there is a value"
        | None -> "there is no value"
    |> test.areEqual "there is no value"
```
So using `None` makes more sense to begin with

**Comment by alfonsogarciacaro** [comment]
Good eye, @Zaid-Ajaj! Yes, this is currently the case, but maybe we should correct it. Fable is already [wrapping other types](https://github.com/fable-compiler/Fable/blob/646463edffaf056c7426c149f3580bfa4422b48e/src/dotnet/Fable.Compiler/Transforms/Transforms.Util.fs#L71-L75) with a [runtime Some](https://github.com/fable-compiler/Fable/blob/646463edffaf056c7426c149f3580bfa4422b48e/src/js/fable-core/Option.ts#L63-L65). We could include also strings and other nullable types, although for some people it may be good that `None` checks discard null values too (and in any case, things will get trickier when interacting with JS).

> BTW, list is being wrapped because at one point I tried compiling empty lists as `null` for Fable 2 but it's not the case anymore.

**Comment by Zaid-Ajaj** [comment]
It would be great if the behavior at runtime is correct, i.e. `Some null <> None` because the less surprises, the better :smile:
