### ISSUE TITLE
(dev2.0) Object Expressions issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1434]
When you compile code similar to the one [here](https://github.com/fable-compiler/Fable/blob/d4c4d29614853cdc52e275ba46c23a688e55145b/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L1535-L1538), you get the following error:
`error FABLE: Object member has kind ObjectMethod false but value is not a function`

Could be related to interface transformation, or something else entirely.
Not happening if we convert the object expression entity to a type (class).

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @ncave. I could reproduce the problem and (hopefully) fix it in latest commit.
