### ISSUE TITLE
(dev 2.0) System.Int64.Parse do not work

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1437]
### Description

When doing`System.Int64.Parse("99")`, the result is null.

Looking at `fable-core` I think we are missing the `Int64.js` file to implement `parse`, `tryParse` methods. 

Is it normal that we don't get the `Replacement not found for ...` error ?

**Comment by MangelMaxime** [comment]
Oups, I didn't looked at the error correctly.

Fable is indeed creating an error:

```
/Users/maximemangel/Workspaces/Github/MangelMaxime/Thot/src/Thoth.Json/Decode.fs(179,42): (179,60) error FABLE: Cannot resolve System.Int64.Parse
```

**Comment by alfonsogarciacaro** [comment]
Will be fixed in next release :)
