### ISSUE TITLE
fable-splitter doesn't output errors in red (nor warnings in yellow)

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1438]
### Description

In Fable 1, errors and warning where colorized in yellow/red. 

In Fable 2 it looks like the output is always in white.

**Comment by alfonsogarciacaro** [comment]
I'm seeing the warnings in yellow for webpack-dev-server and webpack-cli (actually, that code in fable-loader hasn't changed). Can you list the steps to reproduce the problem?

**Comment by MangelMaxime** [comment]
Ah yups, I was thinking you added webpack for Thoth.Json but in fact we are using fable-splitter.

So the problem is probably not related to fable but fable-splitter.

I used the `watch` target of `Thoth.Json` branch `feature/v2`

**Comment by MangelMaxime** [comment]
Not sure why this has been closed ? We could probably change the title :)

And I can send a PR this week-end to make `fable-splitter` colored the output.

**Comment by alfonsogarciacaro** [comment]
Ah, if you're willing to send a PR to add this feature to fable-splitter that'd be very useful!

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Should I send a PR against dev2.0 branch or master ?

**Comment by alfonsogarciacaro** [comment]
`dev2.0` please, I will have a tough time already to merge the two branches ;)

**Comment by alfonsogarciacaro** [comment]
Sorry, I'll close this as it's a bit old, but please feel free to send the PR to color the fable-splitter output at any time. I've cleaned up a bit the code in `fable2-1` branch so maybe it's easier now (I'll likely merge the branch in the next couple of days). @nojaf is using latest fable-splitter so he may be interested in this too.

**Comment by MangelMaxime** [comment]
Yes sorry I forgot about this one or more precisely didn't take the time for it :D

**Comment by MangelMaxime** [comment]
My idea was to use [chalk](https://www.npmjs.com/package/chalk)

In order to output green / red / grey when needed depending of the logs output by `fable-splitter`.

**Comment by alfonsogarciacaro** [comment]
I guess it should be a matter of using chalk [in this function](https://github.com/fable-compiler/Fable/blob/38d4e94b8ed9173098f1427334c6775efb169d04/src/js/fable-splitter/src/index.ts#L76-L84) and test that everything works :)
