### ISSUE TITLE
(dev 2.0) uint64 should throw an error when passed an invalid string

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1449]
On .Net:

```
> "maxime" |> uint64
System.FormatException: Input string was not in a correct format.
```

Fable generate `0`.

I believe this was working in a previous version of Fable 2.0.

**Comment by alfonsogarciacaro** [comment]
I just checked with latest alpha and I do get an error. Can you please update and try again?

However, I did notice we are not failing when converting negative numbers (e.g `"-5"`). This happens with other integer types too. Until it's fixed, we probably need to do the check manually: `res < 0`.

**Comment by MangelMaxime** [comment]
Ok sorry, this was a bug introduced when we refactor Thoth.Json to use `Helpers.asString`, etc.
