### ISSUE TITLE
(dev2.0) Interface casting round-trip issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1452]
Casting to an interface makes a new object that doesn't retain the original object's fields, so it's not possible to cast it back.

**Comment by alfonsogarciacaro** [comment]
The interface wrapper keeps a reference to the original object so it shouldn't be difficult to enable downcasting (and type testing). Could please add some sample code to see what exactly you need and test it?

**Comment by ncave** [comment]
```
module App

type Test(value: int) =
    member __.Value = value
    interface System.IDisposable with
        member __.Dispose() = ()

[<EntryPoint>]
let main argv =
    let d = new Test(3) :> System.IDisposable
    let t = d :?> Test
    if t.Value <> 3 then failwith "boo"
    0
```
