### ISSUE TITLE
(dev2.0) Casting from `obj` to interface is a noop

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1454]
### Description

I have a `Map<string, obj>`, for which the string can be used to get the type. However, when I cast my `obj` to an interface implementation, it doesn't do anything, so I'm left with the empty object (class impl) that doesn't have the methods expected.

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-alpha-025
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Currently this is per design. Given that one of the ideas we're trying for Fable 2 is to remove reflection info from types (atm is only generated ad-hoc) interface casts need to be resolved at compile time so the type needs to be known. If you can use the string to get the actual type, can't you cast to the type and then to the interface?

Maybe in the future we can try to add some interface markers available at runtime, but probably not on the first release. If we do this, then there will be something else we need to support and then something else. However, Fable is not designed to support the full .NET F# behavior in JS, but to bring many of F# capacities into JS and make interop with JS tools and libs as seamless as possible.

For interop, Fable tries to mix some F#/.NET and Typescript concepts, so you can think of:

- F# `obj` as TS `any`: used to represent anything (coming from either JS or F# code). When using `obj` you're dangerously entering in the dynamic realm and going back is not easy (type testing with non-generic types is still possible.
- F# interfaces as TS structural interfaces: that is, the interface defines the shape (fully or partly) of an object but it's not necessarily attached to an actual type (function constructor in JS). As Fable 2 compiles type members as module functions it has to create object wrappers with the shape of the interface when a type is casted to it.

**Comment by Alxandr** [comment]
Comparing `obj` to `any` is completely not the same though. With any, I can do anything to it. With `obj`, given that nothing is attached to the prototype anymore, I can't do anything to it. In general, comparing this behavior to TS is completely backward. In TS, you can cast to anything at any time, because casting is a no-op. The properties/information is already there, casting is just to inform the compiler as such. Whereas, in Fable 2, casting produces a new item. This means that `obj` is fable is essentially useless as in you can't do anything with it. Whereas in TS it's the complete opposite. And the type in question is not even available in the project so there is no way to cast to it. I have the following:

* `IService` defined in `Common`
* `FableService` defined in `Fable`

Then in the the common project I do `sortOfDIContainer.get("service") :> IService`. The project has no knowledge about the `FableService` type, so there is no way to cast to it. For now, I've gotten around the problem by casting to `IService` before inserting it into the collection (`diContainer.register("services", FableService () :> IService :> obj)`) which works, but it's definitely something that will bite you in the ass if you don't know about it. IMHO this is a

**Comment by Alxandr** [comment]
I think I might have a decent solution to the problem. It requires a new attribute, but given that it causes a de-optimization I think that's a price worth paying. Please take a look at the following gist and let me know what you think of it: https://gist.github.com/Alxandr/cc5b8cb4f1f33adfc37c57562a1061d3. I'm willing to help (or at least attempt so) with the implementation if this is something you think we can go forwards with.

**Comment by alfonsogarciacaro** [comment]
Hmm, I foresee some issues with the `IAddExt$$Cast` declaration. I've given a thought to this and maybe using an attribute like `AttachInterfaces` which generates code similar to this could work:

```js
// Code generated by current version of Fable 2
export function AddFoo() {}

export function AddFoo$$$$002Ector() {
  return this != null ? AddFoo.call(this) : new AddFoo();
}

export function AddFoo$$$Fable_Playground$002EIAddExt($this$$2) {
  return {
    [THIS_REF]: $this$$2,
    AddExt(s) {
      return s + "foo";
    }
  };
}

// When using the attribute AttachInterfaces, Fable would add this code
// INTERFACE_IMPLEMENTATIONS would be a symbol defined in fable-core
AddFoo.prototype[INTERFACE_IMPLEMENTATIONS] = {
  "IAddExt": AddFoo$$$Fable_Playground$002EIAddExt
};

// When downcasting to an interface (UnboxGeneric operator) Fable
// would add the full name of the interface, then in the downcast function
// we can check if the INTERFACE_IMPLEMENTATIONS dictionary is available and
// whether it includes IAddExt
export const downCasted = downcast(AddFoo$$$$002Ector(), "IAddExt");
```

**Comment by Alxandr** [comment]
@alfonsogarciacaro I thought about something similar first as well, but I *think* it would be better to be able to be selective about what interfaces we attach. Otherwise, technically, you would need this:

```js
AddFoo.prototype[INTERFACE_IMPLEMENTATIONS] = {
  "IAddExt": fn1,
  "System.IEquatable`1": fn2,
  "System.Collections.IStructuralEquatable": fn3,
  .....
};
```

This will be particulary bad if a type implements a lot of interfaces. Also, what issues do you forsee with the cast symbol declaration?

**Comment by Alxandr** [comment]
I just found another issue. Currently I'm inserting the interfaces into my collection of `obj` instances, however, doing `myThing :?> IFace` calls `downcast`, which goes through the `this` reference. So I just lost the ability to call the interface methods.

**Comment by alfonsogarciacaro** [comment]
Fable 2 finally shipped with interfaces attached to the property (see #1547), so this should be fixed too :+1: Please feel free to reopen if not.
