### ISSUE TITLE
(dev2.0) Wrong currying when calling base constructors.

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1458]
### Description

When calling base constructors with functions, currying is done wrong.

### Repro code

```fsharp
type BaseClass (f: string -> string -> string) =
  member __.MakeString a b = f a b

type AddString () =
  inherit BaseClass (fun a b -> a + b)
```

### Expected and actual results

The base class constructor is called with an argument that is of a different
type than what it expects.

```js
function BaseClass(f) {
  var $this$$1 = this;
  $this$$1.f = f;
}
function BaseClass$$$$002Ector(f) {
  return this != null ? BaseClass.call(this, f) : new BaseClass(f);
}
function BaseClass$$MakeString(__, a, b) {
  return __.f(a, b);
}
function AddString() {
  BaseClass$$$$002Ector.call(this, function (a$$1) {
    return function (b$$1) {
      return a$$1 + b$$1;
    };
  });
}
```

### Related information

* Fable version (`dotnet fable --version`): `2.0.0-alpha-025`
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Good catch, thank you!

**Comment by Alxandr** [comment]
Would you mind publishing a new version of `dotnet-fable`, so I can go on finding new bugs? :P

**Comment by alfonsogarciacaro** [comment]
2.0.0-alpha-026 has been published :)
