### ISSUE TITLE
(dev2.0) Calling base members issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1464]
```
module App

type Foo() =
    let field = 1
    member __.A() = field

type Bar() =
    inherit Foo()
    member __.A() = 2
    member __.B() = base.A()

[<EntryPoint>]
let main argv =
    let bar = Bar()
    if bar.B() <> 1 then failwith "boo"
    0
```
The base call is not properly generated (i.e. properly generated, but the incorrect self object is passed on).

Note: This is more for completeness, not a showstopper for the REPL (there was only one occurrence in FCS which was fixed).

**Comment by ncave** [comment]
Updated, see above. Here is the error:
```
  return __.field;
            ^
TypeError: Cannot read property 'field' of undefined
```

**Comment by alfonsogarciacaro** [comment]
At the end I had to change several things to fix several things to fix the issue. I realized that dealing with `this` was still a bit messy in Fable: it was being captured most of the time, so I removed `Super` and `This` from Fable AST to prevent confusion. Tests are passing but I hope I didn't break anything in the REPL.

**Comment by ncave** [comment]
Looks fixed, thanks.
