### ISSUE TITLE
specially named properties are incorrectly converted to js

### ISSUE THREAD

**Issue by runefs** [fable-compiler/Fable#1478]
### Description

when using ` ``propertyName`` ` some properties might have names that are illegal in JS but might be incorrectly translated

### Repro code

```
let color i =
   let scale  = Colorbrewer.Colors.Qualitative.Set3.``12``
   scale.[i]
```

### Expected and actual results
the actual result is:

```
export function color(i) {
    var scale = Colors.Qualitative.Set3.12;
    return scale[i];
}
```

but should have been:
```

export function color(i) {
    var scale = Colors.Qualitative.Set3["12"];
    return scale[i];
}
```

### Related information
 using docker image: nojaf/fable:latest

**Comment by alfonsogarciacaro** [comment]
Sorry, I don't understand exactly what you mean by `propertyName`. I cannot just numbers for my type properties unless I quote them, as in:
```fsharp
foo.``12``
```
Can you post some fully compilable code that I can reproduce in my machine? Thanks!

**Comment by runefs** [comment]
I've updated the original post, since it was markdown that caused the confusion. I've later found that use of `foo?("  bar  ")` will cause the same issue if the property name can't be used with dot notation in JS

**Comment by alfonsogarciacaro** [comment]
Thanks for editing the post. Hmm, seems to be an issue with Fable 1, [works fine in repl2](http://fable.io/repl2/#?code=open%20Fable.Core.JsInterop%0A%0Atype%20Foo%20%3D%0A%20%20%20%20abstract%20%60%6012%60%60%3A%20string%0A%0Alet%20color%20(i%3A%20Foo)%20%3D%0A%20%20%20%20printfn%20%22%25s%22%20i.%60%6012%60%60%0A%20%20%20%20printfn%20%22%25s%22%20i%3F(%22%20bar%20%22)).

**Comment by runefs** [comment]
I agree it works in fable 2
