### ISSUE TITLE
(dev2.0) Extra namespace issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1479]
Some recent change is causing extra namespaces to be prepended on calls to imports from another module, it's a breaking change. Seems to happen when code from a module with a namespace is called in another module.

**Comment by alfonsogarciacaro** [comment]
Damn! I guess there's no simple way to reproduce. This is weird because tests should cover a case as the one you describe.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, I can't reproduce it small as well despite trying hard. Can we print out the import names so we can narrow it down? Where is the best place to do that? Somehow the namespace is being prepended without need:

it's generating: 
```js
var _bytes = require("./bytes");
_bytes.Microsoft$002EFSharp$002ECompiler$002EAbstractIL$002EInternal$002EBytes$$$ofInt32Array)(...)));
```
where it should be just:
```js
_bytes.Bytes$$$ofInt32Array)(...)));
```

**Comment by alfonsogarciacaro** [comment]
I cannot reproduce this. Is it happening when compiling the REPL? Can you indicate which file is affected by this?

I doubt this is caused by #1475 (but I doubt of my self too), because that PR only touches the overload suffixes, not the rest of the mangled names.

**Comment by alfonsogarciacaro** [comment]
Ups, sorry! I just noticed we wrote the comment almost at the same time and I missed your reply. I managed to download the REPL and I saw the issue. So you think it wasn't happening before #1475? The name mangling when calling a method from another file [is done here](https://github.com/fable-compiler/Fable/blob/c09fe59b7c9c8ed7b9f15e1b5da61606b2dac370/src/dotnet/Fable.Compiler/Transforms/FSharp2Fable.Util.fs#L721). But this is the same code as when declaring the member, so I'm a bit puzzled why is not trimming the root module in this case, but now that we can easily check with the REPL I'm sure we'll pinpoint the issue :+1:

**Comment by ncave** [comment]
@alfonsogarciacaro Right, for some reason getRootModuleAndDecls returns rootEnt=None.

**Comment by alfonsogarciacaro** [comment]
Yeah, I found out that in #1475 I changed the `getEntityLocation` to just `ent.DeclarationLocation` because with the overload hash it shouldn't mind whether you're using signature or implementation files. However, I forgot to make sure we were using the `.fs` extension when checking for a file root module. It should be fixed with latest commit :)

**Comment by ncave** [comment]
@alfonsogarciacaro Thanks for fixing it, it may be a good idea to push another alpha as the previous one was broken.
