### ISSUE TITLE
Error in bitshift with ulong

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1482]
### Description

In .NET `15210016002388773605UL >>> 33` returns `1770678907`. In fable, it returns `18446744073332746875`.

### Repro code

```fsharp
  15210016002388773605UL >>> 33
  |> Expect.equal 1770678907UL "should equal"
```

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-alpha.30
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Ups, apparently there was a specialized function in long.js for unsigned right shift and I missed it. Will be fixed in next release, thank you!
