### ISSUE TITLE
Fable show wrong project\file path error while compiling

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#1488]
### Description
Compile error message has wrong path to file.
### Repro code

https://github.com/Neftedollar/semantic-ui-react-fable-experiment/commit/60240bfa072e042f2b46fd692306181a1b60845e

- clone https://github.com/Neftedollar/semantic-ui-react-fable-experiment.git
- fake build --target run

### Expected and actual results

It show error message
```
/src/Client/Client.fs(22,6): (22,58) error FABLE: Type List passed as generic param 'P must be decorated with Fable.Core.PojoAttribute or be `obj`/interface
 @ ./Client.fsproj 1:0-28 1:0-28
```
while path should  be 
`/src/Fable.Semantic/Elements/Button.fs`

### Related information

* Fable version (`dotnet fable --version`): Fable.Compiler (1.3.17) - restriction: >= netcoreapp2.0
* Operating system: windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @Neftedollar! We're deprecating `PojoAttribute` in Fable 2 so this should automatically disappear when upgrading :) However, let's keep the issue open and revisit a bit later because I think we've a similar problem with inline functions.

**Comment by Neftedollar** [comment]
Yes, thank you!
