### ISSUE TITLE
Improve replacements for StringBuilder.

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1500]
I currently have a shim StringBuilder in my code so as to be able to use APIs that needs stringbuilders. This should probably be part of Fabe.Core (with replacements in place). In JS, it can be implemented as a simple `ref<string>` or similar.

**Comment by ncave** [comment]
@Alxandr It's already part of Fable.Core, just use it.

**Comment by Alxandr** [comment]
@ncave That's weird, cause I've been getting exceptions that no replacement was found for `StringBuilder.Append` (etc.)

**Comment by ncave** [comment]
It was added recently, try it.

**Comment by Alxandr** [comment]
You're right. I still get errors though 😛:

```
[!] Error: 'StringBuilder$$Append$$244C7CD6' is not exported by .fable\fable-core.2.0.0-alpha-031\System.Text.js
```

**Comment by ncave** [comment]
@Alxandr The current SB implementation is a bit simplistic, probably one of the overloads is missing, as the overload mangling is now done based on argument types. Post a bit of F# code so we can see which one.

**Comment by Alxandr** [comment]
I currently use the following implementation as a shim (be adviced that `Remove` and `ToString` with indexes has not been tested):

```fsharp
  type StringBuilder (s: string) =
    let mutable s = s

    new () = StringBuilder ("")

    member __.Length = s.Length

    member sb.Append (s': string) =
      s <- s + s'
      sb

    member inline sb.Append (c: char) = sb.Append (string c)

    member inline sb.Append (num: ^n) = sb.Append (sprintf "%d" num)

    member inline sb.Append (o: obj) = sb.Append (string o)

    member inline sb.AppendLine () = sb.Append System.Environment.NewLine

    member inline sb.AppendLine (s: string) =
      (sb.Append (s)).AppendLine ()

    member sb.Remove (startIndex: int, length: int) =
      if startIndex + length >= s.Length
      then s <- s.Substring (0, startIndex)
      else s <- s.Substring (0, startIndex) + s.Substring (startIndex + length)
      sb

    member inline __.ToString (startIndex: int, length: int) =
      s.Substring (startIndex, length)

    override __.ToString() = s
```

Not entirely sure which are missing, but that's at least the minimal implementation for my sake (wrt which methods are available).

**Comment by ncave** [comment]
@Alxandr Eventually all [StringBuilder.Append](https://msdn.microsoft.com/en-US/library/system.text.stringbuilder.append(v=vs.110).aspx) overloads will have to be added. If you need to get rid of your shim sooner, go ahead and submit a PR, it should work now that @alfonsogarciacaro fixed the overload mangling.

**Comment by Alxandr** [comment]
Yeah, no, the shim works, so this isn't a rush.

**Comment by Alxandr** [comment]
I can work on this issue now that the test issues fixes has been merged 🙂

**Comment by alfonsogarciacaro** [comment]
It'd be nice to have a proper implementation that actually prevents many string allocations, using a typed char array (another reason to merge #1473.

BTW, now that we can use F# for fable-core, it'd be also nice to translate the [System.Decimal source](https://referencesource.microsoft.com/#mscorlib/system/decimal.cs,1b2858baf311cbf9) to F# so we can actually keep accuracy. Just saying ;)

**Comment by Alxandr** [comment]
I think things like System.Decimal is probably a better fit for webassembly (like [long.js did](https://github.com/dcodeIO/long.js/pull/50)). As for string builder, as far as I've seen from tests, JS engines are really well optimized at appending strings together (probably because that's the only way you've been able to build strings), that I don't think the added complexity is worth it. At least not unless someone does a propper meassure to see that it is.

**Comment by Alxandr** [comment]
Speaking of long.js, should it maybe be updated from upstream? Wouldn't it be better if it could be imported as a file untouched, and simply write the fable shims needed on top?

**Comment by alfonsogarciacaro** [comment]
That's what we did for Fable 1, but long.js attaches everything to the prototype so any import would bring the whole file. That's why I changed the functions to get better advantage of tree shaking. I know it makes updating the file more complicated but...

**Comment by Alxandr** [comment]
Ah. You're right. I didn't notice.

**Comment by alfonsogarciacaro** [comment]
Let's close the issue as we already have PR #1505 to track this.
