### ISSUE TITLE
(dev2.0) Issue with constructors that use `as X`

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#1506]
### Description

Constructors that use `ax X` produce really invalid input.

### Repro code

```fsharp
type StringBuilder =

    val mutable value: string

    new () = { value = null }
    new (value: string) = { value = value }
    new (other: StringBuilder) as sb =
        { value = other.value }
        then sb.CheckInvariants ()

    member private sb.CheckInvariants () = ()
```

this produces the following JS:

```js
import { declare } from "fable-core/Types";
export const StringBuilder = declare(function StringBuilder(arg1, arg2) {
  this.value = arg1;
  this["init@7-55"] = arg2 | 0;
});
export function StringBuilder$$$$002Ector() {
  new StringBuilder(null);
  null["init@7-55"] = 1;
}
export function StringBuilder$$$$002Ector$$Z721C83C5(value) {
  new StringBuilder(value);
  null["init@7-55"] = 1;
}
export function StringBuilder$$$$002Ector$$43A65C09(other) {
  new StringBuilder(other.value);
  null.contents = null;
  null["init@7-55"] = 1;
  StringBuilder$$CheckInvariants(null.contents);
}

function StringBuilder$$CheckInvariants(sb) {}
```

### Expected and actual results

Nonbroken JS

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-alpha.31
* Operating system: Windows 10 (and the online REPL)

**Comment by alfonsogarciacaro** [comment]
Using `as X` is [indeed supported](https://github.com/fable-compiler/Fable/blob/a5eb10c5949841d3ddb8d7dea4d2816ab6fdddfd/tests/Main/MiscTests.fs#L196-L199) but it produces quite ugly code (this is coming from the F# AST). I didn't know you could `as X` in non-implicit constructors and also is the first time I see the syntax `new (v) as x = { value = value } then x.Foo()` ;) I'll try to have a look.

**Comment by Alxandr** [comment]
@alfonsogarciacaro I didn't know either. I just read the C# code for StringBuilder, and it did set all properties, then validate, and I was like, well how on earth do I do that in F# 😛. So I guess here's to learning new things 🍻

**Comment by Alxandr** [comment]
@alfonsogarciacaro any updates here?

**Comment by alfonsogarciacaro** [comment]
I've fixed the problems with `as this` in constructors (see #1602) but my attempts to support the `then` syntax in constructors haven't been successful and I haven't seen other use cases besides this.

I'll close the issue for now, but please feel free to reopen if you want to give it a go in a PR.
