### ISSUE TITLE
How to use System.Diagnostics.Contracts ?

### ISSUE THREAD

**Issue by iyegoroff** [fable-compiler/Fable#1520]
### Description

Following code does not produce any js output:

```fsharp
Contract.Requires false
Contract.Invariant false
Contract.Assert false
Contract.Ensures false
```

And this `Contract.Requires<System.Exception> false` results into compile time error:

```
ERROR in ../src/App.fs
Module build failed: Error: An IL call to 'System.Diagnostics.Contracts.Contract::Requires(...)' could not be resolved: Member 'Requires' not found in type Contract, found:  (/Users/iyegoroff/Documents/dev/fsharp/FableApp/src/App.fs)
    at Loader.fableUtils.client.send.then.r (/Users/iyegoroff/Documents/dev/fsharp/FableApp/node_modules/fable-loader/index.js:67:22)
    at <anonymous>
 @ ../src/FableApp.fsproj 1:0-25
```

### Repro code
```fsharp
open System.Diagnostics.Contracts
Contract.Requires<System.Exception> false
```

### Expected and actual results

Expected: some run time contract violation errors
Actual: no run time errors or compile time error

### Related information

* Fable version (`dotnet fable --version`):  1.3.8 and 1.3.17
* Operating system: OSX

**Comment by alfonsogarciacaro** [comment]
Hmm, I've never used `System.Diagnostics.Contracts`. Not sure what they should be compiled to or how much work they would involve. Would you be interested in giving it a try?

**Comment by xdaDaveShaw** [comment]
Are you expecting Runtime checks from the Contracts and/or the Compile Time safety.

TBH I never imagined Code Contracts would work on F# (or be needed), especially since they have been broken bit by bit as Roslyn has developed changing the IL. They seemed to lag behind the C# compiler so I've stopped looking at them and have removed them from my C# code.

**Comment by iyegoroff** [comment]
Thank you for the answers. I end up with using just `failwith`.
