### ISSUE TITLE
Cannot resolve Microsoft.FSharp.Core.LanguagePrimitives.EnumToValue

### ISSUE THREAD

**Issue by zpodlovics** [fable-compiler/Fable#1521]
### Description

It seems that right now there is no EnumToValue implementation exists in Fable.

### Repro code

```fsharp
type Fruits =
| Apple = 1
| Banana = 2
| Coconut = 4
let x = LanguagePrimitives.EnumToValue<Fruits,int32> Fruits.Apple
```

### Expected and actual results
Expected:
Works exactly in the same was as F# on .NET.

Actual:
```
error FABLE: Cannot resolve Microsoft.FSharp.Core.LanguagePrimitives.EnumToValue
```

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-beta-001
* Operating system: Ubuntu 16.04 x86_64

**Comment by alfonsogarciacaro** [comment]
Closed by #1522, thank you! I'll publish a new Fable 2 beta shortly :+1:
