### ISSUE TITLE
inline modifier messes up webpack re-compilation (probably expected behavior)

### ISSUE THREAD

**Issue by SirUppyPancakes** [fable-compiler/Fable#1523]
### Description

Fable in-lines extension methods (maybe static class methods?) and causes webpack to not pick up source changes and re-compile.

### Repro code
[ExtensionExample.zip](https://github.com/fable-compiler/Fable/files/2300191/ExtensionExample.zip)

### Expected and actual results

Download the sample, open a command prompt or powershell prompt at `ExtensionExample\Main`, run `yarn` to install dependencies, run `./start` (a batch file) to start the Fable daemon with webpack watching.

If you make changes to any of the files (`Main.fs`, `Util.fs`, `ObjExt.fs`), webpack will trigger a recompile appropriately, except when you change the function:

```
[<Extension>]
type GenericExt () =
    [<Extension>]
    static member inline Also(source, f) = f source; printfn "oosh"; source
```

It's a rather silly function and definitely not functional style, but it illustrates the point. Simply try to change the string that it prints and you'll notice webpack react, but not find any changes to actually recompile and running the program still shows the original string.

If you run, from a separate terminal (leaving Fable running in the first terminal), `./fable_js` (another batch file that simply runs fable-splitter), and look at the generated `ExtensionExample\Main\fable_js\src\ObjExt.js` file, you'll see that the class is basically ignored:

```
import { setType } from "../fable-core/Symbol";
import _Symbol from "../fable-core/Symbol";
export class GenericExt {
  [_Symbol.reflection]() {
    return {
      type: "ExtEx.Core.ObjExt.GenericExt",
      properties: {}
    };
  }

  constructor() {}

}
setType("ExtEx.Core.ObjExt.GenericExt", GenericExt);
export const value = 123;
```

And at the call-site in `ExtensionExample\Main\fable_js\src\Main.js`:

```
import { middle, ABC, f } from "./Util";
import { printf, toConsole } from "../fable-core/String";
import { value } from "./ObjExt";
(() => {
  const $var1 = f(new ABC(0)) === f(middle);

  (function (x) {
    toConsole(printf("A is middle: %A"))(x);
  })($var1);

  toConsole(printf("oosh"));
  return $var1;
})(), void 0;
toConsole(printf("value : %A"))(value);
```

The function is simply in-lined with no actual call occurring.

### Related information

Windows 10 x64
yarn 1.9.4
npm 5.6.0
node 8.11.4
Fable 1.3.17

Is this just the kind of quirk that we'll have to watch out for, or will this sort of thing be resolved at some point?

**Comment by alfonsogarciacaro** [comment]
Unfortunately the `inline` modifier cannot be ignored as it's important in many situations to resolve types, particularly with SRTP but also with generics as generic info is erased in the JS runtime. I'm aware of the issue and did try to [add a file dependency when a call is inlined](https://github.com/fable-compiler/Fable/blob/44ed21c2580ac44cd206ed76faa029f720cecd69/src/dotnet/Fable.Compiler/Transforms/FSharp2Fable.fs#L988-L993) so Webpack would recompile the dependent file in the inline function changes. However, [we had some weird problems because of this](https://github.com/fable-compiler/Fable/issues/1241#issuecomment-346597473) and had to remove it. Maybe it's fixed in Webpack 4, I'll give it a try.

**Comment by alfonsogarciacaro** [comment]
I think I found the issue, the normalized path separator was causing problems in Windows. @SirUppyPancakes Can you please try with `fable-loader` 2.1.1 and `fable-compiler` 2.1.7 and check if editing an inline function triggers a recompilation of files referencing it?

**Comment by SirUppyPancakes** [comment]
Yep looks good after upgrading :)

**Comment by alfonsogarciacaro** [comment]
It happened there was still an issue with the order of the file recompilation 😅 Please update to `fable-compiler` 2.1.8 if you still have issues.
