### ISSUE TITLE
String.join with chars return weird result

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1524]
### Description

`System.String.Join` with chars returns weird result.

### Repro code

```fsharp
open Fable.Core
open System

[<Emit("debugger;")>]
let debug () : unit = jsNative

[0..10]
|> List.map (fun _ -> '*') 
|> fun chars -> String.Join("", chars)
|> fun x ->
    let y = x
    debug()
    x
|> printfn "%s"
```

### Expected and actual results

*Expected:*
`"**********"`
*Actual:*
`"4242424242424242424242"`

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-beta-001
* Operating system: Windows 10

### Workaround

In this case using strings instead of chars does give the expected outcome.

**Comment by MangelMaxime** [comment]
This is probably because we use `number` to represent char at runtime. This give us a performance boost. 

I guess the `fable-core` module need to be adapted somewhere.

**Comment by alfonsogarciacaro** [comment]
Damn, this is another case were compiling chars as numbers is giving problems. I've been trying for a couple of hours but it's very difficult to get it right because `String.Join` (and `String.Concat`) has many overloads accepting `obj[]`, `IEnumerable<'T>`, `obj1*obj2*...` so it's quite complicated to detect chars at compile time and transform them to strings before they reach runtime (where they're indistinguishable from numbers).

Cases like this keep coming and compiling chars as numbers hasn't shown a big performance improvement so probably it's better to revert #1473... unless @ncave has something to say ;)

**Comment by ncave** [comment]
@alfonsogarciacaro I don't have a lot to say about it. I understand it's not always easy or possible to implement exactly some BCL API in javascript. I'm sure this particular issue can be fixed, but I was more concerned about how char repesentation affects JS initerop. So IMO you should do whatever you think will help in the long run. If you decide to take it out, you can leave it as unmerged PR, in case the decision needs to be reversed in the near future.

**Comment by alfonsogarciacaro** [comment]
Unfortunately, I cannot find a solution that covers all cases. Consider this code:

```fsharp
let concatObjs (xs: obj[]) =
    System.String.Join("--", xs) |> printfn "%s"

[|"a";"b";"c"|] |> Array.map box |> concatObjs
[|'a';'b';'c'|] |> Array.map box |> concatObjs
[|1;2;3|] |> Array.map box |> concatObjs
```

In FSI this prints:

```
a--b--c
a--b--c
1--2--3
```

In Fable it prints:

```
a--b--c
97--98--99
1--2--3
```

At compile time it's not possible to know that `xs` within `concatObjs` contains chars. And at runtime we cannot tell chars apart from numbers. It's not only #1473, [this one](https://github.com/fable-compiler/Fable/commit/d56571e1d23d64d6c2aadebd39bf3d0ac594af56#diff-c9f14fc6657a59581e11dd6a67eeb968) also took a long time to fix. I'm afraid similar issues will keep coming and we'll have to consume a lot of time and add patch after patch to solve them. So far the only performance gain has come from using typed arrays and this can also be achieved by turning chars into `uint16` (though the programmer needs to know about this) so hopefully it's not a big issue to revert the change.

In any case I agree we should keep the PR in case we want to use it again in the future.
