### ISSUE TITLE
(dev 2.0) missing booleanOr operator

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/Fable#1527]
### Description

dev 2.0 code with `(||)` that works in 1.37 gives missing op_BooleanOr compile error

### Repro code

```
let test = [true] |> List.fold (||) false
```

### Expected and actual results

Please provide the expected and actual results.
Expected: compiles correctly 

Actual: compile error like:
`C:/Users/Thomas/GitHub/Visual2-f2/src/Renderer/Files.fs(141,32): (141,34) error FABLE: Cannot resolve Microsoft.FSharp.Core.LanguagePrimitives.IntrinsicOperators.op_BooleanOr`

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-beta-001
* Operating system: windows

The workround in this case is easy: use `List.exists (fun b -> b)`

**Comment by xdaDaveShaw** [comment]
I think I have a fix for this. Going to submit a PR soon if no-one else has.
