### ISSUE TITLE
Inlined overloaded methods are not resolved properly without optimization

### ISSUE THREAD

**Issue by dgchurchill** [fable-compiler/Fable#1531]
Using http://fable.io/repl2 (Version: 2.0.0-beta-001) the following code:

```
type InlineTest() =
    static member inline OverloadedInline(_ : int) : int =
        2

    static member inline OverloadedInline(_ : string) : string =
        "hello"

printfn "%A" (InlineTest.OverloadedInline 1)
printfn "%A" (InlineTest.OverloadedInline "1")
```

Prints `2` twice instead of printing `2` and `"hello"`.

However, if the `Optimize (experimental)` option is turned on then it works as expected.

**Comment by alfonsogarciacaro** [comment]
I just tested it with dotnet-fable CLI version and it's working so apparently it's only a problem of the REPL. Let's close this for now in favor of the issue you originally raised there :+1:

**Comment by alfonsogarciacaro** [comment]
Thanks for investigating it further. Let's reopen this then. Probably fixing it in the CLI will make it work also in the REPL :+1:
