### ISSUE TITLE
LanguagePrimitives.EnumOfValue cannot be resolved unless inlined

### ISSUE THREAD

**Issue by zpodlovics** [fable-compiler/Fable#1536]
### Description

It seems that replacement functions are not composable. Update: the example code shrinked to minimal repro

### Repro code

[issue1536.zip](https://github.com/fable-compiler/Fable/files/2318347/issue1536.zip)

Please consider the following code  using http://fable.io/repl2/

```fsharp
module App

module EnumOperations = begin
    let inline enumOfValue1<'T,'U when 'U: enum<'T>> (value: 'T) : 'U = LanguagePrimitives.EnumOfValue<'T,'U>(value)
    let inline enumOfValue2 value = LanguagePrimitives.EnumOfValue value
    let enumOfValue3 value = LanguagePrimitives.EnumOfValue value
    let enumOfValue4 = LanguagePrimitives.EnumOfValue

end

type [<RequireQualifiedAccess>] BinaryBoolean =
    | F = 0uy
    | T = 1uy

let e0 : BinaryBoolean = LanguagePrimitives.EnumOfValue 1uy
printfn "Enum0: %s" (e0.ToString())
let e1 : BinaryBoolean = EnumOperations.enumOfValue1 1uy
printfn "Enum1: %s" (e1.ToString())
let e2 : BinaryBoolean = EnumOperations.enumOfValue2 1uy
printfn "Enum2: %s" (e2.ToString())
let e3 : BinaryBoolean = EnumOperations.enumOfValue3 1uy
printfn "Enum3: %s" (e3.ToString())
let e4 : BinaryBoolean = EnumOperations.enumOfValue4 1uy
printfn "Enum4: %s" (e4.ToString())
```

The repl2 generated code will looks like this:

```javascript
import { toConsole, printf } from "fable-core/String";
import { declare, Record } from "fable-core/Types";
export function EnumOperations$$$enumOfValue3(value$$3) {
  return null;
}
export function EnumOperations$$$enumOfValue4() {
  return function (value$$2) {
    return null;
  };
}
export const BinaryBoolean = declare(function BinaryBoolean(arg1, arg2, arg3) {
  this.value__ = arg1;
  this.F = arg2;
  this.T = arg3;
}, Record);
export const e0 = 1;
toConsole(printf("Enum0: %s"))(String(e0));
export const e1 = value$$1;
toConsole(printf("Enum1: %s"))(String(e1));
export const e2 = value;
toConsole(printf("Enum2: %s"))(String(e2));
export const e3 = EnumOperations$$$enumOfValue3(1);
toConsole(printf("Enum3: %s"))(String(e3));
export const e4 = EnumOperations$$$enumOfValue4()(1);
toConsole(printf("Enum4: %s"))(String(e4));
```

The ```export const e1 = value$$1;``` and the ```export const e2 = value;``` looks weird. 

### Expected and actual results

Using the webpack-dev-server will have the following errors:

```
ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
/tmp/fable/issue1536/src/App.fs(6,29): (6,65) error FABLE: Cannot resolve Microsoft.FSharp.Core.LanguagePrimitives.EnumOfValue
 @ ./src/App.fsproj 1:0-25 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/App.fsproj

ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
/tmp/fable/issue1536/src/App.fs(7,23): (7,53) error FABLE: Cannot resolve Microsoft.FSharp.Core.LanguagePrimitives.EnumOfValue
 @ ./src/App.fsproj 1:0-25 1:0-25
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./src/App.fsproj

```
Commenting out the following lines now fix the compilation error:

```
    //let enumOfValue3 value = LanguagePrimitives.EnumOfValue value
    //let enumOfValue4 = LanguagePrimitives.EnumOfValue
```

Try to reload the browser, but it will always fail with reference errors until the code will looks like this:

```fsharp
module App

module EnumOperations = begin
    let inline enumOfValue1<'T,'U when 'U: enum<'T>> (value: 'T) : 'U = LanguagePrimitives.EnumOfValue<'T,'U>(value)
    let inline enumOfValue2 value = LanguagePrimitives.EnumOfValue value
    //let enumOfValue3 value = LanguagePrimitives.EnumOfValue value
    //let enumOfValue4 = LanguagePrimitives.EnumOfValue

end

type [<RequireQualifiedAccess>] BinaryBoolean =
    | F = 0uy
    | T = 1uy

let e0 : BinaryBoolean = LanguagePrimitives.EnumOfValue 1uy
printfn "Enum0: %s" (e0.ToString())
//let e1 : BinaryBoolean = EnumOperations.enumOfValue1 1uy
//printfn "Enum1: %s" (e1.ToString())
//let e2 : BinaryBoolean = EnumOperations.enumOfValue2 1uy
//printfn "Enum2: %s" (e2.ToString())
//let e3 : BinaryBoolean = EnumOperations.enumOfValue3 1uy
//printfn "Enum3: %s" (e3.ToString())
//let e4 : BinaryBoolean = EnumOperations.enumOfValue4 1uy
//printfn "Enum4: %s" (e4.ToString())
```

### Related information

* Fable version (`dotnet fable --version`): 2.0.0-beta-001
* Operating system: Ubuntu 16.04 x86_64

**Comment by alfonsogarciacaro** [comment]
Hi @zpodlovics. Thanks a lot for the report, however it seems there are several things going on here and it's difficult to tell me them apart. Would it be possible to post a small failing test reproducing the core issue?

**Comment by zpodlovics** [comment]
@alfonsogarciacaro You mean an example project uploaded as a zip package or a fable test case?

**Comment by zpodlovics** [comment]
I have shrinked the sample code to bare minimal, and uploaded the sample project as a zip file.

**Comment by alfonsogarciacaro** [comment]
Fable test cases are usually the most helpful because it's easier to pinpoint the problem and when it's fixed I can just put the test in the test suite without writing the test myself (it's not always easy to find the proper assertion).

**Comment by alfonsogarciacaro** [comment]
Sorry @zpodlovics, is this still an issue?

**Comment by zpodlovics** [comment]
@alfonsogarciacaro I have to recheck, but I guess it is still an issue (unless significant changes happened with functions & inlining since the reporting)

**Comment by alfonsogarciacaro** [comment]
There's been some works in functions and inlining, but tbh I didn't understand very well the first report. It'd be great if you could post some code easy to reproduce (ideally in the REPL) with an assertion (I expected 5 but got 3, or similar).

**Comment by alfonsogarciacaro** [comment]
Sorry, I was misled by the issue title. If the problem is `LanguagePrimitives.EnumOfValue` cannot be resolved unless inlined, it will be fixed in the next release. I have edited the issue title for clarity.

**Comment by alfonsogarciacaro** [comment]
Ah ok, I think I finally understood the inlining problem! 😅 It was mixed with the `LanguagePrimitives.EnumOfValue` thing, that's what confused me. But I have (hopefully) fixed the inlining of enums now :+1:
