### ISSUE TITLE
Erased DU case not working with variable as key ([<Erase>] Custom of string * obj)

### ISSUE THREAD

**Issue by mvsmal** [fable-compiler/Fable#1542]
### Description

When using a variable for a key of an Erased DU case, the case is not erased, but produces a not erased key and an array as value. Only literal value works. I found this issue when I tried `CSSProp.Custom` from **fable-react**.

### Repro code

```fsharp
type MyType =
    | [<Erase>] Custom of string * obj

let key = "customKey"

let myList = [ Custom (key, "value") ]

// This will work as expected:
// let myList = [ Custom ("customKey", "value") ]

let myObj = keyValueList CaseRules.LowerFirst myList
printfn "%O" myObj
```

### Expected and actual results

_Expected:_
`{"customKey":"value"}`
_Actual:_
`{"custom":["customKey","value"]}`

### Related information

* Fable version (`dotnet fable --version`): 1.3.17
* Operating system: Windows 10

### PS

I tried this code in Fable 2.0 REPL and it works well. So the question: Is v1 still maintained?

**Comment by alfonsogarciacaro** [comment]
Hmm, our development resources are limited so I'd prefer everybody to be moving to Fable 2 so we can focus on it. But if it's very necessary in your case we could try to release a version with a fix.
