### ISSUE TITLE
SVG function for Elmish views generates warnings

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1545]
### Description

When using **dotnet-fable (2.0.0-beta-002)**  and **Fable.React (4.0.0-alpha-001)** we now have warnings printed when using all the `svg` functions.

Warning: `warning FABLE: Type implementing interface must be known at compile time, cast does nothing.`

### Repro code

```fs
let d =
    svg [ SVGAttr.Cx ""
          Id "" ]
        [ ]
```

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! This will be fixed in next release.

**Comment by MangelMaxime** [comment]
Thank you for the fix :)

I guess not much people use SVG in our community :)
