### ISSUE TITLE
Will the fable-core npm package be updated?

### ISSUE THREAD

**Issue by asgerhallas** [fable-compiler/Fable#1565]
Are there any plans to update the npm package (https://www.npmjs.com/package/fable-core) with the new Fable 2 releases? :)

**Comment by Zaid-Ajaj** [comment]
Fable.Core and other Fable packages are no longer distributed to the npm registry but to nuget instead (along with their source files). 

Are you using Fable 0.7.x?

**Comment by asgerhallas** [comment]
Not yet. I am planning to compile an existing library (a simple runtime for a DSL) to javascript to use it in a react native app - so I can just grab the files from the nuget package and use them right now for my initial tests :) 

Thanks!

**Comment by asgerhallas** [comment]
That was not as easy as I expected. Allow me to rephrase the question to: How can I copy/paste the compiled code from the REPL and embed it in my javascript application? :) 

I cannot find the compiled dependency-javascript files in the nuget-package or in the src...
