### ISSUE TITLE
Seq.map val.Split doesn't work, Seq.map val_is_Split does

### ISSUE THREAD

**Issue by rbauduin** [fable-compiler/Fable#1571]
### Description

Using the minimal fable 2 sample, I defined this value in the module `Expenses`:
```fs
let commaSeparator = System.Text.RegularExpressions.Regex(@"(?<=""),")
```

When using it in the update function as this:
```fs
let update (msg:Msg) (model:Model) =
    match msg with
    | OpenFile(csvfile) -> let taggedExpenses = csvfile |> Seq.map Expenses.commaSeparator.Split
                                      model
```

The initial page displayed by the elmish app is blank, ie, the content return by `view` is not present in the page.

To make it work I had to define `commaSeparator` as  (i.e. commaseparator is the `Split` function)
```fs
let commaSeparator = System.Text.RegularExpressions.Regex(@"(?<=""),").Split
```
and use it as
```fs
let update (msg:Msg) (model:Model) =
    match msg with
    | OpenFile(csvfile) -> let taggedExpenses = csvfile |> Seq.map Expenses.commaSeparator
                                      model
```

### Related information
* Fable version (`dotnet fable --version`):

```
$ dotnet fable --version
2.0.0-beta-001

```

* Operating system:
Ubuntu 18.04

**Comment by rbauduin** [comment]
Before opening the issue last week I spent hours to find the workaround, but today I cannot reproduce the problem... It's true I didn't restart the `webpack-dev-server` last week, maybe there was something wrong there?
Anyway, sorry for the noise....

**Comment by alfonsogarciacaro** [comment]
No worries @rbauduin. Yes, sometimes the webpack-dev-server does some weird things. It's usually worth to restart it when seeing some strange behaviour :)
