### ISSUE TITLE
How to deliver mug

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1579]
Congratulations @ncave, you've just received the Community for F# 2018 Hero award! Now we just need  a way to deliver you the mug. Any hint you can provide us to accomplish this mission? :) cc @panesofglass

![image](https://user-images.githubusercontent.com/8275461/46189710-caf0bd80-c2a4-11e8-89d5-6dbcb654cbca.png)

**Comment by ncave** [comment]
@alfonsogarciacaro Thank you, this is really nice, I appreciate it.
A picture is worth a thousand words, as they say, so I'll take it.
And lasts forever (or however long GitHub will be around).
Thanks, cheers, and congratulations on the Fable 2.0 release!

**Comment by alfonsogarciacaro** [comment]
Let's be it then :) Thanks a lot for all your contributions! Everybody was absolutely amazed by the Fable REPL at openfsharp, Don Syme included.

**Comment by ncave** [comment]
@panesofglass Thanks, the awesome F# community recognition itself is very gratifying and more than enough. Congratulations to the other winners @dsyme, @selketjah and @MangelMaxime! Cheers!

**Comment by MangelMaxime** [comment]
Thank you for your congratulation and all the work you are doing. 

🎉 Congratulations 🎉
