### ISSUE TITLE
Strange behavior of min/max function under sub scope

### ISSUE THREAD

**Issue by toburger** [fable-compiler/Fable#1583]
### Description

I have a strange bug since updating to Fable 2.0 in a bigger Elmish app with the min/max function.
min doesn't return the minimum, it returns the bigger number.
When I redefine min/max in a higher-ranking scope, everything works. It looks like the core min function is shadowed by some other min function, but intellisense shows that it is using FSharp.Core.Operators.min.

### Repro code

Sorry, can't reproduce that in a simple example.

This is the code containing the bug:

```fsharp
module App.Common

open Remoting
open Types.Common

// workaround that works
//let min = min
//let max = max

let setFocusedCell direction navigationBounds =
    Option.map (fun (x, y) ->
        match direction with
        | Up -> max (x - 1<x>) 0<x>, y
        | Right -> x, min (y + 1<y>) (snd navigationBounds)
        | Down -> min (x + 1<x>) (fst navigationBounds), y
        | Left -> x, max (y - 1<y>) 0<y>)
```

I had the suspicion that the unit of measures are the problem, but they aren't.

##### This works:

```fsharp
let setFocusedCell direction navigationBounds =
    let min = Operators.min
    let max = Operators.max
    Option.map (fun (x, y) ->
        match direction with
        | Up -> max (x - 1<x>) 0<x>, y
        | Right -> x, min (y + 1<y>) (snd navigationBounds)
        | Down -> min (x + 1<x>) (fst navigationBounds), y
        | Left -> x, max (y - 1<y>) 0<y>)
```

##### This introduces the bug:

```fsharp
let setFocusedCell direction navigationBounds =
    Option.map (fun (x, y) ->
        let min = Operators.min
        let max = Operators.max
        match direction with
        | Up -> max (x - 1<x>) 0<x>, y
        | Right -> x, min (y + 1<y>) (snd navigationBounds)
        | Down -> min (x + 1<x>) (fst navigationBounds), y
        | Left -> x, max (y - 1<y>) 0<y>)
```

So it seems that something is overriding Operators.min/max during execution. 

### Expected and actual results

expected: min 1 11 -> 1
actual: min 1 11 -> 11

### Related information

* Fable version (`dotnet fable --version`): 2.0.1
* Operating system: Windows

**Comment by toburger** [comment]
Here es a screenshot of the min function behavior in the chrome debugger:

![image](https://user-images.githubusercontent.com/728782/46278255-ea6a3d80-c565-11e8-9edd-d4652715fb05.png)

**Comment by toburger** [comment]
Another take to get more information about what's happening:

Log the two min functions to the console.

```fsharp
let setFocusedCell direction navigationBounds =
    Browser.console.log("scope 1: ", min)
    Option.map (fun (x, y) ->
        Browser.console.log("scope 2: ", min)
	...
```

And here is the result:

![](https://i.imgur.com/BBub11u.png)

Detailed scope 1:
![](https://i.imgur.com/Q9oe7n2.png)

Detailed scope 2:
![](https://i.imgur.com/2RtkRVY.png)

**Comment by toburger** [comment]
Another finding:
When inlining the functions the problem exists again:

```fsharp
let inline min x y = min x y
let inline max x y = max x y

let setFocusedCell direction navigationBounds =
    Option.map (fun (x, y) ->
        match direction with
        | Up -> max (x - 1<x>) 0<x>, y
        | Right -> x, min (y + 1<y>) (snd navigationBounds)
        | Down -> min (x + 1<x>) (fst navigationBounds), y
        | Left -> x, max (y - 1<y>) 0<y>)
```

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for such a detailed report @toburger! Would it be possible to post code enough to run the sample? Or at least the type signatures, I'm especially interested to see the type of `y + 1<y>` or `snd navigationBounds`, is it not a number?

**Comment by alfonsogarciacaro** [comment]
Never mind, I think I found the issue :+1:

**Comment by toburger** [comment]
Sorry for my late response...

This is the inferred type. Nothing special, except the unit of measure, which is admittedly a bit overkill, but I wanted to make it impossible to mess up x and y coordinates:
![image](https://user-images.githubusercontent.com/728782/46303549-6edfaf00-c5ac-11e8-8bc6-ed3c30d332d8.png)

**Comment by toburger** [comment]
I can confirm that version 2.0.2 of Fable resolves the issue! 👍🎉

**Comment by alfonsogarciacaro** [comment]
Not at all! Actually the error was different, it was because the generated compare function used values with not unique names (x, y) which where replaced by other optimizations in the pipeline. If it weren't for your insight about `y` being replaced by `tupledArg[1]` it would have taken much longer to realize that, so thanks again!

Can you please try with 2.0.2? Hopefully it's fixed now. In any case, it'd be nice if you could post fully working code so we can turn it into a unit test and prevent regressions.

**Comment by toburger** [comment]
I can confirm that version 2.0.2 of Fable resolves the issue! Thanks a lot!

I will try to make a minimal reproducible example out of my code!

**Comment by toburger** [comment]
I've created a repro here: https://bit.ly/2xP2aKA

**Comment by toburger** [comment]
Sorry to bother again, I've created a much simpler repro: https://bit.ly/2QvKPgT

**Comment by alfonsogarciacaro** [comment]
Awesome, thank you @toburger! :clap: :clap:
