### ISSUE TITLE
Running Fable in non-daemon mode?

### ISSUE THREAD

**Issue by jarcane** [fable-compiler/Fable#1600]
### Description

I've been experimenting with getting Fable running on Glitch, and I've run into a bit of a snag. The container environment on Glitch has pretty limited resources, and the Fable compiler daemon + webpack etc. consumes a significant amount of memory, so that when running it takes up nearly all the available 512mb of RAM leaving nothing left for the server process. In addition, for reasons I can't fathom, the compiler daemon gets stuck in a loop and constantly recompiles the files over and over again.

Thing is I don't really need to have a daemon running at all: Glitch autostarts itself on changes in the editor, so a resident watch process isn't necessary anyway. I really just want to run the compiler once to get a JS bundle, and be done, but I can't seem to figure out a way to do this from the docs or the options in the CLI. 

### Repro code

You can find the code I've been working with on the [Glitch project](https://glitch.com/~fable-compiler-fable2-samples)

### Expected and actual results

Expected: run compiler once, it produces a JS bundle, and exits.
Actual: compiler starts in daemon mode and remains memory resident, continually compiling and re-compiling until server runs out of RAM. 

### Related information

* Fable version (`dotnet fable --version`): 2.0.0
* Operating system: Ubuntu 16.04

**Comment by alfonsogarciacaro** [comment]
Thanks @jarcane! The Glitch project looks very interesting. The problem is that Fable running on .NET doesn't have any code generation or bundling capabilities itself, it only spits JSON files in a format that [Babel](https://babeljs.io/) understands, so we need a way of communicating both processes.

To run Fable on the browser (or in a single Node.js process) our efforts are currently focused [on the REPL](http://fable.io/repl2/) which works by compiling the F# compiler and Fable itself into JS. It would be possible to componentize it if you want to embed it in other sites.

**Comment by jarcane** [comment]
I guess I don't understand then how deployment works for a Fable app? My use case would be the same as generating a static production build, but even in production mode `dotnet fable webpack/-cli` seems to stay resident. 

I guess the assumption is that compilation is handled as part of the server process somehow? That seems to be the case for SAFE Stack if I'm reading the build scripts properly (which I might not be, I'm not really familiar with FAKE).

**Comment by alfonsogarciacaro** [comment]
It depends on your webpack configuration, but if you're not setting the "watch" flag, `dotnet fable webpack-cli` should quit as soon as the bundle is generated.

I'm not familiar with Glitch so I cannot tell what the problem may be, sorry :/ If you want to know a bit more about how the Fable pipeline works, you can read [a brief explanation here](http://fable.io/faq/#how-does-fable-work-).

**Comment by jarcane** [comment]
Well, Glitch is just running whatever I've set to the `install` and `start` scripts in  `package.json`. I guess I'm just not figuring out a correct ´start` script would be to make what I want happen.

**Comment by jarcane** [comment]
Hmm. It seems I'm misunderstanding something about how Glitch works, I don't think it's Fable's fault, as I can run this just fine locally and get what I expect. Apologies. Will close now.
