### ISSUE TITLE
Fable 2.0.4 fails to build on linux (in travis CI) 

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1604]
### Description

Building [tabula-rasa](https://github.com/Zaid-Ajaj/tabula-rasa) repo (branch [upgrade](https://github.com/Zaid-Ajaj/tabula-rasa/tree/upgrade)) locally works perfectly on my windows 10, but once I push code to github, travis becomes [unhappy](https://travis-ci.org/Zaid-Ajaj/tabula-rasa/builds/441395958) when building on a linux vm. 

I assume it has something to do with the project structure, I am getting similar errors to #1599, please see the build log

### Repro code

N/A

### Expected and actual results

The project to build both on windows and linux

### Related information

* Fable version (`dotnet fable --version`): 2.0.4
* Operating system: Ubuntu 14.04 on travis ci

**Comment by alfonsogarciacaro** [comment]
This is interesting, looking at your folder structure, I assume npm packages are installed in `Client/node_modules` so I don't understand why Webpack cannot find `core-js` from there. Does it make any difference if you [remove this](https://github.com/Zaid-Ajaj/tabula-rasa/blob/c5b921d7f11681d7bfb894534c1725041b4769d5/Client/webpack.config.js#L28-L32) or change [useBuiltIns](https://github.com/Zaid-Ajaj/tabula-rasa/blob/c5b921d7f11681d7bfb894534c1725041b4769d5/Client/webpack.config.js#L13) to "entry" or false?

**Comment by Zaid-Ajaj** [comment]
Thanks for taking a look @alfonsogarciacaro I will try these things out

**Comment by Zaid-Ajaj** [comment]
Changing `useBuiltIns` to `entry` fixed the build! :heart: 💯 but what was the difference exactly?

**Comment by alfonsogarciacaro** [comment]
Great to hear it worked! :tada: [According to this](https://babeljs.io/docs/en/babel-preset-env#usebuiltins-usage-experimental) "usage" will try to scan your code and only add the polyfills that you actually use. But it's still marked as experimental so maybe it was failing somehow 🤷‍♂️
