### ISSUE TITLE
Fable CLI doesn't work with Fable.Core v2.0.1?

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/Fable#1618]
### Description

Hi, just updated to Fable.Core 2.0.1, and got this during compilation: `ERROR: Fable.Core v2.0.1 detected, expecting v2.0.0`
The stacktrace contains `Fable.CLI...`, so I guess the problem maybe that I have dotnet-fable (2.0.6), but that wasn't updated ~10 hours ago to match Fable.Core 2.0.1

### Repro code

Just update to Fable.Core 2.0.1
Revering to Fable.Core 2.0.0 solves this

### Expected and actual results

It compiles :)

### Related information

* Fable version: 2.0.6
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
This is why I shouldn't push versions in a rush, sorry! 😬 I just pushed dotnet-fable 2.0.7 to fix this, can you please give it a try!

**Comment by AkosLukacs** [comment]
Almost there :) the new error is: `Error: Fable.Core v2.0 detected, expecting v2.0.1`. I guess the error is somewhere there: https://github.com/fable-compiler/Fable/commit/1b4f084d62faa87375f164dfa05b452363073bcd#diff-54aaa8a512a9985b6a2d892bb3c901f0

**Comment by alfonsogarciacaro** [comment]
Argh, sorry again! My head is not working, can you please try with 2.0.8?

**Comment by AkosLukacs** [comment]
Thanks, works now 🥇 
Too much fable last night? :)

**Comment by alfonsogarciacaro** [comment]
Great, thanks a lot for reporting and confirming! Yes, too much Fable... and beer probably!
