### ISSUE TITLE
adding a replacement for StopWatch

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1619]
I want to add a Replacement for ``System.Diagnostics.StopWatch``.

In a browser environment, this is pretty easy - you can query [ ``performance.now()`` ](https://www.w3.org/TR/hr-time/#dom-performance-now), which is [pretty well](https://caniuse.com/#search=performance.now) supported.

My problem (and why I didn't send a PR yet) is that Fable.Core.JS is environment agnostic - I can't access the browser object from here.

Do you have any ideas if/how best to proceed?

Long term it would be really nice if replacements could be shipped out-of-box. Then the replacement nuget package could reference the browser without any issues.

Short term I can declare my custom Stopwatch in a seperate namespace and do conditional compilation.

**Comment by alfonsogarciacaro** [comment]
Hmm, issues like this keep coming from time to time ;) It's difficult to know where to draw the line of how much of the BCL API we want to support. As you say, `StopWatch` has the added difficulty that it needs to use a native API that is not common across JS platforms. In general we try to be platform agnostic, only in a very few cases we consider the browser to be the default platform which forces us to use a [polyfill in node](https://github.com/fable-compiler/Fable/blob/master/tests/Main/js/polyfill.js). We should try to keep these cases to a minimum.

All in all, I'd prefer not to add a replacement for `StopWatch` for now and let the user write a simple helper if needed (e.g. for [browser](https://github.com/fable-compiler/repl2/blob/405f3cd62208bcb6a1ae9b6690439b3d4973b6ba/src/Worker/Worker.fs#L18-L22) or [node](https://github.com/fable-compiler/Fable/blob/3a989b6d5738e78760ceeeb9949a6ec57ffca0e4/src/dotnet/Fable.Repl/bench/platform.fs#L40-L44)). But it could be a good idea to add those helpers for each platform in Fable.Powerpack.

**Comment by alfonsogarciacaro** [comment]
Sorry, let's close this as we can consider `StopWatch` beyond the BCL we can support in Fable.

**Comment by 0x53A** [comment]
Yes, Stopwatch itself is boring and the technical reasons (no native js timing api) make sense.

In the bigger picture, I would love a revival of some kind of plugin architecture, so that such a replacement could be contributed out-of-box, but talk is easy :D

**Comment by alfonsogarciacaro** [comment]
The main problem of plugins is they require a stable public AST which would make Fable evolution a bit more difficult :/
