### ISSUE TITLE
String.filter Char.IsDigit hangs the browser

### ISSUE THREAD

**Issue by Nhowka** [fable-compiler/Fable#1628]
### Description

Using `String.filter System.Char.IsDigit` causes the browser to consume 100% of CPU .

### Repro code

```fsharp
"Hello! 123" |> String.filter System.Char.IsDigit
```

### Expected and actual results

Expected: `123`
Actual: Everything is frozen

### Related information

Tested on Chrome (70.0.3538.77) on the repl.

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @Nhowka! I think I've found the issue (we had a similar one some time ago), the JS native `.filter` function is injecting the index as second argument to the predicate [here](https://github.com/fable-compiler/Fable/blob/8c1534e7c2efd4505ed237fef5086930f456deaf/src/js/fable-core/String.ts#L490) which confuses Char/isDigit. I've submitted a fix, I'll check if it works in the REPL :+1:
