### ISSUE TITLE
Fable 2 errors when source is in ntfs reparse point

### ISSUE THREAD

**Issue by bilkusg** [fable-compiler/Fable#1632]
### Description

My development source code lives on a different physical drive to my main system, and for many years
I have flattened my namespace by doing a
`mklink /j c:\dev w:\dev`
so that c:\dev and w:\dev refer to the same location

This suddenly became a problem when trying to compile a Fable 2 sample.  It would fail with errors when I used the Elmish library suggesting that various .fs files did not belong to any of loaded projects.

However, if I changed drive to the W drive and ran Fable from W:\dev\src\fable-test rather than C:\dev\src\fable-test, everything works.

### Expected and actual results
Fable should not be confused by paths containing symbolic links / junction points in NTFS

The workaround is to run fable directly from the real drive and not via the reparse point

### Related information

* Fable version (`dotnet fable --version`): ( Any version of Fable 2.x
* Operating system: Windows 10 latest ( 2018 spring ) version. Dotnet core 2.1 node 10

**Comment by bilkusg** [comment]
The workaround is to access the files through their real drive letter and not through the link.

**Comment by bilkusg** [comment]
Sorry - I accidentally closed the issue.

**Comment by chadunit** [comment]
Try setting `symlinks: false` in your webpack config. Reference doc: https://webpack.js.org/configuration/resolve/#resolve-symlinks

**Comment by bilkusg** [comment]
Thanks @chadunit . I can confirm that doing this fixes the problem. It's a bit counterintuitive that this is needed for Fable 2 but not Fable 1, but unless there are undesirable other consequences, it seems like a reasonable solution.  I'd suggest that the error message might usefully be changed to point people at this issue - the 'doesn't belong to any of loaded projects' is just wrong - since the file does belong to the project. Perhaps 'was not loaded under this filename/path. Do you need symlinks:false in your webpack.config?'   or something might save the next person with this issue some time.

**Comment by alfonsogarciacaro** [comment]
Good suggestion @bilkusg! I'll change the error message.

Relates #1490

**Comment by alfonsogarciacaro** [comment]
The error message [has changed](https://github.com/fable-compiler/Fable/blob/2ab66d387d4dc32667e4d6fc5efe0157064ac791/src/dotnet/Fable.Compiler/CLI/Agent.fs#L129) for Fable 2.1 :)
