### ISSUE TITLE
Fable compiler instructions for local use need updating

### ISSUE THREAD

**Issue by bilkusg** [fable-compiler/Fable#1633]
### Description

The instructions in the README.md for how to run a local copy of the Fable compiler don't work as expected.  The fable-next script ( for Windows )
`dotnet run -c Release -p C:\Users\alfonso\Documents\Fable\src\dotnet\Fable.Compiler %* --force-pkgs` 
seems to have two problems.
1. --force-pkgs needs to go after the name of the sub-command ( webpack or whatever ) and before the other parameters
2. An extra -- is needed before %* or dotnet run doesn't pass any extra parameters to the sub-command  such as webpack.

So the command should read:
`dotnet run -c Release -p C:\Users\alfonso\Documents\Fable\src\dotnet\Fable.Compiler -- %*`

and should be called like for example:
`fable-next webpack --force-pkgs -- -config webpack.config.js`

### Related information

* Fable version 2.0.9:
* Operating system:

**Comment by alfonsogarciacaro** [comment]
You're right, I forgot to consider when you pass commands to the subprocess. Hmm, having to add `--force-pkgs` all the time is a bit cumbersome, the tool should detect that is running in development mode. I'll try to make `--force-pkgs` implicit in this case, thanks!

**Comment by alfonsogarciacaro** [comment]
Instructions are [updated now](https://github.com/fable-compiler/Fable#using-your-local-build-in-your-projects) for Fable 2.1 :+1:
