### ISSUE TITLE
for loop var gets overwritten when captured by  concurrent promises

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1634]
_I haven't yet been able to reproduce it standalone in the REPL ..._

I have a really weird issue where it looks like a closure gets overwriten by concurrent promise executions.

The gist of the code is

```f#
        let vertInxMap =
            allMeshRefs
            |> Seq.toArray
            |> Array.map (fun mRef ->
                let mbp = promise {
                    let! m = this.props.LoadMesh(mRef)
                    let meshName = mRef |> System.Convert.ToBase64String
                    let mb = bABYLON.Mesh.Create(meshName, Some e.scene)
                    // fill mb from m
                    return mb
                }
                Fable.PowerPack.Promise.start mbp
                mRef, mbp
            )
            |> FSharp.Collections.Map.ofSeq
            
        for m in renderedDoc do
            let _promised = promise {
                let! mb = vertInxMap.[m.Hash]
                // after the let!, m is overwritten with a different value
                if mb.name <> (Convert.ToBase64String m.Hash) then
                    eprintfn "%s <> %s" mb.name (Convert.ToBase64String m.Hash)
               // do something with mb
                ()
            }
            Fable.PowerPack.Promise.start _promised
```

The reason I am pretty sure this is a compiler bug is, that after changing the lower for-loop to

```f#
        for __m in renderedDoc do
            let _m = __m
            let _promised = promise {
                let m = _m
```

it worked.

**I tried creating a similar setup from scratch in the REPL but failed to reproduce.**

_**If this doesn't immediatly ring any bells, please don't waste too much time, I'll try to reproduce it cleanly again tomorrow.**_

**Comment by alfonsogarciacaro** [comment]
It did ring a bell. I think we had a similar issue because the variables were hoisted and names weren't mangled. However, I tried the following code:

```fsharp
let delay ms x = promise {
    do! Promise.sleep ms
    return x
}

let prs: Map<int, unit -> JS.Promise<int>> =
    [1, (fun () -> delay 500 1)
     2, (fun () -> delay 400 2)
     3, (fun () -> delay 300 3)] |> Map

let ms = [|1;2;3;4;5|]
for m in ms do
    let pr = promise {
        let! mb = prs.[m]()
        printfn "%i" mb
        return mb * 2
    }
    Promise.start pr
```

Which generates this JS for the loop:

```js
for (let idx = 0; idx <= ms.length - 1; idx++) {
  const m = ms[idx] | 0;
  let pr;
  const builder$0040$$1 = PromiseImpl$0024$0024$0024promise;
  pr = Promise$0024002EPromiseBuilder$0024$0024Delay$0024$0024Z243C0199(builder$0040$$1, function () {
    return FSharpMap$0024$0024get_Item$0024$00242B595(prs, m)().then(function (_arg1$$1) {
      const mb = _arg1$$1 | 0;
      toConsole(printf("%i"))(mb);
      return Promise.resolve(mb * 2);
    });
  });
  pr.then();
}
```

This looks good to me because no variable is shadowing any other and `m` is declared as `const` in JS which should create a new instance for each block scope ([we rely on this for tailcall optimization](https://github.com/fable-compiler/Fable/issues/681#issuecomment-280129174)) so not sure what may be causing the problem.

If you cannot isolate the problem, can you use the browser debugger to inspect the values during execution. dotnet-fable 2.0.10 fixes some issues with the source maps and variable names so it should be easier to set a breakpoint (or use `assert false`) and then inspect the values in the local scopes at runtime (I've tested it in Chrome devtools and works fine).

**Comment by 0x53A** [comment]
I reduced it a bit.

```f#

open Fable.PowerPack
                    
type T = { Hash : string }

let renderedDoc =
    [|
        { Hash = "OxQ7ZwCMo1CkZ7ZlGozxp6CS6TsUuffGSWK2ItdzG/k=" }
        { Hash = "uZlsOkx8YZf2k/IKfdNm2W27L4Ru66KBR5sukuRS2c0=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY=" }
        { Hash = "YP5AU4iQhzBVhjeoVVHRT8iSQ5guLT/AEkOmqEn9q7c=" }
        { Hash = "88manZLoR0hUMXwJJ3MXxbdP9NTQlyNVC1b5eAVb80c=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "fLyPRxTqgZ9/R7Riwi3jolx3ULLYCOGvPd7nYlMUf9c=" }
        { Hash = "ywfCv3JOy4bp/xFr9jOWTPHu1WpQ/SPeNpemG/CiX+4=" }
        { Hash = "88manZLoR0hUMXwJJ3MXxbdP9NTQlyNVC1b5eAVb80c=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "yx5bXzTE+92NIRq+fCyTVod1dJfGj0SbkkyKUBNYZ6Y=" }
        { Hash = "d2LyMsAA6WDvX9QrIvCtwEmGB+U3wDOXKHFCLkTlhVI=" }
        { Hash = "88manZLoR0hUMXwJJ3MXxbdP9NTQlyNVC1b5eAVb80c=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA=" }
        { Hash = "0pK5pXYwfiZ9Qq3t6W1Uxu62tyT+hl/KKdXoz2JT3mY=" }
        { Hash = "wjR961JFQcuHhjP3YbX9DVezMT4Ib3fDYHNZJDcn/fA=" }
    |]
//let allMeshRefs = renderedDoc |> Seq.map (fun pm -> pm.Hash) |> set
//Browser.console.log(allMeshRefs |> toResizeArray)
let allMeshRefs =
    [|
        "+AIHvlCdkUZvQaDfetj0NjSA9cIVhh7r3+sJ8bR9hRY="
        "0pK5pXYwfiZ9Qq3t6W1Uxu62tyT+hl/KKdXoz2JT3mY="
        "88manZLoR0hUMXwJJ3MXxbdP9NTQlyNVC1b5eAVb80c="
        "N2frR7k4AG0bcqindQJKsv/s5YMObucDuZyXd6ue+eg="
        "OxQ7ZwCMo1CkZ7ZlGozxp6CS6TsUuffGSWK2ItdzG/k="
        "YP5AU4iQhzBVhjeoVVHRT8iSQ5guLT/AEkOmqEn9q7c="
        "bEw6HOZWJd1TVw3YZ/wNdMNHDtGQ6dfhPAIWHdK7GuA="
        "d2LyMsAA6WDvX9QrIvCtwEmGB+U3wDOXKHFCLkTlhVI="
        "fLyPRxTqgZ9/R7Riwi3jolx3ULLYCOGvPd7nYlMUf9c="
        "uZlsOkx8YZf2k/IKfdNm2W27L4Ru66KBR5sukuRS2c0="
        "wjR961JFQcuHhjP3YbX9DVezMT4Ib3fDYHNZJDcn/fA="
        "ywfCv3JOy4bp/xFr9jOWTPHu1WpQ/SPeNpemG/CiX+4="
        "yx5bXzTE+92NIRq+fCyTVod1dJfGj0SbkkyKUBNYZ6Y="
    |]
printfn "[IFCViewer] %i distinct meshes" allMeshRefs.Length
let vertInxMap =
    allMeshRefs
    |> Seq.toArray
    |> Array.map (fun __mRef ->
        let _mRef = __mRef
        let mbp = promise {
            let mRef = _mRef
            //let! m = this.props.LoadMesh(mRef)
            return mRef
        }
        Fable.PowerPack.Promise.start mbp
        _mRef, mbp
    )
    |> FSharp.Collections.Map.ofSeq

Fable.PowerPack.Promise.start (promise {
    printfn "Starting loop..."
    for x in vertInxMap do
        let! v = x.Value
        if x.Key <> v then
            Fable.Import.Browser.console.error(sprintf "LOOP: %s <> %s" x.Key v )
    printfn "Finished loop."
})
for m in renderedDoc do
    let m2 = m.Hash
    let _promised = promise {
        //let m3 = m.Hash
        let! mb = vertInxMap.[m.Hash]
        if m.Hash <> m2 then
            Fable.Import.Browser.console.error(sprintf "%s %s" m.Hash m2)
        if mb <> m.Hash then
            Fable.Import.Browser.console.error(sprintf "%s <> %s" mb m.Hash)
        ()
    }
    Fable.PowerPack.Promise.start _promised

```


The weird thing is that this fails in my project, but is OK in the Repl AND is also Ok when i create a new project with ``dotnet new safe``.

So maybe it is related to my babel config ...

I'll try to reproduce it in a clean new project, if that fails, I'll try to reduce my actual project to something I can share.

**Comment by 0x53A** [comment]
@alfonsogarciacaro I have it.

It stopped working after I changed something with the babel options in webpack.config.

[fable-test.zip](https://github.com/fable-compiler/Fable/files/2586794/fable-test.zip)

``fake build --target run``

Navigate to http://localhost:8080

![grafik](https://user-images.githubusercontent.com/4236651/48577874-93070d80-e918-11e8-8290-c0ebcd99e845.png)

**Comment by 0x53A** [comment]
So, this looks a bit like a babel issue.

Left is without preset, right is with preset:

![grafik](https://user-images.githubusercontent.com/4236651/48579775-b6808700-e91d-11e8-9612-698a193d25bb.png)

on the right side, ``var m`` is scoped to the nearest function scope, and so there is only one slot for all iterations.

``const m`` is scoped to the iteration, so each iteration has its own slot.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for taking so long to investigate the issue @0x53A! There's indeed a way to print the Babel AST, but if you want to report it's probably better if you can reproduce it in their REPL. For example, [this code with the preset-env enabled](https://babeljs.io/repl#?babili=false&browsers=&build=&builtIns=false&spec=false&loose=false&code_lz=GYewTgBAFANgpgFwgSwCYA8IF4IAYDcKGEAPDgLYDOAdPAHYDmCAFhALQQCMha6A1HwCUEAN4AoCBADGIOpSTlsEKgG1eAXQgAfPPgkR4SAA5g9kmXKQAjAK7IYqOGAAkuXABZcz55yUAFMBByZEo4AElyIxhXXAAmdxj4xPcTIJC4MwgTf0Dg0OS3WIBRALTQgCE7Bydk5IAROBgAQwBPWsL3AC14gGYAYVxOAE4hqFt7Rxc3T29OABoIYBs6KQRkWWhhcUlJMEQbMDoIADEAZWYmsCMAWSajdrj3BkQAfTCEOHIH-NjygFYhn8oCZKAtyIIoIJqCw4HQoEsVmsNlAXpcGJxZlt9DtpLJ5MorEpUWB0bNtLpsTsECA-niQPBgWBkHQEMAoAAiACkyHZggh5CsgkyOL2CAOR1KeTg1D2lHpADc4FABRAAFQQWJCykAXy1kl1mRM0OYsMhem1YiAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=false&presets=env&prettier=false&targets=&version=6.26.0&envVersion=1.6.2) includes a similar example. Although in this case it seems they wrap the loop body in a function which in theory should work. 

> BTW, I think you need to specify `@babel/preset-env` but in your config you've `@babel/env` not sure if it's related. Please also check you're using latest version.

**Comment by 0x53A** [comment]
> Please also check you're using latest version.

I did ``yarn upgrade --all``, that should be enough?

> BTW, I think you need to specify @babel/preset-env but in your config you've @babel/env not sure if it's related.

I *think* babel will automatically prefix everything with ``preset-``.

> [...] it's probably better if you can reproduce it in their REPL.

I tried but couldn't so far.

What i did:

1) I took my code that causes the failure and copy-pasted it into the fable repl.
    ==> That generated nice, correct code that uses ``let`` and ``const``.

2) I then copy pasted that nice JS into the babel repl and selected the preset-env.
    ==> like with your sample, that wrapped the loop body into a function, and so also works.

So it seems like there is a difference between ``AST -> JS(old)`` and ``AST -> JS(latest) -> JS(old)``.

**Comment by alfonsogarciacaro** [comment]
Yes, `yarn upgrade` should be enough. I think I had problems before when not adding `preset-` but if it's working for you, they may have fixed it now :)

There's the [`extra.saveAst` option to print the AST](https://github.com/fable-compiler/Fable/blob/e49bebd3e9cbff26892299aa1cb5d9a4f168e010/src/dotnet/Fable.Compiler/CLI/Agent.fs#L104-L105) but it's been a while since I haven't used it so I'm not sure how it works now. Other times I had to print the AST, I attached a debugger to the Node process and set a breakpoint in the file `node-modules/fable-loader/index.js` in [this line](https://github.com/fable-compiler/Fable/blob/e49bebd3e9cbff26892299aa1cb5d9a4f168e010/src/js/fable-loader/index.js#L65) (or just add a `console.log` there). This will probably easier to do with Fable 2.1 as you can run the Webpack process directly.

**Comment by alfonsogarciacaro** [comment]
@0x53A Was this related to the cold promises? Can the issue be closed now?

**Comment by 0x53A** [comment]
Sorry, I was sick the last few days, and lots of other work before, so I haven't had time to look at it again, what with having a working workaround ...

I don't _think_ this is because of promises, I still think there is a wrong babel transformation somewhere from ``const`` to ``var``.

But as there is no clear fable repro, and I currently blame babel, let's close it for now.
