### ISSUE TITLE
GlobalAttribute on a field compiles down to method calls

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1635]
### Description

When I put ``GlobalAttribute`` on a field, all field reads/writes are converted to function calls on that field.

### Repro code

I had issues with HMR, react, subscriptions, dispatch and everything else, and was experimenting a bit with stashing dispatch in a global.

```f#
[<Fable.Core.Global("__my_dispatch")>]
let mutable dispatch = None

dispatch <- Some 1

let d = dispatch
```

### Expected and actual results

I would have expected this to create a global variable with simple read/write access.

Instead it generated two method calls, which then obviously failed at runtime.

__Actual:__

```js
__my_dispatch(1);

export const d = __my_dispatch();
```

### Documentation

The docs don't go into detail, but from reading https://fable.io/docs/interacting.html#Import-attribute I would expect my code to work.

> If the value is globally accessible in JS, you can use the Global attribute with an optional name parameter instead.

### Workaround

This seems to work:

```f#
// read
let get_dispatch() = unbox Fable.Import.Browser.window?__my_dispatch

// write
Fable.Import.Browser.window?__my_dispatch <- Some d
```

### Related information

* Fable version (`dotnet fable --version`):
REPL https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNSATKXAGICGARrFgMIgBOMLACk0ZSjD706DJm06CAEjCgM+aLACUYrAMY16jFhy5KVE9Vt2UsABUkE00w0lSYnTF+myW9tANoAPHJcvAJYAOJQIOysUAAUAEQA+knAAJ5JYOgErJQ6GAkAlAB8ALrUsJRwwFTG8FloOXkYcAC8cAByIKQwtA1N+XABALRwOCDA8ACMtJVwYG3z2bn5QA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA
* Operating system:

**Comment by alfonsogarciacaro** [comment]
I think this is related to #1314, I need to fix this. As a workaround, it should work if you make the value private.

**Comment by alfonsogarciacaro** [comment]
Closing in favor of #1314
