### ISSUE TITLE
Unable to parse a GUID 

### ISSUE THREAD

**Issue by isaacabraham** [fable-compiler/Fable#1637]
Some GUIDs which appear valid (and tested on full .NET as well) don't work in Fable.

```fsharp
try
    let x = System.Guid.Parse "773788C2-AE1C-2CE4-E053-6C04A8C05E57"
    Browser.console.log (x.ToString())
with
    ex -> Browser.console.log (ex.Message)
```

returns the exception

`Guid should contain 32 digits with 4 dashes: xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx`

cc: @MangelMaxime

**Comment by MangelMaxime** [comment]
I think that the problem is the version of the GUID specification we want to support.

The regex currently used by Fable seems to be implemented for [RFC 4122](https://tools.ietf.org/html/rfc4122).

**Comment by Metal10k** [comment]
This burned me this morning actually. Turns out Guid.Empty does not parse from string either. It was quite tricky to narrow down also because it was happening inside a json decoder.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Should we make it less strict ? 

I know that some web framework took this move for the GUID support.

**Comment by alfonsogarciacaro** [comment]
I think the Guid validating was contributed by @ncave. I guess it's fine to merge a PR (ideally with some tests) if someone wants [to replace it](https://github.com/fable-compiler/Fable/blob/ac85f6426cdb648953fa333086a7c4cd0703d14c/src/js/fable-core/String.ts#L282) with something that matches dotnet behaviour more closely.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! I guess we can try to adapt [some of the tests here](https://github.com/dotnet/corefx/blob/5870ce1bb7df1e609f0ffca809d4048b817d50d6/src/System.Runtime/tests/System/GuidTests.cs#L401). If any volunteer can send a PR that'd be great. If not, I'll try to do it next week :)

**Comment by Metal10k** [comment]
Thanks both! 👍
