### ISSUE TITLE
Question: about fable-compiler-dotnet

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1644]
Apologies for being to enthusiastic, I'm a too curious on this one.
So last week I saw @alfonsogarciacaro [tweeting a story](https://twitter.com/alfonsogcnunez/status/1063406843698036739) about ditching dotnet cli tools.

Now I saw [fable-compiler-dotnet](https://www.npmjs.com/package/fable-compiler-dotnet) on npm.
And from what I learn in https://github.com/fable-compiler/Fable/issues/1621 it would be possible to compile the Fable compiler to have something in js that compiles F# to js.

So what is the story here? Where is this going?

**Comment by MangelMaxime** [comment]
> in js that compiles F# to js.

Just want to clarify this point. We are going to distribute an npm packages with the binaries needed to run Fable Compiler. This is not a JS program that will run but still a dotnet application.

The main difference, is today you are using `dotnet fable webpack` to compile your code. 
But after this changes you will just execute `webpack` and fable-loader will start the Fable compiler to make the compilation.

Exactly in the same way that when you have `sass-loader`, webpack is starting the SASS compiler by itself.

**Comment by nojaf** [comment]
I see, thanks for clarifying that. What will happen to the nuget packages then?
As I noticed `fable-compiler-dotnet` contains `bin\fable-core` with FableCore already compiled. And I can't find any Fable.Core.dll file.
Would other nuget packages follow the same approach? Are we removing the dotnet dependencies this way? And everything for using fable will be listed in the `package.json`?

**Comment by inosik** [comment]
Please see #1639 and especially [Alfonsos comment](https://github.com/fable-compiler/Fable/pull/1639#issuecomment-439364469).

The plan is to remove the need for the _dotnet-fable_ package and distribute the _compiler_ via NPM. Fable _libraries_ (Fable.Core and all others) will continue to be distributed via NuGet.

**Comment by alfonsogarciacaro** [comment]
![image](https://user-images.githubusercontent.com/8275461/48779285-919e6200-ecd7-11e8-9f3a-a0a7052db649.png)

**Comment by nojaf** [comment]
Played with this myself, I like the way this is going where you can have a simple package.json like this
```
{
  "name": "fcd",
  "version": "1.0.0",
  "main": "index.js",
  "license": "MIT",
  "devDependencies": {
    "@babel/core": "^7.1.6",
    "@babel/plugin-transform-modules-commonjs": "^7.1.0",
    "fable-splitter": "^2.1.0-beta-001"
  }
}
```
And compile with `yarn fable-splitter --config splitter.config.js`.

The fsproj project doesn't even need `Fable.Core` references.

Kudos!

**Comment by alfonsogarciacaro** [comment]
And now there's a `--run` option that it's even compatible with watch mode. Check it out!
