### ISSUE TITLE
fable-splitter allFiles: true is being ignored

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1646]
### Description

The `allFiles` option inside a fable-splitter config is being ignored.

### Repro code

```js
const path = require("path");

function resolve(relativePath) {
    return path.join(__dirname, relativePath);
}

module.exports = {
    entry: resolve("src/FableProject.fsproj"),
    outDir: resolve("output"),
    babel: {
        "plugins": ["@babel/plugin-transform-modules-commonjs"]
    },
    allFiles: true // <- ignored
}
```

### Expected and actual results

Workaround is using `--allFiles` in cmd.

### Related information

* "fable-compiler-dotnet": "2.1.0-beta-002",
* "fable-splitter": "2.1.0-beta-002"
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Sorry, this is a regression, can you please try with 2.1.0-beta-003?

**Comment by nojaf** [comment]
Beta 003 works, would it be difficult to add a regression test for this?
It is not the first time I believe this broke. Could you give me any pointers how I could set something up?

**Comment by alfonsogarciacaro** [comment]
Sorry for the so many changes, but we've renamed `fable-compiler-dotnet` to `fable-compiler` for simplicity so if you install beta-004 it will ask you to install the fable-compiler package instead 😅 

Yes, we basically have 0 integration tests so it's difficult to detect these regressions automatically. I'm experimenting with different kind of builds so I don't need to put everything in the FAKE scripts and the npm packages can be a bit independent (although I'm still keeping some dependencies in the repo root to avoid having too many duplicated packages).

Please [have a look at this commit](https://github.com/fable-compiler/Fable/commit/8f5792cafcc296b5f06f9cfcfdaac5b2e9e24362). If you like the way to run the tests you can PR some more. But I warn you I'm still making changes in the `fable2-1` branch :)

**Comment by nojaf** [comment]
This looks exactly to what I had in mind. It will suffice for now.
Hard feelings toward the breaking changes, I'm well aware I'm using alpha/beta bits.
