### ISSUE TITLE
Fable 1 elmish and popups problem.

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#1647]
Hi there, I'm trying to create some simple popup from my Fable 1 + Elmish app. But I can't make it work.

So bsically I need to create a popup on a click event and then store the reference to this popup to call it later and assign a new location to it. It's a basic tric to prevent the popup being blocked by the browser.

So that's what I do: I store a Fable.Import.Browser.window object to my model and then I run some promise and on result I just call the reference from my model and changes its location.

But whatever the way I do that, using Browser.Window or some custom interface via Emit, I always get the same error: `Unable to process a message: RangeError: Maximum call stack size exceeded`

So I wonder what am I doing wrong? Thanks in advance for your answer

**Comment by whitetigle** [comment]
**Context**
basically I just want to do this in my app:

```js
function share(e){
  
  // 1- PREPARE POPUP
  var popup = window.open("", "_blank");
  

  fetch(url, {
    method: "POST",
    headers: { "content-type": "application/json" },
    body: JSON.stringify(data)
  }).then(res => res.json()).then(res => {
   

   // 2- CHANGE POPUP LOCATION
    popup.location.assign(res.facebook);

  
  }).catch(err => {
    console.log(err);
    popup.close();
  });
}
```

**Comment by whitetigle** [comment]
In Elmish + React it would be:
1. create popup on Click event
2. send reference via a Message
3. store reference in model
4. call fetch + promise
5. on result get reference back and assign url.

**Comment by whitetigle** [comment]
(and maybe I'm just to tired to see the obvious error. In that case sorry in advance 😉 )

**Comment by Nhowka** [comment]
Are you using `Cmd.ofPromise` for that?

**Comment by MangelMaxime** [comment]
You can use a scoped variable I think.

```fs
let share e =
    let popup = window.open("", "_blank")

    promise {
        // fetch the data here
        popup.location.assign(res.facebook)
    }
```

**Comment by whitetigle** [comment]
@Nhowka Well I'm using Cmd.ofPromise but later. 

Here is how it works:
- Click event on React component -> create popup and store popup in model
- send message, do things (like fetch and whatever), get back popup reference from model and assign.

@MangelMaxime the popup **must** be created on the click event but yes maybe I could avoid using Elmish to resolve the fetch.

**Comment by MangelMaxime** [comment]
Then you need to have a global variable or a `mutable` in your code.

If you use a global variable you can generate a unique Id for it and store this Id in your model for later access.

```fs
let onClick _ =
    let uniqueId = // generate the unique Id

    window?uniqueId <- window.open("", "_blank")

    StorePopupId uniqueId |> dispatch
```

**Comment by whitetigle** [comment]
Yeah. That's what I thought. 😢 Anyway I will try this. Thanks for you help!

**Comment by Nhowka** [comment]
Not sure how different would be in fable 1, but that kinda of worked on the repl: [Repro here](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNQBQBUD1AsiqfgIZRycFEoAxp0ooQpOJhAB3dgHM4GGXEog4ENPCSpM1AJogIcYRIBm7MHFAAneO1NrOAI0OVEOjL2uCMKSjEFKCFteUks0TkJYNF43DEpKAjQALgB6VJhkdGw5PwwIJywxVOoGAEpaEAIYCQAxZ1gsAGEQWywAKTQyf2sq6iqauHqnRoAJTOrrNCwAJRhOQP7quoaYLHGoSem5hcosAAVepKXB4cb9mRhrfYWAaxOJbWyHxCzMWfnF6nS4FgB5AAiCAAMrRKABPaq-cCZOAAXmocCRcAA3nALhQCHBkkNVlhiIRWnsAEK9aSaaxYADqFmUVVE4iRAF8wZD4Cw0AoEci4AAfOBNWwieAgUy4kZrAkEIlYUkyCnU2nSRHI-lNDCcUhyEVitCUazyFVI-kIay9axwUVwGAAD1IRrgtFgbnYfjgdDK8NR6KqECxcLgADlxPAmQAaAXAMBYUgh2g-ACq+wBAEEACoIJ0wNx+sDC93ATnJDlyT10UBgTLFmFQT3c5HAEQ+KycuCySgYB1qoX+OCkGDSABq3Ag8AAtAA+B08tEYv1enAgYDwftDkehsPTnnIppRrCiw5L9DwOimCASD1wSdb7fbgi9HQwFE32+v50AQjgFoDtWzPiwph-p4ABE8SJCk6QAFZoOIRALDAShQJWlIQgQQgwlgghLqkGhXGgqQAMzAXAADaAC6L6vtuH5wNBXqUtB4gepRVHIrYQTWBI77vtBAD80gwE4aB+DALG3kyZaeuqmraogZqtF2Aoalq8AxNeVEVpkBy+livITnAfwEAypBFD07pnhIWKTnABBYFAIDCMZWCcGgwlyBeoEJAQaSpMBADUaBlBUGk1hGu7RrG-aKaa5rWnaV5TlRZySoS1gkmSCpYaQMGNPZCi2vaIWVlAYV7pFonfKkcCDsQCBUu6thhFcMCWO2ng7IEFTUM6cAAG4oAOVg1nAYDoAQTaePWSKjb1pEClALkxMBjbsGOWWUJw7BXMRFFUSRcBOFQqiFaxSIkWJ25-KQTRQEI9ynadp7ntas3WRdD3io0UoynK5JXFgshhDIWAAAYgwMpBg5eekCj28Aw6NaDjZQPjvQ9nq7R9PIkXqFrATdd1WDA77AWRcAUZVcApvw1CHnI1iRFgwC3HTDPAHAro5gQea9v1A7UDDrOM21LTZSAsBpgzgiiYLvT08LeQdW4wGZB4Y58AQwEC-pQvAFg1jntQQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

```fs

open Fable.Core.JsInterop
open Fable.Helpers.React
open Fable.Helpers.React.Props
open Fable.PowerPack
open Elmish
open Elmish.React

// MODEL

type Model =
    { Popup : Fable.Import.Browser.Window option  }

type Msg =
    | Create of Fable.Import.Browser.Window
    | Change of string
    | Error of exn
    

let init () = { Popup = None }, Cmd.none

// UPDATE

let update (msg:Msg) (model:Model) =
    match msg with
    | Create newValue ->
        { Popup = Some newValue },
            Cmd.ofPromise (fun () ->
                promise{
                    let! r = Fetch.fetch "https://jsonplaceholder.typicode.com/users/3" []
                    let! js = r.json()
                    return !!js?website
                }) () Change Error
    | Change s ->
        model.Popup |> Option.iter (fun p -> p.location.assign ("http://"+s))
        model, Cmd.none
    | Error exn ->
        Fable.Import.Browser.console.log exn
        model, Cmd.none

// VIEW (rendered with React)

let view model dispatch =
    div [ Class "main-container" ]
        [ button
            [
                OnClick
                    (fun ev -> 
                        Fable.Import.Browser.window.``open``() |> Create |> dispatch
                        ) ]
                 [str "Click me!"] ]

// App
Program.mkProgram init update view
|> Program.withConsoleTrace
|> Program.withReact "elmish-app"
|> Program.run
```

**Comment by whitetigle** [comment]
Thanks @Nhowka! Well that's exactly what I did. Don't know why It does not work though.
So I reverted to a simple closure on the OnClick which works well.
