### ISSUE TITLE
Move REPL components to this repository

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1651]
We've talked several times about componentizing the REPL. I've thinking of creating a different repo to host these core components. But given that we're already generating the FCS+Fable JS compilation here and we need some parts for other packages (like the metadata assemblies for fable-compiler-js) it's probably simpler if we generate the components here and pull them from other repos.

So the idea is to put here:

- The REPL web worker that can receive messages to compile, provide tooltips, etc
- The metadata (System.dll and such) + Fable.Repl.Lib assemblies (and precompiled JS files) that must be referenced for the compilation
- The React component for the Monaco editor for F# code.

The fable-compiler/repl should pull these components and provide the rest of the UI and behavior. It will also be the base for other sites that embed the REPL, for example to create Markdown F# tutorials with result evaluation.

It shouldn't be too complicated to create the infrastructure but it's some work, I'll try to start next week, as I'm probably (the only?) person who knows how to fit all the pieces together ;)

cc @ncave @MangelMaxime @whitetigle @tpetricek

**Comment by MangelMaxime** [comment]
I am adding @Krzysztof-Cieslak in the discussion.

**Comment by nojaf** [comment]
>The React component for the Monaco editor for F# code.

Would be interested in this as well, I stole a lot of code to make Monaco work in [AST viewer](http://ratatosk.dynu.net/ast/#?code=Q) 😅. Although I wonder if makes more sense to have a `Fable.Import.Monaco` sort of thing.

**Comment by viebel** [comment]
Please ping me when it's ready. I'd love to integrate Fable with [Klipse](https://github.com/viebel/klipse) to allow F# folks to write blog posts and tutorials with interactive code snippets.

**Comment by alfonsogarciacaro** [comment]
This is complete :) Now assemblies necessary to compile F# projects with Fable are available in the `fable-metadata` npm package, while FCS + Fable compiled to JS are being shipped in `fable-standalone`, together with a web worker that can be embedded in a website.

Fable REPL already depends on these packages. Instructions are more or less like this:

- Copy the contents of `fable-metadata/lib` and `fable-standalone/dist/worker` to wherever you're serving your static files: [example](https://github.com/fable-compiler/repl/blob/d7b4218e1ad869e3879a70b3f30af013b9b50523/build.fsx#L169-L178)
- Add a [reference to these files](https://github.com/fable-compiler/repl/blob/d7b4218e1ad869e3879a70b3f30af013b9b50523/src/App/App.fsproj#L7-L8) in your project (`Fable.Standalone` and `Fable.WebWorker` namespaces respectively):

```
fable-standalone/src/Interfaces.fs
fable-Standalone/src/Worker/Shared.fs
```

- [Start the web worker](https://github.com/fable-compiler/repl/blob/d7b4218e1ad869e3879a70b3f30af013b9b50523/src/App/Main.fs#L24-L26) (`index.js` in the worker folder copied above) and [send the `CreateChecker` message](https://github.com/fable-compiler/repl/blob/d7b4218e1ad869e3879a70b3f30af013b9b50523/src/App/Main.fs#L457-L460) with some info (most importantly where the metadata assemblies can be found).

> Currently the `ObservableWorker` function forces you to do an unsafe cast, I need to fix that.

- Check the src/App/Main.fs file and see the worker messages to learn how to interact with the worker.

**Comment by ncave** [comment]
@alfonsogarciacaro This was an awesome rework and simplification of the repo! Can't wait for the blog post / tweet :)

**Comment by MangelMaxime** [comment]
Awesome work from all of you 🎉

**Comment by alfonsogarciacaro** [comment]
@ncave But you don't have a Twitter account, or do you? ;) TBH, I'm somewhat concerned about making this too public because it's still not trivial to [run the generated code](https://github.com/fable-compiler/repl/blob/d7b4218e1ad869e3879a70b3f30af013b9b50523/src/App/Generator.fs) and I'm afraid if people try to embed the REPL in their sites there will be many more issues to solve :/

**Comment by ncave** [comment]
@alfonsogarciacaro Of course I don't, that doesn't mean I don't follow ;)
I was just joking, whoever wants to know already (probably) knows from following you on GitHub.

Next step -> to the Moon! (I mean, F# projects in REPL, *hint hint elbow jab* ;)

**Comment by viebel** [comment]
I'd love to support F# on [Klipse](https://github.com/viebel/klipse) (js plugin for code evaluation) in the same way Klipse supports [LISP](https://blog.klipse.tech/lisp/2018/05/07/blog-common-lisp.html), [Clojure](https://blog.klipse.tech/clojure/2019/01/08/quines-in-clojure.html) and [ruby](https://blog.klipse.tech/lambda/2016/08/10/pure-y-combinator-ruby.html).

For that purpose, I need simple instructions to follow:
1. A single bundled js file
2. An eval function.

**Comment by alfonsogarciacaro** [comment]
@viebel The instructions to achieve that are [in the comment above](https://github.com/fable-compiler/Fable/issues/1651#issuecomment-463286299). I can help you to reduce them to calling an eval function (and probably an init function at the beginning) but please note without the webworker the user experience is not going to be nice because Klipse UI will freeze while the compiler is loading or compiling.

**Comment by viebel** [comment]
@alfonsogarciacaro I am not worried too much about the freezing of Klipse UI during compilation, assuming that it takes less than 300 msec for short code snippets.

Please help me reduce the instructions to a init + eval  function call

**Comment by alfonsogarciacaro** [comment]
Closing as we're not currently allocating resources into the REPL.
