### ISSUE TITLE
TimeSpan.ToString(string) doesn't work

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1653]
![grafik](https://user-images.githubusercontent.com/4236651/49166874-84ffb680-f334-11e8-9e46-2207d03aac1f.png)

```f#
label [ HtmlFor "stepping" ] [str (sprintf "Increment by %s" (ts:TimeSpan).ToString("mm:ss")))]
```

Would be nice if it either worked or threw a compiler error.

Workaround is simple enough.

**Comment by 0x53A** [comment]
Sure, tomorrow I'll give it a try

**Comment by alfonsogarciacaro** [comment]
Thanks! I knew the gif would work! ;)

**Comment by alfonsogarciacaro** [comment]
For now I just added the error message for `TimeSpan.ToString` with arguments, but it'd be great if you could implement the replacement!

**Comment by 0x53A** [comment]
I knew this would bite me. I should have written "at an indeterminate point in the future" instead of "tomorrow".

Thanks for adding the error, I'll try to get to it the next few days.
