### ISSUE TITLE
FSharp.Core.Result desearilzation is broken

### ISSUE THREAD

**Issue by grishace** [fable-compiler/Fable#1655]
### Description

I have an endpoint returning Result of its operation (the actual type is different, but it's just an alias to Result<string, string>). After upgrade to 2.1.1 tryFetchAs (with corresponding Thoth decoder) is throwing:

```
Error at: `$` I run into a `fail` decoder: Class types cannot be automatically deserialized: Microsoft.FSharp.Core.FSharpResult`2[System.String,System.String]
```

### Repro code

I'm going to create a minimal sample and update the issue.

### Expected and actual results

It was deserializing properly before the upgrade (Fable 2.0.11?).

### Related information

* Fable version (`dotnet fable --version`): 2.1.1
* Operating system: win10-x64

**Comment by MangelMaxime** [comment]
This issue is related to [Thoth](https://github.com/MangelMaxime/Thoth/). :)

So I am moving it: https://github.com/MangelMaxime/Thoth/issues/95

**Comment by MangelMaxime** [comment]
Ah ?! Sorry then 😅

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @grishace! Can you please try with fable-compiler 2.1.2?

**Comment by grishace** [comment]
@alfonsogarciacaro 

Just updated to 2.1.2 and this error is gone! Thanks for the quick fix!
