### ISSUE TITLE
Can two nuget packages use the same module/namespace?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1656]
I'm trying to create bindings for [@material-ui/icons](https://www.npmjs.com/package/@material-ui/icons). There already exists bindings for [@material-ui/core](https://www.npmjs.com/package/@material-ui/core) ([fable-material-ui](https://github.com/mvsmal/fable-material-ui)), which defines the react components under `module Fable.Helpers.MaterialUI`. I would like to have the icon bindings under `Fable.Helpers.MaterialUI.Icons`, but it seems this is not possible. If I use `module Fable.Helpers.MaterialUI.Icons` for my bindings, I get a compilation error in my app (which uses my bindings) because `Fable.Helpers.MaterialUI` exists both as a module and as a namespace. If I instead use `module Fable.Helpers.MaterialUI` and then define `Icons` as a sub-module, I get a similar error (two files defining the same module `Fable.Helpers.MaterialUI`).

I could of course use another module/namespace entirely, such as `Fable.Helpers.MaterialUIIcons`, to get around it, but I would like to use the `Fable.Helpers.MaterialUI.` prefix. Is that possible, or is it simply impossible to use two packages that define the same namespace/module names?

**Comment by MangelMaxime** [comment]
Yes this is possible if the libraries use `namespace` as the root level as in F#.

For example, the `Thoth` ecosystem is using that heavily.

- Thoth.Elmish use `namespace Thoth.Elmish`
    - and define `module Debouncer`
- Thoth.Elmish.Toast use `namespace Thoth.Elmish`
    - and define `module Toast`
- Thoth.Elmish.FormBuilder use `namespace Thoth.Elmish.FormBuilder`
    - and define `module Form`, `module Cmd`, etc.
- Thoth.Elmish.FormBuilder.BasicFields use `namespace Thoth.Elmish.FormBuilder.BasicFields`

You can see some libraries use the same namespace others extends it etc.

I do what you are experiencing is not a Fable limitation but how F# works. In F# you case declare a namespace several times but that's not the case for a module. It's possible that I simplify a bit the situation :)

**Comment by cmeeren** [comment]
Thanks. The way I understand it then, what I'm specifically asking regarding `fable-material-ui` is not possible without `material-ui` changing the namespaces and module names.

> I do what you are experiencing is not a Fable limitation but how F# works. In F# you case declare a namespace several times but that's not the case for a module.

I know this is how things work within any given F# project, but is this also the case between F# projects? E.g. if I have an F# console app or class library (not Fable) and attempt to use two nuget packages that both define `module Foo.Bar`, would compilation of my project fail?

**Comment by MangelMaxime** [comment]
I don't know for "standard" F# compilation. 

But Fable is compiling your project using the sources from your own code and the library code so it's as if everything was a single F# project.

**Comment by cmeeren** [comment]
Thanks, that's what I thought.

**Comment by cmeeren** [comment]
By the way: As I said, I'm creating bindings for native JS react components (to be used as e.g. `alarmIcon [] []`). Is there a "standard" namespace to use for such bindings? `Fable.Import.xx`? `Fable.Helpers.xx`? Something else entirely?

**Comment by MangelMaxime** [comment]
Hum in general we use `Fable.[name of the lib]` for the package name.

<img width="339" alt="capture d ecran 2018-12-02 a 10 54 41" src="https://user-images.githubusercontent.com/4760796/49338385-b6bc9a00-f620-11e8-8345-779de450a17e.png">

And then for the namespace/inside of it we don't have a clear convention.

Some of the namespace we use are:

- `Fable.Helpers.XXXX`
    - [Fable.ReactGoogleMaps](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.ReactGoogleMaps/Fable.Helpers.ReactGoogleMaps.fs)
    - [Fable.React](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.React/Fable.Helpers.React.fs)
- `XXXX` directly
    - [Fable.ReactLeaflet](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.ReactLeaflet/ReactLeaflet.fs)
- `Fable.XXXX`
    - [Fable.Recharts](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.Recharts/Fable.Recharts.fs)


Personally, I am in favor of `XXXX` now because it's following what `ts2fable` use as a convention and make it easy to open the module. Also, you can more easily see/control what the users exposed will be.
