### ISSUE TITLE
Array.choose attempts to construct an array of the input type, instead of the output type

### ISSUE THREAD

**Issue by GBirkel** [fable-compiler/Fable#1658]
### Description

Array.choose attempts to construct an array of the input type, instead of the output type

### Repro code

```fs
let i = [|1; 3; 5; 7|]
type Things = {
    MainThing: int
    OtherThing: string
}
let result = i |> Array.choose (fun x -> Some {MainThing=x; OtherThing="asd"})
let j = result.[0].MainThing
sprintf "0th MainThing is %d" j
```

### Expected and actual results

Expected results:

j is of type "Things array", and the output string is "0th MainThing is 1".

Actual results:

Compiled code turns j into an empty Int32Array.
result.[0]. MainThing throws an exception when run.

Full compiled code:

```js
import { choose } from "fable-core/Array";
import { toText, printf } from "fable-core/String";
import { declare, Record } from "fable-core/Types";
export const i = new Int32Array([1, 3, 5, 7]);
export const Things = declare(function Things(arg1, arg2) {
  this.MainThing = arg1 | 0;
  this.OtherThing = arg2;
}, Record);
export const result = choose(function chooser(x) {
  return new Things(x, "asd");
}, i, Int32Array);
export const j = result[0].MainThing;
toText(printf("0th MainThing is %d"))(j);
```

Workaround:

Avoid Array.choose.  Use Array.filter followed by Array.map.

### Related information

Here is the current implementation of Array.choose :
https://github.com/fable-compiler/Fable/blob/master/src/js/fable-library/Array.fs#L540

Note that the destination array is instantiated based on the type 'T.  There should be another type 'U, like with Array.map

https://github.com/fable-compiler/Fable/blob/master/src/js/fable-library/Array.fs#L174

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @GBirkel! Should be fixed with fable-compiler 2.1.3 :+1:
