### ISSUE TITLE
Fable compiles class methods to loose functions, causing issues with removeEventListener

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1661]
[here](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNSATKXAGICGARrFgMIgBOMLACk0ZSjD706DJm06CAEjCgM+aLACUYrAMY16jFhy5KVE9Vt2UsABUkE00w0lSYnTF+myW97o-NsQAHcJG10Aa1oDWWNBXgE-OS5iQn59GX8uG2DQiMTYrFNVC21faMzFZWLNUus7ekdypLj+QRExCSlaakoATwY4Aj4UADdWcTgAfQAVfGUUUhheVMXSSgAKIYaASjgAXmo4I7gFjAkUSjgfa2WCEFXKAB4IUguAGjgXi4A+Tfs0bbdY5wWCXYBUWJTHSsUhjNBwABccAAQpIgmgJIVpgBZAAy3BhcKQMGAjEuezgpGgUFowNJwHYEkGwzGE0oGHQWEmWlAIyWhNYaAQfLWChhYFganWuwOwOBKAAZlCBfDHt9KdS4OzGIc5XrJtDYYKsAJeTBhWTcehxIs+OsAEQCNAoABeMHtHwAhJ6tRz1AB5UgEo1oLTOt1gQG6o70xl8X2cwPBuHYkAvcRgdY6BGo4IYvhYvHJwXE0lrGXR47sznckkgPnFoUiyhi0gS8zSytHRVwHRwNUaqBQX06vVHA0q-sAWl7Y7gXeOE5DWFYYDAFrWVrQNokDqdrvdXp91YDQZVYYPkdpx1jTJPWCT55g4ZgmZACJA7AAVhW52AQMyCyUAqTD2gA2rMpJQAsMAALpwI+IYXhGnr2teRz1hIwxgPA94CG2u6-mOhpwnAYHEGAcD2pQczQYsjb2gA3FcMBKus3oJqejapumr7bPBYGwdQQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA) is a repl link.

```f#
    member this.OnCanvasResized(o:obj) =
        do printfn "[Timeline] OnCanvasResized!"

// ...

_canvas.addEventListener("resize", !! this.OnCanvasResized)

// ...

_canvas.removeEventListener("resize", !! this.OnCanvasResized)
```

gets compiled down to 

```js

function _TimelineComponent$$OnCanvasResized$$4E60E31B(this$$$2, o) {
  toConsole(printf("[Timeline] OnCanvasResized!"));
}

// ...

    this$$$1._canvas.addEventListener("resize", function (arg00$$1) {
      _TimelineComponent$$OnCanvasResized$$4E60E31B(this$$$1, arg00$$1);
    });

// ...

    this$._canvas.removeEventListener("resize", function (arg00) {
      _TimelineComponent$$OnCanvasResized$$4E60E31B(this$, arg00);
    });
```

This means that my event handlers are never un-subscribed, and one click triggers N messages.

-----------------

I think compiling to functions was an explicit goal to enable tree-shaking?
Then maybe the compiler could detect calls to ``removeEventListener`` and show a warning?
As it stands, this is slightly unintuitive, especially because the exact same typescript code works without issues.

### Workaround

I haven't yet tested it, but I think it should be possible to assign the handlers to mutable let bindings, then remove these:

```fsharp
let mutable handler = null
handler <- !! this.OnCanvasClick
_canvas.addEventListener_click(handler)
_canvas.removeEventListener("click", handler)
```

### Version

``dotnet fable --version``: ``2.0.9``

**Comment by 0x53A** [comment]
I found https://blog.vbfox.net/2018/02/08/fable-react-2-optimizing-react.html

> [...] JavaScript is a weird language where passing this.Add would pass the method add without any this attached, so to keep the semantic of the F# language Fable helpfully do it for us and transpiles it to this.Add.bind(this) instead. But this also re-creates a reference each time so we must capture the bound version in a variable during the construction of the object.

**Comment by alfonsogarciacaro** [comment]
Yes, this is necessary so the `this` context is not lost. Probably you solution works. I think when I had a similar problem I used a local function.
