### ISSUE TITLE
Cannot have two module members with the same name 

### ISSUE THREAD

**Issue by SCullman** [fable-compiler/Fable#1662]
### Description

This complies fine in Fable 1 and Net Standard, but fails in Fable 2:
```
module One =
    type Id = System.Guid

module Two =
    type Id = System.Guid
```
Fable 2 compiler [throws error:](https://fable.io/repl/#?code=LYewJgrgNgpgBAeQHbwLwCg5bgFwJ4AO8AkmHKnAMp4DOOMwAdAOIQCWY66okscAKgHcQ5TNnxE4pclVr0mrDlyA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA) ``Cannot have two module members with the same name:Id``, even in repl. 

One work around is to split up the code into multiple files.   I run into these kind of issues frequently. For instance, it is not supported anymore to have multiple definitions of Elmish Types/State/View modules in one file.

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @SCullman! Is the second case you mention (multiple definitions of Elmish Types/State/View modules) also about type aliases? Can you please try with `fable-compiler` 2.1.5? That should fix the problem (at least for type aliases).

**Comment by SCullman** [comment]
Thanks @alfonsogarciacaro. Tested with ``fable-compiler`` 2.1.6. I was able to rollback all my workarounds.
The second case wasn't about type aliases for sure, but I am also not able to reproduce on the fly. If I run into the case again, I will report.
