### ISSUE TITLE
Missing polyfill for trimStart and trimStart

### ISSUE THREAD

**Issue by nilshelmig** [fable-compiler/Fable#1663]
### Description
Fable 2 seems to translate a `String.TrimStart` call with the `String.prototype.trimStart` function.
The methods `trimStart` and `trimLeft` are at the moment a proposal for the next EcmaScript Version, but not standardized yet. It's also lacking support in older Browser version or Internet Explorer 11.

### Repro code
```fsharp
printfn "right trimmed string %s" ("    hello world".TrimStart())
```
Run this in and old browser like Internet Explorer 11, or Chrome 65

### Expected and actual results
Expected console output: "right trimmed string hello world"

Actual: "Uncaught TypeError: e.trimStart is not a function"

### Related information
Fable version: 2.0.11

**Comment by SCullman** [comment]
Are you using the [webpack config template](https://github.com/fable-compiler/webpack-config-template/commit/001373688d6192e72ed15373aba219c7e4c32771) and ``@babel/polyfill``?

**Comment by nilshelmig** [comment]
@SCullman I'm using `@babel/polyfill` as an entry and have this config:

```javascript
{
  loader: "fable-loader",
  options: {
    babel: {
      presets: [
        "@babel/preset-env",
        {
          useBuiltIns: "entry",
          modules,
          targets: ["last 4 versions", "ie >= 11"]
        }
      ]
    }
  }
}
```

**Comment by SCullman** [comment]
And it is also installed via ``yarn add @babel/polyfill``? I guess otherwise it won't compile. 

Both ``trimStart`` and ``trimLeft`` are part of ``core-js`` since 2.5.0 , which is the foundation of the @babel/polyfill. In my current env, core-js is of version 2.5.1.

**Comment by alfonsogarciacaro** [comment]
Hi @nilshelmig! Did you check @SCullman latest comment (thanks a lot for the help, btw!)? Did it help?

**Comment by nilshelmig** [comment]
It's working now! I seems that core-js was outdated, but I don't know why. I have `@babel/polyfill` installed at the latest version, which brings `core-js` 2.5 as a dependency, but the files `es7.string.trimLeft` and `es7.string.trimRight` weren't in the core-js module directory.

I just deleted the node_modules folder and execute `yarn install` again.

Thanks for your help!
