### ISSUE TITLE
Cannot retreive metadata of built-in Choice type (v2.1.4)

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1664]
Same issue as #1655 but for for `Choice<'a, 'b>` type

**Comment by alfonsogarciacaro** [comment]
Ups, I shouldn't have been lazy and [fixed this TODO](https://github.com/fable-compiler/Fable/commit/a85ba272ca8d86e56a69ea46c47e578f05f24a5a#diff-a34e57b30a53951ff9b99ce4076feaa4L134) together with the Result reflection 😅 Can you please try with 2.1.6? (Yes, 2.1.5 was just published 30 minutes before :wink:)

**Comment by Zaid-Ajaj** [comment]
Thanks for the quick fix! I will migrate SimpleJson soon to Fable 2.1.x to test these edge cases :smile:
