### ISSUE TITLE
Detect Fable.Core.ImportAttribute in GetDeclarationLocation

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1677]
Hi @ncave, I was thinking that it would be very nice if, when running `GetDeclarationLocation` we could detect if the method has a `Fable.Core.Import` attribute and in that case go to the imported js/ts file an search for the `export (function|const) memberName` pattern. However, the types in service.fs are very different from the Tast and I'm not sure where to start. Would you have any pointers?

> I'm opening the issue here, but if the code is not very intrusive it would be interesting to push it to FSC so it can be used by other editors.

**Comment by ncave** [comment]
@alfonsogarciacaro 
If you are getting the decl location range back, can you use that to check if the decl location is an import and do the search in a similarly named imported js/ts file?
Unless you get as a result `DeclNotFound` or `ExternalSymbol`?
I guess what I'm asking is, can this be done outside of FCS, so you wouldn't have to send all the imported js/ts file sources in?

**Comment by alfonsogarciacaro** [comment]
So with the declaration range you have access to the member object and the attributes? I had a quick look but got the impression it was not possible, but if it is, yes, as long we can se the Important tribute and the constructor arguments then we can do the rest of the work outside of FCS. I'll check again. Thanks for your help!

**Comment by ncave** [comment]
@alfonsogarciacaro If you get the location of the declaration, perhaps a regex can then be used to figure out if that declaration is an import? Or `GetSymbolAtLocation`, then look up the symbol attributes? I haven't actually tried any of those, just spitballing here.

**Comment by alfonsogarciacaro** [comment]
That may work indeed, I will try. Thanks for the suggestions!

**Comment by alfonsogarciacaro** [comment]
After thinking about it, it's probably better if Fable doesn't messes up with IDE work, as there are too many of them to support :)
