### ISSUE TITLE
Rounding Error on Decimals

### ISSUE THREAD

**Issue by robkuz** [fable-compiler/Fable#1682]
### Description

`System.Math.Round` is not calculating the correctly

### Repro code

Expected
`System.Math.Round(2.2m, 2) != 2.2m`

But gives 
` System.Math.Round(2.2m, 2) != 2.0m`

### Related information

* Fable version (`dotnet fable --version`): 2.1.8
* Operating system:

**Comment by alfonsogarciacaro** [comment]
This should be working with latest Fable and hopefully you should have it now in your project :) Is this still an issue for you?

**Comment by robkuz** [comment]
This happens on 2.1.8 (the latest as far as I know)

**Comment by alfonsogarciacaro** [comment]
Ah, sorry, I just noticed I wasn't passing the digits for decimals (only for floats). [It will be fixed in next release](2e1541796dd80844a4d4ab02ef7735c9684e47c6).

**Comment by alfonsogarciacaro** [comment]
Closing as this should be fixed in latest Fable. Please reopen if you still have problems.
