### ISSUE TITLE
System.Math.Truncate and other Math operations are missing

### ISSUE THREAD

**Issue by robkuz** [fable-compiler/Fable#1683]
### Description

`System.Math.Truncate` is missing. This is probably related to https://github.com/fable-compiler/Fable/issues/1682
`**` (pow PowerOf) is missing on all numerical types except for floats

* Fable version (`dotnet fable --version`): 2.1.8

**Comment by alfonsogarciacaro** [comment]
If I'm not mistaken the `**` [only works for types implementing `Pow`](https://github.com/Microsoft/visualfsharp/blob/fead0aac540485683f694524eadad79983ec28d9/src/fsharp/FSharp.Core/prim-types.fsi#L2508-L2512) like floats or bigints (decimals don't implement it). However you can use `pown` as in `pown 2.2M 3`.

About `Truncate`, it's true it's not implemented. I'll do it for the next release. For now you can use `Math.Floor` (for positive numbers).
