### ISSUE TITLE
Cannot type test: interface

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1685]
### Description

I have a scenario where I'm hitting [Cannot type test: interface]().

### Repro code

See https://github.com/nojaf/gmap-repro

### Expected and actual results

Behavior is normal as I'd expect when looking at the [source](https://github.com/fable-compiler/Fable/blob/100ceebb044cc4fc13f227924c7af092d03bfadf/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L892). However this blocks me, is there a workaround for this?

### Related information

* Fable version (`dotnet fable --version`): 2.1
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
This behavior is indeed normal.

In Fable 1 we were allowing type test against interface but it was actually doing a "real" test only if this was an real F# type (not coming from a binding).

I can't see the type test in your repro code.

You can see a more complete answer [here](https://github.com/fable-compiler/Fable/issues/1580#issuecomment-428496491)

**Comment by nojaf** [comment]
Hi, I'm still a bit confused about this. Reading #1580 didn't really help.
In my repro the problem occurs when using `LatLng` type in [App.fs](https://github.com/nojaf/gmap-repro/blob/master/src/App.fs#L7). 
Why is [LatLng](https://github.com/fable-compiler/fable-import/blob/master/GoogleMaps/Fable.Import.GoogleMaps.fs#L1886) a problem?

**Comment by MangelMaxime** [comment]
I don't know because for me type test is something like:

```fs
match typ with
| :? MyInterfaceType -> // etc.
| U2.Case2 _ -> // where typ is U2.Case2<MyInterfaceType1,MyInterfaceType2> 

etc.
```

In your case you are just using the type for "typing" the variable. Is it working if you replace `failwith` with a "valid" (`failwith` should be valid I know) code.

**Comment by nojaf** [comment]
Even if I change my own code to something else than `failWith` it returns the same errors:
```
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2275,55): (2275,56) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLng"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2276,55): (2276,56) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLng"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2278,62): (2278,63) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngLiteral"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2279,62): (2279,63) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngLiteral"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2281,61): (2281,62) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngBounds"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2282,61): (2282,62) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngBounds"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2284,68): (2284,69) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngBoundsLiteral"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2285,68): (2285,69) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.LatLngBoundsLiteral"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2287,55): (2287,56) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.Circle"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2288,55): (2288,56) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.Circle"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2290,62): (2290,63) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.CircleLiteral"
C:/Temp/gmap-repro/.fable/Fable.Import.GoogleMaps.0.1.0/Fable.Import.GoogleMaps.fs(2291,62): (2291,63) error FABLE: Cannot type test: interface "Fable.Import.GoogleMaps.CircleLiteral"
```
This suggests that the problem is in [the binding file with LocationBias](https://github.com/fable-compiler/fable-import/blob/master/GoogleMaps/Fable.Import.GoogleMaps.fs#L2269-L2294).

If I comment that part out Fable is able to compile this.
@forki are you using `LocationBias`? Perhaps we can remove it? Or re-write it in a way Fable can deal with it.

**Comment by MangelMaxime** [comment]
Definition for reference: https://developers.google.com/maps/documentation/javascript/reference/places-service#LocationBias

@nojaf Yes, I would because the current code is invalid for Fable. If you can just comment the `LocationBias` type and module so we still have it under hand for later if we find a better solution.

**Comment by nojaf** [comment]
Thanks, I've made https://github.com/fable-compiler/fable-import/pull/74. Let me know if it requires any changes.

**Comment by MangelMaxime** [comment]
Fable.Import.GoogleMaps 0.2.0 has been released (you need to wait after nuget ;) )
