### ISSUE TITLE
Fable produces name collision when using parameter name `document` and using Browser.document in the same scope

### ISSUE THREAD

**Issue by legezam** [fable-compiler/Fable#1687]
### Description

If you have a function that accepts a parameter with name `document` and this function also uses the Browser.document, the produced javascript code is ambiguous and breaks.  please see the fable repl repro for further details.

### Repro code

https://bit.ly/2Q0BHAd

the only difference between myfunc and myfunc' is the name of the parameter.

### Expected and actual results
I would expect an unambiguous js product for myfunc' just as myfunc has. The example code runs to js error: `document.getElementById is not a function` as it tries to call .getElementById on the string parameter and not on the browser.document.

I can imagine two fixes:
1. Fable issues compiler errors when detects such issues
2. This one requires more heuristics as Fable should resolve such issue by renaming the parameter in the produced code so it is not clashing

### Related information

* Fable version (`dotnet fable --version`): 2.0.11
* Operating system: -

**Comment by inosik** [comment]
`document` should be added here:

https://github.com/fable-compiler/Fable/blob/218bf8d601e211cc67c5b742b5755859102fbb40/src/dotnet/Fable.Compiler/Global/Prelude.fs#L207
