### ISSUE TITLE
TimeSpan.Parse and TimeSpan.TryParse missing support

### ISSUE THREAD

**Issue by rfrerebe** [fable-compiler/Fable#1694]
### Description

There is no replacement function available in Fable for TimeSpan.Parse and TimeSpan.TryParse in Fable.

Proposed Pull request : https://github.com/fable-compiler/Fable/pull/1695

There is a one quirk that is not replicated :
* `24:00:00` is understood as [24 days](https://docs.microsoft.com/en-us/dotnet/api/system.timespan.parse) by dotnet, while it will be not valid in fable

Also I was unable to use a toString() function (commented in this pull request).
Any help on how to amend [Replacement.fs](https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/Transforms/Replacements.fs#L2277-L2289) is welcomed :smile:

**Comment by alfonsogarciacaro** [comment]
Closed by #1695. Thanks again for your contribution @rfrerebe!
