### ISSUE TITLE
Arguments cannot be passed byref

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1696]
### Repro code

Given the following code:

```fs
open System.Collections.Generic

let cache = Dictionary<string, int>()
cache.Add("un", 1)
cache.Add("deux", 2)
cache.Add("trois", 3)

let mutable res = -1
let mutable test4 = false

test4 <- cache.TryGetValue("un", &res);;
```

Over dotnet runtime, we get:

```fs
printfn "%A" test4
// Gives: true

 printfn "%A" res;;                      
// Gives 1
```

While over Fable, we get:

```fs
printfn "%A" test4
// Gives: true

 printfn "%A" res;;                      
// Gives -1
```

Note that we get `-1` instead of `1`.

### Expected and actual results

It should output `1` for Fable too.

---------

For me the problem is in [this function](https://github.com/fable-compiler/Fable/blob/21eb9adc771fbd0dde92ab30d14fc90b8ac063dd/src/js/fable-library/Util.ts#L89-L91). It consider the third argument as a `defaultValue` while .Net documentation says:

> When this method returns, contains the value associated with the specified key, if the key is found; otherwise, the default value for the type of the value parameter. This parameter is passed uninitialized.

[Source](https://docs.microsoft.com/en-us/dotnet/api/system.collections.generic.dictionary-2.trygetvalue?view=netframework-4.7.2)

I don't know if others `tryGetValue` methods except the same behavior or no. And so if we should create a new function, also how to generate the default value for the expected type from runtime or should fable inject another arguments ?

**Comment by MangelMaxime** [comment]
Ah ok I didn't know that.

I couldn't use `let ok, res = cache.TryGetValue("un")` version because the variable are defined outside the scope using `mutable`. It's a low level code that's need this kind of "optimization".

But I found a work around to my problem.

**Comment by ncave** [comment]
@alfonsogarciacaro Yeah, a few, but they may or may not be of any use :)
- The particular need to throw error on `TryGetValue` (and `TryParse` etc.) with a `byref` parameter can be solved by limiting the number of parameters we're matching on (as the `byref` parameter is an extra parameter).
- That solves this issue, but not the general case of using `byref` parameters. Unless we can somehow restrict that usage to `Result` type only, perhaps by entity name?
-  This was probably already considered in the past and rejected for some reason, but what about actually implementing support for `byref` parameters, by wrapping them in an object?

**Comment by alfonsogarciacaro** [comment]
> That solves this issue, but not the general case of using byref parameters. Unless we can somehow restrict that usage to Result type only, perhaps by entity name?

It seems `AddressOf` is used whenever the contents of a struct class/union/record/tuple are accessed, so we would need to find a condition other than the name to discriminate the uses.


> This was probably already considered in the past and rejected for some reason, but what about actually implementing support for byref parameters, by wrapping them in an object?

Hmm, right now we're actually [doing something similar](https://github.com/fable-compiler/Fable/blob/fc5a94fac5a2668b34a48133693acce8cd8e2add/src/dotnet/Fable.Compiler/Transforms/Fable2Babel.fs#L1465-L1471) for mutable public values, so it could be possible to do it. For private and local mutable values we'll need to create a getter and setter that access the original value. Something like:

```js
export function createAtomAdHoc<T>(getter: () => T, setter: (v: T) => void): (v?: T) => T | void {
    return (value: T) => value === void 0 ? getter() : setter(value);
}
```

So the following code:

```fsharp
let mutate (i: int byref) =
    i <- i * 2

let test() =
    let mutable x = 5
    mutate &x
    log x
```

Would become:

```js
function mutate(i) {
    i(i() * 2);
}

function test() {
    let x = 5;
    foo(createAtomAdHoc(() => x, (v) => { x = v; }));
    log(x);
}
```

**Comment by alfonsogarciacaro** [comment]
A problem with that approach ☝️ however is devs tend to pass arguments byref for performance reasons (as @MangelMaxime was trying to do) and with the wrapping probably using `byref` becomes actually less performant.

I still couldn't find a way to distinguish the _explicit_ AddressOf when using the `&` operator and the _implicit_ AddressOf when accessing the contents of a struct type (for example, check the AST in [this snippet](http://ratatosk.dynu.net/ast/#?code=DYUwLgBAtgrmCGYQQBQA8BcEDk8ICMBPAJxADMBKVQrXKgXgCgIWI0IAeAWgkMcdCQkAZzAoGzVoOhx4+UGwj0IAeQDWEAKySWsBEggAydigCixYgHtiEAERlLl2xR3REAYwAWigO4BLME9XAB9VDT8ILgA+CAAHYj8AOzAyRLsAUj9bCD8QiHMrG2RouITk1IzhbJBXcX4RMQogA)). So for now, I just [added a check for call arguments](https://github.com/fable-compiler/Fable/commit/f3ee94bc0cbdf42e5ffba88ceaa8041eb4b6da71). This raises a warning atm to prevent regressions, but if we see it's safe we can turn it into an error.
