### ISSUE TITLE
Clarify list vs. seq vs. array vs. ResizeArray

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1702]
I am creating bindings for [match-sorter](https://github.com/kentcdodds/match-sorter) and noticed that ts2fable outputted signatures containing ResizeArray. This seemed a bit weird to me, and I tried replacing them with `seq`, which worked fine without me needing to convert to and from ResizeArrays.

Trying to get to the bottom of this, I have [experimented a bit with the REPL](https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNQBQBUD1AsiqfgIZRycFEoAxp0ooQpOJhAB3dgHM4GGXEog4ENPCSpM1AJogIcYRIBm7MHFAAneO1NrOAI0OVEOjL2uCMKSjEFKCFteUks0TkJYNF43DEpKAjQALgB6VJhkdGw5PwwIJywxVOoGAEpaEAIYCQAxZ1gsAGEQWywAKTQyf2sq6iqauHqnRoAJTOrrNCwAJRhOQP7quoaYLHGoSem5hcosAAVepKXB7WyTiTPMWfnF2lg3NEprAEFra04ATzhkrw-PgA8T2s8gAfHAALxwADaAB9YQBdagPODsShvf4-P5fAFo8FQuGI+4wR7PAAy6DcvyglKBzzBkLgMKRKLRFKeWJpT1xpEo+KZ0KRyJJkmeOBgAEcAIxYzQSukg0hyfniiVYGCESifYWk6yqgBMsslCoZUIgBGEHMFOtFeslAGYjfLgab1BbOFaAEScT0skXA1UAFidJqVKslWBApnZbmh3t9NoDkoArCGXWHGXK4ABvOCfFCZSzxuAAX2JbjRqplvzlPL5jNV6s12tZvINIbxjPNltjforbYdHd5-O7HtjUr7qIHEuDNeNnahjajMZhE5tlZTQ-rUKzufzhbgMrLieeM041bgczQKAAXjAMTj08rGVfb-f3l86BUUcCz4bfq+d4PoCT78oB77-HQcY+gi34imiZ4XuBwF1mBMDXkBH6fF+668n+WLIVhqEvuhb7AVBE4VEAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA) to see how various enumerables are compiled. I'm not a JS guy and am a bit confused, to say the least. There seems to be a lot of different underlying APIs; `[]` vs `new Int32Array([])`, the Fable `List` and `Seq` APIs, `[]` vs. `Array.from(["a"])`... 😵

I can't find any official Fable documentation on which enumerable type to use for which purposes. I'd very much like to know some more details about this, both for curiosity's sake and for performance reasons - I don't want to use unnecessarily slow/inefficient collections, and I would also like to avoid converting back and forth between different types unnecessarily.

Would it be possible to get some official clarification on this topic? :)

**Comment by alfonsogarciacaro** [comment]
It's somewhat succinct, but you can read an explanation of how .NET/F# collections are compiled to JS in the [compatibility docs](https://fable.io/docs/compatibility.html). Basically:

- `seq` is being compiled as [JS iterable](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Iteration_protocols) for compatibility with JS libraries.
- `array` is compiled as JS arrays. But in the case of numeric arrays, they're compiled as [Typed Arrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Typed_arrays) when possible. You can disable this behaviour by setting the [`typedArrays` option](https://www.npmjs.com/package/fable-loader#options) to `false`.
- `ResizeArray` is always compiled as JS array, as this can be resized by default. This is why this was originally picked to translate JS arrays in ts2fable.
- `list` has no equivalent in native JS, so it's compiled as a specific Fable type.

**Comment by cmeeren** [comment]
Thanks! What I'm mostly wondering about is performance. As you say, `list` is the most pleasant and safe to use from F#, especially for Elmish since it's immutable and has structural equality, but converting between `list` and `ResizeArray` surely has some cost. But how much, is the question. (Some cursory testing with match-sorter yesterday indicated that in that specific case, match-sorter's internal logic takes so much longer than the conversion that's it's not noticeable, but I'd like some general understanding/advice.)

By the way, I tried naïvely replacing `ResizeArray` with `list` in the return value of a match-sorter binding, which did not produce compile-time warnings or runtime exceptions, but had the effect of the function not returning any items at all. Is that a bug?
