### ISSUE TITLE
Fable generates curried callback instead of tupled

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1703]
### Description

I am using BabylonJS and calling [SceneLoader.ImportMesh](https://doc.babylonjs.com/api/classes/babylon.sceneloader#importmesh).

With ts2fable@next I generated a mostly working binding and fixed a few small things up.

The generated binding for this method looks like this:

```f#
abstract ImportMesh: meshNames: obj option * rootUrl: string * sceneFilename: string * scene: Scene * ?onSuccess: Nullable<(ResizeArray<AbstractMesh> -> ResizeArray<ParticleSystem> -> ResizeArray<Skeleton> -> ResizeArray<AnimationGroup> -> unit)> * ?onProgress: Nullable<(SceneLoaderProgressEvent -> unit)> * ?onError: Nullable<(Scene -> string -> obj option -> unit)> * ?pluginExtension: Nullable<string> -> Nullable<U2<ISceneLoaderPlugin, ISceneLoaderPluginAsync>>
```

Note how ``onSuccess`` uses a curried form.

When I then call that binding, Fable generates 4 curried functions instead of one tupled:

```f#
bABYLON.SceneLoader.ImportMesh(None, urlPart, filenamePart, se.scene, Some(fun m _ _ _ -> printfn "Hello from Callback"))
```

```js
    babylonjs__WEBPACK_IMPORTED_MODULE_0__["SceneLoader"].ImportMesh(null, urlPart, filenamePart, this$$$4.se.scene, Object(_fable_fable_library_2_1_10_Option__WEBPACK_IMPORTED_MODULE_10__["some"])(function(m$$2) {
        return function(_arg3) {
            return function(_arg2) {
                return function(_arg1) {
                    Object(_fable_fable_library_2_1_10_String__WEBPACK_IMPORTED_MODULE_9__["toConsole"])(Object(_fable_fable_library_2_1_10_String__WEBPACK_IMPORTED_MODULE_9__["printf"])("Hello from Callback"));
                }
                ;
            }
            ;
        }
        ;
    }));
```

### REPL

https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNSATKXAGICGARrFgMIgBOMLACk0ZSjD706DJm06CAEjCgM+aLACUYrAMY16jFhy5KVE9Vt2UsABUkE00w0lSYnTF+myW9tA7ONBXgF3I3ksYkJ+fRkwk2VVC21ffzjFBPNNZOs7ekdUuS5gwRExCSkCwIiovmsAIUkAdzQJWkoATwY4ADloKECAHgByABUAPjgAXmo4WbhRuHpKFBBSWgB6dbhIYFQYRw6unB1GeEnF9gArakP4AEF2NEo+KwBZfYwpi+vbuBtWWooHSwHDtJ4wYBfEBXG6deA4ADWyhglFWUJhvzupHwrGWqwA4pIIAR0T84XBjqcADIgVhgCS5ADmAjQaAQADdGJRSbCusRKaQYDS6QyoBBGSgmOdoWS+QKhbT6XwbGKJaQ7mh2qQdDzefAANoDO5QKAgRq9E1UlDiF5QMYAXQpJ0FwqVOEouKBUxmc02cCwAZ9sw4TxeejgkQI0XemAAXHBgB9uqxE2h4zLFgQ8UwAFRwSQgSgAVT4UHjocljLgebQzpgzBQsFIKZg5eelercFrp3j8s7AH5VjgIDoTqz4xb+vIBgAKLRoFAALxgdz4L3aRsezzeHwmAFoJvOlyu16wN-9AcCYKDwcB94f9sfV+uBojkajSPe4Efl8+z0bsWAT0CSJAgvwgbFKAASgmPNB1IJkWTTHo+kGGd5VdBlJGZfY2U5UhuQPOAIOtGCB1WBA134CdUOndC6zgIiK1IKsiIzJYViYIiSOg2C4H7IhxUlBAAA9xFIBdVhok1BmYxkv0nQYiwAJgGfk60w5VVUlAAaCMMMVUUhPVTVtTGMY2nJQ1jVNc0+itG1WDtR1iFEqNajQb05jgENt3DAyRT4XsNMMvh3U9HRaFgblDUjaIZwAIhzBKdIS9gOHaU1SEuNAEpgx12DuOoAE0qQAeW6eNXJE9zKE884cuTZZOSilEuwY4LTlJGcoOoaK4AAfS+QqSvK7pcBCwLqlqmMMBnbpVhgPSEpSuAVr07tBT0nAQETGcADMIITQaTqGoiCD4SVKH2pgEtMU04H2yRIW4JyoHSnQETyqCgA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA

### Related information

I'm not even sure if this is a Fable issue or a ts2fable issue. I can probably work around this issue by changing the callback to a tupled form in the generated binding (didn't test yet), but there are a few callbacks in babylonjs and I don't really look forward to fixing them all manually.

* Fable version:  `yarn info fable-compiler version` ``2.1.10``
* Operating system ``Win 10 x64``

**Comment by alfonsogarciacaro** [comment]
Hmm, apparently the nested option (the implicit option because of optional argument `?onSuccess` and the explicit option, in your case the `Nullable` alias) is interfering with the auto uncurrying feature.

I'll have a look. For now you can either make the argument not optional, or remove `Nullable`. I assume this will improve compatibility with Babylon, because the JS library won't recognize Fable's `some` wrapper.

**Comment by 0x53A** [comment]
The ``some`` doesn't seem to be an issue, if I set a browser breakpoint inside the outermost callback, then that callback gets hit.

For now I've removed the ``Nullable<>`` from the few callbacks I needed and it seems to work ok.

Maybe it would be better to teach ts2fable about this "pattern"?

In TS, the parameter is ``function | null | undefined``:

```ts
static ImportMesh(meshNames: any, rootUrl: string, sceneFilename?: string, scene?: Nullable<Scene>, onSuccess?: Nullable<(meshes: AbstractMesh[], particleSystems: IParticleSystem[], skeletons: Skeleton[], animationGroups: AnimationGroup[]) => void>, onProgress?: Nullable<(event: SceneLoaderProgressEvent) => void>, onError?: Nullable<(scene: Scene, message: string, exception?: any) => void>, pluginExtension?: Nullable<string>): Nullable<ISceneLoaderPlugin | ISceneLoaderPluginAsync>;
```

![grafik](https://user-images.githubusercontent.com/4236651/50979928-d71d2580-14f7-11e9-99ea-1eaf18118d71.png)

Maybe it would be enough to erase aliases for ``Option`` in ts2fable, so it can _see through_ ``Nullable<T>``.

**Comment by alfonsogarciacaro** [comment]
Probably. I'm not maintaining ts2fable myself now, so I'm not sure how it works in this case. Maybe you can open an issue in that repo. In any case, it's hard to keep up with the constants changes in Typescript type system and making the right decision on how to translate its specificities to F#.

**Comment by 0x53A** [comment]
should be fixed by https://github.com/fable-compiler/ts2fable/pull/277 if/when that is pulled.

I tested the change on babylonjs and it looks good, now I just need to add some tests.

Any additional eyes welcome.
