### ISSUE TITLE
Fable 2.0 must return function for react `createElement` like [<Pojo>] used to

### ISSUE THREAD

**Issue by Stuey2** [fable-compiler/Fable#1709]
### Description

React native fails to render without `[<Pojo>]` attribute. This can be seen in the emulator as the error: 

![image](https://user-images.githubusercontent.com/14346963/51267351-64a7bc00-19b5-11e9-892c-6756f9c188b8.png)

### Repro code

React native project using Fable 2.0

### Expected and actual results

The specific place which causes the error is here:

![image](https://user-images.githubusercontent.com/14346963/51267426-a3d60d00-19b5-11e9-8229-ffd1e93098e2.png)

This returns and `object` type instead of a `function` type, which is required by `createElement`

![image](https://user-images.githubusercontent.com/14346963/51267854-9c633380-19b6-11e9-947b-b761b2cf5218.png)

### Related information

Fable.Core (2.0.3)
Fable.Elmish.React (2.1)

**Comment by alfonsogarciacaro** [comment]
I think this is because `typeof<'T>` doesn't return the function constructor in Fable 2. I've sent https://github.com/elmish/react/pull/33 to fix that, but I haven't tested it. It's possible for you to create your custom `withReactNative` function with the change and confirm if it works?

**Comment by alfonsogarciacaro** [comment]
Closing as stale.
