### ISSUE TITLE
Attaching members to JS classes/function constructors

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#1717]
### Description

I'm trying to upgrade an fable 1.x to 2 and I've hit a bit of a problem.  I'm using the `childContextTypes` and `getChildContext` to pass a theme around React, this works in Fable 1 but the seems Fable 2 pull these functions out so they are no longer members/properties of the object/component.

### Repro code

_this also happens using web pack but this is easier to see:_

[Repl code](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWouuA2gDwAyAlg1nEgB8AXVwo6UACoALMAFswmemAAedAHJwFUALxQARAH0Z8sPpbioILNwBucBlaYhJAT3CUoALijAEAK10objkQbDoAETAAMzgAVyQJfWtQAFo6dzBKc1wM8ClZBSUGNQAKFJBKAEpdXCh6qAB6Ru4IWRsJACUwOABjOlJQ4AhIOnYTIuGSugAFZ0oAGl8AwXL5qrqGyjoHbl6oBTkERihe6W4kABNi1To3D1qGp9OcBzAAeQCoVgLTG7VNNodDpBE5QPcsgB+Pz+MD9KCiTb1Q7HLBQOjnSioADmYDo6HOV3+dFKNR0SOevVeDE+gR+E0UU1ugLAuhBYMqCJYYjxUDgQQZxNQZwu1yZaghlB5EgQAsKjOUZX0+g2ln2egQOLxBNFxNJQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

### Expected by react?

```
export const a = ThemeContext.childContextTypes();
export const b = new ThemeContext(props);
export const c = b.getChildContext();
```

### Actual

```
export const a = ThemeContext$$$get_childContextTypes();
export const b = ThemeContext$$$$002Ector$$Z721C83C5("");
export const c = ThemeContext$$getChildContext(b);
```

### Related information

* Fable Compiler 2.1.11
* Fable Repl v2.0.11

**Comment by alfonsogarciacaro** [comment]
Yes, Fable 2 now compiles type members as module members for better compatibility with tree shaking and optimization. However there are two cases where members are still attached to the prototype: overloads and interface implementations.

The solution here would be to either a) send a PR to fable-react so you can [add those methods to React.Component](https://github.com/fable-compiler/fable-react/blob/b89835014ae16caec51938ad8337010b36b13613/src/Fable.React/Fable.React.fs#L23) and the overload them, or b) create an interface with those methods and make your component implement them.

**Comment by davidtme** [comment]
@alfonsogarciacaro Thanks for the quick responses.  I could send over a PR for `getChildContext` but how would this work for `childContextTypes` which is a static member on the type?

**Comment by alfonsogarciacaro** [comment]
Ah! That's still possible though a bit hacky. You need to use the new `jsConstructor` helper:

```fsharp
open Fable.Core
open Fable.Core.JsInterop

type MyClass(v: int) =
    member __.Value = v

jsConstructor<MyClass>?foo <- fun x y ->
    x + y

[<Emit("MyClass.foo(5, 2)")>]
let test(): obj = jsNative

test() |> printfn "%O"
```

[Example in the REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWouudAnuFALJvpJyVKACgBuALigBLegEooAXlxRlUALZhVCRlAD6O1ADU4SAK5gFUESwBWlTBEp0sJgMZ1sAHh58BlAHwA-ABmwMBQHgC0UEEm0AAeUGxQEX5KKgkA1IksANoeAKKqknRCAETe-IKoIcBCAKwANFAATDKlMn4AurgodFAMjkIyEsAI1ha2AHJwdJIieKxgg3IAPn5QIFjSdEHQpQCkAPKluEA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMDSNMdNEwBEKKSkfjDWngxWSk4u8IgqkLBwQA&css=Q)
