### ISSUE TITLE
fable-splitter doesn't kill previous process when using --run

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1732]
### Description

I am working on a doc generator and I am auto-starting a server to serve the files.

So each time, I am doing a modification of the code `fable-splitter` run the generated JavaScript and start a new server. However, it doesn't kill the previous process.

So it doesn't free the ressource allocated to the previous process. For example, the port `8080` isn't free and my server can't start on that port.

### Repro code

Create a project which use `fable-splitter` and include `live-server` in the deps.

Run the following code using `yarn run fable-splitter -w --run`

```fs
module Test

module LiveServer =

    open Fable.Core

    type [<AllowNullLiteral>] LiveServer =
        abstract start: ?options : unit -> unit
        abstract shutdown: unit -> unit

    let [<Import("default","live-server")>] liveServer : LiveServer = jsNative

LiveServer.liveServer.start()
```

When making changes to the code, you should see in the console output: `http://0.0.0.0:8080 is already in use. Trying another port.`

### Expected and actual results

`fable-splitter` should kill the previous process

### Related information

* `fable-splitter` version: 2.1.5

**Comment by alfonsogarciacaro** [comment]
Hmm, [it should kill the previous process](https://github.com/fable-compiler/Fable/blob/d5a248c85608853259f8febdc1c33cd50a610890/src/fable-splitter/src/run.ts#L6-L8). Maybe your server is in a subprocess which doesn't get the kill signal? Can you try with "tree-kill" [as suggested here](https://stackoverflow.com/a/42545818) and see if it makes any difference?

**Comment by MangelMaxime** [comment]
Yes, I saw this line from fable-splitter but wasn't sure if this was killing or no the server.

I should also, mention that ATM I don't have a "clean exit" from the script. Like detect script exit and dispose of the allocated resource etc.

I should add a clean exit in the next days and will comment if this is solving the problem or if I need to use `tree-kill` as you suggested.

**Comment by alfonsogarciacaro** [comment]
In theory you shouldn't need to exit the script as fable-splitter should kill it before running it again... 🤔

**Comment by alfonsogarciacaro** [comment]
Closing in favor of #2212 which tracks a similar issue for Fable 3
