### ISSUE TITLE
After thoth json decode, decimal is converted to float but fable is still use decimal type

### ISSUE THREAD

**Issue by darting** [fable-compiler/Fable#1737]
After thoth json decode, decimal is converted to float but fable is still use decimal type, so I got `x.sub is not a function` error

![image](https://user-images.githubusercontent.com/4946661/52851701-bc227e80-3151-11e9-9685-d4f0a6735d03.png)

![image](https://user-images.githubusercontent.com/4946661/52851725-c80e4080-3151-11e9-8739-56db99fc5bf2.png)

**Comment by MangelMaxime** [comment]
[Here is the `decimal` decoder](https://github.com/MangelMaxime/Thoth/blob/master/src/Thoth.Json/Decode.fs#L239-L248):

```fs
    let decimal : Decoder<decimal> =
        fun path value ->
            if Helpers.isNumber value then
                Helpers.asFloat value |> decimal |> Ok
            elif Helpers.isString value then
                match System.Decimal.TryParse (Helpers.asString value) with
                | true, x -> Ok x
                | _ -> (path, BadPrimitive("a decimal", value)) |> Error
            else
                (path, BadPrimitive("a decimal", value)) |> Error
```

Can we see the `json` representation you are using ?

**Comment by darting** [comment]
Hi @MangelMaxime I am using `Decode.Auto.unsafeFromString`.
```json
{
  "value": {
    "balance": 8.0
  },
  "error": 0,
  "isError": false
}
```

types:
```f#
type ApiResult<'T> = 
    { Error : int
      Value : 'T 
      IsError : bool }

type Balance = 
  { Balance : decimal }
```

**Comment by MangelMaxime** [comment]
Which version of Thoth.Json are you using?

@alfonsogarciacaro I didn't move the issue to Thoth repo yet because I don't know yet if this is a Fable error or Thoth error.

**Comment by hotyes** [comment]
hi @MangelMaxime , the following packages is what I am using 

Fable.Core: Version="2.0.3"
Fable.Elmish.React: Version="2.1.0"
Fable.PowerPack: Version="3.0.0"
Fable.SimpleHttp: Version="1.0.0"
Fulma: Version="2.0.0-beta-001"
Fulma.Extensions.Wikiki.Switch: Version="1.0.0"
Thoth.Json: Version="2.5.0"
FSharp.Core: Version="4.6.2"

**Comment by darting** [comment]
hi @MangelMaxime , the following packages is what I am using 

Fable.Core: 2.0.3
Fable.Elmish.React: 2.1.0
Fable.PowerPack: 3.0.0
Fable.SimpleHttp: 1.0.0
Fulma: 2.0.0-beta-001
Fulma.Extensions.Wikiki.Switch: 1.0.0
Thoth.Json: 2.5.0
FSharp.Core: 4.6.2
fable-compiler:  2.1.12
fable-loader: 2.1.3

**Comment by alfonsogarciacaro** [comment]
I don't remember how it was in Thoth.Json 2. Maybe it's a Fable bug indeed, but in any case Thoth.Json 3 should work, though you need to add an extra coder for decimals: https://mangelmaxime.github.io/Thoth/json/v3.html#decoding-int64-decimal-or-bigint

**Comment by alfonsogarciacaro** [comment]
Closing as stale
