### ISSUE TITLE
bigint conversion from uint32 fails

### ISSUE THREAD

**Issue by chadunit** [fable-compiler/Fable#1745]
### Repro code

[Repl link here](https://fable.io/repl/#?code=A4JwlgdgLgZhAEAiApAQUfAFAIzAc0ingGUBPAZygFMBbAOgFUBJaANgBY6BZAQwA8AajwA2AVyoBKeAHpp8AO4B7EAGtyAKFCE4SNBhz5CJCtXrNoAZgBM3fkLGSZcmDzDCNQA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohVpU5fxEKyLDhA&css=Q)

```fsharp
printfn "%A" (bigint System.UInt64.MaxValue) // works
printfn "%A" (bigint System.UInt32.MaxValue) // fails
```

### Expected and actual results

Expected:

```
18446744073709551615
4294967295
```

Actual:

```
18446744073709551615
Uncaught TypeError: Cannot read property 'bound' of undefined
    at BigNatModule$$$degree (n.js:388)
    at BigNatModule$$$toString (n.js:1302)
    at BigInt_BigInteger.BigInteger.toString (z.js:379)
    at String (<anonymous>)
    at str2.replace (String.js:133)
    at String.replace (<anonymous>)
    at formatOnce (String.js:117)
    at args (String.js:157)
    at blob:https://fable.io/781bf87c-ca5b-4312-b941-d86cc4e73119:73
```

### Related information

* Fable version: 2.1.12 (and REPL)
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hmm, sees to happen only with System.UInt32.MaxValue. This works:

```fsharp
printfn "%A" (bigint 999999999u)
```

**Comment by chadunit** [comment]
Anything higher than signed int range I believe e.g. this also errors `printfn "%A" (bigint 4294000000u)`
