### ISSUE TITLE
Async.Sleep doesn't respect cancellation

### ISSUE THREAD

**Issue by SirUppyPancakes** [fable-compiler/Fable#1749]
### Description

Fable's `Async.Sleep` implementation doesn't respect cancellation.

### Repro code

```
module Test

open System
open System.Threading

let tokenSource = new CancellationTokenSource()

Async.StartImmediate(async {
    try
        for i in [1..20] do
            printf "%i before" i
            do! Async.Sleep 5000
            printfn "%i after" i
    finally
        printfn "done"
}, tokenSource.Token)

tokenSource.CancelAfter 6000
```

### Expected and actual results

It is expected that when an `async` computation expression's corresponding token (passed to `StartImmediate`) is cancelled, that `Async.Sleep` should cancel immediately.

If you paste the code into the Fable REPL, you'll observe:
`1 before`
after 5 seconds...
`1 after`
`2 before`
after 5 seconds...
`done`

while if you paste it into the Visual Studio F# REPL, you'll observe:
`1 before`
after 5 seconds...
`1 after`
`2 before`
after 1 second...
`done`

Ultimately not a huge problem, but definitely a meaningful difference in behavior between .NET and Fable.

Not sure if it helps, but this behavior was actually present in an older version of F# (but was changed in >=3.0) as described here:
https://stackoverflow.com/questions/9041491/is-there-any-reason-why-async-sleep-can-not-be-canceled-immediately

### Related information

* Fable version: 2.1.12
* Operating system: Windows 10 x64

**Comment by alfonsogarciacaro** [comment]
This is going to be tricky because we implement `Async.Sleep` using JS `setTimeout` and afaik this cannot be cancelled: https://github.com/fable-compiler/Fable/blob/16ab2eed8b213836a9fd1e3253c1c4d633061e74/src/fable-library/Async.ts#L105-L111

We could check the token before calling `setTimeout` but this wouldn't match .NET behaviour either.

**Comment by SirUppyPancakes** [comment]
Can't you use `clearTimeout` as described here (https://www.w3schools.com/jsref/met_win_settimeout.asp)?

Just skimming over the Fable Async code though, looks like you'll need a way to handle cancellation as an event (something `CancellationToken` does not support out of the box). But, since you don't use a full type, just a lightweight interface, you should be able to add it without changing too much:

(in `AsyncBuilder.ts`)
```
export interface CancellationToken {
  isCancelled: boolean;
  onCancel: (() => void) []; // add array of handlers
}
```

`cancel` function (in `Async.ts`):
```
export function cancel(token: CancellationToken) {
  token.isCancelled = true;
  
  // invoke any handlers...
  for (let handler of token.onCancel)
    handler();
}
```

which should allow you to catch it as an event in `sleep`:

```
 export function sleep(millisecondsDueTime: number) { 
   return protectedCont((ctx: IAsyncContext<void>) => { 
     // store id
     let id = setTimeout(() => ctx.cancelToken.isCancelled 
       ? ctx.onCancel(new OperationCanceledError()) 
       : ctx.onSuccess(void 0), millisecondsDueTime); 
     });

     ctx.cancelToken.onCancel.push(() => {
       clearTimeout(id);
       ctx.onCancel(new OperationCanceledError());
     });
 }
```

**Comment by alfonsogarciacaro** [comment]
Ah, you're right. Didn't think of that, thanks for the suggestion. I've implemented it, not sure if there are other places where it would make sense too (can promises be cancelled?). Seems to work but it's tricky to add a unit test for this, please let me know if you've another idea :)

**Comment by SirUppyPancakes** [comment]
As far as I know, F# is one of the few rare cases that implements any sort of auto-cancel mechanism (since it's very opinionated how it should happen), though I think it's probably the rigid nature of computation expressions that make it work so well. JS Promises on the other hand are like .NET Tasks (and other Async primitives in other languages) and leave it up to the user to do cooperative canceling via some sort of passed token or flag, so I think we're safe on that end :)
I'll continue to post the various discrepancies I come across along the way 🚀
