### ISSUE TITLE
let rec inline breaks compiler

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1750]
I was in process to transform my react native app from fable 1.x to 2.x and had a `let rec inline` function.
This breaks the compiler without any warning or error. fable-splitter just returns with exit code 0 and it's super hard to find the reason.

**Comment by ncave** [comment]
@forki Hasn't this been already [discussed](https://github.com/Microsoft/visualfsharp/issues/3634)?

**Comment by forki** [comment]
yes I don't really need let rec inline (it was only because fable needs generic functions to be inlined) 
It's just super hard to find as a user. so yes better error would be good
