### ISSUE TITLE
Fable splitter doesn't put /big.js in output

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1751]
I'm trying to convert my React Native project from fable 1.x to fable 2.x but fable-splitter doesn't put big.js into my out folder. Any ideas what I can try?

![image](https://user-images.githubusercontent.com/57396/53158940-0d54c700-35c5-11e9-9aac-f4a61d51b181.png)

**Comment by forki** [comment]
so that big.js file is correctly copied into `.fable` folder as part of `fable-library.2.1.12` but it's not put into `out`

**Comment by forki** [comment]
@alfonsogarciacaro I wonder if that's related to TypeScript being involved?

**Comment by forki** [comment]
BigInt folder isn't copied as well. So I assume it's only copying the top-level?

**Comment by alfonsogarciacaro** [comment]
fable-splitter is used to compile the tests and they include decimal tests (which require the big.js dependency). Do you have a small repro of your problem?

**Comment by forki** [comment]
Mhm actually no. Only my work project.

Alfonso Garcia-Caro <notifications@github.com> schrieb am Fr., 22. Feb.
2019, 16:56:

**Comment by forki** [comment]
I think I found a probably related bug:

1) clone https://github.com/SAFE-Stack/SAFE-Nightwatch
2) checkout fable2 branch
3) run `build.cmd debug`

now look into `out` folder. I'd expect `BigInt` would be copied into `fable-library.2.2.0-beta-012` folder. But it's directly in `out`. Something is weird here.

**Comment by alfonsogarciacaro** [comment]
fable-splitter flattens the folder structure, this is done mainly to avoid issues with folders coming from an external directory. If the import paths within the files are correct (which should be the case) this is not a problem. (However @ncave has "fixed" this for fable-compiler-js, maybe it could be fixed here too.)

I can see `out/lib/big.js` after running fable-splitter so it seems to work. I cannot run the app though because I don't have Android SDK installed in my machine.

> Also, please note big.js is not about BigInts but Decimal.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/53424152-f6f2a500-39e2-11e9-8350-6cdcadde46ad.png)

I mean the BigInt folder - and it's not flattened at all. it's just that the subfolders are now outside of the original folder (and in the work project they aren't copied at all)

**Comment by ncave** [comment]
@forki Yes, that's what @alfonsogarciacaro means by flattened folder structure - just one level deep, so all the subfolders are brought at top level. That's how the splitter was always working.

If you want to experiment with a different folder structure, the `fable-compiler-js` tries to strike a different balance and retain the original folder structure to the extent possible (within reason, as it has to move any external dependencies into the output somehow, so not possible if we don't want to create full absolute paths under the output folder, which would work but it will be too deep IMO).

**Comment by forki** [comment]
Tbh that folder structure is OK. The problem is that it does not copy it at
all in my real app. I guess I need to turn that one into a repro by
removing all product stuff.

ncave <notifications@github.com> schrieb am Di., 26. Feb. 2019, 17:26:

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/53471932-9dcc5500-3a66-11e9-99a7-aa8b298fe78e.png)

getting some warnings about the same lib. is that related?

**Comment by forki** [comment]
I found something in the log output. In the SAFE-Nightwatch it looks ok:

![image](https://user-images.githubusercontent.com/57396/53474677-0834c380-3a6e-11e9-9bb7-66f5dec92048.png)

In my own project it forgets about the requires:

![image](https://user-images.githubusercontent.com/57396/53474730-28fd1900-3a6e-11e9-9a37-755918631cf9.png)

**Comment by forki** [comment]
Ok. here is a repro:

[msu.Reading.zip](https://github.com/fable-compiler/Fable/files/2909230/msu.Reading.zip)

1) extract the zip
2) `yarn install`
3) `yarn run fable-splitter -c splitter.config.js --define DEBUG`

![image](https://user-images.githubusercontent.com/57396/53476199-15ec4800-3a72-11e9-92f2-ae256d00894f.png)

As you can see it compiles the Decimal.js - which itself has that gnarly require. But the `big.js` is not put into `out` folder

**Comment by forki** [comment]
@alfonsogarciacaro I updated to 2.2.0-beta-014 in my production app and it seems to be fixed. Is there something that might have caused that?

**Comment by alfonsogarciacaro** [comment]
In principle I'd say no, unless this commit had something to with adding an import to Decimal.ts: https://github.com/fable-compiler/Fable/commit/53fcc7a1be069f3b41b653fd2ce0b1ae06864f03

In any case, if it's fixed let's call it a day :)

**Comment by forki** [comment]
;-)

**Comment by forki** [comment]
ok with 2.2.0-beta-016 I see that issue again

**Comment by alfonsogarciacaro** [comment]
Apparently the problem was the babel.config.js file. Babel was reading it when parsing JS files so the AST was different from expected, and the import paths couldn't be adjusted. Can you please try with **fable-splitter** 2.1.6?

**Comment by forki** [comment]
cool, seems to work! thanks a lot!
