### ISSUE TITLE
You may need an appropriate loader to handle this file type (fable-library.2.1.12)

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#1756]
### Description

I've created a Fable library and trying to compile it with the `fable2-sample/minimal` app I get:

```
Module parse failed: Unexpected token (11:18)
You may need an appropriate loader to handle this file type.
| import { fromSeconds } from "../.fable/fable-library.2.1.12/TimeSpan";
```
and 
```
Module parse failed: Unexpected token (5:18)
You may need an appropriate loader to handle this file type.
| import { toText, printf, format, isNullOrEmpty } from "../fable-library.2.1.12/String";
| import { head, fold } from "../fable-library.2.1.12/Seq";
> import * as  from "";
| import { ofArray } from "../fable-library.2.1.12/List";
| import { promise } from "[snip]/fable2-sample/minimal/.fable/Fable.Promise.1.0.0/PromiseImpl.fs";
 @ ./src/App.fs 5:0-277 35:21-59 35:83-131
```

The app w/o the library compiles just fine. What am I missing?

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`:
2.1.12

* Operating system
Windows

**Comment by alfonsogarciacaro** [comment]
Strange... what do you mean by `compile it with the fable2-sample/minimal app`? Would it be possible to post a repro?

**Comment by et1975** [comment]
Found the problem, the error was completely misleading, but my lib had a ts2fable-generated binding with `[<Import("*","")>]` that I didn't notice.
