### ISSUE TITLE
`this` null check in constructors conflicts with some environments (React Native)

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1757]
I'm porting my fable 1.x React Native App to Fable 2.x and I'm having problems with Array.groupBy .

        let mappedCityGroups = 
            requests
            |> Array.map (fun x ->
                match x with 
                | MeterReadingRequest x -> x.GetCity()
                | MeterChangeRequest x -> x.GetCity())

        printfn "mapped"

        let cityGroups = 
            requests
            |> Array.groupBy (fun x ->
                match x with 
                | MeterReadingRequest x -> x.GetCity()
                | MeterChangeRequest x -> x.GetCity())

the mapping part works, but during groupby it fails with "Cannot read property 'MoveNext' of undefined"

**Comment by forki** [comment]
ok somthing really weird is happening.

    let ys = [| 1;2;3 |] |> Array.groupBy (fun x -> x = 2)

^^ even this fails.

**Comment by forki** [comment]
![image](https://user-images.githubusercontent.com/57396/53322217-08e92080-38db-11e9-9e68-96c70320a61a.png)

btw: why is fable-splitter generating minified code?

**Comment by forki** [comment]
ok I was able to repro this thing in SAFE-Nightwatch:

![image](https://user-images.githubusercontent.com/57396/53322620-37b3c680-38dc-11e9-8cd7-1c02beffdcfa.png)

compiled to:

![image](https://user-images.githubusercontent.com/57396/53322685-6631a180-38dc-11e9-93fb-3c06710da460.png)


repro: https://github.com/SAFE-Stack/SAFE-Nightwatch/pull/67 (run `build.cmd debug`)

**Comment by forki** [comment]
a bit of the stacktrace:

![screenshot_20190225-090834](https://user-images.githubusercontent.com/57396/53322900-0a1b4d00-38dd-11e9-86f9-042b87fe3c9d.jpeg)

which points to:

![image](https://user-images.githubusercontent.com/57396/53322958-2cad6600-38dd-11e9-9ff6-d205c539dce4.png)

![image](https://user-images.githubusercontent.com/57396/53323159-a6455400-38dd-11e9-95b2-55b8586ac193.png)

**Comment by forki** [comment]
so it fails at:

![image](https://user-images.githubusercontent.com/57396/53325067-b3187680-38e2-11e9-8df9-3e6fce136a93.png)


en is null for some reason

**Comment by forki** [comment]
I found an "fix":

![image](https://user-images.githubusercontent.com/57396/53325627-0939e980-38e4-11e9-936e-a08fb796f965.png)

this change makes the groupBy work. I have no idea what's it doing tbh!

**Comment by Zaid-Ajaj** [comment]
I think array has to be converted to `seq<_>` first for this to work. Repl example:

```fs
let x = [| 1 .. 10 |]
let y = Array.groupBy (fun x -> x % 2 = 0) x
```
compiles to 
```js
import { groupBy, ofSeq } from "fable-library/Array";
import { rangeNumber } from "fable-library/Seq";
import { structuralHash } from "fable-library/Util";
export const x = ofSeq(rangeNumber(1, 1, 10), Int32Array);
export const y = groupBy(function (x$$1) {
  return x$$1 % 2 === 0;
}, x, Int32Array, {
  Equals($x$$1, $y$$2) {
    return $x$$1 === $y$$2;
  },

  GetHashCode: structuralHash
});
```

See the `ofSeq` being called on the array, for some reason this function is not called in your compiled code before invoking `groupBy`

**Comment by alfonsogarciacaro** [comment]
Maybe #1754 has fixed this too, I will push a new 2.2 beta version (remember you need to install them with "next" tag: npm i fable-compiler@next) so you can try it out.

**Comment by forki** [comment]
@alfonsogarciacaro please take a look at the commented code at https://user-images.githubusercontent.com/57396/53325627-0939e980-38e4-11e9-936e-a08fb796f965.png

It looks weird doesn't it?

**Comment by alfonsogarciacaro** [comment]
It does. Not sure if RN fails when you use `this` in the wrong place. If that's the issue we have a much bigger problem, because Fable 2 uses this pattern to distinguish if the constructor is being called directly or from a child type. But in that case I assume you should have seen the problem much earlier 🤔

**Comment by forki** [comment]
I don't think RN is special. but `this` is not null in my case and therefor it doesn't do the normal ctor

**Comment by forki** [comment]
`this` is a `DedicatedWorkerGlobalScope`. that can't be right!?

![image](https://user-images.githubusercontent.com/57396/53334907-5cb73200-38fa-11e9-88dd-b6945b5c97bf.png)

**Comment by forki** [comment]
repro can even be simpler:

    let m = Map.empty 
    let m2 = Map.add 1 2 m  // fails already

**Comment by forki** [comment]
m is undefined!

**Comment by forki** [comment]
So it looks like this pointer is always pointing to DedicatedWorkerGlobalScope and therefore this subtype check is invalid. Any ideas how this could happen? What can I try to debug? I'm completely lost here.

**Comment by alfonsogarciacaro** [comment]
@forki I've released fable-compiler@2.2.0-beta-012 that replaces the `this` null check with an `instanceof` check. Can you please give it a try?

**Comment by forki** [comment]
that fixes it! thanks

**Comment by forki** [comment]
thanks!!!
