### ISSUE TITLE
Missing files in the source map

### ISSUE THREAD

**Issue by psowinski** [fable-compiler/Fable#1765]
### Description

After bundling with webpack source map contains only some *.fs files
I have created simple project with 6 identical files, but only 2 of them are in the source map

### Code
Simple reproduction (npm install & npm run build)
[testsourcemap.zip](https://github.com/fable-compiler/Fable/files/2914256/testsourcemap.zip)
see ./dist/bundle.js.map

### Expected results

All project files should be contained in the source map

### Related information

* Fable version: 2.1.12
* OS: Win10 & Ubuntu 18.04

**Comment by alfonsogarciacaro** [comment]
Interesting, I can reproduce with your test project but I've never seen this in any other project. TBH, I've no idea why this is happening, I assume you have seen this too in a "normal" project?

**Comment by psowinski** [comment]
Yes, it's from a real project. I've tried to simplify webpack configuration in case if sth is messing up, but without success

module.exports = {
 mode: 'none',
 devtool: "source-map",
  entry: __dirname + '/test.fsproj',
  output: { filename: 'bundle.js' },
  module: { rules: [ 
{ test: /\.fs(x|proj)?$/, use: { loader: 'fable-loader' } },
{ test: /\.js$/, exclude: /node_modules/, use: { loader: 'babel-loader' } } ]  } }

**Comment by alfonsogarciacaro** [comment]
Yes, I tried to change the Web pack config in your test project too but didn't make any difference. Strange... 🤔

**Comment by alfonsogarciacaro** [comment]
Source maps have changed in Fable 3 so not sure if this still an issue (I haven't seen anything like nor got any report) so I'm closing for now. Please reopen if you still see the issue in Fable 3.
