### ISSUE TITLE
Try Fable site?

### ISSUE THREAD

**Issue by fdcastel** [fable-compiler/Fable#177]
What happened with **Try Fable** site? (some problem with hosting? bandwitdth? security considerations?)

What would be needed to bring it back again?

It goes without saying it is an excellent tool for newbies to play around. Together with the latest changes (BTW: @tpetricek @Krzysztof-Cieslak Fantastic work with the new site and samples, guys! :+1:) it would be another nice addition to improve the visibility of the project (with a little mention in F# Weekly, of course :wink: )

**Comment by alfonsogarciacaro** [comment]
The virtual machine I was hosting the web service on went down and I haven't had the time yet to fix it 😞 But I'm planning to do it shortly. I have to change a bit the bootstrapper code to allow several clients: console (current), web service with Suave and embedded (dll), so it's easier to update/restart the web service when need. But that shouldn't be too difficult so expect the online REPL to be back soon (hopefully with a Run Your Code button too) 😸

**Comment by tpetricek** [comment]
I would love to be able to use Fable as a library from F# as a function `F# source code -> JSON for Babel`. That would then make the Try Fable site quite easy as you could translate Babel to JS on the client-side (and it would also allow me to do Fable version of www.fun3d.net, which would be very cool!)

**Comment by fdcastel** [comment]
@alfonsogarciacaro What infrastructure are you using? Docker? Azure? AWS? 

Any chance you could publish the code you already have? 

Of course, I'm not talking about publishing deployment keys, passwords, etc. Just the bare minimum for anyone to run Try Fable on your own machine. Something like what @tpetricek did with the new docs (`build BrowseDocs`). 

You know... The community could lend a hand ;)

**Comment by alfonsogarciacaro** [comment]
It's actually in the `online-repl` branch (have a look at the `docker` folder) but I wouldn't care too much about it. I was just experimenting with Docker at the time but a virtual machine is actually overkill for this. I put the server directly in the javascript bootstrapper, which makes updating difficult.

The way we're planning to do now is different. As discussed with @tpetricek, we'll likely have Babel in the browser and let Fable send directly the AST in JSON format (probably removing the source location data to make it lighter) from the server (hopefully a Suave one) hosted in a web app in Azure or Heroku.

Another thing I want to change is that currently when Fable receives a code string it writes it to a temp file before the compilation. I did this following the FSharp.Compiler.Services tutorial but I think it should be possible to do the compilation in memory instead.

**Comment by alfonsogarciacaro** [comment]
Still a WIP but I've uploaded a Suave client to `fable-clients` branch. If you want to give it a try, you can test it with the following commands:

```
./build.sh FableSuave
mono build/fable/Fable.Client.Suave.exe
```

Then you can send an HTTP POST to `http://0.0.0.0:8083/fable/` with the code you want to compile. You can use `Fable.Core.dll` but any other reference won't work. Also you won't receive the JS code directly but a Babel-compatible AST that must be transformed as you can see [here](#r "../import/core/Fable.Core.dll").

Please tell me if you have any questions. Have fun!

**Comment by WilliamOckham** [comment]
Have you considered hyperdev.com for this?

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
