### ISSUE TITLE
Fable Splitter in watch mode doesn't pick up VS 2017 changes

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#1771]
### Description

I have a simple app using react native and when saving a file in VS 2017 the changes are not picked up.  Changes in VS Code work fine so it could be down to the way VS 2017 saves file (I think it creates a temp file then renames it or some other odd way?)

![save](https://user-images.githubusercontent.com/1804141/53648139-12ee8480-3c37-11e9-98c0-ac780e25a42f.gif)

### Related information

* fable-splitter 2.1.5
* fable-compiler 2.2.0-beta-015
* Windows 10

**Comment by alfonsogarciacaro** [comment]
This answer seems to suggest that we need indeed for rename events to detect when a file is saved in VS: https://stackoverflow.com/a/20130136

**Comment by alfonsogarciacaro** [comment]
I just tried with Fable 3.2.9 and Visual Studio 2019 and the watcher properly reacts to file saves :+1:
