### ISSUE TITLE
npm test fails silently if dotnet sdk in global.json is not installed on the user's machine

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1774]
### Description 

`npm test` fails silently when trying to run the tests locally if dotnet sdk in global.json is not installed on the user machine. For example, current required SDK version is `2.1.403`, if you don't have it installed next to the newer versions then the test simply stops with `fable-splitter` not compiling the project when looking for the `dotnet binary` , the build target then fails with trying to run `mocha` against the test files because they were not generated 
 
```
$ npm test

> @ test C:\projects\Fable
> fable build.fsx --run test

--------------------------------------------
InteractiveChecker created in 1462 ms
Project: build.fsx, FCS time: 1573 ms
--------------------------------------------
File: src/fable-publish-utils/PublishUtils.fs, Fable time: 1241 ms
File: build.fsx, Fable time: 381 ms
> node bin/build.js test
> npx fable-splitter -c tests\splitter.config.js
fable-splitter 2.1.2
fable: Compilation started at 12:34:39
fable-compiler 2.1.10
dotnet binary: C:\projects\Fable\src\Fable.Cli
> npx mocha build/tests --reporter dot -t 10000
Warning: Could not find any test files matching pattern: build/tests
No test files found
child_process.js:636
    throw err;
    ^

Error: Command failed: npx mocha build/tests --reporter dot -t 10000
    at checkExecSyncError (child_process.js:596:11)
    at Object.execSync (child_process.js:633:13)
    at run (C:\projects\Fable\bin\src\fable-publish-utils\PublishUtils.js:386:26)
    at test (C:\projects\Fable\bin\build.js:148:25)
    at C:\projects\Fable\bin\build.js:332:9
    at Object.<anonymous> (C:\projects\Fable\bin\build.js:397:3)
    at Module._compile (internal/modules/cjs/loader.js:678:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:689:10)
    at Module.load (internal/modules/cjs/loader.js:589:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:528:12)
npm ERR! Test failed.  See above for more details.
```

### Expected Behaviour 

The `test` build target should not execute `npx mocha build/tests --reporter dot -t 10000` unless the test files in `build/tests` were actually generated. If the files are missing, tell the user to check for the existence of the correct dotnet SDK on the user's local machine

### Workaround

Change the SDK in global.json to match the installed version on the local machine

### System Info: 

Windows 10 
`dotnet --version` -> 2.2.104
Fable repository, master branch

**Comment by MangelMaxime** [comment]
> If the files are missing, ...

I don't think the check should be if the files are missing. In theory, if Fable is using `dotnet` to launch the compilation it should capture the error at this moment.

The error should be something like:

```
A compatible SDK version for global.json version: [0.0.500] from [/Users/maximemangel/Workspaces/Github/fulma/Fulma.Extensions.Wikiki.Switch/global.json] was not found
Did you mean to run dotnet SDK commands? Please install dotnet SDK from:
  https://go.microsoft.com/fwlink/?LinkID=798306&clcid=0x409
```

Because the problem is `dotnet` will not run if a correct version of the SDK is not found. And so the files are not generated but this fact is only a consequence.

**Comment by MangelMaxime** [comment]
And the result of run `dotnet` with no valid SDK version should generate a non-zero exit code. So it's should be easy to detect.

**Comment by alfonsogarciacaro** [comment]
I think this is already fixed, but please reopen if it's still an issue.
