### ISSUE TITLE
Fable.Core v3.0.0-beta-002 issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#1775]
`Fable.Core.JS.Array.isArray` and `Fable.Core.JS.Number.isNaN` are missing, so tests are breaking.

P.S. I know things moved around, just opening an issue to track when tests are fixed, as changes will have to be made in Thoth and I'm not sure if they need to be made in Thoth's project first before copying here, or is it ok to directly fix it here.

**Comment by ncave** [comment]
On a related note, IMO Fable tests should be referencing Fable.Core by project reference, in order to always use latest and have a chance to catch those issues earlier.

**Comment by MangelMaxime** [comment]
I am not sure to understand the point about Thoth :)

If the new release is just a rename of `Fable.Import.JS.*`  to `Fable.Core.JS.*` Thoth should be easy to update. 

For info, we spoke in private with Alfonso and I asked 2 days before doing the update in Thoth because I am splitting the repo into several repositories and so it's hard for me to accept a contribution for now.

**Comment by ncave** [comment]
@MangelMaxime Yes, it's trivial to add those two missing methods in Fable.Core and adapt to the namespace change. This is just an issue to track the work.

**Comment by MangelMaxime** [comment]
@ncave Ok :)

**Comment by alfonsogarciacaro** [comment]
> On a related note, IMO Fable tests should be referencing Fable.Core by project reference, in order to always use latest and have a chance to catch those issues earlier.

You're right @ncave. I think it's done this way to prevent Fable from trying to compile Fable source files and make sure everything works just with the assembly reference, but I guess we can make an exception for Fable.Core.fsproj :+1:

**Comment by ncave** [comment]
@alfonsogarciacaro Alright, I'll add a PR shortly.

**Comment by alfonsogarciacaro** [comment]
Sorry, @ncave, didn't see your latest message and already did it 😅 f34cd5a70fd9424741e254bab8401c57fe439e23

I tried to fix fable-compiler-js but I'm not sure if I did it right, let's see what CI says...

**Comment by ncave** [comment]
Closing as fixed.
