### ISSUE TITLE
System.Uri support

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#1777]
### Description

Compiler raises no issues but the `Uri` object does not implement the useful stuff:
- `string <| Uri("http://localhost")`: `[object Object]`
- `Uri("http://localhost").Authority`: `error FABLE: Cannot resolve System.Uri.get_Authority`

### Expected and actual results

Would be nice if the `Uri` was implemented, but failing that - errored out early.

### Related information

* `yarn info fable-compiler version`:
>yarn info v1.13.0
>2.1.12

* Operating system
Linux (Elementary OS)

**Comment by alfonsogarciacaro** [comment]
Well, in a sense the compiler message is right, `Uri` is partially implemented so you get the message error when you try to use a not supported API :)

The partial support for URIs came from a contribution #1572 Supporting more APIs should come this way too.

**Comment by jackfoxy** [comment]
A few properties and methods I stumbled on that might be useful to implement.
System.Uri.TryCreate
System.Uri.get_IsUnc
System.Uri.get_OriginalString

**Comment by alfonsogarciacaro** [comment]
Closing for now, but if there's still interest for this, it'd be great to get a follow-up PR for #1572
