### ISSUE TITLE
Q: Is something like `Option.orUndefined` available

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#1778]
### Description

I'm dealing with code-gen'ed TS that implements DTOs serialisation and blindly does this:
`data["someField"] = this.someField;` 

on the F# side I have `Option` for `someField`, but because it gets converted to `null` I get JSON like this:
`{"someField": null}` instead of omitting it, which causes problems on the receiving end.

I can write `Option->undefined` converter, but wondering if there's one already or maybe it would be a good idea to offer that in Fable core.

**Comment by MangelMaxime** [comment]
@et1975 How are you generating the JSON? Because if you use `Thoth.Json` you could write the encoder and choose to send the property only if it has a value.

We could also, had a setting in order to filter `None` properties from the output by default.

**Comment by et1975** [comment]
No, the JSON is produced by the ts library, all I can do is supply
undefined.

**Comment by alfonsogarciacaro** [comment]
Fable does all null comparisons with JS non-strict equality checking, which covers both null and undefined (in JS `undefined == null` is true). `Option.ofObj` with return None if you feed `undefined` to it.

**Comment by et1975** [comment]
Right, but in the situation I'm describing the flow is F#->JS, not JS->F#.

**Comment by et1975** [comment]
I guess that answers it.
