### ISSUE TITLE
CancellationToken Register is missing

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1785]
![grafik](https://user-images.githubusercontent.com/4236651/54224183-4bc11000-44f9-11e9-8f4c-c497bfeb6d37.png)

https://fable.io/repl/#?code=LYewJgrgNgpgBAUSsAlgZwBYDoDKLgAOsAkgHYEQAuAUNSATKXAGICGARrFgMIgBOMLACk0ZSjD706DJm06CAEjCgM+aLACUYrAMY16jFhy5KVE9Vt2UsABUkE00w0lSYnTF+myW9tA7ONBXgF3I3ksYkJ+fRkwk2VVC21ffzjFBPNNZOs7ekdUuS5gwRExCSkCwIiovmsAIUkAdzQJP1icAE80cWAsABUMAVYwFFIAc1pYSjg9NDgAXjhSGEa4blZSHWUoVkoUEFI+kABrRhwQCD4tgAoASlpZ-pPGLLH0cT5rgDMIJju4AC0AD44AQ+KNKF8mAAidabbYwMDQ25wAA+IJQY1I-BgD0o6jhWygdyAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA

**Comment by MangelMaxime** [comment]
It's indeed marked as not implemented for the Mailbox processor [docs](https://fable.io/docs/compatibility.html) I don't know if this is a limitation of JavaScript or just something we don't want to include for some reason.

**Comment by alfonsogarciacaro** [comment]
`CancellationToken` is not supported for Mailbox but it's actually supported for async workflows :) I added a replacement for `Register`. Hopefully works :+1:
