### ISSUE TITLE
Debug Fable.Cli

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1787]
Pre fable 2.1, loader and splitter were communicating through a TCP server, @alfonsogarciacaro replaced that with stdin/stdout. 

This no longer makes it possible to run Fable.Cli in an IDE.
F.ex starting the Fable.Cli project with arguments `fable-splitter --args "-c ../fsx-sample/splitter.config.js"`.

**Comment by alfonsogarciacaro** [comment]
Hi @nojaf! Sorry, but you're not including the steps to reproduce. I've tried cloning your fork, checking out the branch and trying to build the sample (both on mac and Windows) but I'm getting errors different from the one you pasted above.

**Comment by nojaf** [comment]
Hey @alfonsogarciacaro. Sorry for not being so thorough.

You should run `node install.js` in the `samples/react-todomvc-fsx` folder.
That should install `paket` and create the correct `load` file.

Then running `webpack` should create the bundle using the local Fable.Cli.
My problem occurs there.

**Comment by nojaf** [comment]
After reading the last comment in #1751, I changed the fable-splitter version to 2.1.6 and Array and List are included now.

However, with that version, I cannot debug anymore, as 2.1 splitter and loader are communicating with stdin/stdout. Could we perhaps restore that functionality?

**Comment by alfonsogarciacaro** [comment]
In theory it should be possible to attach a debugger to the dotnet process after it has started but it's true I didn't manage to do it when I tried.

Anyways, we should probably add back the option to fable-splitter and/or fable-loader to communicate with Fable through the TCP server so we can make the dotnet process call the node as it was done before.

**Comment by nojaf** [comment]
If you could give me some pointers on how to do that I might give it a try.

**Comment by alfonsogarciacaro** [comment]
This commit is a bit big, sorry, but you can see how the `fable-compiler/src/index.ts` file was edited to replace the TCP functionality with the stdin/out compiler: https://github.com/fable-compiler/Fable/commit/8660298ef062dee05592618f513e77ee93f5cdc3#diff-9dea49eb7de5fbb4a126dc2412265f7f

I assume it should work just by bringing back the TCP capabilities and activate them with an option or an environmental variable (like `FABLE_SERVER_PORT`). The Fable commands to start the TCP server are still in the dotnet part, so you shouldn't need to touch anything there.

**Comment by alfonsogarciacaro** [comment]
It's again possible to start the TCP server as before (passing the "start" command). In your fable-splitter/loader config, just pass the "port" option so the client knows it must connect to the server instead of spawning a process. Example: https://github.com/fable-compiler/Fable/blob/ac99c2e862c1a679c6393b85bdb13f5294bf61c3/src/quicktest/splitter.config.js#L7
