### ISSUE TITLE
MailboxProcessor.TryReceive is missing

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1789]
```f#
let mbp = MailboxProcessor.Start(fun inbox-> 

    let rec messageLoop() = async {

        let! firstMsg = inbox.Receive()
        let! secondMsg = inbox.TryReceive(0)

        // ...

        return! messageLoop()  
    }

    messageLoop() 
)

mbp.Post(1)
mbp.Post(2)
mbp.Post(3)
```

![grafik](https://user-images.githubusercontent.com/4236651/54359066-21d72d00-4662-11e9-949e-33c97fb59d18.png)

(repl: https://fable.io/repl/#?code=DYUwLgBAtgRgDhAvBAsgQwJbBgewB4AKATjgMYgDOFORAdAMphpFgAUAZgK4B2EG3uPAFoAfBABQ4iNIihIREKWiUKaAOYgAMjhxxWASiQQ0FAJ7clAb0kzbs8AEII7DEQpgUFNUf6DaAJUUQDAA3EAMpO2k5JwpFHG4AE09vZF98WgAVIlNA8lDwgAZ9GyiIAHpyiFoa0qiFME4ibicoFXUtHT1DCVsAXzrlKg7tXQMJEvFYOFoCHHdWAEYS6dn5tgAmFfg1hYBmfSA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwKKQEMwCUVgYBLGbJXAMXICNmUBqFAJSRQ05AE4wAzsAD0DJi3w1gmJDHLoYMBAFokARwCu9AG4BeAOQBhCADsYSO9oAqiJOZRRb9uxfsAPGGlibABuDxFRCVVTAxgAM20ADnNqWhU1FBtyFVMAImN6JAB3BAhxXI8vBxg8ovowGDRTMCQCqCRtOoa0ABoUehtGenJsbQkoEaRTAEZc1OBx0XoEGBQJUSg8gH0tgAkAeQBlJx3pbHoOCWlRClgAOgRRCDADWHpbO8wBu4ArCTmZItljB5kCVmsNts9kcTlszhcrjdyLBtJBMA8ni83h8vjZfv9cICoEsVqDicCPE8JBIyvQAOYDCGbXIYLQSABc0mkBhsCAA1nS7p5MNJHhAdPBkBIAALTACsdwAbKKnhLXBJPt8-gDpGCQYpaHrKRBqbSGTYmXlWQgOVyefzBcLrkIIpJZXcAMx3abczBgaSCYRiSSavHawm68mkwhBChUQgcZ5weZgEz9MB5JDYL4SNDacgIBA61PGMkk1brZkcHlgZj4nV60jSRNgZMx4K4IA&css=Q
)

**Comment by 0x53A** [comment]
Also receive does not respect the timeout:

https://github.com/fable-compiler/Fable/blob/291f1df68e84afa693e897ad6db3ecc2bd13f95d/src/fable-library/MailboxProcessor.ts#L79-L87

[this repl](https://fable.io/repl/#?code=FDA2FMBcAIFsCMAO0C80CyBDAlqeB7ADwAUAnfAY3AGdr9SA6AZUk1MgAoAzAVwDto2PgUIBaAHzQQ0GdAgxIpAJ4AlcFWwA3cNEKpomakr4VoAb2Cyr0RUsvWH8gIRxqAc31CRDNRu0dCAEp7BytSKB5SASZ8WB1YdxDrAHdsSAALJIcAfWgJLNDwyEiBADl8PnAkgF9pWXlocNM42kw3cAAZfHxEDkD9Q2NTCwKZZ2gubFJqSHR3T2EiH3VwLXA+0bkoF2p1CoATOY80W19V-wBGYM3EUiFILgEAIknp2ZpqNp1samgAUmwABpoLsKAdBL8-gBBJ4TKYzI4gvZ8Q6JTb7fAuKFGEzMCDgXoAZgADMTrqFGhEoi4Wp92l0en0ZDU6jJaV8Gb1+sBrtihsxWOwAJKwOL7bCYSDrAw44ZJLj0QSCAQXaAMBjQEnQDGbBCIBjEfAzDjYYIUjFY2V48AEjgAVlJwWqgSAA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwKKQEMwCUVgYBLGbJXAMXICNmUBqFAJSRQ05AE4wAzsAD0DJi3w1gmJDHLoYMBAFokARwCu9AG4BeAOQBhCADsYSO9oAqiJOZRRb9uxfsAPGGlibABuDxFRCVVTAxgAM20ADnNqWhU1FBtyFVMAImN6JAB3BAhxXI8vBxg8ovowGDRTMCQCqCRtOoa0ABoUehtGenJsbQkoEaRTAEZc1OBx0XoEGBQJUSg8gH0tgAkAeQBlJx3pbHoOCWlRClgAOgRRCDADWHpbO8wBu4ArCTmZItljB5kCVmsNts9kcTlszhcrjdyLBtJBMA8ni83h8vjZfv9cICoEsVqDicCPE8JBIyvQAOYDCGbXIYLQSABc0mkBhsCAA1nS7p5MNJHhAdPBkBIAALTACsdwAbKKnhLXBJPt8-gDpGCQYpaHrKRBqbSGTYmXlWQgOVyefzBcLrkIIpJZXcAMx3abczBgaSCYRiSSavHawm68mkwhBChUQgcZ5weZgEz9MB5JDYL4SNDacgIBA61PGMkk1brZkcHlgZj4nV60jSRNgZMx4K4IA&css=Q) should print ``1, None``, ``2, 3`` ...

**Comment by 0x53A** [comment]
My use-case for the MBP is communication between Main and WebWorkers.

The actor pattern allows me to ensure that the messages are processed serially after each other, even if the message processing itself uses promises.

The idea with TryReceive (or receive with a timeout of 0) was a performance optimization where I would try to receive up to 10 messages and batch process them.

**Comment by alfonsogarciacaro** [comment]
Yes, MailboxProcessor is kind of half-baked. For example, it has a `cancellationToken` field but it's not actually used, and some parameters in the supported methods are ignored: https://github.com/fable-compiler/Fable/blob/a6b645ad6fbb09646067cda67a162203303df828/src/fable-library/MailboxProcessor.ts#L50-L53

It'd be great if you could review the class and extend its functionality (ideally with tests). About batching messages I guess you can use a proxy observable for that: [Example](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSVolqB0AwsADYlgDGSAlsBAvgOKRgBO1Fm40AYgIYAjcvgCSqEMFZJ06JHHBQAQnyQUAFmAAmAeQEI2AN0HkAPAHIAKgD4AFKgQBKKAF50Ud1HJIowPYbYILlAAIhw0dHyscCYA+gA0Irr6rAZssVa2Dm4eXlACAK4AZoVsQQBKYAjUAF5gAIKsrHxwNlkeUKhoAqUxMfgW7ADmg2w2AB4AXFCWTq7t7dSFeUUlrETA+RDezlAADFBIGhDZ8-MAUjD4+kgW1J0b3jaFm1CtUAC0VienP7n2g4EdgVimx+sAGk0Wm0fjDCpIfHooNRoL5kqlWAwAGp8Ej5SpQTTAb4wmGo-DaCAAOTAYyQdgQAOhJPmwNWRHIkVaxJ+TnsUAAPlYkYMIJIwNz3KzQXVNJpxkykVs2IU+BQwFBEn4UsYwOYLABtAC6QoA7tRDhKOl0en0YPk9BR2N0bCbZpb2rlqJogox8l78NSTb6vVzme5Uf4MfgZXKvXEoK73R4AN5QCBgE0a0IICQIHUJ81qJOnTqobqsKC9fDZ3NgN5zMOkrXohgVVDAVI2L1OQXC0WsdUAXxkfwEICCAFk+NQSAJgGMAAqsYBqhAIST4GBISJ057QZFzsafKDfXKooLKVQaHTNnU2ACMuyfCvPvaShh1+D4stee6gY0CY8QHYLZCmgAAiRQ6gsQgAAkAFFgigABSOpwP-RwZA9MBvAHCgrTXPgRgAGWAUB6ygPgEDgCB8OTS0vAAQg6BkggPed8AqNVqE7BV2jJAZqGGUZ-j4jwByQfJWAgZjOkIkiyJAN4T3aYdvjkvMFPIpx0CydA6mo2jN23KQxE6TRqBUOtKMMujvjhCtqEVKB7ygfB8CgABmfZCUtMsQHwBdgGQGwcxApAlnAicYEYFDqHQ6gxPcQlmIMmiKE3cgwCUgAmZ90EHBwgA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwKKQEMwCUVgYBLGbJXAMXICNmUBqFAJSRQ05AE4wAzsAD0DJi3w1gmJDHLoYMBAFokARwCu9AG4BeAOQBhCADsYSO9oAqiJOZRRb9uxfsAPGGlibABuDxFRCVVTAxgAM20ADnNqWhU1FBtyFVMAImN6JAB3BAhxXI8vBxg8ovowGDRTMCQCqCRtOoa0ABoUehtGenJsbQkoEaRTAEZc1OBx0XoEGBQJUSg8gH0tgAkAeQBlJx3pbHoOCWlRClgAOgRRCDADWHpbO8wBu4ArCTmZItljB5kCVmsNts9kcTlszhcrjdyLBtJBMA8ni83h8vjZfv9cICoEsVqDicCPE8JBIyvQAOYDCGbXIYLQSABc0mkBhsCAA1nS7p5MNJHhAdPBkBIAALTACsdwAbKKnhLXBJPt8-gDpGCQYpaHrKRBqbSGTYmXlWQgOVyefzBcLrkIIpJZXcAMx3abczBgaSCYRiSSavHawm68mkwhBChUQgcZ5weZgEz9MB5JDYL4SNDacgIBA61PGMkk1brZkcHlgZj4nV60jSRNgZMx4K4IA&css=Q)

**Comment by 0x53A** [comment]
I haven't really used Observable much, and so can't _think_ in Observables (yet). Thank you for the sample!

I'm kinda packed with work currently and for the next two/three weeks, some time after that I'd like to finish my vectors pr, this and the other issue(s). So, until then it's just empty promises, don't expect too much tbh ;D

**Comment by alfonsogarciacaro** [comment]
Closing for now, please reopen if further discussion is needed.
