### ISSUE TITLE
System.Collections.Generic.Dictionary.Add should throw if key already exists

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1790]
.NET:

![grafik](https://user-images.githubusercontent.com/4236651/54386618-a98c5e00-4699-11e9-8b01-cb4c64c0f593.png)

Fable:

```f#
let d = System.Collections.Generic.Dictionary<int, int>()

d.Add(1, 2)
d.Add(1, 3)

printfn "%i" d.[1]
```

this prints ``3``.

**Comment by xdaDaveShaw** [comment]
The [docs](https://fable.io/docs/compatibility.html) state that `Dictionary<K, V>` is compiled to a JS `Map`, which doesn't throw exceptions, but instead just updates the entry.

In F# people would probably use F#'s Map over Dictionary, which has the same semantics as the JS Map.

I can't think of a quick way to solve this without implementing a Dictionary in Fable, along-side Map - would probably be a lot of copy and paste with a few changes to the semantics.

**Comment by 0x53A** [comment]
The quick and dirty fix would be to replace just ``.Add`` with a call to a static function that does the check and then the actual add.

Another way would be to emit a warning on Add.

I know Fables goal is to not to faithfully replicate .net, but rather to embrace js, but I think a warning where behaviour differs would be really helpful.

**Comment by alfonsogarciacaro** [comment]
Yes, wrapping to call to JS Map `.set` with a static function that adds the check is the best solution. BTW, for dictionaries with non-primitive keys, Fable actually uses an F# map under the hood to enable custom key comparison.

Can you please add this method and send a PR? We then only need add a replacement here: https://github.com/fable-compiler/Fable/blob/a6b645ad6fbb09646067cda67a162203303df828/src/Fable.Transforms/Replacements.fs#L2069
