### ISSUE TITLE
Indexing a dictionary with non-existent key should throw. Returns undefined instead

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1798]
### Description

Indexing a `Dictionary<'t, 'u>` with non-existent key should throw. Returns `undefined` instead with Fable which gives unexpected results for people coming from .NET

### Repro code

```fs
open System.Collections.Generic

let dict = Dictionary<int, string>()
dict.Add(1, "one")
let value = dict.[0];
printfn "%A" value // undefined
```

### Expected and actual results
Running the code above in dotnet throws an exception: 

![Untitled](https://user-images.githubusercontent.com/13316248/54822988-b49d4a80-4ca6-11e9-9fc8-09e7d7ffcf54.png)

### Related information

* Fable version: 2.2-beta-018
* Operating system: Windows

**Comment by xdaDaveShaw** [comment]
I'll have a go at this one too, if no one else is :)
