### ISSUE TITLE
Cannot run quicktest: The "path" argument must be of type string. Received type undefined

### ISSUE THREAD

**Issue by xdaDaveShaw** [fable-compiler/Fable#1801]
### Description

On the latest code, running `npm run quicktest` produces the following output.error.

>fable: Compiled .fable\fable-library.2.2.0-beta-019\Option.js
fable: Compiled .fable\fable-library.2.2.0-beta-019\Types.js
fable: Compiled .fable\fable-library.2.2.0-beta-019\Seq.js
fable: Compilation succeeded at 9:07:12 PM (10.184 s)
(node:16356) UnhandledPromiseRejectionWarning: TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type
string. Received type undefined
    at assertPath (path.js:39:11)
    at Object.join (path.js:432:7)
    at getMainScriptPath (C:\Users\Dave\Source\Repos\Fable\node_modules\fable-splitter\dist\cli.js:15:29)
    at index_1.default.then (C:\Users\Dave\Source\Repos\Fable\node_modules\fable-splitter\dist\cli.js:159:31)
(node:16356) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing
inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16356) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

### Repro code

- Commit: `* 953a9643 (HEAD -> master, upstream/master, origin/master) Curried ArithmeticTests`
- `git clean -xdf`
- `npm install`
- `npm run build compiler`
- `npm run quicktest`

### Related information

* Fable version: 2.1.12
* Operating system: Windows 10

**Comment by Zaid-Ajaj** [comment]
This is exactly the issue I encountered at #1774, make sure npx is version 10.0+ since you are using windows it might be the case that you have npx installed both inside program files in nodejs directory and installed as a global npm module inside node_modules in your user profile directory. It can problematic if you have both, in that case delete the npx.bat or npx.cmd inside nodejs in program files so that you always use the global module that you can easily update. Next thing to check is whether you have the dotnet sdk installed the same version in global.json

Hope this helps, sorry can't write all details because I am using phone

**Comment by xdaDaveShaw** [comment]
Thanks @Zaid-Ajaj - I've tried that - but I'm getting the same error with npx 10+ on my path, and I have 2.1.403 SDK installed too.

I think the problem is related to this crash here:

> The "path" argument must be of type string. Received type undefined

But I'm not sure where "path" is supposed to be coming from, and I don't know how to debug fable-splitter :)

For completeness:

```plain
> dotnet --version
2.1.403
> where.exe npm
C:\Users\Dave\AppData\Roaming\npm\npm
C:\Users\Dave\AppData\Roaming\npm\npm.cmd
> npm --version
6.9.0
> where.exe npx
C:\Users\Dave\AppData\Roaming\npm\npx
C:\Users\Dave\AppData\Roaming\npm\npx.cmd
> npx --version
10.2.0
> node --version
v10.15.3
```

**Comment by Zaid-Ajaj** [comment]
> I think the problem is related to this crash here:

> > The "path" argument must be of type string. Received type undefined

Indeed this was the issue I was debugging and it seemed to have been reported from the npx repository as well: 
 - [npx / "Path must be a string. Received undefined"](https://github.com/zkat/npx/issues/144)
 - [npx / Puzzling output: "npx: installed 1 in 1.419s"](https://github.com/zkat/npx/issues/148)

Maybe you can find a workaround in one of these issues. The solution that worked for me was to upgrade npx to 10+ (which you already have) and to make sure that `npx` inside Program Files/Nodejs was not being used (version is old and has to be manually updated) by rearranging the order of PATH variables to use the global module first.

**Comment by xdaDaveShaw** [comment]
I should have also mentioned, this just started the other day.

If I checkout 4d5f1e07 then I don't get the problem.

The next commit 841c4b4 introduces the problem, along with another one (but the other problem is resolved by a6b645a - leaving just the path issue.

**Comment by xdaDaveShaw** [comment]
This looks to be because of a problem with fable-splitter and fsx files.

`info.projectFiles` is only set when it is an fsproj:

https://github.com/fable-compiler/Fable/blob/953a964362334c28c41cbda8ed4f12d00ffce178/src/fable-splitter/src/index.ts#L250-L252

But `getMainScript` is expecting to use the last file from the project here:

https://github.com/fable-compiler/Fable/blob/953a964362334c28c41cbda8ed4f12d00ffce178/src/fable-splitter/src/cli.ts#L15-L19

**Comment by alfonsogarciacaro** [comment]
Thank you both for fixing this!
