### ISSUE TITLE
Function, Symbol & Error

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1805]
### Description

[Function](https://github.com/fable-compiler/Fable/blob/dev2.0-inline/src/dotnet/Fable.Core/Fable.Import.JS.fs#L56), [Symbol ](https://github.com/fable-compiler/Fable/blob/dev2.0-inline/src/dotnet/Fable.Core/Fable.Import.JS.fs#L964) and [Error](https://github.com/fable-compiler/Fable/blob/dev2.0-inline/src/dotnet/Fable.Core/Fable.Import.JS.fs#L331) used to be part of Fable.Import.JS.
Do these types still exist?

### Related information

* Fable version: 2.2
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
I guess they do :) I removed these types (together with String, Boolean, Number) from Fable.Core because I found it confusing to have JS versions of types that could be used in F# (Error is System.Exception).

The only outsider is Symbol, but I didn't any use case for having it in Fable.Core. In my view, when you need to call directly the JS Function or Symbol APIs the F# code starts to look ugly very quickly, and in those cases it's usually better to just write JS or Typescript and communicate with the F# code.

Do you need these types? What would be the use case? If necessary, I'm still not sure if they should be added back to Fable.Core or published in a separate package.

**Comment by nojaf** [comment]
`Fable.Import.Express` and `Fable.Import.Node` uses those types.
Maybe the broader problem is that `ts2fable` will still output these types?

**Comment by alfonsogarciacaro** [comment]
The idea is to deprecate the fable-import repo and move each package to its own repo, so we will have to update them anyways. For node, I'd like to do something similar to what we've done for Browser APIs: split it into a separate package for each node module. It'd be great if we could get volunteers for this :wink: (and overall somebody to maintain the node bindings).

And yes, ts2fable will have to be updated :)

**Comment by nojaf** [comment]
Hmm NodeJS might not be that important to split up into own packages. No real need to optimize for bundle size in a node app in my honest opinion. The current repo already contains separate files so that seems maintainable to me. Feel free to disagree though.

What do you think @whitetigle? I believe you are using Fable for node as well.

I'll make a separate issue for ts2fable.

**Comment by MangelMaxime** [comment]
I have the same opinion of @nojaf. I don't think of splitting Node will improve the User Experience.

**Comment by alfonsogarciacaro** [comment]
There could be some benefits like speeding up the compilation bootstrap time of apps referencing the Node packages, but anyways, maintainability is the most important criteria here, so if having separate files is enough for that (they're not so big anyways) it should be fine.

What I would love is someone moving the package away from "fable-import", update it (removing the "Fable.Import" prefix) and taking ownership of it 😸

**Comment by MangelMaxime** [comment]
> What I would love is someone moving the package away from "fable-import", update it (removing the "Fable.Import" prefix) and taking ownership of it 😸

Still under Fable org? Or under the person name?

I could take ownership of it as I am starting to have several projects running on top of Node.js itself. And so know several manual improvements that can be made to it.

**Comment by alfonsogarciacaro** [comment]
Either option works for me :)

**Comment by alfonsogarciacaro** [comment]
However, it'd be nice if someone else could help. You already take care of many packages ;)

**Comment by nojaf** [comment]
I want to help out and would keep it under the Fable org.

**Comment by whitetigle** [comment]
Same here!

**Comment by alfonsogarciacaro** [comment]
Super, thanks! Please see https://github.com/fable-compiler/fable-node/issues/3
