### ISSUE TITLE
high memory usage of fable-compiler in watch mode

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1806]
this was after a few hours

![grafik](https://user-images.githubusercontent.com/4236651/55007397-a40b0e00-4fdf-11e9-8377-145d805dc7de.png)

I mean it's not a killer, I have 20 GB of RAM

```
fable-compiler@^2.2.0-beta-019:
  version "2.2.0-beta-019"
```

maybe related: https://github.com/fable-compiler/Fable/issues/1087

**Comment by alfonsogarciacaro** [comment]
I talked briefly about this with @kkokosa recently. Apparently it's because you've a lot of RAM that the app is reserving more memory, and will only free it after getting pressure from the OS to do it. It's shouldn't necessarily be an indicator of a memory leak.

**Comment by 0x53A** [comment]
ok thanks
