### ISSUE TITLE
Incorrect range selection on lists

### ISSUE THREAD

**Issue by tpetricek** [fable-compiler/Fable#1817]
When you run the following in normal F#:

    let a = [1;2;3]
    printfn "%A" (a.[0 .. -1])

You get an empty list. When I run the same code in the latest Fable REPL, it prints `[1;2;3]`.

**Comment by alfonsogarciacaro** [comment]
I'm trying to fix this in the commit above, but I still need to add tests. I've added boundary checks though this breaks a bit the symmetry with array slicing which in Fable defaults to native JS `slice` which doesn't throw when using indexes out of range.

**Comment by mknj** [comment]
Why are there different tests for the same functionality under different compile targets?
i.e. "List slice works"  can be found in `tests/Js/Main/ListTests.fs` and in `tests/Python/TestList.fs`

Are you accepting pull requests for JS? I can do the JS fix, but i have no idea on how to run the rust, python or php tests.
