### ISSUE TITLE
FSharp.Core.Fluent?

### ISSUE THREAD

**Issue by fuzzthink** [fable-compiler/Fable#1824]
Is it possible to use fluent (http://fsprojects.github.io/FSharp.Core.Fluent/ - eg. `alist.map`) with Fable? How to setup?

**Comment by MangelMaxime** [comment]
Hello,

You can't use it with Fable directly. In order to use a package with Fable it needs to include the source files in a `fable` folder.

[Example from Fulma](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Fulma.fsproj#L64-L66)

Also, the library seems to also extend `nativeptr` which are not supported by Fable. I don't know if Fable will ignore this extension if you don't use it or if it will fail.

So depending on the  Fable behaviour you could probably use `Paket` to include just the library file your project.

However, the best would be to ask the maintainers of the library if they are ok to add Fable support. And so the actions would something like: 

1. Add the few lines I linked to the fsproj
2. Use `#if !FABLE_COMPILER ...` directives around the unsupported.

**Comment by inosik** [comment]
Seems to work fine, as long as you don't use the unsupported stuff:

``` fsharp
open Microsoft.FSharp.NativeInterop

/// <summary>Fluent extension operations on sequences.</summary>
[<AutoOpen>]
module SeqExtensions = 
    type System.Collections.Generic.IEnumerable<'T> with 
        member inline source.append (source2:seq<'T>) = Seq.append source source2

[<AutoOpen>]
module NativePtrExtensions = 
    type nativeptr<'T when 'T : unmanaged> with 
        [<Unverifiable>]
        [<NoDynamicInvocation>]
        member inline ptr.toNativeInt() = NativePtr.toNativeInt ptr

let x = ResizeArray<_> ()
let y = x.append [1;2;3]
```
[Try in the REPL.](https://fable.io/repl/#?code=PYBwpgdgBAsglgYwE7AM7AGYBcB0AxAZQAsBDJEHAORKzgDcwBJCLMFEAWAChuB6fqAB5UAVwC2YsgE8AfHgA2IyFihgAHqwio4waKDY0dWqLqiowARyUQEYVDkG9RE6TO4BtQQEERWYAHlwCBkAXW4xYAATEXkwKAJLAFENSG1dVCgAXihuKDyoLClweKlUVjEcAGFgeViEWnScAHFINkQcRkSIcQMAI1jBAHIAFRkoAHc4LCIcrnz5qH5eIWdJJFkAdSQSEAzpuKxx4CgAc3pIVW6xAwbjEgySMzgIE9ioBF0EGkhvyNyFvJLS49ba3BxOcRrWT-AFLGELIGCJBgNYAa1QMmGRDiyKwIiQEDAkTMlmstigkikUF6cRA93MxJphzAF2myJIkQyqBIGDA8ikOCgAAlgOMwAwkAAaWYAwECZ6RehwaIkeRQTpXG7AJBQOiqpQZE6tUFEqAYFBiArYqC4-GE4nmKyQcmoIjAGLEiDAFQ0qAkBC2VAM+HzIEfGz45Esfng5FojEh-JwuayxF07aWiAka6ZABE6HxtgAjLnMdaMHAkGUSU6bGBwens24U7CBIJG5ns2A8wWkLYAEylrFxczhh2k531xwd5uyxb8RNy5ZIsB4gkY4c2uwxFSOslT3i29ez1MLlsItvqWwgW7vZEYPMEUrlHBeJAnHosSgxeTJa+3IciBQcZoHGbFoDAKZsR1TArQOI4oBAFA6GVU090nDI4FQRd52WbpanBK8wBvIwTwBa4xBpHVnnkZ4R3dPt6x2IJiQACl7AcAC5HSGUYAEosniSwcGYyAHQYl0JLAftuA8bxfACIJQnCKIYjiahaAYAAFLAkGSTQ0mMbJ4UKYos004jdN4iZwKgEYoE4qARAgSQsyNSIxkmaZZhwzwAFUIAlOAKxIfowGU895k8ShgAAESkLMxEQZg6GAL5bgiudEVWVwACVVztB4KX9Ig6L9SJImRIMzW1P1TnOaBTNNczzkQ4BnlYJBwRy9YyIvZcOygRLu1zG8kEAuJnhAXw2o6tgGzIJscMRI8tDLOJJAQUrCXKyq7HsRxVoTSL8goqioBosqxpwPwNPOZgsFYgTsju7TdJu4BXqYFhEN02SuFiFQ1EE-LtAALzAN9tikQQAH0xie7hAagKlsjUESQBYqB3CLABuftcYAZhCIA&html=DwCwLgtgNgfAsAKEaApgQwCbwQAjz4CFMNHcMABwFoUBHAVwEsA3AXgHIBhAewDswU-KgBUAnhRTscAYz4D+HAQA8wAenDQA3DJBoATgGdiremABmVABzts+Agel7GFMDgN7prAEQB9HwAkAeQBlYT9VKEYAIwNVPXRpMAA6Cj1uDHpExj4kiEZeJIArAy8YYFUHJxdbfGBK51d3T18AkLCfCOjY+LREqgxuCBS0jKycvILi0vL66uR1dCxEZCj00RkoNAMDbzQKall+NHyUPVLEO2AMFhxGDG8UKDyDECo9ii8NrZ2vR+fX97TVTXZjYcqrDCibDzDSwRBAA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA)

**Comment by fuzzthink** [comment]
Thank you @MangelMaxime @inosik !  Got it to work by adding the source file locally.  Submitted a [PR](https://github.com/fsprojects/FSharp.Core.Fluent/pull/15) for it.

**Comment by alfonsogarciacaro** [comment]
Thank you all! Closing the issue as it seems to be fixed, please reopen if there're further questions :+1:
