### ISSUE TITLE
MakeTupleType is not working correctly

### ISSUE THREAD

**Issue by Nhowka** [fable-compiler/Fable#1825]
### Description

`MakeTupleType` is not passing the arguments correctly.

### Repro code

```fsharp
open FSharp.Reflection

let real = typeof<float * string * int[]>
let generated =
    FSharpType.MakeTupleType
        [|typeof<float>; typeof<string>; typeof<int[]>|]

printf "Real: %A\nGenerated: %A" real generated
```

### Expected and actual results

Both should be the same, but the generated outputs ``System.Tuple`1[]``. Seeing the output, the cause is apparent:

```js
export const real = tuple(float64, string, array(int32));
export const generated = tuple([float64, string, array(int32)]);
```

Notice the extra bracket between the arguments, making it not working as it should.

### Related information

* Fable version: 2.3.5

**Comment by Zaid-Ajaj** [comment]
Hello @Nhowka, did you encounter any erros with this? if I look at the implementation of `tuple` :
```ts
export function tuple(...generics: TypeInfo[]): TypeInfo {
  return new TypeInfo("System.Tuple`" + generics.length, generics);
}
```
then both `real` and `generated` should be equal, right? (at least, that's what I think the spread operator does)

**Comment by Nhowka** [comment]
It's wrapping it again, making the types go to the first index as `[[typeA,
typeB]]`

Em sex, 26 de abr de 2019 19:20, Zaid Ajaj <notifications@github.com>
escreveu:

**Comment by Nhowka** [comment]
Using the last tip I found [here](https://www.jstips.co/en/javascript/flattening-multidimensional-arrays-in-javascript/), replacing the implementation for

```js
export function tuple(...generics: TypeInfo[]): TypeInfo {
  const gen = [].concat(...generics);
  return new TypeInfo("System.Tuple`" + gen.length, gen);
}
```
might work passing it both ways.

**Comment by alfonsogarciacaro** [comment]
Ah, damn! I've had similar issues other types. Thanks for reporting, I'll take a look :+1:
