### ISSUE TITLE
More helpful error messages when packages are incompatible

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1829]
I'm unsure if this belongs in this repo, but I'll try.

I have tried to compile an app with Fable.Core 3, and one of my packages is not updated for Fable.Core 3. This gives me the following error:

```
  ERROR in ./src/Renderer/SaveLoad.fs
  Module Error (from ./node_modules/fable-loader/index.js):
  C:/Users/Christer/Source/Repos/fable-elmish-electron-material-ui-demo/src/Renderer/SaveLoad.fs(1,1): (1,1) error FSHARP: The module/namespace 'Fable.Import.JS' from compilation unit 'Fable.Core' did not contain the namespace, module or type 'Function' (code 193)
   @ ./src/Renderer/App.fs 7:0-172 91:224-245 104:219-242 107:76-83 133:29-38 193:42-49
   @ ./src/Renderer/Entry.fs
   @ ./src/Renderer/Renderer.fsproj
   @ multi ./src/Renderer/Renderer.fsproj ./src/Renderer/scss/main.scss
```

This is of course very unhelpful, because it tells me absolutely nothing about where the error actually is, not even which package it comes from.

Since I see this error in VS too, I guess this message comes from the F# compiler. But is there something Fable could do to give me a more helpful error message, either directly or through the F# compiler?

Let me know if I'm being unclear.

**Comment by MangelMaxime** [comment]
We explained how to detect the not updated library in [this blog post](https://fable.io/blog/Announcing-2-2.html#other-packages-fulma-thoth-json-fable-simplehttp-).

I don't think we can do much about in Fable side because this error is generated by F# compiler and I don't think it gives us a lot of info about it just the string/error you see...

**Comment by cmeeren** [comment]
Thanks! It's not a general solution, but it certainly helps in this case.
