### ISSUE TITLE
Fable needs logo,Twitter account and Github organization

### ISSUE THREAD

**Issue by sergey-tihon** [fable-compiler/Fable#183]
- [x] Fable needs an beautiful logo
- [x] [Fable needs an official twitter account](https://twitter.com/sergey_tihon/status/739415004877869056)
- [x] Fable needs its own Github organization
- [x] Fable needs a Gitter chat

**Comment by alfonsogarciacaro** [comment]
After solving this, also open Gitter chat (see #123)

**Comment by sergey-tihon** [comment]
Gitter is simple, I can create if you wish @alfonsogarciacaro

**Comment by mastoj** [comment]
Where are we standing on this? I think it is about time to get an organization, and I also think that might help grow the fable ecosystem.

**Comment by alfonsogarciacaro** [comment]
The logo is the bottleneck ;) I'm still trying to decide if I should give it a shot myself or relying on 99designs.es...

**Comment by theprash** [comment]
Why not make the Twitter account without a logo, tweet asking for logo suggestions and ask prominent F# people to retweet?

**Comment by alfonsogarciacaro** [comment]
I asked some people and there are mixed opinions about opening a logo contest but that could indeed be an idea :+1:

**Comment by tpetricek** [comment]
On the logo issue, I think all the nice logos around (F# logo, Suave logo) were created by professionals, so I tend to think that a professional help would be nice to get something really pretty... (that said, you never know...).

I guess Fable could easily get funding for the logo via some crowd-funding thingy, which would also let supporters vote on the final design (could be from the 99 designs site).

**Comment by mastoj** [comment]
Maybe the fsharp foundation can fund a logo?

Anyhow, I really think it is about time :).

**Comment by voronoipotato** [comment]
So are we going with the :turtle: tortoise or the hare :rabbit2: ?

**Comment by alfonsogarciacaro** [comment]
Fable has now its own [Github organization](https://github.com/fable-compiler), [Twitter account](https://twitter.com/FableCompiler) and a (temporary) logo, so we can close this issue now :) I'll open a new one to let users submit proposals for the new logo :+1:
