### ISSUE TITLE
Unit argument is undefined

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#1832]
In the following code:

```fsharp
let run() =
    promise {
        let! res =
            loginAsync Consts.login None
            |> Promise.map (fun t -> token <- t)
        res
    } 
```

`Promise.map` translates as follows:

```js
      }).then(function () {
        const res = _arg2;
        res;
        return Promise.resolve();
      });
```

Which fails with: `_arg2 is undefined`

Arguments identifiers with unit value should be erased.

* Fable version: 2.3.6

**Comment by alfonsogarciacaro** [comment]
@ncave The regressions seems to happen because [of this change](https://github.com/fable-compiler/Fable/commit/c8f5d904e700e30d4b056ca78db279ad93e63cd4#diff-6cdb34550bd9c0e2af515fc24095a947R1157). Do you remember why it was necessary to add the `v.CompiledName.EndsWith("@")` condition?

**Comment by ncave** [comment]
@alfonsogarciacaro
> Arguments identifiers with unit value should be erased.

That's not always true, in some cases that's breaking things.
I see you rolled it back, that's fine I just have to find a more narrowly targeted way of limiting that replacement.

**Comment by alfonsogarciacaro** [comment]
@ncave Thanks for checking! The thing is fable removes the unit arguments, so something like `fun () -> ...` which in the F# AST becomes `Lambda(Value _arg1, ...)` in JS becomes `function () { ... }`. So if we try to reference the compiler generated _arg1 we get an error. That's why I erase argument with unit value.

Do you have a code sample that is broken because of this behaviour? Maybe we could restrict this to compiler generated arguments, if necessary.

**Comment by ncave** [comment]
@alfonsogarciacaro That's what `v.CompiledName.EndsWith("@")` was trying to do, more or less.

**Comment by krauthaufen** [comment]
wouldn't it be simpler not to emit unit-variables at all?
I mean globally replace all occurrences of unit-variables with null or something?

Cheers

**Comment by alfonsogarciacaro** [comment]
@krauthaufen Yes, this is the current behavior. I added a warning in verbose mode because this may cause unexpected results in some corner cases (see #1516). It also seems that @ncave discovered some cases where this broke the code, maybe when using the optimized results from FCS?

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, I'll add some tests when I can to showcase it.
