### ISSUE TITLE
ReferenceError: _arg1 is not defined

### ISSUE THREAD

**Issue by matthid** [fable-compiler/Fable#1833]
### Description

We just debugged some issue which as emerged after some change (`npm update` or something else or whatever).
The interesting thing is the code in change didn't change. Neither did any of the signatures of the objects below. I can give more details as needed and can try to give some full repro if it isn't immediately obvious to someone.

```fsharp
open Fable.Core
open Fable.Import.JS
open Fable.Import
open Fable.Powerpack

type [<AllowNullLiteralAttribute>] HubConnection =
    abstract start: unit -> Promise<unit>
    abstract onclose: callback:(Error->unit) -> unit


let startSignalRConnection(connection : HubConnection) (connectedCallback : bool -> unit) : unit =
    let rec retry() =
        promise {
            try
                let! promise = connection.start()

                connectedCallback true
            with
            | error ->
                Browser.console.error("[SignalR] Connection failed!", error)
                do! retry()
            }
    let onCloseCallback(error : Fable.Import.JS.Error) =
        let helper () =
            promise {
                connectedCallback false
                return! retry()
            }
            |> Promise.start

        helper() |> ignore

    connection.onclose(onCloseCallback)

    Promise.start(retry())

startSignalRConnection null (fun _ -> ())
```

The generated javascript looks like this:

```javascript
  var retry = function retry() {
    return Object(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["Promise$002EPromiseBuilder$$Run$$Z59A68933"])(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["PromiseImpl$$$promise"], Object(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["Promise$002EPromiseBuilder$$Delay$$Z243C0199"])(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["PromiseImpl$$$promise"], function () {
      return Object(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["Promise$002EPromiseBuilder$$Delay$$Z243C0199"])(_fable_Fable_PowerPack_3_0_0_Promise_fs__WEBPACK_IMPORTED_MODULE_4__["PromiseImpl$$$promise"], function () {
        return connection.start().then(function () {
          var promise = _arg1;
          connectedCallback(true);
          return Promise.resolve();
        });
      }).catch(function (_arg2) {
        var error = _arg2;
        console.error("[SignalR] Connection failed!", error);
        return new Promise(function (resolve) {
          return setTimeout(resolve, retryWaitTimeInMilliseconds);
        }).then(function () {
          return retry().then(function () {
            return Promise.resolve(null);
          });
        });
      });
    }));
  };
```

Note how `_arg1` is not defined anywhere.

I tried to reproduce this [in the repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIqoCSAtiNgC6oBSAyvuNPMmhVVtbrtQJ7goAbQA8AQSRJgAdwByAVykAZAJbUwWOEnHVqWVQgUaAfAF0oACQUJMECGADG1VcGgBeXFG9REAZ304ZygAuG4ALigFCHUoAFoTKAAFLGByVT8wUWj1Ey8ff0Dgt0dpTMjHbSQEIIBrcIAKAFEsVKwEnOoASnjEzt5cFGoQ6jDqBlUAcwhtACU7B2dXCAbHN0WXNyhI61t1p02IHtX95zAAE3Qqmsda7agEYGAkXqiY7vvOqE8fKCGoHCOAFgfT8Bo9H6-HwgVLpTJQADe+ShUNByJRGKGAEIoDC0hkwN8oGt7AdlqhQtxwbwMbTiacNJdrnUoPoFHh0XSfAB6bnSSaTTRkCAAM2w5DghwaACJhBNpnMLAsDhcsdKupyMTJ1AALTUogA+UE0bV6+rpACFUjJMlhUCS-M80CbsDK5VMZkhZkqGcsoCK4KoUOc1QAaY2tbAarko87AHE4UHUmNQAC+NJ5fJBUAAXm5Ce4oAAtfOoEsOe0KVqQHi-f5udBlMBXKQ3WoNF1Ye5sEicGj0BioFptCHm-46sBIcBd8Hfc2-PFwwlIlO-XnKYCTVSVJAt3duDQAD1omWoADVtOyoNK1tWkJLlqRztKoDL5Z75r63AB9BtNvdtt+L4ANQjAYECTK+DD8AEYDkKgADiCiqOcqByGAMhISh4JdNGq7eCSGwXABLIBkgmTzhivL8oKdoAOphDEEFuu+ipQMqSxbGU1BhhGI6USivJxjiKT4pkFIoGAIDAqCDHqAAKqo5BgKQEAALJBkgBIkucfgCVCiZVhACYglgYJ4Vy6YpryBqJKJS4ZoJ3KqCKxaluWaCOFWOAQLQMzKVAoiJHmFb+YS1ATtAIVoFg0QNCK0RQN+rwTlOmg4eavKTvCqXTsmGK5elPS2VAHrYByvyEWSbioCUTYNH+wCZCRtwauiiZmbOJVlTgvCUuMHpzBxhxQBASgvPFiXJQkr64UAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)
The problem is that there is no `Fable.Powerpack` in the repl.

### Expected and actual results

Expected: Generated code runs
Actual: Generated code is broken

### Related information

```
$ npm show fable-compiler version
2.3.7
```

**Comment by MangelMaxime** [comment]
This looks similar to: https://github.com/fable-compiler/Fable/issues/1832

**Comment by alfonsogarciacaro** [comment]
@matthid Thanks for reporting! I just published fable-compiler 2.3.8 to fix #1832. Could you please try it to see if this is the same issue? Thanks!

**Comment by matthid** [comment]
Interestingly this has appeared after some unrelated change in the code base, but I'll check npm lockfiles again...

**Comment by matthid** [comment]
Yes indeed in the same change the package-lock was updated to use a `fable-compiler >2.3`
Seems like we still need to get to know the npm tooling better.

By the way another workaround was:

```diff
-                let! promise = connection.start()
+                do! connection.start()
```

Seems the udate to `2.3.8` works as well.
