### ISSUE TITLE
Issues running Fable 2.x

### ISSUE THREAD

**Issue by wilsonwang881** [fable-compiler/Fable#1840]
### Description

Hi I'm getting an error here.

The module/namespace 'Fable.Import.JS' from compilation unit 'Fable.Core' did not contain the namespace, module or type 'Function'

### Related information

* Fable version: 2.3.0
* Operating system: Mac OS X 10.14.4 Mojave

I was working on two computers: one Windows 10 machine and one Mac running Mojave. The problems I got probably have something to do with the recent update.

The error comes from several .fs modules with names: Main.fs, Menubar.fs

The `open` sections of those .fs modules have the following code:

open Fable.Core
open Fable.Core.JsInterop
open Fable.Import
open Fable.Import.Electron
open System

I don't know why this happens. The Windows machine is used for development and the Mac is for testing. All code is completed on the Windows machine

**Comment by Zaid-Ajaj** [comment]
The error is most likely occurring because of an incompatible `Fable.Import.Electron` package, it depends on Fable.Core >= 1.1.15 (while currently you need Fable.Core >= 3.0) and it depends on the deprecated Fable.Import.Browser (now using Fable.Browser family of packages, where Electron probably only needs Fable.Browser.Dom as a dependency) 

The solution is to upgrade to Fable.Import.Electron to [Fable.Electron](https://github.com/fable-compiler/fable-electron) but I see it still not published, you can still include the [Electron.fs](https://github.com/fable-compiler/fable-electron/blob/master/src/Electron.fs) file in your project and only install the [Fable.Browser.Dom](https://www.nuget.org/packages/Fable.Browser.Dom/) package

**Comment by alfonsogarciacaro** [comment]
Even if they're "deprecated" (meaning we're not updating them), old libraries still work. So you can just keep using Fable.Import.Electron, Fable.Import.Browser and Fable.Core 2.0.* until the Electron bindings get updated. The only trick is you need to avoid versions of packages that depend on Fable.Core 3 (e.g. for Fable.Elmish you should use 2.0.*).

BTW, we're looking for maintainers of the Electron package so if you're interested in using Fable with Electron and would like to maintain the package we could help you with the update until you get used to it :)

**Comment by wilsonwang881** [comment]
@Zaid-Ajaj @Zaid-Ajaj Thank you very much for your help! In my paket.dependencies file, I have pinned the Fable.Core version to 2.0.3.

Now I have done

.paket/paket.exe install
.paket/paket.exe update

But this seemed to break my code. I got errors in the following code:

    let opts = createEmpty<Node.Url.Url<obj>>
    opts.pathname <- Some <| Path.join(Node.Globals.__dirname, "../index.html") ///ERROR in 'join'
    opts.protocol <- Some "file:"
    window.loadURL(Url.format(opts)) ///ERROR in 'format'

I checked this webpage: https://github.com/fable-compiler/fable-import/blob/master/Node/Path.fs

And I found `abstract join : [<ParamArray>] paths : string [] -> string` in `IExports`

I also checked this webpage: https://github.com/fable-compiler/fable-import/blob/master/Node/Url.fs

And I found `abstract format: url: Url<obj> -> string` in `IExports`

Why I can't ues `format` and `join` in my code?

Again, thank you very much for your help! And I apologize for asking such rudimentary questions and for taking up your time! It will be great if you could help me out here.

Actually, I'm working on a project using Fable and Electron. And yes I'm glad to be part of the fable community.

**Comment by wilsonwang881** [comment]
Hello again, I have solved the problem of loading the index.html file by look at the link:
https://github.com/fable-compiler/fable-import/blob/master/Node/Exports.fs

My code is modified to:

    let opts = createEmpty<Node.Url.Url<obj>>
    opts.pathname <- Some (Node.Exports.path.join(Node.Globals.__dirname, "../index.html"))
    opts.protocol <- Some "file:"
    window.loadURL(Node.Exports.url.format(opts))

I also looked at this https://github.com/fable-compiler/ts2fable/issues/116

**Comment by alfonsogarciacaro** [comment]
Happy to hear you solved the problem @wilsonwang881! If your project is public, please let me know how I can give it a try to update it to latest dependencies and publish new Electron bindings you can help to maintain :)
