### ISSUE TITLE
Configurable BaseIntermediateOutputPath 

### ISSUE THREAD

**Issue by TheAngryByrd** [fable-compiler/Fable#1843]
### Description

I was trying to setup a Fable project in a docker container similar to [this blog post](https://natemcmaster.com/blog/2017/11/13/dotnet-watch-and-docker/).

Basically you want to volume mount your code directory to the docker container, however you  want to move the `obj` and `bin` folders so they don't collide with the host OS's version.

The way this is configured is by setting this in your fsproj:

```
  <PropertyGroup Condition="'$(DOTNET_RUNNING_IN_CONTAINER)' == 'true'">
    <BaseIntermediateOutputPath>$(MSBuildProjectDirectory)/obj/container/</BaseIntermediateOutputPath>
    <BaseOutputPath>$(MSBuildProjectDirectory)/bin/container/</BaseOutputPath>
  </PropertyGroup>
```

So now in the docker container my `obj` folder should be `obj/container`.

I ended up getting this error:

```
Cannot find restored info for project /code/app/src/BDS.Vision.Federated.ClientApp/AppClient.fsproj
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1647.Invoke(String message)
   at Fable.Cli.ProjectCoreCracker.projInfo(FSharpList`1 additionalMSBuildProps, String file) in /Users/alfonsogarciacaronunez/dev/fable/src/Fable.Cli/ProjectCoreCracker.fs:line 69
   at Fable.Cli.ProjectCracker.fullCrack(String projFile) in /Users/alfonsogarciacaronunez/dev/fable/src/Fable.Cli/ProjectCracker.fs:line 239
```

which led me to this code:
https://github.com/fable-compiler/Fable/blob/15fc91d46a2ba5794893adfb21a7882148f01dcb/src/Fable.Cli/ProjectCoreCracker.fs#L58-L60

### Repro code

Please provide the F# code to reproduce the problem or a link to the [REPL](https://fable.io/repl/).
Ideally, it should be possible to easily turn this code into a unit test.

### Expected and actual results

Fable compiles

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`

2.3.6

* Operating system: 

OSX

**Comment by alfonsogarciacaro** [comment]
I think the check for project.assets.json is only there because the error message from MSBuild if missing is very obscure, but it should probably be safe to remove (Fable also runs `dotnet restore` before calling Dotnet.ProjInfo). What do you think @enricosada?

**Comment by inosik** [comment]
If we really need this check, MSBuild should know the path to this file. We should be able to get it with DotNet.ProjInfo.
