### ISSUE TITLE
Fable.Core v3.0 detected, expecting v2.0

### ISSUE THREAD

**Issue by reflash** [fable-compiler/Fable#1846]
### Description

I am experiencing a problem with dotnet-fable compiler. After paket update I now get the following error:
```
ERROR: Fable.Core v3.0 detected, expecting v2.0
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1645.Invoke(String message)
   at Fable.CLI.Agent.checkFableCoreVersion(FSharpCheckProjectResults checkedProject)
   at Fable.CLI.Agent.createProject@94-7.Invoke(FSharpCheckProjectResults checkedProject)
   at Fable.CLI.Async.map@200-1.Invoke(a _arg1)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvokeNoHijackCheck[a,b](AsyncActivation`1 ctxt, FSharpFunc`2 userCode, b result1)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```
### Repro code

Here's my paket.dependencies file:
```	
group Client
    source https://api.nuget.org/v3/index.json

	nuget Fable.Core ~> 2.0.3
	nuget Fable.React
	nuget Fable.Elmish.React
	nuget Fable.Elmish.Browser
	nuget Fable.Elmish.Debugger
	nuget Fable.Elmish.HMR
	nuget Fulma

    clitool dotnet-fable 
```

I have set Fable core to 2.0 and I'm unsure why it still detects it as 3.0.

### Related information

* Fable version: `npm show fable-compiler version` = `2.3.11`
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Hmm, not sure if this is a Fable or Paket issue. Can you please check the paket.lock file? What's the actual Fable.Core version installed?

BTW, if you're still using `dotnet-fable`, you need to type `dotnet fable --version` to display the version. If you want to use the latest compiler (distributed through npm by the name `fable-compiler`) you can just run `npm install fable-loader fable-compiler` and then start webpack or webpack-dev-server directly, like `npx webpack-dev-server` ([example](https://github.com/fable-compiler/fable2-samples/tree/master/minimal)).

**Comment by reflash** [comment]
That's what I have in paket.lock
```
    dotnet-fable (2.0.11) - clitool: true
      Dotnet.ProjInfo (>= 0.20) - restriction: >= netcoreapp2.0
      FSharp.Compiler.Service (>= 25.0.1) - restriction: >= netcoreapp2.0
      FSharp.Core (>= 4.5.2) - restriction: >= netcoreapp2.0
      Microsoft.NETCore.App (>= 2.0) - restriction: >= netcoreapp2.0
      Newtonsoft.Json (>= 11.0.2) - restriction: >= netcoreapp2.0
    Fable.Core (2.0.3)
      FSharp.Core (>= 4.5.2) - restriction: >= netstandard2.0
```

**Comment by alfonsogarciacaro** [comment]
This is strange. Can you please try removing the `obj` folder next to .fsproj and then running `dotnet restore` again?

In any case, I removed the Fable.Core version check in `fable-compiler` so upgrading the compiler as mentioned above should fix the specific issue too.

**Comment by reflash** [comment]
Removing `obj` has helped somehow 👍 . thank you!
