### ISSUE TITLE
Documentation: Interacting.md incorrect for Fable 2

### ISSUE THREAD

**Issue by kqr** [fable-compiler/Fable#1847]
### Description

The documentation on how to interact with JavaScript [describes JSON serialisation using functions that don't exist](https://github.com/fable-compiler/Fable/blob/master/docs/interacting.md#json-serialization) in Fable 2, and there is also no hint about what alternatives are suggested.

This is a pretty bad situation to be in when it comes to a relatively common operation like that (I, for one, was close to not suggest Fable to my team when I couldn't get JSON serialisation to work.) I understand not wanting to include the support for it, but then the documentation should ideally reference one alternative solution. In the worst case, it should list multiple options and give the reader the information they need to compare and contrast them.

I know the documentation is in the process of being updated, but that is not an excuse for exposing flat out wrong information to the current users who are looking for documentation right now.

I'd be happy to write up a couple of paragraphs suggesting Thoth.Json since that's what I ended up using, but I'd like to hear your thoughts on how first, so I don't do things unnecessarily.

**Comment by alfonsogarciacaro** [comment]
You're right @kqr, sorry for the misleading information. The ongoing effort to update the documentation is [happening in this repo](https://github.com/fable-compiler/fable-doc). About recommending a library for JSON serialization, instead of adding it into the docs, my idea was to create simple package indexer, somewhat similar to [what Elm has](https://package.elm-lang.org/).

**Comment by kqr** [comment]
Sure, either works. Then we simply remove the JSON section from the current docs now? Because whats there now is literally worse than nothing!

**Comment by alfonsogarciacaro** [comment]
New documentation is ready, sorry for the delay! https://fable.io/docs/communicate/js-from-fable.html

If there's something else that can be improved (and there's always something), could you please PR to the [docs source](https://github.com/fable-compiler/fable-compiler.github.io/tree/dev/docsrc)? Thank you!

**Comment by kqr** [comment]
Wow, this is great! This makes me that much more enthusiastic about starting the Fable project back up at work again! Thank you.
