### ISSUE TITLE
Add U9 (and above)

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1852]
In Electron's [TouchBar constructor](https://electronjs.org/docs/api/touch-bar#new-touchbaroptions-experimental) the two arguments must be one of 9 types. Since we have `U8` but not `U9` and above, I have to model this as `obj`.

I propose we add higher arity `U` types. Perhaps up to 16 for good measure? I guess they are basically zero maintenance.

**Comment by nojaf** [comment]
I think that is a limitation of F# itself.
Is the max length of tuples not 8?

**Comment by cmeeren** [comment]
This works fine

```f#
let x = (1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16)
```

**Comment by Zaid-Ajaj** [comment]
If you need to use `U9` then you should probably avoid `U<>` althogether! Implement a better API:
```fs
// add members if needed 
type ITouchBar = interface end 

// common interface for different touch bar elements (button, color picker etc.)
type ITouchBarElement = interface end 

module TouchBar = 

  let button props : ITouchBarElement  = (* do native stuff *)
  let colorPicker props ITouchBarElement  =  (* do native stuff *)
 
  let create (items: ITouchBarElement list) (escapeItems: ITouchBarElement list) : ITouchBar = 
     // convert to arrays because that's what the constructor is expecting
     let itemsArray = Array.ofList items
     let escapeItemsArray = Array.ofList escapeItems
     // call the contructor
     constructTouchBar itemsArray escapeItemsArray 
```
Consume the API
```fs
let touchBar = 
  let items = [ TouchBar.button [ ]; TouchBar.colorPicker [ ] ]  
  TouchBar.create items [ ]   

window.setTouchbar touchBar
```
The interface `ITouchBarElement` could also be a discriminated union but an interface works just fine

**Comment by cmeeren** [comment]
Thanks for the tip! I'll go with having all relevant types implement `ITouchBaritem`.

The Electron API is large/complex enough that I want to stick with pure types for now. A more helpful API with custom code is a possible future endeavor.
