### ISSUE TITLE
How to treat StringEnums as strings in F# and concatenate etc.?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1853]
I want to write a helper for creating [Electron accelerators](https://electronjs.org/docs/api/accelerator) (keyboard shortcuts). In short, I have this:

```f#
  [<StringEnum; RequireQualifiedAccess>]
  type Modifier =
    | Ctrl
    // ...

  [<StringEnum; RequireQualifiedAccess>]
  type Key =
    | A
    // ...

  let createAccelerator (ms: Modifier list) (k: Key) : string =
    "" // How?
```

In order to output accelerator strings valid for use in Electron, `createAccelerator` should join the modifiers and the key with `'+'`. For example, `createAccelerator [Modifier.Ctrl] Key.A` should return `"Ctrl+A"`. How can I write the function to accomplish this? Is there a better way to accomplish this particular use-case?

**Comment by MangelMaxime** [comment]
In general, you use `unbox`:

```fs
!!ms + "+" + !!k
```

**Comment by cmeeren** [comment]
Thanks! :) (I tried that first, but forgot to `open Fable.Core.JsInterop`, so I got another operator and thus an unhelpful compiler error about the types not being supported for the operator.)

**Comment by Zaid-Ajaj** [comment]
You can also use `Emit` or `unbox` without runtime costs: 
```fs
[<Emit("$0")>]
let toString (myEnum: AmazingStringEnum) : string = jsNative

let inline toString (myEnum: AmazingStringEnum) : string = unbox myEnum 

let inline toString (myEnum: AmazingStringEnum) = unbox<string> myEnum 
```

**Comment by MangelMaxime** [comment]
I am not sure of what you mean by "runtime costs" because `!!` is the same as `unbox`.

The string is directly injected at compile time by Fable.

**Comment by Zaid-Ajaj** [comment]
> I am not sure of what you mean by "runtime costs" because !! is the same as unbox.

No runtime costs means the conversion is happening in compile time (same as `!!`) just suggesting another way of doing the same thing

**Comment by cmeeren** [comment]
@MangelMaxime  As I understand it @Zaid-Ajaj meant that `Emit` and `unbox` were additional ways of doing it without runtime costs.

Thanks for the tips guys! For the record, my implementation is currently looking like this:

```f#
let createAccelerator (modifiers: Modifier list) (key: Key) =
  modifiers, !!key ||> List.foldBack (fun (m: Modifier) acc -> !!m + "+" + acc)
```

**Comment by alfonsogarciacaro** [comment]
I was going to suggest the `string` operator or `Fable.Core.Reflection.getCaseName` but I just realized Fable is not checking the union is actually a string in those cases 😅 

We should probably improve that (at least erase the `string` operator for StringEnum). I will reopen the issue as a reminder.

**Comment by alfonsogarciacaro** [comment]
`string` is already erased when used with a StringEnum :+1:
