### ISSUE TITLE
Nasty bug with stateful Regex ?

### ISSUE THREAD

**Issue by Luiz-Monad** [fable-compiler/Fable#1854]
Is there a reason for using the "g" modifier always ?
https://github.com/fable-compiler/Fable/blob/a12e413ebea661594b287fbea42cdea51d3420e4/src/fable-library/RegExp.ts#L11-L14

It appears that regexes in JS are Stateful when using "g", I had a problem when passing regex to a JS library. source: https://ponyfoo.com/articles/stateful-regular-expressions

Code like this will fail when returning a "/g" regex.
https://github.com/text-mask/text-mask/blob/d8510f81c8900c5a35ebb3731a7149164cca0013/core/src/conformToMask.js#L141
This code is totally stateless, and I'm using a simple stateless input component with ref hooks, and it was a nasty bug because of the regex behavior, and because I memoized the array of regex, I guess I shouldn't do that.

I'm talking about the code generated from this replacement.
https://github.com/fable-compiler/Fable/blob/28295febd79592968545a0b74dd3a9dad22e6892/src/dotnet/Fable.Compiler/Replacements.fs#L1209-L1215

![Untitled](https://user-images.githubusercontent.com/4574729/59641975-af328d80-9139-11e9-989d-26a91be2b615.png)

It would be a good thing to put this in the caveat about Regexes.
Perhaps this is not even a bug when you use Regex from the F# side if the compiler is always generating a new call (I didn't test it).

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately it's necessary to have a closer behavior to how Regex works in .NET. My original intention was to use plain JS RegExp and emulate the .NET API for easier use, but there are still some different semantics. We're trying to remove the most obvious ones (like .NET regex being always global) and some users are pushing for more :) (like named groups, see #1820).

However, it's true sometimes you don't want to add the global flag. For those cases you can use the native JS RegExp constructor instead, that lets you customize the flags. I'll put that in the Regex caveats in the new documentation.

```fsharp
open Fable.Core

let myRegex = JS.RegExp.Create("foo")
```

**Comment by Byte-666** [comment]
Yeah, translating semantics between environments is never easy. I was expecting the Dotnet Regex to be translated to JS regex. But I didn't expect JS regex to be stateful.
I guess an warning in the docs is enough for now.

(If I needed perfect semantics I'd try to copy the entire regex engine from the mono source code, performance would be a problem, as it needs an IL emmiter)

**Comment by alfonsogarciacaro** [comment]
Closing, please reopen if there are further questions
