### ISSUE TITLE
Add GetEnumNames to ITypeResolver?

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1855]
With the newish reflection infrastructure (``ITypeResolver``) in place, would it be possible to solve https://github.com/fable-compiler/Fable/issues/1217 and similar?

I tried 

```f#
type E = A = 0 | B = 1 | C = 2

type X = 
    static member GetAllNames(?r:Fable.Core.ITypeResolver<E>) =
        r.Value.ResolveType().GetEnumNames()
```

but that fails with ``error FABLE: Cannot resolve System.Type.GetEnumNames``.

Or is there already a way to get all names?

I'd need a way to enumerate all enum names, and then map a name to a int value, and vice-versa.

For the short term I'll probably just hardcode it, but compiler assistance would be really great.

**Comment by MangelMaxime** [comment]
In Fulma we are using [`Fable.Core.Reflection.getCaseName`](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Common.fs#L13) it gives you the `CaseName` or `CompiledName` attribute value if set.

And if we want the rank of it, we use [`Fable.Core.Reflection.getCaseTag`](https://github.com/Fulma/Fulma/blob/master/src/Fulma/Common.fs#L26)

**Comment by 0x53A** [comment]
my example was wrong, I want to reflect a CLR enum, not a DU. edited, sorry.

I think these two only work with DUs?

**Comment by MangelMaxime** [comment]
Yes this only works for DUs as far as I know. Having reflection for enums would be great for Thoth.Json too but ATM people needs to write extra coder when they use enums.

**Comment by alfonsogarciacaro** [comment]
Interesting. I was about to answer that Fable doesn't emit any type info at all for enums at the moment, but I just noticed it does indeed, though it's totally wrong. We need to fix this before tackling this.

**Comment by MangelMaxime** [comment]
Hello @alfonsogarciacaro ,

as mentioned in https://github.com/fable-compiler/Fable/issues/1918 I am about to take a look at Enum reflection. So I will take this opportunity to fix this issue too.

Could you please explain to me what is totally wrong so I know what I have to fix?

Also, according to Fable REPL, it seems like Fable generate enums in a form of `record` is this normal? 

```fs
type TestEnum =
    | One = 1
    | Two = 1
```

generates

```js
import { declare, Record } from "fable-library/Types.js";
import { type } from "fable-library/Reflection.js";
export const TestEnum = declare(function Test_TestEnum(arg1, arg2, arg3) {
  this.value__ = arg1 | 0;
  this.One = arg2;
  this.Two = arg3;
}, Record);
export function TestEnum$reflection() {
  return type("Test.TestEnum");
}
```

[REPL live](https://fable.io/repl/#?code=C4TwDgpgBAKhDOwCiA7ArgWygXgFBQKgB8oB5FabKARn0JJgHcB7HGoA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLswooOgBzLlYJPl5tcTo0MK8fXXEAdxiwEFYARgAGHPEQJGDwVjNcmGtPb18rJScXeEQVSFg4IA&css=Q)

**Comment by alfonsogarciacaro** [comment]
Now that `Enum.GetNames` is supported (fable-compiler 2.4.5) you should be able to get the enum names using the .NET reflection API. If the type is not known at compile time you can inline or use the `[<Inject>] ITypeResolver` trick :+1:

**Comment by alfonsogarciacaro** [comment]
@0x53A Would it be ok to close the issue if the proposed solution works for you?

**Comment by 0x53A** [comment]
I'm having issues with the REPL so haven't tested it yet, but to get a mapping between name and value I can call both ``Enum.GetNames`` / ``Enum.GetValues`` and then Zip the result, right?

That should work for all cases. Thank you both.

**Comment by alfonsogarciacaro** [comment]
Yes. The funny thing is Fable will store names and values already zipped, but there's no .NET API for that. If you're planning to do this operation intensively, maybe we could add it to Fable.Core.Reflection.

**Comment by 0x53A** [comment]
I'll just do it once at startup and cache the result
