### ISSUE TITLE
Map does not implement S.C.G.IDictionary

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1857]
```f#
let map = Map [ "1", 1]
let keys = (map :> System.Collections.Generic.IDictionary<_,_>).Keys
```

[repl](https://fable.io/repl/#?code=DYUwLgBAtghgDhAvBAsvCBtCAiAjNgGglwF0BYAKFEgGsQBPAZyQgApYEAuAPggGUmYEFAB0AYQD2wUAGMwASwkA7RiIDiIJSABO8mSICSAET0LlMbfQA8AfQI3uAShEBpBoyA&html=DwCwLgtgNgfAsAKEaApgQwCbwQAjz4CFMNHcMABwFoUBHAVwEsA3AXgHIBhAewDswU-KgBUAnhRTscAYz4D+HAQA8wAenDQA3DJBoATgGdiremABmVABzts+Agel7GFMDgN7prAEQB9HwAkAeQBlYT9VKEYAIwNVPXRpMAA6Cj1uDHpExj4kiEZeJIArAy8YYFUHJxdbfGBK51d3T18AkLCfCOjY+LREqgxuCBS0jKycvILi0vL66uR1dCxEZCj00RkoNAMDbzQKall+NHyUPVLEO2AMFhxGDG8UKDyDECo9ii8NrZ2vR+fX97TVTXZjYcqrDCibDzDSwRBAA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA)

![image](https://user-images.githubusercontent.com/4236651/60029869-3a63d400-96a2-11e9-81f8-086bc1250a79.png)

A quick "fix" could be to detect the cast and error out on compilation? It's always a bit annoying when you get a runtime error.

**Comment by alfonsogarciacaro** [comment]
Yes, I noticed this a few weeks ago (see #1729) but at the end I used a workaround and didn't implement a fix 😅 Seems I cannot escape this from this anymore, hopefully it's not difficult to fix.
