### ISSUE TITLE
CaseRules.LowerFirst for all members of a record

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#1861]
Proposal: we introduce a new attribute that will compile all members of a record instance to have a lowercased first letter.

F.ex
```fsharp
[<LowercaseMembers>]
type Foo = { Bar:string; BarryTwo: int }
```
compiles to

```js
import { record, int32, string } from "fable-library/Reflection.js";
import { declare, Record } from "fable-library/Types.js";
export const Foo = declare(function Test_Foo(arg1, arg2) {
  this.bar = arg1;
  this.barryTwo = arg2 | 0;
}, Record);
export function Foo$reflection() {
  return record("Test.Foo", [], Foo, () => [["bar", string], ["barryTwo", int32]]);
}
```

**Comment by alfonsogarciacaro** [comment]
We can consider this, though I'm a bit wary of changing the runtime representation of a type through attributes as it often adds extra complexity. In the very first Fable version I considered always making the record fields start with lower case, but I discarded that in favor of having a runtime representation of the types closer to the actual F# code.

I personally don't have any problem in using records with lower case fields (I also find it convenient to distinguish them from computed properties in upper case), but I understand some people prefer to stick to the style guidelines.

**Comment by Zaid-Ajaj** [comment]
Keep in mind that if you are sharing this type between backend and frontend, your shared JSON serializers will break! because on the back-end the deserializer is expecting upper case fields and the front-end are working with lower case ones

**Comment by nojaf** [comment]
Not everything is meant to be shared between client and server ;)
So to elaborate on why this is useful, I'm conflicted that I have to write lowercase code just to work with existing JS libraries.

Ex:
```fsharp
type QueryResult<'t> =
    { loading: bool
      data:'t }
```
from https://github.com/apollographql/apollo-client/blob/26c4ff31c6e0853fe93094ca83e502fa0eef580c/packages/apollo-client/src/core/types.ts#L21

All my own code uses capitals to start property names which are generally accepted in F# (can't find any link to back this). So I just don't like the mix. Having some sort of attribute could solve this problem.

**Comment by alfonsogarciacaro** [comment]
Closing as there are no plans currently to implement this feature
