### ISSUE TITLE
Fable compiler output appears in webpack profiler json output

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#1862]
### Description

When trying to profile webpack's import resolution with the following command:

```
./node_modules/.bin/webpack --config webpack.config.build.js --profile --json > stats.json
```

I expect to get only JSON output from webpack inside the `stats.json` file, but instead, fable compiler's output (`fable: Compiled src/...` and so forth) appears at the top of the file.

It's only a minor annoyance since this output can simply be deleted, but webpack's analysis tool (http://webpack.github.io/analyse/) silently fails on faulty JSON, making this bug pretty annoying to debug for new users.

### Repro code

Any webpack based fable project.

### Expected and actual results

`stats.json` file should contain valid json.

### Related information

* Fable version: 2.3.12
* Operating system Mac OS 10.13.6

**Comment by alfonsogarciacaro** [comment]
Ah, yeah, that's true. I had a similar problem when analyzing the Webpack bundle and had to edit the generated JSON manually.

We already have a `--verbose` flag, so I guess we could also have a `--silent` flag to skip all output from Fable.
