### ISSUE TITLE
uint64 `Input string was not in a correct format` for variations in case and underscores

### ISSUE THREAD

**Issue by zanaptak** [fable-compiler/Fable#1880]
### Description

The `uint64` function sometimes fails with error `Input string was not in a correct format` on seemingly valid strings depending on case differences or number of underscores.

### Repro code

```fs
// works
uint64 "0x9fffffffffffffff" |> printfn "%i"

// fails
uint64 "0xafffffffffffffff" |> printfn "%i"

// works
uint64 "0xAFFFFFFFFFFFFFFF" |> printfn "%i"

// works
uint64 "0x9fffffff_ffffffff" |> printfn "%i"

// fails
uint64 "0x9fff_ffff_ffff_ffff" |> printfn "%i"
```

### Related information

* Fable version: 2.3.18
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for catching the issue and providing the code to reproduce it! It will be fixed in the next release :+1:
