### ISSUE TITLE
Cannot have two module members with same name

### ISSUE THREAD

**Issue by jbotto94** [fable-compiler/Fable#1881]
### Description
Compiling some F# code which uses the F#+ library results in:
`error FABLE: Cannot have two module members with same name:`

### Repro code

module App

open Fable.Core.JsInterop
open Fable.Import
open FSharpPlus

let x = map string [|2;3;4;5|]
let y = map ((+) 9) (Some 3)

### Expected and actual results
The error should not appear.
Parts of the F#+ library do not compile in Fable, but that is an unrelated issue.

### Related information

* Fable version: 2.3.19
* MacOS 10.14.6

**Comment by alfonsogarciacaro** [comment]
Hi @jbotto94! The error doesn't seem to come from the code you posted. If you look at the compilation logs (or paste them in full here) they should tell you what's the file where the problem is happening (I guess something in FSharpPlus).
