### ISSUE TITLE
[Query, not issue] Workaround for fable-splitter not allowing babel plugins?

### ISSUE THREAD

**Issue by drk-mtr** [fable-compiler/Fable#1882]
> Is this the right place for a question like this or should I delete it and ask on stackoverflow?

### Description

I have the same problem described here: https://github.com/fable-compiler/Fable/pull/1684

In my scenario, I'm trying to import `Collapsible` from `react-native-collapsible`, which also relies on the plugin for the experimental class properties syntax (`@babel/plugin-proposal-class-properties`).

I understand this would address is, but had other problems so it's been reverted: https://github.com/nojaf/Fable/commit/5181876b020dfdca07a6b4eaba36009a21b4e6b7

### Thoughts

The options I've thought of:

- Use Webpack.
- Use a customised version of `fable-splitter` that includes the change in the PR described above, and accept that (for example) Jest will fail.
- Rewrite the library I'm trying to import to remove all experimental features.
- Run the library I'm trying to import through Babel as a "first pass" to strip out experimental features... I haven't looked into this but I'd imagine something like this is achievable.

Is this right or am I missing something obvious?

**Comment by nojaf** [comment]
Maybe we should have a separate configuration option that lists babel plugins from when importing JS files and use it in [getBabelAstFromJsFile](https://github.com/fable-compiler/Fable/blob/master/src/fable-splitter/src/index.ts#L276)

**Comment by alfonsogarciacaro** [comment]
Hi @drk-mtr! I'm not checking SO very often so it's ok to ask here :)

I haven't looked into the issue again, I guess it's solvable but needs sometime to look into (maybe two Babel passes?). I think the PR mentioned could cause other problems, so I don't recommend using it.

For now, the easiest solution would be to use Webpack (but for a react-native app this probably messes with the watcher) or as you say, run a first Babel pass in the library to strip out non-yet standard features.

Anyway, I'll keep this open and try to have a look over it time allowing. Sometimes an issue becomes clearer after is covered in dust ;)

**Comment by drk-mtr** [comment]
Thanks for bearing this in mind!

Maybe the class properties proposal will become official soon and we won't have to worry about this... ojalá.

I find it ironic that the thing causing me problems is a bit of syntax that Fable already does far more nicely in terms of providing safety!

I think for now I'll go for a nice hacky solution that uses webpack to do a first pass, thanks again.

**Comment by alfonsogarciacaro** [comment]
Closing as fable-splitter is not used since Fable 3, please feel free to reopen if you've further questions.
