### ISSUE TITLE
Is there a way to remove undefined fields from records in JS runtime representation?

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#1883]
### Description

JS libraries use the notion of "optional fields" on objects widely. In TypeScript, for example:

```js
interface Foo {
   fieldOne:  number
   fieldTwo?: number
}

const foo = { fieldOne: 42 }
```

In F#, as far as I can tell, this is not doable with records. The best we can do seems to be

```fs
type Foo = {
    fieldOne: int
    fieldTwo: Option<int>
}

let foo = { fieldOne = 42; fieldTwo = None }
```

This results in a runtime JS object

```js
{ fieldOne: 42, fieldTwo: null }
```
This will work for some cases, but some libraries check for `== undefined` or `typeof ... == "undefined"` explicitly, which we can make work if we define a special `Undefined`:

```fs
[<Emit("undefined")>]
let Undefined<'T> : Option<'T> = jsNative

let foo = { fieldOne = 42; fieldTwo = Undefined }
```

results in a runtime representation of

```js
{ fieldOne: 42, fieldTwo: undefined }
```

This has been working well for me for some time now, until yesterday I ran into a library that uses `Object.assign(defaultOptions, userProvidedOptions)` to selectively overwrite `defaultOptions` with user-provided ones. `Object.assign` is key-based, so as long as the key is defined, its value, `undefined` or not, will overwrite that of the default options.

I ended up making things work by implementing a custom `ToPOJO` member method on the record, but it's a very poor, ad hoc solution, which becomes a serious pain when nested records are concerned.

Assuming I come up with some variant of `Option` like

```fs
type CustomOption<'T> =
| NoneDoNotHaveTheFieldOnRuntimeObject
| Some of 'T
```

and use it in my records, is there a way to automate exclusion of keys for `NoneDoNotHaveTheFieldOnRuntimeObject`-assigned fields on the runtime objects that works in all cases, including nested records?

**Comment by alfonsogarciacaro** [comment]
For Fable 2 I was actually considering to remove the fields initialized to None, but at the end we didn't do that because records are ES5 classes at the end and I was also worried this could interfere with the hidden classes optimization of JS engines.

When sending option objects to JS libraries, there are several helpers in the Fable.Core.JsInterop module that you can use to build a POJO without having to fill all the values, like `createObj`, `createEmpty`, `jsOptions` or `keyValueList`. Please check this section of the docs: https://fable.io/docs/communicate/js-from-fable.html#Plain-Old-JavaScript-Objects

**Comment by anchann** [comment]
@alfonsogarciacaro thanks for your response

> there are several helpers in the Fable.Core.JsInterop module that you can use to build a POJO without having to fill all the values

Yum, as I mentioned, that's what I ended up using, but the solution is ugly, ad hoc, and works poorly for nested records.

I think "optional fields" is a fundamental language level mismatch between F# and JS, and as such must be handled at the language level, i.e. Fable, not in some ad hoc per user way. So what you're saying about considering it in Fable 2 sounds like the right direction to me. Except conflating the notion of "field should be absent" with `Option.None` can't be the solution. In JS `some value`, `undefined`, `null`, `field is absent` are four distinct possibilities, and they have to be modelled distinctly on F# records to cleanly cover all interop possibilities. F#'s Option offers only two distinct possibilities, so can't work generally. In my view, the right way to model this would be (modulo better naming — I tried to err on the site of clarity)

```
// in Fable.Core

type JsObjectField<'T> =
| Value of 'T
| Undefined
| Null
| AbsentOnResultingObjectLiteral

// in user code

type SomeThirdPartyConfig = {
    url:            string
    someField:      JsObjectField<int>
    someOtherField: JsObjectField<int>
}

let config = {
    url            = "http://something.com"
    someField      = Undefined // we want explicitly to set this to `undefined`
    someOtherField = AbsentOnResultingObjectLiteral // we want to make sure the library default is applied and not clobbered by an unintended undefined
}
```

Fable runtime would then strip out the `AbsentOnResultingObjectLiteral` keys.

Do you think this would be reasonable?

**Comment by MangelMaxime** [comment]
Depending on what you are doing and how many time you need this you can also use an anonymous record in order to build the exact JObject needed for your library.

Just saying that because `JsObjectField` seems to be a lot of magic and we tried to removed that "magic" from Fable 2 because it was harder for people to know what to do and how to do it.

**Comment by alfonsogarciacaro** [comment]
It is possible now to use an anonymous record with only the fields you need and assign it to an interface with `!!` and still have it type checked by Fable to make sure non-optional fields are present. See [this doc](https://fable.io/docs/communicate/js-from-fable.html#Plain-Old-JavaScript-Objects) and #2459
