### ISSUE TITLE
Unable to use fsx => js on Windows while it's ok on Linux

### ISSUE THREAD

**Issue by rfrerebe** [fable-compiler/Fable#1886]
### Description

I am unable to run https://github.com/fable-compiler/fable2-samples/tree/master/fsx-script on Windows, while it works on linux using https://github.com/nojaf/fable-docker as describe in https://blog.nojaf.com/2018/01/20/building-fable-apps-inside-a-docker-container/

poke @nojaf if you have any idea on this issue ?

### Repro code

On Windows
```
git clone https://github.com/rfrerebe/fable2-samples.git
cd fsx-scripts
npm install
npm start
```

### Expected and actual results

I expect compilation to succeed, it fails with error

```
ERROR in ./src/App.fsx
Module build failed (from ./node_modules/fable-loader/index.js):
Error: File D:/DEV/fable-fsx/fable2-samples/fsx-script/src/App.fsx cannot be found in source list:
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.ReactDom.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.Hooks.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.Props.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.Standard.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.FunctionComponent.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.React.Isomorphic.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.React.5.2.3/Fable.ReactServer.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.Elmish.3.0.0/ring.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.fable/Fable.Elmish.React.3.0.1/react-native.fs
D:/DEV/fable-fsx/fable2-samples/fsx-script/.paket/load/netstandard2.0/main.group.fsx (D:/DEV/fable-fsx/fable2-samples/fsx-script/src/App.fsx)
    at Loader.command.then.data (D:\DEV\fable-fsx\fable2-samples\fsx-script\node_modules\fable-loader\index.js:98:22)
    at process._tickCallback (internal/process/next_tick.js:68:7)
```

NOTE :
It succeeds using docker and nojaf/fable image ...
```
PS D:\DEV\fable-fsx\fable2-samples\fsx-script> $path = "$(pwd)".Replace("D:\","/d/").Replace("\","/");
PS D:\DEV\fable-fsx\fable2-samples\fsx-script> docker run --rm -it -v "${path}:/fable" -p 8080:8080 -w /fable nojaf/fable bash
bash-4.4# npm i
bash-4.4# npm run postinstall
bash-4.4# npm start

> @ start /fable
> webpack-dev-server

ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from ./public
fable-compiler 2.3.20
fable: Compiled src/App.fsx
fable: Compiled .fable/Fable.Elmish.React.3.0.1/react.fs
fable: Compiled .fable/Fable.Elmish.3.0.0/program.fs
fable: Compiled .fable/Fable.Elmish.React.3.0.1/common.fs
fable: Compiled .fable/Fable.Elmish.3.0.0/prelude.fs
fable: Compiled .fable/Fable.Elmish.3.0.0/cmd.fs
fable: Compiled .fable/Fable.Elmish.3.0.0/ring.fs
ℹ ｢wdm｣: Hash: e71b172bdbc4bc6d6e04
Version: webpack 4.31.0
Time: 10495ms
Built at: 08/30/2019 5:17:16 PM
    Asset     Size  Chunks             Chunk Names
bundle.js  901 KiB    main  [emitted]  main
Entrypoint main = bundle.js
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 ./src/App.fsx 40 bytes {main} [built]
[./.fable/Fable.Elmish.3.0.0/program.fs] 7.53 KiB {main} [built]
[./.fable/Fable.Elmish.React.3.0.1/react.fs] 2.94 KiB {main} [built]
[./.fable/fable-library.2.3.20/Reflection.js] 7.71 KiB {main} [built]
[./.fable/fable-library.2.3.20/Types.js] 7.66 KiB {main} [built]
[./.fable/fable-library.2.3.20/Util.js] 18.1 KiB {main} [built]
[./node_modules/loglevel/lib/loglevel.js] 7.68 KiB {main} [built]
[./node_modules/querystring-es3/index.js] 127 bytes {main} [built]
[./node_modules/url/url.js] 22.8 KiB {main} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 8.26 KiB {main} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.59 KiB {main} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.05 KiB {main} [built]
[./node_modules/webpack-dev-server/node_modules/strip-ansi/index.js] (webpack)-dev-server/node_modules/strip-ansi/index.js 161 bytes {main} [built]
[./node_modules/webpack/hot sync ^\.\/log$] (webpack)/hot sync nonrecursive ^\.\/log$ 170 bytes {main} [built]
[./src/App.fsx] 1.71 KiB {main} [built]
    + 37 hidden modules
ℹ ｢wdm｣: Compiled successfully.
```
![image](https://user-images.githubusercontent.com/12632865/64039414-d7d3fc00-cb5a-11e9-97ae-c3d565d6e3d6.png)

### Related information

* Fable version: 2.3.20
* Windows10 with dotnet version 3.0.100-preview8-013656 [C:\Program Files\dotnet\sdk]
(Changing it to 2.2 with a gloabl.json file don't change anything to this error)

**Comment by nojaf** [comment]
Hey, could you check your `.paket` folder. Maybe something is up with the load script.
Does it look like all the files are there and in the right folder?

What version of Paket are you using? I have the global cli version `5.203.0` maybe you have a different version.

**Comment by rfrerebe** [comment]
Hello, 

Thanks for the hint.
It tried to use 5.203.0 (I was using 5.207.0)
```
dotnet tool uninstall -g paket
dotnet tool install -g paket --version 5.203.0
```

But I still have the same error. 
Could you explained how you debug this part ?
What is the expected value of [badSystemDllDir ](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/ProjectCracker.fs#L140-L141) ?
:confused:

**Comment by nojaf** [comment]
Hey, this looks a bit similar to https://github.com/nojaf/fable-reactstrap/issues/2#issuecomment-526892982. Maybe it has something to do with dotnet core 3.x preview.
Not sure if this the case, it does look like an obvious similarity though.

I debug Fable with these settings:
![image](https://user-images.githubusercontent.com/2621499/64079022-79398a00-cce2-11e9-944a-0a8e9a0d672d.png)

Not sure if this helps.

**Comment by nojaf** [comment]
The expected value of bad system dll is `mscorlib.dll` or `System.Private.CoreLib.dll`, however, I do think there is still something not ok with the Paket load script.

**Comment by rfrerebe** [comment]
Hello,

Thanks a lot for your help.

I don't believe my issue has a link to paket file.
I compared linux and windows version and except obvious path differences, they are the same.

Debugging throught the code with your previous comment as a starting point, it seems there is an issue here : https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/Util.fs#L259-L299
because when creating this fsproj with 
netappCore = 3.0
hostVersion = 3.0.0

There is in fact [no version  3.0.0 for Microsoft.NETCore.App on nuget](https://www.nuget.org/packages/Microsoft.NETCore.App)
Using 
```xml
<?xml version="1.0" encoding="utf-8"?>
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netcoreapp3.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.NETCore.App" Version="3.0.0-preview8-28405-07" />
  </ItemGroup>
</Project>
```
(Diff with before is Version is set to **3.0.0-preview8-28405-07** instead of 3.0.0)

I was able to download a package using `dotnet restore`, but it was empty ...
I believe this workaround need to be adapted for next version of dotnet core.

I tried to **uninstall dotnet 3.0-preview8** and **now I can run fsx samples fine** 🚀 
So, my error is definitely linked to a new way of getting theses dlls for dotnet 3.0

Digging in my system, it seems these dlls are installed here:
**C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview8-28405-07\ref\netcoreapp3.0**
(found after creating a very simple program reference System.dll, path was in obj/fsac.cache file)

If I [hard code](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/Util.fs#L273)
```
        let netCoreAssembliesDir = @"C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview8-28405-07\ref\netcoreapp3.0"
        //let netCoreAssembliesDir = Path.Combine(nugetCache, "microsoft.netcore.app", hostVersion, "ref", "netcoreapp" + v.[0] + "." + v.[1])
```
It can run fsx sample fine also 🚀 

Now any idea, on how we can *guess* this path ?

poke @enricosada @alfonsogarciacaro

**Comment by nojaf** [comment]
Ah yes, good catch. Maybe this time the installed system dlls are also a match on Linux.
The default installed dlls always worked on Windows but not on Linux if I recall correctly.

**Comment by rfrerebe** [comment]
No, on linux you are juste using a 2.x dotnet core version in your docker image, while I was a using a 3.0-preview on my windows machine.

**Comment by nojaf** [comment]
No, that is not what I mean. When implementing support for fsx files, we first tried to use the installed dlls at`C:\Program Files\dotnet\shared\Microsoft.NETCore.App\2.2.1`. These come with the installation of dotnet sdk.

This worked well on Windows but not on Linux/Mac so the solution was to get those dlls from NuGet (Microsoft.NETCore.App) to have a cross plat solution.

**Comment by rfrerebe** [comment]
Ok, sorry I misunderstood your comment.

I might be solved in dotnet 3.0, but using **packs** instead of **shared**.

I extracted dlls (/usr/share/dotnet/packs/Microsoft.NETCore.App.Ref/3.0.0-preview8-28405-07/ref/netcoreapp3.0/*) from the mcr.microsoft.com/dotnet/core/sdk:3.0-alpine image and compared them with those from windows installation (C:\Program Files\dotnet\packs\Microsoft.NETCore.App.Ref\3.0.0-preview8-28405-07\ref\netcoreapp3.0\*).

Kdiff tells me all files (261) are binary equals. It was probably expected given microsoft release process ;-)
I don't know what was the issue in dotnet 2.0, but it seems ok to use them for dotnet >= 3.0
Not saying that we won't encounter issues, but I can draft a PR with this.

**Comment by alfonsogarciacaro** [comment]
I just pushed a new fable-compiler version with the change from #1892, thanks again @rfrerebe! Can this be closed now?

**Comment by rfrerebe** [comment]
Sure
Thanks for the merge
I will look to add some tests as you suggested

**Comment by nojaf** [comment]
@rfrerebe @alfonsogarciacaro many thanks for this fix!
