### ISSUE TITLE
static overloads of anonymous records have the same mangled name

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#1891]
### Description

static overloads of anonymous records have the same mangled name

### Repro code

```fs
open Fable.Core
open Fable.Core.JsInterop

type time = 
    static member inline duration(value: {| from: int |}) = toPlainJsObj value 
    static member inline duration(value: {| from: int; until: int |}) = toPlainJsObj value 

time.duration {| from = 1 |}
|> printfn "%A"

time.duration {| from = 1; until = 5 |}
|> printfn "%A"
```

### Expected and actual results

Expected to compile & run without issues
Actual: does not compile and gives error:
```
FABLE: Cannot have two module members with same name: time$$$duration$$4E60E31B
```  

### Related information

* Fable version: latest REPL
* Operating system: N/A

**Comment by alfonsogarciacaro** [comment]
Good catch! I guess the hash generator for overloads arguments doesn't support anonymous records yet. It should be fixable.
