### ISSUE TITLE
Seq.distinct doesn't work on infinite sequences

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#1894]
### Description

Calling `Seq.distinct` on infiinite sequence hangs the execution.

### Repro code

```fsharp
let rnd = System.Random()
let xs =
    seq { while true do yield rnd.Next() }
    |> Seq.distinct
    |> Seq.take 5
xs |> Seq.iter (printf "%d")
```

### Expected and actual results

Expected: print first unique 5 numbers.
Actual: never returns

### Related information

* REPL: https://fable.io/repl/#?code=DYUwLgBATgdgJhAvBAygTwM5hAWwHQBKAhvAPY4AUAlAFCiQAeGSNEbEGIAjhAN4QB3ABYBLUBDBQAriAhxSENCJDAEsOHgByIBmGoQAvq3YAfAHypueOCKwiYAYzDG25y1zxgiAa1kBWGiYINxQrEWwoCAoAByh7MAAzCAAiAFI4ZKogA&html=DwCwLgtgNgfAUAAiQ0BTAhgE3s3KKpjoLhgAOAtKgI4CuAlgG4C8ARAMID2AdmKrxQAqATzKpWCAMY8+vNnwAeYAPThoAbkkh0AJwDOhZrTAAzCgA5WOZMFUZsiGwCNOmYdaS2Xb+LbWwgA&css=Q

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting and the code to reproduce!
