### ISSUE TITLE
Array.Copy not working as of version 2.3.20

### ISSUE THREAD

**Issue by zanaptak** [fable-compiler/Fable#1896]
### Description

Array.Copy worked in 2.3.19, fails silently in 2.3.20. Also fails in latest REPL after ctrl-f5 hard refresh.

### Repro code

[REPL link](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWA2YlQLACuATgMZhQC8UA2gD5QCczUDAurvlACZjIAlhACGSQcGi1GUAIwBuKACZFAZnZdsmAIKlSIuADoAwqDgAKImUoAaKAAY7-IaPGS7juQEos3AmAAPcHIUXhp6JlZFFSh1Tl9MEFJhJAAzaAAiERDiERwoAFJtKEDg0MLtDL4BcVcJaFKwELBeLCA&html=Q&css=Q)

```fs
open System

let source = [| 99 |]
let destination = [| 1; 2; 3 |]

Array.Copy(source, 0, destination, 0, 1)

let expected = [| 99; 2; 3 |]

printfn "actual %A expected %A" destination expected
```

### Expected and actual results

`actual 1,2,3 expected 99,2,3`

### Related information

* Fable version: 2.3.20-23
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Ups, that's the typical regression that always happens when I try to do something clever (see https://github.com/fable-compiler/fable-recharts/issues/8). Thanks for spotting it!
