### ISSUE TITLE
[minor] DateTime in Fable has less precision than in .NET

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#1901]
```f#
open System

let dt1 = DateTime(100L)
let dt2 = DateTime(200L)

printfn "%O and %O are %s" dt1 dt2 (if dt1 = dt2 then "equal" else "not equal")
```

in .NET this results in 

```01.01.0001 00:00:00 and 01.01.0001 00:00:00 are not equal```

in Fable I get 

```Mon Jan 01 0001 00:00:00 GMT+0053 (Central European Standard Time) and Mon Jan 01 0001 00:00:00 GMT+0053 (Central European Standard Time) are equal```

Note that the check succeeds if you increase the values: if you add two zeros (10000L vs 20000L) then I also get ``... not equal`` in Fable.

[repl link](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWA2YlQAmSAjFALxQAiAhigCoCWqYAFCQAwcAyAlLviJIATBWp0wTFq2Fc+WLCABOjCEgBm0AEQBSAPJQaEQlH2GlYUwi1CyxUa0brbY+1CQALSFC1gAjgCuNDg2YDgIlloQwAT+QSG8QA&html=DwCwLgtgNgfAsAKEaApgQwCbwQAjz4CFMNHcMABwFoUBHAVwEsA3AXgHIBhAewDswU-KgBUAnhRTscAYz4D+HAQA8wAenDQA3DJBoATgGdiremABmVABzts+Agel7GFMDgN7prAEQB9HwAkAeQBlYT9VKEYAIwNVPXRpMAA6Cj1uDHpExj4kiEZeJIArAy8YYFUHJxdbfGBK51d3T18AkLCfCOjY+LREqgxuCBS0jKycvILi0vL66uR1dCxEZCj00RkoNAMDbzQKall+NHyUPVLEO2AMFhxGDG8UKDyDECo9ii8NrZ2vR+fX97TVTXZjYcqrDCibDzDSwRBAA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA)

This is a minor issue, I only stumbled on it because I didn't want to have to think about any actual dates for a unit test, and so tested my method with ``DateTime(100L)``. This left me scratching my head for a little bit.

**Comment by ncave** [comment]
@0x53A This is expected, since `System.DateTime` is compiled as JS Date, which has 1 ms resolution (10_000 ticks).

**Comment by 0x53A** [comment]
Okay makes sense, thank you
