### ISSUE TITLE
Data flow problem causing error in closure captured values...

### ISSUE THREAD

**Issue by GordonBGood** [fable-compiler/Fable#1907]
### Description

An inner Tail Call Optimized recursive loop is erroneously referring to the mutable loop value rather than an immutable "captured" version.

### Repro code

[As per this REPL](https://fable.io/repl/#?code=PTAEGcAsHsHdQGIEMBGAbApqAlucBXDAOhIChTMAXUAJwwGNQAHG7ANyUqzWmiZ1DR6AO2oBeUqBwAzAQD4xoAEyhKkDMMEjqGNOAyTQVWgxw8+oAFY5toCVKnZZ1hctXrN2W7v2GpLbFFpTQAibAAuUABSABMAGitI2JCBSwBuM15+AAprAGpQAEYASlBsr1FQApLDcxzsKqLSgB4AH0yLAAYtUQos0G7u1rlmViDQ5NIgA&html=Q&css=Q)
for the following code:
```fsharp
// show Fable issue...

let rec private loop i ocnt =
  if i >= 2 then ocnt else
  let rec iloop j icnt =
    if j >= 2 then icnt else
    printfn "i: %d, j: %d" i j; iloop (j + 1) (icnt + 1)
  loop (i + 1) <| iloop 0 ocnt
loop 0 0 |> printfn "%d"
```

### Expected and actual results

Expected:
```
i: 0, j: 0
i: 0, j: 1
i: 1, j: 0
i: 1, j: 1
4
```
Actual:
```
i: 1, j: 0
i: 1, j: 1
i: 2, j: 0
i: 2, j: 1
4
```

### Analysis of output JavaScript

The problem seems to be that the inner "loop" is referring to the value "i" rather than the actual immutable captured value "$i$$3" (mangled) in the JavaScript code as output:
```javascript
function loop(i, ocnt) {
  loop: while (true) {
    if (i >= 2) {
      return ocnt | 0;
    } else {
      const iloop = function iloop(j, icnt) {
        iloop: while (true) {
          if (j >= 2) {
            return icnt | 0;
          } else {
            toConsole(printf("i: %d, j: %d"))(i)(j);
            const $icnt$$2 = icnt;
            const $j$$1 = j;
            j = $j$$1 + 1;
            icnt = $icnt$$2 + 1;
            continue iloop;
          }

          break;
        }
      };

      const $i$$3 = i;
      const $ocnt$$4 = ocnt;
      i = $i$$3 + 1;
      ocnt = iloop(0, $ocnt$$4);
      continue loop;
    }

    break;
  }
}
```
This would appear to be a data flow ordering problem.

### Related information

* Fable version: REPL Fable version 2.3.21
* Operating system: Not relevent, issue on REPL

**Comment by alfonsogarciacaro** [comment]
Hi @GordonBGood! [This was fixed recently](https://github.com/fable-compiler/Fable/commit/e549bb1f9703dabf2d040273054790852447db83#diff-9ef42320b8c2a5ab449469e7ee82c541R59) but it seems the REPL hasn't been updated yet. Can you try with the CLI tool (fable-compiler)? I'll update the REPL, thanks for letting me know! :+1:

**Comment by GordonBGood** [comment]
@alfonsogarciacaro; thanks for the quick response.  Great that you've already fixed the issue, which I confirmed with the CLI tool with fable-compiler version 2.3.25.

Let's leave this open until you update the REPL.

Fable is Awesome!

**Comment by GordonBGood** [comment]
The online REPL has been updated to version 2.4.2 and this problem has gone away as per the test.

Closing the issue.
