### ISSUE TITLE
Incorrect currying (in particular for React)

### ISSUE THREAD

**Issue by netogallo** [fable-compiler/Fable#1915]
I was writting a react HoC library and found this curious thing.

The F# source is:

```fs
let wrap (inner: obj) =
    fun props ->
        let mutable count = 0
        let effect() = count <- count + 1
        Fable.React.HookBindings.Hooks.useEffect(effect)
        ReactBindings.React.createElement(inner, props, [])

let wrap2 (inner: obj) =
    let comp (props: 't) =
        let mutable count = 0
        let effect() = count <- count + 1
        Fable.React.HookBindings.Hooks.useEffect(effect)
        ReactBindings.React.createElement(inner, props, [])
    comp
```

And the generated code is:

```js
function wrap(inner$$1, props$$1) {
  var count$$1 = 0;
  react.useEffect(function effect$$1() {
    count$$1 = count$$1 + 1;
  });
  return react.createElement.apply(react, [inner$$1, props$$1].concat([]));
}

function wrap2(inner) {
  return function comp(props) {
    var count = 0;
    react.useEffect(function effect() {
      count = count + 1;
    });
    return react.createElement.apply(react, [inner, props].concat([]));
  };
}
```

As you can see, wrap2, even though it returns a function, it gets comiled to a function with two (curried) parameters. This obviously leads to my component not working correctly since the "useEffects" function is called when I wrap the component, not when I use it. Below is a sample usage of this code from an external program:

```js
function Comp(props){
    return <div>Kaiser!!!</div>
}

const RxComp = wrap(Comp);
ReactDom.render(
            <RxComp />,
            document.getElementById('app'));
```

The current workaround is to define the function as I did in wrap2

**Comment by alfonsogarciacaro** [comment]
For better or worse, this is actually intended behavior. The F# compiler uncurries module functions for performance and to increase interoperability with other languages like C#. On top of that Fable also uncurries functions in other situations. So in general you must be careful when calling code generated by Fable from JS because the representation may not be exactly what you expect. However, Fable still offers some guarantees. You can read about them here: https://fable.io/docs/communicate/fable-from-js.html

The F# compiler doesn't know about React effects, so in your sample it thinks it's ok to uncurry the function (it will wrap it if you call it in a curried way _from F# code_). However, if you move the declaration of `count`, then the code will behave as you expect because F# knows it must create a closure every time you call `wrap`:

```fsharp
let wrap (inner: obj) =
    let mutable count = 0
    fun props ->
        let effect() = count <- count + 1
        Hooks.useEffect(effect)
        ReactBindings.React.createElement(inner, props, [])
```

**Comment by alfonsogarciacaro** [comment]
[Example from REPL](https://fable.io/repl/#?code=PYBwpgdgBAQgTsA7gZzHAUKSUBiBDAIwBswA6AJTDwGMAXddE2qROPEARigAoBLCCGgBcUAOQAFKAFoAfFEo1aAURIBbSLQCUUALzooBqAHojUAMq8AJmChgAZnbB0oAKwCuyZrWBQQcMABuGlB4bt6qeLS81FBuENRucHAAnvwA5vqGfvy0dtAARADqbCAg6VAc+ZkGdnE8fqDIIhLastWGBkxQqmGEJFDUwHHMOlAADO0dXfaOdNzaeh1LhoPDUAA8UgNDEMwA1BWTy75wOXlQ+QDCO7RcvMhQAKS8+dvDRwYAEsDAANbIpA8YCUDictG4MzBmg+8iodBg-Es6QBCjopGo-kiwLUGj4AjQABoTo0iQBtAC60MYYGYrHYACYePxBHBmpJZLDFCowOpdgt2iYTmcCsV2GUIGkoPSqlMad1esQbKtdrpxu1atBuA0QE0xOJWjIYdNQXN+cclsrmJs3iqDhwYR1srtzlcboz7k8Xjb6Obvn8AUCQbNwZC6NDzajaAiIEiJSi4bR0ZjaNiebjmYTiTqyZSGNTmNdVFxRnTODwNTwDVAkQEoBS6544BcANJ4e5oCoAQnyua6hcZJZKjO4Ffm0jkNbr5IbtCb+Vb7ab9O7ufQgosqhA-QAFmAiOAm95bD0iFioAApMwADRY2+i2+rYGQbjSeDgDyPeE5aIxVBT3N5ZhqDwIgiHzVxkAAD3LNlZEjACNG0LU2TNQxI2jWM0njRQkz-VNAJHIkQBzKkugCXgwEQMdFkMOw2DSQCpzrGEXCgqBCy4eYWLYjjK246DeK481+PY4BVGHcNjlYgSxIkkT+z4jpyQYSMABExNIfwYzQbhyMo+YiUsYAEkA0g0hpBDdhgZIAElLAuMUpEGXY2xZfJNCAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKVuGiMmHRoHiikFFI8KDlI2hNKGwwzSstoq4sqkLBwQA&css=Q). As you can see, if we don't move the `count` declaration we don't only have a problem with uncurrying but also with the value being reinitialized for every render.

**Comment by netogallo** [comment]
Thank you for the information.

Best, Ernesto Rodriguez
