### ISSUE TITLE
Any tips/guidance for adding Enum reflection?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1918]
### Description

Hello @alfonsogarciacaro ,

I am improving enum support into `Thoth.Json` and as you mentioned in https://github.com/MangelMaxime/Thoth/issues/126 we need to add more reflection methods.

I already implemented the Enum support on Thoth.Json.Net so I know what methods are needed:

- `System.Type().IsEnum` -> [source](https://github.com/thoth-org/Thoth.Json.Net/blob/feature/unit_enum_support/src/Encode.fs#L522)
- ` System.Enum.GetUnderlyingType(t)` -> [source](https://github.com/thoth-org/Thoth.Json.Net/blob/feature/unit_enum_support/src/Encode.fs#L523)
- `System.Enum.GetValues(t)` -> [source](https://github.com/thoth-org/Thoth.Json.Net/blob/feature/unit_enum_support/src/Decode.fs#L1026)
- `System.Enum.Parse` -> [source](https://github.com/thoth-org/Thoth.Json.Net/blob/feature/unit_enum_support/src/Decode.fs#L1031)

I think I can give it a try.

Is there anything I should be careful about? Any tips or guidance you can give me? :)

**Comment by alfonsogarciacaro** [comment]
The situation with enums and reflection is a bit messy right now. There are some reflection bits and it shouldn't be difficult to add support for these methods. But the problem is Fable considers enums as numbers in the runtime and in fact, if you ask for the type of an enum you get `int32`. We probably need to fix that before adding support for enums.

BTW, about `System.Enum.GetUnderlyingType(t)` as I can see in Thoth.Json.Net code, you basically don't support enums with long as underlying type. This is actually the case of Fable where enums with longs are directly not supported and all the other integers just compile to JS number, so in principle it shouldn't be necessary to check the underlying type.

**Comment by MangelMaxime** [comment]
> But the problem is Fable considers enums as numbers in the runtime and in fact, if you ask for the type of an enum you get int32.

Yes, I saw this problem too and want to fix it. Because, for now, it kind of makes the auto encoder/decoders work but it's not solid.

And lead to subtle problems :)

> BTW, about System.Enum.GetUnderlyingType(t) as I can see in Thoth.Json.Net code, you basically don't support enums with long as underlying type. This is actually the case of Fable where enums with longs are directly not supported and all the other integers just compile to JS number, so in principle, it shouldn't be necessary to check the underlying type.

I think it's still needed in order to know which decoder/encoder I have to call. And also, it's a guard against Fable not supporting all the Enum types like `enum<int64>` (long?) and `enum<char>`.

**Comment by alfonsogarciacaro** [comment]
Ok, [this commit](https://github.com/fable-compiler/Fable/commit/355d06eb6c76b327ffb8ffc89ec3134bebb7c6e8) should fix the most serious issues with enum reflection, like omitting the constructor generation and emitting the proper type. Now this:

```fsharp
type MyEnum =
    | Foo = 0y
    | Bar = 5y

let t = typeof<MyEnum>
let v = MyEnum.Bar
```

Compiles to (more or less):

```js
const  t = Reflection.enumType("MyEnum", Reflection.int8, [["Foo", 0], ["Bar", 5]]);
const v = 5;
```

You can work from here. Please check [other reflection helpers](https://github.com/fable-compiler/Fable/blob/355d06eb6c76b327ffb8ffc89ec3134bebb7c6e8/src/fable-library/Reflection.ts#L175-L223) as reference. For example, `isEnum(t)` would become something like `t.enumCases != null`. The underlying type would be the first generic. It'd be great if you could also add tests.

> For now, I'm just emitting all the cases every time you require the enum type. But probably latter we should create a `$reflection` method like for other types to avoid code duplication.

**Comment by MangelMaxime** [comment]
Awesome thank you ❤️

> You can work from here. Please check other reflection helpers as reference. For example, isEnum(t) would become something like t.enumCases != null. The underlying type would be the first generic. It'd be great if you could also add tests.

Yes, I will look at how it's done for others and will add the tests for the different method added.

**Comment by alfonsogarciacaro** [comment]
Sorry, I hope you didn't start working yet. I noticed there was a small regression and a test was failing. I fixed it (just by commenting out the part that wasn't working...) and took the chance to clean a bit the Fable AST. I removed the Fable-only StringEnum type as it didn't add much value and just left `Enum` with the same semantics as F# enums to make things clearer. Hope it helps!

**Comment by MangelMaxime** [comment]
I was going to start so I saw your message on time.

**Comment by MangelMaxime** [comment]
Would you, please, be able to tell me what code make use of [this section](https://github.com/fable-compiler/Fable/blob/355d06eb6c76b327ffb8ffc89ec3134bebb7c6e8/src/Fable.Transforms/Replacements.fs#L2714-L2737)?

For now, all the tests I write seems to go only via [this section](https://github.com/fable-compiler/Fable/blob/355d06eb6c76b327ffb8ffc89ec3134bebb7c6e8/src/Fable.Transforms/Replacements.fs#L2739-L2747).

**Comment by MangelMaxime** [comment]
Ah, scratch that, I think I understand the difference and I actually need to extends [`let enums`](https://github.com/fable-compiler/Fable/blob/355d06eb6c76b327ffb8ffc89ec3134bebb7c6e8/src/Fable.Transforms/Replacements.fs#L2303-L2310) for all the method calls like `System.Enum.GetUnderlyingType(t)`

**Comment by alfonsogarciacaro** [comment]
For `System.Type().IsEnum` adding a `isEnum` function to Reflection.ts should work, I guess. For the other, yes, I think they go in `let enums ...`.
