### ISSUE TITLE
Import of 'intl' package fails in production mode

### ISSUE THREAD

**Issue by nilshelmig** [fable-compiler/Fable#1925]
### Description
We use the [`material-ui`](https://v0.material-ui.com/#/) (0.20.1) datepicker in some old applications. For internationalization we use the [Intl](https://developer.mozilla.org/de/docs/Web/JavaScript/Reference/Global_Objects/Intl) namespace. Since we need support for Internet Explorer 11, we use a polyfill package [`intl`](https://www.npmjs.com/package/intl).
Since Fable 2.3.24 we get the following error when building with webpack in production mode.

```
Uncaught ReferenceError: IntlPolyfill is not defined
```

### Repro code
We use the component like this
```fsharp
type RCom = ReactElementType<obj>
let DatePicker = importDefault<RCom> "material-ui/DatePicker"

let datepicker props children =
  let intl = Fable.Core.JsInterop.importDefault<obj> "intl"
  importAll "intl/locale-data/jsonp/de-DE.js" |> ignore
  let props = JS.Object.assign (createObj [ "DateTimeFormat" ==> intl?DateTimeFormat
                                            "locale" ==> "de-DE"
                                            "firstDayOfWeek" ==> 1 ], props |> wrapProps)
  ReactElementType.create DatePicker props children
```

### Expected and actual results
**Expected**  
No runtime exception.

**Actual**
Runtime exception on page load
```
Uncaught ReferenceError: IntlPolyfill is not defined
```

### Related information

* Fable version: fable-compiler@2.3.24 (up to latest)
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! Hmm, there were some changes in the optimization of bindings in production mode in 2.3.24. It may happen that the `importAll ... |> ignore` statement is being erased by the production optimizations. I'll try to reproduce it.

In the meanwhile can you please try the following instead? This is the recommended way for importing only for side effects:

```fsharp
importSideEffects "intl/locale-data/jsonp/de-DE.js"
```

**Comment by alfonsogarciacaro** [comment]
Ah, ok, thanks! Then I'm pretty sure what's the problem now. When you use a import expression, even if you put it inside a function, Fable will move it to the top of the translated JS file (because you can only have imports at the file level in JS). Because of this, if you're calling Fable from JS, in production mode, tree shaking will take place and remove the `import "intl/locale-data/jsonp/de-DE.js"` statement because it's not actually used by the calling file.

To avoid this, this kind of polyfill imports should always way in the main file (the entry point) of your app. Another alternative is to add the polyfills directly to the entry option of your Webpack config:

```js
module.exports = {
    entry: ["intl/locale-data/jsonp/de-DE.js", "./src/myApp.js"],
    // ...
}
```

**Comment by nilshelmig** [comment]
I solved this issue by removing the polyfill. It seems that Intl is [supported](https://caniuse.com/#search=datetimeformat) by our targeted browsers.

But I can't find an API to use Intl, so I had to use
```fsharp
let [<Global>] private Intl : obj = jsNative
let datepicker props children =
  let props = JS.Object.assign (createObj [ "DateTimeFormat" ==> Intl?DateTimeFormat
                                            "locale" ==> "de-DE"
                                            "firstDayOfWeek" ==> 1 ], props |> wrapProps)
  ReactElementType.create DatePicker props children
```

Any idea to make this cleaner?

**Comment by alfonsogarciacaro** [comment]
Yes! You can take the [Intl module from the old Fable.Import.Browser](https://github.com/fable-compiler/fable-import/blob/a24f2c51bcfc79737427613e5c4aa5e99e114d40/Browser/Fable.Import.Browser.fs#L12129-L12241) and contribute it as a package in the [new Browser bindings](https://github.com/fable-compiler/fable-browser) :)

**Comment by nilshelmig** [comment]
Will do that :)
I'm closing this issue now, since my problem is solved. Thank you ❤️
