### ISSUE TITLE
Floating-point formatting broken in Fable 2.4.8

### ISSUE THREAD

**Issue by markpattison** [fable-compiler/Fable#1932]
### Description

Floating-point formatting has broken between Fable versions 2.4.7 and 2.4.8.

Seems likely to be related to [this commit](https://github.com/fable-compiler/Fable/commit/71377aa4823c4119a0ffdf7872ee3ee247416c58).

### Repro code

In a Fable.React app:

`div [] [ sprintf "Five percent: %.0f%%" 5.0 |> str ]`

### Expected and actual results

Correct output in Fable 2.4.7:

`Five percent: 5%`

Incorrect output in Fable 2.4.8:

`Five percent: 5.000000%`

### Related information

* Fable version: 2.4.8

**Comment by alfonsogarciacaro** [comment]
Argh, damn. I should have done more tests to avoid regressions. I'll fix that, thanks for letting me know! :+1:

**Comment by markpattison** [comment]
Confirmed fixed in 2.4.9, thanks!
