### ISSUE TITLE
List type missing chunkBySize

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#1934]
### Description

List.js is missing the export chunkBySize

### Repro code

REPL seems to be at a lower version and it does compile properly:

```
let test = 
  [0..10]
  |> List.chunkBySize 2
```

Yields:

```
export const test = (() => {
  const list = ofSeq(rangeNumber(0, 1, 10));
  return chunkBySize(2, list);
})();
```

Using this in my own application at version 2.4.6 I get this message:

```"export 'chunkBySize' was not found in '../../../../../.fable/fable-library.2.4.6/List.js'```

I got this to compile by doing

```
input
|> Seq.ofList
|> Seq.chunkBySize 2
|> Seq.map List.ofArray
|> List.ofSeq
```
Where input was a nested list.

**Comment by alfonsogarciacaro** [comment]
Strange, I don't remember when this was working or what could have caused the regression. It's not working for me in the REPL either (maybe your browser is still showing a cached version?). Anyways, it should work now and will be fixed in the next release. Thanks for reporting!
