### ISSUE TITLE
filename like "[id].fs"  created with different path

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#1936]
### Description
Hello!
I'm trying to use fable for next js
I'm using fable-splitter and fable-compiler packages.
There is a part of my App.fsproj
```xml
    <Compile Include="pages/post/[id].fs" />
    <Compile Include="pages/about.fs" />
```
package.json
```json
{
  "scripts": {
     "fableBuild": "fable-splitter App.fsproj --allFiles -o ./"
  }
}
```
starting `npm run fableBuild`
output part:
```sh
fable: Compiled pages/about.fs
fable: Compiled pages/post/[id].fs
```
`about.js` created near the about.fs `./pages/about.js`
And  **`[id].js` created with the path `./post/[id].js` but expected `./pages/post/[id].js`**
<img width="268" alt="Снимок экрана 2019-11-02 в 00 10 21" src="https://user-images.githubusercontent.com/1009015/68056879-4cffb100-fd05-11e9-8620-641aa3fe5a40.png">

[Why I need filenames like this](https://nextjs.org/learn/basics/clean-urls-with-dynamic-routing/dynamic-routing)

### Repro code

https://github.com/Neftedollar/Nextjs-Fable-simple-app/tree/repro

### Related information

* Fable version: 2.4.9
* Fable-splitter version: 2.1.11
* Operating system: Mac OS X 10.15.1 (19B88)

**Comment by alfonsogarciacaro** [comment]
Hmm, probably the file name is not important here. This is just because fable-splitter is just flattening the folder structure so it doesn't reflect exactly the hierarchy of the original files. We did this originally to avoid path conflicts when compiling files coming from different hierarchies.

@ncave I think you mentioned once that you had solved this problem for fable-compiler-js. Would it be possible to port the solution to fable-splitter?

**Comment by ncave** [comment]
@alfonsogarciacaro It should be possible, it's all [this](https://github.com/fable-compiler/Fable/blob/master/src/fable-compiler-js/src/app.fs#L81-L95) calling [that](https://github.com/fable-compiler/Fable/blob/master/src/fable-compiler-js/src/util.js#L126).

We can easily add support in `fable-compiler-js` for `PackageReference` elements in projects (e.g. to resolve the `Fable.React` dependency, etc.). We can either consume the `obj/project.assets.json` created by `dotnet restore`, or (assuming package's been already restored), do an educated guess at the nuget path to it, something like `~/.nuget/packages/Fable.React/5.3.5/lib/netstandard2.0/Fable.React.dll`. This requires the exact version to be specified in the reference (technically even wildcards can be supported, at the cost of adding complexity).

Of course, other package managers can be supported too, if we find a good mechanism to define their use in the project file. (But I'm not trying to reopen the package manager flame wars, so *fnugget about it*).

**Comment by Neftedollar** [comment]
So, can I help somehow?
@alfonsogarciacaro @ncave

**Comment by alfonsogarciacaro** [comment]
It'd be great if you could send a PR ti fix this @Neftedollar. This is the code in fable-splitter that decides the output path: https://github.com/fable-compiler/Fable/blob/bd3b30ab72966ea69ba7a45694bcc1340d42c2e7/src/fable-splitter/src/index.ts#L118-L141

You can keep the folder structure by doing something like `Path.relative(Path.dirname(info.entry), path)`. The challenge would be files that are outside the .fsproj hierarchy (you can use @ncave code for example to see how to deal with files from fable library or packages, for example). I assume the current code for deduplicating file names in case of conflict should work as is.

**Comment by Neftedollar** [comment]
@alfonsogarciacaro ok, I'll take it. 
Thnx

**Comment by Neftedollar** [comment]
@alfonsogarciacaro  how can I build it?
I've started `npm install` at the root and then:

```sh
  fable-splitter git:(master) npm run build                         

> fable-splitter@2.1.11 build /Users/neftedollar/dev/fable/Fable/src/fable-splitter
> node build.js

exec /Users/neftedollar/dev/fable/Fable/node_modules/.bin/tsc 
../../node_modules/typescript/lib/lib.es2015.iterable.d.ts(41,6): error TS2300: Duplicate identifier 'IteratorResult'.
node_modules/@types/node/index.d.ts(179,11): error TS2300: Duplicate identifier 'IteratorResult'.
Error: tsc failed with code 1
    at runNpmBin (/Users/neftedollar/dev/fable/Fable/src/fable-splitter/build.js:23:15)
    at process._tickCallback (internal/process/next_tick.js:68:7)
    at Function.Module.runMain (internal/modules/cjs/loader.js:744:11)
    at startup (internal/bootstrap/node.js:285:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:739:3)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! fable-splitter@2.1.11 build: `node build.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fable-splitter@2.1.11 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
```

what I'm doing wrong?

**Comment by Neftedollar** [comment]
@ncave  @alfonsogarciacaro  pls help https://github.com/fable-compiler/Fable/issues/1936#issuecomment-554764073

**Comment by ncave** [comment]
@Neftedollar I'm not sure, normally building the splitter involves running `npm run build splitter` at the Fable root (all the build targets are in build.fsx).

**Comment by ncave** [comment]
@Neftedollar But if you're stuck, I can take a look at adding this functionality.
Also, you will soon the option to just use the `fable-compiler-js` instead, once #1943 is accepted.

**Comment by Neftedollar** [comment]
@ncave thnx i'll try to build it from the root. thnx

**Comment by Neftedollar** [comment]
@ncave  same story = /

```sh
node_modules/typescript/lib/lib.es2015.iterable.d.ts:41:6 - error TS2300: Duplicate identifier 'IteratorResult'.

41 type IteratorResult<T, TReturn = any> = IteratorYieldResult<T> | IteratorReturnResult<TReturn>;
        ~~~~~~~~~~~~~~

  src/fable-splitter/node_modules/@types/node/index.d.ts:179:11
    179 interface IteratorResult<T> { }
                  ~~~~~~~~~~~~~~
    'IteratorResult' was also declared here.
```
**can you build splitter now with current package-lock.json?**

here https://github.com/microsoft/TypeScript/issues/32333 they said that we need just to update  @type/node but nom update is not working for me (https://github.com/microsoft/TypeScript/issues/32333#issuecomment-550227709) and few days ago it comes back

**Comment by ncave** [comment]
@Neftedollar Yes, it works for me (Node.js 12.x), and in CI. Perhaps the node/npm version that you're using is different, but that's probably not it.

**Comment by Neftedollar** [comment]
@ncave  so, I've asked two coworkers run `npm run build splitter` but they're all failed with the same error about `IteratorResult`.
BUT!
I've found that if I update @types/node now, it's fixed, there is new @types/node package was released.
So it's build now! I'll update package-lock.json with @types/node

**Comment by alfonsogarciacaro** [comment]
Would it be possible to check if this is still an issue when using Fable 3 instead of Fable 2 + splitter?

**Comment by Neftedollar** [comment]
@alfonsogarciacaro  I'll check it this week

**Comment by Neftedollar** [comment]
@alfonsogarciacaro I've checked it!
JS files stored in the same path as fs files.
![image](https://user-images.githubusercontent.com/1009015/101290799-80204800-3815-11eb-8df0-8cadda413157.png)


So we can close this issue.

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot for checking!
