### ISSUE TITLE
printf omits sign for negative numbers

### ISSUE THREAD

**Issue by zanaptak** [fable-compiler/Fable#1937]
`sprintf "%d" -1` in a Fable app incorrectly omits sign and outputs `1`.

It works in the fable-minimal sample with fable-compiler 2.3.19, and breaks after upgrade to 2.4.9.

**Comment by alfonsogarciacaro** [comment]
Oh my, I can't believe I broke this so hard. Hopefully this is the last one, thanks for reporting!

**Comment by kerams** [comment]
@alfonsogarciacaro, maybe not. On 2.4.9, positive (!) longs were printed with negative signs, and on 2.4.10 they have 2 :-D

`printfn "%d" 5L // prints --5`

Two negatives make a positive, so all good :).

**Comment by voronoipotato** [comment]
Fortunately seems like it shouldn't be too hard to write a tests for...

**Comment by ncave** [comment]
Double-negative fixed in #1939.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! Published as 2.4.11. I hope this is the good one :crossed_fingers:
