### ISSUE TITLE
tryExaclyOne was not found

### ISSUE THREAD

**Issue by thitemple** [fable-compiler/Fable#1938]
### Description

I was trying to use `tryExactlyOne` function fro the List module and got the following warning as a result:

```
"export 'tryExactlyOne' was not found in '../../../.fable/fable-library.2.4.9/List.js'
```

### Repro code

`List.tryExactlyOne [1]`

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: 2.4.9
* Operating system MacOS

**Comment by MangelMaxime** [comment]
For the `List` it seems we are pretty relaxing in term of "replacement" if we don't know something we assume the implementation exists in the `List.fs` file from `fable-library` [source](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Transforms/Replacements.fs#L1827-L1830)

But we are indeed missing `tryExactlyOne` implementation in [List.fs](https://github.com/fable-compiler/Fable/blob/master/src/fable-library/List.fs).

To add support for it, we should implement it in `List.fs` and then add tests for it in [ListTests.fs](https://github.com/fable-compiler/Fable/blob/master/tests/Main/ListTests.fs).

*I added the instruction for it someone wants to give it a try*
