### ISSUE TITLE
Type errors sometimes lead to "File not found in source list" exceptions

### ISSUE THREAD

**Issue by kqr** [fable-compiler/Fable#1940]
### Description

I got an error saying roughly

```
ERROR in ./src/Components/Plot.fs
Module build failed (from ./node_modules/fable-loader/index.js):
Error: File /Users/kqr/dev/statan/src/Components/Plot.fs cannot be found in source list:
/Users/kqr/dev/statan/.fable/Fable.Promise.2.0.0/Promise.fs
/Users/kqr/dev/statan/.fable/Fable.Promise.2.0.0/PromiseImpl.fs
/Users/kqr/dev/statan/.fable/Fable.Fetch.2.0.0/Fetch.fs
/Users/kqr/dev/statan/.fable/Fable.React.5.2.1/Fable.React.fs
[...]
/Users/kqr/dev/statan/src/Components/Card/Card.fs
/Users/kqr/dev/statan/src/Views/Diagnostics.fs
[...]
```

### Repro code

I have not yet been able to reproduce this in a minimally failing test case – and I am not legally allowed to share the code I have that does fail. I hope to find the time to reproduce it in a smaller test case, but I can't make any promises. If not, I hope I have provided sufficient clues to locate the error.

Feel free to ask me to poke at the system I have in specific ways too, if that helps the diagnostic process.

### Expected and actual results

I managed to narrow it down to the following line:

```
        let scale : obj = d3?scaleLinear((0, Array.max counts), (height - margins.top - margins.bottom, 0))
```

when I split it up into two lines:

```
        let availableHeight = height - margins.top - margins.bottom
        let scale : obj = d3?scaleLinear((0, Array.max counts), (availableHeight, 0))
```

I get a much more sensible error message:

```
ERROR in ./src/Components/Plot.fs
Module Error (from ./node_modules/fable-loader/index.js):
/Users/kqr/dev/statan/src/Components/Plot.fs(71,38): (71,39) error FSHARP: The type 'int' does not match the type 'float' (code 43)
```

which is indeed the real error – if I cast the integers to float, it compiles again.

### Related information

I have prevously gotten this mysterious error on other occasions as well, frequently when testing things I'm unsure of – only now have I realised it's a type error in disguise. It might very well have been in those other occasions as well.

- Fable version: 2.4.10
- Operating system: macOS 10.14.6

**Comment by alfonsogarciacaro** [comment]
Hmm, the error message does ring a bell but I cannot remember where I saw it. Do you have multiple .fsproj entries in your webpack.config? In those cases, sometimes Fable gets confused about which project a file belongs to in these cases.

**Comment by kqr** [comment]
There are multiple .fsproj entries in the webpack.config.js, but I don't think that's the problem, because even if I delete webpack.config.js and run `fable-splitter src --allFiles`, I get the same problem.

**Comment by alfonsogarciacaro** [comment]
I haven't been able to reproduce the error yet so not sure if it's still an issue, please reopen if you've seen it again with Fable 3.
