### ISSUE TITLE
'Some (box null)' is compiled as 'null' instead of Some(null)

### ISSUE THREAD

**Issue by Alikont** [fable-compiler/Fable#1948]
### Description

When using Thoth json Encode.nil I encountered that my results are matching as None.

While investigating I found out that ```Some (Encode.nil)``` is being matched as None pattern.

### Repro code

[fable.io REPL](https://fable.io/repl/#?code=DYUwLgBA5uBqCGwCuIBCB7AHgCgJQQF4AoCUiAZXQFsQJsAjLCAOyWGFyKNEhjAWQgASvADueQiTKUadVu05Eq8MAGMAFtDiIUGHPlEBLMJqIAfCtVoA3CAFoAfBFQAndKIDOIFwDoAItQ+qujMHuigPsDoUNgARABSYcyWNLGcFgByIbSOzm6e3v6BwaHhIJHRcYkhEFnMIGlcymqafAIoIuIGxqYWMjb2Tq7uXr4BVEEhYRFRMbGdKQ3ptdmDeSOF45OlM5XzYiv1aUA&html=DwCwLgtgNgfAUAAlAUwIYBN4O0iyyoLhgAOAtMgI4CuAlgG4C8A5AMID2AdmMt2QCoBPEsmYIAxlx7cWPAB5gA9OGgBuCSFQAnAM75G1MADMyADmZYcwHeK20SYBDq3jGAIgD6HgBIB5AMr8XopQtABGOopaaOJgAHQkWuzo1LG0XHEQtJxxAFY6bjDAijZ2DpbY1rb2js6unj4BQR4h4ZHRqLFk6OwQCUkpaRlZOfmFxaU1FUihnADWCNFQ7jpgglDIOiDI+G5E0UbuXn6BwaERiuI6kWHUUBComdlxVwUIitPAswtLK2sbWx2YD2IAOR0apxa50ir0UqCgUCeOVeew+iCsq3WyGmigAVAhfJwoIIEJwduhkOgEEZ2FoELRJJwnKgICQNghcYp0dgXlJUNlkFoyDpaAAvTYIOJhKDscQLADe3Jw2HQtB0bNQggAXNSNnJVEqAL5K3ncflkoUi8U6SUMrgIRXK5VhTpzADmSWonHQZEkMq0OsEyAR7AA7ganTgHlo3dkdQAGBAAVhI+qNSom-2xcGK2wwWGAYWSJPEUFQ13cqBI5EZBAFWkKGdV9Hp6HcwayWzIVZIe1L5Z07fuapA3er40UzfgxSL6EE0+UkFgQA&css=Q)

FSharp code

```
let getValueBox() =
    Some (box null)

let getValueRaw() =
    Some (null)
```

Compiled JS

```
export function getValueBox() {
  return null;
}
export function getValueRaw() {
  return some(null);
}
```

#### Expected

Some (Encode.nil) should be matched with Option.Some

#### Actual

Some (Encode.nil) is matched with Option.None

### Related information

* npm show fable-compiler version: 2.4.11
* Operating System: Windows 10 1903

**Comment by alfonsogarciacaro** [comment]
You have found the first case to answer [this comment](https://github.com/fable-compiler/Fable/blob/fdc960905b21faa4e3cee70b2fb2f0a0cdd3d34f/src/Fable.Transforms/Transforms.Util.fs#L306) affirmatively :) I'll make that `obj` options are wrapped too :+1:
