### ISSUE TITLE
Add one more instruction line to Quick start instuctions

### ISSUE THREAD

**Issue by jackfoxy** [fable-compiler/Fable#1949]
### Description

4. Open http://localhost:8080 in your browser after you see the "Compiled successfully" message

### Expected and actual results

I've been experimenting with SAFE stack, and I was used to the Fable client automagically starting in my browser. It took me a while to realize I had to manually open in browser.

**Comment by alfonsogarciacaro** [comment]
Hi @jackfoxy! Thanks for your comment, what's the quickstart guide you mean?

**Comment by jackfoxy** [comment]
https://fable.io/

**Quick start**
Try Fable online or get started in your local machine with our set of samples (more info):
1. Install .NET Core SDK
2. Install Node.js
3. Then type in a terminal:

**Comment by alfonsogarciacaro** [comment]
Done, thanks!
