### ISSUE TITLE
can't use event exposed on generic interface

### ISSUE THREAD

**Issue by smoothdeveloper** [fable-compiler/Fable#1950]
### Description

Event registration doesn't work when done through a generic interface.

### Repro code

```fsharp
let [<Literal>] willRun = false
type IMyType<'t> =
    [<CLIEvent>] abstract member OnI : IEvent<int>
    abstract member Send : 't -> unit
type MyType () =
    let e = new Event<_>()
    
    member x.Send (i:int) =
        e.Trigger i
        
    interface IMyType<int> with
        [<CLIEvent>] member x.OnI = e.Publish
        member x.Send i = e.Trigger i
printfn "hello"
let t : IMyType<int> = MyType() :> _
try

  if willRun then () else
  printfn "subscribing"
  let subscription = t.OnI.Subscribe(fun i -> printfn "on i worked %i" i)
  ()
with e -> 
  printf "oops subscription %A" e
```

the `OnI` event can't be subscribed to from the generic interface, skipping the registration and the program runs to completion.

### Expected and actual results

I expect the registration to work the same as if it was on the concrete instance, it currently causes

> Uncaught TypeError: Object(...) is not a function

### Related information

`$ yarn info fable-compiler version`
> yarn info v1.16.0
> fable2.4.11

**Comment by smoothdeveloper** [comment]
sorry for the glitch, it submitted before I could edit, updated the issue description.

**Comment by smoothdeveloper** [comment]
The current workaround is to strip `[<CLIEnvent>]` from the code behind `#if FABLE_COMPILER`.

The issue also happens with inheriting generic base class exposing such events.

**Comment by alfonsogarciacaro** [comment]
Hmm, there's some magic the F# compiler does to make does CLI events compatible with C# and some .NET frameworks. But tbh I don't know/remember what it was. We added [some special cases](https://github.com/fable-compiler/Fable/blob/fdc960905b21faa4e3cee70b2fb2f0a0cdd3d34f/src/Fable.Transforms/FSharp2Fable.Util.fs#L419-L438) in the AST handling to make some related tests pass, but tbh I don't really know the mechanism well :/
