### ISSUE TITLE
Cannot resolve Aether functions

### ISSUE THREAD

**Issue by 2sComplement** [fable-compiler/Fable#1952]
### Description

Not sure if this is a regression of #624 or a new problem, but I can't get Fable to compile when using Aether.

### Repro code

Repro repo is [here](https://github.com/2sComplement/fable2-samples/tree/master/withpaket) where I added some dummy code to exercise the Aether functions.

### Expected and actual results

Expected: Fable should compile

Actual: 

`npm start` results in:

```
ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
fable2-samples/withpaket/src/App.fs(14,17): (14,35) error FABLE: Cannot resolve Aether.Optic.set
 @ ./src/App.fsproj 1:0-25 1:0-25

ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
fable2-samples/withpaket/src/App.fs(15,12): (15,25) error FABLE: Cannot resolve Aether.Operators.op_HatEquals
 @ ./src/App.fsproj 1:0-25 1:0-25

ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
fable2-samples/withpaket/src/App.fs(16,17): (16,36) error FABLE: Cannot resolve Aether.Optic.set
 @ ./src/App.fsproj 1:0-25 1:0-25

ERROR in ./src/App.fs
Module Error (from ./node_modules/fable-loader/index.js):
fable2-samples/withpaket/src/App.fs(17,12): (17,26) error FABLE: Cannot resolve Aether.Operators.op_HatEquals
 @ ./src/App.fsproj 1:0-25 1:0-25
```

### Related information

* Fable version: `2.4.11`
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
Hello, @2sComplement there is a [Fable.Aether](https://www.nuget.org/packages/Fable.Aether) package which is a port from `Aether` can you please check if this one is working for you?

I don't expect `Aether` to work by default with Fable because it probably doesn't contain a `fable` with all the source files in it for the compilation process.

**Comment by 2sComplement** [comment]
@MangelMaxime  that did it, thanks!
