### ISSUE TITLE
define and support #FABLE compilation constant to Fable REPL

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#1954]
In fable REPL, I would like to write this:
```
#if FABLE
.... 
#else
...
#endif

```
While at first sight this look useless since fable Repl runs on fable anyway, it will help code portability.
For example, I can write a console application and copy the code and paste it to Fable Repl and happily run it without changing anything by using above constant.

**Comment by MangelMaxime** [comment]
Hello, 

you can now do:

```fs
#if FABLE_COMPILER
let x = "Fable"
#else
let x = "not fable"
#endif
```

and it will generate `export const x = "Fable";`.

This is the same behavior as standard Fable compiler
