### ISSUE TITLE
Cannot resolve f#+ modules

### ISSUE THREAD

**Issue by Mateiadrielrafael** [fable-compiler/Fable#1963]
### Description

I just found out about f#+'s monad computational expression and I wanted to play with it, but fable keeps throwing a random error

### Repro code

I do not have a repo, but I just started with the default fable project, installed f#+ (tried with a lot of different versions) and tried running the app with both webpack-dev-server and webpack

Here is my code:

```fsharp
module App

open FSharpPlus

let someOption =
    monad {
        let a = Some 4
        let! b = a

        return b + 2
    }

printfn "hello world %A" someOption
```

### Expected and actual results

Heres the error I got:

![image](https://user-images.githubusercontent.com/39400800/71642582-3995a580-2cb6-11ea-9e2a-0c8abd3c214a.png)

I was expecting to get Some(...) in the browser console

### Related information

* Fable version: I tried with both 2.4.3 and 2.4.12
* Os: Pop os
* Tried with both npm & pnpm
* Tried with both paket and nuget

**Comment by MangelMaxime** [comment]
I think the problem is that FSharpPlus is not compatible with Fable. 

In order to use a library with Fable, the library needs to include the source code in the package under a `fable` folder. I don't think FSharpPlus does that and so Fable can't find the source code to compile the library into JavaScript.

**Comment by alfonsogarciacaro** [comment]
Actually FSharpPlus is [partially compatible with Fable now](https://github.com/fsprojects/FSharpPlus/pull/160), I guess you need to use one of the latest versions. Unfortunately not everything is supported yet, for now it's mainly about the extensions, the monad CE doesn't seem to be included in [the tests](https://github.com/fsprojects/FSharpPlus/tree/master/tests/FSharpPlusFable.Tests). Not sure if it's possible/easy to support it.

**Comment by wallymathieu** [comment]
It would probably help to get some debug output around why the compiler fails to emit a particular js file.

**Comment by wallymathieu** [comment]
How do I get more information around compiler errors?

**Comment by gusty** [comment]
@Mateiadrielrafael I think you didn't try with F#+ v1.1-RC1 which is supposed to be fully compatible with Fable, although, like @wallymathieu says, we're finding some issues, still not sure at this time from which library the issue comes from (Fable or F#+).
