### ISSUE TITLE
Use of obsolete Fable.Import.JS

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#1965]
### Description
`Error	FS0193	The module/namespace 'Fable.Import.JS' from compilation unit 'Fable.Core' did not contain the namespace, module or type 'Float32Array'`

I think this could be because the [Fable.Import.Browser.fs](https://raw.githubusercontent.com/fable-compiler/fable-import/master/Browser/Fable.Import.Browser.fs) still uses the now open obsolete Fable.Import.JS

### Related information

* Fable.Core 3.1.4
* Fable.Import.Browser 1.3.0
* Windows 10

**Comment by alfonsogarciacaro** [comment]
Yes, Fable.Import.Browser is itself obsolete :) Please use the appropriate package from [fable-browser](https://github.com/fable-compiler/fable-browser) instead. More info here: https://fable.io/blog/Announcing-2-2.html#fable-browser

**Comment by davidtme** [comment]
@alfonsogarciacaro thanks for the quick response and info (I missed that).  I can't see and reference to webgl i.e. `WebGLRenderingContext` in fable-browser repo?

**Comment by alfonsogarciacaro** [comment]
Seems I "forgot" to port the WebGL bindings 😅 But luckily they've been added recently: https://github.com/fable-compiler/fable-browser/pull/42
