### ISSUE TITLE
Support tagged template literals (e.g. for styled-components)

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#1973]
It seems that [styled-components](https://styled-components.com/) is all the rage now; for example, it's officially [the future for styling in Material-UI](https://material-ui.com/discover-more/roadmap/).

It seems to use a new kind of syntax I haven't seen (and don't yet understand). I have no idea what, if anything, must change in Fable for it to support this in some way or another, but I thought I'd raise an issue sooner rather than later, just in case.

(I'm not talking about a new syntax for the F# code, which of course is impossible for Fable to do anything about directly, but rather some way to utilize styled-components from F#/Fable.)

**Comment by 0x53A** [comment]
I think this is a tagged interpolated string: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Template_literals

**Comment by 0x53A** [comment]
The good thing is the tags from the tagged interpolated strings are just functions.

If you don't need to add any logic, it's easy:

https://styled-components.com/docs/basics#getting-started

```ts
const Wrapper = styled.section`
  padding: 4em;
  background: papayawhip;
`;
```

```f#
let Wrapper = styled.section([|"""
  padding: 4em;
  background: papayawhip;
"""|])
```

----

If you do need the props logic, it becomes uglier:

```ts
const Button = styled.button`
  /* Adapt the colors based on primary prop */
  background: ${props => props.primary ? "palevioletred" : "white"};
  color: ${props => props.primary ? "white" : "palevioletred"};

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;
`;
```

```f#
let strings = [|
    """
  /* Adapt the colors based on primary prop */
  background: """

    """;
  color: """

    """;

  font-size: 1em;
  margin: 1em;
  padding: 0.25em 1em;
  border: 2px solid palevioletred;
  border-radius: 3px;"""
|]
let Button = styled.button(strings , fun (props:MyPropType) -> if props.primary then "palevioletred" else "white", fun (props:MyPropType) -> if props.primary then "white" else "palevioletred")
```

--------

I think to actually use it you then need to wrap it in React.createElement:

```
div [] [
    React.createElement(Button, butttonProps)
]

**Comment by inosik** [comment]
Could be possible already, albeit pretty ugly:

``` fsharp
open System

// TODO: Come up with proper types
type StyledToken = obj
type StyledComponent = obj

type Styled private () =
    static member button ([<ParamArray>] style : StyledToken array) : StyledComponent =
        failwith "To be done"

type ButtonProps =
    { Primary : bool }

let button = Styled.button ("
    padding: 4em;
    background: black;
    background: ", (fun props -> if props.Primary then "paleviolettred" else "white"), ";
    color: ", (fun props -> if props.Primary then "white" else "palevioletred"), ";
    fonts-ize: 1em;
")
```

Another alternative would be to define the components in JS/TS and import them.

**Comment by CedricDumont** [comment]
Hello, 

Some times ago, I wanted to use fable and this kind of feature for hyperhtml and couldn't come to a good solution. (hyperhtml is also using js tagged template literal)
I just took a look at Fable compiler's code and came to the type `TemplateLiteral` in the file _AST.Babel.fs_, but it does not seem to be used anywhere.
I am interested in working on this issue (of course if no one already is).
If that's ok, could you point me to some technical documentation (if there are some) or the best way to start?

kind regards

**Comment by klcantrell** [comment]
I came up with a hacky solution that looks like it will work for my purposes, just wanted to share.

Bindings:
```fsharp
type IStyled =
    { div: obj array -> obj }

[<ImportDefault("styled-components")>]
let _styled: IStyled = jsNative

module styled =
    let div styles props element = React.createElement (_styled.div styles, props, [ element ])
```
Usage:
```fsharp
let StyledApp = styled.div [| "
    background-color: ", (fun props -> if props.primary then "blue" else "red"), ";
    height: 100px;
    border: ", (fun props -> if props.primary then "20px" else "10px"), " solid black;
    border-radius: 10px;
" |]

// appView defined elsewhere
let App = StyledApp { primary = true } (appView())
```
It works because of the way that styled-components happens to process the arguments passed to the tagged template function. It'd be better if f# had support for string interpolation but until then, this kind of solution will work okay for my side projects anyway.

**Comment by inosik** [comment]
That's kind of what I had in mind as well. And as of now, this is the best we can get, besides maybe leveraging JS/TS to define components.

To support this properly, we either have to wait until string interpolation lands in the language (dotnet/fsharp#6770), or come up with something ourselves. I wouldn't "fork" the language, though.

**Comment by AngelMunoz** [comment]
[lit-element](https://lit-html.polymer-project.org/) also uses interpolated strings and really lends itself to be used [functionally](https://lit-html.polymer-project.org/guide/concepts#thinking-functionally)
I tried using it yesterday but it's quite ugly as well
![image](https://user-images.githubusercontent.com/8684875/100755260-39f85e00-33a9-11eb-9135-3f44a74e4a34.png)

**Comment by inosik** [comment]
String interpolation is in F# now, so we can plan how to use it with Fable. The obvious use case does already work with Fable:

``` fsharp
Console.WriteLine $"x = {42}"
```

To enable the "tagged template literals" use case, we'd need to extend Fable to support [`System.FormattableString`](https://docs.microsoft.com/en-us/dotnet/api/system.formattablestring?view=net-5.0). Library authors can then build on that.

**Comment by alfonsogarciacaro** [comment]
Some support for `FormattableString` has been implemented in 3.2.2. I haven't tried it yet with JS tagged templates, but I think something like this _should_ work: https://gist.github.com/alfonsogarciacaro/ea8a3cfe07e773664ea5078141ca9f82

**Comment by texastoland** [comment]
Would it be possible to add `jsTemplate` to `Fable.Core.JsInterop` such that `jsTemplate Lit.HTML $"<div>Hello {name}</div>"`? Better in Fable.Extras?

**Comment by alfonsogarciacaro** [comment]
Yes, the function would be much simpler. An attribute would require a plugin or modifying the compiler. It would be a good idea to standardize something like this, but Fable.Core is a bit tricky because it doesn't contain actual code, only metadata and many calls are resolved by compiler magic. Fable.Extras could be a good place to include the function. It should also be simple to add it directly in your projects:

```fsharp
let jsTemplate (template: string[] -> obj[] -> 'T): FormattableString -> 'T =
    let convertTemplate (s: FormattableString) =
        let str = s.Format
        let mutable prevIndex = 0
        let matches = Regex.Matches(str, @"{\d+}")
        Array.init (matches.Count + 1) (fun i ->
            if i < matches.Count then
                let m = matches.[i]
                let idx = prevIndex
                prevIndex <- m.Index + m.Length
                str.Substring(idx, m.Index - idx)
            else
                str.Substring(prevIndex)), s.GetArguments()

    fun s ->
        let strs, args = convertTemplate s
        template strs args
``` 

[Example in the REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpK0S1AOgBUwAPJQgJTAHMBXAGwEMAnAUTJFbAQQEtgEBFiyMwSKACsEpVCBYooACgILmKAFxRkrfhFoBtALpQAtAD4owAEZST5qwHJiASm0AxYK1QakzG3EYJD0DRygXKABeLCg4qHFJAGMhADcwViQ5dSVlBE9vXyR-QLBg0NpXaNj42sSdEOidQi8fDRrauPrUehLxKG4wVIBJCAATciaABg7O7o0kgAteJppackIAWQXlhDyQgBooAAEAIgBvAB0xgGoAX1PXWdqAQVZWZjhCfX5JZSKlrxCABhYD0CCSG5QACMVWUADNwVB+I5np04vx4cioAAeKAA3YgsEQqBIZYQNHouoSfFNAlAwz8YyUqldGn8MZkJqDEbjcgs1k80YTLk4sz4wjCyZQogAGUgtDJAqpukIMHoNl0+loyg5ZCORClXPFeqemFZtTAjAQYGV6NV6s1IW1yiFfLIrlcRwQhAA4hI3gxUJAkHszbNEdAEKjzVT6roEEc2LRo1EoCkIOlMtlFGAdCy1LmGqxo8mRJgsAB6StQTjMeTiLA4aAeALiIk8USYepjeioVBwHMaMDsAz6PP7EvaLUGExwsvaWz2YxVGKxuIAKRghAzCGA7cYwB1p0MmxgvuMpyOhgAPiz4d5sWmpqTgMWffKDGTzDCoGNgHaUA2MAXIJoQjLMuuFqYtieJloQn6KospLklA8EQbMN4rl29QoMgKirrM9RcmmADMAAsRE0r2-aDk0MhDkoNEDoxI5jhAtpQcxdEACSnF4b78NG5zGlApF3EBvRAWwyLCcoACsRxmAA7K4DxdnhSDKK4QA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADibxgSlOgQAjNqgHioybdoYAiZMTISuyGg5ETQ9MLGxiGAB5YQ4MVEQ6DDA2NihtZLYMXURkkFzDNk0IZDBuVAxcN2QAc1ziTUDyjEC83L9tNMRLSIQFe0cLJUhYIA&css=Q)

**Comment by texastoland** [comment]
I managed to simplify it a bit:

```fsharp
type JSTemplateTag<'T> = string [] -> obj [] -> 'T

let jsTemplate (tag: JSTemplateTag<'T>) (raw: FormattableString) : 'T =
  let strs = Regex(@"{\d+}").Split(raw.Format)
  let args = raw.GetArguments()
  tag strs args

// Example
[<Emit("up($0,...$1...)")>]
let up (strs: string[]) (args: obj[]) : string = jsNative

let up' = jsTemplate up
let name = "f#"
System.Console.WriteLine(up' $"hello {name}")
```

([See REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpK0S1AOgBUwAPJQgJTAHMBXAGwEMAnAUTJFbAQQEtgEBFixI44KACkYpVCBYpizWgB4A5MQB8UALxRkrfhFoBtALpQAtDuAAjAFYXrOzaMyMwSKA4RyFzChQABRIKgBc0rJoAUoqGtoAlCGszADukQBiwKyogWF2njBIRibJkZp6WFBQnt6GCHpQNLTkwQACAEQA3gA6ACYA1AC+nYmEMAr8SMGpaYTZuYGJ1bVeUGy0jfpzhADiXgCCrAyokEgIwSuYNWG0BiWNmyKYWAD0b1CczPKeWDjQTLMQpgQgAYRyYHcplU7FQ02CnXoIGCABIAAwAGkIONRAEYcYREmMtOYsHUoMiQg1IoZjGZzMlgs9IvYnIyoLSSvSmr4AHKBfgANyhrw862R6l5fhiijAlJA5PWEB+8v0nQAZgBiTpYeDINDgoQIYCeQgAdSMKAAMsYwMFJVBUZ0ABZgRiMYBQboqs6ja5AA&html=DwCwpghgJgfAUMAzgYwE4EsAOAXeB6PAAhG200QC4DsB3dUsVAOmQHsBbPbMADwkWysANhAB2UPAIjYArojwBGACwAmABwBmFUoBsOgOzKADKv361RuG1EDCMzIQC8hABQDUiADSEmviKgBzRABKJ3hCQndEJgAzEWwAWQhMFzdsVG90UMdwiMIAbXdvfyD89ABdAH4mQQBVTExGAGF+MBdg8rgI4KYAK1Z0URcAImHgq1YbYTAmIVYAl3sAA3AhOcIAEgBvYd7EYYBfJfHgSTQsXAQ8cGh4YAAjVigATzu8R5f4IA&css=Q))

`[<Emit>]` was necessary because tag functions are invoked like `tag([str1, str2, str3], arg1, arg2)` in JS. I tried an interface using `[<ParamArray>]` but it was significantly more verbose and didn't emit what I expected.

`FormattableString` is so close to the JS representation I don't see the benefit of an attribute either.

**Comment by alfonsogarciacaro** [comment]
Oh, that's nice! I always forget you can split with regex 😅 

Yes, curried functions in F# are restricted in the sense they don't accept spread or optional arguments. For that we need a delegate. "Delegate" is the original term in .NET for function pointers, and F# uses it to denote non-curried functions. In Fable at the beginning we tried to use delegates to represent functions coming from JS, but the syntax was not very nice, so now Fable tries to hide the distinction by automatically uncurrying lambdas. However, sometimes like in this case we do need a delegate declaration. You can do it like this:

```fsharp
type JSTemplateTag<'T> = delegate of strs: string[] * [<ParamArray>] args: obj[] -> 'T

let jsTemplate (tag: JSTemplateTag<'T>) (fmt: FormattableString) : 'T =
  let strs = Regex(@"{\d+}").Split(fmt.Format)
  let args = fmt.GetArguments()
  tag.Invoke(strs, args)
```

A nice side-effect is this makes it easier to import tags as values (with lambdas this sometimes messes up the uncurrying if we don't declare the import as a function). Example:

```fsharp
let html: JSTemplateTag<HtmlTemplate> = importMember "https://unpkg.com/lit-html?module"
```

[See in REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpK0S1AOgBUwAPJQgJTAHMBXAGwEMAnAUTJFbAQQEtgEBFixI44KACkYpVCBYpizWgB4A5MQB8UALxQAJmEZ1mKKMABmUZKwQAuG0lb8ItANoBdKACoo71QAFNmZUAEFWVmY4LW82WgcLACMAKy8oAFodTVFMEyQoFIQ5BTMwKAAKJBVHGRLFMGU1TS0ASkrLVCRHADFgVlQzaqSTGGdXWnbHTT0sKCh8pzs9KBpacgqAAQAiAG8AHQMAagBfbdbCGAV+JArOyj6Bs1a5hbAC+IQV+8IAcXeIgxUJAkAgKi9MPNqrRCABJCAAN2AAGswBVbAgADRQT4QrAAenxUE4oQUYCwOGgPWYIzAhAAwv1ydhwFSaSYGUzCFIEPCUKxQLlxJIABJIVCMeplFaufmWZgAY3KkAMUEJUECLCVAAtgIwjKxcotteLGLVZGhSkoVKoxRKpSgdPp+PJ+kgALJoJJgVhQbYmpAgByE+gQEDImEK4CofGMG4ZE0SgD8qGABiYYG2RveUETjHUKyKDvKeawiwgoXK+m2lgAxFnMDJCFHhHq6YxgLQKnmCwASf3GDtQXYV4FnCFAA&html=DwCwpghgJgfAUMAzgYwE4EsAOAXeB6PAAhG200QC4DsB3dUsVAOmQHsBbPbMADwkWysANhAB2UPAIjYArojwBGACwAmABwBmFUoBsOgOzKADKv361RuG1EDCMzIQC8hABQDUiADSEmviKgBzRABKJ3hCQndEJgAzEWwAWQhMFzdsVG90UMdwiMIAbXdvfyD89ABdAH4mQQBVTExGAGF+MBdg8rgI4KYAK1Z0URcAImHgq1YbYTAmIVYAl3sAA3AhOcIAEgBvYd7EYYBfJfHgSTQsXAQ8cGh4YAAjVigATzu8R5f4IA&css=Q)

**Comment by alfonsogarciacaro** [comment]
I'm having too much fun with this. This is a full (simple) Elmish app with lit in only 70 lines of code (including adapters): [REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpJQGICGARgDZgB0AwsAE5hY7SGkXV3kBSCAkhCjaAbhoAIQEB3BGBpDcY4JOnkAKnHAJZ0AKIlUASwQALLFgD0pqNQAmYKEmBQCVgiCRQOMO2hAkCKBHYOeADEUABmtKh+KFZQyDR6EADmGpiowFYArmRQyt6+KFAAvFhQdmq2ygRJADwA5MoAfMVQNmRJfrbAYXFINAgAXL0JyQDaALpQAFRQozUACgQ0BKgAgjTLcI2TSylDwEQAVhNQALTNDSaYZWRuAMZ0nVAAFEjVQ1W1DY0AlC9hqCQQzwkWixDIMD6iSSfyGDWKpTKUFuwwCRVyYAAHkhyAAlMBJbJLLSYkB0BAIPTACAIPEErHPAACACIAN4AHSsAGoAL7Mn7kGA+PRIZ4AnEgmhRJA-RE3MBuXZo8KA8gAcQV60JqEgSAQz1l1yRbyS5F4ADdgABrMDPeIIAA0jhoKUNZgsABkRVAiIkrNDUuksjkvW4SkakBUoAAJJCoEh5VA+J7oxL8MIEO62SCxcxQea+LOGYAkGwyTCIlGGOMkD75Toqao1WPxxPJlDNVNJ2hIACyaCI0igzOrSBAg3MmQgICtpruwFQphIItO1fjAH4g9kwMzKwqoHQIGWXkCYzW2wUwH9nmBazHlL2PTo0LqfkMp96uyAe-3UIOaMOo7jgMk7TrO5Dzouy5IKuNabhk267hWmB5jo+hGFA4gioYUChlgW45PMAhJMsqAIkaKJYUghihi8ehWEM8TQteZLACRKxDERbGkfUuxOnUQa3vxqAIEkTqhuQLYJvWHZvvmxE8XUfFQAJGRCSpIlibhIqSeeMlgJ2cpIiit4tPIig0OQAAiC7kFYwB3JkOp8OQSQKs+zlICIcDcFYzz0W6RpIsi+5SEgkJPIJJCtAYIB+HcOHhsFyUhW4KBJpe+IINkYbydxKzkOaehgOIUCsexZFRTFCBxUgCVGSlEmHse6XtmAWU5VAt5XClXEVeQVGGDACoRYUYWjbY5WkVcea8CKegEMuABetjUat+mOEejhQIYt7gOWVY1i0F4Ng8YBPBJa4kFckbgFAWjmrqVQuvug2Ijqf5DtRBjkAAaotmS2OiryGAYUADOuzTRg+Hq8CAmRIB5r6FQD9DIXmqwgCAWC3bYvZqdFSVIqyUD-SQgPg8M0JQDyN1Rr2onkcFAA+liGAQyRgGTFPdFTyRXCiiTegaLQk9zQPDgA6rQpbMjTTqUKgVjkBA1Jo1gKKZCAziFM8mkDAzMIvFFBsE38RNlNKCVQJpmHYUZrOUOznPi1AEAla75wNcTNsE3b1Gk6jLTu+Irs8grSsq2rAv7kVJW+201W1dbRNXVAAAkzJZ1gNT+uaUB3L4FJFMyUSJKc858AQiTSMyjSIjUiTw-cRcICXTcI0hKVlOaqNFKyUV-ajtNBcljI2nAWv92EU4vGA5pDA9r5nM08-kG8L04q7zPNE7HNudvzT+jV8WGDy9fIWUNQnxAjTRreJAOAPBND+TYA8gAhDUpg3xf395xfLOSEsB9VIuQVAVpQErCgELNwWsda2DjuILAO88r9UGrRZkt50KGFOC4EASFUFQNQOQGgU4sBAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohkqCl26mAIhSkKUjwodFxI2t5YOMBojJh0aD5IUBB0uiDkfqQR1jEMVkpOLvCIKpCwcEA&css=BYFwtgNgNAsAUAIwPYBMCeACA3vDeMBmSAdiALQDOAlgF4CmAXBgIwBsADgB4Dc8AvvHgA6MAEMqxMgGMSIccToAnbLnwoqFdhFFomBCHR6q8AdyooQwJswAMNgKS84+DMDpUA5qGt3HxjABWAK4UIFQEaNKydKRMUjEgSk4uohCeklSJYBRxCUn++oZk6op0UmEkcUgQQWDETgJwwhLsQSAqzvjsoijqxB5MQgBMAKylYMn4RKSUtIwsHEadpuaWTKM2XJN4YooeEmTIICBIYNbjDfBAA)

I guess it should be also simple to convert Lit templates into React components for users who want to integrate components written in HTML into their apps. Now we just need an editor that can recognize HTML in F# code 😸

**Comment by alfonsogarciacaro** [comment]
The [clock sample](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQpJQGICGARgDZgB0AwsAE5hY7SGkXV3kBSCAkhCjaAbhoAIQEB3BGBpDcY4JOnkAKnHAJZ0AKIlUASwQALLFgD0pqNQAmYKEmBQCVgiCRQOMO2hAkCKBHYOeADEUABmtKh+KFZQyDR6EADmGpiowFYArmRQyt6+KFAAvFhQdmq2XMoESQA8AOTKAHzFUDZkSX62wGFxSDQIAFx9CckA2gC6UABUUGO1AAoENASoAII0K3BNU8spw8BEAFaTUAC0LY2l5eC5NQ3NrXiR0cRkMP2JSeeXyiaYZTIbgAxnQulAABRIGrDKr3RpNACUw2qdQRxWuZTCmWgYVQbgumLKUCBIwCRVyYAAHkhyAAlMBJbLLLRUkB0BAIPTACAIemM6kQgACACIAN4AHSsAGoAL4ixHkGA+PRICF42nPGhRJCIomAsBuPbk8L48gAcUNGyZqEgSAQEL1AOJZWhSXIvAAbsAANZgCHxBAAGkcNBSTrMFgAMqqoERElYvql0lkcjG3CVnUgKlAABJIVAkPKoHzgimJfhhAjA2yQWLmKALXw1wzAEg2GSYa6kwwFkgo-JdTgIVG1fOF4ullAtcsl2hIACyaCI0igIt7SBAQ3MOJAPvdwOAqFMJFVZ17hYA-CnsmARd3DXFPUkByWChQ4XVx0XB9PWno5xoRdl1XdckE3bdTF3fdyEPY9TyQc8+2vDJb3vZ1SToCAO0hJBhm-Sd30RSEwH7PNlAXKMdDQO1kSgHFY1nEB5yXVAVxoNcNy3QYdwgPcDyPE8zwvEgUNTO9-gbHR9CMKBxFVQwoHTLAbxyBYBCSFZUAxDDH3kpBDHTSE9CsYZ4i+YiIXZYBNNWYZ1JsrSGj2EN6hTUjXNQBAkhDdNyAI38wCReyNKc+oXKgNyMg8yKvJ8pTVX8vtCK6Gd9RJR9SNaeRFBocgABEj3IKxgGBTJbT4cgkkNaiKqQEQ4G4KwIRMiNnRdUkpCQD5wXckg2gMEA-GBRTMxdcaMrcFA3y6BkEGyDNG1C1ZyE9PQwHEKBrNs7S+oGhAhqQEb0pdPysJw6apzAOaFqgUj-gmhydvIfTDBgQ0esKLrPtsbatMkixeFVPQCFPAAvWwDMhwK7BqVIGyMqQ0ACewoDoABHTI9DoOxDFsBBn1h74Ig4iAwGQMBYhgAA1c0vBm-wsB7PtXyulR7gAfRnSkGYoUEwHBPyRKZx8CZfHm2dHLnWhSlBYLBQo-LF-5s1uLRPTtaowz0hTrltNjVwMgxyGp0HMlsCkoUMAwoEGS8WlzCio14EBMiQWraNWs36C7TAGzWEAQCwVXbAXaL+opShMk2TWAO6Xp8q6ZQ4+DnMl05GpyZlvRgR9KAeigROUGT21-lJRJgdBn7HR0l0o5jvgS9sIuwCb8gADkFBDShUCscgIB5H2RbcTIQGcQoIWT3OoDJmlLPrrCkCbqAOaQOPiLG4kF9j20Z+pJBu97-vB7Lx819tGgp7zxMDuG0aiXk7CFHILreH4T1QfVHEV5+E79sOkakIr6FyTnHDuCgnQuhDAARgAAzwOIgAHxaHoJIA86AqxzMvTeZREF5mANHfOvQKxEjwQuRIbt45QBIe1KAeD3qHmwkQ6hfAiT63YrjY2psSDm1rhNKAOpAFGwCK9P+eDcwENJj8GeYjYBgEYbEaAFwZG0JdGQihhQlEtAgA9Yk7DDbWz5JQEgpUfQLGkDWPgmc+ETXVCYvwnC+TcPNsRCwwjyB4GyCQOkBDsK6LKPoji7iPgCD9DY8agjFLCLkrrVRxJxGSJ-sokUp4ki9k0mASA6F+F0KgOQiAlCkktBFOIa2KBsn8PofInksQObSJFMEWBAAmAAzAATgAGwtPQmwkCQTDFKn6L6MAAB1EyBlwkukiY4mJBlZESMIXU9RBTCh1OUU02RDCalFKgNA-xAi+mOPIFGSASQJk4IiXfGZoi4m4PwYs6RTSACs5BZH5MKWsloLSXmbOqUwz5UAAAssDXm+ymYc9xniSDeN8bEC5UyrnRJuTkhJDzlHQKaaClFciFE-2WR86RHSQWnxBCY3OuYCBMKhHHFE69wmkjIMkc5dgwEnKZcYWhpJKVJByBSTFsCZh5L8IYcgCxuCCvPqwMlZiLF2kzkSHslKrAAA1WgQieSCgV0oMrssFYeAIEJuU5DOEKgyorxUWH5YiSBxJFXYQAJpqo1eQLVOqzmKVmFyaAhrkjGtNSKsVUBLUuutUSMWUAAAkIpo1YFqKeMm1wqTQKKCKDVFS4DJtTbAipVImlFDFIYJVyrZTXDgHmgtSr7UludPEYZ+bJWDNCWAatZRa1+jOPJKwBl61gJCcMsZXbDCyiaLGoSZMWhlCwNGnpmA7VWGUKAXCNLch0ouQy05zKG1svdQqx8dBvQ8LXjyVoYR7FTTAc4n2HVHxGotlAflgqFzCvNYKiE+62xu25NANxYCoUwpxFYG1Bo3CFuwqqy2zrXWMvdXq4ABrb3nH9S+4NsDQ2csfKBqwjqIOaqgNq6DEzPWJEhAhk1T6zWBpQ2hl04ao0xswLUYE2NgRkGuMCKk+bMPFrY3ATjlaW1oxTU0ipYQ9DQp7baRtwzh2jqYzQFjQViRTvo8PKAa0NqQm3o3OOLLbTERvgA++tCRKRunbG8N6nxAiGABxkUAqBVwIc-AipxJO3dpFN82BIAqQihHc6RjzHWO0PYymtNRJgS8azS5wTIpAVPOi6J8TDTYEiAAOxtMoFoXztRTByYUxOqAuixQsdMRSqlCyglgIq4iATFbsILpAJCCrumKDVerdcYr0qyuxAhO8woDa+tgBqx1zDDXISDZa+QQbw2wVQE66VpVkItlMIbctwDtXRuLohGtyba2ZvXAC-JoLLoQtRfC5FsLtCaApu6USRLJAU2NLSxlrLYahl+ke809pXTottrAB28ZhgU3QN85O-zuXAuKbBzlsWfmzO+yelpcgqAzHLW0hXNeVdoSFFHuPWwlmsDIKWo5Far0YCZCIAgUEehXBfshNiaAAKe59x6OTogLXL45x9E6IniPScKSMiKUiMlDBnBcCAdCvO0fkBoDiIAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohkqCl26mAIhSkKUjwodFxI2t5YOMBojJh0aD5IUBB0uiDkfqQR1jEMVkpOLvCIKpCwcEA&css=Q) with Lit.

**Comment by texastoland** [comment]
> A nice side-effect is this makes it easier to import tags as values

This is exactly what I was trying to accomplish! Static methods weren't working at all. Should I PR delegate pros/cons in the [FFI doc](https://fable.io/docs/communicate/js-from-fable.html)? 

> The [clock sample](https://github.com/fable-compiler/Fable/issues/1973#issuecomment-902436694) with Lit.

Haha this is my fave. The beauty of ECMA interpolated strings is you can embed anything from event listeners too looping over child components. That isn't possible with type providers right (I love Feliz but thinking about JSX)?

**Comment by alfonsogarciacaro** [comment]
> Should I PR delegate pros/cons in the FFI doc?

That'd be absolutely great :)

> That isn't possible with type providers right?

Well, with type providers you can generate new methods on-the-fly (they've even been used to [create games](http://pinksquirrellabs.com/category/type-providers.aspx)) so _maybe_ it could be possible to chain the template parts and the arguments (and make them typed), but definitely interpolated strings are a better fit here.
