### ISSUE TITLE
Support for web component classes

### ISSUE THREAD

**Issue by OnurGumus** [fable-compiler/Fable#1974]
A typical web component class would like like as below:
```
class Button extends HTMLElement {
  constructor() {
    super();
    this._shadowRoot = this.attachShadow({ mode: 'open' });
    this._shadowRoot.appendChild(template.content.cloneNode(true));
  }
  static get observedAttributes() {
    return ['label'];
  }
  attributeChangedCallback(name, oldVal, newVal) {
    this[name] = newVal;
  }
}
```
I have found no way to generate this especially the static get part via Fable.

**Comment by alfonsogarciacaro** [comment]
Yes, static members are not attached to the class/constructor right now, only abstract member implementations. But maybe you can use a hack like this:

```fsharp
let inline attachStaticGetter<'T,'V> (name: string) (f: unit -> 'V): unit =
    JS.Constructors.Object.defineProperty(
        jsConstructor<'T>, name, !!{| get = f |}) |> ignore
```

[Example in REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQoksiKG2aAUgM4CSEALmFqAQSg1AJYRI9hQ4DBnADGACwDKIhl1EAeAOQAVAHxQAFBDgBbMAC4o1Blh4BzAJSaAZoeAIAVhcMBXCF04BeAlF9QH1JgQxlguogzYSmoA-Fq6YFbyALRQ1mz4HNy8-ILCYlIycgDiYMLMUQA0igBq6nF6hiHmVhq2UG4eUEnqNc7t7l4+fpSS5MEmYRFY1KgA8o5g4agAJmDW-AAKLOBYDACeGkN+fgFBIZORKqoVUNp6NwCEDwDeAD5QZqVQnqlQrwC+Vle6i4ZggFHSAG15EUkPY4EgANxQACCCBCYgY6CQcGo1FUAF0CPtwFAABLKACyABkAKIoPSMDRWbz4Y56HQIZhQAD6qCEIgkknEcGWwAA7sy7I5vv5qAA5IRcABueHwxL2pIAQi5hMAIMzvkcsuJmJ0KTT6WBGQxmcbMjzqCKxeKAErAYBeKAIXFoAX5YWiiV29X4f1CwqiEplLDyHV6iAVHmqY0AIns1GYquWKOEpgQurA1FTxtabk0Vm6UEhr1TOK5SFTrwJFgIQA&html=Q&css=Q)

**Comment by OnurGumus** [comment]
Thanks for this I will give it a try and let you know.

**Comment by OnurGumus** [comment]
@alfonsogarciacaro confirmed that it works
[repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQokUAQlsAO4DOYWBR0ZlNWqAKgJ7hX3jTzI0mHKgBSVAJIQALrVAECAbQA8AQSRJKAOQCuGgDIBLWVjhIAfAF0C0rmCgAJNgFl9bMAFsQSOLICiKB6Q0lAAvARQkVCGEAAWtMaOLvoBnsERUYhU0qYAxiG5wDLBAFxQACLAuTpBMjCmAOa1IRTGsVANYNIANFA00gr4KuqaFLoGxrRmVjZ2Sa7uXj7+gcGc4GEZkSp+HsaYENlYOvnYM-hRUFk5cPlQ6Di+YGU6EIkAtObzbp7eT6nNQYoEKyJZPMpOBa-ZZgAHBTYXKIAE0oEFycGyUBR1WaqFyjxWaRkUAAFAAiUF-WRkgCUg0pMNQMQgtEh+igyneWygZN5GWU2Q4KHM3LxRWkcBitCgAG9uZEQHAkUiYg0ygAOEAADwA3NyAL7chA6aTSIqy+VYwxUP4cMrIKoAaz1iMuwAAbrQAGajMqxQzKyAuy4K4BUYyGIplHDLQye4MhxXK1VlAAMUAAjAA2bUJy5e8XvcMAL2emZzustBZk7woYEMDVi0ntwCQSLzUVkWuk7w93t9UDAGkMIHDVA7kQo-tkRcVuTLEEophAE6g1SwVGwZRAwBiJlXwBNSClZUXLNXrSR0liZQzqdTAFJV-EG02ygAWVO5y0IYBaouGMWKZQL+WBIrQ7y-pWrpRKB4FYLe2p9K2AZQAAxHAGaYZhq4ILcjoNOQrxImUaFeuRFG4X+RaxEqlBplAABMSHvkh6ZYA0eEkqm3Q8TxUCpqgqYAKw0r06bMVqUCalJ7GcXAJLZhm3RKSpWbKQJqDvjSq6FJoCHoQAzFmxnGbpOgbluUA7nutAdoaiLKAA9IKwr8iq7prj4VBUKEZKFDIkoslgZIijByjGqaRTmPoiBDs5kVmhAYWRM5HlhbyZKDCoADimh4RY1j4B4wBIno9jVNkwAeHCMhUAilzAliYBelKpJDkS0haHAQRlEcqq9LYZTAAgABWNJhFAo1UN10hxng+BKMoeUjdMRW2BsADKtEohQABKwDANIJITeEMFBB4CDSte1qoHAIB8Ei6D+m2JJDmUTDULQ7B2FQqBaKVYCnVNM2+PN3IXVdWBQDdf0AI46LQHCbR1pxYCSNAoGjfU5KqNIfeQX2sOsYB-WytUhKEIOzeDi34E1MTHiyVymrcsSbRKc25MoADkbBfCSEA9WW-UQA0E0kl6w1jfjUCvIkVPTQcRwnGaWC8-zAD8QtBBy7xQF6QJdNEEBM-YvgSrk7Oc4YuQ5V0Jga70PMAGoCzrIu42LEtS3LbwhJ8UCu7L8uU9yoibRgRQq2jf0APJjWA+SoOBrUsgACuQ4BYLYpJK9HOSq9gGvmL0Hu9AAhBXMoAD4dMbVNelANf6nSME118DaLjg2XLflZg6lAqgIEctzSOg3lUOcwwaNoehIEYJhrbMGzk6sMgnQ1USQ9KAD6qCdNIqimlghiRWAJIWwZovizjp9i5N00056EOeFDUD7xbbPbXRFAkiN40yg-12gdI6j9QZzRfjBa4eQChFBZPkMAT0zBIDwrkR0Lx-ZQEDqHbkMCx4s1xufZ6cAxZIPQCgtBGC+hewaFAAAVFAABDCmFjWwV8XBdMZ6jHGAvSYphCor3sCQE0SVN5nUuDEeIp8Qhr06idQYjVjZUB2pQUBzYoDALUYdSmIEMRoC-lbLRFBSS1ygCVcCk0yQMDJM3VuijkTAEtJEJquRNDMypgyJ4YpigyDxO4sAANLEkkLkDZxfRVH7R0XdB6kAnovSRKSNxRQwl0yUSERK5oqYqN-uo1ACMkYoyxmrUkZJMkQFpA4yIO9oaw1QDgCA8FxHhPKUyCAwU2R6xhv6P6h9j5EJNPYckPgrpIEqWkqIfYsCn0sfvAKCDZDII0FQ8R1l77SCbv5eBSdFlrkofhLKEzIhTJmfYOpV8z6DJIWQpZqD8KC2Fr0VsSIXZmDLmACgrykDAzqQ0+CpI24EEMdbMGdsHa0GUCIqKEBei7y+NYketBPRIn6afc+VBbGS1eAC9hUBFB1zJCMoctia6WEBfgSqZoarr2kH9VObVyQeA4JBURRQyS9HzocQuaNIWsuSm3IAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZWYiFOOzq4eJKS6AFxKSjRcpADWAObxUhBKAAIA7kjhx6TcfGBRl9d9t1z3ugWnAEzxAAzxAGYlBIaLowH1KFAkPgeLpKLoAKzkdAoRxIbT5QrFUo1CpzXF1JbuFbrTbbPaHY5nJ43O6w4Gg8EQSHQ96nACM8R+vwZYIhSChMIeWRymImOPKYHg1UliwaJI2Wx2ByOfWpV1pb3pui0aCEvQgHPinKBOvQ+r6IrGWMmBPgCBKIFQGAd4RSQkkUBQul0HlRFCkPBQOXRRTgOFwECE5HCRnBXEwXvCAo8HA44qjMbj3GlSjdevtjsgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

I hope one day we get native support for static members.

**Comment by alfonsogarciacaro** [comment]
Hmm, I wouldn't change the current behavior of member declarations, but this could be an interesting case for a plugin in Fable 3.

**Comment by OnurGumus** [comment]
I also noticed one thing if intentional, virtual members of non-abstract classes are not mangled. I personally find it useful.

**Comment by OnurGumus** [comment]
@alfonsogarciacaro one last thing, the case for built-in  web components extending existing elements mandatorily require the class syntax and no polyfill available. It maybe something to be considered for future development of Fable. I have not find anyway to build one with Fable.
