### ISSUE TITLE
Cannot set object property to `null` using Fable.Core.DynamicExtensions

### ISSUE THREAD

**Issue by nilekirk** [fable-compiler/Fable#1982]
### Description

When setting a property to `null` using `Fable.Core.DynamicExtensions`, the property is not changed at all.

### Repro code

    let a = obj()
    a.["p"] <- "apa"
    a.["p"] <- null

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCc0BECeEcAtgJYDGAogB4AukAzqcBAwLABQnKtUcUAXijAEAKwAUASk5xUAbQBEIBQF0oAHgC0UBXBBwFM+UtUbtEAK5IknEFlIRaAM2gKApAEEFfY8pVA&html=Q&css=Q)

### Expected and actual results

Expecting that `a.["p"]` is `null`, but actually it is still `"apa"`.

The following workaround works around the issue though:

    let Null: obj = null
    a.["p"] <- Null

### Related information

* Fable version: 2.4.15
* Operating system Win10

**Comment by hez2010** [comment]
A better workaround since it won't generate a function to get `null`:

```fsharp
open Fable.Core
open Fable.Core.DynamicExtensions

let [<Global>] ``null``: obj = jsNative

let a = obj()
a.["p"] <- "apa"
a.["p"] <- ``null``
printfn "%A" a.["p"]
```

**Comment by inosik** [comment]
Using the `?` operator from `Fable.Core.JsInterop` does work as well:

``` fsharp
open Fable.Core
open Fable.Core.JsInterop

let a = obj()
a?p <- "apa"
a?p <- null
printfn "%A" a?p
```

Prints `null`.

**Comment by inosik** [comment]
The assignment is getting replaced by Babel, namely here:

https://github.com/fable-compiler/Fable/blob/8f0fd71a84997f635d407190ef6e8da6b29a3093/src/fable-babel-plugins/index.js#L89

If the right hand side is `null`, the whole assignment gets removed from the macro. I'll make a PR to fix this.

**Comment by MangelMaxime** [comment]
@inosik Thank you for the fix

@nilekirk If you update `fable-loader` or `fable-splitter` depending on your project configuration to the latest version it should work.

**Comment by nilekirk** [comment]
Thank you all! 😊❤
