### ISSUE TITLE
About curry and js arrow function

### ISSUE THREAD

**Issue by albertwoo** [fable-compiler/Fable#1983]
Hi, I am trying to make a binding library for React.Spring. There is a js function which is something like:
```js
function test(item, key) {
  return function (prop) {
    return ofArray([1, 2]);
  };
}
```
What is the corresponding type of F#?

I tried something like:
```f#
type Demo1<'Item, 'key, 'Prop> = 'Item -> 'Key -> 'Prop -> int list 
type Demo2<'Item, 'key, 'Prop> = 'Item * 'Key -> 'Prop -> int list 
```
But both types are not working?
Anyone can help me?

**Comment by MangelMaxime** [comment]
Hello,

I was able call to bind the test function to F# code using this:

```fs
type Demo3<'Item, 'Key, 'Prop> = System.Func<'Item, 'Key, System.Func<'Prop, string list>>
```

[REPL demo](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWo+408ya1AtiNnS4QBCTAO6VGqACLAuuXHQCe4KJLBdgAZgA8AcmoMuAGig6A0mAXGdABSYgAfFAC8UAMoLKB1DACuEAMa6+mpW5pZuHl6+Abq2oMaeWACWEADmUEhJnvb2cgD0eVAARNy8WHRFUHQAFmBVYJ5QAGZ+-nRJwNAi1Un+1VBZUAAmYP5IcDhDA9A1dQASACoAsgAyVYi4KHRQXArRbR3QAFwqappaiSmpCXTJaTd3qY4uIilDwCIA-AyecltQAA9nDs9q12p1ULQAG7AADWYAAFEUkgYoFC4EgfGAisYivCFGiMViigBKSEQGHwpEgOyEzHYkm4ciuVD+TqUYAkJDAVIIgEkoA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZW4U46YYCJIHgrKeSgMKHNgRXA4+5jGNFzDXAtIumAAFHS8EAA0mADWSEIAlJgA3nsH+zFgNG0ZyOJzAGTOVySHFIH2+v1+-0BZwA2rckA9nq9HlDSABdNQ-eGYAC+BKJxMJuFKNQqiBUqAwCGA4RSQkkUC2ug8KFIFCkPBQOSQ2l2+2AaEYmDoaA8SCg2V0IHIPNI7nZnNl8roiuVvImSglDHgJRZaCE8DpqlgcCAA&css=HQYwhgNiCuFgLgewE4AIDeAoVPUHcBLAE3gAsAuVAFgAYB2ABwA8BubXAIxSIFNlKATM1Qc4IANaoAzogjE2uEdz4BaZGCIFoUygEYArMwW4GGzQDsA5nppHMAX0xPQkGHCTIVHaPCTmM7DikPASWpPCUtHaKpkQW1qgG0bjwPEzwKpCh5pQgPOapyMY4ALZgyJYEOaiGrIGoAG588ATgEJlyltUlxEQQPMX4xGSU+rWDAGaIBSpSBABePIJUyThy5jwqwaHhkbZ1ijDIMvyoDIhVhYNcTLOkGoh4lDSoLwDMwqJgEmyOmC5QWAIFBeHx+YAEKQqTSVeABRQcb7iSzIRDQcxEFQgWQoSidcIonj5X7ONpuYGeby+aYQqGIBjwzhIlFojFYnGnfHwUTQAYOIA)

**Comment by ncave** [comment]
@albertwoo
What @MangelMaxime shows definitely works, and is very short. The only downside is you need to use .Invoke() to use it, or an adapter function.

The more idiomatic way is to use the Fable import functions or attributes:
```fs
// see https://fable.io/docs/communicate/js-from-fable.html
open Fable.Core.JsInterop
let test (x: 'Item,  y: 'Key): 'Prop -> int list = importMember "mylib.js"
//let test (x: 'Item) (y: 'Key): 'Prop -> int list = importMember "mylib.js" // works too

let x = (test ("Item", "Key")) "Prop"
// let x = test ("Item", "Key") "Prop" // works too
// let x = test "Item" "Key" "Prop"    // works too
// let x = (test "Item" "Key") "Prop"  // works too
```
There are many variations on the same import, check them all out [here](https://fable.io/docs/communicate/js-from-fable.html).

I personally like the use of interfaces to model the shape of the imports:
```fs
// declare interface to describe your imports exactly
type MyLib =
    // doesn't have to be generic, if it's not
    abstract test: 'Item * 'Key -> ('Prop -> int list) // note the parentheses
    // other imports ...

// import it
let myLib: MyLib = Fable.Core.JsInterop.importAll "mylib.js"

// use it
let myFunction = myLib.test ("Item", "Key") 
let x = myFunction "Prop"
```
Also, have you tried [ts2fable](https://fable.io/ts2fable/)? May help with the initial type generation, if there is a TS type definition on hand.

**Comment by albertwoo** [comment]
@ncave Hi, thanks for you help. I may misleading you. What I want to do is create find a way to define a f# callback function which will give js to call when needed. It is not call a js function from f#.
@MangelMaxime  Thanks for you suggestion, it works pretty good. But the code may not not be very nice for the end user:
https://github.com/albertwoo/Fun.Animation/blob/905f0100b26d024f19b9be19686b282edf719a38/demo/src/Client/App/ReactSpringDemos/RenderPropsDemo_Trail.fs#L28-L44

Thanks guys!. And if anyone IS interested on React.Spring fable binding, there is a demo (https://albertwoo.github.io/Fun.Animation/). Your suggestions are very welcomed.

**Comment by ncave** [comment]
@albertwoo I see, if it's the other direction, then just adding some side effect should force the uncurrying (see #1915 etc.):
```fs
let test (item, key) =
    let mutable _i = 0
    fun props -> [1;2]
```

**Comment by albertwoo** [comment]
@ncave Thanks for your inspiration. It makes the api nicer now.

**Comment by MangelMaxime** [comment]
@albertwoo You are right my solution make it hard to write the F# code and even to consume it.

@ncave Thank you for showing the interface way, I didn't think about using the parentheses at the end and not the start :D
