### ISSUE TITLE
Seq.head, Seq.tail, Seq.skip are not working as expected

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#1988]
Reported in https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/69

> 
> 
> Ok it seems that the problem is, `Seq.tail` and `Seq.skip` is not working in fable.
> 
> ```fsharp
> open Fable.Core
> let tweets = [ "Hi"; "Hello"; "Hola" ] |> List.toSeq
> JS.console.log(sprintf "tweets are %A" (JS.JSON.stringify(tweets))
> JS.console.log(sprintf "tweet head is %A" (JS.JSON.stringify(tweets |> Seq.head)))
> JS.console.log(sprintf "tweet tail is %A" (JS.JSON.stringify(tweets |> Seq.tail)))
> JS.console.log(sprintf "tweet skip 1 is %A" (JS.JSON.stringify(tweets |> Seq.skip(1)))
> ```
> 
> returns
> 
> ```
> tweets are ["Hi","Hello","Hola"]
> tweet head is "Hi"
> tweet tail is {} // Expectig ["Hello", "Hola"]
> tweet skip 1 is {} // Expecting ["Hello"; "Hola"] 
> ```
>

**Comment by ncave** [comment]
I don't think the problem is with `Seq.tail` and `Seq.skip`, but with the `JS.JSON.stringify` and sequences. E.g. if you do `JS.JSON.stringify(tweets |> Seq.tail |> Seq.toList)` it works.

**Comment by ncave** [comment]
I mean, direct conversion of a sequence to string prints an object on .NET too.
But you should be able to print it with sprintf, so I'll add that.

**Comment by MangelMaxime** [comment]
Thank you @ncave I didn't explore the issue but it seems like you are right. I am taking a look at your PR
