### ISSUE TITLE
Fable splitter doesn't respect constants

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1990]
![image](https://user-images.githubusercontent.com/57396/75888753-26c15d80-5e2c-11ea-824c-8ded2fbf174b.png)

If I run fable-splitter from yarn then `#if REACTNATIVE` is not enabled. Is it possible that the splitter doesn't respect this setting in the fsproj?

**Comment by ncave** [comment]
@forki Is that a referenced project perhaps? Is there a way to get a small repro project?

**Comment by forki** [comment]
No it's not a referenced project. We don't use project references


ncave <notifications@github.com> schrieb am Mi., 4. März 2020, 16:27:

**Comment by ncave** [comment]
@forki If individual output files are what you're after, there is also `fable-compiler-js` you can try.
In any way, a small repro project would go a long way to clarify what's wrong.

**Comment by forki** [comment]
Would https://github.com/SAFE-Stack/SAFE-Nightwatch/blob/master/splitter.config.js#L25 create such a problem?

**Comment by ncave** [comment]
@forki Could be, in the sense that it seems to only handle one `--define` parameter.

**Comment by forki** [comment]
I wonder if it overwrites the ones that are set in the fsproj instead of
appending to those.

ncave <notifications@github.com> schrieb am Mi., 4. März 2020, 17:09:

**Comment by ncave** [comment]
@forki In theory there should be no need to pass additional symbols since the `fable-compiler` (invoked by `fable-splitter`) reads them from the project file using `Dotnet.ProjInfo`, but if it doesn't for some reason, you can pass them in through the command line or the `splitter.config.js`.

**Comment by ncave** [comment]
@forki It should be [concatenating](https://github.com/fable-compiler/Fable/blob/master/src/Fable.Cli/ProjectCracker.fs#L428), not overwriting, but ymmv.

**Comment by ncave** [comment]
@forki I haven't looked in depth at the `ProjectCracker`, so it's theoretically possible that it's not collecting the defines from referenced by dll projects (when they are dll + sources, i.e. Fable packages).

It's an open question which is more preferable, the current practice of merging all sources from all references packages and then Fable-compiling them (with merged defines), or compile projects separately and merge the JS outputs afterwards, which would be more exact since the inner referenced package versions can differ. But that's yet to be implemented.

**Comment by forki** [comment]
The reason for the additional command line parameter is that we have debug code in yet another compiler switch. So during development we pass that extra parameter. For release we pass another one.

**Comment by ncave** [comment]
@forki Sure, all I was saying is that the `splitter.config` you linked above only passes along one of the command line defines, so you might want to fix it if you need to pass more than one. Or you can hard-code them in the `splitter.config`.

I know for sure that `fable-compiler-js` definitely collects and combines all defines and source files from all referenced projects and Fable packages. Perhaps the `fable-compiler` can be fixed to also combine defines from all referenced projects and Fable packages, if it's not already doing that.

**Comment by alfonsogarciacaro** [comment]
Thanks to @ncave, in Fable 3 ProjectCracker collect `DefineConstants` from all referenced projects so hopefully this is not an issue any more.
