### ISSUE TITLE
HMR not working with relative paths

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#1995]
I prepared a repro for this case:

* clone https://github.com/forki/fable-elmish-electron-material-ui-demo
* dotnet tool restore 
* dotnet fake build

This opens the electron demo in HMR mode.

Notice how I added a file that's not in same folder than the fsproj:

![image](https://user-images.githubusercontent.com/57396/76140144-aa12c700-6057-11ea-9985-b60d02bc594e.png)

HMR works with all files that are somewhere in the same folder as the fsproj or below, but not with that relative path to Helper.fs.

Try to change the text here:

![image](https://user-images.githubusercontent.com/57396/76140167-daf2fc00-6057-11ea-8c24-51e06b1531a1.png)

Notice how the app is not recompiling and the text doesn't change:

![image](https://user-images.githubusercontent.com/57396/76140182-fa8a2480-6057-11ea-895f-a64c2a35c174.png)

Now touch any of the other fs files and see how HMR works.

/cc @MangelMaxime @ncave @cmeeren

**Comment by cmeeren** [comment]
Outside my area of expertise. Ping me if you need anything from me. :)

**Comment by forki** [comment]
@cmeeren actually just wanted you to know that people use it. Great work!

**Comment by matthid** [comment]
Interesting, we use repative paths as well and indeed hmr is not always working, I never quite made this connection. Thanks for reporting.

**Comment by forki** [comment]
I assume the problem is here:

![image](https://user-images.githubusercontent.com/57396/76402867-4ef91100-6384-11ea-8122-8e9834f467c1.png)

@MangelMaxime  any ideas how I can add `../../shared/*.fs` to that regex?

**Comment by MangelMaxime** [comment]
Hum, this regex is just for telling webpack when you see a file looking like that pass it to the `fable-loader`.

If the problem is with the webpack configuration I would put my bet on the `resolve.modules` options.

In your case something like:

```js
module.exports = {
    //...
    resolve: {
        modules: [
            path.resolve(__dirname, 'src'), 
            path.resolve(__dirname, 'shared'), 
            'node_modules'
        ]
    }
};
```

But this is with no guarantee. I don't know yet how webpack is detecting files for HMR.

I think I remember that `fable-loader` say to webpack here are all the files I am working with. But this is because the entry point for an F# project is the `.fsproj` which is what we pass as the entry point of webpack too.

**Comment by Zaid-Ajaj** [comment]
@forki The webpack configuration is missing the HMR plugin, at least from what I am seeing. Can you try this please?
```js
const path = require("path");
const webpack = require("webpack")

function resolve(filePath) {
  return path.join(__dirname, filePath)
}

module.exports = {
  entry: [resolve("src/Renderer/Renderer.fsproj"), resolve("src/Renderer/scss/main.scss")],
  output: {
    filename: "renderer.js"
  },
  plugins: [ new webpack.HotModuleReplacementPlugin() ],
  module: {
    rules: [
      {
        test: /\.fs(x|proj)?$/,
        use: {
          loader: "fable-loader"
        }
      }
    ]
  }
}
```
It doesn;t check whether the mode is dev or prod but that can be added later

**Comment by forki** [comment]
@Zaid-Ajaj the file is called `webpack.additions.renderer.js` so I assume electron comes with HMR enabled by default. And HMR works for all files that are directly next to my fsproj. also now I think the issue is not with HMR but with fable's own file watcher since the command line is not showing fable output.

@MangelMaxime tried your suggestion but I couldn't make it work

**Comment by alfonsogarciacaro** [comment]
The watcher in Fable 3 seems to react properly to sources using a relative path in .fsproj. Please reopen if you still have problems.
