### ISSUE TITLE
Storing result of Seq.tail and printing the result several times gives Seq.emty after the first one

### ISSUE THREAD

**Issue by joemphilips** [fable-compiler/Fable#1996]
### Description

In [this PR](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/69), I noticed that applying `Seq.tail >> Ok` and unwrapping `Ok`  will make inner sequence empty.

It might be that I am misunderstanding something about Seq, but weird thing is that the problem does not happen when I use `Seq.skip 1` instead of `Seq.tail`

### Repro code

```fs
  let tweets = seq [ yield "Hi"; yield "Hello"; yield "Hola" ]
  let tweetsTailR = Ok (tweets |> Seq.tail)
  match tweetsTailR with
  | Ok ys ->
      JS.console.log(sprintf "%A" (ys)) /// this will become empty unexpectedly.
```

### Expected and actual results

Expected result
* prints `seq [Hello; Hola]`

actual results
* prints `seq []`

### Related information

* Fable version: 2.4.19
* Operating system: macOS Mojave 10.14.6

**Comment by ncave** [comment]
@joemphilips Seems to be working in the [REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwCgUAuUBA7mGAQM5QC8UlYAjlAN5QBEAEgJbsDcHTmCRJg-QcCRx2UAL74KxMhUoAVONyQAlAFxQtYSgFckBADyUCWbhADm9JgBp6Vm7YB8tKAHkA1lAAKUnIqKAAfTwBlJlQCDSQASlwAWzgCAGMACyUQtXitKBJuAkzcMJ9-AE9qAFp3XChGqAApSNR04AhKSTRRWwDKEGsIAgAzDgBSAEEZAOqEpPKAUSwsbCgADyg6hqbW9s7ulFQ+gPZ14QZ2BKA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltZW4U46YYCJIHgrKeSgMKHNgRXA4+5jGNFzDXAtIumAAFHS8EAA0mADWSEIAlJgA3nsH+zFgNG0ZyOJzAGTOVySHFIH2+v1+-0BZwA2rckA9nq9HlDSABdNQ-eGYAC+BKJxMJuFKNQqiBUqAwCGA4RSQkkUC2ug8KFIFCkPBQOSQ2l2+2AaEYmDoaA8SCg2V0IHIPNI7nZnNl8roiuVvImSglDHgJRZaCE8DpqlgcCAA&css=HQYwhgNiCuFgLgewE4AIDeAoVPUHcBLAE3gAsAuVAFgAYB2ABwA8BubXAIxSIFNlKATM1Qc4IANaoAzogjE2uEdz4BaZGCIFoUygEYArMwW4GGzQDsA5nppHMAX0xPQkGHCTIVHaPCTmM7DikPASWpPCUtHaKpkQW1qgG0bjwPEzwKpCh5pQgPOapyMY4ALZgyJYEOaiGrIGoAG588ATgEJlyltUlxEQQPMX4xGSU+rWDAGaIBSpSBABePIJUyThy5jwqwaHhkbZ1ijDIMvyoDIhVhYNcTLOkGoh4lDSoLwDMwqJgEmyOmC5QWAIFBeHx+YAEKQqTSVeABRQcb7iSzIRDQcxEFQgWQoSidcIonj5X7ONpuYGeby+aYQqGIBjwzhIlFojFYnGnfHwUTQAYOIA) (v2.4.18), please check your compiler version again, just in case.

**Comment by joemphilips** [comment]
You are right. When I cleanup the directory caches and restarted, it worked.
It also worked in new clean repository.

Sorry for the confusion, I really don't understand how paket and fable works in detail.

**Comment by MangelMaxime** [comment]
I was able to reproduce the problem reported in the original PR.

If you add `printfn " tweetsTailR is %A" (tweetsTailR)` before the active pattern, then you will see this result:

```
 tweetsTailR is Ok seq [Hello; Hola] 
seq []
```

Reproduction code:

```fs
let tweets = seq { "Hi"; "Hello"; "Hola" }
let tweetsTailR: Result<seq<string>, string> = Ok (tweets |> Seq.tail)
printfn " tweetsTailR is %A" (tweetsTailR)
match tweetsTailR with
| Ok ys ->
    printfn "%A" (ys)
| Error x ->
    printfn "or else"
```

I checked against dotnet fsi and it seems we should have:

```
 tweetsTailR is Ok (seq ["Hello"; "Hola"])
seq ["Hello"; "Hola"]
```

**Comment by MangelMaxime** [comment]
Smaller reproduction code:

```
let tweets = seq { "Hi"; "Hello"; "Hola" }
let tweetsTailR: seq<string> = tweets |> Seq.tail

printfn " tweetsTailR is %A" (tweetsTailR)
printfn " tweetsTailR is %A" (tweetsTailR)
```
