### ISSUE TITLE
Uri ToString does not match .NET

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#1999]
### Description

`System.Uri.ToString()` does not appear to be implemented correctly. 

### Repro code

```fsharp
open System

printfn "%A" (Uri "https://fable.io/repl/")
```

### Expected and actual results

Actual:

> [object Object]

Expected (as seen in `fsharpi`): 

> https://fable.io/repl/

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`

```bash
✗ yarn info fable-compiler version
yarn info v1.21.1
2.4.21
```

* Operating system

```
Ubuntu 18.04
```

**Comment by MangelMaxime** [comment]
It has been fixed in version 2.4.22
