### ISSUE TITLE
How to make Fable to copy required JS files/folders to 'outDir', and watch them for changes ?

### ISSUE THREAD

**Issue by zenininja** [fable-compiler/Fable#2004]
### Description

I've set of dumb React components implemented in JS/Storybook. Now, how do I make sure that fable compiler copies these components to the out directory ? 

### Repro code

For example,

`let inline StoryBookUI (props: obj list) (elems: ReactElement list): ReactElement =
    ofImport "default" "../storybook/index.js" (keyValueList CaseRules.LowerFirst props) elems`

With the above code I'm able to import the storybook component. However for this to run, we need the fable compiler/splitter to copy all the files under the ./storybook folder into the out folder. How can I achieve that ? 

### Expected and actual results

Right now when we run the fable splitter only the /storybook/index.js file gets copied to outDir, but not all the files under it. So it results in JS error :(

**Comment by MangelMaxime** [comment]
Hello, 

in theory, if your file `../storybook/index.js` include `imports` directives to the other files, they should be included by Webpack.

**Comment by zenininja** [comment]
Thanks for the prompt response..

**Comment by Luiz-Monad** [comment]
I'm doing this to solve this problem.

**Comment by mohandev** [comment]
Thanks @Luiz-Monad, I need figure out how to do this in react native with metro config. In case if you are familiar with that please let me know.. The metro config documentation is not very detailed..
