### ISSUE TITLE
dotnet msbuild process failing on fable packages

### ISSUE THREAD

**Issue by aggieben** [fable-compiler/Fable#2006]
### Description

During a fable build, a child `dotnet msbuild` process seems to be building all the fsproj artifacts from fable package dependencies in `.fable` and failing.  I'm very new to Fable so I may not be describing things very accurately. 

Please see also https://github.com/Zaid-Ajaj/elmish-getting-started/issues/2 for more information and @Zaid-Ajaj 's attempt to troubleshoot with me.

### Repro code

1. Clone https://github.com/Zaid-Ajaj/elmish-getting-started.git
2. yarn install
3. yarn build

### Expected and actual results

Expected: build succeeds.

Actual:

![image](https://user-images.githubusercontent.com/1321/78306573-5c2f9880-7509-11ea-9055-018dca350f37.png)

And when trying the command directly:

![image](https://user-images.githubusercontent.com/1321/78306592-681b5a80-7509-11ea-8785-24a018290d81.png)

### Related information

* Fable version: 2.4.22
* Operating system: Windows 10
* Dotnet SDK Info: 
![image](https://user-images.githubusercontent.com/1321/78306772-ca745b00-7509-11ea-84c5-edd0800eb769.png)

**Comment by MangelMaxime** [comment]
Hello, 

I am unable to reproduce...

Can you please try to force `Fable.Elmish` to use the latest version by doing:

1. `dotnet add .\src\App.fsproj package Fable.Elmish` --> This should add `<PackageReference Include="Fable.Elmish" Version="3.0.6" />` in your `src/App.fsproj`
2. `yarn build`

Are you able to build others Fable projects?

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime did you try to reproduce the issue using same dotnet SDK? it seems like the internal `dotnet msbuild` task is trying to build these projects inside of `.fable` but that should never happen (these projects don't compile on their own) 

cc @alfonsogarciacaro

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj Yes, I installed the same version of the SDK 3.1.102 and tested several others.

I already saw this error (or something similar) in the past and TBH I think I just upgraded my dependencies or something like that but I don't remember exactly.

**Comment by MangelMaxime** [comment]
@aggieben 
Are you able to build another Fable projects like Elmish templates?

1. `dotnet new -i Fable.Template.Elmish.React::*`
2. `dotnet new fable-elmish-react -n MyProject --yarn`
3. `cd MyProject`
4. `yarn install`
5. `yarn start`
6. Go to `http://localhost:8080/` it should works

**Comment by aggieben** [comment]
@MangelMaxime I also tried
> Can you please try to force Fable.Elmish to use the latest version by doing:

and that just added another error to the output:
![image](https://user-images.githubusercontent.com/1321/78417747-c6743600-75fa-11ea-9699-e59d11194fe9.png)

**Comment by MangelMaxime** [comment]
I am sorry @aggieben but I cannot reproduce the problem on my machine and if other templates work...

On the image, you sent in https://github.com/Zaid-Ajaj/elmish-getting-started/issues/2

I see something strange.

![image](https://user-images.githubusercontent.com/4760796/79051745-335a8200-7c32-11ea-9317-183887966bf1.png)

You start the cmd in a `C:` directory and but Fable says you are in a `D:` repository.

I don't know what `pushd` commands does but I never use it so perhaps you could try to not use it too.

Can you also please try to not have space in your path: <- Just to reduce the possibles source of errors.

I propose this test:

1. Start a CMD
2. `cd C:\`
3. `git clone git@github.com:Zaid-Ajaj/elmish-getting-started.git`
4. `cd elmish-getting-started`
5. `npm install` <-- Really use npm that's what is configured in @Zaid-Ajaj templates for the lock file
6. `npm start`
7. It should works

**Comment by aggieben** [comment]
@MangelMaxime Thanks.  That did work, so now I guess the truck will be to try one thing at a time until it breaks :-)

**Comment by aggieben** [comment]
I think I know the issue, finally:
![image](https://user-images.githubusercontent.com/1321/79695360-07478e00-823c-11ea-8da1-05f8fe145544.png)
![image](https://user-images.githubusercontent.com/1321/79695366-11698c80-823c-11ea-8cad-4ecc0c98b9a7.png)
![image](https://user-images.githubusercontent.com/1321/79695377-25ad8980-823c-11ea-9b6e-d2733fd5369f.png)

It seems that either webpack or Fable is unable to work with junctions on windows.  My user home directory has a junction on the C:\ drive to a bigger D:\ drive.

**Comment by MangelMaxime** [comment]
Ooh, so that's indeed the error I had in mind.

After, looking at Elmish template in order to understand why this template was working for you and not the one from Zaid. 

I discover this setting:

```js
    resolve: {
        // See https://github.com/fable-compiler/Fable/issues/1490
        symlinks: false
    },
```
[Source](https://github.com/elmish/templates/blob/master/src/react/Content/webpack.config.js#L101-L104)

The linked issue is similar to what you describe. Can you please try it?
