### ISSUE TITLE
Invalid string length during bundle

### ISSUE THREAD

**Issue by omarmrivas** [fable-compiler/Fable#2007]
### Description

I have got an Invalid string length error during the bundling process in my project file (SAFE-STACK template version 1.22.4). Sorry I could not minimize the project to generate the error. The error seems to come from the Client side of the web application.

ℹ ｢wdm｣: wait until bundle finished: /
readline.js:449
string = this._line_buffer + string;
^

RangeError: Invalid string length
at Interface._normalWrite (readline.js:449:32)
at Socket.ondata (readline.js:172:10)
at Socket.emit (events.js:203:13)
at addChunk (_stream_readable.js:295:12)
at readableAddChunk (_stream_readable.js:276:11)
at Socket.Readable.push (_stream_readable.js:210:10)
at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Repro code

1. Download code:
[ASPMv2-master.zip](https://github.com/fable-compiler/Fable/files/4433008/ASPMv2-master.zip)
2. dotnet tool restore
3. dotnet fake build -t run

### Expected results

The last restore is still up to date. Nothing left to do.
run run
Building project with version: LocalBuild
Shortened DependencyGraph for Target Run:
<== Run
   <== InstallClient
      <== Clean

The running order is:
Group - 1
  - Clean
Group - 2
  - InstallClient
Group - 3
  - Run
Starting target 'Clean'
Finished (Success) 'Clean' in 00:00:00.0118546
Starting target 'InstallClient'
Node version:
> "/Library/Frameworks/Mono.framework/Versions/Current/Commands/mono" --version (In: false, Out: true, Err: true)
/Users/omarmrivas/Projects/ASPMv2> "/usr/local/bin/node" --version (In: false, Out: false, Err: false)
v12.8.0
Yarn version:
/Users/omarmrivas/Projects/ASPMv2> "/usr/local/bin/yarn" --version (In: false, Out: false, Err: false)
1.17.3
/Users/omarmrivas/Projects/ASPMv2> "/usr/local/bin/yarn" install --frozen-lockfile (In: false, Out: false, Err: false)
yarn install v1.17.3
[1/4] 🔍  Resolving packages...
success Already up-to-date.
✨  Done in 0.50s.
Finished (Success) 'InstallClient' in 00:00:01.3007083
Starting target 'Run'
/Users/omarmrivas/Projects/ASPMv2> "/usr/local/bin/yarn" webpack-dev-server (In: false, Out: false, Err: false)
/Users/omarmrivas/Projects/ASPMv2/src/Server> "/usr/local/share/dotnet/dotnet"  watch run (In: false, Out: false, Err: false)
yarn run v1.17.3
$ /Users/omarmrivas/Projects/ASPMv2/node_modules/.bin/webpack-dev-server
watch : Started
Bundling for development...
ℹ ｢wds｣: Project is running at http://0.0.0.0:8080/
ℹ ｢wds｣: webpack output is served from /
ℹ ｢wds｣: Content not from webpack is served from /Users/omarmrivas/Projects/ASPMv2/src/Client/public
fable-compiler 2.4.11
> "http://localhost:8080"  (In: false, Out: false, Err: false)
ℹ ｢wdm｣: wait until bundle finished: /
info: Microsoft.AspNetCore.DataProtection.KeyManagement.XmlKeyManager[0]
      User profile is available. Using '/Users/omarmrivas/.aspnet/DataProtection-Keys' as key repository; keys will not be encrypted at rest.
Hosting environment: Production
Content root path: /Users/omarmrivas/Projects/ASPMv2/src/Server
Now listening on: http://0.0.0.0:8085
Application started. Press Ctrl+C to shut down.
fable: Compiled src/Client/Client.fsproj
fable: Compiled src/Client/Gateways.fs
fable: Compiled .fable/Fable.React.5.3.5/Fable.React.Props.fs
fable: Compiled .fable/Fable.React.5.3.5/Fable.React.Extensions.fs
fable: Compiled .fable/Fable.Elmish.3.0.6/cmd.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Delete.fs
fable: Compiled src/Shared/Shared.fs
fable: Compiled .fable/Fulma.2.4.0/Components/Modal.fs
fable: Compiled src/Client/Utils.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Box.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Table.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Button.fs
fable: Compiled .fable/Fulma.2.4.0/Layouts/Column.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Icon.fs
fable: Compiled .fable/Fulma.2.4.0/Layouts/Container.fs
fable: Compiled .fable/Fulma.2.4.0/Common.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Form/Field.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Heading.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Form/File.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Form/Control.fs
fable: Compiled .fable/Fable.FontAwesome.2.0.0/FontAwesome.fs
fable: Compiled .fable/Fulma.2.4.0/Layouts/Columns.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Form/Input.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/Json.fs
fable: Compiled src/Client/Version.fs
fable: Compiled .fable/Fulma.2.4.0/Components/Tabs.fs
fable: Compiled .fable/Fulma.2.4.0/Components/Dropdown.fs
fable: Compiled .fable/Fable.Elmish.3.0.6/prelude.fs
fable: Compiled .fable/Fulma.2.4.0/Components/Navbar.fs
fable: Compiled FemtoML/Ast.fs
fable: Compiled FemtoML/Prelude.fs
ℹ ｢wdm｣: Hash: f58ade095788f3b54576
Version: webpack 4.41.6
Time: 27762ms
Built at: 04/04/2020 11:47:03 PM
                                 Asset      Size             Chunks             Chunk Names
  06147b6cd88c7346cecd1edd060cd5de.ttf   128 KiB                     [emitted]  
08952b029e4decbc8ef9fb553cae8cea.woff2  62.2 KiB                     [emitted]  
  0bff33a5fd7ec390235476b4859747a0.ttf   188 KiB                     [emitted]  
108f1f23ad45de8aeea5849592c8b685.woff2  14.2 KiB                     [emitted]  
 12e2ed7a180e601bff44253d4c7062ad.woff  68.3 KiB                     [emitted]  
  15c5cdc89d241d373ce228df459821b2.ttf    24 KiB                     [emitted]  
  19b56cfcb97fbcc245242fb28232939e.ttf   117 KiB                     [emitted]  
  1c0b4eb93fcf561eec03297a24922d6c.ttf   128 KiB                     [emitted]  
 23c906d4759f27cdcaa699062c13b0eb.woff  16.2 KiB                     [emitted]  
  24aab533f87e7b434be5fa5b1684975c.svg  1.13 MiB                     [emitted]  
  26f1e68dfbd8b8621e5d07f75571a1f9.ttf   130 KiB                     [emitted]  
  2a9a30e14574c9ec24add2901a80b81c.svg   292 KiB                     [emitted]  
2b5cb36ed50460769e80bf82759c0965.woff2  15.5 KiB                     [emitted]  
3326e4d74d3924ee1c882c29f5b571c0.woff2  45.6 KiB                     [emitted]  
 333bae208dc363746961b234ff6c2500.woff  96.1 KiB                     [emitted]  
3343e54368719e3786f78a1b22839455.woff2  55.3 KiB                     [emitted]  
  336bcb7b78f6c5e55120951f0045a8d8.svg   292 KiB                     [emitted]  
  33f225b8f5f7d6b34a0926f58f96c1e9.ttf   216 KiB                     [emitted]  
383eba0e55ed778006d76428812d343c.woff2  55.3 KiB                     [emitted]  
39d27e13dce3dfe4cdc70a281ccdf113.woff2  44.8 KiB                     [emitted]  
44d537ab79f921fde5a28b2c1636f397.woff2    74 KiB                     [emitted]  
  4595d7f8ce0e7b381abb0254f04f0ec2.ttf   121 KiB                     [emitted]  
4e6f1e88254a1865c135db3feff6b399.woff2  12.8 KiB                     [emitted]  
 4f44077586ec12a35ce6778e879d43da.woff    70 KiB                     [emitted]  
  5063b105c7646c8043d58c5289f02cca.eot   128 KiB                     [emitted]  
5211065d7cf88c28086d8f99f8705b71.woff2  51.5 KiB                     [emitted]  
 525074686dfb8aa36b1b92e29de467ac.woff  74.3 KiB                     [emitted]  
55835483c304eaa8477fea2c36abba17.woff2  45.9 KiB                     [emitted]  
  5a100916f94b0babde0c92aaa8fb80d6.ttf   107 KiB                     [emitted]  
5aaceea2d60ddb477c6aafc825eece3d.woff2  53.3 KiB                     [emitted]  
  65b286af947c0d982ca01b40e1fcab38.ttf  33.3 KiB                     [emitted]  
 693015cfe3fcf90e190a4062559e2c84.woff  17.7 KiB                     [emitted]  
  7b9568e6389b1f8ae0902cd39665fc1e.svg   141 KiB                     [emitted]  
 7be88e73fea7b64568a450d7c01346b0.woff  71.9 KiB                     [emitted]  
 892667349c5cff6fcf7e40439596b97c.woff  62.1 KiB                     [emitted]  
  8e4a6dcc692b3887f9f542cd6894d6d4.eot   188 KiB                     [emitted]  
  93c74904d1169a68c36b4edc333a692b.svg  53.9 KiB                     [emitted]  
 963eb32907744d9a0d6b98127162808f.woff  61.4 KiB                     [emitted]  
 97534dd409492b05b11ab96b3dd4a557.woff  74.6 KiB                     [emitted]  
  9b30f13428e1b4a659aeeab4ac1fff35.ttf   128 KiB                     [emitted]  
 9f2144213fad53d4e0fdb26ecf93865f.woff  68.3 KiB                     [emitted]  
  a33a878f3861ca67e9bc423c58b2a357.svg   285 KiB                     [emitted]  
  a84e8591bb7eb3998ad492c27c4c3d52.svg   284 KiB                     [emitted]  
  a9c4bb7348f42626454c988dbde1d0a0.svg   684 KiB                     [emitted]  
 ac327c4db6284ef64ebe872b6308f5da.woff  62.2 KiB                     [emitted]  
                                app.js  3.02 MiB                app  [emitted]  app
  b22164d568f72650d592271d22dd5cda.svg   259 KiB                     [emitted]  
  b46ff9f5c8bcba1ea3b4b320e22be5c7.svg   290 KiB                     [emitted]  
 b6cf1db5e3827919cd2148bdae913131.woff  19.3 KiB                     [emitted]  
bc511bacf828ac9e833e6208292066b8.woff2  51.8 KiB                     [emitted]  
  bf4dde0147bb02556500d922e2efc90b.svg   267 KiB                     [emitted]  
  c1a866ec0e04a5e1915b41fcf261457c.eot  33.6 KiB                     [emitted]  
  c2801fb415f03c7b170934769d7b5397.svg   823 KiB                     [emitted]  
  c36b5ac7c2dddf6f525c8d161412ef41.ttf   125 KiB                     [emitted]  
 c4f508e7c4f01a9eeba7f08155cde04e.woff  16.4 KiB                     [emitted]  
 c5e0f14f88a828261ba01558ce2bf26f.woff  86.4 KiB                     [emitted]  
cccc9d29470e879e40eb70249d9a2705.woff2  73.6 KiB                     [emitted]  
  cd7296352d159532b66c07d98efb1126.ttf   104 KiB                     [emitted]  
  cdc8a9f118ddbf85ef5d8c06cfe042fc.ttf  26.9 KiB                     [emitted]  
  df2a321f01fad21758777e44fa839ccf.svg  53.6 KiB                     [emitted]  
e7cc7120e670a8073073dbc3e4ff0184.woff2  55.2 KiB                     [emitted]  
 ec55f263e2b86bc0f28fff46b873d6df.woff  73.8 KiB                     [emitted]  
  ecb4572a5e478b107dfcb60c16a7eefa.ttf   105 KiB                     [emitted]  
  f108c981ed9611d5cc44f688b9ce80a4.svg  1.13 MiB                     [emitted]  
  f13a42c6a06af3ffcb6986dbcf5022f5.svg  56.6 KiB                     [emitted]  
  f447e079e7e41d884331200758b40a75.ttf  30.8 KiB                     [emitted]  
f5f2566b93e89391da4db79462b8078b.woff2  13.3 KiB                     [emitted]  
  fedf49d31f55f4beaf2c891f3875554f.svg   265 KiB                     [emitted]  
                            index.html  10.9 KiB                     [emitted]  
                              style.js   964 KiB              style  [emitted]  style
                        vendors~app.js  1.06 MiB        vendors~app  [emitted]  vendors~app
                  vendors~app~style.js   896 KiB  vendors~app~style  [emitted]  vendors~app~style
                      vendors~style.js   129 KiB      vendors~style  [emitted]  vendors~style
Entrypoint app = vendors~app~style.js vendors~app.js app.js
Entrypoint style = vendors~app~style.js vendors~style.js style.js
[0] multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/Client/Client.fsproj 52 bytes {app} [built]
[3] multi (webpack)-dev-server/client?http://0.0.0.0:8080 (webpack)/hot/dev-server.js ./src/Client/style.scss 52 bytes {style} [built]
[./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader/index.js!./node_modules/sass-loader/dist/cjs.js?!./src/Client/style.scss] ./node_modules/css-loader/dist/cjs.js!./node_modules/resolve-url-loader!./node_modules/sass-loader/dist/cjs.js??ref--6-3!./src/Client/style.scss 323 KiB {style} [built]
[./node_modules/strip-ansi/index.js] 161 bytes {vendors~app~style} [built]
[./node_modules/style-loader/lib/addStyles.js] 10.2 KiB {vendors~style} [built]
[./node_modules/webpack-dev-server/client/index.js?http://0.0.0.0:8080] (webpack)-dev-server/client?http://0.0.0.0:8080 4.29 KiB {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/overlay.js] (webpack)-dev-server/client/overlay.js 3.51 KiB {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/socket.js] (webpack)-dev-server/client/socket.js 1.53 KiB {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/utils/createSocketUrl.js] (webpack)-dev-server/client/utils/createSocketUrl.js 2.89 KiB {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/utils/log.js] (webpack)-dev-server/client/utils/log.js 964 bytes {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/utils/reloadApp.js] (webpack)-dev-server/client/utils/reloadApp.js 1.59 KiB {vendors~app~style} [built]
[./node_modules/webpack-dev-server/client/utils/sendMessage.js] (webpack)-dev-server/client/utils/sendMessage.js 402 bytes {vendors~app~style} [built]
[./node_modules/webpack/hot/dev-server.js] (webpack)/hot/dev-server.js 1.59 KiB {vendors~app~style} [built]
[./src/Client/Client.fsproj] 30 bytes {app} [built]
[./src/Client/style.scss] 1.36 KiB {style} [built]
    + 390 hidden modules
Child html-webpack-plugin for "index.html":
     1 asset
    Entrypoint undefined = index.html
    [./node_modules/html-webpack-plugin/lib/loader.js!./src/Client/index.html] 11.4 KiB {0} [built]
    [./node_modules/lodash/lodash.js] 528 KiB {0} [built]
    [./node_modules/webpack/buildin/global.js] (webpack)/buildin/global.js 472 bytes {0} [built]
    [./node_modules/webpack/buildin/module.js] (webpack)/buildin/module.js 497 bytes {0} [built]
ℹ ｢wdm｣: Compiled successfully.

### Actual results

ℹ ｢wdm｣: Compiling...
fable: Compiled src/Client/Client.fsproj
fable: Compiled src/Client/Client.fs
fable: Compiled src/Client/Login.fs
fable: Compiled .fable/Fable.Elmish.3.0.6/program.fs
fable: Compiled .fable/Fable.Elmish.HMR.4.0.1/hmr.fs
fable: Compiled .fable/Fable.Elmish.React.3.0.1/react.fs
fable: Compiled .fable/Fable.Elmish.Debugger.3.0.3/debugger.fs
fable: Compiled .fable/Fable.Elmish.Debugger.3.0.3/Fable.Import.RemoteDev.fs
fable: Compiled .fable/Thoth.Json.3.4.1/Extra.fs
fable: Compiled .fable/Fable.Remoting.Client.5.10.0/Remoting.fs
fable: Compiled .fable/Fable.Elmish.HMR.4.0.1/common.fs
fable: Compiled .fable/Thoth.Json.3.4.1/Types.fs
fable: Compiled .fable/Thoth.Json.3.4.1/Encode.fs
fable: Compiled .fable/Fulma.2.4.0/Layouts/Hero.fs
fable: Compiled .fable/Fulma.2.4.0/Elements/Form/Checkbox.fs
fable: Compiled .fable/Fable.Elmish.3.0.6/ring.fs
fable: Compiled .fable/Fable.Elmish.React.3.0.1/common.fs
fable: Compiled .fable/Fable.Remoting.Client.5.10.0/Types.fs
fable: Compiled .fable/Fable.Remoting.Client.5.10.0/Proxy.fs
fable: Compiled .fable/Thoth.Json.3.4.1/Decode.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/TypeInfo.Converter.fs
fable: Compiled .fable/Fable.Remoting.Client.5.10.0/Http.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/TypeInfo.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/SimpleJson.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/TypeCheck.fs
fable: Compiled .fable/Fable.Parsimmon.4.1.0/Parsimmon.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/Parser.fs
fable: Compiled .fable/Fable.SimpleJson.3.8.1/Json.Converter.fs
ℹ ｢wdm｣: wait until bundle finished: /5c5bbda4c9ea235f018f.hot-update.json
readline.js:449
    string = this._line_buffer + string;
                               ^

RangeError: Invalid string length
    at Interface._normalWrite (readline.js:449:32)
    at Socket.ondata (readline.js:172:10)
    at Socket.emit (events.js:203:13)
    at addChunk (_stream_readable.js:295:12)
    at readableAddChunk (_stream_readable.js:276:11)
    at Socket.Readable.push (_stream_readable.js:210:10)
    at Pipe.onStreamRead (internal/stream_base_commons.js:166:17)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.

### Related information

* Fable version: 2.4.22
* Operating system: Windows 10/Mac OS 10.15.4
* dotnet --version: 3.0.100

**Comment by alfonsogarciacaro** [comment]
Sorry but I haven't been able to reproduce the error so I'm closing the issue as stale. Please reopen if you see it again with SAFE template 3.
