### ISSUE TITLE
Webpack toolchain refuses to recompile file

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#2008]
### Description

I have a unique setup which may be forcing me to hit a weird edge case in the toolchain.

Basically I do some automated code generation when certain files are saved. When I make a manual change in `Foo.special.fs`, a watcher picks up the change, and autogenerates a `Foo.auto.fs`. Both of these files (and all similar pairs) are referenced in my `fsproj` file.

Say some code in `Bar.fs` changed, which caused compilation errors in both `Foo.special.fs` and `Foo.auto.fs`. These correctly show up in webpack output. I go and update `Foo.special.fs` to fix the compilation error, and save. 4 out of 5 times, both files get recompiled by Fable, and the errors go away. But 1 out of 5 times, the errors in `Foo.special.fs` go away, but ones in `Foo.auto.fs` persist. What's worse, and really baffling, is that no subsequent manual changes to `Foo.auto.fs` are picked up by webpack/Fable (even though the file is simply referenced in the "fsproj" file, no magic here). I can add a newline, or add a comment, or completely break the syntax of the file — nothing triggers a recompile. Only killing and restarting webpack brings it back.

### Repro code

I can try isolating this if really required, but for now wanted to start a conversation and see if people have ideas as to what may be causing this.

### Expected and actual results

I expect any change to any file referenced in "fsproj" to always trigger a recompile of that file.

### Related information

* Fable version: 2.4.22
* Operating system: MacOS 10.13.6

**Comment by MangelMaxime** [comment]
Hello @anchann,

I think we will need a reproduction repository in order to try to debug the problem. Like that I don't have any idea to fix it because if we make an error manually in it and fix it then it works.

I guess that's something due to the watcher not being triggered or something like.

**Comment by anchann** [comment]
@MangelMaxime got it, thank you for replying. I'll work on an isolated repro case.

**Comment by alfonsogarciacaro** [comment]
Closing as stale, please reopen if you see the issue again with Fable 3.
