### ISSUE TITLE
Troubles with uncurrying

### ISSUE THREAD

**Issue by uxsoft** [fable-compiler/Fable#2011]
### Description

Trying to create a POJO containing a function. When done directly this function has two parameters (uncurried) which is what the javascript library expects.

When passing this function through a class attribute it will become curried (a function that takes one argument and returns another function) which makes the javascript library for which this object is created fail.

### Repro code

https://fable.io/repl/#?code=PYBwpgdgBAQgTsA7gZzHAUKSUBiBDAIwBswA6AJTDwGMAXTcafYsgYWDjIClkBJCWmlDp0JWlGQALJABVgtPESh4oBKAF4JIOAEsBAMygAiAKTIoZo8tUixE6YjkKiAJmtrNybXtqHT5y3cRWgBPcCgAQQAKAEoNKHQoJKgAWzAUgjQoAA9SAGUHJ0UofWh1ROTK6k48QQB5AgArKABtYylZeUUrdXUAPhLoAF0RUTBxPH5kBQhqMHjomLHxYCb4yYhpvFmyAs7ne33FF3QAEWAU0mpgTeASUiJgAHMoVcagA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKVuGiMmHRoHiikFFI8KDlI2hNKGwwzSstoq4sqkLBwQA&css=Q

### Expected and actual results

Expected: obj contains function that takes two arguments
Actual: obj contains a function that takes one argument

### Related information

* Fable version: 2.4.22
* Operating system: Windows 10

**Comment by MangelMaxime** [comment]
When passing the classes the way you do, you will to force the uncurry yourself:

```fs
type A() = 
    member x.ShowTotal (fn : string -> string -> string) =
        let uncurried = System.Func<string, string, string> fn
        createObj [
            "showTotal" ==> uncurried
        ] 
```

**Comment by uxsoft** [comment]
That's exactly what I was looking for!

Let me know if you want me to submit a PR to some repo with documentation to share with this others as well.

Thanks,
Jan

**Comment by MangelMaxime** [comment]
I think we could indeed add that information to [Fable documentation](https://fable.io/docs/communicate/fable-from-js.html#Functions:-automatic-uncurrying)

The repo is here: https://github.com/fable-compiler/fable-compiler.github.io
