### ISSUE TITLE
When generating source-map JS.debugger is not shown stopped at the right place in the F# file. It seems to be at the beginning of the current scope

### ISSUE THREAD

**Issue by 7sharp9** [fable-compiler/Fable#2012]
### Description

Breakpoints are not working

### Repro code

I have a repo here

https://github.com/7sharp9/fable-vscode-twitch-chatbot
Set breakpoints on any line, none of them work.

### Expected and actual results

Breakpoints work

### Related information

* Fable version: 2.4.22
* Operating system MacOS

**Comment by 7sharp9** [comment]
![Screenshot 2020-04-09 at 12 01 34](https://user-images.githubusercontent.com/588746/78888781-3dc22380-7a5a-11ea-9b4f-baf8a88dc818.png)

**Comment by 7sharp9** [comment]
Previously I noticed that breakpoints were out by ~20 lines but this seems to have stopped and they no longer work at all as seen in the above repo.  The `debugger()` entry on line 83 just jumps into js code:

![Screenshot 2020-04-09 at 12 06 25](https://user-images.githubusercontent.com/588746/78888921-909bdb00-7a5a-11ea-8823-e1112d716a83.png)

**Comment by MangelMaxime** [comment]
Hello @7sharp9,

when debugging your extension for VSCode, you should see a message telling you that you can set breakpoints in your fs files because source maps were not found.

![image](https://user-images.githubusercontent.com/4760796/79047608-04371700-7c18-11ea-910e-6136152dad7e.png)

In order, to be able to debug from an .fs file you need to activate the source map generation in your babel config.

```diff
const path = require("path");

function resolve(relativePath) {
  return path.join(__dirname, relativePath);
}

module.exports = {
  entry: resolve("src/FableVscodeExtention.fsproj"),
  outDir: resolve("out"),
  babel: {
    plugins: ["@babel/plugin-transform-modules-commonjs"],
+    sourceMaps: true,
  },
  allFiles: true
};
```

![debug_vs_code](https://user-images.githubusercontent.com/4760796/79047777-16658500-7c19-11ea-873c-fdf49df4e8e1.gif)

If I add the `JS.debugger()` instruction it also captures it but the stop in the JavaScript file is messed up. I created an issue in order to track the work on the source-maps #2013

**Comment by 7sharp9** [comment]
I think you were there on the stream when I was debugging and between then and when I logged the issue nothing had changed and they stopped working.  I know nothing about the source maps but Im happy to help out if you can suggest anything for me to look into :-)

**Comment by MangelMaxime** [comment]
Are you trying to debug the code from the `*.fs` files? Or are you debugging from the generated JavaScript file?

If that's the first option, then you need the source-maps which is a file generated to make the link between F# code and JavaScript code.

If that's the second option, then no changes are needed in your repo.

For me debugging is working on your project.

**Comment by 7sharp9** [comment]
The *.fs files, if I add breakpoints then nothing happens unless I add
`debugger()` even then the source lines don't match.

**Comment by MangelMaxime** [comment]
You need to have source maps files in order to debug a from `*.fs` files.

VSCode tooltip is explicit about that.

I send a PR to your project: https://github.com/7sharp9/fable-vscode-twitch-chatbot/pull/3

**Comment by 7sharp9** [comment]
Even when I do that the first entry point with a debugger() on line 82:
```
    let client = tmi.client options
    debugger()
    client.connect() |> ignore
```

Is here:

![Screenshot 2020-04-12 at 14 28 41](https://user-images.githubusercontent.com/588746/79069958-15406080-7cca-11ea-99c2-bf1d8a6a9a3c.png)

**Comment by MangelMaxime** [comment]
Yes, I know that's what I explain in my first message.

This is probably a problem related to the source map. If you don't generate the source maps then VSCode stops at the right line in the JavaScript files.

This is not the case, when I activate the source-maps. However, if you active the source map you can directly set the breakpoint from VSCode interface and that's being stop at the right location.

**Comment by 7sharp9** [comment]
To be explicit, this happens with source maps enabled.
