### ISSUE TITLE
Cannot resolve System.Reflection.PropertyInfo.GetValue

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#2015]
### Description

I'm trying to do some reflection based metaprogramming, and am running into the issue that `System.Reflection.PropertyInfo.GetValue` doesn't seem to be implemented. Would it be difficult to add?

### Repro code

```fs
open System
open FSharp.Reflection

type Foo = {
    IsGood: bool
}

// say this comes from some type-unaware code (for good reason, we're in metaprogramming land)
let value: obj = { IsGood = true } :> obj

// say this also comes from somewhere
let theType: Type = typeof<Foo>

// now we want to print out the fields
let fieldNameToValue: Map<string, obj> =
    match theType with
    | t when FSharpType.IsRecord t ->
        FSharpType.GetRecordFields(t)
        |> Seq.fold
            (fun acc field ->
                let fieldValue = field.GetValue value
                acc.Add (field.Name, fieldValue)
            )
            Map.empty
    | _ -> Map.empty

printf "%O" fieldNameToValue
```

### Expected and actual results

Expected: `map [(IsGood, true)]`

Actual: `FABLE: Cannot resolve System.Reflection.PropertyInfo.GetValue`

### Related information

* Fable version: 2.4.15
* Operating system: MacOS 10.13.6

**Comment by anchann** [comment]
Trying to dig into the code and fix this myself, but when following local setup instructions in `README.md`, I'm failing at the "and `npm run build` at the root folder to start the build" step. Running the build command, with any parameter, and through any invocation (`npm`, `npx`, `./node_modules/.bin/fable`) results in the same error:

```
Error: List did not contain any matching elements
```

I hoped I could somehow get away without building, but linking the fable CLI in webpack.config and running webpack unsurprisingly gives me

```
Error: fable-library directory is empty, please build FableLibrary
```

Can somebody please help me get up and running?

**Comment by MangelMaxime** [comment]
Fable support reflection API is limited because it can increase the bundle size. That's why you Fable tells you it doesn't know how to convert `System.Reflection.PropertyInfo.GetValue`.

I don't have problems building Fable with the instruction from the readme can you please open an issue with your error so we can investigate it.

Also, please know that Fable repository support Gitpod which will set up an IDE in the Web for you. And avoid the need to setup the repo on your computer.

**Comment by anchann** [comment]
@MangelMaxime thank you for responding.

> Fable support reflection API is limited because it can increase the bundle size. That's why you Fable tells you it doesn't know how to convert System.Reflection.PropertyInfo.GetValue.

How is it decided what API makes it in, and what does not? Is the case on `GetValue` closed, or may I request that it is added? If it cannot be added, could you make a recommendation on how one might go about implementing it manually?

> I don't have problems building Fable with the instruction from the readme can you please open an issue with your error so we can investigate it.

Will do.

**Comment by MangelMaxime** [comment]
@anchann The decision is kind of made arbitrary by the maintainers after testing the impact on the bundle size etc.

In your case, you can use dynamic typings to work around the limitation. You do need to have access to the value you are working however.

```fs
acc.Add (field.Name, box value?(field.Name))
```

[REPL demo](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMRgCwEMAnEAOgCUwAzAGzAGMkBLYCTcaHQgI3rIDCwYmDIApBAEkIKYqHTokccLmDAoAXigBvdFH1RJCAOJqAJgC4oPNbXQBfBQHonUBIThQk+ZgigNgVDA-ajlUN0CwL2UwAFoAVwhCAHcSKICzKIAKamEoAHNzKBFCBDYAGihksAByEShmaCCkQhA5fOJCVFRG-KhaQggzAEp0eiQoADdCWniwK2AeACtNHUMTIq0kYjmoeygLAD4oRaXnV3dPb18oGbL-SJCwiKDk-DARMbAJ7zAAFRiVgBKi2MWA1AAPDg1IdzlAIMBklUoqkZF51G1GhNgPEfu8oNRmGBaGYEF8JoTiWYAHJdf7AABqMzmVgAsq0IchiL1Kqdjho9AZUIQkAx8F53sCUcxvIL9AAfLxVd5cAgkEBSshGKgBYhmJWxWEGY24NWkTXGb464RmHBEkkILJIUYmgzy44wMAARzIuRJctdBhyiVuDAYBPt+sNAcDJpc-W+EapTNmUS0lJJZEtSBTu2mqZjsYMhDDZAAgmZ9TlI2RaUFKjYAB5TZlgAD81aptbpwxdRf0ff77PIaBASgDioA+lBDVBh2RR+P0JiZNQoAAiACkAHl10mSXX6bmwEA&html=DwCwLgtgNgfAUAAlAUwIYBN4O0iyyoLhgAOAtMgI4CuAlgG4C8A5AMID2AdmMt2QCoBPEsmYIAxlx7cWPAB5gA9OGgBuCSFQAnAM75G1MADMyADmZYcwHeK20SYBDq3jGAIgD6HgBIB5AMr8XopQtABGOopaaOJgAHQkWuzo1LG0XHEQtJxxAFY6bjDAijZ2DpbY1rb2js6unj4BQR4h4ZHRqLFk6OwQCUkpaRlZOfmFxaU1FUihnADWCNFQ7jpgglDIOiDI+G5E0UbuXn6BwaERiuI6kWHUUBComdlxVwUIitPAswtLK2sbWx2YD2IAOR0apxa50ir0UqCgUCeOVeew+iCsq3WyGmigAVAhfJwoIIEJwduhkOgEEZ2FoELRJJwnKgICQNghcYp0dgXlJUNlkFoyDpaAAvTYIOJhKDscQLADe3Jw2HQtB0bNQggAXNSNnJVEqAL5K3ncflkoUi8U6SUMrgIRXK5VhTpzADmSWonHQZEkMq0OsEyAR7AA7ganTgHlo3dkdQAGBAAVhI+qNSom-2xcGK2wwWGAYWSJPEUFQ13cqBI5EZBAFWkKGdV9Hp6HcwayWzIVZIe1L5Z07fuapA3er40UzfgxSL6EE0+UkFgQA&css=Q)

**Comment by anchann** [comment]
> In your case, you can use dynamic typings to work around the limitation

So I'll need to know the runtime structure to know where to pluck out the value from. And I'll have to do this differently for records, union cases, and tuples. Got it.

Thank you for unblocking me, I really appreciate this!

This may be naive of me, and this argument might apply to perhaps many members of the reflection API, but it seems that adding this function would save people the trouble of hacking, and the additional bundle footprint should be fairly small, since all we're doing is accessing existing data, not creating new reflection data and functions to manage it that would bloat the bundle and runtime.

**Comment by MangelMaxime** [comment]
It seems you are right @anchann 

I manage to have something working locally without adding a new type so we should be able to add support for it in Fable. 

I am working it.

**Comment by anchann** [comment]
@MangelMaxime awesome, thank you!
