### ISSUE TITLE
Fable version code snippet returns unexpected version

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#2016]
### Description

This is a meta-issue.
When trying to submit an issue, I run the `npm show fable-compiler version` snippet that's in the issue template, but it gives me a version number different from what I actually have.

Not sure what exactly is happening here, but wanted to bring it to your attention just in case.

### Repro code

```
$ cat node_modules/fable-compiler/package.json | grep '"version":'
  "version": "2.4.15"
$ cat package.json | grep "fable-compiler"
    "fable-compiler": "2.4.15",
$ npm show fable-compiler version
2.5.0
```

**Comment by alfonsogarciacaro** [comment]
Hmm, it could happen that 2.5.0 was released without properly updating the version string within the code 🤔 Anyways, unfortunately we're not updating Fable 2 now, with Fable 3 you should be able to do `dotnet fable --version`, so I'm closing this. Please reopen if you see a similar problem with Fable 3.
