### ISSUE TITLE
Seq.cache does not work on infinite sequences

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2031]
### Description

Seq.cache tries to iterate the whole sequence, so if its passed an infinite sequence, it'll crash when it eventually hits the memory limit. Native F# does not behave in this way. Also see #1143

### Repro code

```
open System
let guids = Seq.initInfinite (fun _ -> Guid.NewGuid()) |> Seq.cache
printfn "guid 0: %A" (Seq.item 0 guids)
printfn "guid 1: %A" (Seq.item 1 guids)
printfn "guid 0 again: %A" (Seq.item 0 guids)
```

### Expected and actual results

Code should not fail, and guid 0 should be the same both times

**Comment by ncave** [comment]
@jwosty The repro provided above is invalid.
But you are correct, `Seq.cache` and seq printing are currently not implemented to support infinite sequences (`Seq.cache` is just implemented with `Seq.toArray` for now).

**Comment by jwosty** [comment]
Yep, I see that now, I've fixed the repro

**Comment by njlr** [comment]
It seems this has been fixed already. 

I added your repro as a test-case here: https://github.com/fable-compiler/Fable/pull/2547

**Comment by njlr** [comment]
OK to close @jwosty ?

**Comment by alfonsogarciacaro** [comment]
Closing as @njlr already submitted a test for this and it's working 👍
