### ISSUE TITLE
Use ReactNavigation/Native with Fable..

### ISSUE THREAD

**Issue by mohandev** [fable-compiler/Fable#2034]
### Description

I'm planning to use ReactNavigation (https://reactnavigation.org/docs/getting-started) with Fable in my React Native project. 

As per documentation, the following import needs to be on top of the App.js,

import 'react-native-gesture-handler';

Otherwise, the app could crash in production. Wondering how this can be achieved when using with Fable because App.js is generated automatically ? Kindly help..

### Related information

* Fable version: 
"fable-compiler": "2.5.1",
"fable-splitter": "2.1.13",
* Operating system: 
React Native 0.62.1, iOS & Android

**Comment by MangelMaxime** [comment]
@mohandev I don't think you can force an import to be on top of the others in Fable.

However, the documentation says:

> To finalize installation of react-native-gesture-handler, add the following at the top (make sure it's at the **top** and there's nothing else before it) of your entry file, such as index.js or App.js:

So, I think you only need to call it once in your application. If yes, you could write a small `bootstrap.js` file which would be your entry file.

And from within `bootstrap.js` do something like that:

```js
import 'react-native-gesture-handler';
import { MyApp} from 'yourFableCompiledCode.js`;
import { NavigationContainer } from '@react-navigation/native';

export default function App() {
  return (
    <NavigationContainer><MyApp></NavigationContainer>
  );
}
```

**Comment by mohandev** [comment]
Good idea. Thanks @MangelMaxime..

**Comment by inosik** [comment]
What about `Fable.Core.JsInterop.importSideEffects`?

**Comment by MangelMaxime** [comment]
I don't think `importSideEffects` will be added at the topmost of the file. But just replaced where it has been imported.

**Comment by inosik** [comment]
Fable seems to put it on top, I've tested it in the REPL. [Link](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCc0CkDOAkhAC5hagCwAUDQJYC2I2JAynQCZgCiAZr2ADGJfFABEEOADcEcLAFpBwJsAiQSYmjRQkoADygBeKAHkQJOqtRdecAK5ISANThI7YKABYATFAByqmBAA&html=Q&css=Q)

That's a strange requirement, though. I imagine JS linters mark this as a warning, if you have a rule that enforces your imports to be sorted.

**Comment by MangelMaxime** [comment]
Ooh 😮 

@inosik Thank you for checking and you indeed seem to be right.

**Comment by alfonsogarciacaro** [comment]
When generating the Babel AST all the imports are collected and moved to the top of the file. This is necessary for the static imports, but probably not for something like `importSideEffects`.

We can fix the behavior of `importSideEffects` or alternatively you can use `importDynamic "..." |> ignore` which is only evaluated where you put it. [REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCc0CkDOAkhAC5hagCwAUDQPR1QCWAtiNiQMpMAmYAogDNBYAMYl8UAEQQ4ANwRwsAWlHA2wCJBJSaNFCSgAPKAF4oAeRAkmm1H0FwArkhIA1OEidgoAFgBMUABymmB61AZQZPgkABQAlGY0UCnMGlgkACIAnrIsTKLSsgpKqursWqRSUAA+AHzMAOYQ2GHUqVAJ4UA&html=Q&css=Q)
