### ISSUE TITLE
(Seq|List).fold produces incorrect output when state is a function with arity > 1

### ISSUE THREAD

**Issue by felixschorer** [fable-compiler/Fable#2035]
### Description

`Seq.fold` and `List.fold` produce incorrect output when `state` is a function with arity greater than 1.

> **`List.fold`**
> `val fold : folder:('State -> 'T -> 'State) -> state:'State -> list:'T list -> 'State`

### Repro code

```f#
let folder state value x y = value :: state x y
let state x y = [x; y]
let d = Seq.fold folder state [0..3]
printfn "%A" (d 42 42)
```

[Repl link](https://fable.io/repl/#?code=DYUwLgBAZg9sAmIBOEDOYCGYQQG4eAFccAPCATwgF48DiIAuBtTbCM8gWAChRJ0spCtQgBtEgG4KAXR58I8EQGUQARwB0sBNDiIUAtqIAM69QGZZ3AA5IAlgDswUexABEAUgCCriAApFACwATBDBAJRAA&html=Q&css=Q)

### Expected and actual results

Expected output: `[3; 2; 1; 0; 42; 42]`
Actual output: `[3]`
The tail of the resulting `List` is a function instead of an other `List`.

### Related information

* Fable version: 2.8.2
* Operating system: Windows 10 Pro 1903

**Comment by felixschorer** [comment]
I stepped through the generated JS. The problem seems to be here:
```javascript
export function folder(state$$1, value, x, y) {
  return new List(value, state$$1(x, y));
}
```
`state$$1` is a curried function, but is called as an uncurried function.

**Comment by ncave** [comment]
Yes, the problem seems to be the curried lambda wrapper at the call site for `state` is not uncurried.
Here it is in a different form:
```fs
let inline folder st value x y = value :: st x y
let inline state x y = [x; y]
let d = List.fold folder state [0;1;2;3]
System.Console.WriteLine(List.length (d 42 42))
```
compiles to:
```js
import { List } from "fable-library/Types.js";
import { length, fold, ofArray } from "fable-library/List.js";
export const d = fold(function (st, value) {
  return function (x) {
    return function (y) {
      return new List(value, st(x, y));
    };
  };
}, function (x$$2) {
  return function (y$$2) {
    return ofArray([x$$2, y$$2]);
  };
}, ofArray([0, 1, 2, 3]));
console.log(length(d(42)(42)));
```
