### ISSUE TITLE
CompiledName has no effect on record fields

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2040]
### Description

`GetRecordFields` ignores the `CompiledName` attribute.

### Repro code

Run this in the Fable REPL

```fsharp
open FSharp.Reflection

type A = {
    [<CompiledName("Renamed")>]
    One: string
    Two: int
}

printfn "%A" (FSharpType.GetRecordFields(typeof<A>))
```

### Expected and actual results

Actual
`One,System.String,Two,System.Int32`

Expected
`Renamed,System.String,Two,System.Int32`

~~https://github.com/fable-compiler/Fable/issues/1563#issuecomment-419580684 suggests this should work. Has the behavior been changed?~~ That talks about `GetUnionCases`.

**Comment by MangelMaxime** [comment]
For references, there is also an old discussion about the same feature here https://github.com/fable-compiler/Fable/issues/1149#issuecomment-329740415

**Comment by inosik** [comment]
F# on .NET gives the same result as Fable as well.

**Comment by kerams** [comment]
@inosik, great point. So Fable is consistent. However, doesn't it seem like a bug in the first place?

**Comment by MangelMaxime** [comment]
I am not sure who interprets the names provided by `CompiledName` but if it is F# compiler then I think we should keep the behaviour consistent with.

Because the problem with interpreting it from Fable is we need to make sure that reflection info uses the provided name and also the generated JavaScript code. I think it could be tricky to make sure that it works everywhere.

One thing, that could be added without deviating too much from F# compiler behaviour could be a warning perhaps.

**Comment by inosik** [comment]
I'm not too familiar with FCS, but AFAIK the `FSharpEntity` type stores its name as defined in the source code and the compiled name as well. I guess it depends on the developer to use the correct one when doing codegen.

**Comment by alfonsogarciacaro** [comment]
As commented [here](https://github.com/fable-compiler/Fable/issues/2041#issuecomment-622250810) the behavior of CompiledName attribute is already not very intuitive in .NET F# and unfortunately it's not consistent with Fable for the case names, but there's already a lot of code relying on this so it cannot easily be changed.

I would avoid changing the behavior for the record fields in order not to add to the confusion.

**Comment by kerams** [comment]
@alfonsogarciacaro, thank you. Bit disappointing, but I understand.
