### ISSUE TITLE
Aliasing a function, which wraps a function with arity > 1, produces incorrect output

### ISSUE THREAD

**Issue by felixschorer** [fable-compiler/Fable#2045]
### Description

Aliasing a function, which wraps a function with arity > 1, produces incorrect output.

The problem seems to be here:
```javascript
export function wrap(decoder, _arg2$$1, _arg1$$1) {
  return decoder(null, null);
}
```
`doesWork` is called with an uncurried function for the `decoder` argument.
`doesNotWork` is called with a curried function for the `decoder` argument.

### Repro code

```f#
let fortyTwo _ _ =
    42

let wrap someFun _ _ =
    someFun () ()

let doesWork someFun = 
    wrap someFun

let doesNotWork = 
    wrap

printfn "%A" <| doesWork fortyTwo () ()
printfn "%A" <| doesNotWork fortyTwo () ()
```

[Repl link](https://fable.io/repl/#?code=DYUwLgBAZg9gTmAngFQO4wgfSxAvAWACgISIAWAJiKNElTgEMAHCAZxgFsQAxAVwDsc2AsVLsufQQAoAlBFnVCtCABMYIVgHV4AazaceAvBCKkI9ZvokDFytRoByMMNrh7cJ0SQtNFTOACW-GBQggBEAKQAgmEQADwAPqrqWrrQ8EhoGLLyMkT+QSHh0bGJyY7OrnqwCCjoublAA&html=Q&css=Q)

### Expected and actual results

Expected:
```
42
42
```

Actual:
```
42
0
```

### Related information

* Fable version: 2.8.4
* Operating system: Windows 10 Pro 1903

**Comment by stkb** [comment]
Came across I think the same issue, when I found my javascript code handling functions instead of values.

[Maybe a simpler example](https://fable.io/repl/#?code=LYewJgrgNgpgBAFRgZwC4FgBQXarmASwCcYBjVAMQDs4BDOAIzgF464AqRrHGPWqArWQww1FvmJlKVIA&html=DwCwLgtgNgfAsAKAAQqaApgQwCb2ag4CdMTJcMABwFp0BHAVwEsA3AXgCIBhAewDsw6AdQAqAT0roOSAMb9BAzoIAeYAPThoAbhkhMAJwDOJNgzAAzagA4OeQhqy5EhAEY9sYu6mBq3HvD6asEA&css=Q)

``` fsharp
module Test

let directFn a b = a * b

let aliasedFn = directFn
```
Gives
``` js
export function directFn(a, b) {
  return a * b;
}
export function aliasedFn(a$$1) {
  return function (b$$1) {
    return directFn(a$$1, b$$1);
  };
}
```

Aliasing with the points is a workaround of course.

**Comment by alfonsogarciacaro** [comment]
Sorry for the late reply @felixschorer and thanks a lot for reporting the issues. Point-free styling causes some issues because they're a bit hard to interpret from the F# AST, but the examples help a lot to spot the issues. I'll have a look at this and the other issues you reported.

**Comment by alfonsogarciacaro** [comment]
I tried to fix this and manage to make your sample code work, but there were many other cases that didn't, like using a static class member for `doesNotWork` or making `fortyTwo` accept 3 or more arguments. Thing is the AST generated by the F# compiler is very different when using point-free style and it even seems the type info is wrong in this case. So at the end I'm just emitting a warning recommending users to avoid point-free style. Hopefully this should be enough in most situations.

**Comment by alfonsogarciacaro** [comment]
Scratch that, the warning was raised in many situations and I think I found the way to fix it. It should work with 3.1.4.
