### ISSUE TITLE
Assigning a function with arity > 1 to a scoped mutable variable does not compile to valid Javascript

### ISSUE THREAD

**Issue by felixschorer** [fable-compiler/Fable#2046]
### Description

Assigning a function with arity > 1 to a scoped mutable variable does not compile to valid Javascript.

### Repro code

```f#
let fortyTwo () () =
    42

let all someFun =
    let mutable state = fortyTwo
    state <- someFun
    state

printfn "%A" <| all fortyTwo () ()
```

[Repl link](https://fable.io/repl/#?code=DYUwLgBAZg9gTmAngFQO4wgCgJRdwXgFgAoCMiAFgCYSTRIBDYYCAZxgFsQAxAVwDsIRUuXoQOvMAwBGoNlLAgh0eEjQwS5eQ0UQAPAFo2nHgM3lWCkLWIAHOAEt+YKIIBEAUgCCb-QB8IJhZYBBR0PDwgA&html=Q&css=Q)

### Expected and actual results

Expected: Does compile to valid Javascript.

Actual:
```
ERROR in ./src/App.fs 24:2
Module parse failed: Assigning to rvalue (24:2)
File was processed with these loaders:
 * ./node_modules/fable-loader/index.js
You may need an additional loader to handle the result of these loaders.
|   };
|
>   curry(2, state) = curry(2, someFun);
|   return curry(2, state);
| }
 @ ./src/App.fsproj 1:0-25 1:0-25
```

### Related information

* Fable version: 2.8.4
* Operating system: Windows 10 Pro 1903

**Comment by alfonsogarciacaro** [comment]
This took a while but should be finally fixed in 3.1.3 😸
