### ISSUE TITLE
Add support for Guid no hyphen string format

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#2055]
### Description

It appears using `System.Guid().ToString("N")` is not currently supported.

### Repro code

[Repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDKAngM4AuYAtqgOICuAlgCYAUAlPseVbY626gAqwAmSwMIAcxYAiAHIy2QA&html=DwQgJg9gxgLgngBwKYAIAWMC2AbAfAKGAxwMLSQEMwCUVgYBLGbJXAUQA8olsUBmAGwBWFAwB2KChLQQArgCdgAekbNW+WsExIYFdDBgIAtEgCOshgDcAvAHIAwhDEwkzowBVESWyihOXznYuHDBKxNgA3L5oFPIAzjrWsjAAZkYAHLY0dNq6KGIU2tYARJYMSADuCBDyMMW+-q4wJRUMYDBo1mBIZdxGre1oADSiYkwMFNhGcVCTSNYAjMXZwDPyDAgwKHHyUCUA+vsAEgDyAMruh0rYDABGcUrylLAAdAjyEGCysAxOL5jiF4AKziy2Uaw2MBWEM2212B2O50u+2udweTwosCMkEwbw+Xx+fwBYmBoNw4Kg6020PgLGytFunzgKAA3hpaByEFQwOIAOYALhQQgADAgOBF2RyUCl-EYUoUGNg4IK4lI4tMkOsUhKpQBffCSlC6W4sVmGhk1bryaZcqB8wWi8XmlCM+RWoyMgwQTCChZi7YQG5gFAAYiQwvD4Z1Updls1RnWvIwvv9cUDbVDkYjwujtH1hpgYCGBbQZpjKAGHUFIrFuY5rvdLBSMBTHADQcz2ajzob8ZgEAQrfbGbDXZzzq5YB5YgFQtrzoglk1KWwEAqgrQbW6YjrtGCMCMi+Xq-XKB4NwQcQYcTr+alhZeCRYsCQwbZ5cn09njtvBvvwfEBBkjLGNKzQQVZmwKAAAoFmFYUAFIUCMOcOAASl3dAkAYJMWxQAAmfD53LTBYl5cQHWIjl9U0JQ4lpdRlHIKhSGARkwDgFYeUsUQwBKUjxDBJRuIIZR2M4g0mKwPB8CAA&css=Q)

### Expected and actual results

```fsharp
System.Guid()
```

becomes

```js
"00000000-0000-0000-0000-000000000000";
```

where as:

```fsharp
System.Guid().ToString("N")
```

results in:

```bash
FABLE: Cannot resolve System.Guid.ToString
```

where it would be expected as:

```js
"00000000000000000000000000000000";
```

**Comment by alfonsogarciacaro** [comment]
At beginning we just compiled Guids to plain string and they've remained as such. However it should be possible to apply format options when `ToString` has an argument. The problem is that it's usually difficult to support all the format options in .NET. Do you know what other format options are available for Guids in .NET? Could you please write a function that formats a guid with hyphens accordingly?

**Comment by Shmew** [comment]
I can try taking a crack at it!

These are the options:

Specifier | Format of return value
-- | --
N | 32 digits:00000000000000000000000000000000
D | 32 digits separated by hyphens:00000000-0000-0000-0000-000000000000
B | 32 digits separated by hyphens, enclosed in braces:{00000000-0000-0000-0000-000000000000}
P | 32 digits separated by hyphens, enclosed in parentheses:(00000000-0000-0000-0000-000000000000)
X | Four hexadecimal values enclosed in braces, where the fourth value is a subset of eight hexadecimal values that is also enclosed in braces:{0x00000000,0x0000,0x0000,{0x00,0x00,0x00,0x00,0x00,0x00,0x00,0x00}}
