### ISSUE TITLE
How does non-string-keyed JS objects work?

### ISSUE THREAD

**Issue by cmeeren** [fable-compiler/Fable#2059]
See Electron's [ServiceWorkers.getAllRunning](https://www.electronjs.org/docs/api/service-workers#serviceworkersgetallrunning). It returns a `Record<Number, ServiceWorkerInfo>`, which I interpret as a JS object with numeric keys (integer in this case, I expect). How is this exposed in Fable, since objects can't have numeric property names? Double backticks? Something else?

**Comment by Zaid-Ajaj** [comment]
Converting it to `Map<int, ServiceWorkerInfo>` would probably get you the best results. Emitting `Object.keys($0)` on the object returns a runtime object that can be unboxed into `(int * ServiceWorkerInfo) list` and from there you can simply call `Map.pfList` on it

**Comment by cmeeren** [comment]
Are you sure I can unbox to `list` and not `array`?

**Comment by Zaid-Ajaj** [comment]
Oh yeah, you are right! my bad 😅 an `array` should work

**Comment by cmeeren** [comment]
Hm, but how do I code that? All the bindings in Fable.Electron are direct-to-JS abstract bindings. Currently I have this:

```f#
type ServiceWorkers =
  /// Returns an object where the keys are the service worker version ID (int) and the
  /// values are `ServiceWorkerInfo` objects.
  abstract getAllRunning: unit -> obj
```

I know how I can use `Emit` to call `Object.keys`, but I don't know how to mix in `Map.ofArray` there.

**Comment by cmeeren** [comment]
In any case, I am still wondering how Fable handles this. :)

**Comment by Zaid-Ajaj** [comment]
direct-to-JS bindings are very limited because you won't be able to call F# functions. Let me. First of all you can get to ` (int * ServiceWorkerInfo) array` easily like this:
```fs
type ServiceWorkers =
  /// Returns an object where the keys are the service worker version ID (int) and the
  /// values are `ServiceWorkerInfo` objects.
  [<Emit("Object.keys($0.getAllRunning())")>]
  abstract getAllRunning: unit -> (int * ServiceWorkerInfo) array
```
However, you can go just a bit further and create a nice *direct* type for the `int * ServiceWorkerInfo`:
```fs
type ServiceWorker =
  abstract id : int
  abstract info : ServiceWorkerInfo

type ServiceWorkers =
  [<Emit("Object.keys($0.getAllRunning()).map(tuple => ({ id: tuple[0], info: tuple[1] }))")>]
  abstract getAllRunning: unit -> ServiceWorker array
```

**Comment by cmeeren** [comment]
Thanks!

I know direct-to-JS bindings are limited, but in the scope of something as massive as Electron, it's unfortunately the only thing I have the capacity to do. (Not even that actually; I don't use Fable.Electron actively myself and would be grateful if someone that does can take over. I'll ping relevant folks regarding that later on.)

In any case, I'm still wondering how Fable handles non-string object keys. Do you know that?

**Comment by Zaid-Ajaj** [comment]
I don't think Fable does anything special to non-string object keys. Heck, I think Fable doesn't anything special with JS records. Though you can index `obj` by string if you open `Fable.Core.DynamicExtensions`. To index by int, you `unbox` your way into it:
```fs
module App

open Fable.Core.JsInterop
open Fable.Core.DynamicExtensions

let record = createObj [ unbox 1 ==> "one"; unbox 2 ==> "two" ]

Browser.Dom.console.log(record)

let one = record.[unbox 1]
let two = record.[unbox 2]

printfn "One is '%A', Two is '%A'" one two
```

**Comment by cmeeren** [comment]
Thanks!
