### ISSUE TITLE
Ts2Fable transforms only first module if multiple modules are defined in the same definition file

### ISSUE THREAD

**Issue by Krzysztof-Cieslak** [fable-compiler/Fable#206]
As in tittle, working on it.

**Comment by Krzysztof-Cieslak** [comment]
Looks like the problem exists when definition file is using `declare module XXX.YYY` syntax for nested modules instead of normal module nesting. 

Modified my definition file as workaround, will try to investigate more later.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report, I'll try to investigate it too.

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
