### ISSUE TITLE
Weird compilation error of valid code with open inside a module

### ISSUE THREAD

**Issue by l3m** [fable-compiler/Fable#2063]
### Description

I ran into a strange error in a larger Fable/Elmish project related to namespace imports with open. 

### Repro code
Unfortunately, I was not able to make a small project that reproduces the error, so I try to collect all the important information here. 

```fsharp
namespace Some.Engine.Savings 

open Some.Engine

module SuperSavings = 
    open Some.Engine.Savings

    ... 
```
I have code with the above import/open. When running in .net CLR, it works nicely. However, when running in Fable.Mocha tests it fails consistently, and sometimes also failed when running in webpack-dev-server. In webpack, generally a stop and complete rebuild made the problem go away. 

The error messages is as follows 
```
.../src/Engine.Test/Savings/TestSavings.fs(167,49): (167,101) error FSHARP: This expression was expected to have type
    'Engine.SavingsCalculationInputs'
but here has type
    'Engine.SavingsCalculationInputs (Engine, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null)'     (code 1)
```
and many other similar messages for other types. 

In our larger project (which I unfortunately cannot share) the error occurred reproducibly when moving the ```open Engine``` inside the module, and went away when the open was moved outside of the module to the top of the file below the namespace declaration.

The setup is as follows: 
- Engine - fsproj with the above code
- Engine.Test - fsproj with Expecto & Fable.Mocha tests that compile in the CLR and fail in Fable.

### Expected and actual results

Expected: Code should compile in Fable as it does in .Net. 
Actual: Compilation error as above. 

### Related information

fable-splitter 2.1.13
fable-compiler 2.10.0

OS: Windows 10 Enterprise, 1909

**Comment by alfonsogarciacaro** [comment]
Hmm, sometimes happens that Fable and dotnet sdk are using different F# compiler versions and you may get different type checking errors. If you're using fable-compiler 2.10.0 it should be equivalent to the most recent F# compiler version, are you using the latest dotnet sdk? If not, can you try upgrading to 2.1.300 and see if you get the same compilation error when building?

**Comment by l3m** [comment]
This was done on dotnet 3.1.202, but I had an older fable-compiler first then upgraded to latest when I got the error. 

I'll try to repro.

**Comment by l3m** [comment]
I confirm I can reproduce the error with latest dotnet (3.1.300) and fable-compiler 2.10.0. 

I realize that opening the namespace the module is in inside the module is probably broken or at least pointless (I assume it's a leftover by whoever originally wrote this code), but I still feel that the different behavior of Fable and dotnet-compilation is confusing and the error message doesn't really help...

**Comment by alfonsogarciacaro** [comment]
The thing is there're two steps in Fable compilation: F# compilation (well, type checking and AST generation) and Fable compilation. The first step is being done by the F# compiler services and all the error messages that are prefixed by `error FSHARP:` come from this step, before Fable does anything. So there's not much we can do about it unfortunately :/

**Comment by l3m** [comment]
@alfonsogarciacaro Hmm, so this means that the F# compiler comes to a different result during compilation triggered by Fable and compilation triggered by dotnet build...because the identical code works nicely when building in .Net.

**Comment by alfonsogarciacaro** [comment]
Hmmm, looking at the error message in more detail it looks as if two types with same name in different assemblies are being referenced. This may be related to the fact that Fable gathers all the files in referenced projects and compiles them as a single project (maybe a reference to Some.Engine assembly is lingering around?), though I'm not sure.

Can you please run Fable in verbose mode and send me the output? (Basically, the generated compiler options passed to the F# compiler.) If you're using webpack you can activate it like:

```js
            {
                test: /\.fs(x|proj)?$/,
                use: {
                    loader: "fable-loader",
                    options: {
                        babel: CONFIG.babel,
                        cli: {
                            verbose: true
                        }
                    }
                }
            },
```

**Comment by l3m** [comment]
I can reproduce the error when compiling for unit tests with fable-splitter:

``` E:\platform\src\Flow.Test\node_modules\.bin\fable-splitter . -o ../../dist/Flow.Test.Fable --commonjs```

Not sure how to map the webpack loader fable options to this.

**Comment by alfonsogarciacaro** [comment]
Sorry, only just now when I'm reviewing old issues I realize I missed your last comment 😞 It's possible to pass more or less the same options to fable-splitter than fable-loader using a `splitter.config.js` file. However, given that fable-splitter is out-of-support now and I couldn't reproduce the issue I'm closing this for now. Please reopen if you something similar with Fable 3.
