### ISSUE TITLE
Can't access private modules from within the same namespace but a different file; can in F#

### ISSUE THREAD

**Issue by stkb** [fable-compiler/Fable#2069]
May be related to #696 and fsharp/FSharp.Compiler.Service#690

Came across this discrepancy compared to standard F#. Trying to access a public function in a private module, from a 'sibling' module, where both modules are in different files but under a (the same) namespace.

The F# compiler is fine with this, but the Fable compiler gives the error:  "Cannot reference private members from other files".

### Repro code

Example code at [stkb/fable-private-modules](https://github.com/stkb/fable-private-modules) (a modified `dotnet new fable` project). In summary:

Inner.Private.fs:
``` fsharp
module private Inner.Private

let myFn a = a + 1
```

Inner.Internal.fs:
``` fsharp
module internal Inner.Internal

let myFn a = Inner.Private.myFn a
```

### Expected and actual results

```
$ cd src
$ dotnet build

  Determining projects to restore...
  Restored C:\fable-private-modules\src\App.fsproj
  App -> C:\fable-private-modules\src\bin\Debug\netstandard2.0\App.dll

Build succeeded.
    0 Warning(s)
    0 Error(s)

$ npx fable-splitter
fable-splitter 2.1.14
fable-compiler 2.10.0
C:\fable-private-modules\src> dotnet restore App.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.

Parsing ./App.fsproj...
...
C:/fable-private-modules/src/Inner.Internal.fs(3,13): (3,33) error FABLE: Cannot reference private members from other files: Inner.Private.myFn
fable: Compilation failed
```

### Notes

* The problem didn't exist in Fable v1 (found when upgrading a project)
* The workaround is to mark all your private modules as internal instead.
* fable-compiler 2.10.0
* Windows 10

Thanks for all your hard work guys!

**Comment by alfonsogarciacaro** [comment]
Thanks to you for the detailed report! Hmm, interesting, didn't know this was possible in F#.

I guess in order to fix it we need to make all members of a private **root** module public **outside** of the file, the same way all members of a private **nested** module are already public **within** the file.

**Comment by stkb** [comment]
I'm a bit clearer on this issue now and have modified the title accordingly.

I realised that it does work in Fable if you put everything in the same file, eg:
``` fsharp
namespace Inner

module private Private =
    let myFn  = ...

module internal Internal =
    // `Private` module accessible here; this works (correct)
    let anotherFn = Private.myFn ... 

namespace global

// Inner.Private not accessible from here (correct)
// Inner.Internal is
```
Just not if the namespace is split across files, as in the first example.

---

> I guess in order to fix it we need to make all members of a private **root** module public **outside** of the file, the same way all members of a private **nested** module are already public **within** the file.

I don't think this is right. Private modules should be:
- Accessible to all other code within the same namespace, and
- Inaccessible to all code that's in a different namespace.

The concept of "files" is irrelevant and shouldn't make any difference.

**Comment by stkb** [comment]
Also to clarify (and I had to test this), child namespaces are considered "in the namespace of" their parent, and everything comes under the **global** namespace (where all modules are put if you don't define a namespace explicitly). So private modules in the global namespace are accessible to everything.

**Comment by alfonsogarciacaro** [comment]
Well, my wording was probably not correct :) but I was talking about how Fable should represent those values in JS where there's no private or public, only scopes and import/export to cross file boundaries. From where you can access a private value in F# code is controlled by the F# compiler, but in JS we need to conform with JS practices to play well with tools like Webpack, tree shaking, etc. You can read a bit about how Fable translates F# modules here: https://fable.io/docs/communicate/fable-from-js.html

**Comment by stkb** [comment]
OK fair enough! Yeah I was gonna say, I don't know how it works in the implemtation.

**Comment by alfonsogarciacaro** [comment]
Closing for now as the solution to this is not trivial. Unfortunately we'll have a to keep as one of the caveat of transforming .NET namespaces into JS modules.
