### ISSUE TITLE
Compile to TS from fable-splitter

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#2072]
I saw @ncave's PR #2056, but setting my fable options in my `splitter.config.js` to 
```js
fable: {
    classTypes: true,
    typescript: true
}
```

Doesn't output ts files, am I doing something wrong or is this not available yet?

I'm running this on version 2.1.14

**Comment by ncave** [comment]
@Shmew Yes, it's not fully available yet. It will generate classes and type declarations in your .js files, but the `fable-library` files copied in your output are not going to be in TypeScript, and it won't rename your output files from `.js` to `.ts`.
