### ISSUE TITLE
2.10 "Compile Option.None as undefined" is a breaking change

### ISSUE THREAD

**Issue by AkosLukacs** [fable-compiler/Fable#2081]
### Description

[Material UI's datepicker](https://material-ui-pickers.dev/) seems to select the current date/time if you don't give it a value, or pass `undefined` as the value. It's empty only if you send in `null`. After updating to 2.10, all previously empty datepickers have the current date selected.

### Repro code

Demostration of this behaviour in JS: https://codesandbox.io/s/material-demo-7bm22?file=/demo.js 
The REPL still has an earlier version of the compiler, so can't repro there

### Expected and actual results

Expected: Updating to 2.10.1 won't break MUI datepickers :(
Actual: All empty pickers show the current day as selected value

### Related information

* Fable version: 2.10.1
* react 16.13.1
* @material-ui/pickers 3.2.10

Is there any workaround to explicitly change `None` to `null` in JS?

**Comment by alfonsogarciacaro** [comment]
We could revert the change and include it only in Fable 3, but I guess this will just postpone the problem a bit because the MUI bindings would have to be updated at some point. So I would suggest to apply a solution as @ncave proposes. `Option.toObj` should work too, although it may happen that it's broken now and doesn't give null for None but undefined, I will check.

**Comment by AkosLukacs** [comment]
Thanks for the input! It's kind of a strange decision on MUI picker's side, but they must have their reason...
Yes, there is no point in temporarily reverting to `null`, if changing to `undefined` is on the roadmap.
Going back to 2.9 and sending a PR to MUI Pickers to fix this should solve my problem.
Sorry for bothering you, probably should have just asked in the chat...

**Comment by alfonsogarciacaro** [comment]
No worries at all! It's totally fine to ask it here, particularly when it's something related to a recent change in the compiler :+1:
