### ISSUE TITLE
Fable tree-shaking

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2088]
Compatibility with Webpack tree-shaking is working quite well, but as suggested by @krauthaufen given that we have a typed AST we can even do better.

> Note I'm suggesting here to make additional tree-shaking to Webpack's, not trying to replace it.

Webpack tree-shaking cannot remove methods that are attached to prototypes (as is the case of interface implementations) but we could add an extra pass before Fable2Babel (only in compilation for production) that checks what interface methods are actually being invoked, and then remove the implementations if there is no implementation at all.

**Comment by MangelMaxime** [comment]
It would be really cool indeed 👍 

I wonder if we should make this pass optional for example if people generate a "library/bundle" that contains information that will be used via reflection. I suppose reflection is not the best example as it needs information via `inline` but I don't know how to explain my idea in another way.

**Comment by ncave** [comment]
It would be a wonderful feature, I agree, especially in cases where you can't use webpack or rollup on the output (when you want to preserve types, for example).

Yes, perhaps adding an attribute to opt out of it can help with building libraries.
Not sure how many passes the optimization will have to do, as some of those methods may be referencing each other.

What about when they're referenced by a method that gets dropped later by tree-shaking?
I wonder if it will be too hard to make it generic enough so it's not just for interfaces.

**Comment by krauthaufen** [comment]
Hey, basically this would render tree shaking unnecessary when doing a full dead-code elimination. Conceptually we could also try to find unused implementations when there is no instance ever being interpreted as a base-interface, etc. but those will be very hard to track.

Since this will be really tedious we should maybe come up with some general "optimization" api that allows information to propagate back and forth while modifying the TAST.

**Comment by alfonsogarciacaro** [comment]
I was hoping this could be an easy task but it's true it has many implications we need to take into account.

Also, [if we finally don't mangle interface names by default](https://github.com/fable-compiler/Fable/issues/2091#issuecomment-643868191), this feature would make less sense, because most interfaces could be potentially sent to JS so we cannot remove members.

**Comment by ncave** [comment]
Sure, to prevent breaking existing code, perhaps only enable this optimization with an opt-in switch.

**Comment by alfonsogarciacaro** [comment]
I'm closing as this has fallen out of Fable 3's scope but please reopen if anybody is willing to give it a try.
