### ISSUE TITLE
Documentation says that Arrays and ResizeArrays are compiled down to native arrays

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fable-compiler/Fable#2089]
### Description

Bumped into this updating Fable, Thoth, and moving off PowerPack.  React.Table 6 PageSizeOptiopns wants an array. Using `ResizeArray<'T>` works but `[| 5;10 |]` fails. Also `Array.isArray` says it is not an array. I'm not sure which is incorrect, the documentation, or the behavior.

### Repro code

```
[<Emit("Array.isArray($0)")>]
let isArray (x:obj) = jsNative
[<Emit("x[$0]")>]
let getFirst (x:obj) = jsNative
let values = [| 5;10 |]


let x: string = Encode.Auto.toString(2,values)
printfn "%A <- %A" (isArray values) x

getFirst values
|> printfn "Got First item? %A"

## Expected and actual results
Run in the Repl but also in my project
"true <- [5,10]"
5

actual:
"false <- [5,10]"
undefined

### Related information

* Fable version: 2.10.1 from yarn.  
* MacOs DotnetCore

**Comment by ncave** [comment]
@ImaginaryDevelopment
- As stated [here](https://fable.io/docs/dotnet/compatibility.html#Caveats), numeric arrays (with the exception of int64/uint64, decimal, bigint) by default are transpiled to JS [TypedArrays](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/TypedArray) (this behavior can be turned off with a compiler option `typedArrays)`.
- Array.isArray [returns false](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/isArray) for TypedArrays.
