### ISSUE TITLE
Make typedArrays=false the default in Fable 3?

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2090]
Issues like #2089 keep coming from time to time when typed arrays cause an unexpected problem when interacting with JS.

Maybe we should make `typedArrays=false` the default in Fable 3? So we can set the option only for applications that can benefit from this feature (like when self-compiling the F# compiler and Fable).

**Comment by ncave** [comment]
@alfonsogarciacaro Sure, if you think it makes sense as a default. It's turned off by default for typescript output as a temporary workaround until we can make it work well with types.

**Comment by alfonsogarciacaro** [comment]
As discussed in #2197, we are reverting this change to avoid breaking changes in existing code. However typed arrays will be disabled when outputting Typescript (see comment immediately above).
