### ISSUE TITLE
Improve type testing

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2092]
Following the increased reflection support we could try to overcome the current limitations in Fable's type testing:

- Allow testing interfaces (except the `NoMangle` ones as they're supposed to represent JS objects). For that we should include the implemented interface names in the type (we already did something similar in Fable 1).
- Allow testing generic types. For that we need to inject the name of generic arguments to the constructors.

**Comment by Shmew** [comment]
This would be great [look at this gross code](https://github.com/Shmew/FSharp.Control.AsyncSeq/blob/fable-support/src/FSharp.Control.AsyncSeq/AsyncSeq.fs#L794) 😅

**Comment by alfonsogarciacaro** [comment]
I've tried different approaches: injecting generics as arguments, wrapping the constructors, trying to infer the generics from private fields... but I was not convinced by anyone, as none was perfect and they introduced complications without opening interesting scenarios. The only cases I've seen this is need is to cross-compile code for .net and Fable, so for now I will just enable testing generic types with a warning saying the generics are not taken into account. Hopefully that should be enough for most cases.
