### ISSUE TITLE
Async.StartChild does not appear to apply the optional timeout parameter correctly

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2097]
### Description

`Async.StartChild` does not appear to apply the optional `timeout` parameter correctly. 

### Repro code

This code should time out. 

```fsharp
open Fable
open Fable.Core
open Fable.Core.JS
open System

module Async =

  let withTimeout timeout action =
    async {
      let! child = Async.StartChild (action, timeout)
      return! child
    }

(async {
    printfn "Started... "

    do!
      Async.FromContinuations ignore
      |> Async.withTimeout 3_000

    printfn "Finished. "
}
|> Async.StartAsPromise).catch (fun error -> console.error error)
|> ignore 
```

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgLAChSVolA6AYWACc1Nxp5kxCSaApAZQy2kYE8BnAFzAFsMGPsAAmAVxRQAgp3YQAxlAC8g9FCgpuUAO4BLbgAsAKrr5hgYrd1PnLUOPOvBoKtevuyFUAN4Z37zQBCKHkDXSQRZWlPeTxGbjhibgIwiKgACgcnCAAaKGszC24ASj9-KFJuMWIIYNDwkTL1AF9VTJifJqgQYl0IbgAzaAAieMTeETwpqGHVfxFgQK71GTlYmGJgPiJ+vrE4bM4oXQBzCDplqAAfAD5otbw9QxNCuwBmAH0ABh+59x6+oMRjA+rpOAYwJMZhhWuhbvcFHEEkkZAAFTZ8MFgYp4eQHUIZAZiaBgYibYhQAC0d3kzk4wHwpPJUCZJFKcLup3OpCgGCAA&html=Q&css=Q)

### Expected and actual results

The program never terminates

### Related information

* Fable version: `2.10.1`
* Operating system: `Ubuntu 18.04`

**Comment by njlr** [comment]
Work-around using `setTimeout` (not rigorously tested!)

```fsharp
module Async =

  let withTimeout timeout workflow =
    Async.FromContinuations
      (fun (resolve, reject, cancel) ->
        let timer =
          setTimeout
            (fun _ ->
              sprintf "Task took longer than %ims! " timeout
              |> Exception
              |> reject)
            timeout

        let q =
          workflow
          |> Async.StartAsPromise

        q.``then``
          (fun x ->
            clearTimeout timer
            resolve x)
        |> ignore

        q.``catch``
          (fun exn ->
            clearTimeout timer
            reject !!exn)
        |> ignore
      )
```

**Comment by alfonsogarciacaro** [comment]
Well, not only is not being applied correctly but it's not applied at all 😉 https://github.com/fable-compiler/Fable/blob/7d02d3e690a9b15cb7ca823b90c20f46f13f2a37/src/fable-library/Async.ts#L56

Would it be possible to send a PR to add the `timeout` parameter to the method linked above?

**Comment by njlr** [comment]
https://github.com/fable-compiler/Fable/pull/2540
