### ISSUE TITLE
Witnesses

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2104]
Related #2101 #2083 

SRTP resolution in Fable is not good and fails many times as in the issues reported above. This is because the F# TypedTree didn't expose much information and Fable had to make its own rudimentary resolution.

Fortunately this is about to change thanks to Don Syme work to include witnesses for SRTP resolution in the TypedTree and expose them in the FCS API: https://github.com/dotnet/fsharp/pull/9510

Use the new FCS to take advantage of the witnesses and use the same STRP resolution as the F# compiler does.

**Comment by gusty** [comment]
Could this be related to #2135 ?

I am not sure as the SRTP call involved there is a simple one (no multiple type variables involved).

**Comment by alfonsogarciacaro** [comment]
Sorry @gusty, I just realized I missed #2135. Still get confused with the new UI for notifications 🤦 

Yes, definitely. When we can use the new witness feature we can let FCS handle SRTP, and remove Fable's custom (and buggy) resolution mechanism.
