### ISSUE TITLE
System.Boolean.TryParse

### ISSUE THREAD

**Issue by shazmodan** [fable-compiler/Fable#2111]
### Description

Fable might be missing an implementation of System.Boolean.TryParse method. 
I get the following error:
"Error FABLE: Cannot resolve System.Boolean.TryParse"

Many other parsers such as Int, Date, Double exists.

### Repro code

If you try using System.Boolean.TryParse you get a compiler error.
`System.Boolean.TryParse "true"`

### Expected and actual results

```
let (couldParse, parsedValue) = System.Boolean.TryParse "false";;
val parsedValue : bool = false
val couldParse : bool = true
```
Described here: [System.Boolean.TryParse](https://docs.microsoft.com/en-us/dotnet/api/system.boolean.tryparse?view=netcore-3.1)

**Comment by alfonsogarciacaro** [comment]
Yes, seems we're missing that one 😅 Would it be possible to PR a `parseBool` function in Typescript for the fable-library that behaves (more or less) like the .NET version? As an example, here's the `parseInt` version: https://github.com/fable-compiler/Fable/blob/7d02d3e690a9b15cb7ca823b90c20f46f13f2a37/src/fable-library/Reflection.ts#L111-L113

> We don't have a specific file for Bools so maybe this one could go in `Util.ts`.

**Comment by inosik** [comment]
See #2114.
