### ISSUE TITLE
UTF8.GetString fails in REPL

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2113]
### Description

`System.Text.Encoding.UTF8.GetString [|161uy|]` fails in the Fable REPL with `ReferenceError: Buffer is not defined`.

### Expected and actual results

Expecting the function to return a string.

### Related information

* Fable version: Online REPL

**Comment by ncave** [comment]
@kerams Yes, that was [fixed](https://github.com/fable-compiler/Fable/commit/8f3019aaa19645604af8c3005de6d28fae290981#diff-e4a94de612d7a11d921e9c6da4fa5cc3) in the Fable compiler some time ago, but the Fable REPL hasn't been updated in a while.

**Comment by MangelMaxime** [comment]
Thank you @ncave 

I republished a new version of the REPL.
