### ISSUE TITLE
error FABLE: Cannot resolve System.Type.MakeGenericType

### ISSUE THREAD

**Issue by lfr** [fable-compiler/Fable#2119]
https://github.com/fable-compiler/Fable/blob/cc99764047953681dfe03551011cfe8a631be07b/tests/Main/ReflectionTests.fs#L471

I'm not sure what to make of this error as it seems this same method is used in a test that seems to work according to the comments.

**Comment by alfonsogarciacaro** [comment]
This was added recently, what version of fable-compiler are you using? `npm show fable-compiler version`

**Comment by lfr** [comment]
@alfonsogarciacaro it says 2.10.1

**Comment by lfr** [comment]
Not sure what happened but I can no longer reproduce this issue, this is a list of the remaining 'cannot be resolved' issues, is there anything here that you reckon should be working? If not I'll close this issue.

- System.Delegate.CreateDelegate
- System.Delegate.DynamicInvoke
- System.Reflection.MemberInfo.get_DeclaringType
- System.Type.GetMethod
- System.Reflection.MethodInfo.MakeGenericMethod
- System.Reflection.MethodBase.Invoke
- System.Type.IsAssignableFrom
- Microsoft.FSharp.Reflection.UnionCaseInfo.get_DeclaringType
- System.Type.GetInterfaces
- System.Type.get_GUID
- System.Type.GetMethods

**Comment by alfonsogarciacaro** [comment]
As the method in the issue title is already supported, let's close this in favor of #2321 (I've added a link to the comment above just in case)
