### ISSUE TITLE
Support for System.Nullable<'t>

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2121]
### Description

It looks like defining types with `System.Nullable<'t>` works but once you start actually constructing or using them, they are not recognized by Fable:

### Repro code

```fs
open System 

let content = Nullable 42
Console.WriteLine content.HasValue
Console.WriteLine content.Value
```
### Expected and actual results

Expected the code to compile and work (preferably the same way `Option<'t>` works) but it doesn't compile nor work

### Related information

* Fable version: 2.10.1 (latest as of the time of writing) 
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Nullables should be supported now 👍
