### ISSUE TITLE
Record with key toString causes type error exception

### ISSUE THREAD

**Issue by olivercoad** [fable-compiler/Fable#2133]
### Description

`toString` on javascript objects must be a function of type `unit -> string`.

----

I had an anonymous record which happened to have a label `toString`. This lead to the exception
`Uncaught TypeError: Cannot convert object to primitive value`.
The message about converting object to primitive value lead me to think it was a problem with my abstract type interfaces and JS interop so it took quite a while to find the problem which had nothing to do with js intererop.

It would be really useful to have a compilation error (or at least a warning) for any code that leads to `toString` on a javascript object having a value other than of type `unit -> string`.
Record type definitions and anonymous records come to mind but there are probably other cases that could be caught as well.

To be clear, the error is not due to fable and stems from javascript:
```javascript
String({toString: "foo"}) //Uncaught TypeError: Cannot convert object to primitiv...
```

### Repro code

Repro on [fable repl](https://fable.io/repl/#?code=DYUwLgBAZg9jEF4IG8A+BYAUBHEwwGUwAnASwDsBzRCAIgCMBDY2rVAXyyxIE8tcIABzLkwUcnVgwAXBACkAQVo4pWAO6kwACwggAHhAC0APn65hFMRNqLl+rEA&html=Q&css=Q)

```fsharp
let foo = {|
    toString = "bar"
|}

printfn "foo: %A"  foo
```

### Expected and actual results

Expected:  
a compilation error on line 2 along the lines of "the record field toString must be of type unit -> string"

Actual:  
a runtime exception `TypeError: Cannot convert object to primitive value`

**Comment by alfonsogarciacaro** [comment]
The sample code seems to work correctly in the current repl so I'm closing for now. Please reopen if necessary.

**Comment by olivercoad** [comment]
The issue hasn't actually been fixed, just the Fable implementation of printfn or System.Object.ToString() or something as called in F#. Any **js** code that tries to get a [text representation of an object](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/toString#description) will still fail. 

Repro on [fable repl](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwFgBQBA2gDwCiAtgJYAuAFAEQDKNWVEA5nQCQAMAlA34A+ALoEUNKACsAzgBVgLNpyjAoAXhmyAcnBpUAbnkL5JUAGbB1WgN4AfAlGdQaS1uw6aoDBHCwMBPYAvgQErACeTi7mVu5Y3nKKyp6W1tHOICo0FtAMcQBcUACksgzOccoEAO60ABZQYAAeUAC0whlQWew5ecUAguXNQA&html=Q&css=Q)

```
open Fable.Core

[<Emit("String($0)")>]
let jsToString o = jsNative

let foo = {|
    toString = "bar"
|}

try
    let fooStr = jsToString foo
    printfn "foo: %s"  fooStr
with ex ->
    printfn "%A" ex
```

**Comment by alfonsogarciacaro** [comment]
Ah, you're right. Sorry I missed that. Although I'm still unsure if we should add a compiler check for this. That's because this would require a lot of defensive code for a (likely) rare case. To do it well we would have to check anonymous records, records and interfaces. And also consider similar "native" JS methods like `toJSON`. There are already several things that are not checked by the compiler or at runtime (array boundaries, unsafe casting...) and for example Typescript, a language that goes a great deal to make JS "type-safe", doesn't emit any warning if you do something like:

```js
const foo = String({
  toString: "foo"
})
```
