### ISSUE TITLE
Prevent fable compiler from running `dotnet restore`

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#2134]
Some build pipelines separate restore and build stages and prevent restores from happening in the build stage.
Right now this behavior leads to a broken build even though everything is already restored by the time Fable is called.
I'm looking for a way to tell fable not to run the restore, as I'll be restoring everything ahead of time.

**Comment by alfonsogarciacaro** [comment]
Sorry, I just realized I completely missed this! 🤦 At one point during Fable 3 development we had a `--noRestore` option. It seems I removed it, but it shouldn't be difficult to bring it back.

**Comment by alfonsogarciacaro** [comment]
Next Nagareyama release will include a `--noRestore` cli option
