### ISSUE TITLE
Problem with object expressions

### ISSUE THREAD

**Issue by stkb** [fable-compiler/Fable#2139]
1. Create an abstract base class with an abstract member function, where that member function is called within the constructor (in a do-expression)
    ``` fsharp
    [<AbstractClass>]
    type AbstractBase () as this =
        do this.sayHello ()
        abstract member sayHello : unit -> unit
    ```
2. Create an object expression that derives from that abstract base class, and implements/overrides the abstract member function.
    ``` fsharp
    let objectExpression () =
        { new AbstractBase () with
            override this.sayHello () = printfn "Hello %s" "Object Expression"
        }
    ````
**Expected**: In standard F# this is fine; the implemented function is called in the base class's constructor
**Actual**: With Fable this fails with error `this$.contents.sayHello is not a function`

Rest of the example code ([Repl link](https://fable.io/repl/#?code=NoHgggRgzgLgTgQwMYwMIBsFSgPgLoCwAUDAJ4AOApgASSyIoBCWNAFAJTVbUwAWAllGoBeYtXHUAJgHseAqADooCUgAlK6dLI5iJCaPGQxqAW0omIlONWVqNW6gC5qAVwB2-YwFocrjzGJidEpjaQgAK0oUAFEAD3I4Smx+aTdqDhFdcQBvajdKAHdaAwYYZig2TgLPXiyJcWkANys4fkkaPkElFXVNbU5hagT+NxgAMzSAIl6HAFIoSepJgHkIqOM4hKSoFLdJuoBfQJIKGlRUpESYSgAVU-SBupHeK09i+iNyyrqmlraaAD63TsfQeIiGrVGEyWM1k80Wk3ObkuIRodyo+yIxCRKOu6Mq1AAPr5+ABzNzSRLEMKRGLxRLJVJg4nUMkUqlEIA&html=Q&css=Q)). The `ConcreteType` is just added for comparison (that works fine).

``` fsharp
type ConcreteType () =
    inherit AbstractBase ()
    override _.sayHello () = printfn "Hello %s" "Concrete Type"

ConcreteType () |> ignore
objectExpression () |> ignore
```

Javascript. The problem is where the `extend` function is called within the `objectExpression` function; it calls the base class constructor *before* adding the member functions.
``` javascript
import { declare, FSharpRef } from "fable-library/Types.js";
import { class_type } from "fable-library/Reflection.js";
import { toConsole, printf } from "fable-library/String.js";
import { extend } from "fable-library/Util.js";
export const AbstractBase = declare(function Test_AbstractBase() {
  const $this$$1 = this;
  const this$ = new FSharpRef(null);
  this$.contents = $this$$1;
  $this$$1["init@2-140"] = 1;
  this$.contents.sayHello();
  void null;
});
export function AbstractBase$reflection() {
  return class_type("Test.AbstractBase", undefined, AbstractBase);
}
export function AbstractBase$$$$002Ector() {
  return this instanceof AbstractBase ? AbstractBase.call(this) : new AbstractBase();
}
export const ConcreteType = declare(function Test_ConcreteType() {
  const $this$$2 = this;
  AbstractBase$$$$002Ector.call($this$$2);
  $this$$2["init@6-141"] = 1;
  void null;
}, AbstractBase);
export function ConcreteType$reflection() {
  return class_type("Test.ConcreteType", undefined, ConcreteType);
}
export function ConcreteType$$$$002Ector() {
  return this instanceof ConcreteType ? ConcreteType.call(this) : new ConcreteType();
}

ConcreteType.prototype.sayHello = function () {
  const arg10 = "Concrete Type";
  const clo1 = toConsole(printf("Hello %s"));
  clo1(arg10);
};

export function objectExpression() {
  return extend(AbstractBase$$$$002Ector(), {
    sayHello() {
      const arg10$$1 = "Object Expression";
      const clo1$$1 = toConsole(printf("Hello %s"));
      clo1$$1(arg10$$1);
    }

  });
}

(function () {
  const value = ConcreteType$$$$002Ector();
  void value;
})();

(function () {
  const value$$1 = objectExpression();
  void value$$1;
})();
```

Fable v2.10.2

Thanks!

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! I think we can fix the issue by generating a class expression for inheriting object expressions instead of using the `extends` helper (as in `new (class extends AbstractBase { ... })()`). It may make more sense to do it in Fable 3 where everything will be compiled as classes by default. Would it be ok for you to use the workaround for now and wait until Fable 3 beta for the fix?

**Comment by alfonsogarciacaro** [comment]
Fixed in nagareyama branch (Fable 3).
