### ISSUE TITLE
Fable cannot resolve module.exports = factory(require('react'))

### ISSUE THREAD

**Issue by halcwb** [fable-compiler/Fable#2141]
### Description

I want to load a react library: [react-number-format](https://github.com/s-yadav/react-number-format). However the syntax to import the react module is not the normal import:

```javascript
(function (global, factory) {
  typeof exports === 'object' && typeof module !== 'undefined' ? module.exports = factory(require('react')) :
  typeof define === 'function' && define.amd ? define(['react'], factory) :
  (global = global || self, global.NumberFormat = factory(global.React));
}(this, function (React) { 'use strict';

  React = React && React.hasOwnProperty('default') ? React['default'] : React;

 // etc...
```

When I try to load this code using:

```fsharp
        static member inline numberformat props : ReactElement = 
            ofImport "default" "react-number-format" (keyValueList CaseRules.LowerFirst props) []  
```

The fable compiler complains that react is not defined: 

> Module Error (from ./node_modules/fable-loader/index.js):
> C:/Development/Informedica/apps/Feliz.MaterialUI.Components/src/Client/NumberFormat.fs(16,39): (16,44) error FSHARP: The namespace or module 'React' is not defined. Maybe you want one of the following:
>    React_number_format (code 39)
> 

I guess this is because the normal way to import like: `import React from 'react'` is not used.

Is there a work around? For example creating a local js file that performs the imports of react and react-number-format? 

### Related information

* Fable version: 2.10.2
* Operating system

**Comment by alfonsogarciacaro** [comment]
Well, Fable doesn't resolve modules, that's left to your bundler or JS runtime :) The error you posted seems to be a type error. It's difficult to say without seeing the rest of the code, but maybe some open statement is missing (e.g. `open Fable.React`)?

**Comment by halcwb** [comment]
@alfonsogarciacaro. Of course, my bad, thanks.
