### ISSUE TITLE
Newbie: access custom property of the window object without JS interop

### ISSUE THREAD

**Issue by lucabol** [fable-compiler/Fable#2168]
Hi there, sorry for the beginner question. I am working with a Log-In widget that adds a new property to `window` which contains data about the identity of the user who logged in.

Perhaps with JS interop (i.e. Emit) it is possible to get to this property somehow, but that would make the code less portable as it assumes that it is compiled down to JS (i.e. can't be used in a webassembly).

As there is a Browser.Dom.window object, I was wondering if there is a pure F# way to get to its properties.

MORE DETAILS 
In index.html
```html
<!doctype html>
<html>
<head>
  <title>TRL</title>
  <meta http-equiv='Content-Type' content='text/html; charset=utf-8'>
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.4/css/bulma.min.css" />
  <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" 
        integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous" /> 
  <link rel="shortcut icon" href="fable.ico" /> </head>
<body>
    <div data-netlify-identity-button class="button is-primary is-large is-rounded is-focused"></div>

    <div id="elmish-app"></div>
    <script src="bundle.js"></script>
    <script type="text/javascript" src="https://identity.netlify.com/v1/netlify-identity-widget.js"></script>
</body>
<HTML>
```

**Comment by MangelMaxime** [comment]
Could please show us what you would write in JavaScript ?

Also, you mention webassembly but for now support for webassembly is not planned in Fable development.

If you want to write something like that: `Browser.Dom.window.myProperty` you can:

- Use dynamic typings  `Browser.Dom.window?myProperty` by opening `Fable.Core.JsInterop` but it is not recommanded because not typed
- Use type augmentation to add the new property to `Browser.Dom.window` type.

```
open Fable.Core
open Browser.Types

type Window with
       member __.myProperty with get(): MyProperty= jsNative
```

**Comment by lucabol** [comment]
Hi, thanks for the prompt reply. I will try the type augmentation solution.
