### ISSUE TITLE
TypedArray set method has incorrect signature

### ISSUE THREAD

**Issue by Shmew** [fable-compiler/Fable#2169]
The `Fable.Core.JS.TypedArray<'T>` seems to have an incorrect signature for the `set` method. You can it in action [here](https://fable.io/repl/#?code=PTAEHUCcEsBcFNQGMD2ATRLKgDYoIZqj6gDO+AtgA46IBmkKFZ0GARvpALABQKV8AHagAYvja0AdAGEs8XvyGjxU2ZHiSAUqQCSghIyoKBwgMoBPUggq9etWKDYBXOnXjYAvKE2mZKQVaQTkiwWKSSAIKQkPjmAEIubpAy6vgIABQAHACUdvAOTtD6mVGe3r6yAbBBIWGSAKpFsCXRsSnwafDpzq7uuTx5DghWoF6FxaWSpPnpANoAPgCMANwATMsAzPMAugA0oBv9vFQw+nTCAEQApBEXoOPNpcensOeg17egw7BAA&html=Q&css=Q).

I haven't gone through the rest of the api of it, but there may be other cases where the method signature should return `unit` rather than `TypedArray<'T>`.

**Comment by alfonsogarciacaro** [comment]
Ups, I guess we don't use directly typed arrays often because numeric arrays already convert to typed arrays. Thanks for spotting it! Would it be possible to send a PR with the fix so we can publish a new version?

**Comment by Shmew** [comment]
Yeah sure thing. I'm in the middle of implementing message pack protocol for `Fable.SignalR` but didn't want to forget.
