### ISSUE TITLE
"Maximum call stack size exceeded" when comparing relatively large sets (Fable 3)

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2203]
### Description

Comparing relatively large sets in Fable 3 throw an error "Maximum call stack size exceeded". This issue does not occur in current Fable 2.x

### Repro code

```fs
testCase "Comparing large sets works" <| fun _ ->
    let largeSetA = Set.ofArray [| for i in 1 .. 80_000 -> i |]
    let largeSetB = Set.ofArray [| for i in 1 .. 80_000 -> i |]
    Expect.equal largeSetA largeSetB "The sets are equal"
```

### Related information

* Fable version: 3.0.0-nagareyama-alpha-009
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for catching this! This must related to the new Map/Set implementation #2188 

I haven't checked the dotnet/fsharp tests but I guess (hope) this won't affect .NET F#. Maybe it's an issue with mutually recursive functions as tail call optimization for this case is not supported in Fable. I will have a look to see if we can fix it. If not, we may need to go back to the old implementation.
