### ISSUE TITLE
printf "%A" on a string

### ISSUE THREAD

**Issue by naartjie** [fable-compiler/Fable#2207]
### Description

The printf functions behave differently in Fable than on .NET, with the `%A` format specifier and a string value:

### Repro code

```fsharp
printf "%A" "value"
```

### Expected and actual results

Expected: `"value"` (the same as on .NET)
Actual: `value`

### Related information

* Fable version: e0a6e01f (latest `nagareyama` branch at the time of writing)
* Operating system: macOS

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @naartjie! Unfortunately there are many places where the string formatting differs between Fable and .NET. We're not trying to make it identical as it is quite challenging sometimes especially with types that map to JS native ones. The main goal is to make printing as informative as you would expect when using .NET.

**Comment by alfonsogarciacaro** [comment]
Let's close this for now, please reopen if you've any other suggestion/comment.
