### ISSUE TITLE
Code splitting is no longer compatible for Fable 3

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2211]
When working with F#/Feliz, sometimes we export a React component from a file say `Component.fs` and then import dynamically from another file, say `App.fs`. Now the import statement is pointing to the F# file:
```fs
let asyncComponent : JS.Promise<unit -> ReactElement> = JsInterop.importDynamic "./CodeSplitting.fs"
```
But this doesn't work because there is no loader anymore from webpack and one should instead use `./CodeSplitting.fs.js`

Would it be possible to detect this case when importing values from F# modules and appending `.js` to them in Fable 3?

**Comment by alfonsogarciacaro** [comment]
Yes, should be feasible. I'll have look :+1:
