### ISSUE TITLE
Code printer for Fable 3: redundant comma added to disposables?

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2214]
### Description

Given this piece of code:
```fs
let createDisposable() =
    let value = {  new System.IDisposable with  member this.Dispose() = printfn "Disposed" }
    value
```
It generates:
```js
export function createDisposable() {
    const value = {
        Dispose() {
            String_toConsole(String_printf("Disposed"));
        }
        ,
    };
    return value;
}
```
There is a comma after the definition of the `Dispose()` function. It doesn't seem to cause a syntax error, but maybe it is possible to clean it up? 

### Related information

* Fable version: 3.0.0-nagareyama-alpha-014
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Hmm, trailing commas are accepted in JS objects and I think some style guides even recommend it. But it doesn't look nice at all when appearing after the line break. We can try to fix that :+1:

**Comment by Zaid-Ajaj** [comment]
New line is removed as of  3.0.0-nagareyama-alpha-015 and it looks better :)
