### ISSUE TITLE
Map.change problem.

### ISSUE THREAD

**Issue by p1eXu5** [fable-compiler/Fable#2222]
### Description

When I try to use change function from Map module I get this error: 
Uncaught TypeError: (0 , _fable_fable_library_2_13_0_Map_js__WEBPACK_IMPORTED_MODULE_4__.change) is not a function

### Code

```fsharp
    let onClick key =
        this.setState (fun state _ ->
            state
            |> Map.change key (fun v -> v |> Option.map (fun v' -> v' + 1))
        )
```

#### Generated code:

```javascript
function App$$onClick$$Z721C83C5(this$, key) {
  this$.this.contents.setState(function (state, _arg1) {
    const table$$1 = state;
    return (0,_fable_fable_library_2_13_0_Map_js__WEBPACK_IMPORTED_MODULE_4__.change)(key, function f(v) {
      const option = v;
      return (0,_fable_fable_library_2_13_0_Option_js__WEBPACK_IMPORTED_MODULE_8__.map)(function mapping$$1(v$0027) {
        return v$0027 + 1;
      }, option);
    }, table$$1);
  });
}
```

Why this happens and how to solve this problem?

### Related information

* Fable version: 2.13.0 
* Operating system: win10

**Comment by alfonsogarciacaro** [comment]
I guess because we don't have a replacement for that function yet, actually I didn't know it existed until now 😅

**Comment by alfonsogarciacaro** [comment]
I just realized this is fixed in Fable 3 with the new Map implementation, I added a test for that :+1:
