### ISSUE TITLE
ofImport not working in nagayerama beta 002

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2224]
### Description

Whenever I try to use Fable:React.Helper's ofImport function I get an error in fable 3 beta002:

    D:/code/eCarApp/src/Client/.fable/Fable.React.7.0.1/Fable.React.Helpers.fs(164,42): (164,72)
       error FABLE: Cannot resolve Fable.Core.JsInterop.import - Inline call from ../../Pagination.fs(57,4)

### Repro code

![image](https://user-images.githubusercontent.com/57396/96993887-34973080-152c-11eb-9d96-9eb623829efb.png)

### Expected and actual results

Fable 3 working backwards compatible or suggesting a fix

### Related information

 F# to JS compiler 3.0.0-nagareyama-beta-002

**Comment by forki** [comment]
simple repro in #2225

**Comment by alfonsogarciacaro** [comment]
Hopefully fixed in beta 3

**Comment by kerams** [comment]
Works for me, thanks.
