### ISSUE TITLE
error FABLE: Cannot reference entity from .dll reference: Chia.Shared.Ids.SortableRowKey

### ISSUE THREAD

**Issue by tforkmann** [fable-compiler/Fable#2237]
### Description

Chias shared model doesn't get fully compiled.
I get following error message:

```error FABLE: Cannot reference entity from .dll reference: Chia.Shared.Ids.SortableRowKey```

### Repro code

The module inside Chia looks like this:
```fs
module Ids =
        type ReportId =
            | ReportId of reportId: int
            member this.GetValue = (fun (ReportId id) -> id) this
            member this.GetValueAsString = (fun (ReportId id) -> string id) this


        type SortableRowKey =
            | SortableRowKey of string
            member this.GetValue = (fun (SortableRowKey id) -> id) this

        module SortableRowKey =
            let toRowKey (dateTime: DateTime) =
                String.Format("{0:D19}", DateTime.MaxValue.Ticks - dateTime.Ticks) |> SortableRowKey
            let toDate (SortableRowKey ticks) = DateTime(DateTime.MaxValue.Ticks - int64 ticks)
```

Is there any way to get this working?

### Expected and actual results

Module should get compile

### Related information

* Fable version: 3.0.0-nagareyama-beta-003
* Operating system: Windows 10

**Comment by Zaid-Ajaj** [comment]
@tforkmann Is Chia compiled as a shared library or referenced as a project? If it is a library where you don't have access to the source code, then you can make it Fable-compatible by publishing the sources as well like all Fable packages do

**Comment by alfonsogarciacaro** [comment]
Yes, as @Zaid-Ajaj says, you need to include the F# sources in the package for Fable to be able to compile and access the code as in here: https://github.com/Fulma/Fulma/blob/0e7330d95f7555710dde1f0f992732b9bb357a43/src/Fulma/Fulma.fsproj#L68-L71

Maybe we should improve the error message 🤔

**Comment by tforkmann** [comment]
Thanks guys! That worked!

**Comment by joprice** [comment]
@Zaid-Ajaj I'm getting the same error when using `ProjectReference` with a plugin defined in the same project. Is it possible to get that to work, or does it have to be published separately?

**Comment by tforkmann** [comment]
@joprice If possible get rid of Chia since the maintainer of that project arent working at that company anymore.

**Comment by joprice** [comment]
Thank you, but I'm not using Chia. This is for a separate compiler plugin I've written locally.

**Comment by tforkmann** [comment]
ahh ok

**Comment by joprice** [comment]
I just noticed that the errors are actually for transitive dependencies. Not sure if that helps clarify the error:

```
error FABLE: Cannot reference entity from .dll reference, Fable packages must include F# sources: Fable.MemberDeclarationPluginAttribute
error FABLE: Cannot find Fable.AST.Fable.Ident constructor
error FABLE: Cannot find Fable.AST.Fable.Expr constructor
error FABLE: Cannot find Fable.AST.Fable.ImportInfo constructor
error FABLE: Cannot find Fable.AST.Fable.MemberDecl constructor
```
