### ISSUE TITLE
Map.toSeq creates a seq backed by a mutable iterator, does not match dotnet runtime behaviour

### ISSUE THREAD

**Issue by anchann** [fable-compiler/Fable#2242]
### Description

The `Map.toSeq` call produces a seq that is backed by a mutable iterator, so calling any function on it consumes it. This is contrary to how things work in the dotnet runtime.

### Repro code

```
let pr (sequence: seq<int * string>) =
    let strValue =
        sequence
        |> Seq.map (fun (i, v) -> v)
        |> String.concat ", "
    printfn ">%s<" strValue

let someSeq = Map.ofList [(1, "a"); (2, "b")] |> Map.toSeq
pr someSeq
pr someSeq
```

### Expected and actual results

In Fable, this code produces

```
>a, b<
><
```

while in dotnet fsi it produces

```
>a, b<
>a, b<
```

### Related information

* Fable version: 2.10.1
* Operating system MacOS 10.15.7

**Comment by ncave** [comment]
Seems to work fine in Fable 3.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the report @anchann! I've added your example to Fable tests. Given it's working in Fable 3 (we're using the new Map implementation from FSharp.Core), I'll close this as our development resources are limited and we are focused on releasing a stable Fable 3 version, so it's difficult to update Fable 2 to fix bugs. I hope that's ok with you.
