### ISSUE TITLE
The type 'DataContract' is not defined. (code 39)

### ISSUE THREAD

**Issue by ThisFunctionalTom** [fable-compiler/Fable#2253]
### Description

Putting the code below into QuickTest.fs on master branch works and 
running `npm run build quicktest` the test succeeds 
but on nagareyama branch the compiler write following errors:
```
Initializing F# compiler...
Compiling ..\quicktest\QuickTest.fsproj...
F# compilation finished in 1622ms
Skipping Fable compilation of up-to-date JS files
Fable compilation finished in 6ms
C:/Users/leko.tomas/private-source/Fable/src/quicktest/QuickTest.fs(72,3): (72,15) error FSHARP: The type 'DataContract' is not defined. (code 39)
C:/Users/leko.tomas/private-source/Fable/src/quicktest/QuickTest.fs(74,5): (74,15) error FSHARP: The type 'DataMember' is not defined. Maybe you want one of the following:
   DateTime (code 39)
C:/Users/leko.tomas/private-source/Fable/src/quicktest/QuickTest.fs(75,5): (75,15) error FSHARP: The type 'DataMember' is not defined. Maybe you want one of the following:
   DateTime (code 39)
C:/Users/leko.tomas/private-source/Fable/src/quicktest/QuickTest.fs(76,5): (76,15) error FSHARP: The type 'DataMember' is not defined. Maybe you want one of the following:
   DateTime (code 39)
C:/Users/leko.tomas/private-source/Fable/src/quicktest/QuickTest.fs(77,5): (77,15) error FSHARP: The type 'DataMember' is not defined. Maybe you want one of the following:
   DateTime (code 39)
Watching ..\quicktest
```

### Repro code

```fsharp
open System.Runtime.Serialization

[<DataContract>]
type Person = {
  [<DataMember(IsRequired = true)>] FullName: string
  [<DataMember(IsRequired = true)>] TimeOfBirth: DateTimeOffset
  [<DataMember(IsRequired = true)>] NumberOfChildren: int
  [<DataMember(IsRequired = true)>] IsAlive: bool
}

testCase "Struct with DataContract can be created" <| fun () ->
    let person =
        { FullName = "Max Maxwell"
          TimeOfBirth = DateTimeOffset(1975, 2, 7, 10, 32, 11, TimeSpan.Zero)
          NumberOfChildren = 2
          IsAlive = true }

    person.FullName |> equal "Max Maxwell"
    person.NumberOfChildren |> equal 2
    person.IsAlive |> equal true
```

### Expected and actual results

I would expect the nagareyama to compile this excatly as fable 2 did.

NOTE: If someone could just explain shortly what could be the problem and in which direction to search I would like to help solving this problem if it is not to hard for an intermediate F# developer 😄 .

I am a big fan of Fable. Please continue the magnificent work. 🤩

**Comment by alfonsogarciacaro** [comment]
Hmm, Fable is not compatible with System.Runtime.Serialization. Because Fable doesn't compile attributes, I'm assuming Fable 2 just ignores DataContract and DataMember. In Fable 3 I removed references to assemblies that don't contain classes supported by Fable to make the build cleaner. We can add back the System.Runtime.Serialization reference to fix this (or just reference all the .net bcl assemblies as before).

**Comment by ThisFunctionalTom** [comment]
As you said, you left the references to assemblies not supported by Fable to make the build cleaner and I think you should stick to it.
We can always put `#if !FABLE_COMPILER` arround the attributes (it looks ugly though 😅).

I think I will close this issue now.

**Comment by alfonsogarciacaro** [comment]
Thanks for your understanding @ThisFunctionalTom. If you use the attributes a lot, instead of using a lot of compiler directives, you can create an empty declaration of the attributes in just one place, like:

```fsharp
#if FABLE_COMPILER
namespace System.Runtime.Serialization
open System

type DataContract() = inherit Attribute()
type DataMember(IsRequired: bool) = inherit Attribute()
#endif
```

**Comment by ThisFunctionalTom** [comment]
> Thanks for your understanding @ThisFunctionalTom. If you use the attributes a lot, instead of using a lot of compiler directives, you can create an empty declaration of the attributes in just one place, like:
> 
> ```fsharp
> #if FABLE_COMPILER
> namespace System.Runtime.Serialization
> open System
> 
> type DataContract() = inherit Attribute()
> type DataMember(IsRequired: bool) = inherit Attribute()
> #endif
> ```

Oh, this is a wonderful tip. Thanks for it.
