### ISSUE TITLE
Key is overwritten when creating JS object

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2257]
with nagareyama RC2 we often see the following error.

![image](https://user-images.githubusercontent.com/57396/98542303-fa9a8e00-2290-11eb-9e73-53657bfd1ec9.png)

any ideas what that is?

**Comment by alfonsogarciacaro** [comment]
I introduced a check in keyValueList in debug mode (shouldn't happen when compiling for production) to see if the same property was being set more than once, hoping it would identify when, for example, we set the same react prop twice. But we can remove it if it gives false positives.

**Comment by forki** [comment]
dunno if we it's false positives. @atheheck

**Comment by alfonsogarciacaro** [comment]
Looks like the method and headers properties in the fetch object. It may be that Thoth.Fetch is setting them with default values and then your app is overwriting them, which shouldn't be an issue. I'll remove the warning.
