### ISSUE TITLE
Potential file conflict in fable 3

### ISSUE THREAD

**Issue by albertwoo** [fable-compiler/Fable#2259]
### Description

If I have a project structure like below:

```
Client
      Share
          Utils.fs
      App.fs
      Client.fsproj
Share
      Utils.fs
      Share.fsproj
```
Client has dependency on Share.
Run `fable watch . --outDir .clientjs` in Client folder, the output folder is like:
```
.clientjs
    .fable
    Share // looks like this folder is reflect the Share project
        Utils.js  // Client/Share/Utils.js will be used and the Share project`s Utils.js will be replaced
    App.js
```
### Expected and actual results

We should have a way to distinguish project and normal folder

### Related information

* Fable version: 3.0.0-nagareyama-rc-003
* Operating system: Windows

**Comment by ncave** [comment]
@albertwoo Is `Client/Client.fsproj` referencing `Share/Share.fsproj`? Or are you building them separately?

**Comment by albertwoo** [comment]
@ncave Yes. `Client/Client.fsproj referencing Share/Share.fsproj`
