### ISSUE TITLE
Cannot implement ICollection and IReadOnlyCollection

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2265]
### Description
I cannot implement both `ICollection` and `IReadOnlyCollection` on one type. 

### Repro code

```fsharp
open System.Collections
open System.Collections.Generic

type Foo<'t when 't : equality> (xs : 't list) = 

  interface IEnumerable<'t> with
    member this.GetEnumerator() = (xs :> _ seq).GetEnumerator()

  interface IEnumerable with
    member this.GetEnumerator() = 
      (xs :> _ seq).GetEnumerator() 
      :> IEnumerator
    
  interface IReadOnlyCollection<'t> with
    member this.Count = List.length xs

  interface ICollection<'t> with
    member this.IsReadOnly = true
    member this.Count = List.length xs
    member this.Add(i) = failwith "ReadOnlyCollection"        
    member this.Remove(i) = failwith "ReadOnlyCollection"    
    member this.Clear() = failwith "ReadOnlyCollection"
    member this.Contains(x) = List.contains x xs
    member this.CopyTo(arr, i) = failwith "todo"
```

https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoDCwA2OwDGSAlsBAgFCiSyIobZ6ElkLoDikYATsQRRSRxwUAGLBgAHgDkSKAHcAFjVlQAXFDABHAK4BDHMSEA+KAAoAHgnVRVh5AEooAXigCoUYhBTcAZnoIwKABJAFEIHVQePQAjfBkkU3kjRQoPDyjUGJ4oJEViNk4kcMjopGBuMydXS2s1UwB9KARtBw4wYoio7j1yyod3T28ef0CQku7Y-AUUtPTM7O5c-MKOibKKqpc3dPTa9Ubm1vbO0p6+rbnd+vGuje4rnaGfUaDggCUwPQATAHkIHBwRj4IikCAJJKzXYLHJ5ApYYA6bzbAAyBSQ6HwEAA5nkoFZBl4XgE3sDmGCITM8o8YUs4WxgghPj9-oDtkhuDowDS0ItlvDsEi5K40chMZBcYp8ZRobzYSt0ABBb7fMzEapQfzEHDJPEAImZfwBQNwIJYED1u12PKy8vhn1QwAAbmA1RqtTqUlADV8jYCyaCyJb0ja+fSsPg9P1th7dVKfSzjQHzXrQ3a2NhvHovAhLBrRRiCGQkNnyPjpWm6QrsCA4AAVYBmKPcAA0nnd2c9+vK32AqaAA&html=Q&css=Q

### Expected and actual results

```
FABLE: 
  Cannot implement two record/interface/abstract members with same name: 
    System-Collections-Generic-IReadOnlyCollection`1-get_Count / 
    System-Collections-Generic-ICollection`1-get_Count
```

I guess this is a name mangling issue?

Note that for `IEnumerable` I was able to work around this. 

### Related information

* Fable REPL `2.1.1`

**Comment by alfonsogarciacaro** [comment]
Yes, this is because interface members are not mangled as they're used for JS interop. (We just have a hard-coded exception for Enumerable.) This should be fixed in Fable 3 where you can mangle interfaces and also BCL interfaces are mangled by default.

**Comment by cartermp** [comment]
This successfully compiles now in the latest Fable REPL. I think this can probably be closed.

**Comment by alfonsogarciacaro** [comment]
Yes, it does! Forgot about this, thanks a lot for checking!
