### ISSUE TITLE
dotnet fable does not preserve webpack console output colors in Windows Command Prompt

### ISSUE THREAD

**Issue by zanaptak** [fable-compiler/Fable#2267]
- `npx webpack`:

![image](https://user-images.githubusercontent.com/53196138/98859680-2603b100-2428-11eb-8605-9c80e0c5300c.png)

- `dotnet fable App --run webpack`:

![image](https://user-images.githubusercontent.com/53196138/98859743-3fa4f880-2428-11eb-9632-ea863f5dd23f.png)

- `npx webpack-dev-server`:

![image](https://user-images.githubusercontent.com/53196138/98859836-65320200-2428-11eb-969f-885db428e39b.png)

- `dotnet fable watch App --run webpack-dev-server`:

![image](https://user-images.githubusercontent.com/53196138/98859879-7549e180-2428-11eb-9733-dba1f32ac45d.png)

### Related information

* Fable version: 3.0.0-nagareyama-rc-004
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Yes, that's a bit of a pity. Not sure how to fix it, any ideas?

**Comment by alfonsogarciacaro** [comment]
Apparently there's no way to retain color info from the process output, we may need to open and extra shell (maybe enable this through a cli command), although I'm not sure if it works outside windows, I'd have to check.

**Comment by zanaptak** [comment]
@alfonsogarciacaro I opened PR to remove output redirection and just allow the process to write direct to console, unless there's some reason to keep the redirection.
