### ISSUE TITLE
Paket change seems to affect ability of Fable RC to compile F# 5 code

### ISSUE THREAD

**Issue by NatElkins** [fable-compiler/Fable#2273]
### Description

I was playing around with the SAFE stack and trying to upgrade the project that comes with the template to use the latest Fable RC and use a bit of F# 5 code (string interpolation).  However, I was experiencing some weirdness where occasionally Fable was complaining with the following message:

![image](https://user-images.githubusercontent.com/1795462/99193582-eef30f80-2747-11eb-9a30-311f38ccd3c7.png)

But other times it would succeed.  At this point I think I've narrowed it down to a change in Paket.Restore.targets, although it's not immediately clear to me why this affects things.

### Repro code

1. Clone https://github.com/NatElkins/NHS
2. `dotnet tool restore`.
3. `dotnet fable src/Client --run webpack` --> This should complain with the error mentioned previously.
4. `dotnet fake build --target run` --> This should succeed.
5. Now if you run `dotnet fable src/Client --run webpack` it will succeed.  Also notice there will be a change to the Paket.Restore.targets.
6. `git stash`
7. `dotnet fake build --target run` --> It will fail.
8. `git stash pop` (to reapply the Paket change)
9. `dotnet fake build --target run` --> It will succeed.

### Expected and actual results

I would've just expected it to work, since the TargetFramework is set to net5.0.  What actually happens is it fails.

### Related information

Here's the Paket.Restore.targets change:

![image](https://user-images.githubusercontent.com/1795462/99193822-74c38a80-2749-11eb-8da3-1a20be98e6ba.png)

I'm on Windows 10, using dotnet 5.0.100, and fable 3.0.0-nagareyama-rc-006.

**Comment by NatElkins** [comment]
Looks like the version of FSharp.Core in the paket.lock file was 4.7.2.  If I change that to 5.0 (but without making the Paket.Restore.targets change), it also will work.

At this point I'm not sure whether this is a bug or just a config/dependencies issue, but at the very least it seems surprising that if  the project is set to use net5.0, it should be able to compile F# 5.0 code.

**Comment by alfonsogarciacaro** [comment]
The error message is a bit misleading but this is the same behavior as in dotnet (you can try compiling a project that references FSharp.Core 4.7.2). Some of the new features require **both** to set the LangVersion to 5.0 or preview **and** reference FSharp.Core 5.0.

**Comment by NatElkins** [comment]
Hm, I see that you're right about `dotnet build` having the same behavior.  Oh well, guess this isn't a real issue then.  If it's simple it might be worth it to add some kind of additional warning about the FSharp.Core version.  At least `dotnet build` reports an error about conflicting versions of FSharp.Core, which provides some kind of clue.

I'll close this out then.  Thanks!
