### ISSUE TITLE
inline call does not compile in Fable but works in dotnet

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2275]
### Description

I am trying to port `FSharpx.Extras` to Fable, but [this code](https://github.com/fsprojects/FSharpx.Extras/blob/ac5053bd5cdaf8ec82099efe4d25a100be0e5fb8/src/FSharpx.Extras/String.fs#L10) does not compile:

```fsharp

/// Functional wrappers around String instance methods
[<CompilationRepresentation(CompilationRepresentationFlags.ModuleSuffix)>] //need this so doesn't hide String class in C# assemblies (should consider for other extension modules as well)
module String =

    /// Returns a value indicating whether a specified substring occurs within this string.
    let inline contains value (s:string) = s.Contains(value)
```

### Repro code

```
module String = 
 
      let inline contains value (s:string) = s.Contains(value)


module M = 

  let x = String.contains "ab" "abcdef"
```

https://fable.io/repl/#?code=LYewJgrgNgpgBAZQC4CcCWA7A5nAvHAKELhNNiTkyk3gGMQMkBDTAZzgDcmoJ4AKVgC5WqTFgCUeOKwB0AYQbM2fLjxjiCm0JFhwAslM0lycAB5Tk6bDPqMWGdgCImAI0dxnL2mBgAzR0aEQA&html=Q&css=Q

### Expected and actual results

It should compile. 

### Related information

* Fable version: 

```
    "fable-compiler": "^2.13.0",
    "fable-splitter": "^2.2.1",
```

* Operating system: Ubuntu

**Comment by alfonsogarciacaro** [comment]
This code seems to work in Fable 3 RC. We are very close to release the stable version so unfortunately we're not updating Fable 2 anymore to focus on the new version. Is it possible for you to upgrade? https://fable.io/blog/Announcing-Nagareyama-1.html

**Comment by inosik** [comment]
The compilation fails because the call to `String.Contains` is ambigous. There's `String.Contains(char)` and `String.Contains(string)`. With this change, it compiles fine:

``` diff
 module String = 
 
-     let inline contains value (s:string) = s.Contains(value)
+     let inline contains (value : string) (s:string) = s.Contains(value)


 module M = 

   let x = String.contains "ab" "abcdef"
```

Or do you see some other error?

**Comment by cartermp** [comment]
Yes, @inosik is correct, this isn't a Fable issue. It's core behavior of the F# compiler.

![image](https://user-images.githubusercontent.com/6309070/117907865-61beec80-b28c-11eb-8378-93bfcdfbc21e.png)

This is because .NET 5 added the ambiguous overload.

This issue can be closed.
