### ISSUE TITLE
Formatting Decimals to specific number of Decimal Places

### ISSUE THREAD

**Issue by VinceAvery** [fable-compiler/Fable#2276]
### Description

I am trying to display decimals in the UI to a configurable number of decimal places, but cannot find a good way to make it work

### Repro code

let decimalPlaces = 4
let decimal = 1234.56m
sprintf "%.*f" decimalPlaces decimal is not supported and crashes the UI

let decimal = 78.500000
decimal.ToString("2F")
Actual - 78.5
Expected -  78.50

I ended up doing someting like this

let round (n: decimal) = Math.Round (n, points)
match points with
| 1 -> sprintf "%.1f" (round number)
| 2 -> sprintf "%.2f" (round number)
....
| _ -> string (round number)

### Expected and actual results
See above

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`
> yarn info fable-compiler version
yarn info v1.22.5

* Operating system
Windows 10 v 903 (OS Build 18362.1139)

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately the `sprintf "%.*f"` pattern is not supported yet. Using a specific number like `"%.2f"` should work with floats but it may happen we didn't test it with `decimal` type. I'll have a look.

**Comment by alfonsogarciacaro** [comment]
Using `sprintf "%.4f" 1234.56m` works for me. Also, `decimal.ToString("2F")` doesn't seem to work in .NET either. You can use the format ` decimal.ToString("0.00")`. However there was a bug ignoring the format argument in decimals, it will be fixed in the next release.
