### ISSUE TITLE
createObj no longer compiles to an object literal in Fable 3

### ISSUE THREAD

**Issue by bklop** [fable-compiler/Fable#2278]
### Description
Given a list of KV pairs where the keys are known at compile time, createObj no longer compiles to an object literal. Is this an intended change for Fable 3 or a regression?

### Repro code
```F#
open Fable.Core.JsInterop
let foo = createObj [ "bar" ==> 42 ]
```

### Expected and actual results
Fable 2:

```JS
export const foo = {
  bar: 42
};
```

Fable 3:
```JS
export const foo = createObj(singleton(["bar", 42]));
```

### Related information

* Fable version: 3.0.0-nagareyama-rc-007
* Operating system: macOS 11.0.1

**Comment by alfonsogarciacaro** [comment]
Sorry, yes, this is a regression. I changed a bit the code and broke the optimization. I fixed it for `keyValueList` but forgot about `createObj`. I will fix that, thanks for reporting!
