### ISSUE TITLE
Idential types from differents bundles are not equal

### ISSUE THREAD

**Issue by Prunkles** [fable-compiler/Fable#2282]
### Description

Comparing instances with the same value of the same type (in particular DUs), created in different bundles, always returns false. 

### Repro code

Full example is in this repo:
https://github.com/Prunkles/FableMultiBundleTypeIssue
All instructions are included to the readme

Briefly:

```fs
// PluginFramework.fs (shared between Application and Plugin)
type PluginId = PluginId of string
type Plugin = { Id: PluginId }
```

```fs
// Plugin.fs (bundle #1)

[<Emit """
globalThis.GlobalPluginHandler = $0
""">]
let setGlobalPluginHandler (plugin: Plugin) : unit = jsNative
let plugin = { Id = PluginId "THE_PLUGIN_ID" }
setGlobalPluginHandler plugin
```

```fs
// Application.fs (bundle #2)

[<Emit """
globalThis.GlobalPluginHandler
""">]
let getGlobalPluginHandler () : Plugin = jsNative

let pluginCode = "..." // copy code from webpacked bundle #1

let loadPlugin () =
    let scriptElement = document.createElement("script")
    scriptElement.innerHtml <- pluginCode
    document.appendChild(scriptElement)
    // wait until the node is loaded and executed

loadPlugin ()

let plugin = getGlobalPluginHandler ()
let actualId = plugin.Id
let expectedId = PluginId "THE_PLUGIN_ID"
let controlId = PluginId "THE_PLUGIN_ID" // another instance for check if there is no instance equality issue


// Testing

printfn "actualId   = %A" actualId   // PluginId "THE_PLUGIN_ID"
printfn "expectedId = %A" expectedId // PluginId "THE_PLUGIN_ID"
printfn "controlId  = %A" controlId  // PluginId "THE_PLUGIN_ID"
printfn "(expectedId = actualId)  = %b" (expectedId = actualId)  // false (should be TRUE!)
printfn "(expectedId = controlId) = %b" (expectedId = controlId) // true
```

### Expected and actual results

Since the types in the repro are Discriminated Union, which have defined comparison by value, they must be equal.
However, in reality they are not equal.

### Related information

Fable version: 3.0.0-nagareyama-rc-008 (also tested on the latest 2.x)
Operating system: Manjaro Linux

**Comment by alfonsogarciacaro** [comment]
This is a tricky one. The thing is that if they come from different bundles each object comes from a different constructor. Fable equality checks the constructor of the objects is the same, so `Foo1.Foo 5 = Foo2.Foo 5` evals to false. Changing this behaviour will likely cause other bugs. To fix your case you probably need to make structural comparison ignoring the type somehow, or if possible maybe you can extract the shared types so there are accessible to both bundles. I think doing code splitting with Webpack does this automatically.

**Comment by Prunkles** [comment]
Thanks for answering!


> Changing this behaviour will likely cause other bugs.

I would like to ask what exactly bugs can occur? Why not compare not by the constructor, but, for example, just the full type name?

**Comment by alfonsogarciacaro** [comment]
For example, two DUs with different types but same structure would be considered equal, which is not the expected behavior. About the full type name, right now it's only available through reflection info, which must be accessed explicitly and resolved at compile time so tree shaking can remove it if not needed.

**Comment by alfonsogarciacaro** [comment]
For the reasons above, unfortunately we have to leave with the inconvenience of objects of same type from different bundles not being equal.
