### ISSUE TITLE
Add compiler constant for Fable 3

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2283]
Following our discussion, it would be great to have a `FABLE_COMPILER_3` constant to be able to write code that maintains Fable 2.x compat, this is an issue to keep track of it :smile:

**Comment by alfonsogarciacaro** [comment]
At the end, I've added:

- Two compilation constants: FABLE_COMPILER and FABLE_COMPILER_3
- Fable.Core.Compiler.version: string
- Fable.Core.Compiler.majorMinorVersion: float

The last helper should be helpful when you need to check for a feature that comes in a manor version as in ` Compiler.majorMinorVersion >= 3.2`
