### ISSUE TITLE
Generic binding without arguments generates a function

### ISSUE THREAD

**Issue by belka-ew** [fable-compiler/Fable#2287]
### Description

I'm writing bindings and don't see a better way, but make a variable generic:

```fs
let listItem<'N> : NodeSpec<'N> = importMember "prosemirror-schema-list"
```

It seems to work but fails at runtime with

> Uncaught TypeError: _Prosemirror.SchemaList$$$listItem is not a function

### Repro code

```fs
open Fable.Core
open Fable.Core.JsInterop

type NodeSpec<'N> =
    { content: 'N }

let listItem<'N> : NodeSpec<'N> = importMember "prosemirror-schema-list"

let item = { listItem<string> with content = "some" }
```

### Expected and actual results

```js
import { declare, Record } from "fable-library/Types.js";
import { record_type } from "fable-library/Reflection.js";
import { listItem as listItem$$1 } from "prosemirror-schema-list";
export const NodeSpec$00601 = declare(function Test_NodeSpec(content) {
  this.content = content;
}, Record);
export function NodeSpec$00601$reflection($gen$$1) {
  return record_type("Test.NodeSpec`1", [$gen$$1], NodeSpec$00601, () => [["content", $gen$$1]]);
}
export const listItem = listItem$$1;
export const item = (() => {
  const inputRecord = listItem();
  return new NodeSpec$00601("some");
})();
```

This is the generated code according to the Fable REPL (REPL 2.1.1, Fable 2.10.1). If you look at the end:

```js
  const inputRecord = listItem();
```

`listItem` is called as function, but it isn't one.

### Related information

* Fable version: 2.13.0
* Operating system: Slackware Linux x86-64

### Workaround

```fs
[<Emit("require('prosemirror-schema-list').listItem")>]
let listItem<'N> : NodeSpec<'N> = jsNative
```

**Comment by alfonsogarciacaro** [comment]
Yes, this is an issue we sometimes have when interacting with JS. This is because generic value in F# are just syntax sugar and are actually functions in disguise, as eager module values cannot be generic in .net. Unfortunately we do need a workaround, yours is good but maybe you can make it a bit more robust by combining Import and Emit attributes which is allowed by Fable. Sorry, writing from mobile so I cannot format, but the code would look like:

```
[ImportMember(prosemirror-schema-list)]
[(Emit($0)]
let listItem<'N> : NodeSpec<'N> = jsNative
```

Another alternative would be to use an interface to type the JS module and then the problem is gone because interface properties can be generic. You can see the fable-node bindings as reference for this.

**Comment by belka-ew** [comment]
Well, then I suppose, it is expected behaviour. Thanks anyway for suggesting a better way to handle this.

> Another alternative would be to use an interface to type the JS module and then the problem is gone because interface properties can be generic. You can see the fable-node bindings as reference for this.

```fs
type SliceConstructor =
    abstract empty<'N> : 'N
```
Like this? It doesn't work, I get:

> A property cannot have explicit type parameters. Consider using a method instead.

I had to write:

```fs
open Fable.Core

type SliceConstructor =
    [<Emit("$0.empty")>]
    abstract empty<'N> : unit -> 'N
```

to work around it.

**Comment by alfonsogarciacaro** [comment]
Ah, ok. Then it only works with generic arguments of the interface itself, sorry! 😅
