### ISSUE TITLE
Edit docs/improve compiler erros: overriding a native JS class method without abstract declaration should fail

### ISSUE THREAD

**Issue by vrescobar** [fable-compiler/Fable#2289]
### Description

I am trying to import an ES6 class from an external library and I want to add the types and mark them with the jsNative.
In the way this library has been done I am required to:
- Inherit from the JS class
- Execute my code in the constructor/methods
- Call parent's equivalent method within

The error is as follows: in the child class when I declare the code as "member" then child's method is bypassed and only parent's method is called.

If I declare child's method with the override keyword (and I restart the compiler) the code works as it should and I can see the actual results in the browser (with prints and so on) but I also get the following compiler error for each one of the overwritten methods:

```
error FSHARP: No abstract or interface member was found that corresponds to this override (code 855)
```

### Repro code

This is the actual code which is giving me errors. I've tried lots of variations during the last days and finally I decided this must be a bug. The keywords "class end" seem to be just avoidable syntactic sugar.

```F#
    [<Import("DataManager", from="@syncfusion/ej2-data")>]
    type DataManager<'Model> (conf:obj) =
        class
            member this.insert(_:'Model):Promise<obj> = jsNative
            member this.update (_:'Model):Promise<obj> = jsNative
        end

    type FirebaseAdaptor<'Model> (conf, inst)=
        inherit DataManager<'Model> (conf)
        let DB:obj = inst
        do
            printf "I've been created"

        override this.insert(o:'Model):Promise<obj> =
            printf "insert method comes with object:"
            console.log o
            base.insert o
            //Constructors.Promise.Create o

        override this.update(o:'Model): Promise<obj> =
            printf "Update method comes with object:"
            console.log o
            base.update o
            //Constructors.Promise.Create o
```

### Expected and actual results

Either I can use the methods as members without being bypassed or I am allowed to override parents methods without any error.

### Related information

```
fable-compiler@2.13.0 | MIT | deps: none | versions: 288
Fable compiler
https://github.com/fable-compiler/Fable#readme

keywords: fable, fsharp, F#

dist
.tarball: https://registry.npmjs.org/fable-compiler/-/fable-compiler-2.13.0.tgz
.shasum: 3fa37b4eae3c8216e3555f0229751960b969807b
.integrity: sha512-eEd+ue0CWhLpZBXqkIm4uWTGPfX8Q14RkCwSrbO0zPfB9hHW8IylipJ4YVfCZKd27sHDTpGOBwW8JMHqMBrXPQ==
.unpackedSize: 23.9 MB

maintainers:
- alfonsogarciacaro <alfonsogarciacaro@gmail.com>
- mangelmaxime <mangel.maxime@outlook.com>

dist-tags:
latest: 2.13.0        next: 2.3.0-beta-001
```
Operating system: windows 10, no wsl has been involved at the moment.
Serving and packaging Fable's code with Webpack toolchain and babel:
```json
{
        "@babel/core": "^7.12.3",
        "@babel/plugin-transform-runtime": "^7.12.1",
        "@babel/polyfill": "^7.12.1",
        "@babel/preset-env": "^7.12.1",
        "@babel/preset-react": "^7.12.5",
        "@babel/runtime": "^7.12.5",
        "@types/react": "^16.9.56",
        "@types/react-dom": "^16.9.9",

        "fable-compiler": "^2.13.0",
        "fable-loader": "^2.1.9",
        "fable-splitter": "^2.2.1",

        "@types/webpack": "^4.41.25",
        "babel-loader": "^8.2.1",
        "webpack": "^4.44.2",
        "webpack-cli": "^3.3.12",
        "webpack-dev-server": "^3.11.0"
    }
```
### Unrelated

Thank you so much for the awesome work at fable and its libraries, I had no prior dotnet, F# or C# experience.

**Comment by vrescobar** [comment]
It turns out it was an F# beginner mistake (which cost me a bit)

It turns out that in F# people cannor override a method which has not been declared previously as abstract.
For that the solution was to declare the methods as abstract and provide a default implementation before override.

```F#
    [<Import("DataManager", from="@syncfusion/ej2-data")>]
    type DataManager<'Model> (conf:obj) =
        class
            abstract member insert: 'Model -> Promise<obj>
            default this.insert(_:'Model):Promise<obj> = jsNative

            abstract member update:'Model -> Promise<obj>
            default this.update (_:'Model):Promise<obj> = jsNative
        end
```

After that it is possible to override the child class without issues, compiler erros, etc. The bug is not what  thought it was but I still would suggest to **modify** this [documentation page](https://fable.io/fable-doc/dotnet/compatibility.html#object-oriented-programming) which suggests that people can happily declare a member in the child class with the same name and it will get overriten as easy as if it was python.

Worth mentioning that the compiler accepts the way in the docs but then behaved indefined.

**Comment by vrescobar** [comment]
I changed the title to **Edit docs/improve compiler erros: overriding a native JS class method without abstract declaration should fail**, I am not blaming Fable docs but it could be advisable to include in a link to F# docs in the OOP section. At least for me as F# beginner who learnt through Fable that was a huge waste of time/pain point.

F# docs related:
https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/inheritance#virtual-methods-and-overrides

**Comment by alfonsogarciacaro** [comment]
Thanks for the report @vrescobar! You're right, probably the docs are written with .NET developers in mind and some points are not clear for devs coming from Python or other languages. Also, I just realized your link pointed to an old version of the docs I forgot was still online. I should have added some redirects but for now I just removed the repo to avoid confusion. Please check the updated docs here: https://fable.io/docs/

In the latest version, there's an Edit button so it'd be much appreciated if you could help us improve the wording in cases like this. Would it be possible to add the F# docs link or anything else you find useful to the "Objected Oriented Programming" section? https://github.com/fable-compiler/fable-compiler.github.io/edit/dev/docsrc/dotnet/compatibility.md

**Comment by vrescobar** [comment]
Hi,

Unfortunately I ended up hitting an F# limitation, not being capable of calling the parent method from a closure/function and I ended up giving up in favor of typescript just for this piece of code. I am going to improve the docs anyway, as it took me a great amount of time anyway.

**Comment by vrescobar** [comment]
I made a PR on the docs here, gh doesn't let me reference issues from other repos:
https://github.com/fable-compiler/fable-compiler.github.io/pull/80

Feel free to close this issue when the PR is merged. I will contribute more in the future as soon as I will have more chances to work with Fable.

**Comment by alfonsogarciacaro** [comment]
Merged! PRs to improve the docs are super helpful, thanks a lot!
