### ISSUE TITLE
Question: Overwrite or delete and create

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#2290]
Hello, I've got a small question about how Fable 3 will write an existing compiled file to disk.
Will it remove the original file and write a new one? Or will it overwrite the existing file?

**Comment by ncave** [comment]
@nojaf 
If you asking if it cleans the output folder, I don't think it does.
The default behavior for [System.IO.StreamWriter(path)](https://docs.microsoft.com/en-us/dotnet/api/system.io.streamwriter.-ctor?view=net-5.0#System_IO_StreamWriter__ctor_System_String_) is to overwrite file if it exists, or create a new file if it does not.

**Comment by alfonsogarciacaro** [comment]
Yes, Fable doesn't remove any existing file. Note that in watch mode it actually checks the timestamp of the JS file and it skips compilation if it's more recent than the F# source.

There's a `dotnet fable clean` command that will remove the `.fs.js` files that are written next to .fs files, but it's not intended to be used in combination with `--outDir` (in that case you can just delete the folder).

**Comment by nojaf** [comment]
Ok, thanks for clarifying this. The reason I'm asking is that the snowpack dev server something gives a 404 if a file has just been compiled. I'm trying to pinpoint what is happing there, delete and recreate came to mind so that was a thought.
