### ISSUE TITLE
Different code behavior between Fable 3 and Fable 2 code when using FSharp.Data.Adaptive

### ISSUE THREAD

**Issue by sasmithjr** [fable-compiler/Fable#2291]
### Description

I discovered when migrating to Fable 3 that some of my tests were failing in Fable 3 but not Fable 2. I've only noticed failed tests with code involving the [FSharp.Data.Adaptive](https://github.com/fsprojects/FSharp.Data.Adaptive) library, specifically involving the AList type.

I'm not sure what the differences are in the generated code is yet.

### Repro code

[Repo here](https://github.com/sasmithjr/nagareyama-008-different-behavior)

Steps to reproduce:
1. Clone repo and change working directory to repo root
2. `dotnet tool restore && npm install`
3. `dotnet run --project ./tests/StuffTests.fsproj`
4. `npm run test` to run the Fable 2 tool
5. `npm run test-nagareyama` to run the Fable 3 tool. "X: 0" is not printed and the test fails.

### Expected and actual results

Expected and actual for `dotnet run` in step 3:

```
X: 3
X: 0
First: 4
Second: 1
```

Expected and actual in `npm run test` in step 4 :

```
X: 3
X: 0
<test passes, First has a value of 4 and Second has a value of 1>
```

Expected for `npm run test-nagareyama` in step 5 is the same as expected/actual for step 4 just above.

Actually printed for step 5:

```
X: 3
<test fails, First has an incorrect value of 1>
```

In a nutshell, there are mapped adaptive values with side-effects (e.g. printing to console) that should be run because of the calls [here](https://github.com/sasmithjr/nagareyama-008-different-behavior/blob/1331ce4b1a2da080ab19611b9ec3dda1b0e0119e/tests/Main.fs#L19-L20), forcing the value in the list to update.

The .NET code prints the X value twice correctly, and then displays the value in the list both before and after the update. The Fable 2 code prints the X value twice correctly and then passes the tests for its values [here](https://github.com/sasmithjr/nagareyama-008-different-behavior/blob/1331ce4b1a2da080ab19611b9ec3dda1b0e0119e/tests/Main.fs#L31-L32). The Fable 3 code prints the "X: 3" line, does not print the second one, and then fails on [this assertion](https://github.com/sasmithjr/nagareyama-008-different-behavior/blob/1331ce4b1a2da080ab19611b9ec3dda1b0e0119e/tests/Main.fs#L31).

Please let me know if there's more information I can provide, and thank you for the help!

### Related information

* Fable 2: v2.13.0
* Fable 3: 3.0.0-nagareyama-rc-008
* .NET SDK: 5.0.100
* FSharp.Data.Adaptive: 1.0.1

**Comment by alfonsogarciacaro** [comment]
Investigating this.

**Comment by alfonsogarciacaro** [comment]
At the end this was a hashing issues. In Fable 2 all compiled F# types were inheriting from `SystemObject` but we've removed this inheritance for classes so there was no default implementation of `GetHashCode` and calling `hash` was using structural hashing instead of identity hashing. Can you please try with latest release?

**Comment by sasmithjr** [comment]
RC9 seems to fix the issue. It works in the referenced repo in the issue, and it works in my larger, local project.

Thanks so much for the help! I greatly appreciate it.

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks to you for reporting and for confirming the fix!
