### ISSUE TITLE
3.0.0-nagareyama-rc-009 broke my build

### ISSUE THREAD

**Issue by mlaily** [fable-compiler/Fable#2302]
Even more precisely, `ffeea9cc04600a70c4969279383807fbf7e96d92` broke my build. The commit just before compiles my project ok.

From the problematic commit and after, compiling outputs two lines or error:
```
/home/yaurthek/dev/LastFmStats/src/ClientApp/src/LastFmApi.fs(1,1): error EXCEPTION: No compiled representation for provided namespace
/home/yaurthek/dev/LastFmStats/src/ClientApp/src/App.fs(1,1): error EXCEPTION: No compiled representation for provided namespace
```

I'm using https://github.com/fable-compiler/Fable.JsonProvider and I suspect this is related...

**Comment by alfonsogarciacaro** [comment]
Thanks for the detailed report and pointing out the commit @mially! Thanks to the info I could quickly the problem, will be fixed in next release.

**Comment by mlaily** [comment]
Happy to help! :)
