### ISSUE TITLE
[Fable 3]Custom filenames or how to remove 'fs.' suffix

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#2308]
## Description
Another try to use Fable with next js 
The first time was here (https://github.com/fable-compiler/Fable/issues/1936)
So, next js is lying on top of filenames, for example: index.js will be mapped to `example.com/index` or `example.com/` but index.fs.js will be mapped only to  `example.com/index.fs`.

That's why I have the question.
Is there any way to remove 'fs.' suffix from the output filenames?

**Comment by alfonsogarciacaro** [comment]
It you pass the --outDir option, the extension will just be .js, but you can also use --extension to customize the extension.

**Comment by Neftedollar** [comment]
@alfonsogarciacaro thank you! I've missed --extension option!
