### ISSUE TITLE
Invalid hook call

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#2315]
### Description

The latest fable-compiler seems to break [the rules of hooks of React](https://reactjs.org/warnings/invalid-hook-call-warning.html).

### Repro code

See https://github.com/nojaf/fable-hooks-repro

![image](https://user-images.githubusercontent.com/2621499/102134564-fdbc0780-3e56-11eb-858b-b712ac9ecc87.png)

### Expected and actual results

I believe the problem is that the compiler function name (of the useElmish hook in my case) is not starting with the word `use` anymore. (diff between rc-008 and 3.0.1 stable)

- [rc-008](https://github.com/nojaf/fable-hooks-repro/blob/647b3ef1ee7e2288825d6272b0308d7e88ed5aee/rc-008/src/Library.fs.js#L9)
- [3.0.1](https://github.com/nojaf/fable-hooks-repro/blob/647b3ef1ee7e2288825d6272b0308d7e88ed5aee/3.0.1/src/Library.fs.js#L7)

### Related information

* Fable version: `3.0.0-nagareyama-rc-008` and `3.0.1`
* Operating system: Linux (docker image on Gitpod)

**Comment by Shmew** [comment]
Hooks don't need to start with `use`, it's just a convention to make it easier for people to differentiate normal functions from them. What's likely happening here is either a bug with the compiler or with @Zaid-Ajaj's plugin.

**Comment by Zaid-Ajaj** [comment]
@nojaf The error you get is not because of the rules of hooks, but rather it is a plugin issue potentially because it doesn't seem to transform the call-site from
```js
render(Title(""), app);
```
to
```js
import { createElement } from 'react'
render(createElement(Title, { name: "" }), app)
```
I see that you are using `Feliz.UseElmish` v1.5 which depends on `Feliz` v1.17 Meanwhile, latest `Feliz` is at v1.27 which has had a bunch of bug fixes with regard to the plugin. Can you please upgrade and see if it solves the problem?

**Comment by Zaid-Ajaj** [comment]
Just tested locally and confirmed that updating `Feliz.CompilerPlugins` to v1.10.0 should do the trick

**Comment by nojaf** [comment]
Thanks, @Zaid-Ajaj and @Shmew for pointing this out. 

The reason I suspected the name was due to the docs of React when writing a custom hook:
> Its name should always start with use so that you can tell at a glance that the rules of Hooks apply to it.
