### ISSUE TITLE
Relax FSharp.Core dependency from Fable.Core

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2317]
### Description

Right now, latest Fable.Core v3.2 requires FSharp.Core >= v5.0 which breaks compatibility with many packages that still depend on FSharp.Core v4.7.2

Please consider pushing  a new version of Fable.Core that instead relies on a lower version of FSharp.Core (for example v4.7.2) for better compatibility.

> This is happening on many packages because anyone who has installed .NET 5 SDK and haven't pinned FSharp.Core before will suddenly and  _implicitly_ resolve FSharp.Core v5 that comes with the sdk instead of whatever it was using in previous versions. For those who have paket, use `lowest_matching: true` and `nuget FSharp.Core ~> 4.7.2`  on direct dependencies or add this line to your package references when using nuget:
```xml
<PackageReference Update="FSharp.Core" Version="4.7.2" />
```

**Comment by kerams** [comment]
This is a bit of a ballache, since you need to reference FSharp.Core 5 just to compile (typecheck in this case) code using string interpolation (which, I assume, is the reason it's used in Fable.Core), even though the runtime dependency is irrelevant/inapplicable in the context of Fable.

**Comment by Zaid-Ajaj** [comment]
Applications can still depend on FSharp.Core v5 and being compiled that way, only the *libraries* should depend on a lower version to improve the compatibility

These implicit FSharp.Core versions are a real PITA

**Comment by kerams** [comment]
Yes, but those libraries then can't use features like string interpolation since the compiler requires FSharp.Core 5 (which Fable users are not obliged to use) despite the fact that it wouldn't matter for Fable because you're not producing binaries (unless I misunderstand this whole situation).

**Comment by Zaid-Ajaj** [comment]
I think you are right @kerams. It is a good compromise for libraries not to use latest features for better compat with users. Especially now when not everyone has started using dotnet sdk 5. And indeed, it doesn't matter for Fable, because Fable compiles the sources, not the binaries. Though I am not sure about the requirements of the plugins because those *are* binaries that are loaded in runtime into Fable

**Comment by alfonsogarciacaro** [comment]
TBH, at this point I don't really know if you need to reference FSharp.Core 5 or not **in the application** for Fable 3 to work properly, as some of the new F# features Fable relies on like witnesses seem to behave differently on that. I would recommend to reference FSharp.Core 5 in applications now, but it's true we don't want to break existing packages. The implicit FSharp.Core references are understandable but are indeed a PITA. It shouldn't be a problem to lower the requirement in Fable.Core as most of it is just metadata and the actual functions are resolved in the Replacements module.

**Comment by alfonsogarciacaro** [comment]
Fable.Core 3.2.1 released with a dependency on FSharp.Core 4.7.2. I hope that works. Actually after pushing I realized Fable.Core 3.1.5, the one with most downloads depended on FSharp.Core 4.7.0, maybe I should have used that? 🤔
