### ISSUE TITLE
Can't execute "dotnet fable clean" without blocking the console

### ISSUE THREAD

**Issue by MarkBracke** [fable-compiler/Fable#2320]
This is actually an improvement request, but I'll just fill in your template anyway 😃 

### Description

We're using automated build tools to build our fable app. We've recently switched to Fable 3 and we've fixed the import statements. Everything works fine, except when we rename a file. The old javascript file still hangs around. We'd definitely like to perform a clean before every compile, but there doesn't appear to be a "--force" argument (or similar) we can pass to "dotnet fable clean".

### Repro code

Execute "dotnet fable clean --force"

### Expected and actual results

Expected: The question "are you sure?" isn't posed, the .fable folder(s) and all .fs.js files are removed.
Actual: The question "are you sure?" is still posed.

### Related information

* Fable version: 3.0.1

**Comment by alfonsogarciacaro** [comment]
This makes sense @MarkBracke, thanks for suggesting it. We will add it for the next release. Maybe we can use the `--yes` argument instead, as I think this how you usually reply `yes` automatically in other CLI tools.
