### ISSUE TITLE
Regex seems to yield different results with Fable

### ISSUE THREAD

**Issue by lfr** [fable-compiler/Fable#2322]
### Repro code

```fsharp
Regex.IsMatch("\\p{C}", "a\nb") // false (FABLE)
Regex.IsMatch("\\p{C}", "a\nb") // true (non-FABLE)
```

### Related information

* Fable version: 2.13.0
* Windows

**Comment by lfr** [comment]
From F# fiddle:
![image](https://user-images.githubusercontent.com/6348118/102550695-88eb0680-40be-11eb-9ec8-46f9d6355ded.png)

**Comment by alfonsogarciacaro** [comment]
How are you evaluating the F# fiddle? If I try this in F# interactive I get `false` too.

![image](https://user-images.githubusercontent.com/8275461/102565759-7229cb80-4121-11eb-8995-7ecfb5312cb6.png)

**Comment by lfr** [comment]
Ok, it must be a bug with .NET 5 then, I evaluated it with dotnetfiddle.net that's probably still running on an earlier version.

**Comment by inosik** [comment]
.NET 5 behaves different on Windows in regards to the previous versions, see dotnet/runtime#43736. This probably affects Regex as well.

Also, note that Fable translates to JavaScript and isn't a fully fledged .NET runtime for the browser. So this is actually a mismatch between .NET and the browser.

**Comment by alfonsogarciacaro** [comment]
Thanks @inosik ! Yes, sorry. Forgot to say that, as mention in the docs, regex in Fable behave as if you're using the RegexOptions.ECMAScript flag (no named groups for example) so it's better to use it explicitly for a proper comparison.
