### ISSUE TITLE
Fable 3 - Uncaught ReferenceError: process is not defined

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2328]
### Description

I'm trying to upgrade my application from Fable 2 to Fable 3, and everything builds and loads in, but the app errors out right at the beginning with an ``Uncaught ReferenceError: process is not defined``. 

### Repro code

It seems that this occurs when you use an explicit ``main`` function, and goes away when you use an implicit one instead. For example:

Clone fable3-samples at https://github.com/fable-compiler/fable3-samples/tree/6d34ece9a2793b59e91500d5d407e8e4028273af, and change browser/src/App to use an explicit ``main``, like this gist: https://gist.github.com/jwosty/a727d85603bea808421468a006af9910. Run it and look at the devtools console.

### Expected and actual results

Expected: Program should run just fine.

Actual: program crashes with an error like the following:

    Uncaught ReferenceError: process is not defined
        <anonymous> webpack:///./src/App.fs.js?:35
        js http://localhost:8080/bundle.js:530
        __webpack_require__ http://localhost:8080/bundle.js:553
        <anonymous> http://localhost:8080/bundle.js:615
        <anonymous> http://localhost:8080/bundle.js:618
    bundle.js line 530 > eval:35:1

### Related information

* fable 3.0.2
* Windows 10
* dotnet sdks 5 and 3.1 both installed

**Comment by inosik** [comment]
Looks like there's some magic happening if the `main` function is marked with `EntryPoint`. This is a smaller repro:

``` fsharp
module Main
[<EntryPoint>]
let main _ =
    0
```
Compiles to this:
``` js
(function (_arg1) {
    return 0;
})(process.argv.slice(2));
```
Removing `EntryPoint` produces this:
``` js
export function main(_arg1) {
    return 0;
}
```

**Comment by alfonsogarciacaro** [comment]
Yes, this was done thinking of node console apps. It makes sense to check if `process` is available in the current environment first, although I'm surprised you're only seeing this when upgrading to Fable 3 because I think this "feature" has been like this Fable 0.x.
