### ISSUE TITLE
[Feature request] dotnet fable run

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2335]
### Feature request

`dotnet fable run` to compile a project into JS and run the entry file right away with node. Basically as a short-hand to 
```
dotnet fable . --run node {EntryFile}.fs.js
``` 
This is to easily go from a console app running dotnet with `dotnet run` into a JS application running node `dotnet fable run`

I can't seem to find the options of the CLI to figure out whether this feature is already there or not 😅

**Comment by alfonsogarciacaro** [comment]
Yes, the option is available :) `--runScript` You can see for example how it's used for [running the quicktest](https://github.com/fable-compiler/Fable/blob/1f743ae58866d118fdf9412f04f1b081220739bf/build.fsx#L523).

Note you don't need to specify the last file. If you add something after `--runScript` those will be passed as arguments to the node app. This feature [uses `esm` to load the ES modules](https://github.com/fable-compiler/Fable/blob/1f743ae58866d118fdf9412f04f1b081220739bf/src/Fable.Cli/Main.fs#L549) in node without issues.

**Comment by Zaid-Ajaj** [comment]
Would it be possible to make `run` an alias for `--runScript` 🙏 ?  It would make for really cool demo's when showcasing Fable 😁

**Comment by MangelMaxime** [comment]
Hum, IHMO we need to be careful  `run` is already used for running a "CLI" process it would be a breaking change.

Perhaps, we can say if `--run` is invoked without an argument then the user wants to run the compiled JavaScript. If it has an argument we spawn a process using the provided argument? This would avoid breaking the project of everyone relying on `run` behavior.

**Comment by Zaid-Ajaj** [comment]
>  This would avoid breaking the project of everyone relying on run behavior.

> `run` is already used for running a "CLI" process

I don't understand why this would be a breaking change, where is `run` being used exactly?

**Comment by MangelMaxime** [comment]
Well, today you can do `dotnet fable myprject.fsproj --run command args1 args2` 

So `run` is already used unless you want to make a difference between `dotnet fable --run` and `dotnet fable run` which looks confusing for the user. 

IHMO if there is already `--runScript` which does what is asked I am all in favor of not adding `run` to keep everything explicit and separated.

**Comment by alfonsogarciacaro** [comment]
Yes, --run is already used to start Webpack, etc, and this how we've been promoting the upgrade so we shouldn't touch. If you mean run without the dashes it can tricky too, it's quite ambiguous and it can cause issues with how the arguments are parsed. We could consider turn --run into --runScript if there are no arguments after it, but --runScript can also take arguments so this may be confusing for users.

**Comment by Zaid-Ajaj** [comment]
You are right, it is a bit of a shame but it would be confusing to have both `run` and `--run` . Thanks @alfonsogarciacaro and @MangelMaxime for hearing me out 🙏
