### ISSUE TITLE
printf: parameterized alignment compiles, but fails at runtime

### ISSUE THREAD

**Issue by VitalyBrusentsev** [fable-compiler/Fable#2336]
### Description

The [x]printf family of functions supports a width value specified as an integer parameter.
As per the [Microsoft documentation:](https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/plaintext-formatting#format-specifiers-for-printf)

> The optional width is an integer indicating the minimal width of the result. For instance, %6d prints an integer, prefixing it with spaces to fill at least six characters. If width is *, then an extra integer argument is taken to specify the corresponding width.

The hardcoded version (as in `"%6d"`) is supported in Fable, while the parameterized one fails at runtime.

### Repro code

```fsharp
printf "[%6s]" "Hello"
printf "[%*s]" 6 "Hello"
```
### Expected result

Both lines are expected to print `[ Hello]` (with a single leading space before H).

### Actual result

The snippet compiles fine (and actually requires the int parameter to compile).
During the execution, the second line fails with `Uncaught TypeError: Object(...)(...) is not a function` or `Uncaught TypeError: toConsole(...) is not a function`

### Related information

* Fable version: 3.0.5 (also reproduced in the [current Fable REPL](https://fable.io/repl/#?code=A4JwlgdgLgZgBAIgNoFIBsBnAugxAJAUwBsiB7BAWAChRJZFUAqbXNfYshIA&html=DwCwLgtgNgfAUKApgQwCbwAQeBRZkbhgAOAtIgI4CuAlgG4C8A5AMID2AdmIl6QCoBPYoiYYAxp25dm3AB5gA9OGgBucSGQAnAM54GVMADNSADiaZs2sZprEwGbZrEMARAH03ACQDyAZT4eClA0AEbaCpooYmAAdMSabKhU0TScMRA0HDEAVtouMMAKVjZ2FsDFtvaOzu5efgFuQaHhkcjRpKhsEHEJSSlpGVm5+YUVpQhKKOgIIYkC4lDI2tquyMRkElzImYia+XBYWMCo9Bg0qK6IUBnaIKRrxC4LSysuVzd3DyMKJ3TwhbNUAJ-kpILAgA&css=Q)).
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately this is not supported, there's another issue about it I think. I don't remember if it was difficult to implement or just I haven't looked into that 😅 We should probably at least have a compile error to let the user know is not supported.

**Comment by inosik** [comment]
Yes, this was already reported in #1399.

**Comment by alfonsogarciacaro** [comment]
Can you please try with 3.1.1?

**Comment by VitalyBrusentsev** [comment]
@alfonsogarciacaro can confirm the fix with 3.1.1 - great job, as always! 👍
