### ISSUE TITLE
where is the gitpod ready-to-code template repo for fable projects?

### ISSUE THREAD

**Issue by markfirmware** [fable-compiler/Fable#2346]
### Description

Please provide a succinct description of your issue.

### Repro code

Please provide the F# code to reproduce the problem or a link to the [REPL](https://fable.io/repl/).
Ideally, it should be possible to easily turn this code into a unit test.

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`
* Operating system

**Comment by MangelMaxime** [comment]
Hello @markfirmware,

we don't have one. Please feel free to contribute one 😊

The closer thing we have is probably https://github.com/MangelMaxime/fulma-demo.

In the past, I had some problem with Gitpod and locking the dotnet version used by the workspace.

**Comment by markfirmware** [comment]
Thanks! I will pursue this.
