### ISSUE TITLE
Is there a way to tell Fable to not transform a relative import path?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2347]
### Description

In my application at work, 
I have a legacy application written using Haxe (transpiler to JavaScript) and wants to use Fable for the new features.

I would like to write code like that:

```fs
type FleetMappingHaxe =
    abstract testInterop : unit -> unit

let haxe : FleetMappingHaxe = import "testInterop" "../haxe/app.js"

haxe.testInterop()
```

The problem is that when using fable with `outDir` to:

```js
import { testInterop } from "../../haxe/app.js";

export const haxe = testInterop;

haxe.testInterop();
```

It is modifying the import path to target the file where it "thinks" it is. The problem is that the file is note hosted near the source code but will be put in the `outDir`

In fable-splitter I think it was possible to use `${entryDir}` and `${outDir}` to avoid this behaviour.

Can we had this feature to Fable 3 too? Is there already a way to avoid Fable rewriting the import path in some case?

**Comment by inosik** [comment]
Do you use Webpack? You could use aliases then.

**Comment by MangelMaxime** [comment]
On the server up until now we weren't bundling the output because Haxe generates a single JavaScript file.

And I was kind of thinking of keeping the generated files as they are. Should I bundle them using Webpack or a bundler? 

For now, in dev mode I have a workaround using a `haxe_compat.js` file:

```js
import { App } from "./../build/haxe/app"

export default App;
```

This made me discover that when using a local JavaScript file and `outDir` Fable will update the import path because it leave the `.js` in it's original place. So not everything will be in the `outDir`.

I guess this is not a problem if the person use a bundler in the end and don't use the generated files as they are. But it was nice to be able to use generated file directly and removing a tool from the toolchain.

**Comment by ncave** [comment]
@MangelMaxime Yes, you are correct, what was previously provided by the `fable-splitter` can be done by other tools in your pipeline. As you said, if you need all your external non-F# JavaScript dependencies (imports) to be copied to the output folder, you have to run some tool (e.g. TypeScript or a bundler) on the output.

The `${outDir}` variable is supported, it just has to be at the very beginning of the import path string.

**Comment by MangelMaxime** [comment]
Oh @ncave you are right `${outDir}` is indeed supported.

I got tricked because my files are under `fable/Main.js` so when it generates the files with `--outDir build`.

The `${outDir}` is relative to `build` folder not `fable` directory.

So I had to do `${outDir}/haxe/app.js` and not `${outDir}/../haxe/app.js`.

Folder structure is:

```
| build
    |- haxe
        |- app.js
    |- fable
        |- main.js
```

I don't think adding `${entryDir}` is needed as it seems to be the default behaviour of Fable.

> As you said, if you need all your external non-F# JavaScript dependencies (imports) to be copied to the output folder, you have to run some tool (e.g. TypeScript or a bundler) on the output.

It makes sense and I had the same situation with Haxe where I simply added a copy step in my Fake build.
