### ISSUE TITLE
Fable3 regression:  In the on line repl TypedArray's are still not the default...

### ISSUE THREAD

**Issue by GordonBGood** [fable-compiler/Fable#2349]
### Description

There have been several issues raised on this that have been closed, with the latest decision seeming to be to revert to the Fable2 default behavior.  However, that isn't how it currently works, as will be seen  below.  This is breaking behaviour as far as performance.

### Repro code

let testarr: uint8[] = Array.zeroCreate 42

### Expected and actual results

Expected result:

import { fill } from "fable-library/Array.js";

export const testarr = fill(new Uint8Array(42), 0, 42, 0);

Actual Result:

import { fill } from "fable-library/Array.js";

export const testarr = fill(new Array(42), 0, 42, 0);

Please provide the expected and actual results.

### Related Discussion

This issue seems to apply to the on-line repl.  perhaps the fix is to provide a switch in the repl settings to enable/disable TypedArray's?

### Related information

* Fable version: Fable 3.1.1
* Operating system Linux Fedora 33 64-bit

**Comment by delneg** [comment]
I'm seeing the following code:
```fsharp
module App
let testarr: uint8[] = Array.zeroCreate 42
```
producing the following JS code:
```
export const testarr = new Uint8Array(42);
```

Using https://github.com/fable-compiler/fable3-samples/tree/main/nodejs as the template (with version changed to Fable 3.1.1 in `.config/dotnet-tools.json`)

**Comment by GordonBGood** [comment]
> Using https://github.com/fable-compiler/fable3-samples/tree/main/nodejs as the template (with version changed to Fable 3.1.1 in `.config/dotnet-tools.json`)

I may have posted the issue in the wrong place.  The problem is with the online repl, not the use of the fable3 compiler.

**Comment by alfonsogarciacaro** [comment]
Yes, this is only happening in the REPL. I've followed @GordonBGood suggestion and changed the default but also adding a switch in the settings to change the `typedArrays` option in the compilation. Can you please check? (you may need to clear the browser cache to get latest version) https://fable.io/repl

**Comment by GordonBGood** [comment]
> Yes, this is only happening in the REPL. I've followed @GordonBGood suggestion and changed the default but also adding a switch in the settings to change the `typedArrays` option in the compilation. Can you please check? (you may need to clear the browser cache to get latest version) https://fable.io/repl

@alfonsogarciacaro, you are the best BDFL with which I have ever had dealings!  Less than one day since I posted the issue, and when I checked as per your request above, it entirely solves the issue for me so I am closing it.  Thank you so much.

**Comment by alfonsogarciacaro** [comment]
Thanks @GordonBGood 😊 Well, this was an easy one and I also had to update the REPL for another reason. Other issues can take mich longer to be fixed 😃
