### ISSUE TITLE
Compiling an empty file yields suspicious js file (Fable 3)

### ISSUE THREAD

**Issue by PierreYvesR** [fable-compiler/Fable#2350]
### Description

When compiling an empty .fs file, or a file that just contains a `Module ModuleName` line, the compiled file contains the following block:
```javascript
export class  {
    constructor() {
    }
}
```
My javascript is pretty limited, but it looks the class name is missing (and Babel complains about it when trying to transpile this file)

### Repro code

Just compile a completely empty file on [REPL](https://fable.io/repl/).

### Expected and actual results

A syntax-correct js file.

### Related information

```
❯ dotnet fable --version
Fable: F# to JS compiler 3.1.1
Thanks to the contributor! @goswinr
3.1.1
```

Running on Windows 10.

and also on [REPL](https://fable.io/repl/)

**Comment by alfonsogarciacaro** [comment]
Yes, I noticed that but didn't look into that deeper because it's not usual that people compile empty file 😅 I will look into this, should be an easy fix. I guess the F# compiler is generating an empty class for empty files and this confuses Fable. Thanks for reporting!

**Comment by PierreYvesR** [comment]
I actually encountered it while messing with fable 3 + babel + mocha. It came up while compiling [Fable.ReactServer.fs](https://github.com/fable-compiler/fable-react/blob/master/src/Fable.ReactServer.fs) from Fable.React.
The file looks like:
```
module Fable.ReactServer

#if !FABLE_COMPILER
(...)
#endif
```

**Comment by inosik** [comment]
As a workaround, [adding a `do ()`](https://fable.io/repl/#?code=LYewJgrgNgpgBAWQFBhHAFASiUA&html=Q&css=Q) produces an empty file.
