### ISSUE TITLE
System.Math.Ceiling() and System.Math.Floor returning incorrect values for some Decimals

### ISSUE THREAD

**Issue by sasmithjr** [fable-compiler/Fable#2355]
### Description

System.Math.Ceiling() and System.Math.Floor() return incorrect values for some Decimal values. It seems to occur to whole numbers with precision, e.g. `Math.Ceiling(3m)` returns 3 correctly but `Math.Ceiling(3.0m)` returns 4.

### Repro code

Repl code [here](https://fable.io/repl/#?code=LYewJgrgNgpgBAWQIYBcAWBhGBLK2B2A5gCowDOKAUJQBQBUdlCB2wSUcSADl3gMapsIfHDJoQAdwKE44iXBQg4EMvACiUYNjGUAmiAhwBIgGYEwcUACd4BE0qQAjAyjhqtYzlb5psKGHwoEDac+BZkSMC85JyuaCgoXGQAXAD0qTCa2mgAdIR+aBCOOUKplHQAlNSwrmAYAIxwALxwAMoAnhQwwDnI6DlYuNI0AMw5AAzAFXDpAKr4MAAeXAH+FjZk0FQ1cHUATM1tnf49fbmDeEQ0JlAgqHBjk1U7dSOHHV2nqOc4l4SjU0oOxMGHex26vW+A1+w0eVSBMFqADFGi0PidIf0kbcQFYaABaR5TGapeZLFaBGDrchbBHIg5o8FfLE4vE3O6uQkTQEvJFvRmfTG5bEgXEEkY8xFwExIsGCs45EVirnjeFcKwEFAmEQAEgARHVGmAAqx2Mk4ABvQ0AXz1lHVmu1cH1+12JrYUHxinx7NQ5qtGD2tvtGvwWt1Bowb2NfFNUH9r2DDrDTv1IOltz9lpBwZDjojYBRbtjHoTKKTofDzoNSIOMbjXpAPszKDLQbtyarLr5xbjZZGFfz1ZlGY5-pltqAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA)

### Expected and actual results

Repl contains a `float` example and a `decimal` example with less precision that match expectations.

### Related information

* Fable version: 3.1.1
* .NET SDK: 5.0.101
* Operating system: macOS 11.1

**Comment by ncave** [comment]
Looks like a rounding-up bug in [big.js](https://github.com/fable-compiler/Fable/blob/nagareyama/src/fable-library/lib/big.js#L257).

**Comment by alfonsogarciacaro** [comment]
Thanks for pointing that out @ncave! That function seems to have changed a bit in [latest big.js](https://github.com/MikeMcl/big.js/blob/aa4ed0ba3210e421c14f46cccadd390a9ef0022a/big.js#L192) (although not exactly the lines you link). Should we try updating it? Maybe it's a good idea to update the whole big.js to latest version in any case, I hope there are no breaking changes.

**Comment by ncave** [comment]
@alfonsogarciacaro I don't think just updating to latest big.js fixes it, cause it's the same code. I tried to fix it in #2360.

**Comment by sasmithjr** [comment]
Thanks, y'all! Greatly appreciate the help!

**Comment by sasmithjr** [comment]
Unfortunately, v3.1.2 caused other Ceiling/Floor values to evaluate incorrectly.

```
System.Math.Ceiling(0.0666666666666666666666666667m) = 0m // ❌ should be = 1m
System.Math.Ceiling(0.09m) = 0m // ❌ should be = 1m
System.Math.Ceiling(0.0999999m) = 0m // ❌ should be = 1m
System.Math.Ceiling(0.1m) = 1m // ✔️
System.Math.Ceiling(0.19m) = 1m // ✔️

System.Math.Floor(-0.0666666666666666666666666667m) = 0m // ❌ should be = -1m
System.Math.Floor(-0.09m) = 0m // ❌ should be = -1m
System.Math.Floor(-0.0999999m) = 0m // ❌ should be = -1m
System.Math.Floor(-0.1m) = -1m // ✔️
System.Math.Floor(-0.19m) = -1m // ✔️
```

**Comment by ncave** [comment]
@sasmithjr You're right, hopefully #2363 fixes it.
