### ISSUE TITLE
Regex.Replace with function and regex with named group constructs incorrect Match

### ISSUE THREAD

**Issue by Booksbaum** [fable-compiler/Fable#2359]
### Description

Regex.Replace with function and regex with named group constructs incorrect Match

### Repro code

```fsharp
let regexIndex = Regex("0(\\d*)")
let regexNamed = Regex("0(?<number>\\d*)")
let text = "number 012345!"

let replace (m: Match) =
    console.log m
    string m.Index

let resIndex = regexIndex.Replace(text, replace)
printfn "regexIndex=%s" resIndex
let resNamed = regexNamed.Replace(text, replace)
printfn "regexNamed=%s" resNamed
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoAqYAeT0BKYA5gK4A2AhgE4CiOI1YCCAlsBAgLABQokUAGKUARuTDoAwsCboAUjF69xSKE2K4AkhAAmuKAF4oRDTgAUAIgAMZgDq2dAKgCUF58rCr1uAHKVUYDqGxiS4ljYA-AA8EKSoImDUAHz2Tq7uPCpQKHjBFrHxiVBWAIwATADMACwArACEFkqZnmpgIFQAxmBQZqgAXFAAspRIHQAWzoa8UDNQHRwIwOLo5MDEUKjTs8jUrBDrGNp6OE1ZTAhH+kbeOJc4hG2dYGY5SAA0re2UXRmMe0gAM2gFhudwMAFIEBZWhddLgPF5mH4AkFrqEcMjAg8vl0Xrh3p8nr9dhBAcCbpidBCoTDKUA&html=Q&css=Q))

### Expected and actual results

Output:
> regexIndex=number 7!
> 
> regexNamed=number number 012345!!

Both should be `number 7` (with `7` being the index of the match in the input), but regexNamed instead returns the original input instead of the index.  
Named groups aren't supported in Fable, but it shouldn't introduce some incorrectness. (someone might access via indices, but copy a regex with named groups from somewhere)

### Why is this happening?

Match objects (via `console.log` in replace function):

regexIndex:
```
0: "012345"
1: "12345"
index: 7
input: "number 012345!"
length: 2
```
regexNamed:
```
0: "012345"
1: "12345"
2: 7
index: "number 012345!"
input:
  number: "12345"
length: 3
```
-> input is set to named groups, index to original input, and index is instead added as additional index (`m.[2]`).

The .Net `Match` lookalike-object is created in https://github.com/fable-compiler/Fable/blob/a7685d442c30b95db9f4fc7e9e3b2c49afe43a8f/src/fable-library/RegExp.ts#L76-L83 from the arguments passed into `replacer` function.  
These [arguments](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/replace#specifying_a_function_as_a_parameter) are:
* `match`: matched substring
* `p1`, `p2`, ...: nth capture group string
* `offset`: offset of matched substring
* `string`: whole string examined
* `groups`: named capturing groups

-> variable number of arguments (based on groups in regex)  
& `groups` is only passed if regex has any named groups

BUT: Fable always takes the last argument as original input `string`.  
-> if last argument is `groups` it takes that as `string` and the other arguments get shifted accordingly.

Fix: check if last element in arguments is of type string. Then it's original input. Otherwise it's groups.

### Related information

* Fable version: `3.1.1` (REPL version: `3.1.1`)

Note: I'm currently working on support for named capture groups and the fix is basically part of it (and how I found this bug in the first place...).  
-> Fix is in the works and should come in the next days.

**Comment by alfonsogarciacaro** [comment]
Yes, Fable delegates to JS regular expressions which unfortunately don't support named groups. This is one of the caveats in the documentation. It'd be great to support named groups although we also have the goal of avoiding too much "overhead". For example, if we add a runtime check to see if the pattern contains a named group, we are adding extra calculations to many cases that may not needed, cannot use a literal js regex, etc (we are already using the global flag by default to match . NET semantics which also adds some overhead). But maybe we could try to identify named groups at compile time...

**Comment by Booksbaum** [comment]
JS does [support named groups](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions/Groups_and_Ranges#using_named_groups), but only for not too old browser or node versions ([compatibility](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Guide/Regular_Expressions#browser_compatibility) -- search for "Named capture groups")

Named groups are in `myMatch.groups`, and access to a named group is `myMatch.groups.["myGroupName"]`.  
So implementing named groups is "just" checking if `groups` exist and then getting accessing the group name: (in TS)
```typescript
myMatch.groups?.myGroupName
```
That's one added null check -- compared to not able to use named groups at all as it's now....

And for `Groups` functions like `Count` or iterating over it: all named groups occur as indexed group too. That means all these function already cover named groups. The other `Groups` functions like `Keys` aren't supported, so no additional issues here.
[REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYDoAqYAeT0BKYA5gK4A2AhgE4CiOI1YCCAlsBAgLABQokUAGKUARuTDoAwsCboAUjF69xSKNSgBeKEWK4oAIgAMACgD8AHgilUIsNQB8AHUcATANQBKfcrCrUmtXQAWUokAGMACwMAOWtbdUMARgAmAGYAFgBWKFYEKBBgNiRWADcwbx5eMI4EYHF0cmBiKFReRlYIJAAzaH1pUk6NAFIAQX0W9ABxamBSEAQpWc6oFYB6VahktuoO7t6ASRRqYbGoYwxp2fmoAB97WDAAR3QkYAAZXKQPKHWoSnJyC1QpFmGcRHAchAXLgPAAaKAQSioMAuKDEGZzKAAAysNjsWJyeQ60JwUESvF+7U6PQMADV-qRmCdxucphj5uh6eRGXk7g9nq8Pshvr8IMBVAg5gVqCgXBSNlS9gYANJgRDMs4XdkLVWIW73GBPF7vT4ijZiiVSmSyoA&html=Q&css=Q)



Identifying at compile time: what if you get the regex or match from some other JS. No chance to identify named group at runtime.  
And there's always the issue with older browsers without named groups support: It would not only depend on the regex but the target browser too. But that's always an issue with JavaScript: Deciding what browser versions are supported and then limit JS to only supported stuff...

**Comment by alfonsogarciacaro** [comment]
Oh, didn't know JS supported named groups in Regex now 😮 That's great! Then please do send the PR and let me know if you have any question/need help. Looking at the compatibility table, the only problem seems to be IE so it should be ok. If users need to support IE, they can use Babel plus core-js polyfills as they do now.
