### ISSUE TITLE
Question about generated JavaScript when using `unbox null` for callback

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2367]
### Description

When using `unbox null` I am expecting Fable to generate `null` or `undefined`.

However, depending on where or for what it is being called the representation can change.

```fs
let x : obj = unbox null
// Generates: export const x = null;

type Application =
    abstract engine: fn: (string -> #obj -> unit) -> Application
    abstract engine2: path: string -> Application   

app.engine(unbox null) |> ignore
// Generates: const value = app.engine(uncurry(2, null));
app.engine2(unbox null) |> ignore
// Generates: const value = app.engine2(null);
```

So it seems like if `unbox null` replace a "callback" then it's use `uncurry`. It seems to works because is defined as:

```js
export function uncurry(arity, f) {
    // f may be a function option with None value
    if (f == null) {
        return undefined;
    }
    // ...
```

But to me it seems like this case is more to handle cases where the bindings contains a function option:

```fs
type Application =
    abstract engine: fn: (string -> #obj -> unit) option -> Application
```

If `unbox null` was to always emit `null` it would avoid the confusion and also help keep the code be cleaner. And save a few bytes :stuck_out_tongue_closed_eyes: 

If that's the expected result, then it is also fine. But a bit confusing when looking at the generated code.

It is also possible that in practice this kind of case are not often encounter or the binding will use `option<callback definition>`.

### Repro code

[REPL demo](https://fable.io/repl/#?code=LYewJgrgNgpgBAFRgZwC4Ch0gA4wHZwBiAhgEawB0AwiAE4xa4EDKAnmjMJqq7nAILZsUAJYBjYqhEgCAXnRxFcMmlrExqOPgDmIvDABccAGZ4jAClV7tcALQA+OAGIQpAFZ3HEPCNQBKTwEhUQkpGQUlFVQ1DS08XX0AJiNsSQALIyt4wMFhcUlpAiVMWE0ADzgjVw9ZOG9SEAq8aCh0UrhWSrhLaOtA6sDvXwDa+saAHh7aPoc4Admh-0dmqFaSmE1iIS7ckIKZOFq3ZAA5AoA3BnQt7AodPRhzMaaWgIAfRxFtPDoGG7v4g9Ek88A0Xqt3p9vr8gA&html=Q&css=Q)

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `npm show fable-compiler version` or `yarn info fable-compiler version`: 3.1.1

**Comment by alfonsogarciacaro** [comment]
Yes, I also noticed this a few days ago and tried to ignore it 😅 I think it's because of this, which triggers uncurrying for values of function option type even if they are None: https://github.com/fable-compiler/Fable/blob/69d672e376d94fd55c0288e352a4190d0c215b82/src/Fable.Transforms/FableTransforms.fs#L363-L373

This was a hack to fix some tests. But I need a more formal solution because similar problems with uncurrying are being reported when wrapping functions in lists or unions. Hopefully fixing those solves this issue too.

**Comment by alfonsogarciacaro** [comment]
At the end I just fixed this by making `uncurry` just return the argument if is null (instead of `undefined`), would that work for you?
