### ISSUE TITLE
fable-library char says `“` and `”` are letters

### ISSUE THREAD

**Issue by NickDarvey** [fable-compiler/Fable#2376]
### Description

fable-library char says `“` and `”` are letters when calling `System.Char.IsLetter`. This is inconsistent with the dotnet BCL's behaviour.

### Repro code

https://github.com/NickDarvey/Fable/commit/81658ff20ffa87eff9aa6155b9b252542bbd889d

### Expected and actual results
Expect tests pass. Actual:
```
 1927 passing (7s)
  1 failing

  1) Chars
       Char.IsLetter works:

      Error: Expected: false - Actual: true
      + expected - actual

      -true
      +false

      at assertEqual (build\tests\.fable\fable-library.3.1.2\Util.js:51:29)
      at Testing_equal (build\tests\Util\Util.js:37:5)
      at Context.<anonymous> (build\tests\CharTests.js:40:5)
      at processImmediate (internal/timers.js:461:21)
```
### Related information

Forked from https://github.com/fable-compiler/Fable/commit/97093df8228558dbae07e8266eff178dd75eaf83.

**Comment by alfonsogarciacaro** [comment]
@ncave I think you implemented `IsLetter` using unicode categories, would it be possible to have a look?

**Comment by ncave** [comment]
@alfonsogarciacaro I'll take a look, we may have to update the unicode mapping to latest.

**Comment by NickDarvey** [comment]
Thanks @ncave! That was rapid
