### ISSUE TITLE
static let orphaned if not used

### ISSUE THREAD

**Issue by Jmaharman** [fable-compiler/Fable#2388]
Firstly, I do not need this fixed myself, but I spotted and thought it would be good to log.

The separate issue you spotted when fixing #2383 appears to have had a strange side effect on an unused static let. 

This first example appears to add the static let, although in a separate location to the static function:

```fs
open Fable.Core
open Fable.Core.JsInterop
open Browser
open Browser.Types

// Stimulus controller abstract class
[<AttachMembers>]
type GreetController() =

  static let targets = [| "name" |]

  static member staticFunction() =
    console.log("static function")

  member this.greet() =
    //console.log("Hello!")
    console.log((sprintf "Names list %A" targets))
```

Which produces

```js
export class GreetController {
    constructor() {
    }
    static staticFunction() {
        console.log(some("static function"));
    }
    greet() {
        console.log(some(toText(printf("Names list %A"))(GreetController.targets)));
    }
}

export function GreetController$reflection() {
    return class_type("Test.GreetController", void 0, GreetController);
}

export function GreetController_$ctor() {
    return new GreetController();
}

(() => {
    GreetController.targets = ["name"];
})();
```

[In use targets example](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWo+40AQkwO6WMuEfBujVABUAnuEq5cAehlQAynQCWAWwCuSdZSgBjYPSZIUWKIkp0scXXT1I4lKQG0APAEE6dawAsAsmFUERkoAPgBdXDoJMCgAcRwwOkxDYGNGAAoASigAXmkoKAs4FV0oFFsvLABzRJ0cqCcAHygAIgg4VTAWqEaI3AKikqhOwMZCrxKYdQgbZQMs3P6CvQNKVLQkYCr0lsHlUoAzadmDFsz84YCg0zpvZUpUKoS6BbzlqDl9CDWSTe2WgASYGMwAAhGclgUvj8Nlt0ulKCAsMp6AdWgA5DpgHRIe62ACkbm6lRqdEomUyQA&html=DwCwLgtgNgfAUHUBTAhgE3gAk8CSwqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEt2QCoBPEkmaYAxlx7cWPAB5gA9OGgBuCSBQAnAM75G1MADMyADmZYcO8VtokwmHVvGMARMRI6AXIsXVOJADWAOYAdJIQigACAO5IAEYRJFy8YDqK4tQ6YOwQFFBIeNw6UQCMoQBMoQAMGVk5eUgFRWmhELScoQBWOq4wwIrWtvaWwEN2Dk4u7mCk3r7+QWER0XGJucmcqek6mmiCaLlloeUAzIN7B7ltHd29-YM2E-ADIKgYCMDx7PsSUCg6HRuFAkciSbgoDpILR9ODYbC4QRkeKGHKcTD-eJNNzsdh9AYQJEo2ZcF6Kb77eCIZSQWBwIA&css=Q)

If you swap the commented out console.logs in greet you'll notice setting targets on GreetController changes to the below.

```js
(() => {
    const targets = ["name"];
})();
```

[Orphaned targets example](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWo+40AQkwO6WMuEfBujVABUAnuEq5cAehlQAynQCWAWwCuSdZSgBjYPSZIUWKIkp0scXXT1I4lKQG0APAEE6dawAsAsmFUERkoAPgBdXDoJMCgAcRwwOkxDYGNGAAoASigAXmkoKAs4FV0oFFsvLABzRJ0cqCcAHygAIgg4VTAWqEaI3AKikqhOwMZCrxKYdQgbZQMs3P6CvQNKVLQkYCr0lsHlUoAzadmDFsz84YCg0zpvZUpUKoS6BbzllYg1kk3tloAJMDGYAAQjOSwKcn0n3WqB+6XSlBAWGU9AOrQAch0wDokPdbABSNzdSo1OiUTKZIA&html=DwCwLgtgNgfAUHUBTAhgE3gAk8CSwqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEt2QCoBPEkmaYAxlx7cWPAB5gA9OGgBuCSBQAnAM75G1MADMyADmZYcO8VtokwmHVvGMARMRI6AXIsXVOJADWAOYAdJIQigACAO5IAEYRJFy8YDqK4tQ6YOwQFFBIeNw6UQCMoQBMoQAMGVk5eUgFRWmhELScoQBWOq4wwIrWtvaWwEN2Dk4u7mCk3r7+QWER0XGJucmcqek6mmiCaLlloeUAzIN7B7ltHd29-YM2E-ADIKgYCMDx7PsSUCg6HRuFAkciSbgoDpILR9ODYbC4QRkeKGHKcTD-eJNNzsdh9AYQJEo2ZcF6Kb77eCIZSQWBwIA&css=Q)

**Comment by alfonsogarciacaro** [comment]
Thanks @Jmaharman! Yes, this looks a bit odd, but please note that although we try to Emit code that plays well with native JS, and the AttachMembers attribute is a effort in that direction, some things will remain implementation details that are subject to change in different Fable versions, particularly private fields.

In this case I think it's just a direct translation of the representation in the F# ast. If you need to expose the member in JS, please use `static member`.

**Comment by Jmaharman** [comment]
It's not a `static member` I'm trying to expose, but the `static let`, as per the stimulus controller targets.

https://stimulus.hotwire.dev/reference/targets#definitions

After the [twitter conversation ](https://twitter.com/Emmet_Ray/status/1360671637037793280?s=20) referenced in #2383 I was intrigued as to what was possible with the newer JS syntax. It may be that stimulus controllers may not get a big benefit from being in F# as they look more dynamic than I first anticipated.

Anyway, if you're happy I'm happy. Feel free to close the ticket if you do not feel it needs any work.

**Comment by alfonsogarciacaro** [comment]
Thanks @Jmaharman! Yes, I agree. If a library requires some very JS-specific ways of interaction it's usually better to just use JS. Ok, then let's close this and we can reopen in the future if we find some new interesting to interop with hotwire from Fable :+1:
