### ISSUE TITLE
Fable 3 - try with custom error

### ISSUE THREAD

**Issue by JordanMarr** [fable-compiler/Fable#2396]
### Description

After upgrading to Fable 3, a try catch must have a default error pattern match if a custom exception type match exists.

### Repro code

The following fails to compile in Fable 3 (but it compiled previously in Fable 2):
```fs
    async {
        try
            let! res = asyncWorkflow
            onSuccess res
        with
        | :? Fable.Remoting.Client.ProxyRequestException as ex -> onEx ex
    } 
```

```
error FABLE: Cannot resolve replacement System.Runtime.ExceptionServices.ExceptionDispatchInfo.Capture
error FABLE: Cannot resolve replacement System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw
```

This change fixes it in Fable 3:

```fs
    async {
        try
            let! res = asyncWorkflow
            onSuccess res
        with
        | :? Fable.Remoting.Client.ProxyRequestException as ex -> onEx ex
        | ex -> raise ex // <-- This fixes the issue
    } 
```

### Expected and actual results

I'm assuming it should automatically insert a general error handler if one is not provided.

### Related information

* Fable version: 3.1.5
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Sorry for the late reply, hopefully this will be fixed in the next release :+1:
