### ISSUE TITLE
`uncurry(1, ...` generated when casting a named `unit -> a` function to Func<a>

### ISSUE THREAD

**Issue by stkb** [fable-compiler/Fable#2400]
Thanks for all the recent work on fixing the (un)currying issues. For me my project was going pretty smoothly until I hit another (small) one. Thankfully this one was pretty easy to isolate and also to work around.

### Description

[REPL link](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQWD0OoAqAFgJYJRlQBmJEYAdFAMLCogkA2Y5SwAXLnxQoAY2ARk1AK4QRARigBeKAAoAlEoB8UOQG4sXJFBAAnEgDcAhimmyFfKADEZIgDy0k25c9nuInlSoZVQ0AWm05NSxBQlJySghgJABCZlZ2Lh5+GOExCSMg2QAmJSgXKRMTOBU5ABpqCCL1NX1MQ2MzKxsqRpDSuQMwI1MLazBbERKHHzcPLycXPwCeoqjMIA&html=Q&css=Q)

These two cases should essentially produce the same code, but don't.

``` fsharp
open System

// This is fine. Compiles to:
//   const func1 = () => 1;
let private func1 : Func<int> = Func<int>(fun () -> 1)

// This is not! Compiles to:
//   const func2 = uncurry(1, fn2());
let private fn2 () = 1
let private func2 : Func<int> = Func<int>(fn2)
```

When casting a function with signature `unit -> a` to type `Func<a>`:
* If it's done "inline" on a lambda it's fine.
* But if done on an existing named function, then the generated code has an `uncurry(1, ...` expression, which in turn gives an error message because '1-arity' is invalid for the uncurry function.

Seems to only happen with that function signature; other-arity functions work ok

### Related information

* Fable version: 3.1.5
* Windows 10

**Comment by alfonsogarciacaro** [comment]
For some reason, when converting to `Func<'T>` instead of using `Func<unit, 'T>` in the AST the F# compiler applies a unit argument to the expression to be converted (something like `Func<int>(fn2())`). Not sure if it's a bug but I'm checking the expression for this case and "unwrapping" it. Hopefully I'm doing it right, at least it solves this case :)

**Comment by stkb** [comment]
Belated thank you!
