### ISSUE TITLE
Structural equality gives inconsistent results for records with NaN

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#2404]
### Description

Comparing two records that have a `float` value of `NaN` gives inconsistent results 

### Repro code

```fs
open System

type Row = { number: float }

let firstRow = { number = Double.NaN }
let secondRow = { number = Double.NaN }

// true
printfn "firstRow = firstRow => %b" (firstRow = firstRow)
// false
printfn "firstRow = secondRow => %b" (firstRow = secondRow)
```
Notice how comparing the `Row` instance with itself (firstRow = firstRow) gives the correct equality answer but it gives `false` when comparing with `secondRow` which has the same value

### Expected and actual results

Expected `firstRow = secondRow` to yield `true`
Actual: yields `false`

### Related information

* Fable version: 3.1.5
* Operating system: Windows 10

**Comment by Zaid-Ajaj** [comment]
Actually I take it back, it is probably that `firstRow = firstRow` is what giving the wrong value since that should actually be `false` 😱 according to F# and `NaN`/floating point rules rules 

![2021-03-04 11_50_10-Administrator_ Developer Command Prompt for VS 2017 - dotnet  fsi](https://user-images.githubusercontent.com/13316248/109954821-12839b00-7ce2-11eb-8d5f-31d04c868b87.png)

**Comment by alfonsogarciacaro** [comment]
Hmm, interesting. There's an optimization for record equality that first checks if the two objects share the same reference. I guess to "fix" this we would have to remove the optimization which would be a real pity. .NET behavior is actually a bit unexpected here, do you need it? We already have some discrepancies when dealing with numbers.

**Comment by Zaid-Ajaj** [comment]
> .NET behavior is actually a bit unexpected here

After a bit of research, it turns out that this is indeed expected because `NaN <> NaN` 

> do you need it?

No, I don't and I don't think it really matters a lot tbh but I still worth mentioning in case it has other ramifications that I am not aware of

**Comment by Zaid-Ajaj** [comment]
Let's close this, I don't think this needs "fixing" at the Fable level when you have `NaN <> NaN`
