### ISSUE TITLE
String interpolation with escaped percentage sign has incorrect output

### ISSUE THREAD

**Issue by sWW26** [fable-compiler/Fable#2407]
### Description

Trying to insert a `%` while using string interpolation results in a `%%` in the output

### Repro code

https://fable.io/repl/#?code=A4JwlgdgLgZgBAEgEQFIwG8CMBfOKVJA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q

### Expected and actual results

Expected: $"%i{1}%%" = "1%"
Actual: $"%i{1}%%" = "1%%"

### Related information

* Fable version: 3.1.5
* Operating system: Windows

**Comment by MangelMaxime** [comment]
Hello, can you please try with the latest version 3.1.8?

There has been a fix recently related to `%` in string interpolation https://github.com/fable-compiler/Fable/issues/2394

Perhaps, it fixed your problem too

**Comment by sWW26** [comment]
Thanks @MangelMaxime its fixed in the latest version.  Not sure how my searches didn't find that other issue! 😕
