### ISSUE TITLE
`DateTimeOffset(DateTime, offset)` fails when `DateTime.Kind = Unspecified` and `offset` doesn't match local timezone

### ISSUE THREAD

**Issue by Booksbaum** [fable-compiler/Fable#2411]
### Description

`DateTimeOffset(DateTime(Kind = Unspecified), offset)` fails for offsets not matching local timezone.

<br/>

`DateTimeOffset(DateTime, offset: TimeSpan)` creates a DateTimeOffset from passed Date with custom offset -- as long as that offset follows the specified `DateTime.Kind`:
* `UTC`: only `offset = 0` valid
* `Local`: offset must match local time zone: `DateTimeOffset(DateTime.Now, TimeSpan.FromHours(1.0))` (Standard Time in Central Europe)

Last `Kind` is `Unspecified`:
* No offset specified (`DateTimeOffset(DateTime)`): uses local offset
* with offset: uses specified offset. But in Fable it still behaves like `Local` and allows only offsets matching the local timezone.

### Repro code & Output

```fsharp
let unspecified = DateTime(2008, 5, 1, 8, 30, 52, DateTimeKind.Unspecified)

let offset = TimeSpan.FromHours(1.6)  // using timezone offset that's (hopefully...) not used anywhere
printfn "%A" <| DateTimeOffset(unspecified, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh0BsxKgVwgXAGMBLAMzLABMoBeKAEQEMUAVM1MACgCYADAIAcAGigBWcQEZxYqAGYB4iX3GsOXMAGkyEGgDoAqkVKVqNAJSYceYBQoJcDKJ24wQLCAYBiAJ2BUAAlgfD8EHmkDADZrED89JApoACIAUgBBFKgAHgAfZjYwNzAAeQcnJB5CYjByKlpxe0dcSyA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +01:36

Fable:
> Exception: `The UTC Offset of the local dateTime parameter does not match the offset argument.`

And: `DateTimeKind.Unspecified` is used when no `DateTimeKind` is explicitly given. -> This fails too:
```fsharp
let dt  = DateTime(2008, 5, 1, 8, 30, 52)

let offset = TimeSpan.FromHours(1.6)
printfn "%A" <| DateTimeOffset(dt, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh0BsxKgEzwF4oARAQxQBUBLVMACgCYAGFgDgBooBWbgRm5coAZhbceTAJSYceYADMFCXFBK16MEOQgA6AGIAnYKgASwAK6GEDfroBsMkIZoQkC6ACIApAEFPUAA8AD5klGAaYADySipIDITcisq4UkA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +01:36

Fable:
> Exception: `The UTC Offset of the local dateTime parameter does not match the offset argument.`

Only accepted offset is `offset = local offset`:
```fsharp
let dt = DateTime(2008, 5, 1, 8, 30, 52)

let offset: TimeSpan = !! (dt?getTimezoneOffset() * -60_000)
printfn "%A" <| DateTimeOffset(dt, offset)
```
([repl](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMQIYBGANmAHQDCwATmQFIICSEKVo66JSUAJlwLxQAInhQAVAJaowACgBMABnkAOADRQArGoCMa1VADM8tetkBKdpyjAAZtYRgkALigSpMEHmgD0AYnHXcAEEAIQAZAFEAfXIAeQBZAAUGCIAldCgMqABCLKhpXgB+AHMHVzAAL2AIMBjbeyRpUygAKigAWgA2eUjFeXMfMCJ7dMyygC0qsCZrYFJQ4ABjPCJSAHEHAFUkBdq7B3ykfshuf3YQKnFma2gAIgBSQJuoAB4AHyERMDLd+oO1Gz2hyAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwssOYLona6pMJl3aJTAEQB9TwAkA8gDKAt5KUHQARrpK2qgSYAB0pNocaDRxdNzxEHRc8QBWuu4wwEq29o5W2DZ2Dk4ubl6+gcGeoRFRMShx5GgcEInJqemZ2bkFRSVltfAlIKgYCMDhKUKSUCi6uh4opBRSPCg5SNpFcDi4aIyYdGgeSFDZuiDkO6Tuaxtb7vePz68TSkuDBmSmWaCE8EQKkgsDgQA&css=BYFwtgNgNAUARgewCYE8AEBvGadoGYIB2IAtAM4CWAXgKYBcaAjAGwAOAHgNwwC+MMAOjABDCoRIBjIiFGEaAJ0zZcSCmVYRhKBngg0uynAHcKSEMAaMADFYCk3XGmA0KAc1CWb9w2gBWAVzIQCjwUSWkaYgYJSJAFB1xhCDdxCjiwMmjY+J9dfRJVeRoJYKJohAh-MEJuPkExVn8QJUdWYSRVQlcGAQAmAFYisAScAmJyanomNgNHEzMLNAGrDhG0EXlXMRJEEBAEMEsh2pggA))

.NET:
> 2008-05-01 08:30:52 +02:00

Fable:
> 2008-05-01 08:30:52 +02:00

### Related information

* Versions:
  * Fable: `3.1.5`
  * Repl: `3.1.5`

Note: I'm currently working on this one. It's a case of: easy to fix, hard to unit test...:  
Is there a way to use a specific timezone in a unit test?  
I'm currently getting the local time zone (like above) and using that for tests. But that means: 
* different tests on different systems 
* Cannot test for both normal time and summer time (daylight saving time)
* I have to adjust unit tests to ensure they match or don't match the local offset 
* Less useful tests on systems with local time = UTC

**Comment by MangelMaxime** [comment]
Hello @Booksbaum ,

in https://github.com/fable-compiler/Fable/issues/2375 someone mentioned that it should in theory be possible to force the timezone using an ENV variable.

I didn't test it yet, so I can't be sure if this will works or not.
