### ISSUE TITLE
Nested React Components fail to compile

### ISSUE THREAD

**Issue by roboz0r** [fable-compiler/Fable#2412]
### Description

If a function tagged with `[<ReactComponent>]` calls another function also tagged with `[<ReactComponent>]` on the same line of code the compiler fails with the following message `EXCEPTION: Cannot find implementation file /`. If the component is bound to a value prior to being passed the compilation is successful. 

### Repro code

From the Felliz template I modified `App.fs` per below

    module App

    open Feliz

    [<ReactComponent>]
    let Comp3 (children:ReactElement) = Html.div [ children ]

    [<ReactComponent>]
    let Comp2 ()  = Html.h1 "Hello world"

    [<ReactComponent>]
    let HelloWorld() = 
        Comp3 (Comp2 ())

If `HelloWorld` is changed to:

    [<ReactComponent>]
    let HelloWorld() = 
        let comp2 = (Comp2 x)
        Comp3 comp2

Then the code is able to compile. 

### Expected and actual results

Expected: The code compiles.
Actual: Fable compiler reports the following `C:/Projects/Feliz Template/src/App.fs(1,1): error EXCEPTION: Cannot find implementation file /`

### Related information

* Fable version: Fable: F# to JS compiler 3.1.10 
* Operating system: Windows 10. Compiling through VS Code powershell terminal. 

    Feliz Version="1.37.0"
    Feliz.Router Version="3.7.0"
    Fable.DateFunctions Version="3.7.0"

Note: `npm show fable-compiler version` (shown in this form template) shows version 2.13.0. Suspect this is no longer relevant now Fable is a dotnet tool. Used `dotnet fable --version`.

**Comment by roboz0r** [comment]
Cross posted on the Feliz repo as not sure where the error lies https://github.com/Zaid-Ajaj/Feliz/issues/331

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @roboz0r! This requires a fix in the plugin, I've added a comment to the issue in Feliz repo :+1:
