### ISSUE TITLE
Fable.React fails to compile after update to Fable 3.1.11

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#2414]
I'm not completely sure what the reason is, but after update to Fable 3.1.11 we see:

![image](https://user-images.githubusercontent.com/57396/111433615-ce8b8f80-86fe-11eb-8b2f-da958686427c.png)

**Comment by Zaid-Ajaj** [comment]
can you remove cache and restart:
```bash
dotnet fable clean --yes
```

**Comment by forki** [comment]
apparently no.

**Comment by alfonsogarciacaro** [comment]
Oh, my. I'm breaking everything with each release 🤦 I assume you only updated Fable and no other dependencies. What was the previous Fable version you were using?

**Comment by forki** [comment]
Yes. Only updated fable from 3.1.10 to 3.1.11. Downgrade fixes everything

Alfonso Garcia-Caro ***@***.***> schrieb am Mi., 17. März
2021, 11:32:

**Comment by alfonsogarciacaro** [comment]
Actually the problem was in Fable.React because it has an `Emit` with a JS statement, and in Fable 3 you need to add `isStatement=true` in those cases. I've changed it to use a JS expression instead. Can you please try with Fable 3.1.1 and Fable.React 7.0.3?

Sorry for breaking your app so many times, and thanks a lot for reporting!

**Comment by forki** [comment]
Yes that seems to work. Awesome!

Am Mi., 17. März 2021 um 13:21 Uhr schrieb Alfonso Garcia-Caro <
***@***.***>:

**Comment by alfonsogarciacaro** [comment]
I just realized that Fable.React is a mess because I published two versions 7.1.0 (broken) and 7.2.0 from a branch that has not been finally merged. I've unlisted those two versions and republished as 7.3.0 with the fix in case other people that already updated to 7.2 have the same issue.

**Comment by MangelMaxime** [comment]
Hello @alfonsogarciacaro,

I think version 7.0.1 of Fable react also contains the broken code.

![image](https://user-images.githubusercontent.com/4760796/115965022-7464c200-a527-11eb-9fc6-4e1c764c18cc.png)

Surprisingly, when using webpack to compile for the browser I don't have any error/crash. However, when running it on node.js for testing purpose I get a crash.

Should we also unlist Fable.React 7.0.1 and 7.0.2 ?

It seems like you released the fix in version 7.0.3. 

https://github.com/fable-compiler/fable-react/commit/412b711c9e4e30bf1ffa9303dd42ba609b8fcea3#diff-99c8562fb974e3cdf209c74461078604f6a539599c7c077c7789cca7efb05f20
