### ISSUE TITLE
Mangling issue with some overloads

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#2417]
For example, the following two overloads:

```fs
    static member OfList(elements: list<'K * 'V>) = ()
    static member OfList(elements: list<struct('K * 'V)>) = ()
```
seem to generate the same mangling (and trigger an error).
Perhaps we need an extra bit there for value types.

**Comment by alfonsogarciacaro** [comment]
Hmm, right now we are only checking for `struct` in generic constraints: https://github.com/fable-compiler/Fable/blob/85f0459a91db711095fe9bf8bd6cc0f74eefb536/src/Fable.Transforms/OverloadSuffix.fs#L68

We probably need to check for structs in the case of tuples too: https://github.com/fable-compiler/Fable/blob/85f0459a91db711095fe9bf8bd6cc0f74eefb536/src/Fable.Transforms/OverloadSuffix.fs#L88-L89
