### ISSUE TITLE
Breaking changes in JSON serialization introduced in 3.1.6

### ISSUE THREAD

**Issue by JohnTheGr8** [fable-compiler/Fable#2418]
First things first, thank you all for your work in this project.. it has been a delight using Fable for the last ~3 years!

### Description

I caught a regression after upgrading a project from Fable **3.1.5**. I use Fable alongside **Thoth.Json** (and **Thoth.Fetch**), and upgrading from 3.1.5 caused data serialized on the client-side to fail to deserialize on the server-side.

After some (admittedly not very thorough) digging, I have found that the behavior of `Fable.Core.JS.JSON.stringify` - when used with lists specifically - was changed in Fable **3.1.6** and probably in [this commit](https://github.com/fable-compiler/Fable/commit/80c2bca08d4ba4df3c7771178ccfba7b3e064dbe#diff-6c42f9ea66826c0c9cf544bd8a40a919bd1b1700c2988825e8094bbc28892503). This change is not mentioned in the release notes as intended, so I assume it is not.

### Repro code

As a quick example, the following code:

```fsharp
Fable.Core.JS.JSON.stringify [ "a"; "b"; "c" ]
```
when ran with **Fable 3.1.5** gives:
```json
["a","b","c"]
```
whereas with **Fable 3.1.6 - 3.1.11** it gives:
```json
{"head":"a","tail":{"head":"b","tail":{"head":"c","tail":{"head":null}}}}
```

### Related information

* Fable 3.1.6 up to 3.1.11
* Fable.Core 3.2.5

(I am not familiar with this codebase.. hopefully the above information is enough to get an idea for what is going on)

**Comment by ncave** [comment]
@alfonsogarciacaro We're missing the `toJSON` attach method on the List object, but I'm not sure how to add that. Is there a way to force a single method to be attached?

**Comment by alfonsogarciacaro** [comment]
Thanks for report and the nice words @JohnTheGr8! Ah, damn, forgot about the "native" JSON serialization with `toJSON`. Yes, we need to add it back to list to avoid breaking changes and it's probably a good idea to add it to other fable-library types already coded in F# like BigInt, maps or sets. @ncave I think there's no way to explicitly mark a method as attached, but we can just declare an `IJsonSerializable` interface with a `toJSON` method and make list (and other types) implement it.

**Comment by alfonsogarciacaro** [comment]
I've added back `toJSON` to lists, and also bigints, maps and sets. I had some doubts particularly in the case of MutableMap and MutableSet because the native JS Map and Set (which are used for primitive keys) don't work with `JSON.stringify` but I finally did it for consistency with the types within fable-library. Hopefully this doesn't cause other problems.

**Comment by JohnTheGr8** [comment]
Thank you for the quick response and fix, looking forward to the new release.

**Comment by MangelMaxime** [comment]
I am a bit surprised that you add this kind of problem with Thoth.Json.

I would have expected Thoth.Json to not be affected by this problem. 

@JohnTheGr8 Could you please share with us how you use `Thoth.Json` to encode list?

**Comment by JohnTheGr8** [comment]
> 
> 
> I am a bit surprised that you add this kind of problem with Thoth.Json.
> 
> I would have expected Thoth.Json to not be affected by this problem.
> 
> @JohnTheGr8 Could you please share with us how you use `Thoth.Json` to encode list?

I use it with Thoth.Fetch like I mentioned, nothing special really... I see that Thoth.Json's `Encode.toString` [uses JS.JSON.stringify](https://github.com/thoth-org/Thoth.Json/blob/master/src/Encode.fs#L358) which should explain it.

@MangelMaxime If you want me to expand on this any further, let me know and I'll be happy to.

**Comment by MangelMaxime** [comment]
Thoth.Json use it as the last moment, at that moment all the list should have already been converted into a JSON compatible type.

I am interested in see how you write the `Encoder` in the case of a list or to know if you use auto encoder.

**Comment by JohnTheGr8** [comment]
Okay, I see what you mean. I have done some more testing, removing any extra coders I had to try to boil it down. I am getting some strange behavior...

I have a helper module that looks like this:

```fsharp
[<RequireQualifiedAccess>]
module F =
    let inline post<'a> (url, data) : Fable.Core.JS.Promise<'a> =
        Thoth.Fetch.Fetch.post<_,'a> (url, data = data)
```

which I typically use as a shorthand with elmish like so:

```fsharp
Cmd.OfPromise.either F.post ("/endpoint", [ "a"; "b"; "c" ]) onSuccess onFailure
```

Using the above in Fable 3.1.6 sends the bad json payload I mentioned above. **However**, if I move this module to the same file as the page that calls it, it produces the expected json and everything works... 🤷‍♂️ 

I have tested the exact same situations (putting `F` in same/separate file) with Fable 3.1.12 and both cases work just fine.

Does this make any sense?

**Comment by alfonsogarciacaro** [comment]
Hmm, it's difficult to say without seeing the code but my guess is somehow the generic parameters were not inferred correctly and serialization was just defaulting to `toJSON` which was removed in 3.1.6 for lists and brought back in 3.1.12.

I have a similar inlined helper for different http methods (get, put, post, delete...). Can you please check what the IDE says and whether the generic parameters are filled with the expected types?

![image](https://user-images.githubusercontent.com/8275461/112241511-b6cb8280-8c8d-11eb-8e74-7a4cbd46589f.png)

**Comment by JohnTheGr8** [comment]
@alfonsogarciacaro good call. I found some time to look into this some more:

When the `F` module (same as above)  is in its own file, `data` is inferred to be of type `obj`. If I set it to be a generic type like `'Request`. it works as expected with fable 3.1.6

When the module is in the same file, `data` is not treated as an `obj`. (I only called `F.post` from one place to test it, and so it picked `data` to be of type `string list`, which explains why it worked.) If I try to use `F.post` elsewhere I get a compilation error.

So, when having the module in the same file, the compiler is forcing me to add a generic type annotation. Do you have any idea if this is normal/expected?

@MangelMaxime tldr: thoth had a problem in fable 3.1.6-3.1.11 because the request object was treated as `obj`. Does it make sense now?

**Comment by alfonsogarciacaro** [comment]
@JohnTheGr8 It's difficult to say without opening the full project in an F# IDE, but it's true type inference sometimes can yield unexpected results, particularly in inlined functions or recursive modules. The safest bet is always to use type annotations in the function signature, this is also a good practice for public utility methods because it makes the function better documented and avoid unexpected changes (when type inference changes for some reason).

**Comment by MangelMaxime** [comment]
> @MangelMaxime tldr: thoth had a problem in fable 3.1.6-3.1.11 because the request object was treated as obj. Does it make sense now?

@JohnTheGr8 Yes think the cause was due to what Alfonso explained. And indeed, in the case of obj it's possible that we fallback to the default serialiser to support some specific case in the case of the Auto module..

**Comment by JohnTheGr8** [comment]
Thank you, guys!
