### ISSUE TITLE
Customize generated source maps

### ISSUE THREAD

**Issue by mlaily** [fable-compiler/Fable#2427]
*This is a follow up for https://github.com/delneg/source-map-sharp/pull/5 (Fix option serialization).*

I would like to be able to override the default settings used by Fable to generate source maps.

In particular, as a Fable user, I would like to be able to set the `sourceRoot` property to "file:///" so that source maps work out of the box without requiring another tool (e.g. webpack or another bundler).

I have verified this would work in Chrome on Windows.

It wouldn't currently work in Firefox on Windows, because of something looking like a bug (https://bugzilla.mozilla.org/show_bug.cgi?id=1702920). A workaround would be to url-encode the colon following the drive letter (It seems Firefox interprets `C:/` as an url scheme, making the source path absolute and preventing the `sourceRoot` from being used), so I wonder if Fable could also allow to somehow customize the source paths in its source maps... (Simply always url-encoding colons might be a solution, though I'm not sure it's a good idea)

- Supposing I was to make a PR, how would you like me to expose the `sourceRoot` property from the Fable CLI? (Should I add a CLI option? Is there another extension mechanism? A settings file maybe?)
- What's your opinion about the suggested workaround for the Firefox bug?
  - Would url-encoding the source paths be acceptable? (I don't know how webpack and co handle these urls, so it might maybe break things?)
  - As an alternative, I was thinking of maybe exposing a setting when generating source maps to make Fable choose between simple absolute paths (like currently), or relative paths (either the nearest common folder for all sources, or a manually configured folder, I'm not sure...)

I can start by making a PR to expose just the `sourceRoot` property for now, but I'd really like your opinion about all this before I submit anything... :)

**Comment by alfonsogarciacaro** [comment]
TBH, I got the source maps working by trial-and-error so I'm not sure what would be the best way to make them configurable 😅 Obviously the most important thing is to avoid breaking current configurations, but it should be ok to expose a `--sourceRoot` cli argument. Maybe we could use a macro-like pattern? As in `--sourceRoot file:///{absolutePath}` or `--sourceRoot file:///{relativePath}`

> Fable 3 only accepts options via CLI, I'd like to avoid config files for now. If at one point we need to add them, I would prefer to have something like a JSON that just mimics the CLI args.

**Comment by mlaily** [comment]
Alright, thanks for your feedback!

> Fable 3 only accepts options via CLI, I'd like to avoid config files for now. If at one point we need to add them, I would prefer to have something like a JSON that just mimics the CLI args.

Understood. I was just a bit loath to pollute the CLI by adding obscure settings... I'll see if I can figure something out.

Thanks again :)
