### ISSUE TITLE
Stale issues

### ISSUE THREAD

**Issue by mabasic** [fable-compiler/Fable#2440]
### Description

@alfonsogarciacaro I have noticed that there are a lot of old issues related to Fable 1 and 2 and/or are resolved but not closed. Do you need help with issues? I can go through each one, ask for current status and if not reply in a couple of days close them. If the issue is in regard to an older version of Fable, it can also be closed I think. There are a bunch of issues with ideas and discussions but nothing actionable. Those can be moved somewhere or better structured. What do you think?

I think that when people see 100+ issues they think that something is wrong, but it seems that the case is that a lot of issues are just old or outdated.

Examples:

https://github.com/fable-compiler/Fable/issues/1285

https://github.com/fable-compiler/Fable/issues/1433

https://github.com/fable-compiler/Fable/issues/1422

https://github.com/fable-compiler/Fable/issues/1593

https://github.com/fable-compiler/Fable/issues/1777

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for looking into this @mabasic! Yes, I try not to close issues too early in order not to be rude but then I forget about them and they just accumulate 😅 It's probably about time to do a cleanup of stale issues. I'll go through the ones you link and also through the remaining open ones in the coming days :+1:

**Comment by mabasic** [comment]
Awesome. Let me know if you need help. Feel free to close this one first 😉

**Comment by cartermp** [comment]
This meta issue can be closed now, as all the listed stale issues have been closed!

**Comment by mabasic** [comment]
Yes, but there are a lot of other issues to close too. I've provided here just a few examples of issues to close.

I am willing to do go over all issues to help speed this process along.

**Comment by cartermp** [comment]
Do you have some more examples? I did a pass a few weeks ago and several issues were closed. There's only 92 open issues now, which isn't exactly a big deal for a project as large and ambitious as Fable.

**Comment by mabasic** [comment]
I have skimmed a few of the old ones before and have noticed that there are issues regarding fable 1 and 2. 

Considering that a new major release is being worked on, having issues for version 2 and 1 could be meaningless.

I will take the time this week and send more issues that I think need to be closed or need attention.

**Comment by alfonsogarciacaro** [comment]
Finally it was that time of the year again: Issue cleanup! :) I think most of the stale issues are closed now, so we can close this one too :)

**Comment by mabasic** [comment]
@alfonsogarciacaro I got totally swamped at work, that I forgot about this. Great work! 29 issues is very eye pleasing.
