### ISSUE TITLE
Improve error message when fable doesn't implements an API

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2445]
Currently if an API is not supported by Fable the following message is displayed:

```
FABLE: Cannot resolve replacement System.Array.TrueForAll
```

The problem is that this error is not really explaining itself. If that's the first time you see this error I don't think you can understand what it means.

We should change this error message to be more precise/clear.

My proposition would be:

```
System.Array.TrueForAll is not supported by Fable. 

Fable only support a subset of the standard API, if possible try to find a way to not use this API or open an issue on https://github.com/fable-compiler/Fable/ repository to see if we can add support for it.
```

There are a lot to improve in my proposition but what I would like to see in the error are:

1. A clear explantion of what happening the "replacement" terms is internal to Fable I think saying `XXX is not support by Fable` is more direct
2. Explanation on how to solve the problem either not use the API or open an issue to see if we can add support for it in Fable.
3. Optional: We could also mention this documentation page `https://fable.io/docs/dotnet/compatibility.html` and improve it by trying to explaining how we decide to add an API or not.

**Comment by faldor20** [comment]
As the person who brought this up. Yes. This would have been way more helpful. Particularly having an action to take in response to the problem written right into the error.

**Comment by alfonsogarciacaro** [comment]
That makes sense! I added the `WarnOnlyOnce` helper (although currently it's only in the Fable2Babel step) so we can add lengthy warnings without overcrowding the logs. We can probably adapt it.
