### ISSUE TITLE
Can we change NUGET_KEY to FABLE_NUGET_KEY ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2455]
Hello @alfonsogarciacaro,

when releasing new version of the Fable.Browser pacakges I had a problem because I am using my personnal key inside `NUGET_KEY` and even if I an administrator of the Fable nuget org it is not enough to push package where I am (as MangelMaxime) not register as an owser in it.

For example, it is the case for [Fable.Browser.Gamepad](https://www.nuget.org/packages/Fable.Browser.Gamepad)

![image](https://user-images.githubusercontent.com/4760796/119796902-10dd0400-beda-11eb-8d6d-a81cc5c39f7b.png)

I had to regenerate a new NUGET key specifying Fable as the owser of the key:

![image](https://user-images.githubusercontent.com/4760796/119797033-2baf7880-beda-11eb-9ae4-01b51425ebcb.png)

Would you be ok to change the name of the env variable to `FABLE_NUGET_KEY` so we can keep using `NUGET_KEY` for our personnal keys ?

https://github.com/fable-compiler/Fable/blob/aae71ec3e57af680f9d52d6639d0b472c057328b/src/fable-publish-utils/PublishUtils.fs#L565

In order to make the transition easier, we could do something like that:

```fs
let nugetKey =
    match envVarOrNone "FABLE_NUGET_KEY" with
    | Some nugetKey -> nugetKey
    | None -> 
        match envVarOrNone "NUGET_KEY" with
        | Some nugetKey ->
            failwith 
                """
The Nuget API key must be set in a FABLE_NUGET_KEY environmental variable

We recently created a Fable org on NuGet, if you are a member of this organisation you need to generate a new
nuget key specifing Fable as the owner of the key.

We are now using FABLE_NUGET_KEY for the Fable's key so you can keep hosting your personnal key inside NUGET_KEY.

More information can be found at: https://github.com/fable-compiler/Fable/issues/2455
                """
        | None ->
            failwith "The Nuget API key must be set in a FABLE_NUGET_KEY environmental variable"
```

Adding an error message trying to guide the other owner on solving their problem.

**Comment by alfonsogarciacaro** [comment]
You're right, actually I had a similar issue. My only thing is, although these are published as `fable-publish-utils` in principle they can be used to publish any nuget/npm package so I would try not to make them too Fable-specific. Maybe we can pass the key as argument and then be explicit in the fable-browser/build.fsx script:

```fsharp
let pushNuget (projFile: string) props buildAction nugetKey = ...

// In build.fsx
envVar "FABLE_NUGET_KEY"
|> pushNuget projFile [] doNothing

// We can also add an explicit helper to the publish utils with your message
let getFableNugetKey() =
    match envVarOrNone "FABLE_NUGET_KEY" with
    | Some nugetKey -> nugetKey
    | None -> ... // your error message

getFableNugetKey()
|> pushNuget projFile [] doNothing

// And we can also add yet another helper to publish Fable packages explicitly
let pushFableNuget projFile props buildAction =
    getFableNugetKey()
    |> pushNuget projFile props buildAction
```

What do you think?

**Comment by MangelMaxime** [comment]
> My only thing is, although these are published as fable-publish-utils in principle they can be used to publish any nuget/npm package so I would try not to make them too Fable-specific

In principle, indeed but I am not sure if anyone except the Fable org use it. I took a look at the commit and it seems good to me it allows both usage.

----

I will make a pass on the different project still used today under Fable org to update them to use `FABLE_NUGET_KEY`
