### ISSUE TITLE
Trait calls still not working properly

### ISSUE THREAD

**Issue by gusty** [fable-compiler/Fable#2468]
### Description

In Fable 3 lot of code containing complex SRTP trait calls previously not compiling now works without issues, due to F# witness included in the AST feature.

However for some unknown reason, there are still lot of code fragments where Fable is not able to resolve trait calls. Here's one:

### Repro code

```fs
open System
open System.Globalization

type Parse =
    
    static member inline Parse (_: ^R, _: obj  ) = fun (x:string) -> (^R: (static member Parse : _ -> ^R) x)
    static member inline Parse (_: ^R, _: Parse) = fun (x:string) -> (^R: (static member Parse : _ * _ -> ^R) (x, CultureInfo.InvariantCulture))

    static member Parse (_: bool, _: Parse) = fun (x:string) -> Boolean.Parse (x)
    static member Parse (_: char, _: Parse) = fun (x:string) -> Char.Parse (x)

    static member inline Invoke (value: string) =
        let inline call_2 (a: ^a, b: ^b) = ((^a or ^b) : (static member Parse : _*_ -> _) b, a)
        let inline call (a: 'a) = fun (x: 'x) -> call_2 (a, Unchecked.defaultof<'r>) x : 'r
        call Unchecked.defaultof<Parse> value

// test

let h: int = Parse.Invoke "123"
printfn "result is : %i" h
```

### Expected and actual results

Code should compile but it fails with `FABLE: Cannot resolve trait call Parse - Inline call from .(19,13)`.

### Related information

* Fable version: 3.1.15
* Operating system: tried with the online Fable Repl

**Comment by gusty** [comment]
It seems to start working If we add a type parameter at the end of the Invoke method and a function calling it:

```
open System
open System.Globalization

type Parse =
    
    static member inline Parse (_: ^R, _: obj  ) = fun (x:string) -> (^R: (static member Parse : _ -> ^R) x)
    static member inline Parse (_: ^R, _: Parse) = fun (x:string) -> (^R: (static member Parse : _ * _ -> ^R) (x, CultureInfo.InvariantCulture))

    static member Parse (_: bool, _: Parse) = fun (x:string) -> Boolean.Parse (x)
    static member Parse (_: char, _: Parse) = fun (x:string) -> Char.Parse (x)

    static member inline Invoke (value: string) : 'T =    // <-- : 'T added
        let inline call_2 (a: ^a, b: ^b) = ((^a or ^b) : (static member Parse : _*_ -> _) b, a)
        let inline call (a: 'a) = fun (x: 'x) -> call_2 (a, Unchecked.defaultof<'r>) x : 'r
        call Unchecked.defaultof<Parse> value

// added
let inline parse (value: string) :'R = Parse.Invoke value

// test

let h: int = parse "123"
printfn "result is : %i" h
```

So, it seems to me that this issue has to do with propagating output parameters, somehow the Fable compiler requires them to be explicit.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for investigating this @gusty! I've been debugging your samples and it looks the issue was "nested" witnesses need other witnesses to be resolved, a case that Fable wasn't covering. I've tried to fix that and at least your example (the first one) is working now :) I hope it helps with other cases too but please let me know if you find something else that it's still not working 👍

**Comment by gusty** [comment]
Thanks a lot for taking care of this.

I tried updating the sample to test more cases, it seems still there are some issues.

Have a look  https://github.com/fable-compiler/Fable/pull/2470
