### ISSUE TITLE
DefineConstants "DEBUG" and "TRACE" are dropped

### ISSUE THREAD

**Issue by stroborobo** [fable-compiler/Fable#2477]
### Description

Hey lovely Fable people,

(This is kind of a follow up to #2401 and #2402.)

I have a project configuration called "Test" that also defines "DEBUG" and "TRACE". When building with Fable these constants are stripped after the project cracker had found them in the project file.

### Repro code

In the project file:

```xml
<PropertyGroup Condition=" '$(Configuration)' == 'Test' ">
  <DefineConstants>DEBUG</DefineConstants>
</PropertyGroup>
```

```fsharp
printfn "DEBUG %s"
#if DEBUG
    "yes"
#else
    "no"
#endif
```

Build with `--configuration Test`

### Expected and actual results

- Expected (DotNet): prints "DEBUG yes"
- Actual (Fable): prints "DEBUG no"

After some digging I've found a function that explicitly drops `--define:DEBUG` and `--define:TRACE`, 

https://github.com/fable-compiler/Fable/blob/4ecab554/src/Fable.Cli/ProjectCracker.fs#L272

Maybe the outer match is obsolete since the change with the configuration parameter in #2401 / #2402?

### Related information

* Fable 3.2.9
* macOS 11.4

**Comment by alfonsogarciacaro** [comment]
I always keep forgetting about this discussion 😅 but if I remember correctly we remove `--define:DEBUG` because DotnetProj.Info adds it by default, and in Fable we only want `DEBUG` (by default) in watch mode. Maybe the solution is just not to remove `--define:DEBUG` (and TRACE) when the user passes the configuration explicitly?

**Comment by stroborobo** [comment]
The configuration is always set from the ProjectCracker's point of view ([here][pc]), since Fable sets the default configuration if not passed explicitly. So Dotnet.ProjInfo added it because we used to call it without a configuration, which made it (or MSBuild) fall back to Debug, which resulted in the default Debug constants. At least that was my train of thought, perhaps that doesn't happen anymore?

Adding the configuration as a constant manually ([here][cm]) is probably not needed anymore either then, I probably only did that because I missed the filter function.

I'll open a PR if you agree and add a few test projects with different constants per configuration, too.

[pc]: https://github.com/fable-compiler/Fable/blob/0daabeab2/src/Fable.Cli/ProjectCoreCracker.fs#L157
[cm]: https://github.com/fable-compiler/Fable/blob/0daabea/src/Fable.Cli/Entry.fs#L165

**Comment by stroborobo** [comment]
Couldn't stop myself 🙃

I can change it all if you want of course.
