### ISSUE TITLE
Choice with arity 3+

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2485]
### Description

While serializing choice values with arity of more than 2 using Thoth I discovered that these are incorrectly represented.

### Repro code

```fsharp
printfn "%A" (Choice2Of3 55)
printfn "%A" (Choice3Of3 55)
```

### Expected and actual results

Prints

```
Choice2Of2 55
undefined 55
```

I'd either expect it not to compile if not all choice types are supported or print

```
Choice2Of3 55
Choice3Of3 55
```

### Related information

* Fable version: 3.2.9

**Comment by alfonsogarciacaro** [comment]
Oh, my. You discovered we're cheating and just using a single class for all `Choice` arities 😅 I'll see if we can fix this or we need a separate class for each arity, thanks for reporting!

**Comment by alfonsogarciacaro** [comment]
My mistake, we did have multiple [FSharpChoice in the library](https://github.com/fable-compiler/Fable/blob/af8a145fe244434a56c10912218af64966093aee/src/fable-library/Choice.fs#L18-L61) but the way I was referencing them in the code was a bit messy and not correct. Hopefully it's better now :)

**Comment by kerams** [comment]
Thank you.
