### ISSUE TITLE
invite you to try a new series of lex/yacc tools

### ISSUE THREAD

**Issue by xp44mm** [fable-compiler/Fable#2490]
A compiler cannot be written without compiler tools, I am very pleased to invite you to try a new series of lex/yacc tools. It is a very powerful, easy-to-use next-generation series of Lex/Yacc tools.

The open source see to:  [xp44mm/FSharpCompiler](https://github.com/xp44mm/FSharpCompiler)

The usage of `FSharpCompiler.Lex` and `FSharpCompiler.Analyzing`, see the resolution: [xp44mm/PolynomialExpressions](https://github.com/xp44mm/PolynomialExpressions)

The usage of `FSharpCompiler.Yacc` and `FSharpCompiler.Parsing`, see the resolution: [xp44mm/ArithmeticExpressions](https://github.com/xp44mm/ArithmeticExpressions)

I'd also like to help make some contributions to this project when you need to split some small tasks from a big task.

**Comment by alfonsogarciacaro** [comment]
Thank you very @xp44mm. Fable just gets the F# AST directly from the F# so fortunately we don't need to do any F# code parsing by ourselves :)

**Comment by xp44mm** [comment]
You can sometimes use lex/yacc to pre-process the source code before you pass it into the F#compiler, which can improve performance or avoid some conflicts.

**Comment by alfonsogarciacaro** [comment]
F# compiler already uses lex/yacc for parsing. I'm not sure which use-cases would improve performance or what conflicts could be avoided by preprocessing the files before sending them to the F# compiler, do you have something in mind?

**Comment by xp44mm** [comment]
Because I haven't delved into it, I can't give specific use cases, but in general, to improve performance and avoid conflicts should note that normalized separators, nullable symbols or groups, syntax sugars, etc

If you try to use `FSharpCompiler` library, you'll find that it can be helpful at handling some strings just like Regex or other string operators.

**Comment by alfonsogarciacaro** [comment]
Most of these things are being done by the F# compiler, it's out of the scope of Fable to provide analysis of F# code, although it could be interesting for other projects. But just a question, why is your project called `FSharpCompiler`? if I understand it correctly it's not about compiling F# code but generating a parser (in F#) from .lex and .yacc files. Is not the name somewhat misleading?

**Comment by xp44mm** [comment]
> it's not about compiling F# code but generating a parser (in F#) from .lex and .yacc files. Is not the name somewhat misleading?

yes! It's a generic parser written in F# language.

name is the first version of the beginning of the projects, more proper name did not come up with, name is difficult things.

**Comment by xp44mm** [comment]
@alfonsogarciacaro Do you read `.fsl` and `.fsy` files?

`lex-highlight` is a syntax highlighter written according to the lexical analyzer. So it can correctly analyze all kinds of tokens. and It supports advanced features such as string interpolation and language nesting.

the open source of `lex-highlight` is [here](https://github.com/xp44mm/lex-highlight)

A demo is [here](https://github.com/xp44mm/colorful-language), to highlight .fsl or .fsy files, you can open the `/dist/index.html` file with a browser.

**Comment by MangelMaxime** [comment]
Hello @xp44mm ,

I don't think we read thus file. Fable only works with `.fs`, `.fsx` and `.fsi` files. In fact, it doesn't read them directly it is the F# compiler service which read the project files and return the typed AST that Fable used to transform into JavaScript

**Comment by xp44mm** [comment]
This package is legacy and is no longer maintained. Replace this package with the FslexFsyacc package, which implements all the features of this package and is more friendly.

**Comment by alfonsogarciacaro** [comment]
Thanks again for the suggestion @xp44mm! I'm closing this for now because, as discussed above, the code parsing is already done by FSharp.Compiler.Services so Fable doesn't need to do it. But we'll keep this in mind if writing our own full-compiler :)
