### ISSUE TITLE
Calls to custom Pow operator use Math.pow instead

### ISSUE THREAD

**Issue by baioc** [fable-compiler/Fable#2496]
### Description

If a type implements a custom `Pow` operator, using `( ** )` should call that static member.
However, Fable generates calls to `Math.pow` instead, which only works for built-in JS numeric types.

### Repro code

Minimal example: [REPL](https://fable.io/repl/#?code=C4TwDgpgBAwgrgZ2AewLYAVkHcoF4BQURUA3lAPIDWAXFAEbLIA2UAvocVgJbAAWHxYkgCGwLgGMoqCKjoQATlExYAFAA9a8JGmUAaKADtaXA8ACUeUhUqXg8uNHb4mEYFDWWyVSwDNhTBEdnVygQSw8AKgioACZ8AGUQJBkAOhhkAwRmCBSAdXkeCAAZE2gQFKp8IA&html=Q&css=Q)
The following doesn't print anything:
```f#
type CustomPow =
    { Ok: bool }
    with
        static member Pow(x: CustomPow, n: int) = { Ok = true }

let x = { Ok = false }
let y = x ** 2
System.Console.WriteLine y.Ok // should print true
```

Supposedly, that is because the generated JS looks like:
```js
export function CustomPow_Pow_Z545D00C6(x_1, n) {
    return new CustomPow(true);
}

export const x = new CustomPow(false);
export const y = Math.pow(x, 2);
console.log(y.Ok);
```
(notice the code for the custom operator is generated, just never called)

### Expected and actual results

Expected: Fable should generate calls to the actual custom `Pow` operator.
Actual: Using `**` typechecks, but fails at runtime because generated code wrongly calls `Math.pow`.

### Related information

* Fable version: 3.2.1, as well as the version in the online REPL.
* Operating system: Linux, Web.

**Comment by baioc** [comment]
Apologies in case someone received an email with an incomplete description of this issue, I accidentally sent it while still editing.

**Comment by alfonsogarciacaro** [comment]
No problem, thanks for reporting @baioc! Will be fixed in next release :+1:
