### ISSUE TITLE
.net 5 -> String interpolation error compile

### ISSUE THREAD

**Issue by KaBaJIeP** [fable-compiler/Fable#2502]
doesn't work with fable-compiler but works with dotnet compiler.

```
let getUrl url = $"/{url}"
```

```
F# <TargetFramework>net5.0</TargetFramework>
```
```
(27,28) error FSHARP: This token is reserved for future use (code 1160)
```
```
fable-compiler 2.13.0
```

works 
```
let getUrl url = sprintf "/%s" url
```

<img width="274" alt="Screenshot 2021-07-31 at 22 55 19" src="https://user-images.githubusercontent.com/5019401/127757603-42519820-d118-4983-a037-5dc80f682860.png">

dotnet fable --version
Fable: F# to JS compiler 3.2.9
Thanks to the contributor! @2sComplement
3.2.9

MacOS Big Sur v 11.4

**Comment by MangelMaxime** [comment]
Hello @KaBaJIeP,

What version of Fable are using ?

Because you are referring to `fable-compiler` and `dotnet fable` in this issue.

If you made the move to Fable 3, you should not use `fable-compiler` anymore.

.NET 5 feature are supported only on Fable 3 if I recall correctly.

**Comment by KaBaJIeP** [comment]
Thanks, got it.

```
dotnet fable --optimize 
```
works too.

I've used dependencies from

https://github.com/fable-compiler/webpack-config-template

to get the production-ready package.

**Comment by alfonsogarciacaro** [comment]
Ups, the webpack-config-template wasn't updated yet, sorry. I've changed it remove the fable-loader (not necessary with Fable 3) and and also babel-loader (as most browsers already support the code generated by Fable).

Hmm, in principle you shouldn't need to use the `--optimize` option, it's kind-of experimental and can cause other problems in your code. `let getUrl url = $"/{url}"` works in the REPL, would it be possible to create a minimal project that reproduces this error? Also, please make sure you're using latest FSharp.Core just in case.

**Comment by KaBaJIeP** [comment]
Thanks, everything is fine now. 
I've found a way how to combine and build everything in docker.
