### ISSUE TITLE
Fable fails to bundle/compile NPM dependencies using optional-chaining syntax (?.)

### ISSUE THREAD

**Issue by darranhayes** [fable-compiler/Fable#2510]
### Description

Trying to use npm dependencies: <https://github.com/mozilla/pdfjs-dist> via <https://github.com/agentcooper/react-pdf-highlighter> and encountered compilations errors with Fable.

### Repro code
[Github: darranhayes/fable-npm-compilation-issue](https://github.com/darranhayes/fable-npm-compilation-issue)

1. dotnet new fable
2. dotnet tool restore
3. npm install pdfjs-dist
4. App.fs, take any dependency from the pdfjs-dist module, e.g.,
Add code
```
open Fable.Core.JsInterop
let globalWorkerOptions: obj = importMember "pdfjs-dist/lib/pdf"
```
5. npm run start
6. Observe multiple compilation errors, failing to handle npm dependencies due to not supporting optional-chaining syntax "?." <https://babeljs.io/docs/en/babel-plugin-proposal-optional-chaining>

### Expected and actual results
```
ERROR in ./node_modules/pdfjs-dist/lib/display/annotation_layer.js 366:34
Module parse failed: Unexpected token (366:34)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|
|       link[jsName] = () => {
>         this.linkService.eventBus?.dispatch("dispatcheventinsandbox", {
|           source: this,
|           detail: {
 @ ./node_modules/pdfjs-dist/lib/pdf.js 244:24-64
 @ ./src/App.fs.js
```

### Related information
- Fable: F# to JS compiler 3.2.9
- Node v14.15.1
- Windows 10

### Remarks
I can work around the problem locally by adding a babel preset-env loader in webpack.config for supporting optional-chaining, but I think this limits the ease of building a consumable Fable wrapper around react-pdf-highlighter that I would like to publish.

**Comment by MangelMaxime** [comment]
Hello @darranhayes ,

The error you are seeing is coming from Webpack and not Fable.

You can try using Webpack 5 and see if they added native support for this syntax in it. Or you will indeed need to use babel to support this syntax when bundling your JavaScript.

**Comment by darranhayes** [comment]
Thanks @MangelMaxime, I mistakenly though Babel was still part of the process.
