### ISSUE TITLE
Implement Uri.OriginalString

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2520]
### Description

We need to add a replacement for OriginalString.

### Repro code

```fsharp
System.Uri("http://example.org").OriginalString = "http://example.org" // should evaluate to true
```

### Expected and actual results

Above code should succeed and evaluate to true, and does under .NET. Under fable we get:

```
error FABLE: Cannot resolve replacement System.Uri.get_OriginalString
```

### Related information

* Fable version: 3.0.5
* Operating system

**Comment by njlr** [comment]
I had a go at this: https://github.com/fable-compiler/Fable/pull/2534
