### ISSUE TITLE
Outdir breaks imports if extension is not set

### ISSUE THREAD

**Issue by thehabbos007** [fable-compiler/Fable#2522]
### Description

When compiling a project with `--outDir` option set, the resulting compiled code has a different extension than the default extension set in the compiler.
The presence of a outDir overwrites the file extension that might be incorrect.

### Repro code

```F#
// Library.fs
module Library
let hello name = printfn "Hello %s" name
```

```F#
// OtherFile.fs
module OtherFile
open Library
hello "hello"
```
Compiled in a F# project to js with `fable -o .fable`

### Expected and actual results

Expected
The files in the .fable folder should have the default filename extension `.fs.js` (from the fable help command)
 `Library.fs.js  OtherFile.fs.js`
Likewise the imports from `OtherFile.fs` should contain the line 
```js
import { hello } from "./Library.fs.js";
```

Actual
Files in the `.fable` directory have the extension `.js`: `Library.js  OtherFile.js`
`OtherFile.js` incorrectly contains the line 
```js
import { hello } from "./Library.fs.js";
```
with the wrong extension `.fs.js` instead of `.js` as the filenames imply.

---
Seems that this is set in 
https://github.com/fable-compiler/Fable/blob/7d05051b24a92945c2cd6b7e47604f405188e18b/src/Fable.Cli/Entry.fs#L90

### Related information

* Fable version: `dotnet fable --version` = 3.2.12
* Operating system: WSL2 Ubuntu with kernel 4.19.104 on Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @thehabbos007! Does this happen only when you try to output to `.fable` folder? Actually, this is kind of a reserved directory and trying to output files to it will indeed likely break things. We can add a check and throw error if you pass `-o .fable` if necessary.

**Comment by thehabbos007** [comment]
You're right, it only happens when outputting to `.fable` . I was under the impression that was not a special location, my bad!
What would be the conventional place to put the output? :)

Adding a check might be nice, especially if other things could break as well with that directory as outdir.

**Comment by MangelMaxime** [comment]
Hello @thehabbos007 personally depending on the usage I have 2 possibles locations:

- `dist`: If the generated files are consumed directly for example in an npm packages without bundler
- `fableBuild`: If the generated files are consumed via a bundler like webpack, rollup, etc.
