### ISSUE TITLE
Should we support infinit arguments for curry/uncurry?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2525]
Hello,

When using Fable.Form, someone reported an error about having an error if they go more than 8 fields.

https://github.com/MangelMaxime/Fable.Form/issues/22

Their issue has a workaround by rewrite the code a bit, but it is never fun to see this kind of "cryptic" errors.

It seems like it should be possible to support any number of arguments for curry/uncurry.

Should we try to do it?

https://javascript.info/currying-partials

**Comment by alfonsogarciacaro** [comment]
I've sent a PR to fix this. Seems to be working although I'm not sure if it can have any impact on performance. Should we benchmark it first before merging? Also, we should probably add tests, it'd be nice to use the code reported in Fable.Form, though that would imply adding several dependencies to the test project 🤔

**Comment by MangelMaxime** [comment]
> Seems to be working although I'm not sure if it can have any impact on performance.

I have the same interrogation ^^

> Also, we should probably add tests, it'd be nice to use the code reported in Fable.Form, though that would imply adding several dependencies to the test project thinking

Adding Fable.Form can be tricky because as you said, it is split in 3 different packages.

I manage to write a code in the REPL which looks similar to Fable.Form and generate curried function.

Also the code should be testable because we can just test the generated tuple. We should probably test arity 1, 2, 8 and 10 for example. 

```fs
let addString (value : string) (f : string -> 'T) =
    f value

let addBool (value : bool) (f : bool -> 'T) =
    f value


let res =

    let onSubmit =
        fun (arg1 : string)
            (arg2 : string)
            (arg3 : bool)
            (arg4 : string)
            (arg5 : string)
            (arg6 : string)
            (arg7 : string)
            (arg8 : string)
            (arg9 : string) ->

            (arg1, arg2, arg3)

    onSubmit 
        |> addString "name"
        |> addString "password"
        |> addBool true
        |> addString "dummmyValue"
        |> addString "dummmyValue"
        |> addString "dummmyValue"
        |> addString "dummmyValue"
        |> addString "dummmyValue"
        |> addString "dummmyValue"

printfn "%A" res
```

[REPL live](https://fable.io/repl/#?code=DYUwLgBAhgJjDKYBOBLAdgcwgCgG5WAFcQIAuCAZ2XQwEocAzMy6zCAWgD4IByAFXoBeAFAQxEJviIhhw0JFgwAQgHsVwHFOLMARmuD1sTcnvUdu-IaPGSCxWXPAQkIChBHWx8iCrTxCOgC2KJAi4uEShGg4UEgYAIzMVKiYtJ4R4dixGABMSax06RliWXEAzLr6acURpRgALPkphTWZ2QCsTTTVrSXZAGxdqUXFdQDsQy29MXEAHJM9vXUAnAvmstMzCQA00HE5u9llaem+-kEhECNiAD7ciojNEABEaFCBIM-XEHfQcI80F4ABygFAoAHcVEgYF8ar9FKozMh7HD7v8Ci8YIRAjiAJ4ANTsn2+8PRT2eWJxgQJRNhxVJCAxFOxeMJ0jpGQZALYzKpNPZJLRjPJlNZtMFf2FgN5YoFwiBKTADGizwApABBZ7OVxAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohkqCl26mAIhSkKUjwodFxI2t5YOMBojJh0aD5IUBB0uiDkfqQR1jEMVkpOLvCIKpCwcEA&css=Q)

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Not sure if this is me, but I think you forget to add tests for this feature?

Am I right? Do you want me to send a PR?

**Comment by alfonsogarciacaro** [comment]
Ups, you're right! Didn't remember tests were pending 😅 Yes, please it'd be great if you could send a PR.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Ok, I will do it today.
