### ISSUE TITLE
Fable AST type info for Rust

### ISSUE THREAD

**Issue by alexswan10k** [fable-compiler/Fable#2541]
### Description

Whilst working on the rust implementation, we uncovered a couple of possible areas in the Fable.AST, where info about types was not available. These are the examples:

* When trying to extract and transpose the generic parameters of a function, there seems to be no representation of the actual raw generic parameters. The workaround done here is to walk the types of each parameter and look for type Generic, which is sub-par.
https://github.com/alexswan10k/Fable/blob/fc428aca12312ca39b749f07126f37ab70ab041c/src/Fable.Transforms/Rust/Fable2Rust.fs#L2308

* Imports seem to not contain type information (the type field contains Any). In Rust, the import presumably will have to defererence all the submodules defined in the file to get to the intended symbol.
https://github.com/alexswan10k/Fable/blob/fc428aca12312ca39b749f07126f37ab70ab041c/src/Fable.Transforms/Rust/Fable2Rust.fs#L2651

Any ideas on how we can get around these things @alfonsogarciacaro?

Thanks in advance!

### Related information

* Fable version: next

**Comment by ncave** [comment]
@alexswan10k
Yes, looks like the generic params of a function are extracted [from the parameters](https://github.com/alexswan10k/Fable/blob/fc428aca12312ca39b749f07126f37ab70ab041c/src/Fable.Transforms/Rust/Fable2Rust.fs#L2276).
For entities, [from the entity itself](https://github.com/alexswan10k/Fable/blob/fc428aca12312ca39b749f07126f37ab70ab041c/src/Fable.Transforms/Rust/Fable2Rust.fs#L388-L391).

**Comment by alexswan10k** [comment]
Happy to go with the typescript solution if that gets the result. I will have another look next time I am in that area, thanks.

**Comment by alexswan10k** [comment]
I am going to close this as I think we have a way forward. Now using the parameter approach recursively.

**Comment by alfonsogarciacaro** [comment]
Sorry for replying late, many things happening now in Fable world 😅 Yes, the generic parameters should be accessible from the entity or function signature and then matched with the concrete generic arguments by index. About the import, using `Any` was a quick hack to import members from other F# files. We can build the proper type of the imported function (PHP also needs this I think). But I was also thinking for Fable 4 we could leave imports only for user explicit imports (that is, calls to a external language) and for the calls just leave the member reference (we basically have it already in `CallMemberInfo`) more or less as in the F# AST itself, and the actual import/reference can be resolved at the last stage of the compilation. Would that work for you?

**Comment by ncave** [comment]
@alfonsogarciacaro 
> then matched with the concrete generic arguments by index

I'm not sure I get that part, what index?

> using Any was a quick hack to import members from other F# files

Do yo mean `fable-library`, or some other code?

**Comment by ncave** [comment]
@alfonsogarciacaro 
> generic parameters from the entity ... match with the genArgs list

Yes, entity genArgs are in the AST, I believe @alexswan10k 's point was about not having functions actual genArgs in AST (I haven't looked if they're in the F# AST either).

**Comment by alexswan10k** [comment]
@alfonsogarciacaro not to worry we know you are busy! Imports containing the Any was my issue yes, and having the types there would definitely help us I think.

As for the generic args, yes they do not seem to be in the AST. As @ncave  pointed out we do have a workaround for the time being though. I have no idea how this will perform when we start to have to deal with type constraints though, but we will cross that bridge when we come to it.

Is there anything actionable you want me to reopen and leave this issue to handle by the way?
