### ISSUE TITLE
Emit on DU case not respected

### ISSUE THREAD

**Issue by Happypig375** [fable-compiler/Fable#2543]
### Description

Please provide a succinct description of your issue.

### Repro code

```fs
type [<Fable.Core.Erase>] MarkerDescriptor =
| [<Fable.Core.Emit "{type:'time',timeMinutes:$0}">] Time of timeMinutes: int
| [<Fable.Core.Emit "{type:'session'}">] Session
| [<Fable.Core.Emit "{type:'permanent'}">] Permanent

let a = Time 4
let b = Session
let c = Permanent
```

### Expected and actual results

Expected
```js
export const a = {type:'time',timeMinutes:4};

export const b = {type:'session'};

export const c = {type:'permanent'};
```
Actual
```js
export const a = 4;

export const b = "session";

export const c = "permanent";
```

### Related information

* Fable version: `dotnet fable --version` 3.2.11
* Operating system: Fable REPL, Mac

**Comment by alfonsogarciacaro** [comment]
Yes, it's true `Emit` doesn't work on DU cases. We could try to make it work although this may bring other issues/inconsistencies (Emit doesn't work for record fields either, should we support it?).

If you don't mind qualifying the "constructors", what you're trying to do is already possible with a bit more of code:

```fsharp
[<Erase>]
type MarkerDescriptor =
    [<Emit "{type:'time',timeMinutes:$0}">]
    static member Time(timeMinutes: int): MarkerDescriptor = jsNative
    [<Emit "{type:'session'}">]
    static member Session: MarkerDescriptor = jsNative
    [<Emit "{type:'permanent'}">]
    static member Permanent: MarkerDescriptor = jsNative

let a = MarkerDescriptor.Time 4
let b = MarkerDescriptor.Session
let c = MarkerDescriptor.Permanent
```

**Comment by MangelMaxime** [comment]
IHMO, we should keep `Emit` as it is.

In the past, we decided to not go the `Emit` root for record fields because people could abuse it for "bad reason".

```fs
type MyRecord =
    {
        [<Emit("propertyA")>]
        PropertyA : sting
    }
```

This would also increase the complexity of both Fable reflection and serializers code in order to support emit en properties, Enums, etc.

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime is definitely right. It also came to my mind that we'd have the issue of pattern matching with such unions as in the example above.

**Comment by Happypig375** [comment]
Alright then
