### ISSUE TITLE
Error assigning to rvalue: (void 0) = (void 0)

### ISSUE THREAD

**Issue by pkese** [fable-compiler/Fable#2548]
### Description

Fable renders wrong JavaScript code for mutable assignment when generic type gets resolved as `unit`.

### Repro code

This code is a minimal reproducible simplification of what some code in FSharp.Data.Adaptive does (as described in #2539).

```fsharp
let inline f (x:'A) = Unchecked.defaultof<'A> |> ignore
//let inline f x = 42 |> ignore
//let inline f x = 42
//let inline f x = ()

let inline doit x (f: 'A -> 'T) =
    let mutable r = Unchecked.defaultof<_>
    r <- f x   
    r

printfn "%A" (doit 1 f)
```

### Expected and actual results

On dotnet version of F#, the above code prints `()`.

Fable however compiles it into the non-compliant JavaScript
```js
(function () {
    let arg10;
    let r = null;
    (void 0) = (void 0); // <-- Module parse failed: Assigning to rvalue
    arg10 = (void 0);
    toConsole(printf("%A"))();
})();
```

### Related information

* Fable version: 3.3.0
* Operating system: Linux

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report and sorry for replying so late @pkese. Fable sometimes replaces values of unit type with the unit constant (don't remember exactly the reason) but in this case it generates wrong JS. I've added a check so in this situation we remove the assignment and keep only the expression for the side effect 👍

**Comment by pkese** [comment]
Gee, thanks. 🙏
