### ISSUE TITLE
DateTimeOffset.Parse test is incorrect for some locales

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#2587]
DateTimeOffset.Parse JavaScript test fails on locales that have not switched to winter time yet:
```
DateTimeOffset.Parse doesn't confuse day and offset:

      Error: Expected: 2047 - Actual: 2046
```

I'm not sure much can be done, I assume this only happens in the small window where some locales have switched and others have not, so the problem will fix itself in a few days, and will go away permanently when summer time goes away ;)

Feel free to close.

**Comment by alfonsogarciacaro** [comment]
Oh, that's a bummer. I do want to make Fable easier to contribute so it's preferable that tests don't fail in some machines because time zones issues. Maybe we can "relax" this test (e.g. allow `2046` too). Would it be possible send a PR to change the test in a way it works on your machine? Thanks!

**Comment by ncave** [comment]
@alfonsogarciacaro My point was, the test doesn't work at the moment, but it will start working next week, I'm pretty sure :)

**Comment by ncave** [comment]
@alfonsogarciacaro I stand corrected, it's not a summer time issue and it's not going to fix itself.
I fixed it, but it took me quite a while to figure out what's happening :(
