### ISSUE TITLE
Fable .NET tests are dependent on the system locale

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2597]
### Description

I'm seeing 8 tests that are failing in Expecto when running them locally. For instance:

```
[15:11:04 ERR] All/DateTime/Parsing doesn't succeed for invalid dates failed in 00:00:00.0040000.
. Actual value was true but had expected it to be false.
[15:11:04 ERR] All/Types/Mangled interfaces work with object expressions failed in 00:00:00.0060000.
.
          Expected string to equal:
          "Zar77.40rfalsefalsedbca"
                ↑
          The string differs at index 5.
          "Zar77,40rfalsefalsedbca"
                ↑
          String does not match at position 5. Expected char: '.', but got ','.
```

They are caused by the following:

```fsharp
let r, _date = DateTime.TryParse invalidAmericanDate
// ...
bar.DoSomething(multiplyTwice, 3.).ToString("F2")
```

The solution is to call the methods with a hard-coded `CultureInfo` outside of the JS tests.

**Comment by alfonsogarciacaro** [comment]
We added (dummy) support for `InvariantCulture` for cases like this, so we could add CultureInfo in the tests and avoid problems in .NET. I think we did it for parsing numbers and I'm not sure if DateTime.Parse accepts CultureInfo yet, but it would a solution for these cases too.

https://github.com/fable-compiler/Fable/blob/f13f582f4ed7ae273cc0106c490071ead068825c/src/Fable.Transforms/Replacements.fs#L2773-L2781
