### ISSUE TITLE
Cannot build to output directory named 'obj'

### ISSUE THREAD

**Issue by NickDarvey** [fable-compiler/Fable#2602]
### Description

This is a low priority issue, though it did trip me up for a little while!

Building with an output directory of 'obj':
```
dotnet fable MyFableApp --outDir obj
```
leads to a referenced package not being available:
```
The value, constructor, namespace or type 'NamespaceInReferencedPackage' is not defined
```

### Repro code

https://github.com/NickDarvey/fable-outdir-package

### Expected and actual results

<details>
❯ dotnet fable Optml.Html.Fable.Tests --outDir obj/tests  
Fable: F# to JS compiler 3.2.9
Optml.Html.Fable.Tests> cmd /C dotnet restore Optml.Html.Fable.Tests.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
Parsing Optml.Html.Fable.Tests\Optml.Html.Fable.Tests.fsproj...
Initializing F# compiler...
Compiling Optml.Html.Fable.Tests\Optml.Html.Fable.Tests.fsproj...
F# compilation finished in 2093ms
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(3,22): (3,27) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(4,22): (4,27) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(5,23): (5,28) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(13,44): (13,49) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(14,36): (14,41) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(15,37): (15,42) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(16,48): (16,53) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(17,71): (17,76) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(19,11): (19,16) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(20,5): (20,17) error FSHARP: Lookup on object of indeterminate type based on information prior to this program point. A type annotation may be needed prior to this program point to constrain the type of the object. This may allow the lookup to be resolved. (code 72)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(21,36): (21,41) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Testing.Fable.fs(23,25): (23,30) error FSHARP: The value, constructor, namespace or type 'Mocha' is not defined. (code 39)
C:/repos/fable-outdir-package/Optml.Html.Tests/Example.fs(6,3): (6,11) error FSHARP: This value is not a function and cannot be applied. (code 3)
C:/repos/fable-outdir-package/Optml.Html.Tests/Program.fs(6,13): (6,21) error FSHARP: This value is not a function and cannot be applied. (code 3)
Compilation failed
</details>

### Related information

* Fable version: 3.2.12
* Operating system:
  Edition	Windows 11 Pro
  Version	21H2
  Installed on	‎2021-‎10-‎23
  OS build	22000.318
  Serial number	029325794157
  Experience	Windows Feature Experience Pack 1000.22000.318.0

**Comment by alfonsogarciacaro** [comment]
Hmm, `obj` and `bin` are special directories used by .NET, I wouldn't recommend using them as output directories. In any case, maybe we can add them [as forbidden outDirs](https://github.com/fable-compiler/Fable/blob/78268be34d9534d01039208691ef4347c64c15ff/src/Fable.Cli/Entry.fs#L184-L185). (It's true that we could detect if there's an .fsproj in the parent dir, but I'd rather keep it simple and just ask devs to use an alternative name.)

**Comment by NickDarvey** [comment]
If it means anything, the outDir is outside of the project directory (i.e. it is the sibling of the solution, not the project) and 'bin' works.
