### ISSUE TITLE
Char addition is implemented as string concatenation

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2614]
### Description

Adding two chars together is supposed to give one char as a result whose value is the addition of the numeric values of the two inputs.

### Repro code

Take the following code:
```fsharp
for i in 0..25 do
    printfn "%c" i ('A' + char i)
```

### Expected and actual results

CLR F# will the characters A-Z.

Fable mostly prints garbage:

```
A
A
A
A
A
A
A
A
A
A	
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
A
```

A workaround is to explicitly do the math as ints, then convert to char afterward:

```fsharp
for i in 0..25 do
    printfn "%i -> %c" i (char (int 'A' + i))
```

The compiled JS appears to be performing string concatenation instead of char addition:

```javascript
import { printf, toConsole } from "fable-library/String.js";

for (let i = 0; i <= 25; i++) {
    const arg10 = "A" + String.fromCharCode(i);
    toConsole(printf("%c"))(arg10);
}
```

### Related information

* Fable version: 3.4.7
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
I've added automatic conversions so char addition works as expected in .NET. However, please note the operation won't be very performance won't be very good as it's necessary to convert back and forth between number and string because Fable represents chars as strings of length 1 in runtime.

**Comment by jwosty** [comment]
Interesting, and thanks for the fix.

Any reason that chars are represented as JS strings instead of numbers? Mostly for displaying them to "just work" most of the time, I assume (i.e. printing to console, etc)?

**Comment by alfonsogarciacaro** [comment]
If I remember correctly, originally it was because enumerating a string in JS gives you 1-length strings, and it was difficult to make the conversion to uint16 in generic code dealing with enumerables. Although now we're indeed transforming the string when iterating to solve some other issues, I believe.
