### ISSUE TITLE
New APIs in FSharp.Core 6

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#2626]
- [x] List/Array/Seq.insertAt
- [x] List/Array/Seq.removeAt
- [x] List/Array/Seq.updateAt
- [x] List/Array/Seq.insertManyAt
- [x] List/Array/Seq.removeManyAt
- [x] Tests 

👇 Original issue below 

### Description

Following up on https://github.com/fable-compiler/Fable/issues/2607#issuecomment-979962354
[List.removeAt](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-collections-listmodule.html#removeAt) is currently not supported.

### Repro code

https://fable.io/repl/#?code=DISwzgLgdATgpgWwPYDc4EEIAIAMWDauWAukA&html=Q&css=Q

### Expected and actual results

Same behavior as in `dotnet fsi`:

### Related information

* Fable version: `dotnet fable --version`: 3.6.0
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Thanks @nojaf! I've updated the issue to track the other new APIs in F# 6 (I hope I'm not missing any). I've sent PR #2629 to implement insertAt/removeAt/updateAt. It'd be great if someone could help with insertManyAt/removeManyAt and the tests (including corner cases like inserting at the end of the list, empty collections, etc).

**Comment by nojaf** [comment]
Hi @alfonsogarciacaro, thank you for the follow-up here.
I might take a stab at the remaining work someday when I find some time.

**Comment by alfonsogarciacaro** [comment]
At the end I stole the tests from the F# repo : The PR should be go to go.
