### ISSUE TITLE
Fable 2 Java (Feature request / idea)

### ISSUE THREAD

**Issue by jkone27** [fable-compiler/Fable#2627]
### Fable2Java

A Java transpiler **allowing F# code to run on JVM**.

I admit i have very little knowledge of the topic or if this discussion already started in the past, i tried to search and didnt find, so i thought of writing this anyway.

The main idea would be to be able to write F# code and have it outputed as valid java code (or anything else runnable on jvm maybe?)

### some similar "ideas" (?)

http://www.fssnip.net/l3/title/Simple-F-Expression-to-Java-compiler

https://github.com/ponsonio/fjord

#### typescript and java

https://wizawu.github.io/tyrian/

#### nodejs and java

https://github.com/apigee/trireme

there are projects transpiling java to js (j2cl, jsweet) but i ma not aware of the other way around.. JS -> Java..

**Comment by smoothdeveloper** [comment]
Was wondering if we had one for C# already? it may sound stupid, but extremely useful in places where F# is "¡No pasarán!"

**Comment by ncave** [comment]
@smoothdeveloper Technically for any .NET language including F# you can decompile the .NET assembly to C# using any IL decompiler like [dnSpy](https://github.com/dnSpy/dnSpy) or [ILSpy](https://github.com/icsharpcode/ILSpy).
I'm not sure if it's easier to maintain the C# code this way rather than referencing the F# assembly directly.

**Comment by delneg** [comment]
Doesn't F# already run on JVM in Xamarin ?

**Comment by jkone27** [comment]
@smoothdeveloper couldnt' find any valid C# to java or jvm valid projects or transpiler, @delneg i think Xamarin uses Mono, which is a .NET compiler not jvm or java.

**Comment by inosik** [comment]
@delneg No, Mono runs on top of the OS. This diagram from [the official docs](https://docs.microsoft.com/en-us/xamarin/get-started/what-is-xamarin#how-xamarin-works) shows the architecture:

![grafik](https://user-images.githubusercontent.com/11393003/144250493-dab2c6a9-42e5-48a3-8e7e-b6c698a5a163.png)

**Comment by alfonsogarciacaro** [comment]
Thanks for the suggestion @jkone27! For now, let's close this. There's currently work in `beyond` branch to make Fable 4 target other languages, but there's no strict guideline about which languages to choose, each depends on the expertise and personal motivations of the team members. I personally have very little experience with the JVM so I don't think I could undertake this. But of course if anyone is up to the task they're more than welcome :)
