### ISSUE TITLE
After Plugin Transform: Function expression compiled as tupled when usage is compiled as curried.

### ISSUE THREAD

**Issue by stroborobo** [fable-compiler/Fable#2628]
### Description

When using ReactComponentAttribute from Feliz I noticed multiple argument functions are not compiled correctly, making our app crash. Nothing changed in Feliz as far as I know and moving from Type Any to the known types in the transformed AST didn't change anything either, so I thought the issue might be in Fable.

Caller:
- Fable 3.2.14 and below: `fn: (a) => ((b) => fn(a, b))`
- Fable 3.3.0 and above: `fn: (a, b) => fn(a, b)`

In the component: `myComponentInputProps.fn(1)(2);`

### Repro code

https://github.com/stroborobo/feliz-reactcomponent-drops-function-type

### Expected and actual results

Expected: function signatures are consistent in caller/callee

Actual: Caller passes function in tupled form, callee uses it like curried form

### Related information

* Fable version: 3.3.0 and newer
* Operating system: macOS

**Comment by stroborobo** [comment]
I believe it's this commit: [Uncurry functions passed to an object expression](https://github.com/fable-compiler/Fable/commit/e4dcd8642367cb39b74f72c7b7b32c4a59ac3be2) from issue #2436.

If I comment out the ObjectExpr transformation there, it works again.

**Comment by stroborobo** [comment]
With this change it seems to work and also for the existing tests:

```diff
 --- src/Fable.Transforms/FableTransforms.fs
 +++ src/Fable.Transforms/FableTransforms.fs
 @@ -589,7 +589,8 @@ module private Transforms =
                  | _ -> Map.empty
              let members =
                  members |> List.map (fun m ->
 -                    if m.Info.IsGetter || m.Info.IsValue then
 +                    let hasGenerics = m.Body.Type.Generics |> List.isEmpty |> not
 +                    if m.Info.IsGetter || (m.Info.IsValue && not hasGenerics) then
                          let membType =
                              Map.tryFind m.Name membersMap
```

Inspired by [this comment](https://github.com/fable-compiler/Fable/blob/44b38de/src/Fable.Transforms/FSharp2Fable.Util.fs#L505), no idea if it's really the right thing to do though.

**Comment by alfonsogarciacaro** [comment]
Wow, thanks a lot for investigating this so thoroughly and even including the fix! 👏 👏 👏 I've added it together with a test based in you repro and seems to work, so it will be in the next release. Thanks again!
