### ISSUE TITLE
Literal CRLF sequence in regex emits invalid JS

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#2635]
### Description and repro

Creating a regex with a character return sequence like so:

```fsharp
let someRegex = Regex("\r\\n|\\n|\"|\\\\")
```

Emits the following broken JS:

```javascript
const SExpr_fs_AtomModule_escRegex = /
\n|\n|"|\\/g;
```

Same thing happens if you use `\013` instead of `\r`.

### Expected and actual results

The CR (\r) character should be escaped before inserting into the source file. I would expect to see this output:

```javascript
const SExpr_fs_AtomModule_escRegex = /\r\n|\n|"|\\/g;
```

### Workaround

Dynamically build the string: 

```fsharp
Regex (string (char 13) + "\\n|\\n|\"|\\\\")
```

### Related information

* Fable version: 3.4.7
* Operating system: Windows 10.0.19043

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! This will be fixed in the next version. BTW, you can workaround this by using `@` in front of the string. This is what I always do with regex (so I don't need to double the backslashes) and it's likely the reason I didn't notice the problem myself 😆 

```fsharp
// When using @ we've to double the quotes to escape them
let someRegex = Regex(@"\r\n|\n|""|\\")
```

**Comment by jwosty** [comment]
Interesting. I will admit I didn't know about `@` string literals.

Thanks for fixing it!
