### ISSUE TITLE
Piping to an alias of a function which returns a function produces incorrect JavaScript

### ISSUE THREAD

**Issue by 0101** [fable-compiler/Fable#2657]
### Description

Under certain conditions, using a function alias in a pipe creates an incorrectly uncurried function.

I don't know what are the exact conditions but it happened to me when I aliased `Option.defaultValue` (it's too long!). When a `Some` of a function (with arity >1) was piped through it it didn't receive any arguments past the first one when called. 

### [Example 1 (REPL)](https://fable.io/repl/#?code=LAKANgpgLgBAZjAhjARjAvDADgJwJYB2UcBMAJAEQDeiAvjFSrRaKJLHAPoD2WUe3UpgDK3ALYR4rcNHgBXAgGN+ggIIZ4PPgNIAfAHwwA8tsEA6ACYQ4iOWCgA1RGDmS4oOAuU71FT0pUCVQoYCgB3bhwAawBnFhA2WSsbO0dnVw0TQMtrW3snFwhEji9AgCENZLy0wvhNXkCPUp0Kv2bBMpDwyNj44vkAnQBhDS4GnRgDGCrUgoz3EH9vQRG2wZWuiOi40CA&html=Q&css=Q):
```fsharp

let f a b = printfn $"{a} {b}"

let f_option = Some f

let functionA = f_option |> Option.defaultValue f
functionA "functionA" "works"

let defaultValue = Option.defaultValue
let functionB = defaultValue f f_option
functionB "functionB" "works"

let functionC = f_option |> defaultValue f
functionC "functionC" "works"
```

Here, for `functionC` an extra `uncurry` call is generated.

#### Expected output
```
functionA works
functionB works
functionC works
```

#### Actual output
```
functionA works
functionB works
functionC undefined
```

### [Example 2 (REPL)](https://fable.io/repl/#?code=LAKANgpgLgBAZjAhjARjAvDADgJwJYB2UcBMAJAEQDeiAvjFSrRaKJLAObQBiArgQGMoeAPakAHjACeGaW2gwuUPoOFiAgmDyIAzrKUqhogq3AK4-IxtkIAPgD5FPS2tIBGUBdXH1MCl6sCdQo-AHcRHABrHRYQeVgA1wAhfWdvDS1dGDd4TxdjFP98sSSQinComNN2eGKCAGEbGAcnZTrNbT0AJjz0hr9E43qyiuiAfligA&html=Q&css=Q):

When trying to find a minimal example I encountered a slightly different behavior:

```fsharp
let f a b = printfn $"{a} {b}"

let getFunction x y = y
let getFunctionAlias = getFunction

let functionA = f |> getFunction 1
functionA "functionA" "works"

let functionB = getFunctionAlias 1 f
functionB "functionB" "works"

let functionC = f |> getFunctionAlias 2
functionC "functionC" "works?"
```

Here the uncurrying is actually done by the compiler and we get 
```js
(a, b) => { f(a, b); }
```
instead of 
```js
(a) => ((b) => { f(a, b); })
```

### Related information

* Fable version: 3.6.3
* Also REPL: 3.4.10, Fable: 3.4.10

**Comment by alfonsogarciacaro** [comment]
Yes, aliasing functions this way is tricky. I think we had a warning at some point, but removed because it had false positives sometimes. I'll have a look. In any case, if you want to alias I recommend creating a function with the same arguments (inline if you want to avoid the extra call). This works:

```fsharp
let inline defaultValue v o = Option.defaultValue v o
```

**Comment by 0101** [comment]
Thanks! 

I don't know the details but might be worth it putting the warning back in, it took me a while to find where the problem was.
