### ISSUE TITLE
[Python] Invalid codegen for `incr`

### ISSUE THREAD

**Issue by thautwarm** [fable-compiler/Fable#2677]
### Description

Using `incr(a)` causes `void(a.contents++)` which is invalid python syntax.

### Repro code

```fsharp

let f x =
    incr x
    !x
```

-> 

```python
from typing import Any

def f(x: Any) -> int:
    void(x.contents++)
    return x.contents
```

### Expected and actual results

```python
from typing import Any

def f(x: Any) -> int:
    x.contents += 1
    return x.contents
```

### Related information

* Fable version: `dotnet fable --version`:
   ```
     ➜ fable-py --version
     4.0.0-alpha-020
   ```
* Operating system: Windows 10(19043.1415)

**Comment by dbrattli** [comment]
Should be fixed in 4.0.0-alpha-021. Please re-open if things are not working as expected.
