### ISSUE TITLE
Fable 3.7 generated javascript performance

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/Fable#2684]
### Description

Generated javascript collection performance comments (under electron 16/Chromium recent version)

Fable when compared with F# 6 .Net runs 2X slower. Not bad. Some rough edges:

1. Sequences are a lot slower than under .Net
2. As a result of 1., `Map.values` - which generates a sequence - is about 5X slower than an optimal `Map.toList >> List.map snd` implementation. It is possibly more space efficient.
3. I don't really understand how much optimisation of sequences is done by the F# .Net compiler. You'd think in many cases they could be transformed to non-sequence equivalents before the Javascript generation but obviously not.

From: 
https://github.com/tomcl/issie/blob/a17356f2927f8b1fd663120cf1eac14edfae5a53/src/Renderer/Common/TimeTests.fs

### Electron16 (Chromium) javascript performance

```
Comparing speed filtering an input list, array, seq of size 90000.
The output is the same type as the input except for iter and for which change a mutable output value.
 In those cases the output must be a list: arrays cannot incrementally add one element quickly.
 Iter and For result in a reversed list as output: for non-reversed add on time of List.rev.
        Code Fragment           Time (output size=1)  Time (output size=89999) 
        sequence (seq) time:    12.82                  16.83
        list time:              5.11                  12.32
        array time:             3.40                  5.92
        array collect time:     8.30                  50.40
        list collect time:      0.56                  4.23
        list iter->list time:   0.64                  2.00
        array iter->list time:  0.23                  1.20
        array for loop time:    0.61                  5.80
 
Testing time in ns to read the values of a Map of given size (per value)
 Size  in items:   100       1000       10000
 viaArrays:       51.30     47.21      48.56
 viaArraysSumBy:  21.73     19.95      23.36
 viaLists:        31.19     28.71      44.45
 viaListsSumBy:   16.76     16.34      20.50
 viaValues:       214.51     183.44      190.54
 viaRamdomLookup: 92.45     164.95      215.52
```

### .Net 6 performance

```
Comparing speed filtering an input list, array, seq of size 90000.
The output is the same type as the input except for iter and for which change a mutable output value.
In those cases the output must be a list: arrays cannot incrementally add one element quickly.
Iter and For result in a reversed list as output: for non-reversed add on time of List.rev.

       Code Fragment           Time (output size=1)  Time (output size=89999)
       sequence (seq) time:    11.04                  19.33
       list time:              9.50                  25.66
       array time:             7.09                  17.83
       array collect time:     1.86                  2.69
       list collect time:      0.84                  8.54
       list iter->list time:   0.64                  2.57
       array iter->list time:  0.29                  2.12
       array for loop time:    0.38                  4.97

Testing time in ns to read the values of a Map of given size (per value)
Size in items:   100       1000       10000
viaArrays:       31.91     31.30      39.89
viaArraysSumBy:  22.93     25.59      31.91
viaLists:        26.80     28.83      39.71
viaListsSumBy:   21.79     21.28      24.25
viaValues:       35.49     35.18      36.25
viaRamdomLookup: 56.28     94.32      117.29
```

**Comment by ncave** [comment]
@tomcl Fair point, fixed `Map.keys` and `Map.values` in #2685. Thank you for reporting.

Please feel free to reopen if you spot other performance issues inconsistent with your expectations.

Fable sequences are lazy collections so they are expected to perform slower than lists and arrays when fully iterated, but the performance *ratio* should (in theory) more or less follow the .NET `FSharp.Core` performance ratio.

**Comment by tomcl** [comment]
Just a comment. My tests have going through arrays as 50% slower for small maps than going through lists. Which I find weird, but it seems to be the case. You could argue for arrays on the grounds that it is more space-efficient, and I think use cases where this is the main component of performance are probably pretty small.

```
 Size             100       1000       10000
 viaArrays:       51.30     47.21      48.56
 viaLists:        31.19     28.71      44.45
```

You can see that as expected for large collections things even up, but lists still stay faster at 10,000. However (I've just checked) at 100,000 map size lists go down to half the speed of arrays as expected. I guess it is some interaction with garbage collection. Anyway even though it is slower for most small use cases I think going via arrays is safer, since the large use cases are more significant.

Thanks, Tom

**Comment by tomcl** [comment]
I'm happy for this to be closed

**Comment by ncave** [comment]
@tomcl
I'm not sure how space-efficient arrays are internally, in JavaScript regular (untyped) arrays are complicated objects, more like dictionaries (they can have gaps). There are some internal optimizations in certain cases, if you use them with primitives and fill them in a gradual manner from the bottom-up, avoiding gaps. Typed arrays have more traditional representation and should be more efficient, they are used by default if possible, can be turned off with a compiler option, but they are only for numbers.

**Comment by tomcl** [comment]
That would explain why arrays do not look so good. But for this use case no problem
