### ISSUE TITLE
Seeded random is not deterministic

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2688]
### Description

`System.Random` does not give consistent output when given a fixed seed.

### Repro code

```fsharp
open System

let r = Random(0)

r.Next() |> printfn "%i"
r.Next() |> printfn "%i"
r.Next() |> printfn "%i"
```

### Expected and actual results

In FSI this gives the same every time:

> 1559595546
> 1755192844
> 1649316166

In Fable REPL this gives different results each time it is run. 

I would expect this to at least be deterministic, although the same as .NET would be even nicer!

### Related information

> Fable REPL 3.4.10

```bash
$ dotnet --version
6.0.101
```

**Comment by kerams** [comment]
https://github.com/fable-compiler/Fable/issues/2309

**Comment by ncave** [comment]
@njlr At the moment `Math.random()` [doesn't support](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Math/random) seeding, so Fable doesn't support it either.

I agree there needs to be a compiler warning issued when code tries to use the seed constructor. Contributions are very welcome.

A good work-around is to use your own random generator with statistical properties that satisfy your use case.
(e.g. see #2309 for some random generator suggestions, or use a different one that works for you).

**Comment by ly29** [comment]
If something isn’t supported an error seems reasonable instead of an warning.

**Comment by njlr** [comment]
I did a quick port of the C# [`System.Random`](https://github.com/microsoft/referencesource/blob/master/mscorlib/system/random.cs) to F#. 

Perhaps we can include this in the replacements?

```fsharp
type FSharpRandom (seed : int) =
  let MBIG = System.Int32.MaxValue
  let MSEED = 161803398
  let MZ = 0

  let mutable inext = 0
  let mutable inextp = 0
  let mutable seedArray = Array.zeroCreate 56

  do
    let mutable ii = 0
    let mutable mj = 0
    let mutable mk = 0

    let subtraction =
      if seed = System.Int32.MinValue then
        System.Int32.MaxValue
      else
        abs seed

    mj <- MSEED - subtraction

    seedArray.[55] <- mj

    mk <- 1

    for i = 1 to 54 do
      ii <- (21 * i) % 55
      seedArray.[ii] <- mk
      mk <- mj - mk

      if mk < 0 then
        mk <- mk + MBIG

      mj <- seedArray.[ii]

    for k = 1 to 4 do
      for i = 1 to 55 do
        seedArray.[i] <- seedArray.[i] - seedArray.[1 + (i + 30) % 55]

        if seedArray.[i] < 0 then
          seedArray.[i] <- seedArray.[i] + MBIG

    inext <- 0
    inextp <- 21

  new() =
    new FSharpRandom(System.Environment.TickCount)

  member private this.InternalSample() =
    let mutable retVal = 0
    let mutable locINext = inext
    let mutable locINextp = inextp

    locINext <- locINext + 1
    if locINext >= 56 then
      locINext <- 1

    locINextp <- locINextp + 1
    if locINextp >= 56 then
      locINextp <- 1

    retVal <- seedArray.[locINext] - seedArray.[locINextp]

    if retVal = MBIG then
      retVal <- retVal - 1

    if retVal < 0 then
      retVal <- retVal + MBIG

    seedArray.[locINext] <- retVal

    inext <- locINext
    inextp <- locINextp

    retVal

  member this.Sample() =
    float (this.InternalSample()) * (1.0 / float MBIG)

  member this.Next() =
    this.InternalSample()

  member this.Next(minValue : int, maxValue : int) =
    if minValue > maxValue then
      raise <| System.ArgumentOutOfRangeException("minValue", "minValue must be less than maxValue")

    let range = int64 (maxValue - minValue)

    if range <= int64 System.Int32.MaxValue then
      int (int (this.Sample() * float range) + minValue)
    else
      int (int64 (this.GetSampleForLargeRange() * float range) + int64 minValue)

  member this.Next(maxValue : int) =
    if maxValue < 0 then
      raise <| System.ArgumentOutOfRangeException("maxValue", "maxValue must be positive")

    int (this.Sample() * float maxValue)

  member this.NextDouble() =
    this.Sample()

  member this.GetSampleForLargeRange() =
    let mutable result = float (this.InternalSample())

    let negative = this.InternalSample() % 2 = 0

    if negative then
      result <- -result

    let mutable d = result
    d <- d + float (System.Int32.MaxValue - 1)
    d <- d / (2.0 * float (uint (System.Int32.MaxValue - 1)))
    d

  member this.NextBytes(buffer : byte array) =
    if isNull buffer then
      raise <| System.ArgumentNullException("buffer")

    for i = 0 to buffer.Length - 1 do
      buffer.[i] <- byte ((int (this.InternalSample())) % (int System.Byte.MaxValue + 1))

let r = FSharpRandom(1234)
let s = System.Random(1234)

for i = 0 to 9 do
  printfn "Next() %A %A" (r.Next ()) (s.Next ())
  printfn "Next(100) %A %A" (r.Next (100)) (s.Next (100))
  printfn "Next(1000, 10000) %A %A" (r.Next (1000, 10000)) (s.Next (1000, 10000))
```

**Comment by kerams** [comment]
Your parameterless constructor uses `System.Environment.TickCount`, which we don't have in Fable. The non-seeded replacement should not adopt this class and just emit the current code, which is supposedly just a call to `Math.random`.

**Comment by alfonsogarciacaro** [comment]
Maybe we could use something like `(new Date()).getTime() % 2147483647` or `Math.floor(Math.random() * 2147483647)` instead of `System.Environment.TickCount`. The nice thing about using `Math.random` is we can use the (non-seedable) System.Random API almost for free, but @njlr doesn't look like a lot of code and hopefully it's not much slower that native's `Math.random`. Using a custom class would also help to make the behaviour consistent when targeting other languages like Python or Rust. Programmers should be aware that both System.Random and Math.random only produce pseudo-random values so they need to look elsewhere for more secure methods.

**Comment by ncave** [comment]
(optional optimization)
Perhaps also the use of `int64` in Next can be replaced with `float`.
Should be a bit faster, due to the way `int64` is represented in Fable.

**Comment by kerams** [comment]
That would mean JS and .NET might generate different sequences with the same seed. Maybe that would not be desirable for someone?

**Comment by ncave** [comment]
@kerams I think the `int64` widening is just used for range checking, but I may be wrong. Anyway, it's fine as is.

**Comment by alfonsogarciacaro** [comment]
Good point @ncave, I missed that Random uses `int64`. This means that using Random will bring the full `int64` polyfill even if the app doesn't use longs or seeded random. Probably we should follow @kerams suggestion and have two Random classes, one with the code above (without the empty constructor) and only invoked when using a seed, and a light one that defaults to `Math.random` when we don't need a seed.
