### ISSUE TITLE
Beta build error - "Expecting string literal" @ ofImport

### ISSUE THREAD

**Issue by JordanMarr** [fable-compiler/Fable#2709]
### Description

I am getting the following errors on some of my bindings after upgrading to the latest v3.7.0-beta-005.

![image](https://user-images.githubusercontent.com/1030435/148697679-80fe2de3-196f-4c69-aab1-effbe75bc37d.png)

Ex:
```F#
    // This compiles without error in fable v3.6.3 but fails in v3.7.0-beta-005
    let [<Literal>] importPath = "@fluentui/react"
    let detailsList<'T> props = ofImport "DetailsList" importPath (IDetailsListProps<'T>.p<'T> props)
```

Hovering over `ofImport`, I see that it says "the first two arguments must be string literals".
I tried this, but the error still persists:
```F#
    // This still fails in v3.7.0-beta-005
    let [<Literal>] importPath = "@fluentui/react"
    let [<Literal>] importMember = "DetailsList"
    let detailsList<'T> props = ofImport importMember importPath (IDetailsListProps<'T>.p<'T> props)
```

### Related information

* Fable version: `dotnet fable --version`: 3.7.0-beta-005
* Operating system: Win 10

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @JordanMarr! Can you please try with beta-006?

**Comment by JordanMarr** [comment]
The issue is resolved. Subsequent build time dropped from 45s to 30s! Awesome! 😀
