### ISSUE TITLE
Feliz.Router importing non-existing functions from Feliz

### ISSUE THREAD

**Issue by AngelMunoz** [fable-compiler/Fable#2718]
### Description

During some feedback on https://github.com/AngelMunoz/perla-samples/issues/2
@nojaf found out that Feliz.Router seems to break on Fable 3.7 beta but not in Fable 3.6
Feliz Router seems to pull a React.useCallbackRef from Feliz but after fable 3.7 beta it doesn't seem to find the correct import 

webpack seems to also give warnings about missing functions which disappear in fable 3.6

### Repro code

- Perla project -> https://github.com/AngelMunoz/fable37repro
- Webpack Project -> https://github.com/AngelMunoz/fable372

### Expected and actual results

I don't expect to see any error in the browser's console or warning about non existing imports

Error
```
Router.fs.js:4
    Uncaught SyntaxError: The requested module '../Feliz.1.57.0/React.fs.js' does not provide an export named 'React_useCallbackRef_7C4B0DD6'
```

Although the compiled JS has this function
```js
export function useReact_useCallbackRef_7C4B0DD6(callback) {
    const lastRenderCallbackRef = useReact_useRef_1505(callback);
    const callbackRef = useReact_useCallback_93353E((arg) => lastRenderCallbackRef.current(arg), []);
    useReact_useLayoutEffect_3A5B6456(() => {
        lastRenderCallbackRef.current = callback;
    });
    return callbackRef;
}
```
so something might be getting missnamed 

### Related information

* Fable version: `dotnet fable --version`: `3.7.0-beta-008`
* Operating system: `Windows 11`

Please let me know if this is indeed here or should I move it to Feliz.Router

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for creating the project to reproduce the issue @AngelMunoz, that's been really helpful! 👍 Seems the problem was I introduced some changes in the AST and it prevented Feliz Hook plugin from working correctly. Hopefully it's fixed now, can you please try with beta-009?

**Comment by AngelMunoz** [comment]
@alfonsogarciacaro Looks like it's been fixed in beta-009! thanks!
