### ISSUE TITLE
Would like to fix small bug, but Fable tests are failing due to missing IFormatProvider

### ISSUE THREAD

**Issue by andagr** [fable-compiler/Fable#2726]
### Description
I've found a small bug here:
https://github.com/fable-compiler/Fable/blob/60b956fb0d457d377c78d68573e8cc9a16ac96da/src/fable-library/Date.ts#L174
`input` is compared to `null` using strict equality, which means it's `false` for `undefined`, and then rather than throwing the expected "not a valid Date" it throws an `undefined`-error:
![fable_parseRaw_error](https://user-images.githubusercontent.com/1420717/149287079-77834148-8233-44a7-ba9e-c4954a14ccc8.png)

However when running the Fable tests locally via `dotnet fsi build.fsx test` I get 4 test failues from tests/Main/StringTests.fs, e.g:

```
[07:12:58 ERR] All.Strings.String.Format works with thousands separator failed in 00:00:00.0030000.
. String does not match at position 2. Expected char: ',', but got ' '.
expected: 12,343,235,354.655
  actual: 12 343 235 354,655
```

I assume this is related to the tests not specifying an `IFormatProvider`, so formatting is done using my local culture, which is sv-se (Swedish). I tried specifying `CultureInfo.InvariantCulture` in the tests which makes the Expecto-tests succeed, but then the javascript-tests (mocha?) fails instead:

```
  1) Strings
       String.Format works with thousands separator:

      Error: Expected: 12,343,235,354.655 - Actual: 12343235354.654776
      + expected - actual

      -12343235354.654776
      +12,343,235,354.655
```

Any guidance on how to get the tests working?

**Comment by andagr** [comment]
This seems related:
#2582

**Comment by alfonsogarciacaro** [comment]
Ah, yes, sorry for that. I thought we were using `InvariantCulture` to avoid these issues, but it may be missing in some tests. I will check. If you send a PR with your changes, I can see which tests were failing.

In any case, thanks a lot for spotting the issue with the null check. If you send a PR with the change (you can edit Date.ts directly in Github if it's easier) it should pass the build so we can merge it :+1:

**Comment by andagr** [comment]
Thanks for the quick reply, and for a really cool project :)
The PR is here: #2728 

Will see if I can get the tests running locally as well as soon as I can, as I would have liked to add a test for this bug while fixing it.

**Comment by alfonsogarciacaro** [comment]
Thanks for sending the PR @andagr! I've updated the StringTests so they use InvariantCulture, I hope that helps: https://github.com/fable-compiler/Fable/commit/ac9bec8fd71b45861a01eb65353f296564d736e2

**Comment by andagr** [comment]
Thank you! That fixed those ones. There were two more that failed in se-sv culture, please see PR #2729 for the fix. With this all tests pass for me :).

**Comment by alfonsogarciacaro** [comment]
Great, thanks for confirming and for the PRs. Welcome as a Fable contributor!
