### ISSUE TITLE
Fable CLI 3.7 watch stales

### ISSUE THREAD

**Issue by AngelMunoz** [fable-compiler/Fable#2727]
### Description
Hey! sorry to bother again
When invoking the fable cli `3.7.0-beta-*` in watch mode through a library like `CliWrap` it never goes into watch mode this behavior is not observed in `v3.6.3` using the same conditions

```
Fable: F# to JS compiler 3.7.0-beta-009
Thanks to the contributor! @fbehrens

Parsing src\fable37-cli.fsproj...
src> cmd /C dotnet restore fable37-cli.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.
Project and references (1 source files) parsed in 2125ms

Started Fable compilation...
```

### Repro code
Here's a reproduction repository: https://github.com/AngelMunoz/fable37-cli

### Expected and actual results
I expect to observe the same behavior as Fable `3.6.3`, it should compile and start watching for file changes

### Related information

* Fable version: `dotnet fable --version`: `3.7.0-beta-009`
* Operating system: `Windows 11`

**Comment by AngelMunoz** [comment]
**Note**: invoking the CLI manually `dotnet fable watch ./src/project.fsproj` doesn't fail... so I'm not sure if it is related to something with a stdout redirect

**Comment by AngelMunoz** [comment]
I think they are generated, I need to check further, but CliWrap allows me to set env vars for the process perhaps I can add the CI env var, I'll test in a couple of hours and let you know

**Comment by AngelMunoz** [comment]
Well it weren't a few hours I could find a spot

> I see. Does watch mode doesn't work at all (no JS files are generated)

I just checked and no, no files are generated at all

Setting the CI flag (`.WithEnvironmentVariables(fun env -> env.Set("CI", "1") |> ignore)`) does indeed make it work! it isn't as pretty but works nicely
![image](https://user-images.githubusercontent.com/8684875/149438494-d3bef91a-60ce-4278-9692-2b411fc6dd89.png)

**Comment by alfonsogarciacaro** [comment]
Hmm,  interesting. So I guess that trying to move the cursor when being called from CliWrap is breaking/freezing the process somehow. Maybe opening an issue about that in CliWrap? Or you may need to spawn the process with its own shell.

**Comment by AngelMunoz** [comment]
Had a talk with CliWrap's author on discord he was kind enough to give this issue a glance

> Hi. Moving the cursor should not affect CliWrap anyhow, however the actual code that does this (i.e. calling Console.SetCursorPosition in Fable compiler) would most likely throw. I don't remember exactly. Are you sure the process doesn't outright crash? If so, it might write something to stderr.

Interestingly it doesn't seem to throw or crash the process (maybe it does? I just know that the program keeps running waiting for the command to finish)

> Also Alfonso said:
> > Maybe is there a way to also detect when the tool is being called as a subprocess?

You might be able to use this one instead of the CI env var possibly?

> You can do that by checking if the output is redirected via Console.IsOutputRedirected. If true, it's running through some automation tool and not in a shell.
> The best way to debug this would be to add Debugger.Attach() somewhere inside Fable compiler, probably put a breakpoint also in StreamPipeTarget (created by PipeTarget.ToStream(...), then call the CLI from CliWrap, and then see what happens exactly

I Will try to investigate further over the weekend if I have a chance in the meantime I can workaround this issue with the CI env var, I'll let you know if I find something

**Comment by alfonsogarciacaro** [comment]
Thanks for checking with CliWrap author @AngelMunoz! I've added the `Console.IsOutputRedirected` check, can you please try with beta-011?

**Comment by AngelMunoz** [comment]
Just in time before I go to sleep 😴 it worked!

![image](https://user-images.githubusercontent.com/8684875/149453016-8b4de2de-d4d8-48cf-bd9c-7e50095ca058.png)
