### ISSUE TITLE
[Python] Regex support

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2752]
@dbrattli How's the support for Regex? I see there's a file in `fable-library-py` but there are no tests and when I tried to run this code it failed:

```fsharp
open System.Text.RegularExpressions

let r = Regex("foo")
r.IsMatch("bar") |> printfn "%b
```

I have a small query language implemented with regex that works with CSV files and I wanted to try it with the Python interactive and Pandas 😸

**Comment by dbrattli** [comment]
Currently not implemented, we need to fix `src\fable-library-py\fable_library\reg_exp.py` similar to `RegExp.ts`. Regex are a bit different in Python so it's not a direct translation.  Let me have a look at it later tonight.

**Comment by dbrattli** [comment]
@alfonsogarciacaro , I've started the port, but it's going a bit slowly (now you have two problems 😉)

The last test I tried:

```fs
[<Fact>]
let ``test Regex instance Match and Matches work`` () =
    let str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"
    let test pattern expected =
        let re = Regex(pattern, RegexOptions.IgnoreCase)
        let index = let m = re.Match(str) in if m.Success then m.Index else -1
        let ms = re.Matches(str)
        index + ms.Count |> equal expected
    test "[A-E]" 10
    test "(ZZ)+" -1
``` 

Transpiled to:

```py
def test_regex_instance_match_and_matches_work() -> None:
    str_1: str = "ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz"

    def test(pattern: str, expected: int) -> None:
        re: Any = create(pattern, 1)
        index: int
        m: Any = match(re, str_1)
        index = m.index if (m is not None) else (-1) # FIXME: needs to be .pos
        ms: Any = matches(re, str_1)
        Testing_equal(expected, index + len(ms))

    test("[A-E]", 10)
    test("(ZZ)+", -1)
```
In the code I need to change `m.index` to `m.pos` (I think). Any clues what generates the `.index` for the match object?

**Comment by dbrattli** [comment]
(btw fixed the issue above)
