### ISSUE TITLE
Lua Support for Fable

### ISSUE THREAD

**Issue by lucasteles** [fable-compiler/Fable#2753]
### Description

[Lua](https://www.lua.org/) is a very small language largely used for configuration and games. I think that would be great to write it in F#

wdyt?

**Comment by MangelMaxime** [comment]
Hello, 

there is a PR opened with a bit of work done to target Lua https://github.com/fable-compiler/Fable/pull/2509

I think they are looking for contributors to help work on it.

**Comment by alfonsogarciacaro** [comment]
Thanks for the reply @MangelMaxime. Closing for now as it's a duplicate of #2509
