### ISSUE TITLE
fable-cli failed with a keynotfound when using paket

### ISSUE THREAD

**Issue by runefs** [fable-compiler/Fable#2766]
### Description

Using paket for package management doesn't work when building a fable package. This is in contrast to the documentation stating that the only change needed is to copy the source files into `fable/`.

### Repro code

Any project using `paket` will result in `KeyNotFound` when trying to compile the dependant project with fable. Specifically it will fail in `tryGetFablePackage`

### Expected and actual results

The result should match the documentation. If using PackageReferences in the project file is required then that should be stated in the documentation otherwise I'd expect fable to pick up the packages referenced using paket.

### Related information

* Fable version: `3.6.3`
* Operating system: macOS 12.1

**Comment by alfonsogarciacaro** [comment]
Would you have a specific example? TBH, I'm not sure about the mechanics atm but there are indeed Fable packages using Paket, for example all libraries for Elmish, like [Elmish.React](https://github.com/elmish/react).

**Comment by alfonsogarciacaro** [comment]
If it's ok with you @runefs, let's close this as Paket is being used successfully with several Fable libraries. Please reopen if there's a way to reproduce the issue so we can investigate.
