### ISSUE TITLE
`String.Format` should fail if there are less arguments than placeholders

### ISSUE THREAD

**Issue by JaggerJo** [fable-compiler/Fable#2768]
### Description

`String.Format` replacement behaves differently than .NET implementation.

### Repro code

```fsharp

let formatted = String.Format ("Hello {0}", args = Array.empty)

// .NET -> throws a String.FormatException
// Fable -> returns "Hello undefined"
```

### Expected and actual results

I'd expect an invalid call (placeholder count > argument count) mismatch to throw, as the .NET implementation does. 

Note that the .NET implementation does not throw if the argument count exceeds the placeholder count.

### Related information

* Fable version: `dotnet fable --version` 3.1.1
* Operating system

**Comment by JaggerJo** [comment]
A length check is missing here IMHO. 

https://github.com/fable-compiler/Fable/blob/155bd5e0e446a11ad010d4869a04ca59785f183a/src/fable-library/String.ts#L125

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @JaggerJo!
