### ISSUE TITLE
Unable to use System.Text.Json.Nodes with Fable

### ISSUE THREAD

**Issue by guythetechie** [fable-compiler/Fable#2771]
Apologies if I'm missing something simple, but I'm unable to use the [System.Text.Json.Node](https://docs.microsoft.com/en-us/dotnet/standard/serialization/system-text-json-use-dom-utf8jsonreader-utf8jsonwriter?pivots=dotnet-6-0#use-jsonnode) namespace introduced in .NET 6.

For simplicity, I started with the [minimal template](https://github.com/fable-compiler/fable2-samples/tree/master/minimal) and made the following changes:

**src/App.fsproj**
- Updated TargetFramework to net6.0
- Updated Fable.Core package reference to 3.6.1

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="App.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="Fable.Core" Version="3.6.1" />
    <PackageReference Include="Fable.Elmish.React" Version="3.0.1" />
  </ItemGroup>
</Project>
```

**src/App.fs**
- Added System.Text.Json.Nodes namespace
- Added line to create a JSON value and write it to the console
```f#
....
open Fable.React.Props
open System.Text.Json.Nodes

System.Console.WriteLine(JsonValue.Create("abc").GetValue<string>())

// MODEL

type Model = int
....
```

**src/.config/dotnet-tools.json**
- Updated the fable tools version to 3.6.3
```json
{
  "version": 1,
  "isRoot": true,
  "tools": {
    "fable": {
      "version": "3.6.3",
      "commands": [
        "fable"
      ]
    }
  }
}
```

I then ran ``npm install``, which was successful. ``npm start`` gave me the error below:
```text
Started F# compilation...
F# compilation finished in 4775ms

Started Fable compilation...
Fable compilation finished in 653ms

.\src\App.fs(12,18): (12,22) error FSHARP: The namespace 'Json' is not defined. (code 39)
.\src\App.fs(14,1): (14,69) error FSHARP: A unique overload for method 'WriteLine' could not be determined based on type information prior to this program point. A type annotation may be needed.

Known type of argument: 'a

Candidates:
 - System.Console.WriteLine(buffer: char[]) : unit
 - System.Console.WriteLine(format: string, [<System.ParamArray>] arg: obj[]) : unit
 - System.Console.WriteLine(value: bool) : unit
 - System.Console.WriteLine(value: char) : unit
 - System.Console.WriteLine(value: decimal) : unit
 - System.Console.WriteLine(value: float) : unit
 - System.Console.WriteLine(value: float32) : unit
 - System.Console.WriteLine(value: int) : unit
 - System.Console.WriteLine(value: int64) : unit
 - System.Console.WriteLine(value: obj) : unit
 - System.Console.WriteLine(value: string) : unit
 - System.Console.WriteLine(value: uint32) : unit
 - System.Console.WriteLine(value: uint64) : unit (code 41)
.\src\App.fs(14,26): (14,35) error FSHARP: The value, namespace, type or module 'JsonValue' is not defined. (code 39)
Watching...
```

**Comment by alfonsogarciacaro** [comment]
Hi @guythetechie! Thanks for the detailed report, as [mentioned in the docs](https://fable.io/docs/dotnet/compatibility.html), Fable only supports a small subset of .NET BCL. Usually there's a more meaningful error message, but in this case it seems System.Text.Json is not included in the assemblies referenced by Fable (Fable compilation is different from what happens when running `dotnet build`) so the error message is a bit confusing.

If you want to parse JSON with Fable, you can use the JS native APIs (`Fable.Core.JS.JSON.parse/stringify`) or a Fable-compatible library like [Thoth.Json](https://thoth-org.github.io//Thoth.Json/) or [Fable.SimpleJson](https://github.com/Zaid-Ajaj/Fable.SimpleJson#fablesimplejson---).

**Comment by guythetechie** [comment]
Thank you @alfonsogarciacaro for the response and JSON parsing suggestions. Closing the issue.
