### ISSUE TITLE
[Python] File extension broken with latest release

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/Fable#2787]
### Description

Looks like #2774 broke Python file generation outside fable_library for Python. E.g  `program.py` will now be generated as `program_fs.fs.py`. Investigating ...

FYI: @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
@dbrattli Ah, sorry for that. This is compiling **without** `--outDir`, right? I set it to use the .fs.py extension in that case but it looks as if Fable adds the extension, then replaces `.` with `_` and then adds the extension again :/

**Comment by dbrattli** [comment]
Yes, it's compiling without --outDir. Debugging right now

**Comment by dbrattli** [comment]
Note that the extension for Python must  be `.py`, not `.fs.py` since for `filename.fs.py` would mean the `fs` file module within the `filename` dir module (which will fail)

```
filename
        \  
         fs.py
 ```

**Comment by dbrattli** [comment]
Ok so it must be here:

```fs
let defaultFileExt usesOutDir (language: Fable.Language) =
        let fileExt =
            match language with
            | Fable.TypeScript -> ".ts"
            | Fable.Python -> ".py"
            | Fable.Php -> ".php"
            | Fable.Dart -> ".dart"
            | Fable.Rust -> ".rs"
            | Fable.JavaScript -> ".js"
        if usesOutDir then fileExt else ".fs" + fileExt
```
