### ISSUE TITLE
Update source-map-sharp

### ISSUE THREAD

**Issue by delneg** [fable-compiler/Fable#2793]
Hello,
Just letting you know that maybe it's a good idea to update source-map-sharp version used in Fable to 1.0.8, see if everything works fine.
@davidtme did notice substancial improvement in parsing speed (see delneg/source-map-sharp#9) using StringBuilder.

P.S. Please also take a look at delneg/source-map-sharp#8

**Comment by alfonsogarciacaro** [comment]
Thanks @delneg! Yes, I think this makes sense. We can make this the last change to increase performance for the "official" 3.7 release :+1: 

And sorry, for some reason I missed the notification for the issue in the source-map-sharp repo, I'll reply there.
