### ISSUE TITLE
Can we improve jsNative error message?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#2805]
### Description

The error reported by `jsNative` is not really explicit.

A few days, ago someone posted an issue https://github.com/thoth-org/Thoth.Json/issues/128 on Thoth.Json where he didn't understand why his code was not working.

The error was that he was trying to use Thoth.Json on .NET runtime instead of Thoth.Json.Net.

So he was gettting:

```
Unhandled exception. System.Exception: JS only
```

If you are not used to writting binding, this error is a bit cryptic.

@alfonsogarciacaro What do you think of trying to make the message a bit more verbose/explicit.

Something like:

This API is available on JavaScript only. Please, check that your binding is correct or if the library provides different packages per runtime (JavaScript, .Net, etc.).

or

This API is available on JavaScript only. Possible source of the problem:
1. Your binding is incorrect
2. You are not using the right version of the package for the targetted runtime (JavaScript, .Net, etc.)
3. Make sure you are compiling and running the project through Fable and not dotnet

**Comment by alfonsogarciacaro** [comment]
Sorry for the late reply @MangelMaxime. I think this is a nice idea. In Fable 4 we're replacing `jsNative` with `nativeOnly`, so it'd be nice to have a generic message for any target language. A couple of other notes:

- This message will only be seen if compiling (and running) `jsNative/nativeOnly` to .NET by mistake. When compiling to Fable, the method is [always intercepted and an error message displayed at compile time](https://github.com/fable-compiler/Fable/blob/b3eba43a65a381061d8120bce8c48364dce669b2/src/Fable.Transforms/Replacements.fs#L1167-L1173). So we probably can use something like: "You've hit dummy code, this probably means you're compiling Fable bindings to .NET by mistake, please check."
- To display the error message in .NET we need to push a new version of Fable.Core. I'm ok to do it but I think users update it less frequently so it will take a while until it becomes more widely used.

**Comment by MangelMaxime** [comment]
> Sorry for the late reply @MangelMaxime. I think this is a nice idea

No worry :)

> To display the error message in .NET we need to push a new version of Fable.Core. I'm ok to do it but I think users update it less frequently so it will take a while until it becomes more widely used.

True for the slow deployment of Fable.Core but I think this is still better than the current message.

> "You've hit dummy code, this probably means you're compiling Fable bindings to .NET by mistake, please check."

I don't know if we should be more explicit exhaustive in the possible source of the problem like I tried to be. I will let you make the final decision, as both proposition are better than the current message. :)
