### ISSUE TITLE
Unnecesary extra lambda with requestAnimationFrame?

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2817]
### Description

When creating a request animation frame loop, an extra lambda is created. 

### Repro code

```fsharp
open Browser

let mutable private previousTime = 0.0

let rec private loop time =
  let deltaTime = time - previousTime
  previousTime <- time
  window.requestAnimationFrame(loop) |> ignore
  ()

window.requestAnimationFrame
  (fun t ->
    previousTime <- t
    window.requestAnimationFrame(loop) |> ignore)
|> ignore

```

https://fable.io/repl/#?code=PYBwpgdgBAQgTsA7gZzHAUOgNmALlAWwFdcBDAIxyhDgEsA3U3MauMe24I5AFVoJYBeKAAYAdCMw58bAMasGTFlmCgoufkPRQo0qABMwWMnwFRhGswFpW7Tt1Nhttjl16aoAHhuWnOxLQQ+khibACORGDIuACCEPxMnBAAYnCkAgAUKqAAlFAAPgB8ULQA5hDAbM4ZOZgBQSHhkdFxCRrAKWkC1QBmRND4VoXOOjR2bo5ePiNQ9cGIoWARUbHxBIkdqelgWaogeUUl5ZVgtYdlFVVAA&html=Q&css=Q

### Expected and actual results

Compiles to this:

```javascript
let previousTime = 0;

function loop(time) {
    const deltaTime = time - previousTime;
    previousTime = time;
    window.requestAnimationFrame((time_1) => {
        loop(time_1);
    });
}

window.requestAnimationFrame((t) => {
    previousTime = t;
    window.requestAnimationFrame((time) => {
        loop(time);
    });
});
```

But this would be better:

```javascript
let previousTime = 0;

function loop(time) {
    const deltaTime = time - previousTime;
    previousTime = time;
    window.requestAnimationFrame(loop);
}

window.requestAnimationFrame((t) => {
    previousTime = t;
    window.requestAnimationFrame(loop);
});
```

### Related information

```bash
$ dotnet fable --version                      
3.7.0
```

**Comment by alfonsogarciacaro** [comment]
The F# compiler always create the lambda. I think at one point we had an optimization to remove it in cases like this, but I don't remember if the optimization is not working now because it was disabled by a refactor or because it caused issues in some edge cases.

**Comment by Zaid-Ajaj** [comment]
@kerams workaround?
```fs
[<Emit "$0!">]
let referenceByName (x: 'a) : 'b = jsNative

let rec private loop time =
  let deltaTime = time - previousTime
  previousTime <- time
  window.requestAnimationFrame(referenceByName (nameof loop)) |> ignore
```
Though not sure how this would work when nameof doesn't give you the exact compiled name

**Comment by alfonsogarciacaro** [comment]
I just realized the optimization was there but it was not working properly 😅 #2819 should fix it. The optimization is done at the very last step (printing) so unfortunately we cannot test it because we don't have tests yet to check the generated code string. It'd be nice to have something like this, probably we could add it to the [Compiler tests](https://github.com/fable-compiler/Fable/blob/b3eba43a65a381061d8120bce8c48364dce669b2/tests/Compiler/Util/Compiler.fs#L60-L81) by reading the contents of the generated file.
