### ISSUE TITLE
Dictionary with key of string with a unit of measure throws

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#2834]
### Description

Adding an item to a `Dictionary` where the key is a string with UoM throws an exception. `Map` works though. Things like `Array.groupBy` are also affected by this since there's supposedly a dictionary created behind the scenes.

### Repro code

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYCh0G0A8BBAVyWAHlwIA+AXXVWABMCAbMKAVQFkANKAXnSiCouDmACGCAgCcweCBGBIxKengBGamQDcAlsp3BKVKEjjgoyKTogBzHCPGSZ1KAHJUFPhaRXbmIVB0jCxQIFZayqxsEAhiAGas-AEBLEhQ1kzWrADGEkg4rmIANG5qngAUYlAAXG5iAJQ1pXwCQgDEOnFQAIQAYngAQgAyAKIA+gDCJBwACgCSowBKrcnJ5W1QAESbUFW1rmpQbfUrR2BMCGCnq4IEEGrAAB4FZbunbZD0nf5CpuacPH41yEyH02UCaDUYCk6QgmQgrCUdgcEmkYGo7gqjyalmsNkatVxtgKHi80ViCQAdLlkFBHj9VqCkDpwahIdDYfDWHckfYcKJUc4qJioOVsYSfHiSRQCd5fDYyTF4mBqXk6QzkkyWRDUFCYRkslAafkUU50cLUABGEqmtEY1AAJixOMlxPclplLvlJKdiopKuN6tOuEIxDIkGopyCzFY4akymAUgQLWBqU5hrCOgiKCgY2NOCgAD0ACoTEqFx6ocuPaAAdwAFpBRSWJlBE0XK22YRWILLylrWeyYYHahXUFAALSeHv1Z2jyuNJI3QTlcotrsd8ftmdNftKZmD3UckebyfTmuNR4nVNgNIGhGigB+AFJGmKmmPZT2vHm8jgAdWVYdpQQa2kK6B-Kwib0NCcz0BBZixlIMFSHBXhEnY0GwfQFCYGmVS8LAiAoKglITMATAsNkzKGAglIAOKQNCLKUgAIiyNEQGIUhwDgJDIdhJTWEgFQnGIlJ4PQ9Cis+mz0LE9CbCUAAM16ZhASBxNAmzPngOxiEAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q)

### Related information

3.7.0 on Win 10 and whatever version the REPL is on.

**Comment by alfonsogarciacaro** [comment]
Maybe I need to revisit the issue but unfortunately FCS doesn't give proper information for types with UoM, see https://github.com/dotnet/fsharp/issues/5992#issuecomment-569801049

Because of this, I have to hard-code the names of the types, including those in FSharp.UMX so atm it doesn't work for custom types.
