### ISSUE TITLE
[Beyond] Proposal: change codename to Snake Island

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2836]
Sorry for this, but giving we're not in the beta release cycle yet, it could be nice to change the codename of Fable 4 to "Snake Island" as a small homage to the people fighting for their freedom. If you agree, @ncave @dbrattli, I will rename the branch. Thanks!

**Comment by ncave** [comment]
@alfonsogarciacaro Go for it, and thanks for updating the doc page!

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave! I've renamed the branch, please use `snake_island` as the target for the PRs from now on.

**Comment by dbrattli** [comment]
@alfonsogarciacaro This is very nice! Thanks!

**Comment by Happypig375** [comment]
Nice pun with the addition of Python which is a snake as well.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry for that! Is `snake_island` updated with the latest Rust bits now? I can push a new release. If there's nothing left in `beyond` we can just delete it.

**Comment by alexswan10k** [comment]
Nice. Will keep in mind. Thanks both.
