### ISSUE TITLE
Array setSlice is incorrect for slices of length 1 starting at 0

### ISSUE THREAD

**Issue by jpacker** [fable-compiler/Fable#2844]
In F# array slicing is bounds-inclusive and slices of length 1 are functionally the same as indexing with an index (except the assignment must be an array).

ie:

`> let a = [|1;2;3;4;5;6|];;`
`val a: int[] = [|1; 2; 3; 4; 5; 6|]`
`> a.[0..0] <- [|999|];;`  
`val it: unit = ()`
`> a;;`
`val it: int[] = [|999; 2; 3; 4; 5; 6|]`
`> a.[3..3] <- [|999|];;` 
`val it: unit = ()`
`> a;;`
`val it: int[] = [|999; 2; 3; 999; 5; 6|]`

In the Array module, setSlice does not work correctly for a[0..0]. In Fable, take the following example.

`let a = [|1;2;3;4;5;6|]`
`//val a: int[] = [|1; 2; 3; 4; 5; 6|]`
`a.[0..0] <- [|999|]`
`printfn "%A" a`
`//[|999; undefined; undefined; undefined; undefined; undefined|]`

This is due to lines 611-613 seen below.
https://github.com/fable-compiler/Fable/blob/b202924c8f512ed189d36d368090001d30842161/src/fable-library/Array.fs#L610-L619

For the a.[0..0] case, on line 613 the `>` should be a `>=`, but of course, the actual fix is more subtle than that due to supporting a.[0..]

I understand it is odd to see a.[0..0] or a.[3..3], but this can happen when programmatically creating slices based on the size of another array in generalized code. 

Tests are also needed for these cases.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the report and spotting the problem @jpacker! I will push shortly a new release with the fix.
