### ISSUE TITLE
Memory leak in `Regex.Matches`

### ISSUE THREAD

**Issue by Prunkles** [fable-compiler/Fable#2845]
### Description

An infinite loop with a memory leak appears when use the `Regex.Matches` function.

### Repro code

```fs
open System.Text.RegularExpressions

let input = "aaa"
let pattern = @".*"
let ms = Regex.Matches(input, pattern)
// here the code loops infinitely and the memory starts consuming
```

It's reproduced in Fable REPL as well.

### Expected and actual results

Returns a collection of matches.

### Related information

* Fable version: 3.7.6
* Operating system: Manjaro Linux
* Browser: Firefox Developer Edition 99.0b2

**Comment by alfonsogarciacaro** [comment]
Thanks for the report and the code to reproduce @Prunkles! I will push shortly a new release with the fix.

**Comment by Prunkles** [comment]
I found a simpler example:
```fs
let input = "ab"
let pattern = @"(?<=a)(?=b)"
let ms = Regex.Matches(input, pattern)
```

I guess the problem is in the lookarounds.

**Comment by Prunkles** [comment]
https://github.com/fable-compiler/Fable/blob/ca276d826db804441ae9353077f0967cfa2c64a8/src/fable-library/RegExp.ts#L38

Why not just use `Array.from(input.matchAll(reg))` here?

**Comment by alfonsogarciacaro** [comment]
Ups! Thanks for checking and providing further test cases. Using `matchAll` makes sense but it looks like we need to retarget TypeScript compilation to es2020. It should probably be fine at this point, but we risk breaking some projects that may be missing a polyfill. Also, `matchAll` doesn't accept a start index so to be compatible with the `startAt` parameter in .NET Regex.Matches we would have to find a workaround for that.

I've tried to "fix the fix" in cd01f23ee7821370d6156dddbd34c280d6908955 and it works for the samples above. If you think this solution works for you I can push another release with the patch.

**Comment by Prunkles** [comment]
I've tested the new fix with a few more cases, and it's still not exhaustive.

After playing around a bit, a solution seem to be found: [TypeScript Playground link](https://www.typescriptlang.org/play?target=7#code/GYVwdgxgLglg9mABAWwIZQgCwKYGcAUATtgOYBciASqQKIAeADgDSIxgMhQW5SFskseqQlACCURAF5EABgCUiAN4AoRK2CJ8bDhMnSwIADaGFKtWqiZCcAO6Iw2OzULXC+AEQBJdp0QRUYGBwEgBG2PZGhu5yANyqiAC+8TAa+ACExCQAdCSGcCGoJkrxFla29o6Izq4eAHIIALS5+YVUtIzRMYgA9N2IAArEAG7YYBJswGwwUOF5cAzxSWqZWYaoPN4AJth0UohCIuJxahAIPCjoWHgU1CT0DPTYEKIuqACeANoAunvfx4iGbASZA3doPOhPF6Ed6IAA+EWM-0BEjWPAAspdMFsdnsGgBGf69RBQXCGNhcTYwXCoEKAhoOOhQBpkhxkIINU5gSmwBCFBrrXAwEhgZCjKDxGyYGCAzT4ZB7FY7J5aHxQOQKNL6SKmEo9PqeCT+JCYVAMBijRDYEZIZoFQyITI4khA-ZQEAQADWgmw4QAxAAmAAcABYAKy6lKaZBZNjbXZ6aSoqAYjBYrk7HXmcxE3AemAMC6p3VqSNymPp3YAHlYqtWoxIlkQDUQeMzWfM8q1xmL5hWSexdAA1IOewlLYZcOEzO21CFiKgPf8s0tzGPsBOpz2kymsAO9tHYzslx3MXgshxcJg5bFdSuV8Q3YQkGhU3g4kllKBIDykDMeCqdG4Xh+BYTJQTuRg2xOM4JFQaAQFaaQXyuAhMhYbRODkXVOXOHZzWgbBNj2KF3iyYBrGQADOCyZDMFEYwiFIdVsJg-Z3QgPBcD2AApABlAB5Wosh4PgwBIFI3nwOC3UKBQ9EQPjBOE4CxIk-A8KeGZNiwrNSzSXB2M4qD2xwuBASybAXDgNwAANaLwfAABJFEyBIWHcZyMKgBJoikaRnMUoSRP4NTpIQkwx01RAAoEoKVPE4BJI0gjtISGydNXcdJ2KGdoLAXAzOwVY4BIfA7NPAhnNc9zPNVHy5P8xRAuU0SEsksLZLHeSYqU4LVMS9TGE0wi5DSjK1CSD8cIkBh0BmJ89nwOSAD4enwAB+StJGiDayAAHQOvbYQO9xYSyOQACoNu2uRYQ+UQGgALVQBoAC8ZAaABOAB9BovkHboSGUP8oHwXj4qyaEbBs9x3BslhZqgeawCWrCQbBiGoZs1BEFhxAQnhxBEeR1HgbwUHwdayHUGhnH3BCRA9vcCB3EQbZ3GAOGEbmyyUeY9HKf4anadZk7Gdh1n6fFlm2ewDmuaJnmn1JgXMZp7HRaZ8XYdQPbcE2YA9tx3HNcZxmmdFiWGaZmX2c5wnid5lXyYxqmsdQTXLZ1vWDaNxAAHJ3H9xng9EdxeKIvbUEN1BsA0f2jZx4P-YTw6JZNyXjdhPHs4zyXTaNk6valm3WbthXHeV5igA)

**Comment by DragonFrai** [comment]
Shorter version [TS Playground](https://www.typescriptlang.org/play?target=7#code/GYVwdgxgLglg9mABAWwIZQgCwKYGcAUATtgOYBciASqQKIAeADgDSIxgMhQW5SFskseqQlACCURAF5EABgCUiAN4AoRK2CJ8bDhMnSwIADaGFKtWqiZCcAO6Iw2OzULXC+AEQBJdp0QRUYGBwEgBG2PZGhu5yANyqiAC+8TAa+ACExCQAdCSGcCGoJkrxFla29o6Izq4eAHIIALS5+YVUtIzRMYgA9N2IAArEAG7YYBJswGwwUOF5cAzxSWqZWYaoPN4AJth0UohCIuJxahAIPCjoWHgU1CT0DPTYEKIuqACeANoAunvfx4iGbASNY8ACyl0wWx2ewaAEZ-oCJMgbu0HnQni9CO9EAAfCLGf7xXqIKC4QxsLibGC4VAhQENBx0KANckOMhBBqnMBU2AIQoNda4GAkMDIUZQeI2TAwQGafDIPYrHZPLQ+KByBRpfSRUwlHp9TwSfxITCoBgMUaIbAjJDNAqGRCZaEkIH7KAgCAAa0E2HCAGIAEwADgALABWPUpTTILJsba7PTSEFQcEYSHcna68zmYm4T0wBgXNN65akVbrKBQugAamreoSVsMuHCZmzAIrqawVb2MbjO3+2bQabwWQ4uEw8ti9cW8WI7sISCHV1wcSSylAkF5SBmPFVOm4vH4LEyKLujCz5i551Q0BArWkS5wBEyLG0nDkeqvEh2Fug2E2eyYu8WTANYyB7pwWSPqIxhEKQGqfmcEi4B6EB4LgewAFIAMoAPK1FkPB8GAJApG8+A3u6hQKHoiA4fhhGHiRZH4D+TwzJsH7ZlG6QoRAaG4LgF5tn4ZxwICWTYC4cBuAABo+eD4AAJIomQJCw7gqW+UAJNEUjSCp9EEUR-AsZRd4mA2WqIIZeHGUxpHAORbF-pxCSyVx5gNtgTYtiWl5iRJeQkPg8kQopKlqRpWlqrpNEGYoRmMcRjnkeZ1ENrRtkMSZzFOaxjDsf+cjuZ5ahJGuX6IAw6AzAuez4DRAB8PT4AA-AAPJI0TtWQAA6A19TiA3uDiWRyAAVO13VyDiHyiA0ABaqANAAXjIDQAJwAPoNF81bdCQyg7lA+DYQ5WRYjYsnuO4sksDVUB1WAjUfidZ0XVdsmoIgt2ICE93VbVUkvQh73nSll2oNdP3uCEiB9e4EDuIg2zuMAd0PcDC6vcdeCnRD-BQzDKMjQjt0o3D5PI6j2Do5jQNPSDuPg590PfaTiPk7dqB9bgmzAH1v2-ZzCMI4jpMU-DiM02jGOA49z0s-jH2Q19qCc5LPN8wLQuIAA5O4+sI8bojuNhAF9agguoNgGj60LP3G-rDuDRTIuU8LOJ-d7HuU6LQsjVrVMyyjcsM4rzMIUAA)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for this @Prunkles, @DragonFrai! I've implemented your suggestion and added the other tests cases. Hopefully I did it right this time 😺

**Comment by Prunkles** [comment]
Looks nice! Waiting for the next release with the fixed fix. Thank you!

**Comment by alfonsogarciacaro** [comment]
I've pushed a new release with the fix, please give it a try :+1:
