### ISSUE TITLE
Duplicate const definition (from using member constraints?)

### ISSUE THREAD

**Issue by stkb** [fable-compiler/Fable#2855]
Getting invalid JS here. Have cut this code down as much as I can. Note the extra `const f_3 = f_3;` line near the bottom of the output JS. [REPL link](https://fable.io/repl/#?code=C4TwDgpgBAYgrgOwMbAPYCcoF5aJRqAdwEtgALAWACgooBnYAQ2GKSgFsJ2AjCTYhABsB0dozBQAFPGRp0AGigAzAFxQA5IygBaAHwbuigB5rG6dIxAAeTboCU2KAEFzlgHRiJSqEeq0GzKwcXLz8QiIc4lIy+ArKapo6+uqGPmoAMsQMNoz2jpkMHlHevlTU1IIQwFACwgiiUZKqUAB6Wnqt3A6SJq1GDlh+UpItRlAELTFydmqSASxsnDx8kWBqk3hyUABUUm1JnQ67owct6N1TGIpKxnZ25VSgkFAAcqgIAKLsYKAFwDYAFX0ODen2+vyy1VQ3nUAJ2UD+gP0JHIQ3mQSWoRq4Xqq2imyu8Q07WSqVBXx+ID+kjIimAM1e7wpEOytgGQ1o5PBVMhUm8tLx3npD0q1TA6GIADdmA0wABZHkMKRGOhqLmUxEMCUIADmeTVTO5muA2r12CGnj5iHoBzoUAA1FAAEQAfSdDhV1CAA&html=Q&css=Q)

``` fsharp
type Functor = Functor with
  static member inline map (Functor, f: 'a -> 'b, x: array<'a>) = Array.map f x
  static member inline map (Functor, f: 'a -> 'b, x: List<'a>) = List.map f x

let inline map (f: ^a -> ^b) (x: ^x) =
  ((^x or ^Functor): (static member map: ^Functor * (^a -> ^b) * ^x -> ^r) (Functor, f, x))

type NonEmptyList<'T> = NonEmptyList of 'T * List<'T> with
  static member inline map (Functor, f: 'a -> 'b, NonEmptyList(h, t): NonEmptyList<'a>) =
    NonEmptyList (f h, map f t)

let private mapMyList (xs: NonEmptyList<string>) : NonEmptyList<string> =
  map (fun s -> s + "_") xs
```

``` js
import { Union } from "fable-library/Types.js";
import { list_type, union_type } from "fable-library/Reflection.js";
import { map } from "fable-library/List.js";

export class Functor extends Union {
    constructor(tag, ...fields) {
        super();
        this.tag = (tag | 0);
        this.fields = fields;
    }
    cases() {
        return ["Functor"];
    }
}

export function Functor$reflection() {
    return union_type("Test.Functor", [], Functor, () => [[]]);
}

export class NonEmptyList$1 extends Union {
    constructor(tag, ...fields) {
        super();
        this.tag = (tag | 0);
        this.fields = fields;
    }
    cases() {
        return ["NonEmptyList"];
    }
}

export function NonEmptyList$1$reflection(gen0) {
    return union_type("Test.NonEmptyList`1", [gen0], NonEmptyList$1, () => [[["Item1", gen0], ["Item2", list_type(gen0)]]]);
}

function mapMyList(xs) {
    let t, h;
    const f_3 = (s) => (s + "_");
    const f_3 = f_3;
    const _arg2 = xs;
    return (t = _arg2.fields[1], (h = _arg2.fields[0], new NonEmptyList$1(0, f_3(h), map(f_3, t))));
}
```

This started happening with v3.7.2. Versions prior to that also fail to build (the full code I have, not this cut down example) but for different reasons:

* ≤ 3.7.0: "Cannot resolve trait call map" errors
* 3.7.1: "Unexpected unresolved expression" errors
* 3.7.2: Compiles, but produces the invalid JS described above.

Thanks as always :heart:

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for trimming down the issue @stkb and sorry for the late reply. I finally managed to spot the problem, should be fixed in the next release.
