### ISSUE TITLE
Fable Samples Page is broken

### ISSUE THREAD

**Issue by leolorenzoluis** [fable-compiler/Fable#286]
### Description

It doesn't display anything when Adblock is turned on.
### Repro steps
1. Install Adblock and navigate to https://fsprojects.github.io/Fable/samples.html 
### Expected behavior

<img width="850" alt="screen shot 2016-07-26 at 6 54 14 pm" src="https://cloud.githubusercontent.com/assets/15150044/17158182/6e2a9c6e-5362-11e6-8d9f-f8f114a126c3.png">
### Actual behavior

<img width="889" alt="screen shot 2016-07-26 at 6 54 23 pm" src="https://cloud.githubusercontent.com/assets/15150044/17158179/628d1800-5362-11e6-91e1-fbcfd8b5a082.png">
### Known workarounds

Disable Adblock
### Related information

N/A

**Comment by tpetricek** [comment]
Have you tried reporting this as an Adblock issue? I think there is absolutely nothing odd about the samples page that should make Adblock think this is an ad...

**Comment by leolorenzoluis** [comment]
I think I figured out why.

```
[blocked] The page at https://fsprojects.github.io/Fable/samples.html was not allowed to run insecure content from ws://fsprojects.github.io/websocket.
``` 

Silly. I'll close this.

**Comment by alfonsogarciacaro** [comment]
Nice catch @leolorenzoluis! @tpetricek, is there an easy way to make that part appear only when building the website locally? Thanks!

**Comment by mexx** [comment]
I still have this problem.
My investigations showed that AdBlock reacts on `fb-content` class.
Maybe another class prefix without a clash with some social network would be better ;)

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the tip @mexx! I'll try to fix it when updating the documentation. This is probably the same as #574.

**Comment by alfonsogarciacaro** [comment]
I tried to change all `fb-` CSS classes to `fable-`, but that broke the styles 😞 Maybe @tpetricek can help here?

**Comment by codec-abc** [comment]
@alfonsogarciacaro I think you can close this one now :)
