### ISSUE TITLE
CancellationTokenSource seems to compile to a single token and does not implement Dispose?

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2879]
### Description

`CancellationTokenSource` seems to compile to a single token and does not implement `Dispose`.

### Repro code

```fsharp
open System
open System.Threading

let cts = new CancellationTokenSource()

let token = cts.Token
```

Compiles to:

```javascript
import { createCancellationToken } from "fable-library/Async.js";

export const cts = createCancellationToken();

export const token = cts;
```

https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSVolqB0AKgBYBOYAhgCYCWEA5uugDZhJQDGSCUAvFBDAB3KAGEKEDmGbMKSGsAiFgAa0gxgAV1JSAFAEomrdklXZ+XBETMR0QA&html=Q&css=Q

### Expected and actual results

I would expect something like:

```
import { createCancellationTokenSource } from "fable-library/Async.js";

export const cts = createCancellationTokenSource();

export const token = cts.token();
```

And for `Dispose` to be provided. 

### Related information

```bash
$ dotnet fable --version
3.4.3
```

**Comment by alfonsogarciacaro** [comment]
Sorry for the late reply @njlr. Not entirely sure why we implemented `CancellationTokenSource` and `CancellationToken` in the same object. Can you please provide usage code that's not working at the moment with the expected results so we can turn it into a test? Thanks a lot!

**Comment by alfonsogarciacaro** [comment]
It'd be nice to have a use case we can convert into a unit test for this to be actionable. As far as I can see it seems we (I) used a dirty & cheap implementation of `CancellationToken` that just uses the same object for the source and the token because there are no threads in JS and I just wanted to be able to cancel the async workflows. I'm ok with improving this implementation, but without a use case it's difficult to know if the new implementation is working as intended.

**Comment by njlr** [comment]
Sorry for the delay!

I wasn't able to come up with a simple unit-test that fails... I think the issue is the interplay between Fable and Feliz?

Anyway, here is a repro of the issue: https://github.com/njlr/fable-issue-2879

**Comment by alfonsogarciacaro** [comment]
@njlr I see, thanks a lot for the example to reproduce. We can make `CancellationTokenSource` implement `Dispose` but please note that, [according to MSDN documentation](https://docs.microsoft.com/en-us/dotnet/api/system.threading.cancellationtokensource.dispose?view=net-6.0), calling Dispose does not trigger cancellation, so if the effect you intended is to cancel the asynchronous operation if the React effect is disposed, you'll need to create a `IDisposable` object that calls `cts.Cancel` explicitly.

**Comment by njlr** [comment]
> calling Dispose does not trigger cancellation

Good catch, thank you!
