### ISSUE TITLE
Javascript: Generators, Async Generators

### ISSUE THREAD

**Issue by AngelMunoz** [fable-compiler/Fable#2885]
### Description

It seems that Fable JS doesn't have a representation to emit JS [generators](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Generator), generators are basically functions that can suspend execution and yield a result on the next invocation

these functions can be enumerated via Symbol.iterator and have a Generator Function prototype, while there are collections in the Fable Core library that can be enumerated with that same symbol, I don't think we have an equivalent for generator functions and also I'm not sure how close they are to IEnumerable/IEnumerator in the case for .NET

An example of such function is the following 

```js
async function* asyncInfiniteCounter() {
    let count = 0;
    while (true) yield count++;
}

const counter = infiniteCounter();
counter.next();
// { value: 0, done: false }
counter.next();
// { value: 1, done: false }
counter.next();
// { value: 2, done: false }

function* until3Counter() {
    let count = 0;
    while (count <= 3) yield count++;
}
const counter2 = until3Counter();
counter2.next();
// { value: 0, done: false }
counter2.next();
// { value: 1, done: false }
counter2.next();
// { value: 2, done: false }
counter2.next();
// { value: 3, done: false }
counter2.next();
// { value: undefined, done: true }
for (const value of until3Counter()) {
    console.log(value);
}
// 0 // 1 // 2 // 3
```

```js
const delay = (ms) => new Promise((resolve) => setTimeout(resolve, ms));

async function* asyncInfiniteCounter() {
    let count = 0;
    while (true) {
        await delay(1000);
        yield count++;
    };
}

const counter = asyncInfiniteCounter();
counter.next();
// Promise {<pending>}
await counter.next();
// { value: 1, done: false }
```

In the case for Async Generators they are basically the same with the difference that they return a promise on each yield, similar to IAsyncEnumerable/IAsyncEnumerator they are also iterable with [`for await`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of) there are not a lot of browser built ins that are asyncIterable but the one that got in recently are [Web Streams](https://streams.spec.whatwg.org/) which are also available in recent versions node.js so at some point these could be relevant

### Related information

For more information here is the spec for 
- Generators https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-generatorfunction-objects
- Async Generators https://tc39.es/ecma262/multipage/control-abstraction-objects.html#sec-asyncgeneratorfunction-objects

### Pending Questions

- How to write bindings for these kind of functions?
- Are there true F# equivalents for these constructs?

cc @alfonsogarciacaro (as per twitter question)

**Comment by alfonsogarciacaro** [comment]
Generators should be fine, because Fable makes .NET `IEnumerable` (aka F# `seq`) compatible with JS iterables. But IAsyncIterator is a different interface (it's not the same as `Iterable<Promise>`) so we need to add it. I would probably add the interface to Fable.Core.JS (generic and non-generic versions) but add helpers to Fable.Promise package as Fable.Core only includes metadata.

```fsharp
type AsyncIterable =
    interface end

type AsyncIterable<'T> =
    interface end
```

We won't be generating `async/await` JS workflows but we can generate an object that implements `Symbol.asyncIterator` (like the promise CE does) as in this example: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/for-await...of#examples

**Comment by alfonsogarciacaro** [comment]
Closing as there's already a PR in fable-promise to deal with this: https://github.com/fable-compiler/fable-promise/pull/36
