### ISSUE TITLE
Exception is raised by equals<T> when comparing objects created by Object.create(null)

### ISSUE THREAD

**Issue by BillHally** [fable-compiler/Fable#2900]
### Description

Objects created using by passing `null` to [Object.create](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Object/create#custom_and_null_objects) in javascript have no prototype, which results in an exception when they are passed to the [equals<T>](https://github.com/fable-compiler/Fable/blob/b0a610f07d28dab7c355a2428621db8a3ca03434/src/fable-library/Util.ts#L406) function defined in `fable-library/Util.ts`.

### Repro code

This [repro](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYFgBQXSSgMQEMAjAGzB3GiLLADoBhYAJws12pPMZfoCkEASQgpmoLFnJIoAMzGoAcgFdSpfAEtmyKFAC8UPjDoB5YgCswAYyR1LrQigAUEFaQCUWOcEWuNWpAD8CN5gAApi4MxIcFAAPAC0UABEAIJQAG6EpEpgSRKYUrLyyqowVsAQACZ6BkamFta29k4uqh6YXj6l5VVBIeG4UTEJyWmZ2bn5IMzqIjLQACRJnSVqmtqGxgoAXFAA3oZ0mwp0yDMQAObqMjErvutIAL55mNOzSPNQS3fdlhXVx12ByMx1OSHOVxuRW8qzKfyqz3yhVYCBU0n0PzW-joAFEAI5KLIIRyYuH-dpvOaLJIAJTAqNISF2AFJiHsUWjEZggA&html=Q&css=Q) demonstrates the issue. Although it uses some non-standard code in order to create a small repro, I did run into this issue with more normal code which uses a 3rd party package which uses `Object.create(null)` to create an empty object, then sets some properties on it. 

#### Expected

when such objects are tested for equality, `true` or `false` is returned as appropriate.

#### Actual

the following error occurs:
```
Uncaught TypeError: Object.getPrototypeOf(...) is null
equals https://fable.io/repl/js/repl/fable-library/Util.js:326
```

**Comment by BillHally** [comment]
I *think* that changing then end of `equals<T>` from:
```typescript
  } else {
    return Object.getPrototypeOf(x).constructor === Object && equalObjects(x, y);
  }
}
```

to:
```typescript
  } else {
    return equalObjects(x, y);
  }
}
```
would be OK, but I'm not sure. What is the `Object.getPrototypeOf(x).constructor === Object` checking that the earlier check:
```typescript
  } else if (typeof x !== "object") {
    return false;
  }
```
didn't already cover? Also, if it's necessary, why doesn't the prototype of `y` also need checking?

Anyway, if this issue is something you agree needs fixing, I'd be happy to create a PR to do so (once we've discussed what should go in it).

**Comment by alfonsogarciacaro** [comment]
Thanks for catching this @BillHally! This was done because of the implementation of anonymous records as plain JS objects. To enable structural equality/comparison in this case we need to assume that all **plain JS objects** are record-like. Note this shouldn't affect classes which have reference equality by default, that's why we need to check whether the prototype is exactly `Object` (this is not the case for class instances though `typeof x` is "object").

The TypeScript null-safe property accessor operator should work here:  `Object.getPrototypeOf(x)?.constructor`. Thanks again!
