### ISSUE TITLE
Bindings for ResizeObserver

### ISSUE THREAD

**Issue by davedawkins** [fable-compiler/Fable#2903]
I have created these bindings, in the style used in Browser.Dom/Api ; would you like a PR for them to review?

**Comment by alfonsogarciacaro** [comment]
That'd be great @davedawkins! Could you please send it to the fable-browser repo?

**Comment by alfonsogarciacaro** [comment]
If it's ok with you @davedawkins, let's close this. When ready, it'd be great if you could send the PR to the fable-browser repo. Thanks!
