### ISSUE TITLE
[Dart] Options as nullable types

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#2919]
Dart is null-safe, this means the compiler won't let you assign null to values that are not marked as nullable (it seems to be possible to assign null to generics though). At the moment, I'm compiling F# options as Dart nullables (so `int option` becomes `int?`), this plays well with Dart type checking, generates nice and works well in most cases. But it doesn't work with nested options because you cannot do something like `int??` in Dart. It's particularly tricky with generic options because in that case the consumer code can pass an option (becoming a nested option) and Dart type checking won't complain but it can cause unexpected behavior at compile time, because something like `Some None` just becomes `null` in runtime (I'm trying to at least throw an error instead of getting unexpected behavior).

In JS where there's a chance for a nested option, I wrap the value with a special `Some` type. But this doesn't work with Dart type system because I cannot cast `Some(5)` to `int?`.

Let's see what users feel about the limitation after announcing the alpha release, although I'm trying to think of alternatives. The most obvious one is to use "real" F# options, and leave `Nullable` for interop. The most problematic part would be the arguments. Not entirely sure how we would represent optional arguments in native bindings in that case.

Thoughts? @Nhowka @MangelMaxime 

> Note that Dart null-safety brings other limitations that we won't overcome even if using real F# options. E.g. we cannot assign null to a string or use `Array.zeroCreate<T>` when T is a class (because we cannot use null as default value).

**Comment by MangelMaxime** [comment]
If using "real" F# options means that standard F# code will works has expected, I think I would probably go this way.

*I know nothing about Dark ^^*

**Comment by ncave** [comment]
@alfonsogarciacaro On a completely unrelated note, great job with the Dart AST, very minimal:

AST sizes, without construction, comments or empty lines:

| AST | Size |
|-------|----------|
| Php | 100 lines |
| Dart | 160 lines|
| JS | 260 lines|
| Python | 280 lines|
| Rust | 750 lines|

**Comment by alfonsogarciacaro** [comment]
@ncave `[<Optional>]` may work. The trickiest part is the F# compiler will automatically inject the default value in the call site so for bindings we need a way to identify if the constant is compiler generated (maybe the range is empty?) and remove it.

For the Dart AST, I took some reference from the Dart documentation, but I've been mostly building it for the needs of the printer, so atm it cannot fully represent the Dart language. I'm happy that I changed it into a typed AST at the beginning, this way we can still make optimizations after the transformation.

**Comment by alfonsogarciacaro** [comment]
Ah, I just realized that F# AST uses `FSharpExprPatterns.DefaultValue` when filling `[<Optional>]` arguments (but only if `[<DefaultParameterValue>]` is not set). So maybe we can use that to identify arguments need to be removed.

**Comment by alfonsogarciacaro** [comment]
Ok, I've merged #2920 (and #2921) with the conclusions of this thread. I'll leave some notes for whoever is interested and my future self:

- Now options in Dart are always wrapped. This avoids issues but means we cannot use options to interop with Dart code as we do with JS.
- To represent nullables in Dart, I've added `Fable.Core.Dart.DartNullable`. This is the same as `Nullable` but it's not restricted to value types.
- The tricky part is to represent optional arguments in Dart. We can use `[<Optional>]` for that but in this case F# compiler will resolve the missing args in the call site (by injecting the default value) which has to be avoided (e.g., we don't want the compiler to use default values for ints when calling Dart APIs). I've tried to solve this with two actions:
    - Only for Dart for now, [I check also the Optional attribute](https://github.com/fable-compiler/Fable/blob/a9889955ba8c0e2413bbb8c148c5ae4663e824bf/src/Fable.Transforms/FSharp2Fable.Util.fs#L656-L661) to consider an argument declaration as optional.
    - F# uses `FSharpExprPatterns.DefaultValue` to fill missing args decorated with `[<Optional>]` (if `[<DefaultParameterValue>]` is not present), so I'm [resolving these always as null for Dart](https://github.com/fable-compiler/Fable/blob/a9889955ba8c0e2413bbb8c148c5ae4663e824bf/src/Fable.Transforms/FSharp2Fable.fs#L584-L588).

> Note that when `Unchecked.defaultof<'T>` is called explicitly this is resolved in Replacements module so it shouldn't be affected (Unchecked.defaultof causes issues in Dart with reference types but that's another issue).

> `FSharpExprPatterns.DefaultValue` is also used when initializing ref values used in APIs like `DateTime.TryParse` and in this case we do need to use the actual default value if possible, so I'm [resolving `DefaultValue` when used in a binding](https://github.com/fable-compiler/Fable/blob/a9889955ba8c0e2413bbb8c148c5ae4663e824bf/src/Fable.Transforms/FSharp2Fable.fs#L600-L607) separately.

> I couldn't find a way to remove the injected value when `[<DefaultParameterValue>]` is used but in principle it shouldn't mind, because bindings don't use `[<DefaultParameterValue>]`. It should only be used when writing functions with optional arguments that will be exposed to Dart. When writing such a function you'll need to type optional reference types as `DartNullable` so Dart compiler doesn't complain.

> A case to consider because it'll happen quite often is when passing F# optional arguments `?fsharpArg: int` to Dart optional arguments `[<Optional>] dartArg: int` as with `?dartArg=fsharpArg`. The compiler will translate these cases as `dartArg: Option.defaultValue(defaultof<int>, fsharpArg)`, so it's important to also use null as the default value here too.

**Comment by adelarsq** [comment]
> To represent nullables in Dart, I've added Fable.Core.Dart.DartNullable. This is the same as Nullable but it's not restricted to value types.

Fable.Core.Dart.DartNullable can be converted to Nullable and vice versa? 

For me the less things related only with Dart the better since we will be able to use the same code base for both web and mobile, for example.

**Comment by alfonsogarciacaro** [comment]
@adelarsq Yes, but `Nullable` cannot be used with reference types, that's why I had to add DartNullable to remove the restriction. The alternative would be to compile all reference types as nullables which would cause many other issues of its own.

Let's see how it  goes, I have the impression there's not much F# code dealing with nulls (unless it's to interact with C# libraries which won't work with Fable anyways). For strings, usually `String.IsNullOrEmpty` is used, which works.  F# serializers and similar tools like Thoth.Json usually use `option` to represent nullability.
