### ISSUE TITLE
Source maps possibly not working in Chrome?

### ISSUE THREAD

**Issue by MaxWilson** [fable-compiler/Fable#2924]
### Description

In response to a [Reddit question](https://www.reddit.com/r/fsharp/comments/v6f831/how_can_i_enable_source_maps_for_fable_f_code_in) and following directions at [https://github.com/MangelMaxime/fulma-demo/pull/43](https://github.com/MangelMaxime/fulma-demo/pull/43), I attempted to enable source maps on a repo based on the simple Fable template. I added source-map-loader v1.1.13 and added it to web config, as shown [here](https://github.com/lowercase1024/SimpleFableApp/pull/1/commits/054343c8a46f6f19a78d73f80a164d62f92189c8).

I hoped and expected that this would make Chrome show me App.fs itself, but alas:

![image](https://user-images.githubusercontent.com/6829565/172950784-f95f92f8-5b46-4e9f-b3c4-9220f399ab6b.png)

### Repro code

git clone https://github.com/MaxWilson/SourceMapRepro.git
npm install
npm start
Open Chrome and navigate to http://localhost:8080

### Expected and actual results

**Actual**: F12 shows App.fs.js (nice JavaScript) but no App.fs (F#).
**Expected**: When I F12 and Ctrl+O and type "App.fs", there should be an App.fs listed as well as App.fs.js, and it should be in F# and allow breakpoints, etc.

### Related information

Fable: F# to JS compiler 3.2.9
Windows 11

This is not a blocking issue for me personally (I actually like the JavaScript source maps because it means I don't have to guess at variable names) but it was perplexing to me that I couldn't help the Redditor use this feature.

### Additional information

I tried it with devtool: "source-map", devtool: "eval-source-map", and no devtool entry at all. Didn't seem to make a difference.

**Comment by alfonsogarciacaro** [comment]
Thanks for providing the "repro repo" @MaxWilson! I cloned it, run "npm i && npm start" and everything worked without issue. I can see the sources maps in Chrome. May it happen that you don't have source maps enabled in your browser? (You need to check "Enable JS source maps" somewhere in the settings)

![image](https://user-images.githubusercontent.com/8275461/172989518-5c36cc4e-aa82-496f-9127-25d9f26076f4.png)

**Comment by lowercase1024** [comment]
@MaxWilson, could it be that you just forgot to clean and rebuild the project? It didn't work for me either until cleaned the project with `dotnet fable clean`.

**Comment by alfonsogarciacaro** [comment]
Ah, you're right @lowercase1024. It may happen  that Fable doesn't update the files because it doesn't detect changes. But changing the sourcemap option should invalidate previous compilation, I'll check why that's not the case 👍

**Comment by MaxWilson** [comment]
Confirmed, doing dotnet fable clean && npm start enables F# source maps as expect. Closing this issue.
