### ISSUE TITLE
Fable RegEx and Unicode

### ISSUE THREAD

**Issue by zelenij** [fable-compiler/Fable#2925]
### Description

I don't understand how to force Fable to stamp /u flag on generated regular expressions.  Without it unicode specific stuff won't work.

### Repro code

```fs
let regex = Regex(@"^[\p{L} ,.'-]+$", RegexOptions.ECMAScript)
let res = regex.Match("John Smith")
printfn "%A %A" regex res
```

### Expected and actual results

Expected:

```js
/^[\p{L} ,.'-]+$/ug <something>
```

Actual:

```js
/^[\p{L} ,.'-]+$/g null
```

### Related information

* Fable version: online tool

**Comment by alfonsogarciacaro** [comment]
Oh, didn't know that JS regex didn't support unicode by default 😮 Maybe we should add it automatically for better compatibility with .NET (same as we do with the `g` flag)? Are there any performance considerations?

In the meanwhile you can invoke the JS RegExp constructor to pass flags manually:

```fsharp
JS.Constructors.RegExp.Create(pattern, "u")
```

This is a bit hacky, but I've also use this trick sometimes to create JS regex:

```fsharp
[<Emit("/$0!/u")>]
let unicodeRegex (pattern: string): Regex = jsNative
```

> The `!` after the placeholder tells Fable to emit the string content as is (don't surround it with quotation marks)

[Example in REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChSSyIobZoBSAzgJIQAuYWo+40AygJ6UMC2qAKmAAedVACUwAcwCuSOFgCiQkDkqUAlsAiVcuANoAeBT3V0AFACIA9ABIADAEIr0iwEoAfAF1cKOlGkQ6gDGwAAmYBKSwlBmIHB0DFgQAFxQ3FjqEJKuqZHRALxQAFaUAHLx6gBueD5gfgHBYRFSwgBMMXEJjClpdBlZOVB5QlD5uFATUORspNp90kF02JTiUkogGDjxYLHxiRAANFAWLq66vlA4USOFDSHhw+0AAhYAenoAOiAA3gAyAL5QA6oADkAFpPABqGwWWp+VSjS4tISoACy8SCAAtLORgJj2CY6Ji3LgVJk6AAzaAWACkAEEoPSLEjrkjKEA&html=Q&css=Q)

**Comment by zelenij** [comment]
I _suspect_ there might be performance issues, but I have never looked into it too deeply :)

Unfortunately, in my specific example I can't really fall back on calling native JS, because I want to share the same RegEx object between client and server.  I mean, of course I could code a workaround, but if you tell me this will be fixed in Fable soon, I'd rather not.

**Comment by zelenij** [comment]
I think /u flag is not compatible with older versions of JavaScript - I am not sure what's the officially supported version for Fable.  Some useful info here: https://stackoverflow.com/questions/280712/how-can-i-use-unicode-aware-regular-expressions-in-javascript
