### ISSUE TITLE
ResizeArray .Remove and .Contains don't work with union types

### ISSUE THREAD

**Issue by fahrenq** [fable-compiler/Fable#2931]
### Description
Some of the ResizeArray methods, such as `.Remove` and `.Contains` compile to JS code that doesn't use Fable's `equals` method when finding index of the union case in the array.

### Repro code
[REPL Link](https://fable.io/repl/#?code=C4TwDgpgBAggdgSwLYEMA2UC8UA+UAiArgMYDWAUGhMFEiAEoQDOCAXhDAE6cohZRwIAdyiMW7LjxAAeeMnQA+ABQBKcuQD0G2ABMdCOAHMCJUlBRwdUMJwPADx4AAtoKbr3J0xbDu5AA6GD0TMnIbOwAzOCgAIgAhCAiAe05oVKQkgDcHKB1TAC4oAFIYGNoGZh9JD01tAGEXMhyECKhnVz8oYiS4YBQDJlzTMNteqNi6nr6BobJCooAjMqUvSok-f0ne-rhBojI1WtEIDOyjNpdZswsrcN6c9vM-TwrxXyl-RlPofbMcBSgCEMcBSEBGkWiMRgEWAEE4UHSWRyeTmxVK5W86yk5CAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q)

#### Remove
Expected empty array, got array containing one `Duck`.
```fsharp
type Animal = | Duck
let myResizeArray = new ResizeArray<Animal>()
myResizeArray.Add Duck
myResizeArray.Remove Duck |> ignore
printfn "After removing duck: %A" myResizeArray
```
 
#### Contains
Expected `true`, got `false`.
```fsharp
type Animal = | Duck
let myResizeArray = new ResizeArray<Animal>()
printfn "Contains duck: %b" (myResizeArray.Contains Duck)
```

### Related information
* Fable version: 3.2.9
* macOS Monterey 12.0.1, Intel

**Comment by alfonsogarciacaro** [comment]
Ah, ok. The intention was to use the native versions for better performance but as you correctly point out, we need to check if the item is compatible with native equality and if not, offer custom methods that use F# equality.
