### ISSUE TITLE
[Python] file mode for writing

### ISSUE THREAD

**Issue by daz10000** [fable-compiler/Fable#2940]
### Description

Opening a file for writing - I have been struggling with finding the correct invocation for opening a file for writing in Python.  The python equivalent would be `open("output.txt","w")`.  I get various errors from intellisense with the code below

### Repro code

```
#r "nuget:Fable.Python"

open Fable.Python.Builtins

[<EntryPoint>]
let main argv =
    use outF = builtins.``open``(StringPath "output.txt",OpenTextModeWriting CreateText)
    0
```

I am compiling and watching with 

`dotnet fable watch --lang py --runWatch python program.py foo`

### Expected and actual results

I would expect that to create an output file(empty) called 'output.txt' but the generated python seems more complex than I would expect but also raises an exception

```
import builtins
import sys
from typing import Any
from fable_modules.fable_library.types import Array

def main(argv: Array[str]) -> int:
    def arrow_18(argv: Array[str]=argv) -> Any:
        raise 1

    with builtins.open("output.txt", mode = arrow_18()) as out_f:
        return 0


if __name__ == "__main__":
    main(sys.argv[1:])
```

The python throws an exception as you'd expect

```
.> cmd /C python program.py foo
Watching .
Traceback (most recent call last):
  File "C:\extproj\FablePython\program.py", line 15, in <module>
    main(sys.argv[1:])
  File "C:\extproj\FablePython\program.py", line 10, in main
    with builtins.open("output.txt", mode = arrow_18()) as out_f:
  File "C:\extproj\FablePython\program.py", line 8, in arrow_18
    raise 1
TypeError: exceptions must derive from BaseException
```

### Related information

```
$ dotnet fable --version
4.0.0-snake-island-alpha-010
```

Win 10, dotnet 6.0.300

**Comment by daz10000** [comment]
I think you're on top of this already but the workaround was
```
open Fable.Core.PyInterop
use outF = builtins.``open``(StringPath "output.txt",!!"w")
```

And also small but important thing - the write method is missing from the `TextIOBase` - 

```
type TextIOBase =
    abstract read : unit -> string
    abstract read : __size: int -> string
    abstract write : __message: string -> int // this was missing
```

With those two changes my code does work now though.. just ported a large simulation to Python with almost no effort other than this little wrinkle..

**Comment by dbrattli** [comment]
Yes, it was a bit complicated trying to make it type safe. There is a PR that should simplify/stringify things. What do you think? https://github.com/fable-compiler/Fable.Python/pull/58

**Comment by alfonsogarciacaro** [comment]
Closing as this should have been already fixed in Fable.Python library. Please reopen if needed.

**Comment by dbrattli** [comment]
Yes it's fixed in Fable.Python but not pushed to NuGet yet. I got a bit confused if Fable.Python should depend on Fable.Core or my own Fable.Core.Experimental, or if I should now deprecate Fable.Core.Experimental? And similar if I should still keep `fable-py`dotnet tool or use the fable tool now? @alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
I think it should be ok now to use the Fable.Core 4 alpha releases. About the dotnet tool, maybe at one point we'll have to split them, but for now using `dotnet fable` with the `--lang` parameter should work for experimentation. What do you think @ncave? In any case, distributing `fable-py`, `fable-rust` tools that are just alias of Fable with different language defaults should be fine.

**Comment by ncave** [comment]
@alfonsogarciacaro If you ask me, it's more confusing using different tools that have to be maintained (and supporting different versions multiplied by the number of languages can get old very quick), so my vote is for a single dotnet tool.

**Comment by dbrattli** [comment]
Thanks for clarifying. I will start to align with the alpha-releases ...
