### ISSUE TITLE
Question: One Nuget package that work for .NET and Fable?

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#2953]
Suppose my package `Foo` has these dependencies:

 - `Thoth.Json` (works on Fable)
 - `Thoth.Json.Net` (works on .NET)

Then in my library, I choose the appropriate import:

```fsharp
#if FABLE_COMPILER 
open Thoth.Json
#else
open Thoth.Json.Net
#endif
```

Now, my understanding is that when this is compiled for Nuget, the conditional get resolved to:

```fsharp
open Thoth.Json.Net
```

This does not work on Fable.

To fix this, I can ship two versions of the package `Foo`: 

 - `Foo` (works on Fable)
 - `Foo.Net` (works on .NET)

However, I was wondering if I can make one package that works on both?

Since the source-code is shipped inside the Nuget package I figure this is possible.

**Comment by alfonsogarciacaro** [comment]
Closing for now as in principle nothing needs to be done on Fable's. but please reopen if you find another issue @njlr.

Alson pinging @MangelMaxime in case he has also thought about this possibility in the past.
