### ISSUE TITLE
fsx file as plugin

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#296]
The plugin system is great but it would be even easier if you could reference an .fsx file in the fableconfig.json

```
{
    ....
    "plugins": [ "bin\\plugin1.dll", "plugin2.fsx" ]
    ....
}
```

**Comment by alfonsogarciacaro** [comment]
This has been finally implemented in latest alpha. Could you please give it a try?

**Comment by davidtme** [comment]
this looks to be working, thanks very much 👍
