### ISSUE TITLE
Missing Glyph union case

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#2995]
@alfonsogarciacaro

When building `fable-standalone`:

There seems to be a new `FSharpGlyph.TypeParameter` union case that doesn't have mapping for it in [Interfaces/Glyph](https://github.com/fable-compiler/Fable/blob/main/src/fable-standalone/src/Interfaces.fs#L6).

**Comment by alfonsogarciacaro** [comment]
Thanks for spotting this @ncave! You've made me also realize the bindings for Monaco CompletionItemKind were wrong, I've fixed that too 👍
