### ISSUE TITLE
[Rust] Const and Pointer attributes

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3001]
@alexswan10k

We probably need to add some more attributes to control return types for Rust for wasm interop:
```fs
let bufferLength = 1024
let buffer = Array.zeroCreate<byte> bufferLength

[<OuterAttr("wasm_bindgen")>]
let get_buffer_length () = bufferLength 

[<OuterAttr("wasm_bindgen")>]
let get_buffer_offset () = buffer // <--- I want to somehow make this return `*const u8`
```

What do you think?

**Comment by alexswan10k** [comment]
Can you do this with emit?

**Comment by ncave** [comment]
@alexswan10k I guess we can. The other option is perhaps to implement parts of the [NativePtr](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-nativeinterop-nativeptrmodule.html) module just for that purpose, but that may be unnecessary if we can do simple cases with `Emit`.

**Comment by alexswan10k** [comment]
Agree. I think for now though you can probably do something like this?

```
[<Emit("*$0")>]
let ptrOf x = native

[<OuterAttr("wasm_bindgen")>]
let get_buffer_offset () = ptrOf buffer
```

**Comment by ncave** [comment]
@alexswan10k Right, the problem is not in the body, we can generate anything in the body, it's in the function signature.

**Comment by alexswan10k** [comment]
Oh i see. No, we cannot, this is a good point and something that absolutely needs attention.

I suppose you could write the interop layer bit in Rust for now and plumb in?

**Comment by ncave** [comment]
@alexswan10k Unfortunately we currently erase type abbreviations from the AST (although we can easily add them for Rust if we need to).

But this seems to work:

```fs
let bufferLength = 1024
let buffer = Array.zeroCreate<byte> bufferLength

[<Emit("*const u8")>]
type BufferType = BufferType of byte[]

[<Emit("buffer().as_ptr()")>]
let ptrOf x: BufferType = nativeOnly

[<Rust.OuterAttr("wasm_bindgen")>]
let get_buffer_length () = bufferLength

[<Rust.OuterAttr("wasm_bindgen")>]
let get_buffer_offset (): BufferType = ptrOf buffer
```
Although it requires custom types.
It would be easier if we allow `Emit` on parameter types somehow.

**Comment by alexswan10k** [comment]
Yeah this is an interesting problem. Not sure what the best way forward is but I agree it would be nice to be able to control the function signature somehow directly in one place. I guess this runs the risk of needing to introduce more arbitrary attributes, which might muddy the waters in terms of concepts. I am not against this in principle, I guess it just needs some careful consideration.

**Comment by ncave** [comment]
@alexswan10k I updated the [fable-raytracer](https://github.com/ncave/fable-raytracer) demo with the code above, you can use it as a starting point if you want to experiment. It's pretty straight-forward, the only twist is that for simplicity it shares code base for both `lib` and `bin` targets, so we have both `lib.fs` and `main.fs`. But that's specific to this repo as it also needs to run binaries on different platforms, normal `webasm` projects can be just libraries.

**Comment by alexswan10k** [comment]
This is great. Will have a look, thanks.
