### ISSUE TITLE
Extend rules for StringEnum 

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#302]
Consider the following:

```
 [<StringEnum>]
 type ItemAlignment =
 | [<CompiledName("flex-start")>] FlexStart
 | Center 
 | [<CompiledName("flex-end")>] FlexEnd
 | Strech
```

I think fable should generate these names with - automatically

**Comment by MangelMaxime** [comment]
I think like @forki, as in javascript people tend to use the snake case synthax.

And if we need to do it CamelCase we could used the `CompiledName` attribute.

**Comment by 7sharp9** [comment]
It would be nice if a sigil or similar could be used rather than the longwinded attribute stuff.

**Comment by alfonsogarciacaro** [comment]
I always try to keep a balance between expressiveness and cognitive load. `CompiledName` works like other cases and we shouldn't have to use it that often (especially if we add this rule).

**Comment by tpetricek** [comment]
Another option would be to specify the naming convention in the `StringEnum` attribute:

    [<StringEnum(NamingConvention.SnakeCase)>]
    type ItemAlignment =FlexStart | Center | FlexEnd | Strech

Though I wouldn't want to end up with the beauties of `[<CompilationRepresentationAttribtue(CompilationRepresentationFlags.ModuleSuffix)>]` :see_no_evil:

**Comment by alfonsogarciacaro** [comment]
A bit more of work but I like that the translation rule is explicit in the code :+1:

**Comment by forki** [comment]
Please make snake case the default ;-)

**Comment by rmunn** [comment]
I like being able to explicitly specify the `NamingConvention`, and I also like the idea of having one default naming convention. I do think that lisp-case should be the default for CSS stuff. But please don't use the name "snake case" for the hyphenated naming convention. Almost everywhere, snake_case means underscores, while lisp-case means hyphens. (It's also been called kebab-case and caterpillar-case, and there doesn't yet seem to be convention on what to call it -- but snake_case means underscores just about everywhere).

**Comment by rmunn** [comment]
In case it isn't clear, I agree with @forki that the hyphenated-case should be the default for StringEnum. I'm only disagreeing with calling it "snake case". On the lisp-case vs. kebab-case vs. caterpillar-case, I have a slight preference for "lisp-case", due to my fondness for Clojure (which introduced me to functional programming), but I'd be happy with anything, and a bit of research does suggest that kebab-case is slightly more common than lisp-case as a name for the lowercase-with-hyphens style.

**Comment by alfonsogarciacaro** [comment]
Thanks for the clarification @rmunn, I think you're absolutely right. I've also seen kebab-case more often so I guess to start we can add just two possibilities: `NamingConvention.KebabCase` and `NamingConvention.None` (meaning the case name will be used as is) and later add more if needed. If we don't want to break current bindings (though there're not that many) we should leave the argumentless constructor for `StringEnumAttribute` and then KebabCase should indeed be the default.

**Comment by rmunn** [comment]
I suggest `AsIs` or `Unchanged` rather than`None`, so it doesn't look like an Option case. Other than that, :+1:.

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
