### ISSUE TITLE
Rust - path redirects + default not working with --extension 

### ISSUE THREAD

**Issue by alexswan10k** [fable-compiler/Fable#3031]
It seems when running with or without the extension suffix, the outputted paths for associated modules do not respect the suffix
```
dotnet fable path/to/some/Proj.fsproj --lang rust --extension .test.rs
```

##### Output is
```
#[path = "./shapes.rs"]
mod module_42b5373b;
```

##### Expected
```
#[path = "./shapes.test.rs"]
mod module_42b5373b;
```

This also means the default does not work as expected, because the output files are ```.fs.rs```, but the reference is to ```.rs``` only

##### Tested with
4.0.0-snake-island-alpha-019

### Workaround
You can use --extension .rs

**Comment by ncave** [comment]
@alexswan10k Thanks, I'll take a look.

**Comment by alexswan10k** [comment]
Nice.. Since https://github.com/fable-compiler/Fable/pull/3036 fixes, I will mark this as resolved.

Will test and confirm next time a release goes out and I get a chance to integrate.

Thanks!
