### ISSUE TITLE
Unexpected results for nested options with Option.orElse

### ISSUE THREAD

**Issue by IanManske** [fable-compiler/Fable#3051]
### Description

For nested options (i.e. `Option<Option<_>>`) where the innermost option is `None`, `Option.orElse` does not behave as expected.
Instead of returning the second arguement `option` as is, it is unwrapped and the inner `option` is returned. This occurs because `Option.orElse` is compiled into JS using `defaultArg`.
This same issue exists for `Option.orElseWith`.

### Repo code
[REPL](https://fable.io/repl/#?code=DYUwLgBAhhC8EGUD2BbEEBySB2IBQA9ARAGIDEAXNHIqulrgNwQBSCVM8yaEA3hADcowAK4gqI7ABMQAMwCWuKRAC+EPAAcATorCzsEAERQqAUgCCAGgjyAzt3TxTAI2t2GjiC8PUoAOgBJezpoQNsPPDxQSGcaGAAfAD4IAHkNMHkcPyQtAFFgW3QACgcIEpDDXAEQLUMASjrCYnIykAAPDRAAYzAQKTqqWK4QiKJSMjKoHpFhAYghzBwQZjZBmkkZBSVNHWw9A0NnMysbYJ4nV1OPGm95+bDS5zCIoA&html=Q&css=Q)

### Expected and actual results
Expected:
```fsharp
(Some None) |> Option.orElse (Some (Some "never")) // = Some None
// the expected JS representation is: Some { value: undefined }
```
Actual:
```fsharp
(Some None) |> Option.orElse (Some (Some "never")) // = None
// the actual JS representation: undefined
```
### Related information

* Fable version: 3.7.10 (REPL), also tested on 3.7.17

**Comment by alfonsogarciacaro** [comment]
Closed by #3052, will release a version with the fix soon.
