### ISSUE TITLE
Unexpected compilation results on anonymous function parameters

### ISSUE THREAD

**Issue by napretep** [fable-compiler/Fable#3066]
### Description

If you run the following code, you will get unexpected compilation results on parameters

### Repro code

```F#
module app.test
open Fable.Core
open Fable.Core.JS

type [<AllowNullLiteral>] BaseEvent<'T> =
    abstract addListener: callback: 'T  -> unit
type [<AllowNullLiteral>] Event<'T> =
    inherit BaseEvent<'T>
    abstract addListener: callback: 'T -> unit   
type [<AllowNullLiteral>] ExtensionMessageEvent =
    inherit Event<((obj option *  int option *  (obj -> unit) option ) -> unit)>

type [<AllowNullLiteral>] IExports =
    abstract onMessage: ExtensionMessageEvent

let jsObj:IExports = jsNative

jsObj.onMessage.addListener(fun (msg,senderid,callback)->(
        console.log($"msg={string msg}, sender={string senderid}")
 ))
```

[check on repl](https://fable.io/repl/#?code=LYewJgrgNgpgBAQwA5IHQBcYGd0CgRIwB2cAYggEayoDCIATjPoSeVTLQxwFIDKuudAE9CcANoAeAIJQoIAO4A5aFAAyAS0z0EUAHwBdOACEEWGAFEAbsXQSA5ABVdcALy44HxBRzaAxukQwMA0cYhh6AC44Xx0oCgRfAGsoxw8AWmcIIk1BEXhJGTklFQ0tHQM4Kxt7J1d3T3UiAAtwzWNTC2siW0ddeo9KHwSAhCCQzCJwqJjZeKSUhzgMuCy2j1zRAtkFZVlS8PLDcwAPCax1ECIAWWwsBABzTps6zzhGlvo2qu6JAApfkAUABWcAI6AuJAAVB5GgEwRC4NC4ADgUtMtl0ABKUFIcGXODY5arLF9Db5aTbYp7TQHPSGACSJyQDHQWBenkG6D8cOutweMCiJzOEJuWDuj2+eFwsACQKwAHlgRFGcdmfRWa44HLFAhwdYBHLFUDUJdReKOKNgupQpN6L8AGZZZHALD3AA0ZiIYFaYDdMziCUSmIyv36r2ilywIGocnuvwAJAAiF33FwAbx8jXucBTAF83XBPd76OnM0Rs0WfbnE5j3JjMUA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q)

### Expected and actual results

expected:
```javascript
import { toString } from "fable-library/Types.js";
import { some } from "fable-library/Option.js";

export const jsObj = (() => {
    throw (new Error("A function supposed to be replaced by native code has been called, please check."));
})();

jsObj.onMessage.addListener(() => {
    const msg = arguments[0];
    const senderid = arguments[1];
    const callback = arguments[2];
    console.log(some(`msg=${toString(msg)}, sender=${toString(senderid)}`));
});
```

or
```javascript
jsObj.onMessage.addListener((...tupledArg) => {
    const msg = tupledArg[0];
    const senderid = tupledArg[1];
    const callback = tupledArg[2];
    console.log(some(`msg=${toString(msg)}, sender=${toString(senderid)}`));
});
```

actual
```javascript
import { toString } from "fable-library/Types.js";
import { some } from "fable-library/Option.js";

export const jsObj = (() => {
    throw (new Error("A function supposed to be replaced by native code has been called, please check."));
})();

jsObj.onMessage.addListener((tupledArg) => {
    const msg = tupledArg[0];
    const senderid = tupledArg[1];
    const callback = tupledArg[2];
    console.log(some(`msg=${toString(msg)}, sender=${toString(senderid)}`));
});
```
The result of the compilation is to treat the first argument `msg` as an object with subscripts and to access its 0th, 1st and 2nd members, thus it ignores the remaining two parameters `senderid` and `callback`
### Related information

* Fable version: 3.7.10
* Operating system: https://fable.io/repl

**Comment by inosik** [comment]
In interop-scenarios, it's better to use delegates instead of an F# functions. Doing this change should work:

``` diff
 type [<AllowNullLiteral>] ExtensionMessageEvent =
-    inherit Event<((obj option *  int option *  (obj -> unit) option ) -> unit)>
+    inherit Event<System.Action<obj option, int option, (obj -> unit) option>>
```

**Comment by napretep** [comment]
> In interop-scenarios, it's better to use delegates instead of F# functions. Doing this change should work:
> 
> ```diff
>  type [<AllowNullLiteral>] ExtensionMessageEvent =
> -    inherit Event<((obj option *  int option *  (obj -> unit) option ) -> unit)>
> +    inherit Event<System.Action<obj option, int option, (obj -> unit) option>>
> ```

still the same
[here to see code](https://fable.io/repl/#?code=LYewJgrgNgpgBAQwA5IHQBcYGd0CgRIwB2cAYggEayoDCIATjPoSeVTLQxwFIDKu6AJ6EyEIgGN0ASxAkAvHF6CcMYKgCCkmUQHD4AbQA86qFBAB3AHLQoAGSmZ6CKAD4AunABCCLDACiAG7E6IYA5AAqLnByuHBxiBQ4TpKIYGD2KkQw9ABccOLOUBQI4gDWeRFxALRRYg66IkYmZlY29o7O7nCBwWGR0bHxUkQAFtkOXj7+QUQhES6DcZRJJeip6VKZ2XkFpsVlFeFwNXB1a3ENBsamFtam7dmdHn4AHphEWNoAsthYCADm02CA3icAA9GC4MMxvQJj1ZoYABSIkAUABWcAI0lkcAAVHFhmssdo8XEUejjrUiA4AJSYpDYkh0k5nGkLUHQ8ZreEhJQqNSaRmGQlxfFQ2aismojEs6noNkLISNa4tO52ByPVweACSryQDHQWBB8WW6GSRKIPywf0BeVe70+sitNqBs1wuFgazRWAA8uicrqXvr6IbonBvZYENIgh6YGsAGZwRHALD-HKEgA0viIYHGYHTswzuyKJXK0pqrLD4lkWBA1DM-0RABIAEQp-5yADeSWG-zg7YAvhm4Nnc-Quz2iH3R3mBy2aYtQXB3bhvX60agnb8ARwEGkMu9soisuZFMpMAKtLJDAB9FyI+N0mlAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwt4wFagwJgAIw5ohWHMAkouDFLslRfXVYGOiQAd3EwujQwEFYAFgAGRPEQJDoAc3AE5MtrT29fKyUnF3hEFUhYOCA&css=Q)

**Comment by inosik** [comment]
You're still passing the args as a tuple. Note this difference:

```
Mine:  Event<System.Action<obj option, int option, (obj -> unit) option>>
Yours: Event<System.Action<int  *  int  *  (obj -> unit)>>
```
