### ISSUE TITLE
Error in compilation with type inheritance

### ISSUE THREAD

**Issue by francotiveron** [fable-compiler/Fable#3076]
### Description

Inheritance compilation seems to have an issue in this case

### Repro code

```
type A(p1: string, p2: string list) =
    new(p1: string) = A(p1, [])
    member __.P2 = p2

type B(p1: string) =
    inherit A(p1)

type C(p1: string) =
    inherit A(p1, [])

let b1 = B("Test")
let a1 = (b1.P2 = [])

let b2 = C("Test")
let a2 = (b2.P2 = [])
```

### Expected and actual results

Expected results: both a1 and a2 are true
Actual results: a1 = false

When instantiating B, the primary constructor of A is called directly with p2 = undefined
Note: running the code in F# interactive, a1 = true as expected

### Related information

* Fable version: 3.7.16
* Operating system: W10Pro

**Comment by alfonsogarciacaro** [comment]
Hi @francotiveron! This is unfortunately a limitation of Fable. To support inheriting from secondary constructor we would need to do a workaround and avoid JS classes which brings a performance penalty, so we decided against it. You should get a warning as follows when compiling the code above.

![image](https://user-images.githubusercontent.com/8275461/184811024-f26350e8-6377-4010-9f8b-e7abcefba8f7.png)

**Comment by francotiveron** [comment]
Gotcha. No warning. though.

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately the code is only highlighted in the REPL and not in other IDEs. You should see the warning in Fable logs in the terminal though, but sometimes it gets buried among other logs. If necessary, we can make it an error so you know for sure the compilation has failed.
