### ISSUE TITLE
When I turn on both fable and vite watch mode, there is a chance that vite's watcher will crash.

### ISSUE THREAD

**Issue by napretep** [fable-compiler/Fable#3104]
### Description

I use watch mode of fable to hot compile the fs code to js code , and use vite to bind the compiled js code with jslib code together and vite's watch mode to hmr the bundle code, but when I turn on both fable and vite watch mode, there is a chance that vite's watcher will crash by the compile error reporting from fable.

I use these two commands to run my project :
1. `dotnet fable watch src/fscode/app.fsproj  -o src/jscode --run vite`
2. first run `dotnet fable watch src/fscode/app.fsproj  -o src/jscode`  then in another terminal to run `vite`

They both trigger the crash.

how to avoid the conflict?

### Repro code
For example, when fable compiling failed and report an error:
```
(60,29) error FSHARP: The type 'style' does not define the  field, constructor or member 'filter'. Maybe you want one of the following:
   fill (code 39)

```
It causes Vite's watcher to stop working and report the following error:
```
node:events:368
      throw er; // Unhandled 'error' event
      ^

Error: EBUSY: resource busy or locked, lstat 'D:\DumpStack.log.tmp'
Emitted 'error' event on FSWatcher instance at:
    at FSWatcher._handleError (file:///D:/workshop/chrome%20extension/scapp2/node_modules/rollup/dist/es/shared/watch.js:4
397:10)
    at ReaddirpStream.NodeFsHandler$1._boundHandleError (file:///D:/workshop/chrome%20extension/scapp2/node_modules/rollup
/dist/es/shared/watch.js:2873:43)
    at ReaddirpStream.emit (node:events:390:28)
    at emitErrorNT (node:internal/streams/destroy:157:8)
    at emitErrorCloseNT (node:internal/streams/destroy:122:3)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
  errno: -4082,
  code: 'EBUSY',
  syscall: 'lstat',
  path: 'D:\\DumpStack.log.tmp'
}
```

### Expected and actual results

Expected results should be when fable compiles failed , vite still working right.

### Related information

* Fable version: `dotnet fable --version`
* Operating system

**Comment by alfonsogarciacaro** [comment]
This is strange, I use Fable with Vite every day and I have never seen this error. Could you please give us more information? Versions of Fable and Vite, contents of `D:\\DumpStack.log.tmp` and some particularities of your system (example, I assume you're on Windows but are you using WSL or a network disk to run Fable?)

**Comment by napretep** [comment]
I figure out that the problem comes from Vite itself, even though I don't run the Fable watch mode , Vite still may crash.
thank you for your help.

**Comment by alfonsogarciacaro** [comment]
Thanks for confirming @napretep! It's always a relief when we're not the ones causing the problem 😅
