### ISSUE TITLE
Should we add a notification system to fable-compiler ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#311]
### Description

I started thinking that a notification system included in the fable-compiler could be a good feature.
The notification will be shown only on key steps like:
-   Watch started
-   Build finish (with or without error)

The notification would be an additional args to the command line to enable it like: `fable -w --notify`

I am finding it to be a better experience than just having the console output. 

What do you think about this idea ?

**Comment by alfonsogarciacaro** [comment]
What was the npm package you were thinking to use for this? In principle it'd be a very nice opt-in feature to have, I'm just concerned about adding heavy dependencies for something that not everybody will be using.

**Comment by MangelMaxime** [comment]
I was thinking about [Node-notifier](https://github.com/mikaelbr/node-notifier) which seems to work fine on the 3 OS.

And yes I agree with you about the heavy dependencies. I don't know if we should find a way to extend fable-compiler without adding thing to it's core. 
Like plugins etc. But not sure if it's a better idea because I don't find a lot of case where that could be usefull.

**Comment by alfonsogarciacaro** [comment]
I'm thinking that maybe it's easier to just call Fable from a FAKE script (as it's done [here](https://github.com/TheAngryByrd/Fable/blob/suave-backend-sample/samples/browser/suave-backend/build.fsx#L112)) and trigger the notification whenever a line like `Compiled ...` is received from the Fable process. What do you think?

**Comment by MangelMaxime** [comment]
Yes, that can be a good solution as it add no modifications to fable compiler.

So the target for this functionality will be for people experienced with FAKE or really wanted to make a better workflow. As it's harder than just passing an arguments to the command line.

But it's seems that there not so much need for it so could be a good choice. We probably should provide a sample script for it. (I have no idea of the moment of how to do it :) )

**Comment by alfonsogarciacaro** [comment]
Ok, I'll try to write something. About the complication of using a FAKE script, we could write a node wrapper to emulate most of Fable functionality, but I'm not sure it's worth it because I think the need of notifications will be limited to very specific scenarios (I might be wrong). As you want the notifications to avoid having to display the terminal windows, using a FAKE script will also have the nice effect of automatic integration with VS Code 😄

**Comment by MangelMaxime** [comment]
Yes that sure :). Thanks.

**Comment by alfonsogarciacaro** [comment]
Closing the issue for now, please feel free to reopen... or better yet, send a PR ;)
