### ISSUE TITLE
AST - not enough information in LibraryImport

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3110]
In some cases I want to know if a `LibraryImport` is a module member, or a static member import.
Can this information be added before we lock down the AST?
I know it's not important in the JS case, cause everyting gets rendered as a module function, but it is important for other languages where calling conventions may be are different.
```fs
type ImportKind =
   | UserImport of isInline: bool
   | LibraryImport
   | MemberImport of isInstance: bool * fullPath: string
   | ClassImport of fullPath: string
```

**Comment by alfonsogarciacaro** [comment]
I added the isInstance fields before the MemberRef refactor. Maybe it makes sense to use MemberRef for imports too? This way you can get more information if needed (although currently this is usually available from the CallInfo anyways). In that case, I guess for library imports we should probably use generated members, which may be a bit cumbersome, but we're using helpers in Replacements anyways so hopefully it doesn't require too many code changes.

Of course, if you had any other structure in mind, please let me know.

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, makes sense to add `MemberRef` and  `EntityRef` for imports.
And perhaps simplify `ImportKind` to drop `isInstance`, and make `isLibrary` a property instead?
Is the `fullPath` still needed if we have `MemberRef/EntityRef?

**Comment by alfonsogarciacaro** [comment]
Ok, I'll check how this can be done without too many changes in the code 👍 Probably we can remove `fullPath` as you say. IIRC this was added for PHP but we may need to remove the language before the release as it's currently not maintained. I'm trying to keep it compilable with the AST changes, but it seems it's not actually working (at least it didn't with repl4).
