### ISSUE TITLE
How to import react component download from npm?

### ISSUE THREAD

**Issue by napretep** [fable-compiler/Fable#3115]
### Description

I installed a react component from npm, and tried some method to import it into my fsharp code file.
but all methods are failed , can anyone help me?

### Repro code
these codes  produce a return null function in js
```fsharp
type reactComponent =
  [<ReactComponent(import = "Draggable", from = "../../node_modules/react-draggable/cjs/Draggable.js")>]
  static member Draggable () = React.imported ()
```

or
```fsharp
type reactComponent =
  [<ReactComponent(import = "Draggable", from = "react-draggable")>]
  static member Draggable () = React.imported ()
```
they all produce return null function
```javascript

export function reactComponent_Draggable() {
    return null;
}
```
if I use`[<import>]`, it's js version just disapeared
```fsharp
  [<Import( "Draggable",from="react-draggable")>]
  static member Draggable () =jsNative
```
nothing happen in js file
### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `dotnet fable --version`
* Operating system

**Comment by napretep** [comment]
I solved it by
https://github.com/fable-compiler/fable-react/blob/master/docs/using-third-party-react-components.md

**Comment by alfonsogarciacaro** [comment]
Great you managed to solve it @napretep! If you still want to use the Feliz-style I think the following should work. Looking at Draggable's documentation it looks you need a default import, so:

```fsharp
open Feliz

// You can add more arguments to the function as needed,
// you can also make the arguments optional

type reactComponent =
  [<ReactComponent(import = "default", from = "react-draggable")>]
  static member Draggable (axis: string, handle: string, ?allowAnyClick: bool) = React.imported ()
```

Don't worry about the generated function, that's just a dummy function that won't be actually called and will be removed when tree shaking your bundle. The important thing is when calling `reactComponent.Draggable("x", ".handle")` the Feliz plugin will automatically invoke the imported React component 👍
