### ISSUE TITLE
fable.io/repl does not work - shows 404

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#3127]
Not apparent from existing issues if anyone is aware or looking at it.

**Comment by MangelMaxime** [comment]
Hum, for me it seems accessible at  [https://fable.io/repl/](https://fable.io/repl/).

Perhaps this is temporary or regional issue.

Can you try clearing your cache just in case? Not sure if a cache issue can cause a 404.

**Comment by et1975** [comment]
![image](https://user-images.githubusercontent.com/623703/187692937-2422ac1c-7e05-4f1e-bc2b-5ba09a7649e7.png)

**Comment by MangelMaxime** [comment]
Hum indeed, you are not getting the same url as I am:

![image](https://user-images.githubusercontent.com/4760796/187694144-8ecef673-e773-41ac-925b-05241cb57e11.png)

And looking at the index file from gh-pages, I don't know why it is requesting that `.js` file this is not the one set for the `index.html`

```html
<!doctype html><html><head><title>Fable REPL</title><meta http-equiv="X-UA-Compatible" content="IE=edge"/><meta http-equiv="Content-Type" content="text/html;charset=utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><link rel="shortcut icon" href="img/fable.ico"><link href="app.css" rel="stylesheet"></head><body><div id="app-container"></div><script>if(window.navigator && navigator.serviceWorker) {
  navigator.serviceWorker.getRegistrations().then(function(registrations) {
    for(let registration of registrations) {
      registration.unregister();
    }
  });
}</script><script src="app.2c596ad09f19db5ab08e.js"></script></body></html>
```

[Source](https://github.com/fable-compiler/repl/blob/3f13c8700b9ddaa87febaae6fb3143eed6f0cc7c/index.html)

**Comment by alfonsogarciacaro** [comment]
@et1975 The service worker gave us issues and we removed it. If you haven't visited the repl in a while maybe your browser still has the old worker. You may need to unregister it manually, sorry for that!

![image](https://user-images.githubusercontent.com/8275461/187719198-65394cb8-09db-40a5-84bb-5be1e5000341.png)

BTW, we're experimenting with the new REPL (which can compile to Python, Rust and Dart too) in fable.io/repl4 so you can try that one too. It should replace the current repl in the next days anyways.

**Comment by et1975** [comment]
Had to clear this cache ,now it works:
![image](https://user-images.githubusercontent.com/623703/187729800-74bd284d-b403-4315-b2bb-7b38cda0d40c.png)
