### ISSUE TITLE
Python imports broken on 4.0.0-theta-003

### ISSUE THREAD

**Issue by teknikal-wizard** [fable-compiler/Fable#3168]
I just updated to try continuing with the TensorFlow binding I am working on as Dag was good enough to fix a [bug](https://github.com/fable-compiler/Fable.Python/issues/70) I found. However now the ability to import libraries is broken altogether.

There is an example [here](https://github.com/CompositionalIT/Python-TensorFlow-binding-example) of the simple binding I am working on.

Previously 
```fsharp
[<ImportAll("tensorflow")>]
let tensorflow: obj = nativeOnly
``` 
used to generate
```python
import tensorflow
```

but now generates
```python
def _arrow0(__unit: Literal[None]=None) -> Any:
    raise 1

tensorflow: Any = _arrow0()
```

which generates the error
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
g:\Git Repos\C\CompositionalIT\Python TensorFlow\fable 4 python example.py in <cell line: 67>()
     [63](file:///g%3A/Git%20Repos/C/CompositionalIT/Python%20TensorFlow/fable%204%20python%20example.py?line=62) def _arrow0(__unit: Literal[None]=None) -> Any:
     [64](file:///g%3A/Git%20Repos/C/CompositionalIT/Python%20TensorFlow/fable%204%20python%20example.py?line=63)     raise 1
---> [67](file:///g%3A/Git%20Repos/C/CompositionalIT/Python%20TensorFlow/fable%204%20python%20example.py?line=66) tensorflow: Any = _arrow0()

g:\Git Repos\C\CompositionalIT\Python TensorFlow\fable 4 python example.py in _arrow0(__unit)
     [63](file:///g%3A/Git%20Repos/C/CompositionalIT/Python%20TensorFlow/fable%204%20python%20example.py?line=62) def _arrow0(__unit: Literal[None]=None) -> Any:
---> [64](file:///g%3A/Git%20Repos/C/CompositionalIT/Python%20TensorFlow/fable%204%20python%20example.py?line=63)     raise 1

TypeError: exceptions must derive from BaseException
```

**Comment by dbrattli** [comment]
This is strange. I cannot reproduce. I've cloned the project, but it compiles fine on both Mac and Windows. 
Are you perhaps missing `open Fable.Core`  in your current code?

**Comment by dbrattli** [comment]
PS: Also update the nuget Fable.Core to `4.0.0-theta-001` when using `fable`tool `4.0.0-theta-003`

**Comment by teknikal-wizard** [comment]
Ah, I had set both Fable Core and the tool to theta 003, that's probably the issue!

**Comment by teknikal-wizard** [comment]
Yep all fixed, thank you

**Comment by dbrattli** [comment]
Great. It can be confusing that they are versioned separately. Perhaps we should use wildcards in the examples

**Comment by teknikal-wizard** [comment]
I think you do suggest a wildcard for the tool, I should have done the same for the nuget ref.
