### ISSUE TITLE
ITypeResolver not working in Fable.Remoting with Fable 4

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#3177]
### Description

Resolver is no longer getting injected with `[<Inject>] ?resolver: ITypeResolver<'t>`.

### Repro code

- Clone https://github.com/Zaid-Ajaj/Fable.Remoting
- dotnet tool restore
- dotnet run --project .\build\Build.fsproj IntegrationTestsNagareyamaLive
- Navigate to 127.0.0.1:5000/index.html - you should see tests passing
- dotnet tool update fable --prerelease
- dotnet fable clean
- dotnet run --project .\build\Build.fsproj IntegrationTestsNagareyamaLive
- Navigate to 127.0.0.1:5000/index.html - the page is blank and `Uncaught Error: Option has no value` is printed in the console

The error occurs here https://github.com/Zaid-Ajaj/Fable.Remoting/blob/112dd4b702c8f20fbed286c5a570cef8defb3a26/Fable.Remoting.ClientV2/Remoting.fs#L45-L47

### Related information

* Fable version: 3.6.3, 4.0.0-theta-004
* Win 10

**Comment by dbrattli** [comment]
This should be relevant: https://github.com/fable-compiler/Fable/issues/2713

**Comment by kerams** [comment]
I see, `ITypeResolver` is a goner in Fable.Core v4. What's the upgrade path here then?

**Comment by kerams** [comment]
Apparently using

```fsharp
    static member inline buildProxy<'t>(options: RemoteBuilderOptions) : 't =
        let resolvedType = typeof<'t>
```

works with v3 and v4 compiler. Maybe we switch to this, @Zaid-Ajaj?

**Comment by alfonsogarciacaro** [comment]
Oh, I thought `ITypeResolver` was only being used by Thoth.Json. Sorry for that! Yes, inlining works. I actually removed `Inject` during the refactoring for Fable 4 because inlining is already a solution compatible with standard F# and which doesn't require extra Fable magic.

**Comment by alfonsogarciacaro** [comment]
BTW, thanks a lot for your help to upgrade packages for Fable 4 @kerams!
