### ISSUE TITLE
Publish fable-library as npm package

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#3206]
@MangelMaxime @nojaf @kunjee17

Continuing [discussion started in Twitter](https://twitter.com/alfonsogcnunez/status/1574396828627320832). Thanks to @ncave Typescript compilation is making great progress so there's an opportunity to make the experience of creating npm packages with Fable better. The main challenge will likely be versioning.

**Comment by nojaf** [comment]
Hello, thank you for considering this.

It would be nice if we could pass some flag to fable so that is outputs

```js
import { Record, Union } from "fable-library/Types";
```
instead of
```js
import { Record, Union } from "./fable_modules/fable-library.3.7.18/Types.js";
```

Installing `fable-library` would be up to the user.
And the version needs to match with what `dotnet fable --version` outputs.

You could prefix every npm version with `prerelease-` (for example `prerelease-3.7.18`) to indicate that nothing will respect `semver` at any point.

That would serve my use case with Perla/Skypack, but I'm open for alternatives as well.

**Comment by nojaf** [comment]
Hello @alfonsogarciacaro, any further thoughts on this?

**Comment by alfonsogarciacaro** [comment]
@ncave has already managed to compile fable-library to TypeScript, so it's a good opportunity to publish it with the .d.ts declarations. @dbrattli is also interested in publishing the Python version of fable-library as a package, so it'd be nice to agree on a common approach.

Although I was concerned at first about versioning, I'm thinking now that we should try to conform to semver. This is because, at least for JS, fable-library has been quite stable for several months so with some care it should be possible to avoid breaking changes. Also, if the version cannot float in a range, the benefit of publishing as a package is diminished. Say there are two libraries A and B compiled with different versions of Fable: if they cannot share the library, npm will install multiple versions (same as when we just embed the files).

Please note that it's already possible to customize the location of fable-library using the `--fableLib` CLI argument. But if we want to make it more systematic I think this is the TODO list:

- [Keep the version](https://github.com/fable-compiler/Fable/blob/d56e92e05cec399acfd1ed0f67fd2e50ba617295/src/Fable.Transforms/Global/Compiler.fs#L4) of the fable-library the tool currently can depend on.
- Use a keyword in combination with `--fableLib` argument so users can decide to have fable-library as a dependency instead of embedding the files. This is already implemented for Python, see #3023.
- Actually enforcing that the proper version is installed with npm, pip, etc is difficult (we would have to implement Femto within Fable). But at least we can display a message like: "Please install fable-library >= 4.2.1"
- When publishing a new version of Fable tool, we should somehow check the files for fable-library have not changed. If they have, publishing should be interrupted until a new version of the library is published.
- Not sure if there's a tool that can automatically detect if an npm/pip package has breaking changes, but if there are breaking changes in any case, we should bump the major version of the library (it doesn't need to be the same as the Fable tool).

**Comment by MangelMaxime** [comment]
> This is because, at least for JS, fable-library has been quite stable for several months so with some care it should be possible to avoid breaking changes.

@alfonsogarciacaro Wasn't one of the problem we had with publishing fable-library the mangled code?

Like depending on the version of Fable, the same code would compile to a different function name?

Pseudo code (this is just to show what I am speaking about)

```js
// Fable 3.1.1
export function Dummy__Hello(_) {
    return "";
}

export function Dummy__Hello_Z721C83C5(_, name) {
    return "";
}

// Fable 3.1.2
export function Dummy__Hello(_) {
    return "";
}

export function Dummy__Hello_AAAAAAAAA(_, name) {
    return "";
}
```

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Yes, we need to be careful with this as well. If name mangling changes, we should bump the fable-library major version too. But luckily name mangling has also been quite stable for a while, so hopefully we can cope with that too.

**Comment by alfonsogarciacaro** [comment]
fable-library has already been pushed to npm. More info here: https://fable.io/blog/2023/2023-04-20-Better_Typed_than_Sorry.html#compilation-options

**Comment by nojaf** [comment]
Many thanks for this @alfonsogarciacaro!
