### ISSUE TITLE
Updating fable-library in fable_modules for non-JS languages

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#3208]
When creating `fable_modules` folder, if there's already a package subfolder (including fable-library) Fable doesn't overwrite. This is important for packages other than fable-library so Fable doesn't need to recompile them. It works well because packages include the version number with the name so the folders are idempotent. However, it seems for new languages we are not including the version for fable-library: https://github.com/fable-compiler/Fable/blob/ce39614d6790be8e85e147f8d259a1d3ef2bf0e0/src/Fable.Cli/ProjectCracker.fs#L509-L516

@dbrattli @ncave I had problems with this when updating Fable in a Rust sample. How should we fix it, should we include the version in other languages as well as in JS, or just always overwrite `fable_modules/fable-library`?

**Comment by dbrattli** [comment]
@alfonsogarciacaro Yes, it's not normal to include version numbers in Python module names, but I see the problem of not having it. Several times I have experienced the fable-library to be old and I get strange errors that are difficult to understand. Perhaps we should just overwrite.

**Comment by alfonsogarciacaro** [comment]
The process is a bit complicated now since the cache optimizations in 3.7 (e.g. if compiler options and version haven't changed Fable won't touch the fable_modules folder at all), but anyways I set Fable to always overwrite fable-library when updating the fable_modules. Hopefully this should solve the issue 👍
