### ISSUE TITLE
New Fable search site missing Fable packages

### ISSUE THREAD

**Issue by JordanMarr** [fable-compiler/Fable#3221]
### Description

Some Fable packages that exist on NuGet do not show up on the new [Fable Packages search site](https://fable.io/packages/).

For example:
* Fable.Store
* Fable.FluentUI

I stopped there, but there are probably others.

**Comment by MangelMaxime** [comment]
Hello @JordanMarr,

In order for a package to be listed on the website it needs at minimum the tag "`fable`".

To support advance search, it needs additional tags. You can find the [documentation here](https://fable.io/docs/your-fable-project/author-a-fable-library.html#make-your-package-discoverable).

**Comment by dbrattli** [comment]
I think this is really cool! Thanks for making this @MangelMaxime ❤️  Finally there's a way to find the [Fable Python](https://fable.io/packages/#/search?dotnet=false&javascript=false&rust=false&python=false&dart=false&all=false&bindings=false&libraries=false&sortBy=relevance&includePrerelease=true&query=python) packages.
