### ISSUE TITLE
[JSX] Type & Import name clashing

### ISSUE THREAD

**Issue by delneg** [fable-compiler/Fable#3237]
### Description

While using JSX, resulting import shadowed the type from another file being imported which resulted in 
"Uncaught TypeError: class constructors must be invoked with 'new'"

### Repro code
https://github.com/Bearle/django_private_chat2/commit/e2c455fcce66904fe3f472fdbe0fce7901803fc9

This commit fixes the problem

### Related information
Fable: 4.0.0-theta-011
Fable.Core: 4.0.0-theta-006
Feliz: 2.0.0-prerelease-003
Fable.React.UseElmish: 1.0.0-beta-001

@alfonsogarciacaro

**Comment by alfonsogarciacaro** [comment]
Yes, unfortunately this can be an issue. Maybe we can try to raise a warning if we detect that an import from JSX (or any other emitted JS) conflicts with any other identifier in the file scope.
