### ISSUE TITLE
Fable 4 cannot recognize generic property type parameter, when it is not declared on the property explicitly

### ISSUE THREAD

**Issue by ArtemyB** [fable-compiler/Fable#3248]
### Description

When a type has a property with implicit generic type parameter, Fable 4 reports an error `type parameter is not defined`. However F# compiler and Fable 3 handles compilation successfully.

### Repro code

Example code:

```fsharp
type Example1 =
    abstract implicitlyGenericProperty1 : 't with get, set
    abstract implicitlyGenericProperty2 : ('t -> string) with get, set
    abstract explicitlyGenericProperty1<'t> : 't with get, set
    abstract explicitlyGenericProperty2<'t> : ('t -> string) with get, set
    abstract implicitlyGenericMethod : 't -> string
    abstract explicitlyGenericMethod<'t> : 't -> string
```
![REPL example screenshot](https://user-images.githubusercontent.com/8839749/199027979-127ba04a-94a7-453a-b467-652ed747bf55.png)

[REPL link](https://fable.io/repl/#?code=C4TwDgpgBAogHgQwLZgDYQIxQLwFgBQURUCARgM7ABOCAxsFAJYqqO2PCogDiEAdhCpsAClQD2kKqCwAuKAHIGAdw4ALKAHMIwADRRy2gsRIVqdBszRsOXXgKG1REwaABMUOQApFUALQA+fWpGPg0ASigVYHUtXX1DQmIyShp6KAg4K3ZOHn5BEXFJaQAeRUC5HyiY7T0DYCMk01SGDKybXPsC5ykQV1LgcqhvBgCgoVCIqs0a+PrEomSzNMtWbNs8hwBZbVUxABMKkcCUkI0GhabzdMzV9rt82m3o-f7Bn1GT0IIgA&html=Q&css=Q)

### Expected and actual results

In the example above the members `implicitlyGenericProperty1` and `implicitlyGenericProperty2` provokes the error while the other slightly different members doesn't. The expected behavior is to have the whole code being compiled successfully as it happens with regular F# compiler and Fable 3.

### Related information

* Fable version: at least 4.0.0-theta-008, 4.0.0-theta-012, 4.0.0-theta-014
* Operating system: Windows 10 21H1

**Comment by kerams** [comment]
https://github.com/dotnet/fsharp/issues/12198
https://github.com/fable-compiler/fable-browser/pull/79

This is no longer allowed as it didn't make sense in the first place.

**Comment by ArtemyB** [comment]
@kerams so that's me who is wrong, not Fable 4 - what a twist 🤔 And just because the issue has been fixed quite recently, I don't see the error in environments other than Fable 4 as I understand. So the problem relates only to inferred property parameters -- there is nothing wrong with explicitly set generic property parameters or inferred (implicit) generic method parameters, am I right?

**Comment by kerams** [comment]
Properties may not be generic.

> I don't see the error in environments other than Fable 4

Fable 4 is using the bleeding edge version of FCS, so it includes the recent fix which prohibits generic properties.

**Comment by ArtemyB** [comment]
> Properties may not be generic.
Then `abstract explicitlyGenericProperty1<'t> : 't with get, set` in my example should produce the error too. However it doesn't now, and I've even used that in my Fable code as a fix of the issue.

**Comment by kerams** [comment]
Hmm, I don't know. That should not work either in my opinion. It's basically the same thing.

Doesn't work

```csharp
interface X
{
   public T GetT<T> { get; }
}
```

Works with a class-level generic type

```csharp
interface X<T>
{
   public T GetT { get; }
}
```

@vzarytovskii, thoughts?

**Comment by kerams** [comment]
Yeah, explicit type parameters are definitely wrong too. Just try it with `get` only. I've submitted a PR forbidding this use case too.

**Comment by ArtemyB** [comment]
Got it, @kerams, thank you for the clarification. Most likely I wouldn't have discovered the true origin of the issue by myself any time soon 👍 Seems like now it can be closed.
