### ISSUE TITLE
Broken codegen for parseInt

### ISSUE THREAD

**Issue by nneeoo** [fable-compiler/Fable#3249]
### Description

Current codegen does not allow to use radix.

### Repro code

[REPL](https://fable.io/repl/#?code=LYewJgrgNgpgBASQAoEExgE4wM7YLABQhIADjAHZwDKAntgC4zCHFmUBiAhgEawB0AYRBY+AKWwJyjDKVYU4XXjEHDloqiyIFY9OCABmVehgCW5AOZwAHnAC8cEpwzYYk3TYCMANiA&html=Q&css=Q).

### Expected and actual results

Expected codegen:
```
export function Byte_ofString(x) {
    return parseInt(x, 16);
}
```

Actual codegen:

```
export function Byte_ofString(x) {
    return parseInt(x)(16);
}
```

**Comment by inosik** [comment]
Probably has to do with currying/uncurrying. Still reproducable in Fable 4.

``` fsharp
open Fable.Core

// Same as default Fable bindings
[<Global "parseInt">]
let parseInt : string -> int -> int = jsNative

[<Global "parseInt">]
let parseInt' (string: string) (radix: int) : int = jsNative

let x = parseInt "ff" 16
let y = parseInt' "ff" 16
```

@nneeoo You can work around this for now by redefining `parseInt`, as seen above.
