### ISSUE TITLE
ts2fable - Parse Documentation Comments from `d.ts` Declaration Files

### ISSUE THREAD

**Issue by cloudRoutine** [fable-compiler/Fable#325]
Currently the documentation comments aren't being parsed from the typescript definition files and added/transferred to the generated Fable F# interfaces. The lack of this information has definitely been a major source of friction when starting to work with an unfamiliar API. 

I think supporting this functionality will net high usability gains for a modest amount of effort.

**Comment by alfonsogarciacaro** [comment]
Continued on https://github.com/fable-compiler/ts2fable/issues/6
