### ISSUE TITLE
Exception of type 'FSharp.Compiler.CompileOps+FileNameNotResolved' was thrown

### ISSUE THREAD

**Issue by UnoSD** [fable-compiler/Fable#3262]
### Description

New Fable project from template does not compile.

```
  ./src/Temp.fsproj 39 bytes [built] [code generated] [1 error]

ERROR in ./src/Temp.fsproj
Module build failed (from ./node_modules/fable-loader/index.js):
Error: Exception of type 'FSharp.Compiler.CompileOps+FileNameNotResolved' was thrown.
    at /home/uno/Temp/node_modules/fable-loader/index.js:98:22
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
```

### Repro code

```
dotnet new fable-elmish-react -n Temp
cd Temp/
npm install
DOTNET_SYSTEM_GLOBALIZATION_INVARIANT=1 npm start
```

### Expected and actual results

Expected to compile, actual result is the error above.

### Related information

```
dotnet --version
7.0.100
npm --version
8.19.2
dotnet fable --version
3.7.20
```

Running on Arch Linux with dotnet installed from manual script.

Same issue here: https://github.com/nojaf/fable-reactstrap/issues/2

Thank you

**Comment by nojaf** [comment]
Hi, I'm not sure if Fable already supports the dotnet 7 SDK. You could try and use net6 SDK via a global json instead.

**Comment by UnoSD** [comment]
thank you, @nojaf. that improved the situation a bit. now I get a different error (still vanilla new template):

```
Error: error:0308010C:digital envelope routines::unsupported
    at new Hash (node:internal/crypto/hash:71:19)
    at Object.createHash (node:crypto:140:10)
    at module.exports (/home/uno/BustaPaga/node_modules/webpack/lib/util/createHash.js:135:53)
    at NormalModule._initBuildHash (/home/uno/BustaPaga/node_modules/webpack/lib/NormalModule.js:417:16)
    at handleParseError (/home/uno/BustaPaga/node_modules/webpack/lib/NormalModule.js:471:10)
    at /home/uno/BustaPaga/node_modules/webpack/lib/NormalModule.js:503:5
    at /home/uno/BustaPaga/node_modules/webpack/lib/NormalModule.js:358:12
    at /home/uno/BustaPaga/node_modules/loader-runner/lib/LoaderRunner.js:373:3
    at iterateNormalLoaders (/home/uno/BustaPaga/node_modules/loader-runner/lib/LoaderRunner.js:214:10)
    at Array.<anonymous> (/home/uno/BustaPaga/node_modules/loader-runner/lib/LoaderRunner.js:205:4) {
  opensslErrorStack: [ 'error:03000086:digital envelope routines::initialization error' ],
  library: 'digital envelope routines',
  reason: 'unsupported',
  code: 'ERR_OSSL_EVP_UNSUPPORTED'
}
```

this time I used 6.0.100 as dotnet version in global.json

**Comment by nojaf** [comment]
What node version do you have? Maybe that version isn't overly compatible anymore with what the node modules from that template need. At this point, I think your problem shifted from dotnet to node 😔.

**Comment by UnoSD** [comment]
thank you for the help; the node version is 19.0.1. I can't see any version requirements on the template GitHub or the Fable docs

**Comment by nojaf** [comment]
That sounds rather recent, are the versions of the node modules (like `webpack`) somewhat recent?
Maybe there is a bit of a clash between what is used in the template (version-wise) and the node you have. 

@MangelMaxime any thoughts?

**Comment by UnoSD** [comment]
OK, updating the webpack packages to the latest version, fixing the incompatible config and running then worked. Thanks again @nojaf.

For other people's reference: the issue in the title is for unsupported dotnet version (7) for Fable.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for your help @nojaf!

**Comment by nojaf** [comment]
You're welcome, @UnoSD maybe you can contribute your fixes to the template afterwards?

**Comment by UnoSD** [comment]
@nojaf already on my TODO list :)

I know my way around F# and dotnet, but I'm a oblivious to whatever is node/JS related, so, hopefully my pull request will make sense.

Just for the sake of accuracy, the broken template was `Fable`; the `Fable.Elmish.React` has an up-to-date enough version of webpack, the issue there was just dotnet version.
