### ISSUE TITLE
Bug: The type parameter 'T is not defined

### ISSUE THREAD

**Issue by adelarsq** [fable-compiler/Fable#3266]
### Description

I getting this error using latest Fable version:

```
./src/fable_modules/Feliz.SweetAlert.2.8.0/Bindings.fs(26,25): (26,27) error FSHARP: The type parameter 'T is not defined. (code 39)
./src/fable_modules/Feliz.SweetAlert.2.8.0/Bindings.fs(187,37): (187,71) error FSHARP: The type 'obj' does not match the type ''a option' (code 1)
```

### Repro code

For some reason 'T option isn't reconized:

```
abstract value: 'T option with get, set
```
https://github.com/Shmew/Feliz.SweetAlert/blob/fb27a206ddf04f3f483368d46135459ea5186eaf/src/Feliz.SweetAlert/Bindings.fs#L26

### Expected and actual results

To clear projects has no effect.

### Related information

* Fable version: `dotnet fable --version` 4.0.0-theta-015
* .NET 6.0.402 and  7.0.100
* Operating system macOS

**Comment by ncave** [comment]
@adelarsq The error seems to be coming from the F# compiler (FCS), perhaps it's more stringent now, with the [static abstract methods](https://devblogs.microsoft.com/dotnet/announcing-fsharp-7/#static-abstract-members-support-in-interfaces) support?

**Comment by alfonsogarciacaro** [comment]
@ncave is likely right. It has happened in the past the type inference in F# has become stricter and properties returning a generic (not defined by the type) are tricky. Can you please type adding a type annotation? For example, to the binding:

```fsharp
let value: MyType = alert.value
```

**Comment by ArtemyB** [comment]
@adelarsq here is similar issue: #3248. To sum up, properties in .NET can't have their own generic parameters, only methods can. And previous (before F# 7) ability to declare such generic property was actually a bug. The solutions are:

- to use a method instead of property;
- set generic parameter on type that "owns" the member.

**Comment by adelarsq** [comment]
Got it! Since it's a bug on the library I will close this issue.
Thanks for the help. I will send a pull request for the library.
