### ISSUE TITLE
Fable compilation breaks with -theta-016

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/Fable#3267]
### Description

Upgrading to -theta-016 breaks the `Fable.Python` [test project](https://github.com/fable-compiler/Fable.Python).

### Repro code

In Fable.Python:

```console
> cd test
>  dotnet fable --lang python --outDir ../build/test  
```

This can be seen in GH actions:  https://github.com/fable-compiler/Fable.Python/actions/runs/3454283901/jobs/5765484684

### Expected and actual results

This compiles with -theta-15. With -theta-16 I get:

```
./../src/stdlib/Ast.fs(10,3): (10,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(14,3): (14,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(18,3): (18,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(22,3): (22,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(27,3): (27,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(32,3): (32,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(37,3): (37,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(47,3): (47,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(56,3): (56,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(61,3): (61,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(66,3): (66,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(72,3): (72,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(77,3): (77,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(84,3): (84,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(91,3): (91,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(103,3): (103,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(109,3): (109,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/Ast.fs(115,3): (115,9) warning FSHARP: This type does not inherit Attribute, it will not work correctly with other .NET languages. (code 3242)
./../src/stdlib/TkInter.fs(23,27): (23,37) warning FABLE: Member title is duplicated, use Mangle attribute to prevent conflicts with interfaces
./../src/stdlib/asyncio/Futures.fs(3,6): (3,11) error FSHARP: The namespace or module 'Fable' is not defined. (code 39)
./../src/stdlib/asyncio/Futures.fs(13,7): (13,11) error FSHARP: The type 'Emit' is not defined. (code 39)
./../src/stdlib/asyncio/Futures.fs(17,7): (17,11) error FSHARP: The type 'Emit' is not defined. (code 39)
./../src/stdlib/asyncio/Events.fs(3,12): (3,16) error FSHARP: The namespace 'Core' is not defined. (code 39)
./../src/stdlib/asyncio/Tasks.fs(3,12): (3,16) error FSHARP: The namespace 'Core' is not defined. (code 39)
./../src/stdlib/asyncio/Tasks.fs(21,7): (21,11) error FSHARP: The type 'Emit' is not defined. (code 39)
./../src/stdlib/asyncio/Tasks.fs(23,7): (23,11) error FSHARP: The type 'Emit' is not defined. (code 39)
./../src/stdlib/asyncio/Tasks.fs(28,7): (28,16) error FSHARP: The type 'ImportAll' is not defined. (code 39)
./../src/stdlib/asyncio/Tasks.fs(29,29): (29,39) error FSHARP: The value or constructor 'nativeOnly' is not defined. Maybe you want one of the following:
   nativeint
   NativeInterop
   nativeptr (code 39)
./../src/stdlib/Ast.fs(3,12): (3,16) error FSHARP: The namespace 'Core' is not defined. (code 39)
...
```

For more info see builds in GH Actions:

- Theta-015: https://github.com/fable-compiler/Fable.Python/actions/runs/3454286017/jobs/5765488336 (works)
- Theta-016: https://github.com/fable-compiler/Fable.Python/actions/runs/3454283901/jobs/5765484684 (fails)

The only difference between these two builds are 015 vs 016.

### Related information

* Fable version: `dotnet fable --version`
* Operating system, Mac OS X but also fails in GH Actions

**Comment by dbrattli** [comment]
Looks like it some how cannot resolve `Fable.Core` when referencing `<ProjectReference Include="../src/Fable.Python.fsproj" />`

**Comment by dbrattli** [comment]
A strange thing is that after compiling with -015 (which works), then compiling to -016 suddenly works. But if I delete `obj` and `bin` folders then will fail to compile again.

PS: This is also not related to Python in any way. Compiling to JS will produce the same error

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting @dbrattli , I think I know what's happening. I'll check when I get home.

**Comment by dbrattli** [comment]
FYI: still fails with -theta-17

**Comment by alfonsogarciacaro** [comment]
Oh, my! I swear I did try with Fable.Python before releasing 🤦 There's a little problem with the repo as it misses a global.json file, though it shouldn't be a strict requirement to compile a Fable project. I'm assuming you're using dotnet 7 sdk.

In my tests it works when Fable.Python.Test targets net6.0 and dotnet 6 sdk is used or with the net7.0/dotnet 7 sdk combo. I need to see if we can go around this or we will have to ask the users to target the same version as the sdk 😕

**Comment by pkese** [comment]
I'm seeing this to.

While trying to compile my FS -> JS project with Theta-017 as suggested in https://github.com/fable-compiler/Fable/issues/3260#issuecomment-1317090873  
I'm seeing heaps of `The namespace or module 'Fable' is not defined` or `The type 'Emit' is not defined` at places where I import or use Fable.Core or other Fable modules.

**Comment by dbrattli** [comment]
@alfonsogarciacaro I'm using

```console
❯ dotnet --version
6.0.401
```
Is .NET v7 a requirement now? Here's the CI build btw using 6.0.403 so you can see all the details: https://github.com/fable-compiler/Fable.Python/actions/runs/3496871994/jobs/5855289982

**Comment by dbrattli** [comment]
Confirming that Fable Python now compiles again with theta-018. Thanks for fixing @alfonsogarciacaro. Magnificent work!!

https://github.com/fable-compiler/Fable.Python/actions/runs/3503038164/jobs/5867808843

**Comment by dbrattli** [comment]
Confirming that Fable Python now compiles again with theta-018. Thanks for fixing @alfonsogarciacaro. Magnificent work!!

https://github.com/fable-compiler/Fable.Python/actions/runs/3503038164/jobs/5867808843

**Comment by alfonsogarciacaro** [comment]
Hurra :tada: Thanks for reporting and confirming @dbrattli!
