### ISSUE TITLE
Compilations errors with .NET 7 & Fable 3.0.1

### ISSUE THREAD

**Issue by OkayX6** [fable-compiler/Fable#3278]
### Description

Working project doesn't compile anymore with **Fable 3.0.1**.
**Fable 3.7** simply hangs.

### Repro code

Any Fable project. Try with Feliz template
`dotnet new feliz -n AwesomeApp`

### Expected and actual results

Expected results is that it compiles.
Actual results:

<img width="764" alt="image" src="https://user-images.githubusercontent.com/1169339/202851578-136bbacd-8a20-4b2c-ba1e-507aefc5226c.png">

### Related information

* Fable version: 3.0.1
* Operating system: Windows
* .NET version:

```
.NET SDK:
 Version:   7.0.100
 Commit:    e12b7af219

Runtime Environment:
 OS Name:     Windows
 OS Version:  10.0.22621
 OS Platform: Windows
 RID:         win10-x64
 Base Path:   C:\Program Files\dotnet\sdk\7.0.100\

Host:
  Version:      7.0.0
  Architecture: x64
  Commit:       d099f075e4

.NET SDKs installed:
  5.0.404 [C:\Program Files\dotnet\sdk]
  6.0.101 [C:\Program Files\dotnet\sdk]
  6.0.302 [C:\Program Files\dotnet\sdk]
  6.0.400 [C:\Program Files\dotnet\sdk]
  7.0.100 [C:\Program Files\dotnet\sdk]

.NET runtimes installed:
  Microsoft.WindowsDesktop.App 5.0.13 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 5.0.14 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.6 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.7 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.8 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.9 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.10 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 6.0.11 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
  Microsoft.WindowsDesktop.App 7.0.0 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]

Other architectures found:
  x86   [C:\Program Files (x86)\dotnet]
    registered at [HKLM\SOFTWARE\dotnet\Setup\InstalledVersions\x86\InstallLocation]
```

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report @OkayX6! Yes, unfortunately dotnet sdk 7 is giving problems. We've almost fixed it for the incoming Fable 4 (see #3279) but I'm not sure if we'll be able to patch it for Fable 3.

Can you please try upgrading to Fable 4? You should be able to upgrade any Feliz app with just two commands:

```
dotnet tool install fable --prerelease

# In your project directory
dotnet add package Feliz.CompilerPlugins --prerelease
```

**Comment by harvito** [comment]
Just want to add that it also fails with Fable 2 but in a different way. This is from fable2-samples/nodejs with .net sdk 7.0.100
```
$ npm run build

> @ build C:\CODE\fable2-samples\nodejs
> fable-splitter src -o build --commonjs

fable-splitter 2.1.12
fable: Compilation started at 6:37:06 p.m.
fable-compiler 2.4.18
C:\CODE\fable2-samples\nodejs\src> dotnet restore App.fsproj
  Determining projects to restore...
  All projects are up-to-date for restore.


Parsing ./src/App.fsproj...
The list of files returned by F# compiler is empty
ERROR: File C:/CODE/fable2-samples/nodejs/src/App.fs cannot be found in source list:
 (C:/CODE/fable2-samples/nodejs/src/App.fs)
   at Microsoft.FSharp.Core.PrintfModule.PrintFormatToStringThenFail@1637.Invoke(String message) in E:\A\_work\130\s\src\fsharp\FSharp.Core\printf.fs:line 1637
   at Fable.Transforms.FSharp2Fable.Compiler.transformFile(ICompiler com, IDictionary`2 implFiles) in /workspace/Fable/src/Fable.Transforms/FSharp2Fable.fs:line 1169
ERROR: File C:/CODE/fable2-samples/nodejs/src/App.fs cannot be found in source list:
 (C:/CODE/fable2-samples/nodejs/src/App.fs)
```

**Comment by pkese** [comment]
@OkayX6, @harvito 
If you can't install Fable 4 prerelease, then you can select an older version of dotnet SDK by adding a `global.json` file to the root of your project, containing e.g.:

```json
{
    "sdk": {
      "version": "6.0.100",
      "rollForward": "latestFeature"
    }
}
```
You'll also need the older version of sdk (e.g. dotnet 6) installed besides dotnet 7. They can coexist just fine.

**Comment by OkayX6** [comment]
Thanks @pkese for your tips!

> Thanks a lot for the detailed report @OkayX6! Yes, unfortunately dotnet sdk 7 is giving problems. We've almost fixed it for the incoming Fable 4 (see #3279) but I'm not sure if we'll be able to patch it for Fable 3.
> 
> Can you please try upgrading to Fable 4? You should be able to upgrade any Feliz app with just two commands:
> 
> ```shell
> dotnet tool install fable --prerelease
> 
> # In your project directory
> dotnet add package Feliz.CompilerPlugins --prerelease
> ```

Thanks @alfonsogarciacaro, it worked, but now I have another issue:

### Environment variables
This code fetching environment variables is not working anymore:
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1169339/205436449-7d17cfdf-4e86-44b0-be85-024d68ff68cb.png">

The generated code looks fine
<img width="460" alt="image" src="https://user-images.githubusercontent.com/1169339/205436482-99ea4365-e004-490a-8f92-14815fc31f9e.png">

But the result is None

**Comment by alfonsogarciacaro** [comment]
@OkayX6 Happy yo hear it worked for you!

Did you upgrade from Fable 2 or 3? In Fable 2 Webpack called Fable but since Fable 3 it is the other way around, maybe this caused by the issue with the env cars.

**Comment by harvito** [comment]
Thanks for the global.json tip, this is working with Fable compiler 2. Will upgrade to 4 once it's GA.
