### ISSUE TITLE
DateOnly / TimeOnly with scripts

### ISSUE THREAD

**Issue by isaacabraham** [fable-compiler/Fable#3284]
### Description

`DateOnly` doesn't appear to work in scripts.

### Repro code

```fsharp
open System

type Order =
    {
        OrderDate : DateOnly
    }
```

### Expected and actual results

Should compile, but leads to the following error:

```
error FSHARP: The type 'DateOnly' is not defined. (code 39)
```

### Related information

* Fable version: `dotnet fable --version`: 3.7.20
* Operating system: Windows 11
* .NET Version: 6.0.403

**Comment by alfonsogarciacaro** [comment]
Hi @isaacabraham. Can you please try with Fable 4 (`dotnet tool install fable --prerelease`)? I just tested and DateOnly works for me in scripts.

**Comment by MangelMaxime** [comment]
I tested and it is working for me with Fable .
