### ISSUE TITLE
System.Int128

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3286]
@alfonsogarciacaro Is it too late to add the `System.Int128`, `System.UInt128` and `System.Half` to the Fable AST for Fable 4?

**Comment by alfonsogarciacaro** [comment]
Actually, I wanted to write a post for the announcement, but I was quite busy the past weeks. So we can take that as a chance to add the numeric types. Not sure if the addition will force updating many pattern matchings (as in Replacements). Did you try it already?

**Comment by ncave** [comment]
@alfonsogarciacaro Hopefully should not cause too much issues. I'll add a PR for it over the next few days, so you can keep writing.
