### ISSUE TITLE
sprintf "%s" "%%" // evaluates to"%"

### ISSUE THREAD

**Issue by markek** [fable-compiler/Fable#329]
using 0.5.2 on win 7

**Comment by alfonsogarciacaro** [comment]
This one is tricky. The regex I'm using to identify the placeholders is ignoring `%%` but then when returning the string I'm replacing all doubles `%%` with single `%`. I need to think of an elegant way to solve this problem. Suggestions are welcome! 😄 

Regex: https://github.com/fsprojects/Fable/blob/264269a6219390419b7f6e093c87e38c822b4126/src/fable/Fable.Core/npm/fable-core.ts#L740

`%%` replacement: https://github.com/fsprojects/Fable/blob/264269a6219390419b7f6e093c87e38c822b4126/src/fable/Fable.Core/npm/fable-core.ts#L781

**Comment by markek** [comment]
Ok,

I looked at the code.

How about for each replacement text `r`, let `r'` be `r` with each `%` replaced with `%%`.
Use `r'` for the replacement text instead of `r `.

I think this fits with your current design. These new  `%% ` will be skipped by your  `% ` regex for format cases, but be changed back to  `% ` by the final  `%%  -> % ` step.

This would need to be done for all replacements except for those in which  `% ` can't possibly occur, like for  `%d `.

**Comment by alfonsogarciacaro** [comment]
That's a good idea, I'll give it a try 👍 I've limited access to my computer for a couple of days so it may take a bit of time. In the meanwhile if you could post some sample code to implement your idea (or send a PR), that'd be very helpful 😄 

Cheers!

**Comment by markek** [comment]
Sure will
