### ISSUE TITLE
Support .NET 7 for Fable 3?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3294]
### Description

I see more and more people reporting issues with their dependencies not being found.

The cause of the error is that Fable 3 doesn't support .NET 7 but because the error is not obvious they can't figure it out.

Would it be possible to post the changes made for Fable 4 to Fable 3? If not is it possible to detect the error and indicate to the user to add a `global.json` to their project to lock to .NET 6?

Option 1 would be better if doable :)

**Comment by MangelMaxime** [comment]
Workaround:

Create a `global.json` with the following content:

```js
{
    "sdk": {
        "version": "6.0.0",
        "rollForward": "latestMinor"
    }
}
```

This will tell dotnet to use .NET 6 for the current directory and children.

**Comment by AlbertoLeon** [comment]
Maybe another approach is update the template with this approach and also, adding the Fable 4 templates?

**Comment by AlbertoLeon** [comment]
There is a complete log after adding the `global.json`
![image](https://user-images.githubusercontent.com/942409/208323620-70689ed8-79cc-4596-9ee3-4517f79d6ab9.png)

**Comment by MangelMaxime** [comment]
@AlbertoLeon The template has been updated to include a `global.json` file.

https://github.com/fable-compiler/fable-templates/blob/master/minimal/CHANGELOG.md#390---2021-12-12

Make sure you deleted all temporary artefacts like  `bin` and `obj` folders. One way to do it in general is to commit your work and then run `git clean -xdf` to remove all the files that are not tracked

**Comment by object** [comment]
I second @MangelMaxime's proposal. This failure can be quite frustrating because the error message doesn't give a clue about possible cause of failure except that it looks like nothing works. With growing .NET 7 adoption it's quite important to enhance Fable 3 with support for it.

**Comment by stken2050** [comment]
Readme suggests
- [dotnet SDK 6 or higher](https://dotnet.microsoft.com/download)

and looking at the page

![image](https://user-images.githubusercontent.com/1316994/212420142-b09bb421-c1b5-4930-83b4-c829f5b2a1da.png)

.NET 7.0
Standard Term Support
Recommended

https://github.com/fable-compiler/Fable/issues/3028#issuecomment-1382231437

>Fable 4 is already looking very nice.
Is there a timeframe for a ready-for-production Fable 4 release?

I also wish Fable4 become the production-ready release with the official templates soon.

**Comment by rfrerebe** [comment]
I think this issue should be pinned above all issues until it's solved.
I think it would help.

**Comment by MangelMaxime** [comment]
The `global.json` is required to force .NET to use the correct version.

This is because something changed in .NET 7 in how dependencies resolution should be done (like with every release of .NET I think...)

If you use the `global.json` file with the setting I provided then `dotnet --version` should return 6 otherwise you probably miss configured that file.

**Comment by kspeakman** [comment]
Point is: `dotnet build` compiles to net6.0 even with 7 installed, presumably because it uses the target SDK version from the .fsproj file. Could Fable use a similar strategy?

Simply having .NET 7 installed -- which is now a prerequisite for most VS 2022 workloads -- breaks all Fable 3 projects. It is very disconcerting when a project suddenly and inexplicably stops working. Adding a global.json is a work-around, but only after half a day of trying to figure it out, confidence destroyed.

**Comment by MangelMaxime** [comment]
> Point is: `dotnet build` compiles to net6.0 even with 7 installed, presumably because it uses the target SDK version from the .fsproj file. Could Fable use a similar strategy?

It could if dependencies resolution is fixed when running with .NET 7.

You can install several version of dotnet side by side, so you can have both .NET 6 and .NET 7 installed at the same time.

> Simply having .NET 7 installed -- which is now a prerequisite for most VS 2022 workloads -- breaks all Fable 3 projects. It is very disconcerting when a project suddenly and inexplicably stops working. Adding a global.json is a work-around, but only after half a day of trying to figure it out, confidence destroyed.

Indeed, this bug is annoying.

In general, it is a good idea to lock your runtimes in the same way you do it for your dependancies. This help makes the code reproducible between machines and easier to spot why something is breaking.

**Comment by kspeakman** [comment]
I do have both SDK versions installed. But the correct target is specified in the .fsproj file. The dotnet build tool has the `-r <runtime identifier>` option. But I don't have to use that to get it to compile net6.0 -- it does so by itself. So it seems possible for Fable to avoid this issue too.

**Comment by PaigeM89** [comment]
For what it's worth, this story gets a bit more complex on linux - or at least it was weird for me on Ubuntu.

I had the `6.0.406` and `7.0.200` dotnet SDKs installed, but even with the `global.json` configured to point at `6.0.406` I was having issues where Fable would hang with no output when I tried to run it.

I'm adding this anecdote for 2 reasons:
1. It's a use case for getting Fable 3 to support dotnet 7, to avoid the headache I ran into.
2. It may be of help to someone running into the same issues.

For anyone stumbling across this issue and having similar symptoms, I had to manually extract the dotnet 6 binaries & copy the content of `shared/Microsoft.NETCore.App/6.0.14` over to `/usr/share/dotnet/shared/Microsoft.NETCore.App/` before Fable would give me output. My `global.json` was unchanged, still pointed at `6.0.406`.

**Comment by JoostVanVelthoven** [comment]
How is this issue prioritized?

**Comment by MangelMaxime** [comment]
We don't have a blog post announcement yet, but today Fable 4 has been released with JavaScript considered stable.

The idea is that the maintainers want to avoid spending time fixing issues in Fable 3, and encourage people to move to Fable 4 in order to get the latest features ans support for .NET 7 is part of it.

**Comment by kspeakman** [comment]
This break occurs from a supposedly backward compatible tool update and the cause is hard to discover. (Google didn't find it... a kind soul on F# slack directed me here.) Is there no way to address this economically?

Asking everyone to upgrade to a newly released major version is pretty intense.
