### ISSUE TITLE
slicing [1;2;3][..9] behaves differently in fable and dotnet F#

### ISSUE THREAD

**Issue by mknj** [fable-compiler/Fable#3295]
### Description
Slicing shorter lists throws an exception.
The following code works in dotnet F#, but fails with fable.

My actual use case is filtering a list by search string and truncating it to max 10 entries.
### Repro code

```f#
let a=[1;2;3]
printfn "A %A" a
let b=a[..1]
printfn "B %A" b
let c=a[..4]
printfn "C %A" c
```

#### expected (dotnet F#)
```
A [1; 2; 3]
B [1; 2]
C [1; 2; 3]
```
#### actual (fable https://fable.io/repl/)
```
A [1; 2; 3]
B [1; 2]
Uncaught Error: The index was outside the range of elements in the collection.\nParameter name: endIndex
    getSlice List.js:1234
```

### Related information

* current version of https://fable.io/repl/ 😉
* Fable version: `4.0.0-snake-island-alpha-026` on `ubuntu 22.10`

**Comment by mknj** [comment]
related to #1817
Please add test cases also for edge case and compare them with dotnet F#.

**Comment by mknj** [comment]
Why are there different tests for the same functionality under different compile targets?
i.e. "List slice works" can be found in tests/Js/Main/ListTests.fs and in tests/Python/TestList.fs

Are you accepting pull requests for JS? I can do the JS fix, but i have no idea on how to run the rust, python or php tests.

**Comment by dbrattli** [comment]
@mknj Thanks for filing this issue. This indeed looks to be a bug with Fable. The Fable supported languages have separate testing which enables them to have different levels of support i.e alpha vs stable. Having the same test suite for all languages would be difficult. Some languages use Expecto style tests while other uses XUnit style for tests. This duplicates the tests for each language but for now we consider it the better evil.
