### ISSUE TITLE
Fable 3.7.20 breaks Mocha when using tests written in typescript.

### ISSUE THREAD

**Issue by serefarikan** [fable-compiler/Fable#3305]
### Description

The Mocha test runner in Webstorm breaks when Fable is updated from `3.2.9` to `3.7.20` 

The configuration includes `typescript` and `ts-node` along with `mocha` and `chai` packages.  I run tests in typescript and test the js generated by fable using tests written in typescript. I'm using Mocha as the test framework and WebStorm provides a nice UI that allows me to run individual tests from the IDE, directly from the text editor, if I invoke the context menu. 
Screenshot shows this feature:
![image](https://user-images.githubusercontent.com/1894220/208251681-ef31910a-eea4-46b1-939c-67897cf07dac.png)

When Fable is upgraded to `3.7.20` this feature breaks. Further details below.

### Repro code

I isolated the problem and created this repo: https://github.com/serefarikan/fable-mocha-ts-problem

### Expected and actual results
Expected result is Mocha to run the test. Actual result is mocha complaining about unknown file extension `.ts`. The command line prompt shows both the syntax Webstorm uses to invoke mocha and the resulting error.
```
/usr/bin/node /PATH_TO_PROJECT_NODE_MODULES/node_modules/mocha/bin/mocha.js --require ts-node/register --ui bdd --reporter /PATH_TO_MY_WEBSTORM_INSTALLATION/WebStorm-202.7660.23/plugins/nodeJS/js/mocha-intellij/lib/mochaIntellijReporter.js /PATH_TO_PROJECT_ROOT/test/TestJsInterop.ts --grep ^User module increments user age$

TypeError [ERR_UNKNOWN_FILE_EXTENSION]: Unknown file extension ".ts" for /PATH_TO_PROJECT_ROOT/test/TestJsInterop.ts
    at new NodeError (node:internal/errors:387:5)
    at Object.getFileProtocolModuleFormat [as file:] (node:internal/modules/esm/get_format:75:11)
    at defaultGetFormat (node:internal/modules/esm/get_format:117:38)
    at defaultLoad (node:internal/modules/esm/load:81:20)
    at nextLoad (node:internal/modules/esm/loader:163:28)
    at ESMLoader.load (node:internal/modules/esm/loader:601:26)
    at ESMLoader.moduleProvider (node:internal/modules/esm/loader:457:22)
    at new ModuleJob (node:internal/modules/esm/module_job:63:26)
    at ESMLoader.#createModuleJob (node:internal/modules/esm/loader:476:17)
    at ESMLoader.getModuleJob (node:internal/modules/esm/loader:434:34)
    at async Promise.all (index 0)
    at async ESMLoader.import (node:internal/modules/esm/loader:526:24)
    at async importModuleDynamicallyWrapper (node:internal/vm/module:438:15)
    at async formattedImport (/PATH_TO_PROJECT_ROOT/node_modules/mocha/lib/nodejs/esm-utils.js:9:14)
    at async Object.exports.requireOrImport (/PATH_TO_PROJECT_ROOT/node_modules/mocha/lib/nodejs/esm-utils.js:42:28)
    at async Object.exports.loadFilesAsync (/PATH_TO_PROJECT_ROOT/node_modules/mocha/lib/nodejs/esm-utils.js:100:20)
    at async singleRun (/PATH_TO_PROJECT_ROOT/node_modules/mocha/lib/cli/run-helpers.js:125:3)
    at async Object.exports.handler (/PATH_TO_PROJECT_ROOT/node_modules/mocha/lib/cli/run.js:370:5)

Process finished with exit code 1

```

### Related information
**Update: I think this is due to using ts-node**
The Mocha runner in WebStorm uses ts-node to run tests that are written in typescript. ts-node acts different than a bundler and resolves the imports unlike a bundler that produces a unified js version (es5 etc). Fable itself generates es2015 compatible js, and node supports running commonjs along with es2015. However, when ts-node encounters the `"type":"module"` statement in package.json that is at the root of the Fable runtime libraries that come with `3.7.20`, it attempts to treat them as an es module, and an es module is not supposed to use `require()`. So it is telling me to either remove the `"type":"module"` which would allow it to treat these libraries as commonjs modules, or use `import...` instead of `require()` as es requires. 
So the interesting question is, why is the Fable runtime libraries declaring themselves as an es module in package.json when they're using require? This is as far as I could come with my ignorance in the js ecosystem.
**End of update**
I found out that the problem emerges when the js generated by fable includes the import for `Record` as in 
`import { Record } from "./fable_modules/fable-library.3.7.20/Types.js";`
I'm not sure if other imports are causing the problem, but the difference between thing working and not working is the difference in the import statements generated by  `3.2.9` and `3.7.20` . 
This works:
```
import { printf, toText } from "./.fable/fable-library.3.2.9/String.js";
import { getItemFromDict, addToDict } from "./.fable/fable-library.3.2.9/MapUtil.js";
import { singleton, toArray } from "./.fable/fable-library.3.2.9/List.js";
import { Record } from "./.fable/fable-library.3.2.9/Types.js";
import { record_type, int32_type, string_type } from "./.fable/fable-library.3.2.9/Reflection.js";
```
While this does not (taken from the project where I came across this issue):
```
import { printf, toText } from "./fable_modules/fable-library.3.7.20/String.js";
import { getItemFromDict, addToDict } from "./fable_modules/fable-library.3.7.20/MapUtil.js";
import { singleton, toArray } from "./fable_modules/fable-library.3.7.20/List.js";
import { Record } from "./fable_modules/fable-library.3.7.20/Types.js";
import { record_type, int32_type, string_type } from "./fable_modules/fable-library.3.7.20/Reflection.js";

```
* Fable version: `dotnet fable --version`
`3.7.20`
* Operating system
Ubuntu 18.04 Bionic . The machine has .net 7 installed but the project is using .net 6 (global.json) because Fable 3.x freezes when compiling fs under .net 7

**Comment by serefarikan** [comment]
Ok, I'm not sure how much this'll help but I managed to make the test runner give me more information. 
I modified the test runner so that I used the following node options:
`--experimental-specifier-resolution=node --loader ts-node/esm`
And then suddenly it gave me a hint:
```
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /PATH_TO_PROEJECT/fable-mocha-problem/src/fable_modules/fable-library.3.7.20/Types.js
require() of ES modules is not supported.
require() of /PATH_TO_PROEJECT/fable-mocha-problem/src/fable_modules/fable-library.3.7.20/Types.js from /PATH_TO_PROEJECT/fable-mocha-problem/src/JsInterop.fs.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead change the requiring code to use import(), or remove "type": "module" from /PATH_TO_PROEJECT/fable-mocha-problem/src/fable_modules/fable-library.3.7.20/package.json.

```

So I manually modified the mentioned `package.json` above and removed the `type:module` and the mocha runner worked!

Right now I have no clue if this breaks something else, but at least it may help people who know what they're doing :)

**Comment by MangelMaxime** [comment]
Fable 3 output JavaScript ESM code which is now the default module format in Node.js

Mocha doesn't support ESM out of the box and so as you discovered you need to use a loader to make it understand it.

I don't remember if earlier version of Fable 3 where generate non ESM code but I don't think so.

So for me, there is not much to do on Fable side for this problem.
