### ISSUE TITLE
JS tests fails in main

### ISSUE THREAD

**Issue by dbrattli** [fable-compiler/Fable#3311]
### Description

JS tests fails consistently in `main` after https://github.com/fable-compiler/Fable/commit/76e538be77a81abef987a7b01d6281eb4f49e810. Not sure why we get `RangeError: Maximum call stack size exceeded`.  Does this mean that the code has not been tail call optimized in GH?

**Comment by ncave** [comment]
@dbrattli Yes, looks like 2/3 of the new tests are not tail call optimized when compiled by Fable-JS.
I'll take a look.

**Comment by ncave** [comment]
I temporarily disabled two of the tests for JS, so we can get back to a working build.
It could be that the F# AST is different between `Fable` and `Fable-FCS` somehow.

**Comment by ncave** [comment]
Turns out F# AST was the same, it was just a matter of not defaulting to DEBUG mode for `fable-standalone`. See #3324.
