### ISSUE TITLE
string(someEnumValue) and someEnumValue.ToString() should use the enum name instead of the int value

### ISSUE THREAD

**Issue by jwosty** [fable-compiler/Fable#3315]
### Description

The following code:

```fsharp
type SomeEnum = | A = 0 | B = 1 | C = 2
printf "%A" (string SomeEnum.B)
```

Should print "B" to match .NET. Fable currently prints "1" instead (I understand this is because the toString implementation sees the enum case as a number). I would think it should be possible to fulfill this as #1217 seems to have done the hard work already.

### Related information

* Fable version: 3.7.20
* Operating system: macOS

**Comment by Happypig375** [comment]
.NET prints "B". To print "A" would be a bug.

**Comment by alfonsogarciacaro** [comment]
"%A" formatting already differs from .NET in many places, like collection. As it's already possible to get the name by using `Enum.GetName` I would prefer to leave it like this.

**Comment by jwosty** [comment]
> 

Thanks, fixed the typo

> 

Fair enough.
