### ISSUE TITLE
Iteration

### ISSUE THREAD

**Issue by ordinaryorange** [fable-compiler/Fable#3330]
Wondering if [Iteration](https://tc39.es/ecma262/#sec-iteration) interfaces are on the roadmap ?

**Comment by MangelMaxime** [comment]
I think this is not related to the Browser APi but more like JavaScript support in general.

This is why I moved this issue to Fable repo

**Comment by alfonsogarciacaro** [comment]
Fable compiles `seq` (alias for `IEnumerable`) as JS iterables, so you can any F# collection to any JS code that expects an iterable. It also works the other way: you can consume any iterable from JS as if it were `seq`.

Closing for now, but please feel free to reopen if my understanding was not correct.
