### ISSUE TITLE
SRTP call to Int32.TryParse fails

### ISSUE THREAD

**Issue by njlr** [fable-compiler/Fable#3332]
### Description

SRTP call to `Int32.TryParse` fails

Testing out this: https://github.com/demystifyfp/FsToolkit.ErrorHandling/blob/master/src/FsToolkit.ErrorHandling/Option.fs#L40-L52

### Repro code

```fsharp
let inline tryParse< ^value when ^value: (static member TryParse: string * byref< ^value > -> bool)>
  (valueToParse: string)
  : ^value option =
  let mutable output = Unchecked.defaultof< ^value>

  let parsed =
      (^value: (static member TryParse: string * byref< ^value > -> bool) (valueToParse,
                                                                            &output))

  match parsed with
  | true -> Some output
  | _ -> None


let x = 
  tryParse "123"
  |> Option.defaultValue 0

printfn $"x = %i{x}"

```

https://fable.io/repl/#?code=DYUwLgBAlgdssgmATgTwAoENkGcQB4IA9AN02AFdEB3ACxBmLMpAC4IAKHMTMKAYwgBbEEIBGIZBAAqaLLjYRuyWAHMIAKghjUyEADNCpclQgA+CAFoLYgPa3gASjMAoCJ2ZVpt+XnbK1RzcIdmMWCFsABz5bRgBeYNBIIQoeMVAI1MjUiDiIAFUYfnp+AGsQABMAOgqDTApgMFtDJhMQV0TwCEjsPArc4Pd3DjCqdi4ePkERcUkZOV7FAJh1LR09FtHEC2tteycPNu9fEAAaQaHLq+ub27v7h-uAMlss1Mcg4KFeYu7F-uoUDAtGCAB8kMhTLsAMq2ESZMDZMBgiAAfSsFgAcrEQC48UkIAAPXIQYIoDCLCAAIgAjAAmADMVLBFgA8tEoLEanUGmAAGptCAABjxkRUMDA+kYABIqcS8gBSKAAb0JAF9mUA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8A5AMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3JJAoATgGcCTGmABm5ABwt4wFagwJgAIw5oh8REqcu311bDhA&css=Q

### Expected and actual results

Actual

```
x = 0
```

Expected

```
x = 123
```

### Related information

```
REPL: 4.0.0-theta-009
```

**Comment by ncave** [comment]
@njlr This will be fixed in the next 4.x release (see #3328).
