### ISSUE TITLE
Q: What is the proper way to create native objects like WebSockets?

### ISSUE THREAD

**Issue by MaxWilsonMS** [fable-compiler/Fable#3341]
Besides using Emit, what is the right way to create a WebSocket? Import doesn't seem to work because it's a native module, not a JS module:

```
[<Import("default", from="WebSocket")>]
let t : WebSocketType = jsNative
let createSocket clientUrl protocol : WebSocket =
    t.Create (clientUrl, U2.Case1 protocol)
```

**[vite] Internal server error: Failed to resolve import "WebSocket" from "src\WebSync.fs.js". Does the file exist?**

Obviously I can just do

```
[<Emit("new WebSocket($0, $1)")>]
let createSocket clientUrl protocol : WebSocket = jsNative
```

but then that makes me wonder why WebSocketType exists and whether there's a different way.

**Comment by SCullman** [comment]
It is part of f[able-browser](https://github.com/fable-compiler/fable-browser/); there is a NuGet package for it.

**Comment by MaxWilsonMS** [comment]
@SCullman, I am consuming the Nuget package via **<PackageReference Include="Fable.Browser.WebSocket" Version="1.3.0" />**. That's why I have WebSocketType in the first place. But how do you instantiate a WebSocket without using Emit, and what is WebSocketType for? That is my question.

**Comment by MangelMaxime** [comment]
@MaxWilsonMS You can create a web socket by doing `WebSocket.Create`

`WebSocketType` is how the constructor or equivalent for it is exposed. This is because we can't or could not use the native F# constructor to map to JS binding constructor.

**Comment by MangelMaxime** [comment]
You don't want to access the Types but the [`WebSocket` global](
https://github.com/fable-compiler/fable-browser/blob/b095554a9dbf5dcf8687e021d785126dbc785fe8/src/WebSocket/Browser.WebSocket.fs) as in JavaScript:


```fs
open Browser

let socket = WebSocket.Create("wss://demo.piesocket.com/v3/channel_123?api_key=VCXCEuvhGcBDP7XhiJJUDvR1e1D3eiVjgZ9VRiaV&notify_self")

socket.onopen <- fun ev ->
    console.log("Socket connected: ", ev)

socket.onmessage <- fun ev ->
    console.log("New message received:")
    console.log ev.data
```

**Comment by MaxWilsonMS** [comment]
Oh, I see.

Browser.WebSocket.WebSocket.Create(clientUrl, U2.Case1 "json.webpubsub.azure.v1")

Thanks!
