### ISSUE TITLE
Type with no Type Parameter and with abstract member function that receives a generic argument, fails compilation

### ISSUE THREAD

**Issue by panmona** [fable-compiler/Fable#3353]
### Description

When defining a type with an abstract member function that receives a generic argument, this doesn't compile in Fable 4. Whereas in Fable 3 and F# this compiles perfectly fine.
I don't see why Fable 4 should behave differently here than F# and couldn't spot something regarding this in the Release Notes. I'm very curious about why this happens, I'd be glad for some enlightenment.

For context: This issue came up when I tried to upgrade a project to Fable 4 that uses the library Feliz.MaterialUI & Feliz.MaterialUI.Pickers, which both have some code that uses this concept. (for reference: [here](https://github.com/Shmew/Feliz.MaterialUI/blob/7eb1fe0d975b13f2f3018d42a98b002550c65ea4/src/Feliz.MaterialUI/Bindings.fs#L462))

### Repro code

```fsharp
// Doesn't work in Fable 4. Works in Fable 3. Works in F#
type CreateFilterOptionsOptions =
  abstract stringify: ('option -> string) with get, set

// Works in Fable 4. Works in Fable 3. Works in F#
type CreateFilterOptionsOptions2<'option> =
  abstract stringify: ('option -> string) with get, set
```

https://fable.io/repl/#?code=PTAEBEHsFMGcDsDkAXUB3SAnA1qAlvKAGICGARgDbSgAsAdKAOpbaz6GmXUDMDzObAsQDEAKGQBPAA7UAwpmglk0IngrLMAeSnI8keLG279bALyjQocrGSYSAY1Q3MBAOZ4AZhIBcoABSIkDp6hAC0AHygzm4AlOh4yAAWoK7QyAA0UWmioiBMLIIc5FS0fAXsxMU8ZQIVRGKSMqDyisqq6tBawSZGIbAATAA8gd3wkeaW1rYOTrZunj7+I8ZhkdHwrnFoCcmpGVnIokA&html=Q&css=Q

### Expected and actual results

Expected: Both type definitions work in Fable 4 aswell
Actual: Only the type definition with the generic works in Fable 4. Both work in plain F#. Both worked in Fable 3.

### Related information

* Fable version: 4.0.0-theta-008

**Comment by kerams** [comment]
That's not a function but a property. The CLR does not support generic properties; this has been fixed and is no longer allowed in F# 8 (in preview).

**Comment by panmona** [comment]
Thanks for the clarification. I wasn't aware of that.
