### ISSUE TITLE
fable watch stops watching after one change

### ISSUE THREAD

**Issue by halcwb** [fable-compiler/Fable#3365]
### Description

When running fable watch src/Client -o dist .js -e .jsx --run vite, fable will only recompile once. Any additional save will not trigger a recompile anymore. 

### Repro code

See https://github.com/halcwb/GenPres2 and do a npm start 

### Expected and actual results

Expected continuing recompiles when client code changes.

### Related information

* 4.0.0-theta-011
*  OS Name:     Mac OS X
 OS Version:  12.6
 OS Platform: Darwin

**Comment by MangelMaxime** [comment]
Hello @halcwb,

can you please try with the latest version of Fable 4 beta? Currently it is 4.0.0-theta-018.

**Comment by halcwb** [comment]
@MangelMaxime thanks! However, the same problem remains. Only at the first save there is a recompile, but then nothing happens any more, although additional changes are saved.

**Comment by MangelMaxime** [comment]
@halcwb Can you try setting `DOTNET_USE_POLLING_FILE_WATCHER = 1`?

When working with watcher in .NET in the past I think I needed to set that variable to change how .NET watch files.

**Comment by davedawkins** [comment]
I'm having same issue, but only with vite. Works fine with webpack, but have had to abandon webpack...
Will try this workaround

**Comment by davedawkins** [comment]
Kind of works - takes a few seconds to kick in

**Comment by halcwb** [comment]
@MangelMaxime setting DOTNET_USE_POLLING_FILE_WATCHER = 1 doesn't work.

@davedawkins As a work around I just open a file from the vite dist folder. When I want a refresh I do a save on that file. 

Note: I think the fable compiler does kick into action but it's vite that doesn't pick up the changes in the dist folder.

**Comment by MangelMaxime** [comment]
> Note: I think the fable compiler does kick into action but it's vite that doesn't pick up the changes in the dist folder.

An easy, way to check if you are right. Is if you look at the generated file on the disk now that Fable 3 and 4 write files on the disk. If the file on the disk changes it means that Fable is working correctly.

By checking quickly ViteJs seems to be using chokidar which also have a setting to use polling events. I know for Nacara, I had to use it for one of my computer.

Taken from chokidar documentation:

![CleanShot 2023-03-18 at 14 52 16](https://user-images.githubusercontent.com/4760796/226110222-d842be68-5606-4429-8ac2-8c609dd59e2e.png)

**Comment by alfonsogarciacaro** [comment]
Thanks for providing the repo @halcwb. I tried it and hot reloading is working for me (I'm on Windows).

As @MangelMaxime says, one important thing is to check if the target JS file is updated to see if it's an issue with Fable or Vite watcher.

Another thing I noted is `.js` should likely be removed from the command, as it doesn't correspond to any option. Fable ignores it, but maybe it should throw an error.

**Comment by halcwb** [comment]
@alfonsogarciacaro: Thanks. I removed `.js` from the command. As for the hot reloading, this is working on Windows for me as well, only not on MacOS. 

@MangelMaxime setting the chokidar_usepolling works!

**Comment by reinux** [comment]
Same problem on Linux. I thought I had it working yesterday with CHOKIDAR_USEPOLLING = 1, but apparently not...

**Comment by MangelMaxime** [comment]
Hello @reinux,

You are probably encountering the same problem as here https://github.com/fable-compiler/Fable/issues/3631

The workaround right now, is to use `dotnet fable --verbose` or to start the process separately. 

We suspect the problem to be due to the fact that both Fable and Vite tries to re-write the console history.

**Comment by reinux** [comment]
> The workaround right now, is to use `dotnet fable --verbose` or to start the process separately.

That seems to have done the trick. Thanks!
