### ISSUE TITLE
Broken codegen when rewriting struct field

### ISSUE THREAD

**Issue by nneeoo** [fable-compiler/Fable#3371]
### Description

Fable 4.0.0 does not access FsharpRef contents field when rewriting fields of struct records. 

### Repro code
Example here -  [REPL](https://fable.io/repl/#?code=NoHgygLgTgrgxhAfAXQLACgIE8AOBTAAjAEsBbHAGzwCU84B7KAEwIF4CBvDAnggQQBcBAM7RiAOwDm3XgCECQ0VAmSCGAL4YqEEWUqEhJclVoNmbTjJ58LAIltWC89gVuyH6Tem27jNOows7By++gQA7sQQABb8dny2BF6OGEA&html=Q&css=Q).

### Expected and actual results
Code generated:
```
export const simpleRecord = new SimpleRecord("A", (new FSharpRef(simple)).B);
```

Expected:

```
export const simpleRecord = new SimpleRecord("A", (new FSharpRef(simple)).contents.B);
```

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting! Should be fixed in the next release.
