### ISSUE TITLE
Create Fable.Core.Serialize.ofPlainJs<'T> function

### ISSUE THREAD

**Issue by funlambda** [fable-compiler/Fable#339]
Recently I ran into an situation where I really needed to convert a dynamically created object (made with createObj) to a known type.

Suppose you have a custom record type:

```fsharp
type MyRecord = { Number: int; String: string }
```

And you create an object like this:

```fsharp
let o = createObj [| "Number" ==> 4; "String" ==> "hello" |]
```

I want to be able to convert `o` to a value of type `MyRecord`. I've been able to accomplish that with this function I made:

```fsharp
[<Emit("(function () { var T = require('fable-core').Util.__types.get($0); return T ? Object.assign(new T(), $1) : $1; })()")>]
let ofPlainJs<'T> (typeName:string) (o: obj): 'T = failwith "JS only"
```

It's a bit ugly, but it gets the job done:

```fsharp
let v = o |> ofPlainJs<MyRecord> "Module.MyRecord"
```

This works great except it's a pain to have to specify the type name as a string every time. It will only work if the string exactly matches the corresponding key in Fable's `__types` map. The convention is easy enough to remember for custom types but isn't always predictable for built-in types (and may even change altogether in future Fable versions).

It would be nice if there was a function like this on the Fable.Core.Serailize module that didn't require the typeName parameter. Instead it would figure out the correct JS constructor to call based on the type parameter seen during Fable compilation. Is something like that even possible? Thinking something like:

```fsharp
val ofPlainJsObj<'T> : o:obj -> 'T
```

**Comment by alfonsogarciacaro** [comment]
The generic information is not available at runtime, but if you **inline** the function Fable will replace the generics with concrete types. This trick is used for example in the React helper to [access the type constructor](https://github.com/fsprojects/Fable/blob/master/import/react/Fable.Helpers.React.fs#L579-L580). You could do something similar:

```fsharp
open Fable.Import

let inline ofPlainJs<'T when 'T : (new : unit -> 'T)> (o: obj): 'T =
    unbox(JS.Object.assign(new 'T(), o))
```

I hope this helps! Could you give it a try and confirm if it works?

**Comment by funlambda** [comment]
Thanks again for the insanely quick response!

I will try that inline function tomorrow and see if it works, but wouldn't the type constraint `'T : (new : unit -> 'T)` prevent this solution from working with record types (since they don't have a constructor to call from F#)?

**Comment by alfonsogarciacaro** [comment]
Ups, you're right. We need to make it trickier then, maybe this works?

```fsharp
open Fable.Core

[<Emit("Object.assign(new $0(), $1)")>]
let private ofPlainJs' (cons: System.Type) (o: obj): 'T = failwith "JS only"

let inline ofPlainJs<'T> (o: obj): 'T = ofPlainJs' typeof<'T> o
```

**Comment by alfonsogarciacaro** [comment]
Can you please confirm if it works and close the issue if it does? Cheers!

**Comment by funlambda** [comment]
Sorry for the delay!

Originally it seemed to be working most of the time but was failing for some built-in types (eg. `Choice`). I got busy with other things and just recently came back to it after upgrading to latest Fable compiler and core.

Changes in v0.5.* must have fixed the issue -- now the code above works as expected, even for built-in types. Looks like the the generated type key strings are more standardized now, which seems to have fixed the issue with `Choice` as well as made my server-side serializer more reliable. 👍  👍

**Comment by alfonsogarciacaro** [comment]
No poroblem, glad to hear it's working for you know 😄
