### ISSUE TITLE
JSX with source maps?

### ISSUE THREAD

**Issue by bigjonroberts** [fable-compiler/Fable#3407]
### Description

I would like to use JSX with source maps and debugging and all the other goodies that are already set up in the SAFE Template.

### Repro code

I took a working freshly generated safe template project and attempted to convert the client to use the latest Fable and JSX.  When using 'source-map-loader', it chokes on the jsx. 'babel-loader' doesn't appear to be working either.  I'm open to solutions using other packaging/run tools than webpack, such as vite.

Here is the project that I attempted to upgrade/convert: https://github.com/bigjonroberts/safe-template-jsx

### Expected and actual results

I was hoping to get this working as using JSX makes it easier to collaborate with designers and developers coming from typescript or javascript.

### Related information

* Fable version: 4.0.4
* Operating system: Windows 10
* npm version: 8.19.4
* node version: v18.15.0

**Comment by bigjonroberts** [comment]
I'm fine opening a ticket with the SAFE Template project in addition to this issue or instead of this issue.  I just thought I'd start here with the fable experts first.

**Comment by alfonsogarciacaro** [comment]
Hmm, I had the feeling source maps work in apps using JSX, but I need to check. I am recently using Vite instead of Webpack so not sure about source-map-loader.

**Comment by delneg** [comment]
> Hmm, I had the feeling source maps work in apps using JSX, but I need to check. I am recently using Vite instead of Webpack so not sure about source-map-loader.
> 
> @delneg Have you used sorce maps with JSX?

Nope, in fact I haven't used source maps much at all, and did source-map-sharp at the time just for the fun of it (I'm using Rider, not VSCode)

Anyway, if I can help one way or another I'll try to do it - right now I don't particularly understand how source maps would function differently with JSX

**Comment by bigjonroberts** [comment]
I'll try it with vite for now and forgo source maps as JSX is more important to me. 

But to have both would be great. 

I honestly don't know enough about JS ecosystem and transpiling or packaging and modules yet or any of that to be of too much assistance on this right now outside of reporting and testing.

**Comment by OnurGumus** [comment]
If I recall correctly you can't intermix JSX code with Fable. Then it works fine.

**Comment by bigjonroberts** [comment]
I dug into this a little farther and source-maps are indeed working fine with JSX.  It's also working with the debugger for F# code embedded in the JSX.  I'm having some other issues that are apparently not related to source maps.  I will investigate further and will open another issue if needed.

**Comment by alfonsogarciacaro** [comment]
Thanks for confirming sourcemaps work with JSX @bigjonroberts. There's another error with latest version (4.1.3) that @OnurGumus reported on #3438, I have to fix that one.
