### ISSUE TITLE
[TS] Slow compilation of some union cases

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3411]
@alfonsogarciacaro I tried to make a relatively small repro, only happens for TS, not JS.

The attached file compiles 10x slower for TypeScript (than for JavaScript).
Can't really figure out why, seems to be just deeply nested ifs. There must be some additional work that's called for TypeScript quite often that slows it down.

One thing I noticed is if we remove (comment) all 3 occurrences of the case guard `when relaxWhitespace2`,
it makes it speeds up for TS as well (somehow the resulting decision tree gets compiled faster?). Not sure that helps though.

[LexFilter.fs.txt](https://github.com/fable-compiler/Fable/files/11184740/LexFilter.fs.txt)

**Comment by alfonsogarciacaro** [comment]
Wow, it's slow indeed. I need to investigate but my guess is this operation takes long time and repeats a lot with many union tests: https://github.com/fable-compiler/Fable/blob/31a92cd90196dbe726845d14452b953028a6ea83/src/Fable.Transforms/Fable2Babel.fs#L1759-L1774

Probably there's an opportunity to cache the reference to the `tagIdent` as it will be retrieved many times when compiling big decision trees to TypeScript.

**Comment by ncave** [comment]
@alfonsogarciacaro That was my first guess too, but unfortunately no, even if you comment the typescript portion of `transformUnionCaseTag` it's still slow. It helps a little bit, but that's not the main reason.

**Comment by ncave** [comment]
@alfonsogarciacaro I tried profiling it, it's completely different profile between compiling to TS and JS.
For TS it spends a *lot* of time in `transformIfStatement` and appending arrays, and in JS, it doesn't.
I know, not very helpful. It's probably something very obvious, I just don't see it.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for this! Actually I just realized the generated code is 1630 lines of code for JS... and 813,431 for TypeScript! 😮 

I've tried going back as far as 4.0.0-theta-009, which is the first tag that accepts the `quicktest-ts` target, and it also generates too much code. So there seems to be an issue remaining from the early stages of TypeScript compilation that causes code duplication in certain situations.

**Comment by ncave** [comment]
> generated code is 1630 lines of code for JS... and 813,431 for TypeScript! 😮

Amazing, must be a new record :)

**Comment by alfonsogarciacaro** [comment]
Seems to be this. If we remove the if branch it "only" generates 1900 lines: https://github.com/fable-compiler/Fable/blob/31a92cd90196dbe726845d14452b953028a6ea83/src/Fable.Transforms/Fable2Babel.fs#L1961-L1966

But then we need to "force" the bound idents  in the second switch (e.g. `stack_mut = rest_2!`) so TypeScript doesn't complain. I've sent #3412 for that, but it seems I broke other things along the way. Will try to have a look at it again tomorrow.

**Comment by alfonsogarciacaro** [comment]
Scratch that, I fixed the issue and the tests seem to be passing so maybe we can merge. Although it could be a nice idea to add your sample code as an integration test to check the size of the generated file is not too big.
