### ISSUE TITLE
Fable 4.0.5 breaks modules

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#3419]
### Description

with upgrade to Fable 4.0.6 we see multiple errors like

```
ERROR in ./out/fable_modules/fable-library.4.0.6/Guid.js 10:25
Module parse failed: Unexpected token (10:25)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| const guidHexCaptures = /^([0-9a-f]{8})-(([0-9a-f]{4})-)(([0-9a-f]{4})-)([0-9a-f]{2})([0-9a-f]{2})-([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/;
| export function toString(str, format, _provider) {
>     if (format && format?.length > 0) {
|         switch (format) {
|             case "N":
 @ ./out/Server/Shared/JSON.js 1:0-74 10:52-59 11:45-52
 @ ./out/RenderB2BInvoice.js
ERROR in ./out/fable_modules/fable-library.4.0.6/DateOffset.js 147:49
Module parse failed: Unexpected token (147:49)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
| }
| export function timeOfDay(d) {
>     const d2 = new Date(d.getTime() + (d.offset ?? 0));
|     return d2.getUTCHours() * 3600000
|         + d2.getUTCMinutes() * 60000
 @ ./out/RenderB2BInvoice.js 21:0-73 [279](https://gitlab/a-team/eCarApp/-/jobs/1081547#L279):58-62 279:84-88
```

@ncave @alfonsogarciacaro

**Comment by ncave** [comment]
@alfonsogarciacaro Possibly somehow related to #3412? Not sure.

There are very few differences between `fable-library` 4.0.5 and 4.0.6, here is an an example of one of them:

```js
        // v4.0.5
        switch (matchResult) {
            case 0:
                return true;
            case 1:
                return false;
        }
```
```js
        // v4.0.6
        switch (matchResult) {
            case 0:
                return true;
            default:
                return false;
        }
```

**Comment by forki** [comment]
I think 4.0.5 is already broken. I reverted back to 4.0.3 and it works.
I did not test 4.0.4

Слава Україні! Героям слава! ***@***.***> schrieb am Mi., 12.
Apr. 2023, 19:30:

**Comment by ncave** [comment]
@forki I see, so this is then probably something like [this](https://stackoverflow.com/questions/63759629/simple-webpack-build-fails-because-of-new-es-syntax), because 4.0.5 switched to using native JS `bigint` for `int64`/`uint64`.

Just for context, what Webpack version is being used?

**Comment by alfonsogarciacaro** [comment]
@ncave The PR for Bigint changed the target in fable-library/tsconfig.json to es2020, so the ?. operator is left as is. In principle it should be supported by main browsers, but I think @forki is developing a React Native app so maybe it's not supported yet... Or updating Webpack may be enough as you say.

**Comment by forki** [comment]
OK I see.

So I think the problem is that I need to upgrade webpack in my azure
function projects and it's not directly a fable issue.



Alfonso Garcia-Caro ***@***.***> schrieb am Do., 13. Apr.
2023, 00:36:

**Comment by alfonsogarciacaro** [comment]
@forki Please feel free to reopen until your issue is fixed. I've unlisted 4.0.6, I should have at least bumped the minor version when targeting more modern JS. Maybe you don't need to update Webpack but Babel if it's still in your toolchain. Can you please share your Webpack config?

**Comment by forki** [comment]
I actually managed to fix it by updating webpack. All good on my end. Thanks for the help @ncave @alfonsogarciacaro.
