### ISSUE TITLE
Specifying langversion

### ISSUE THREAD

**Issue by kerams** [fable-compiler/Fable#3423]
I'm trying to use a preview feature, but according to https://github.com/fable-compiler/Fable/issues/2607#issuecomment-968900884 Fable does not pick up lang versions from fsproj files. Does it mean there's no way to use preview features? What about having a command line parameter to force a specific lang version across all projects compiled by Fable?

**Comment by alfonsogarciacaro** [comment]
I'd have to check, but I think we have all features including preview ones enabled by default. It depends on the FCS version embedded with Fable.

It also depends on the feature itself. Some are entirely handled by FCS so we don't need to do anything. But in other cases we need to make changes in Fable to support the feature.

**Comment by kerams** [comment]
I'm trying to do

```fsharp
let synthesizeAudioLink (req: SynthesizeRequest) =
    sprintf Route.Synthesize (serialize req |> base64urlEncode)
```

fsproj contains `<LangVersion>preview</LangVersion>`, but Fable compilation fails with

```
.\src\Client\Common.fs(271,13): (271,29) error FSHARP: Feature 'String values marked as literals and IL constants as printf format' is not available in F# 7.0. Please use language version 'PREVIEW' or greater. (code 3350)
```

I don't think Fable needs any additional handling here.

**Comment by kerams** [comment]
> but I think we have all features including preview ones enabled by default

Oh, you're enabling each feature individually here? That would explain things, since this has been merged into fsharp main only a couple of weeks ago.

**Comment by ncave** [comment]
I updated Fable to latest FCS in #3424, hopefully it will help.

**Comment by alfonsogarciacaro** [comment]
Thanks @ncave!

@kerams Can you please try with Fable 4.1.0-beta-001? I have activated `--langversion:preview` when set in the main project.

**Comment by kerams** [comment]
All good, muchas gracias!
