### ISSUE TITLE
Fable changes syntax from 4.0.6 to 4.1.0 

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3430]
### Description

I am working on a fable-library (https://github.com/Freymaurer/ArcGraphModel/tree/Fable, this fork and branch) and noticed that my Fable.Mocha test are failing with fable `4.1.0` with the following error:

```
file:///C:/Users/Kevin/source/repos/ArcGraphModel/tests/ArcGraphModel.JsNativeTests/fable/src/ArcGraphModel/ArcType.js:1
import { Union } from "../../fable_modules/fable-library.4.1.0/Types.js";
         ^^^^^
SyntaxError: Named export 'Union' not found. The requested module '../../fable_modules/fable-library.4.1.0/Types.js' is a CommonJS module, which may not support all module.exports as named exports.
CommonJS modules can always be imported via the default export, for example using:

import pkg from '../../fable_modules/fable-library.4.1.0/Types.js';
const { Union } = pkg;

    at ModuleJob._instantiate (node:internal/modules/esm/module_job:123:21)
    at async ModuleJob.run (node:internal/modules/esm/module_job:189:5)
    at async Promise.all (index 0)
....
```

As i previously had set up something similiar and it worked i compared fable versions and noticed that the same tests run perfectly fine with fable `4.0.6` (Change fable version in `config/dotnet-tool.json` --> `dotnet tool restore`).

![image](https://user-images.githubusercontent.com/39732517/233668109-502e73d7-9b2f-403b-aa80-bab29f705611.png)

### Repro code

This is the repo: https://github.com/Freymaurer/ArcGraphModel/tree/Fable

#### prerequisites

- .NET 6 SDK
- nodejs (tested with ~v16)

#### setup

- dotnet tool restore
- npm install

#### Linux/macos

- run `build.sh runTestsJs`

#### Windows

- run `build.cmd runTestsJs`

### Expected and actual results

I expected fable to support Fable.Mocha setup under both version.

### Related information

* Fable version: `4.0.6`, and `4.1.0`
* Operating system: Windows 11
* Nodejs: v16.18.0
* Npm: 9.2.0

**Comment by MangelMaxime** [comment]
Hello @Freymaurer, you repo link leads to a 404 error.

**Comment by Freymaurer** [comment]
Ah sorry i didn't notice that the main repo was private. I will post a new link soon

**Comment by Freymaurer** [comment]
@MangelMaxime should be public now 👍

**Comment by MangelMaxime** [comment]
After think about it, I think your problem has been fixed in this PR: https://github.com/fable-compiler/Fable/pull/3429

@alfonsogarciacaro I think this issue answer your question from https://github.com/fable-compiler/Fable/commit/7db9778c68ad291883d96bffa9cda1ceb457a399. If there is a regression and we have the fix, releasing a bug fix is better 🙂

**Comment by alfonsogarciacaro** [comment]
Ok, ok, I've pushed a new version 😅 @Freymaurer Can you please try? BTW, if you are working on a library with Fable you may be interested in [this post](https://fable.io/blog/2023/2023-04-20-Better_Typed_than_Sorry.html) 👍

**Comment by Freymaurer** [comment]
I am out of office until wednesday, but then i will try :+1:

**Comment by Freymaurer** [comment]
Tested with `4.1.2` and works just fine! Thanks for having a look!

And thanks again for the linked post, we will discuss the related implications in our group 👍

**Comment by Freymaurer** [comment]
@alfonsogarciacaro Sadly i a seem to run into issues when trying to convert the library to typescript. What is the expected workflow to test fable typescript output? Can i still use Fable.Mocha?

**Comment by Freymaurer** [comment]
One of the issues seems to origin from Fable.Mocha. 

**Test file**
![image](https://user-images.githubusercontent.com/39732517/234558161-9fafbeb6-292a-4d3b-91d9-deca4c6d4e13.png)

With the error: `Cannot find module './fable_modules/Fable.Mocha.2.16.0/Mocha.fs.js' or its corresponding type declarations.`

And if i look into the folder i can see:

![image](https://user-images.githubusercontent.com/39732517/234558337-354a2267-aeeb-4192-9683-734009ff974d.png)

So the file extension is not correct. Not sure how to progress from here on.

**Comment by Freymaurer** [comment]
Same for imports from our dotnet library:

![image](https://user-images.githubusercontent.com/39732517/234560381-17f69f1c-fade-415b-b21d-032fe5f01258.png)

**Comment by alfonsogarciacaro** [comment]
Oh my, apparently we didn't test this with libraries 😅 I think I know what the problem is, I will fix it. Thanks for reporting @Freymaurer!

**Comment by Freymaurer** [comment]
Ah what i also wanted to ask. Are there some docs where all those fable specific attributes are explained?

I found `[<Erase>]`, [<Mangle(false)>]` , `[<AttachMembers>]` and (not fable specific but useful) `[<CompiledName>]`.

**Comment by MangelMaxime** [comment]
Hello @Freymaurer 

documentation about the different attributes can be found on Fable documentation. Most of documentation relation to code generation is located on these 2 pages:

- https://fable.io/docs/communicate/js-from-fable.html
- https://fable.io/docs/communicate/fable-from-js.html

---

Documentation for [`[<Erase>]`](https://fable.io/docs/communicate/js-from-fable.html#erase-attribute)

Documentation for [`[< Mangle >]` and [<AttachMembers>]](https://fable.io/docs/communicate/fable-from-js.html#custom-behaviour)

**Comment by alfonsogarciacaro** [comment]
@Freymaurer What options are you passing to the compiler? Are you using `-e .ts`? I just tried compiling a project with a library dependendy to TypeScript and for me it worked.

**Comment by Freymaurer** [comment]
Hey Thanks for your work!
I updated fable and fable-library and removed the previously generated output. Now the filenames are correctly referenced but i have over a hundred errors. The same thing works if i just remove `--lang ts`. 

32 errors alone in Fable.Mocha, for example:

```cmd
tests/ArcGraphModel.JsNativeTests/fable/fable_modules/Fable.Mocha.2.16.0/Mocha.fs.ts:636:8 - error TS2339: Property 'innerHTML' does not exist on type 'Html_IDocElement'.

636     el.innerHTML = node.Content;
           ~~~~~~~~~

tests/ArcGraphModel.JsNativeTests/fable/fable_modules/Fable.Mocha.2.16.0/Mocha.fs.ts:641:16 - error TS2339: Property 'setAttribute' does not exist on type 'Html_IDocElement'.

641             el.setAttribute(forLoopVar[0], forLoopVar[1]);
                   ~~~~~~~~~~~~

tests/ArcGraphModel.JsNativeTests/fable/fable_modules/Fable.Mocha.2.16.0/Mocha.fs.ts:651:16 - error TS2339: Property 'appendChild' does not exist on type 'Html_IDocElement'.

651             el.appendChild(childElement);
                   ~~~~~~~~~~~
```

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for checking @Freymaurer! Unfortunately this is kind of expected, as most of the bindings were not written to be Typescript compliant. I will check to see if at least we can build your project alone, even if the tests have to be run in JS.

**Comment by MangelMaxime** [comment]
Doing some clean up I think the original issue has been fixed
