### ISSUE TITLE
Wrong range for code compiled from inline functions

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/Fable#3435]
### Description

As you can see, it is showing an error on line 102 which doesn't exist. It is way past the limit.

![Screenshot (185)](https://user-images.githubusercontent.com/6266635/234585062-27abd932-0525-4239-8985-35ff4d437292.png)

### Repro code

Here is the repo branch where I put it: https://github.com/mrakgr/MIP-And-Giraffe/tree/fable-line-bug

I tried making a minimal example, but I failed. On the online REPL, I get this kind of result.

![Screenshot (184)](https://user-images.githubusercontent.com/6266635/234583508-bfe24e44-314b-4360-a4e4-41f3d9ea88d3.png)

I expected to get compilation errors due to those typeofs, but instead it just passes nulls. Is the online REPL using an older version of Fable, maybe?

### Expected and actual results

I expected it to show an error on line 74.

### Related information

* Fable version: 4.0.6
* Operating system: Win 10

**Comment by alfonsogarciacaro** [comment]
I've tried to fix the range for inline functions, but in the case of `typeof` I've changed the range to call-site because this should be more helpful for the users to fix the error. Can you please try with Fable 4.1.3?

**Comment by mrakgr** [comment]
Yeah, it works fine now.

![Screenshot (189)](https://user-images.githubusercontent.com/6266635/235233876-1d5253b2-304e-48e9-9ab9-cc20d78e0755.png)

**Comment by alfonsogarciacaro** [comment]
Awesome, thanks a lot for confirming!
