### ISSUE TITLE
Don't ignore error when loading plugin

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3441]
### Description

In the past, I had the feeling that the plugin version compatibility detection is off and this https://github.com/elmish/react/issues/87 seems to confirm it.

I feel like if the version are not compatible instead of crashing Fable still compile the code but without taking into consideration the plugin. Leading to situation where the code is compiling but incorrect because plugin is not applied.

This issue needs further investigation but I wanted to log it so it can be tracked.

### Related information

* Fable version: I think Fable 3 and Fable 4 are impected

**Comment by MangelMaxime** [comment]
Using Fable 4 with a plugin expecting version 3.0 fail as expected (I think Fable doesn't expect to support the same AST between major versions) ✅

![CleanShot 2023-05-05 at 17 29 46](https://user-images.githubusercontent.com/4760796/236501826-0703e0d6-4ac6-418f-96f3-26c4653bba8f.png)

Using Fable 3 with a plugin expecting version 4.0 succeeds instead of failing ❌

![CleanShot 2023-05-05 at 17 34 15](https://user-images.githubusercontent.com/4760796/236502896-9461c361-9f46-45cc-a8b8-5311178b439a.png)

I suppose the problem is also present in Fable 4 if we have a plugin expecting version 5.0. So both Fable 4 and Fable 3 needs a fix, in order to improve the transitioning between major releases.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro I implemented a fix for Fable 3 but I think something similar needs to be ported to Fable 4.

Perhaps, by trying to give more context on the error side to have a better error message than the one I made for Fable 3.

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! Yes, probably we can port your code to Fable 4, or make the plugin loader also reject new major versions. Can you please send a new PR for `main` branch?

**Comment by MangelMaxime** [comment]
> or make the plugin loader also reject new major versions

I agree doing that is best. And actually, Fable kind of does that later in the code when trying to apply the plugin.

The problem, in the case I covered for Fable 3 was that the code responsible for loading the assembly throw an exception:

![image](https://github.com/fable-compiler/Fable/assets/4760796/145dfe85-7567-4035-b40d-a44042e778f2)

So we had an error before being able to load the plugin and get access to its version information. I don't know what is causing this load error, perhaps this is because of an incompatible dependency like FSharp.Core or Fable.Core having a different version than he one loaded by Fable.

------

I can indeed, port my code to the `main` branch and move the version detection logic at the plugin loading stage too if you want. Because, loading a plugin and failing later to apply it doesn't seem really intuitive. And it is probably better if Fable stop here instead of letting the user think that all is fine unless they read the console logs.
