### ISSUE TITLE
Why is the import not included in the compiled JS file?

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/Fable#3443]
### Description

I've rebuilt an abandonware Fable project [here](https://github.com/mrakgr/Rebuild.Fable.SignalR) by going over the old one and including the new things file by file.. I've made sure to pack it with the sources included.

The problem is when I try to use it in a real program an import is missing.

![Screenshot (197)](https://user-images.githubusercontent.com/6266635/236634344-b40dc2a5-775d-479f-b49a-4a5043ffffad.png)
![Screenshot (198)](https://user-images.githubusercontent.com/6266635/236634345-55c7a99d-b02c-463d-b4e2-7656282f704f.png)

As you can see the import is simply nowhere in the file.

![Screenshot (199)](https://user-images.githubusercontent.com/6266635/236634346-81d68847-16e3-4c28-b188-b344040da123.png)

In the library itself, this is the only place where it is importing anything.

I am not sure what I should do here.

### Related information

* Fable version: 4.0.3.
* Operating system: Win 10.

**Comment by mrakgr** [comment]
I am importing it from the Github repo via paket.

Also, I tried `dotnet run`ing it with 4.1.3 of Fable, but not only am I getting the same errors as the above, but in the terminal I am getting some weird source map errors that weren't there before.

![Screenshot (200)](https://user-images.githubusercontent.com/6266635/236636467-d1309b3a-4b55-47e5-b22a-6cfc75cc1122.png)

They aren't happening on an earlier branch of the [repo](https://github.com/mrakgr/CFR-In-Fable/tree/micros1). I'll try backtracking tomorrow and seeing what causes it.

**Comment by adelarsq** [comment]
Maybe something with Vite. Do you have references for the file that is missing?

**Comment by mrakgr** [comment]
What do you mean by a reference? The original `App.js` in the output folder? I've checked it just now and the import isn't in it.

Or do you mean the `paket.references` file? You can find it in the [repo here](https://github.com/mrakgr/CFR-In-Fable/blob/783948b89e26db6a558813234a0f9d52cd45a36c/src/Client/paket.references). I had to rename the package id to prefix it with `Rebuild` otherwise it might try downloading the nuget package.

Here are the [dependencies](https://github.com/mrakgr/CFR-In-Fable/blob/783948b89e26db6a558813234a0f9d52cd45a36c/paket.dependencies) and the paket [lock](https://github.com/mrakgr/CFR-In-Fable/blob/783948b89e26db6a558813234a0f9d52cd45a36c/paket.lock) file respectively.

**Comment by mrakgr** [comment]
I am not sure if this is what you meant, but I just realized that if I add the reference to the project that is in `paket-files`, it works correctly.

![Screenshot (201)](https://user-images.githubusercontent.com/6266635/236642430-24258140-6d02-4f72-8efa-c538f62e5855.png)

`paket-files` is where paket puts all the repo references. I'll make a minimal repo.

**Comment by mrakgr** [comment]
Link: https://github.com/mrakgr/CFR-In-Fable/tree/min-repro1

Here is the first branch with the incorrect results.

```fs
module App

open Fable.SignalR

let hub : HubConnection<obj,obj,obj,obj,obj> =
    SignalR.connect <| fun x -> x.onMessage ignore
```

When I try to compile this with `dotnet fable -s -o output` I get:

```js
export const hub = Fable_SignalR_SignalR_connect_8CA73D6((x) => Fable_SignalR_HubConnectionBuilder$5__onMessage_2163CAFC(x, (value) => {
}));

//# sourceMappingURL=App.js.map
```

Link: https://github.com/mrakgr/CFR-In-Fable/tree/min-repro2

When I compile it in this repo, I get the following, plus another 200 lines that were omitted.

I only removed the reference the `paket.references` file, and added a direct one to the repo.

```js
import { HubConnectionBuilder$5__onMessage_2163CAFC } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/SignalR.js";
import { HubConnectionBuilder$5_$ctor_Z66CB2AA1 } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/SignalR.js";
import { HubConnection$5_$ctor_3ED56BCC, Bindings_signalR } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/HubConnection.js";
import { Json_TextMessageFormat_write, Json_TextMessageFormat_parse, Json_JsonProtocol_$ctor, MsgPack_parseMsg, MsgPack_MsgPackProtocol_$ctor } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/Protocols.js";
import { toFail, printf, toText } from "./fable_modules/fable-library.4.1.3/String.js";
import { singleton, reverse, cons, empty } from "./fable_modules/fable-library.4.1.3/List.js";
import { Reader__Read_24524716, Reader_$ctor_Z3F6BC7B1 } from "./fable_modules/Fable.Remoting.MsgPack.1.18.0/Read.fs.js";
import { fromInt32, op_Subtraction, compare, op_Addition, toUInt64 } from "./fable_modules/fable-library.4.1.3/BigInt.js";
import { class_type, enum_type, int32_type, obj_type, unit_type, uint64_type } from "./fable_modules/fable-library.4.1.3/Reflection.js";
import { InvokeArg$1_$reflection, MsgPack_Msg$4, MsgPack_Msg$4_$reflection } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/Shared.js";
import { writeObject } from "./fable_modules/Fable.Remoting.MsgPack.1.18.0/Write.fs.js";
import { choose, addRangeInPlace } from "./fable_modules/fable-library.4.1.3/Array.js";
import { equals } from "./fable_modules/fable-library.4.1.3/Util.js";
import { SimpleJson_readPath, SimpleJson_parse } from "./fable_modules/Fable.SimpleJson.3.24.0/SimpleJson.fs.js";
import { map, value as value_10 } from "./fable_modules/fable-library.4.1.3/Option.js";
import { Convert_serialize, Convert_fromJson } from "./fable_modules/Fable.SimpleJson.3.24.0/Json.Converter.fs.js";
import { createTypeInfo } from "./fable_modules/Fable.SimpleJson.3.24.0/TypeInfo.Converter.fs.js";
import { Result_Map, FSharpResult$2 } from "./fable_modules/fable-library.4.1.3/Choice.js";
import { HubRecords_CloseMessage_$reflection, HubRecords_PingMessage_$reflection, HubRecords_CancelInvocationMessage_$reflection, HubRecords_StreamInvocationMessage$1_$reflection, HubRecords_CompletionMessage$1_$reflection, HubRecords_StreamItemMessage$1_$reflection, HubRecords_InvocationMessage$1_$reflection } from "./paket-files/github.com/mrakgr/Rebuild.Fable.SignalR/src/Fable.SignalR/Protocols.js";

export const hub = (() => {
    let protocol_2, protocol, protocol_1;
    const _ = ((x_3) => HubConnectionBuilder$5__onMessage_2163CAFC(x_3, (value_9) => {
    }))(HubConnectionBuilder$5_$ctor_Z66CB2AA1(new Bindings_signalR.HubConnectionBuilder()));
    return HubConnection$5_$ctor_3ED56BCC((protocol_2 = (_.useMsgPack ? ((protocol = MsgPack_MsgPackProtocol_$ctor(), {
        name: "messagepack",
        version: 1,
        transferFormat: 2,
        parseMessages(input, logger) {
            let arg_3;
            try {
```

**Comment by baronfel** [comment]
I _think_ I might have a similar error with the webpack build of Ionide on 4.1.3. Here's the error I see after updating to latest:

```shell
ERROR in ./out/Components/Fsi.js 19:0-133
Module not found: Error: Can't resolve '../paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js' in 'D:\Code\ionide-vscode-fsharp\out\Components'
resolve '../paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js' in 'D:\Code\ionide-vscode-fsharp\out\Components'
  using description file: D:\Code\ionide-vscode-fsharp\package.json (relative path: ./out/Components)
    using description file: D:\Code\ionide-vscode-fsharp\package.json (relative path: ./out/paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js)
      no extension
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js doesn't exist
      .js
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.js doesn't exist
      .json
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.json doesn't exist
      .wasm
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.wasm doesn't exist
      as directory
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js doesn't exist
 @ ./out/fsharp.js 21:0-62 130:12-23

ERROR in ./out/Components/SolutionExplorer.js 16:0-110
Module not found: Error: Can't resolve '../paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js' in 'D:\Code\ionide-vscode-fsharp\out\Components'
resolve '../paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js' in 'D:\Code\ionide-vscode-fsharp\out\Components'
  using description file: D:\Code\ionide-vscode-fsharp\package.json (relative path: ./out/Components)
    using description file: D:\Code\ionide-vscode-fsharp\package.json (relative path: ./out/paket-files/ionide/ionide-vscode-helpers/src/Fable.Import.VSCode.js)
      no extension
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js doesn't exist
      .js
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.js doesn't exist
      .json
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.json doesn't exist
      .wasm
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js.wasm doesn't exist
      as directory
        D:\Code\ionide-vscode-fsharp\out\paket-files\ionide\ionide-vscode-helpers\src\Fable.Import.VSCode.js doesn't exist
 @ ./out/fsharp.js 12:0-74 99:16-26
```

This missing Fable.Import.VSCode file is type definitions only - a sibling file called `Helpers.fs` has actual logic and is correctly emitted by Fable, but these types-only files don't seem to be transpiled for whatever reason. The behavior is not present on 4.0.6 - we build successfully then (though the types-only files are still not present in the build output).

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for creating the repo @mrakgr! I cloned it, checked min-repro2 and built it. I had to upgrade the Fable.SimpleJson dependency to fix a compilation error, but besides that when running `dotnet fable src/Client -s -o output` and inspect the generated App.js I don't see any missing reference.

**Comment by mrakgr** [comment]
Link: https://github.com/mrakgr/CFR-In-Fable/tree/min-repro1

The second link is for comparison, it actually compiler properly. This one doesn't even even though they should be linking to the same package, sorry for the confusion.

**Comment by alfonsogarciacaro** [comment]
Ah, ok, thanks @mrakgr. Sorry, I misunderstood. I can reproduce the issue now.

Hmm, this is tricky. Fable has some expectations about libraries distributed through Nuget: basically the package must include the sources in a `fable` folder (Fable also reads some metadata from the .nuspec file). But Paket seems to build github dependencies in a different way than what `dotnet pack` does, so Fable cannot identify the sources and compilation fails.

I cannot think of an easy solution to this. The workaround is what you already did: use github source in paket.dependencies but then don't add it paket.references and use a project reference instead.
