### ISSUE TITLE
ParamArg arrays whose arguments are upcasted to obj implicitly are passed incorrectly

### ISSUE THREAD

**Issue by mrakgr** [fable-compiler/Fable#3451]
### Description

I am playing with the SignalR bindings and stumbled upon a case where paramArg arrays are not being passed in correctly.

### Repro code

Here is a minimal example.

```fs
module Client.Test

open System

type Q =
    abstract f : string * [<ParamArray>] args : obj [] -> unit

let q : Q = failwith ""
q.f ("asd", [|"Hello"|])
q.f ("qwe", [|box "Hello"|])
```

### Expected and actual results

```js
export const q = (() => {
    throw new Error("");
})();

q.f("asd", ["Hello"]);
q.f("qwe", "Hello");
```

I expected that both of the last two lines would have the second argument passed in as a string.

### Related information

* Fable version: 4.0.6 & 4.1.3
* Operating system: Win 10

**Comment by alfonsogarciacaro** [comment]
This is expected. If you run this code in .NET:

```fsharp
type Q() =
    member _.f(_: string, [<ParamArray>] args : obj[]) =
        args[0].GetType() |> printfn "%O"

let q = Q()
q.f ("asd", [|"Hello"|])
q.f ("qwe", [|box "Hello"|])
```

You get the following:

```
System.String[]
System.String
```

Using `ParamArray` with `obj[]` is tricky: in the first case you're passing `string[]`. The F# compiler doesn't cast it to `obj[]` but to `obj` so it passes the array as is. However in the second case, the compiler sees `obj[]` so it understands it must spread the arguments.
