### ISSUE TITLE
Interesting date formatting with Fable

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#3459]
```fs
open System
open Fable.Core
open Fable.Core.JsInterop

let options = {|
    timeZone = "Europe/Amsterdam"
    day = "2-digit"
    year = "numeric"; month = "2-digit";
    hour = "2-digit"; minute = "2-digit";
    hour12 = false
|}


[<Emit "new Intl.DateTimeFormat(['en'], $0)">]
let formatter options = jsNative

let formatParts (d:DateTimeOffset) : string [] =
    let parts : obj [] = (formatter options)?formatToParts(d)
    parts |> Array.map (fun x -> x?value)

let formatAsGermanDateTime (d:DateTimeOffset) =
    let parts = formatParts d
    sprintf "%s.%s.%s %s:%s" parts.[2] parts.[0] parts.[4] parts.[6] parts.[8]

let date = DateTimeOffset.Parse("2022-10-30T23:53:38Z")

printfn "%A" (formatAsGermanDateTime date)
```

[Fable REPL](https://fable.io/repl/#?code=PYBwpgdgBAygngZwC5gLYChSSgMQIYBGANmAHQDCwATmJuNPsWZTaQFIICSEKVo66EkiigkAS2AQEUALxQA3gB90UVVHGowALUlhZUAEQBRAK59wAegCCqZGCoATPKgMq1TuPoMAmALQOxAHMxJFc1KDgwPCovCBNNKjEAYwMAbihUSSQACy8-AODQ1LdVbOAzPP8gkLSMsTiUSoKa4vCyswBGb30AMzwiBFpFAF8BdABtAB4jVBDDCDAAdyhuJCJSABE8FAAVMU0calRtgApxgHJIc4BdABooABIABgBKAwA+a8EwYR6j7d4IhA4kk0jkACsEAA5bZiAButG+v3+SAACtEkNITg4AFxbXb7MAAeR6PUGSBeUBxUGQiQggSg42ushKUCEUBAGOk1OABHBjOZchOfyoxyQgNEEikLwA-CKxTtgOiqJjsS9WZyVdJFO8oFYqFQ8HBSMcQFBhSZoAAPKC+XVWmVw-omMDqpFQeXbKwIADi9mOEHxYD2mnNuKDIeJpPJlJkrPZmsxvRRyqTDlZCBAdKQPUMAFIEKQC0XpAWcQWDByuaRxt5mYnC+MnvXq+MACwtrU1gBsncxNYAHF93U5GnII4SSWSfqRlYMTj4nt4-B0nr4AMxPHbedc4gCsu-XA60BjdWfqOegBjzVkrwpR3r9orwge2wcJUFHrqAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwssOYLrBCoSKzhwAjDmiGYA3nGd-MxtLkxigQdFBCAFyYAOScNNp0SNqYAHJIAO4xADSYENwcuqQoEkhqvv44CmDkKFB0AOZc0aU8yeWVmAC+FdjASrb2jogqqBgIwG4eTrhojJh0aKy6UtpimFyhSMurYjD9cwwzwIcLSyz6Ulxo9Vzrm-jLSFc3dHeWB4zHh-sSKFwMFC6M6sP4AoHiDKLMAgVgAVgAjAAmcQgJCNcDw5EfJRgwG6fZKH4jKZCeAjVSwIA&css=Q)

this prints "31.10.2022 24:53" - which is kind of unusal. ;-)

Any ideas what might going on here?

**Comment by MangelMaxime** [comment]
Well, executing the same code in JavaScript gives the same result:

<img width="429" alt="CleanShot 2023-05-17 at 17 22 53@2x" src="https://github.com/fable-compiler/Fable/assets/4760796/af92f578-45e1-4413-bcb2-f0459c803d6c">

So I think this is not a Fable specific bug but it is indeed strange.

*Congrats you found a way to have more time your day 😉*

**Comment by MangelMaxime** [comment]
People on this [SO thread](https://stackoverflow.com/questions/65604554/intl-datetimeformat-returns-an-hour-over-24) propose to use `hourCycle: 'h23'` instead `hour12: false`

Which gives this result, and I think this is correct because Amsterdam is UTC+1 if I am not wrong.

![CleanShot 2023-05-17 at 17 27 42@2x](https://github.com/fable-compiler/Fable/assets/4760796/87e30aea-ed94-42e1-b56a-8dd1a6b73785)

Perhaps, there is somewhere on earth where people write 24 instead 00 for the hours 🤷‍♂️

**Comment by forki** [comment]
Thanks so much. I'm looking forward to the day when everyone just uses UTC.

Maxime Mangel ***@***.***> schrieb am Mi., 17. Mai 2023,
17:29:
