### ISSUE TITLE
When switching between target Fable doesn't recompile the `fable_modules`

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3464]
### Repro code

1. `mkdir my-fable-project`
1. `cd my-fable-project`
1. `dotnet new console -lang F#`
1. `dotnet new tool-manifest`
1. `dotnet tool install fable`
1. `dotnet fable`
1. `dotnet fable --lang python`

See that `fable_modules/fable_library` contains the `.js` version of the files and not the python version.

So the user cannot execute the python version of is code. The solution right now, is to manually delete the `fable_modules` folder so Fable doesn't have an existing cache.

I think it would be nice, when using a language to check that the version of `fable_modules` exist for that languages. 

Must have?: I think it would be nice if several languages can exist side by side. My reason, is that when working on cross platform libraries it means that it is possible to run several Fable instance and tests in parallels.

### Related information

* Fable version: `4.1.4`
* Operating system: OSX

**Comment by ncave** [comment]
Also, need to make sure the "cache" is not stale. IMO we should always replace it with the latest `fable-library-*` that Fable carries, or at least have clear rules in what circumstances it will not be replaced.

**Comment by MangelMaxime** [comment]
I took a look at this issue.

I was able to make the cache invalid if the language changed and also decided to always delete the `fable_modules` directory when the cache is invalid. I think this is better to work with a clean state rather than override files and keeps some potential non useful files.
