### ISSUE TITLE
proposal for rust: make it easy to define `#[repr(C)]` structs and `#[no_mangle] extern "C" fn` constructs from F# code

### ISSUE THREAD

**Issue by smoothdeveloper** [fable-compiler/Fable#3468]
### Description

I am playing with the rust target and modified this repository to enable:

```fsharp
[<ReprCAttr;Struct>]
type ExternStruct =
    {
        a: int
        b: int
    }
[<NoMangleExternCAttr>]
let extern_c_function data =
    printfn $"a: {data.a} b: {data.b}"
```

to be supported by rust target, turning it into functions that can bind to C:

```rust
#[repr(C)]
#[derive(Clone, Copy, Debug, Default, PartialEq, PartialOrd, Hash, Eq,
         Ord,)]
pub struct ExternStruct {
    pub a: i32,
    pub b: i32,
}
#[no_mangle]
pub extern "C" fn extern_c_function(data: Main::ExternStruct) {
    println!("a: {} b: {}", &data.a, &data.b,);
}
```

Currently, with current compiler, you can only add `#[repr(C)]` and `#[no_mangle]` but can't produce `extern "C"`.

Wondering if there is a way around that I didn't find.

@ncave if this makes sense, I can make a PR for you to review and help me adjust the changes if wanted.

**Comment by ncave** [comment]
@smoothdeveloper Sure, if you want to add a new `ExternCAttribute` (i.e. `[<ExternC>]`, go ahead.
The rest (`repr(C)`, `no_mangle`) as you said can already be generated using `OuterAttr`.

Unfortunately this means a change in `Fable.Core` which is infrequently released.
Another option if you don't want to wait, would be to check for some non-existing Rust attribute as a marker, and convert it to `extern "C"` in the decl, i.e. something like this: `[<OuterAttr("extern_C")>]`.

**Comment by MangelMaxime** [comment]
If I may, I think it is better to make an addition to Fable.Core instead of a hacky solution on top of string.

Releasing Fable.Core using a minor bump should be ok, as this impact only the Rust portion of its API.

**Comment by smoothdeveloper** [comment]
@MangelMaxime @ncave are the concerns with the additional attributes that it require changing Fable.Core api surface and release?

I can also make my current suggestion to work for attributes that are defined in other assemblies than Fable.Core and just release a Fable.Rust.FFI fable package that define the attributes. we can release this package separately than Fable.Core.

@ncave is the suggestion to have those two attributes?

```fsharp
[<ExternC>]
let add a b = a + b
[<Struct;ReprC>]
type Struct = { x: int; y: int }
```

I can adjust:
* `ExternC` adds the `no_mangle` + `extern "C" ` decoration
* `ReprC` adds the `repr(C)` attribute to the types

**Comment by MangelMaxime** [comment]
> I can also make my current suggestion to work for attributes that are defined in other assemblies than Fable.Core and just release a Fable.Rust.FFI fable package that define the attributes. we can release this package separately than Fable.Core.

Doing so, would make Rust unique compared to others targets. I think there was a discussion in the past, and the decision was to keep a single Fable.Core package with Fable.Core.JS, Fable.Core.Rust, Fable.Core.Python, etc. in it.

Personally, I am not concerned with releasing new version of Fable.Core

Regarding the effect of the attributes, I think it is better to have an attribute to 1 thing at a time. If the attribute does several thing, then if in the future we discover that it should only do 1 thing it will be difficult to fix has to would break all the existing binding that use it.
