### ISSUE TITLE
Fable2Rust.GetImportName when resolving module path gives an absolute path to stableStringHash

### ISSUE THREAD

**Issue by smoothdeveloper** [fable-compiler/Fable#3470]
I'm trying to figure out how to properly use the compiler for using in a library project (not one with main.fs with all the `#[path = "somemodule.rs"]`)

I'm seeing the module path that is resolved using `stableStringHash` is done using absolute file paths and was wondering if this was done on purpose?

When I compile a repository where I have my own "lib.rs" with similar `#[path ...]` attributes as those that fable would put in the main.rs, the module name seems to have changed when I do it on another machine (compiling on it gives different absolute paths).

I also wonder if there is a way around manually maintaining those imports (they come with `pub use module_abababa::*`) when trying to build a lib crate, and I can't rely on this since the module name change on another machine.

**Comment by ncave** [comment]
@smoothdeveloper You can have a library project with `src/lib.fs` instead of `src/main.fs`.

Yes, perhaps we can try to calculate the module hash based on relative path instead of absolute path, to make it more stable across machines.

**Comment by smoothdeveloper** [comment]
@ncave thanks, I'm having a `lib.rs`, so I've put a last.fs and can see the hash that works on a given machine generated there for convenience.

Do you know if it would break to use the relative path to the fsproj (which in fact come in the code, as far I troubleshooted)? in context of several projects or even bare rust crates? the main issue is probably "link" items in fsproj.

I'm not yet at ease with all of this and not clear how to improve beside the first step to make the hash stable on the machines, and trying to better understand how I can make the system work in library environment only in mostly rust codebase.

**Comment by ncave** [comment]
@smoothdeveloper I changed it to hash the relative path to last file (cause that's what the relative module path is). Let me know if that works for you.

**Comment by smoothdeveloper** [comment]
@ncave, I gave it a quick look on 2 machines and it seems to be consistent now, that's great!

I was wondering how to pull the imports in my **lib.rs** (which I write in rust, manually), I'm not sure if `pub use ` syntax could help get the imports that end up being in the generated **last.fs.rs** (last.fs is last file of my library) in my case?

**Comment by ncave** [comment]
@smoothdeveloper `pub use` re-exports everything in your `last.fs`, so you should be able to use anything from it (including wildcard use). But perhaps I'm missing your point, feel free to elaborate if you need to.

**Comment by smoothdeveloper** [comment]
Let me try to describe the concrete issues I'm facing:

# issue 1

about what we were discussing, I'm trying

```rust
#[path = "last.fs.rs"]
mod last;
pub use last::*;
```

but it creates all the structure into `crate::last::*` rather than `crate::*`, making the fable code not compile.

# issue 2

modulename1/decls.fs
```fsharp
namespace modulename1.decls
type A = { a: int }
```

lib.rs
```rust
#[path = "./modulename1/decls.fs.rs"]
mod module_abcdef;
pub use module_abcdef::*;

fn f() {
  let a = modulename1::A{a:1};
  modulename1::f(a);
}
```

modulename1/mod.rs

```rust
fn f (decls::a:A) {

}
```

* in lib.rs, I can't reach modulename1::f due to import of modulename1/decls.fs.rs
* in modulename1::f I can't reach modulename1/decls.fs.rs types

I'm not implying my issues are related with fable, but my shortcomings with rust and how the module system interacts with the fable2rust compilation system makes me stumble a bit on this type of issues.

**Comment by ncave** [comment]
@smoothdeveloper 
- Issue 1:
I tested it, if your import is in lib.rs, i.e.:
lib.rs
```rs
#[path = "last.fs.rs"]
mod last;
pub use last::*;
```
they you'll see the contents of `last.fs.rs` in both `crate::last::*` and re-exported to `crate::*`.
- Issue 2:
Perhaps you're mixing (overwriting) the `modulename1` module with your own `modulename1/mod.rs`.
I don't have a good picture of what you're trying to achieve, but in general it may be better to try to avoid mixing Rust folder-based modules and Fable-generated modules. Also, currently Fable-to-Rust support for F# namespaces is limited, so not using namespaces might help. To clarify, Rust doesn't natively support namespaces, so they are currently generated as modules, and we still need to implement a process to properly merge those namespace modules, otherwise they hide each other.

**Comment by smoothdeveloper** [comment]
Would there be a way for fable generated code to not have to rely on crate rooted paths with those hashes but using relative paths with super only?

**Comment by smoothdeveloper** [comment]
> I don't have a good picture of what you're trying to achieve

* I'm trying to check the kind of interop and layout of code files I can manage to get working, in a rust codebase (that integrates a C++ one) 
* I'd like to use subfolders with either or both rust & F#
* I may need to put forward declaration in my F# code that are erased or emit rust code to access parts of the rust codebase of the same crate

> but in general it may be better to try to avoid mixing Rust folder-based modules and Fable-generated modules.

This creates a tension that should ideally be solvable, I think for now, I need to work around by pulling the module hashes into some mod.rs files.

ideas (that may be dead end):
* having a stable path to reference fable generated code anywhere in rust hosting codebase, even if this path has something special (like crate::fable2rust::...), instead of the several module_xyz
* having minimum edits to perform or some flags in case lib.rs or main.rs need to remain pure rust, not generated by fable
* maybe some convention (such as namespace matching 1 to 1 the folder and filename allows to retain the code in the same place
* if it is possible to check presence of rust files in same folder, and even parse the mod declarations in mod.rs, there is something clever to do?
* the compiler could be editing lib.rs main.rs or mod.rs files with a section that fable rust recognizes when they are defined in rust

**Comment by ncave** [comment]
@smoothdeveloper 
> Would there be a way for fable generated code to not have to rely on crate rooted paths with those hashes but using relative paths with super only?

> I'd like to use subfolders with either or both rust & F#

Is it possible to get a very small sample repo (or zip a few files together as an attachment), to illustrate what issues are you running into when using it from a sub-folder?
