### ISSUE TITLE
[Rust] Add proper namespace support

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#3474]
Since Rust doesn't natively support namespaces, currently they are generated as Rust modules.
This only works for unique namespaces (per project), otherwise some Rust modules will hide others' content.

The code generation needs to somehow properly merge all those namespace modules to prevent some of them hiding others.

Minimal example:
```fs
namespace A.B.C
type MyType = MyType of float

namespace A.B.D
type MyType = MyType of int64
```

```rs
pub mod A {
    use super::*;
    pub mod B {
        use super::*;
        pub mod C {
            use super::*;
            #[derive(Clone, Debug, PartialEq, PartialOrd,)]
            pub enum MyType { MyType(f64), }
        }
    }
}
pub mod A {
    use super::*;
    pub mod B {
        use super::*;
        pub mod D {
            use super::*;
            #[derive(Clone, Debug, PartialEq, PartialOrd, Hash, Eq, Ord,)]
            pub enum MyType { MyType(i64), }
        }
    }
}
```
Here `A.B.C` is being hidden (unreachable).

**Comment by smoothdeveloper** [comment]
I assume this is the desired output:

```rust
pub mod A {
    use super::*;
    pub mod B {
        use super::*;
        pub mod C {
            use super::*;
            #[derive(Clone, Debug, PartialEq, PartialOrd,)]
            pub enum MyType { MyType(f64), }
        }
        pub mod D {
            use super::*;
            #[derive(Clone, Debug, PartialEq, PartialOrd, Hash, Eq, Ord,)]
            pub enum MyType { MyType(i64), }
        }
    }
}
```

I'm suspecting it would still not help to merge with rust written modules, but it would avoid clashes with F# code itself, which is good.

**Comment by ncave** [comment]
@smoothdeveloper Correct, the task would be to properly merge all namespace levels, potentially declared in different files (or same file).

**Comment by smoothdeveloper** [comment]
what about having 1 file per namespace at the root, and the modules brought into them?

It will be unwieldy to have all in the last file.

I also think there should be some solution to allow rust library to merge, but I don't know rust enough to even figure my own troubles :)

**Comment by ncave** [comment]
@smoothdeveloper
> what about having 1 file per namespace at the root, and the modules brought into them?

 Having 1:1 mapping between source F# files and generated Rust files is normally how Fable works, so adding artificially generated file is probably not something we want to do, as it will increase complexity.
 
 Also, those merged module declarations are not going to be very big, if they would use wildcards.
 Something like this perhaps:
 
 ```rs
#[path = "./namespaces.rs"]
mod module_6e0bd2df;
pub use module_6e0bd2df::*;

 pub mod A {
    pub use module_6e0bd2df::A::*;
    pub mod B {
        pub use module_6e0bd2df::A::B::*;
        pub mod C {
            pub use module_6e0bd2df::A::B::C::*;
        }
        pub mod D {
            pub use module_6e0bd2df::A::B::D::*;
        }
    }
}
 ```
 Unfortunately that would only work for namespaces in different files, not if they're in the same file.
 Perhaps we'll have to flatten the namespace as a module prefix, e.g.
 ```rs
 pub mod A_B_C {
      use super::*;
      #[derive(Clone, Debug, PartialEq, PartialOrd,)]
      pub enum MyType { MyType(f64), }
  }
pub mod A_B_D {
      use super::*;
      #[derive(Clone, Debug, PartialEq, PartialOrd, Hash, Eq, Ord,)]
      pub enum MyType { MyType(i64), }
  }
 ```
 And they re-export them like this in the last file:
 
 ```rs
  pub mod A {
    pub use module_6e0bd2df::A::*;
    pub mod B {
        pub use module_6e0bd2df::A_B::*;
        pub mod C {
            pub use module_6e0bd2df::A_B_C::*;
        }
        pub mod D {
            pub use module_6e0bd2df::A_B_D::*;
        }
    }
}
  ```
  That should work for single files too, as long as we make sure the last file is processed last (currently they can be compiled by Fable out of order).
  
 > I also think there should be some solution to allow rust library to merge,
 
 I don't think there is, but I could be wrong.

**Comment by smoothdeveloper** [comment]
> Also, those merged module declarations are not going to be very big, if they would use wildcards.

Oh, they look like forwarding to the contents, not having the namespace contents, my overlook!

Then yes, this solution looks great.
