### ISSUE TITLE
What is the difference between `ParamObject` and `NamedParams` ?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3478]
### Description

```fs
open Fable.Core

type StaticClass =
    [<NamedParams>]
    static member NamedParams(foo: string, ?bar: int) = int foo + (defaultArg bar -3)
    [<ParamObject>]
    static member ParamObject(foo: string, ?bar: int) = int foo + (defaultArg bar -3)

let x = StaticClass.NamedParams(foo = "3", bar = 5)

let y = StaticClass.ParamObject(foo = "3", bar = 5)
```

generates

```js
export function StaticClass_NamedParams_3B406CA4({ foo, bar }) {
    return parse(foo, 511, false, 32) + defaultArg(bar, -3);
}

export function StaticClass_ParamObject_3B406CA4({ foo, bar }) {
    return parse(foo, 511, false, 32) + defaultArg(bar, -3);
}

export const x = StaticClass_NamedParams_3B406CA4({
    foo: "3",
    bar: 5,
});

export const y = StaticClass_ParamObject_3B406CA4({
    foo: "3",
    bar: 5,
});
```

It looks like both attributes does the same thing to me. If that's the case, we should deprecate one of them I think. (New Fable documentation is using ParamObject so it should probably be the one we keep)

**Comment by Happypig375** [comment]
They seem to even be aliases.
![image](https://github.com/fable-compiler/Fable/assets/19922066/72e58316-1081-419b-9f22-c8a16d8b7ec8)
![image](https://github.com/fable-compiler/Fable/assets/19922066/e299ef79-b54b-41fd-97f7-9407324b7a54)

**Comment by MangelMaxime** [comment]
@Happypig375 Ah I didn't think about looking into Fable.Core source code.

Thank you

@alfonsogarciacaro @dbrattli @ncave are you ok with removing `NamedParams`? 

I think it will break Fable.Python, but Python is still in Beta.

**Comment by Happypig375** [comment]
You're welcome!

**Comment by dbrattli** [comment]
@MangelMaxime I think this is because the name `ParamsObject` do not make any sense for Python. But `NamedParams` do. So these should be separated for each language or we should find a name that make sense for both.

**Comment by MangelMaxime** [comment]
Thank you for the clarification.

Then I think this issue is linked to https://github.com/fable-compiler/Fable/issues/3513

**Comment by MangelMaxime** [comment]
I am closing as both are needed but they should probably be moved to their respective target modules when doing the Fable.Core rewrite
