### ISSUE TITLE
Remove `Py.python` and `Py.expr_python`

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3482]
### Description

There are `emitStatement` and `emitExpr` which cover the same feature with the bonus of accepting argument so the user can use `$0`, `$1`, etc. to access them in the expression.

**Comment by dbrattli** [comment]
I don't think `emitStatement` does the same thing as `python`. The `python` one supports string interpolation to handle arguments e.g:

```fs
let add a b = Py.python $"""
    return {a+b}
    """
```

This produces:
```py
def add(a: int, b: int) -> Any:
    
    return (a + b)
```

**Comment by dbrattli** [comment]
The JS equivalent was not removed so I think we should add this back: https://github.com/fable-compiler/Fable/blob/main/src/Fable.Core/Fable.Core.JS.fs#L547

Better naming would be nice, but there are some magic happening to get syntax highlighting in vscode for the contained code https://github.com/alfonsogarciacaro/vscode-template-fsharp-highlight
