### ISSUE TITLE
Consistency of generated Javascript tag fields in discriminated unions

### ISSUE THREAD

**Issue by tomcl** [fable-compiler/Fable#3493]
### Description

Can I rely on Javascript target D.U. tags implemented consistently? (For reasons of D.U. type conversion via unboxing).

### Use Case

This is a slightly weird question, but it would be interesting to know the answer.

I have a digital logic simulator running under electron written in F# compiled by FABLE  https://github.com/tomcl/ISSIE

This does component-level simulation where there are about 50 different components, each implemented by a D.U. case with varying numbers of parameters (so no `StringEnum` here, even if it were performant which it probably would not be).

The F# simulation code runs under Fable/ JS  about 45% of the speed it runs under F# dotnet - which is not bad considering what happens to it and that the inner simulation loop never gets JIT compiled.

Anyway this issue is about how I serialise circuits (and therefore components) to JSON.

This works fine, but when I upgrade component definitions I need to write code that reads from JSON a legacy component definition D.U. (with a few no longer used for real cases) and translates this to the current D.U. by converting the legacy cases to equivalent new cases.

I'd like to do the conversion by checking for the (very few) cases that need to be converted, doing the conversion, and otherwise unboxing the legacy D.U. and pretending it is the current D.U. type. This is less onerous than an explicit conversion and also faster - speed reading big circuits on startup is an issue and changing this type means remaking a whole large record it is contained in for every component read. (Though probably the JSON deserialisation is much slower than anything after - so for me speed is not an issue).

I was hoping I could be sure that tag numeric order would be the same as the case order in the type definition so that the JS values in the two D.U.s will be identical for all cases of the two D.U.s that are the same (if I write those first). But perhaps this is not true? It is perhaps a very atypical requirement but there might be other reasons why consistency would be helpful? Anyway it would be good to know is this the case. In the REPL the tag order seems consistent as can be seen from the code below where in Tiny and Tiny1 the tag order is consistent and X=0, Y=1, Z=2.

```fs
type Tiny = X | Y | Z

type Tiny1 = X | Y | Z

let conv (t:Tiny) : Tiny1 = unbox t

printfn "%A" (unbox X)

let tinyf1 (t:Tiny) = match t with | Tiny.X -> 1 | Tiny.Y -> 2 | Tiny.Z -> 3

let tinyf (t:Tiny) = match conv t with | X -> 1 | Y -> 2 | Z -> 3
```

this generates (for both the D.U.s):

```js
export function tinyf(t) {
    const matchValue = conv(t);
    switch (matchValue.tag) {
        case 1:
            return 2;
        case 2:
            return 3;
        default:
            return 1;
    }
```
}

Information would be appreciated!

### Related information

* Fable version: v4 latest

**Comment by MangelMaxime** [comment]
Hello @tomcl,

I didn't look into Fable code itself but indeed expect the case order to be based on the user declaration should probably be expected.

In Haxe (another transpiler) the declaration order is what controls the output, and this is important when storing stuff in a database for example etc.

As it allows, to add now case to a DUs without having the change the database representation when done using reflection and not manual code.

I think Fable does use the declaration order as the source of truth because if I use this code:

```fs
type MyType =
    | A_Prop
    | B_Prop
    | D_Prop
    | C_Prop

let test =
    function 
    | A_Prop -> "A - 0"
    | B_Prop -> "B - 1"
    | D_Prop -> "D - 2"
    | C_Prop -> "C - 3"
```

I get 

```js
export function test(_arg) {
    switch (_arg.tag) {
        case 1:
            return "B - 1";
        case 2:
            return "D - 2";
        case 3:
            return "C - 3";
        default:
            return "A - 0";
    }
}
```

and as you can see the `C_Prop` is generated with the highest tag rank which would not be the cased if Fable/F# was using the alphabetical order.

**Comment by tomcl** [comment]
Thanks! It seems to work for me.

**Comment by tomcl** [comment]
Nope. That was too soon.

Matches on the unbox converted values work fine. Equality tests do not. Printing out the javascript representation of teh compared objects shows why:

```
JSONComponent_ComponentType {tag: 3, fields: Array(0)}
ComponentType {tag: 3, fields: Array(0)}
```
The JS class preserves the F# type, so unboxing can't be used for type conversion. Matches work because they explicitly compare tag and then fields. F# `=` however does not work because it uses `equals` from `utils` which I guess compare class as well.

Specifically when printing with console.log in dev tools and expanding:
The [[Prototype]]  info differs on:

- cases
- constructor

Is there some nice way I can to the JS class conversion (changing the [[Prototype]]) while leaving all fields outside that the same?

(I have not much JS knowledge, given I nearly always program in F#)

**Comment by tomcl** [comment]
https://github.com/fable-compiler/Fable/issues/2282

Says what FABLE does. But does not address the question of how easily (without impacting performance) what Fable compares can be changed.

Otherwise my use case means I need a 40-way match to convert the type of my D.U.s.

I cannot avoid having different types for the D.U.s because they by design have a few cases which are not identical.

**Comment by tomcl** [comment]
The (correct) F# conversion function with 40 cases in a match compiles nicely to JS as:
```javascript
/*
 * Transforms JSON components (parsed from JSON)  to current components
 * Normally this means converting legacy JSON component types into new ones.
 * However it could in principle be more radical.
 * The default transform unboxes the value which works when there is no chnage in the JS value
 * representation
 */
export function convertFromJSONComponent(comp) {
    let ct, v, v_1;
    const inputRecord = comp;
    return new Component(
    inputRecord.Id, 
    (ct = comp.Type, 
        (ct.tag === 1) ? (new ComponentType(1, [ct.fields[0]])) : 
        ((ct.tag === 2) ? (new ComponentType(2, [ct.fields[0]])) : 
        ((ct.tag === 3) ? (new ComponentType(3, [])) : 
        ((ct.tag === 4) ? (new ComponentType(4, [])) : // lots of cases deleted...
    ))))), 
    inputRecord.Label, 
    inputRecord.InputPorts, 
    inputRecord.OutputPorts, 
    inputRecord.X, 
    inputRecord.Y, 
    inputRecord.H, 
    inputRecord.W, 
    inputRecord.SymbolInfo);
}
```

I could write JS to do this without all the match cases - since always the second argument of `ComponentType` is `ct.fields`. Do I need to do a shallow copy of `ct.Fields` as here? I suspect that is just an artifact, for DU cases with tuples parameters I need to pattern match each component of the tuple with a separate variable for some reason to get the match to be syntactically correct.

Anyway this looks like a solution to this problem that will allow me to replace 40 match cases.

**Comment by MangelMaxime** [comment]
Hello @tomcl,
Do you need anything else or can we close the issue?

I did re-read the issue but admit that I am not so sure where it at now ^^

**Comment by tomcl** [comment]
All now understood! this can't be done due to equality testing
