### ISSUE TITLE
Fable output and js await

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3498]
### Description

We are working on a library we want to transpile to multiple languages, so access of fable generated code from javascipt is very important for us.

Now i want to create an f# async function and be able to use it with js await once transpiled.

### Repro code

[Repl](https://fable.io/repl/#?code=LYewJgrgNgpgBAYSgQwM6oLAChsgA4wB2cAYsgEawB0CIATjLgcWZTDfewFKoCShAFxh182MVlgC4Q1FIC8cNAE9CAYzgBvbHB1wGAiHWIAGXXGwBfcQG0APAFFgASwEAKAESqQhVCGpQQAHNXABJjAEp3cIA+AF1sSTgAwLhXEHIAKwAudIzwuCy4CEIXOAUM1AA5ZAEnADdGHCw7RxcPZAB3ZFKwqLiEmClO7qlXZTUSYtVCgEFUFVVbAHIZ6PzClbK4CurahvFkuHcACRgoALgAdXooMHcDwb0YVC3h0pkBA6Cn1CA&html=Q&css=Q)

I have the library code available here: https://github.com/CSBiology/FsSpreadsheet/blob/FsSpreadsheet.Exceljs/src/FsSpreadsheet.Exceljs/Xlsx.fs

and tried calling it with js mocha like this:

```javascript
import { equal } from 'assert';
import { Xlsx } from './FsSpreadsheet.Exceljs/Xlsx.fs.js';

describe('FsSpreadsheet.Exceljs', function () {
    describe('read', function () {
        it('table', async () => {
            const path = "./TestFiles/ReadTable.xlsx";
            const wb = await Xlsx.fromXlsxFile(path)
            console.log(wb)
            equal("name", "name")
        });
    });
});
```

#### REPL: 

I assume, as js allows top level await, this should technically work, but it does not print any result.

#### Library mocha test: 

the printed "wb" returns `[Function (anonymous)]`

#### Library mocha test with `Async.StartAsPromise`: 

I tried returning not `Async<FsWorkbook>`, but instead `Promise<FsWorkbook>` using `Async.StartAsPromise` but it returns another error.

> TypeError: computation is not a function
      at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:86:9
      at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:76:17
      at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:113:50
      at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:76:17
      at startWithContinuations (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:147:5)
      at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:156:45
      at new Promise (<anonymous>)
      at startAsPromise (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:156:12)
      at Xlsx.fromXlsxFile (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/Xlsx.fs.js:11:16)
      at Context.<anonymous> (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/Exceljs.js:8:35)
      at process.processImmediate (node:internal/timers:476:21)

### Related information

* Fable version: `dotnet fable --version`: **4.1.3**
* Operating system: Windows

**Comment by Freymaurer** [comment]
Maybe the correct question is: How can i write this logic so that fable makes it usable with await?

```fsharp
static member fromXlsxFile (path:string) : Async<FsWorkbook> =
        async {
            let wb = ExcelJs.Excel.Workbook()
            do! wb.xlsx.readFile(path)
            return JsWorkbook.toFsWorkbook wb
        }
```

Mocha tests calling all functions seperatly works

```javascript
describe('FsSpreadsheet.Exceljs', function () {
    describe('read', function () {
        it('table', async () => {
            //const wb = await Xlsx.fromXlsxFile(path)
            const path = "C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/TestFiles/ReadTable.xlsx";
            const wb = new Excel.Workbook();
            await wb.xlsx.readFile(path)
            const fswb = toFsWorkbook(wb)
            console.log(fswb)
            equal("name", "name")
        });
    });
});
```

**Comment by MangelMaxime** [comment]
Hello @Freymaurer,

Fable async are transpiled as F# async expression using a custom/different implementation from JavaScript. JavaScript async are in fact hidden promised.

If you want Fable to generate "awaitable" code from JavaScript, you need to use `promise` types. You can use `Fable.Promise` to get access to `promise` computation.

The difference is made because `promise` are hot meaning executing at declaration while `async` in F# are cold, waiting for the user to start then before running.

**Comment by Freymaurer** [comment]
I tried using Fable.Promise but it returned this error message:

> TypeError: computation is not a function
at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:86:9
at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:76:17
at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:113:50
at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/AsyncBuilder.js:76:17
at startWithContinuations (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:147:5)
at file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:156:45
at new Promise ()
at startAsPromise (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/fable_modules/fable-library.4.1.3/Async.js:156:12)
at Xlsx.fromXlsxFile (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/FsSpreadsheet.Exceljs/Xlsx.fs.js:11:16)
at Context. (file:///C:/Users/Kevin/source/repos/FsSpreadsheet/tests/JS/Exceljs.js:8:35)
at process.processImmediate (node:internal/timers:476:21)

**Comment by Freymaurer** [comment]
@MangelMaxime you can find the repo [here](https://github.com/CSBiology/FsSpreadsheet/tree/FsSpreadsheet.Exceljs).

With the code in question here:

https://github.com/CSBiology/FsSpreadsheet/blob/146d9205a549e6ccbf0b317a52fe56ea63e08bfc/src/FsSpreadsheet.Exceljs/Xlsx.fs#L12

```fsharp
type Xlsx =
    static member fromXlsxFile (path:string) : Promise<FsWorkbook> =
        promise {
            let wb = ExcelJs.Excel.Workbook()
            do! wb.xlsx.readFile(path) |> Async.StartAsPromise
            let fswb = JsWorkbook.toFsWorkbook wb
            return fswb
        }
```

And the respective test in javascript here:

https://github.com/CSBiology/FsSpreadsheet/blob/146d9205a549e6ccbf0b317a52fe56ea63e08bfc/tests/JS/Exceljs.js#L43

```javascript
        it('combined function', async () => {
            const path = "tests/JS/TestFiles/ReadTable.xlsx";
            console.log("start")
            const wb = await Xlsx.fromXlsxFile(path)
            console.log(wb)
        });
```

These tests can be run with `npm run testjs` in root. Please have a look at this, i would be more than happy to buy you a coffee for this issue 😅

**Comment by Freymaurer** [comment]
Thank you so much! I will implement this tomorrow morning and see if it works! Let me know how i can buy you a coffee!

**Comment by MangelMaxime** [comment]
Your welcome :)

If you want to buy me a coffee I have 2 options:

- https://www.patreon.com/MangelMaxime best suited for monthly paiement
- https://paypal.me/MangelMaxime if you prefer one time donation

**Comment by Freymaurer** [comment]
It works, thanks a lot!

**Comment by MangelMaxime** [comment]
Your welcome always happy to help and thank you for the tip :)

**Comment by Freymaurer** [comment]
Please have a look at your private gitter messages, regarding future tips 👍
