### ISSUE TITLE
Running JavaScript tests compiled using Fable in watch mode fails

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3522]
### Description

1. `dotnet run -c Release --project /Users/mmangel/Workspaces/Github/fable-compiler/fable/src/Fable.Cli -- tests/Js/Main --outDir build/tests/JavaScript/Main --lang javascript --exclude Fable.Core --noCache --watch`
2. Kill the Fable program
3. `npx mocha build/tests/JavaScript/Main --reporter dot -t 10000`
4. See that a test is failing

The test seems related to https://github.com/fable-compiler/Fable/issues/3301

And according to the commit that fix it and add the tests. I suspect this is expected that we need to run in Release mode. I think this is a problem to have such a behaviour because it means there is a different set of features supported depending on in user use watch mode or not.

And means that he can't use Fable in watch mode if he encounter this case in his codebase.

* Fable version: 4.1.4
* Operating system: OS

**Comment by MangelMaxime** [comment]
The generated code is indeed really different depending if in watch mode or not.

Watch mode on the left | Release mode on the right

<img width="1237" alt="CleanShot 2023-09-09 at 11 35 47@2x" src="https://github.com/fable-compiler/Fable/assets/4760796/a89f1814-2958-4a46-af84-2ff74b2b4d9e">

**Comment by ncave** [comment]
@MangelMaxime I don't think this qualifies as a bug, as this is the expected behavior of the F# compiler when run in `Debug` mode. Switching to `Release` mode using `--watch --configuration Release` will resolve the issue, please feel free to close if you agree.

**Comment by MangelMaxime** [comment]
@ncave I don't agree on this one, but I revisited my position.

Having a different code generated is not really a bug per se, however having the code fail is IHMO. The code, that I listed is just one of the failing tests.

Personally, I would consider that a bug because it means that I can't run the same code between release or watch mode. And a normal user would probably not know/think about passing `--configuration Release` option.

The more things we can support in both mode the better I believe.

There is also the possibility to always compile in Release mode for the FCS. But I don't know if this can have some negative impact like performance at compilation or less readable output. And if these impact are small enough to be ignored.

**Comment by ncave** [comment]
@MangelMaxime I'm not sure if there is much can we do, besides switching `--watch` mode to `Release`.
In any case, I don't think it can be classified as a `bug`, cause running recursive functions without optimization (in `Debug` mode) can fail even on .NET.

**Comment by MangelMaxime** [comment]
Well I suppose this issue can be postpone to later because with the latest version on master I can't reproduce it anymore.

@ncave Regarding the fact that recursive functions can fails in watch mode I am fine with that, I was thinking there were other issues like it is the case for TypeScript or Python targets where the errors is related to "invalid code generated".

- https://github.com/fable-compiler/Fable/issues/3520
- https://github.com/fable-compiler/Fable/issues/3526
