### ISSUE TITLE
Fable Python, name '...' is not defined.

### ISSUE THREAD

**Issue by sheridanchris** [fable-compiler/Fable#3527]
### Description

I'm currently adding support for python tests to FsToolkit.ErrorHandling and a few tests are failing with the error `name '...' is not defined`.

![image](https://github.com/fable-compiler/Fable/assets/105478675/9c2135b2-b43f-4e6f-8130-e026450b818c)

### Repro code
You can view the PR [here](https://github.com/demystifyfp/FsToolkit.ErrorHandling/pull/227)
Running the command `./build.sh RunPythonTests` will run the tests. The tests are located in a `.python-tests/` directory in the individual test folders.

I've been trying to create a minimal repro but I've had no luck doing so.

### Related information

* Fable version: 4.1.4
* Python version: tested with 3.9 & 3.11

**Comment by dbrattli** [comment]
I have a lokal repro now so trying to figure out what's going on.

**Comment by dbrattli** [comment]
Fix is merged and will be available in the next release of Fable.
