### ISSUE TITLE
Function hidden by a signature file should not be exported 

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#3528]
### Description

When using signature files to hide implementation details, I would expect every function that is not in the signature file, not to do be exported in JavaScript

### Repro code

Lib.fsi:

```fsharp
module Lib

val f: int -> int
```

Lib.fs:

```fsharp
module Lib

let g a  = a + 1
let f a = g a
```

### Expected and actual results

Expected:
```js
function g(a) {
    return a + 1;
}

export function f(a) {
    return g(a);
}
```

Actual:
```js
export function g(a) {
    return a + 1;
}

export function f(a) {
    return g(a);
}
```

The workaround is to mark `g` as private in the implementation file, but given the signature that should not be necessary.

### Related information

* Fable version: `4.1.4`
* Operating system: Ubuntu (WSL2)

I would be interested in contributing a fix for this if I get a pointer where to start.

**Comment by MangelMaxime** [comment]
Hello @nojaf,

The way I would go to fix this is issue is to is to make the `src/quicktest/QuickTest.fs` contains your minimal reproduction.

And then, I would either use the debugger or `printfn` to track down which portion of the printer is responsible for generating the code.

My guess is that this is this portion:

https://github.com/fable-compiler/Fable/blob/dd4d6c986c1083495044ed29e9f9d11abe4dfd66/src/Fable.Transforms/BabelPrinter.fs#L602-L605

If that's the case, I would then look which portion of the code is responsible for generating `ExportNamedDeclaration` which seems to be:

https://github.com/fable-compiler/Fable/blob/dd4d6c986c1083495044ed29e9f9d11abe4dfd66/src/Fable.Transforms/Fable2Babel.fs#L2455-L2457

And then, I would check if the `isPublic` is determine correctly at each invocation places.

Sorry, I don't have better pointer to gives you. If you need more help or information, don't hesitate to ping me here or on Slack.
