### ISSUE TITLE
Broken link on Fable homepage: JS Interop

### ISSUE THREAD

**Issue by MaxWilson** [fable-compiler/Fable#3532]
### Description

I went to review the interop docs, but the documents linked from https://fable.io/index.html in the "Easy JavaScript Interop" section are broken links: https://fable.io/docs/communicate/js-from-fable.html and https://fable.io/docs/communicate/fable-from-js.html just err out and then lead back to the Fable homepage.

I searched the repo to see if I could locate the old docs and maybe submit a PR, but my search-fu wasn't good enough.

**Comment by MangelMaxime** [comment]
Hello @MaxWilson,

I forgot to update these links when re-writting the documentation for Fable 4. Now all the information can be found in https://fable.io/docs/javascript/features.html.

And we actually need to change the home page, now that Fable 4 support severals languages.

I fixed the links for now

**Comment by MaxWilson** [comment]
Thank you!
