### ISSUE TITLE
New copy-and-update warnings with Fable 4.4

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#3567]
It looks like Fable 4.4 is using F# 8 features and also emits F# 8 warnings:

We see LOTS of new warnings. Things like:

` warning FSHARP: This copy-and-update record expression changes all fields of record type 'MyRecordType'. Consider using the record construction syntax instead. (code 3560)`

@MangelMaxime @ncave Is this expected? 

references https://github.com/dotnet/fsharp/issues/16182

**Comment by ncave** [comment]
@forki You are correct, sounds like a lot of people have concerns about warning 3560 and so it will be [turned off](https://github.com/dotnet/fsharp/pull/16160) by default in F# 8.0 final (post-RC2). It hasn't been merged in F# main yet, but I can cherry-pick it and have a new build shortly.

**Comment by nojaf** [comment]
Add `<NoWarn>$(NoWarn);FS3560</NoWarn>` for now.

**Comment by forki** [comment]
@nojaf  it's not just that particular one. there are more. But yes that is a valid workaround

**Comment by ncave** [comment]
I updated FCS to turn off 3560 by default, it will be in the next release.
++ @MangelMaxime

**Comment by ncave** [comment]
@nojaf 
> is --langversion being passed to FCS as an argument?

I believe so, not as an Fable CLI argument, but most of what's in your `.fsproj` will be passed to FCS.

**Comment by MangelMaxime** [comment]
Thank you @ncave.

I just released a new version, @forki can you please check if this fixed all the warnings you hard?

**Comment by forki** [comment]
Friends, thank you very much for this super duper fast fix.

I'll test it tomorrow morning in the office.

Hugs.

Maxime Mangel ***@***.***> schrieb am Mi., 25. Okt. 2023,
19:48:

**Comment by forki** [comment]
yes it works. Thank's a lot.
