### ISSUE TITLE
Fable 4.3/4.4.1 regression: JSX component fails to load if it uses local functions

### ISSUE THREAD

**Issue by MaxWilson** [fable-compiler/Fable#3570]
### Description

JSX component fails to load with browser console errors, due to optimizing local functions out of existence.

### Repro code

Create a JSX function that uses a local function:

```fs
[<JSX.Component>]
let PartyPicker dispatch =
    let randomName() = "Bob"
    let chooseAWinner _ = Browser.Dom.window.alert $"Happy birthday, {randomName()}!"
    JSX.jsx """
    <div>
        <b>Party picker</b>
        <button onClick={chooseAWinner}>Choose a winner</button>
    </div>
    """
```

Place that local function on the page somewhere and compile it for production using **dotnet fable src -e .jsx -o dist**.

**Actual result:** Invalid JSX is generated, with "chooseAWinner" optimized out of existence. This will cause browser errors at runtime. 'ReferenceError: chooseAWinner is not defined'

```js
export function PartyPicker($props) {
    return     <div>
        <b>Party picker</b>
        <button onClick={chooseAWinner}>Choose a winner</button>
    </div>
    ;
}
```

**Expected:** chooseAWinner should be retained in the JSX code. This is a regression--does not happen in fable version 4.0.0-theta-011.

Alternate repro: clone https://github.com/MaxWilson/FableJSXRepro and do **npm run build && npx http-server dist** (will not repro for some reason with **npm start**)
 
### Related information

* Fable version: 4.3 or 4.4.1 (does not repro with 4.0.0.-theta-011)
* Operating system: Windows

**Comment by MaxWilson** [comment]
If you try to work around the bug by making the local function a module-scope function, you have to use JavaScript syntax at the call site or vite compilation will fail:

```
                <button onClick={newPC(setDraft)}>New PC</button>
```

works, but 

```
                <button onClick={newPC setDraft}>New PC</button>
```

fails:

**_[vite:esbuild] Transform failed with 1 error:
c:/code/Arena/dist/UI/Components/CampaignView.jsx:104:39: ERROR: Expected "}" but found "setDraft"_**

**Comment by MaxWilson** [comment]
The workaround of using JavaScript syntax at the call site doesn't crash but it isn't correct either. It executes the onClick handler too soon, at render rather than on click. I don't currently know of a workaround other than downgrading to an earlier version of fable.

**Comment by ncave** [comment]
@MaxWilson Yes, looks like unused local functions are optimized away, when in Release mode.

You can fix that by adding `dotnet fable --configuration Debug` or `-c Debug` (or if you use `--watch` it also defaults to Debug mode).

**Comment by MaxWilson** [comment]
Using interpolated JSX.jsx $"""... works great, thanks!

From my perspective this workaround is good enough to completely satisfy my needs, but I'll leave the issue open because in case the Fable team decides to change something in response. Feel free to close otherwise.

**Comment by ncave** [comment]
@MaxWilson Closing as this behavior is expected in Release mode. Feel free to reopen if needed.
