### ISSUE TITLE
Question: Filter SDK references?

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#3574]
Hey @ncave, I'm unsure how to contact you so I'm opening an issue here. I'm sorry for the noise.
As I'm doing some work involving project cracking I had a thought.
Fable can't just transform anything that is in the BCL. Only a subset is supported, so I'd like to know if it would be interesting to trim the references we get after project cracking.

Right now, a `net8.0` class lib resolves a lot of references that can't be used like
```
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Data.Common.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Data.DataSetExtensions.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Data.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.Contracts.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.Debug.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.DiagnosticSource.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.FileVersionInfo.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.Process.dll',
    '-r:C:\\Program Files\\dotnet\\packs\\Microsoft.NETCore.App.Ref\\8.0.0-rc.2.23479.6\\ref\\net8.0\\System.Diagnostics.StackTrace.dll',
```

Would it make sense if we try to filter some of these?
My naive thinking is that having fewer references would mean the interactive checker needs to do less work and type-checking could become a little bit faster.

I'm curious to hear your thoughts on this.

**Comment by ncave** [comment]
@nojaf I don't think that's going to help much or speed anything up, the type-checking is the slow part (by far), not BCL metadata lookup. But you can try filtering references and measure it, if you want, I've been wrong in the past many, many times.

**Comment by nojaf** [comment]
Yeah, that does sound right. I might experiment with this to see if it has any effect.
Going to close this issue as there is nothing actionable for Fable here.
