### ISSUE TITLE
Importing large fable-library has reference errors.

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3580]
### Description

Hey, we develop a large fable compatible library [ARCtrl](https://github.com/nfdi4plants/ARCtrl). We already use it in nodejs and pure dotnet, now i tried running it in a fable (SAFE stack) environment and i noticed some compilation errors.

I reproduced this issue with a minimal example:
- dotnet tools + fable 
- .fsx script file
- transpile
- Error. In the following a small screenshot of some of these errors:
![image](https://github.com/fable-compiler/Fable/assets/39732517/053cb11b-d80c-4dc6-ac28-539496539c82)

Looking into fable modules, i notice that all files are present, but in the transpiled .js files `OntologyAnnotation` for example is not imported.

![image](https://github.com/fable-compiler/Fable/assets/39732517/78ded2ea-8cba-4215-9573-dcf7dd1ac953)

Not sure where this problem comes from.

### Repro code

```f#
// test.fsx
#r "nuget: ARCtrl, 1.0.0-beta.3"

open ARCtrl
open ARCtrl.ISA

let assay = ArcAssay.init("MyAssays")
```

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `4.4.1`
* Operating system: Win 11

**Comment by ncave** [comment]
@Freymaurer Looks like some reference issue, try building with `--verbose` flag to see what files are included in the build.

I noticed the build is referencing `ARCtrl.ISA.Spreadsheet` as a binary, which doesn't look like it bundles its source files (so not Fable-compatible). But it might just as well be something else.

**Comment by Freymaurer** [comment]
> I noticed the build is referencing ARCtrl.ISA.Spreadsheet as a binary, which doesn't look like it bundles its source files (so not Fable-compatible). But it might just as well be something completely different.

You are absolutly right. I am so sorry! Must have overlooked that. I added it and now it works 😞 I really need to see if i can add this via FAKE. This happens way to often.
