### ISSUE TITLE
Missing `.gitignore` file in the generated `fable_modules/` folder

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3603]
### Description

`fable_modules` folder should have a `.gitignore` file generated with `**/*` content.

However, it seems like this is not the case anymore.

### Repro code

1. `dotnet new console -lang f# --name reproBugFableMobules`
2. `cd reproBugFableMobules`
3. `dotnet new tool-manifest`
4. `dotnet tool install fable`
5. `dotnet fable`
6. `ls -a fable_modules`

See that there is no `.gitignore` file.

### Expected and actual results

Should have a `.gitiginore` file generated.

### Related information

* Fable version: 4.5.0
* Operating system: OSX

**Comment by MangelMaxime** [comment]
It seems like this bugs returns in Fable 4.9.0

**Comment by pracplayopen** [comment]
If you have a free moment, could you maybe articulate why this is the default?

a guess for the rational would be supporting common practice of not committing generated files, but if there are other reasons for this would love your thoughts.

**Comment by MangelMaxime** [comment]
I am not sure what you want me to explain.

Generated files should not be tracked because it would pollute your Git history, also the output of them sightly changes with each Fable version.

**Comment by pracplayopen** [comment]
just wanted you to write down exactly what you did. thx
