### ISSUE TITLE
Fable Logo

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#361]
Fable is a cool project and deserves a cool logo from its cool community! The current one is just a temporary placeholder until we can decide together on a more appealing one. Given my 0-level design skills, it'd be fantastic if the community could post some proposals, then vote on the best one. 

I haven't thought of any specific way to choose the logo, but I guess we can have a first discussion with drafts to decide the general direction and then a second round to create a polished version.

Looking forward to seeing your amazing ideas!

**Comment by rmunn** [comment]
There was some [recent discussion on Gitter](https://gitter.im/fable-compiler/Fable?at=57b39b4c8d93113d5f02033f) about logo ideas. Rather than reproduce it here, I'll just provide a link that should hopefully go straight to the relevant discussion.
