### ISSUE TITLE
[Python] Equality between Records with None fields fails

### ISSUE THREAD

**Issue by HLWeil** [fable-compiler/Fable#3611]
### Description

Equation between two `Records` fails in python, when the `Record Type` contains an `Option field` and the value bound to this field is `None`.  The error message is the following:

```
TypeError: '<' not supported between instances of 'NoneType' and 'NoneType'
```

### Repro code

[Please provide the F# code to reproduce the problem or a link to the [REPL](https://fable.io/repl/).
Ideally, it should be possible to easily turn this code into a unit test.](https://fable.io/repl/#?code=MQJwBARAdgrg5gUwC4C4wDECGAjANggOgGEB7EBAGjABYCAmAgBggFgAodkgBwSgx3zEyCTjz4BlAJ4BnJAgC2Q3PgDGSAJYko0ggHFeCEOpXtRvMFNkKCAFQQAPJAQBKCODFyYQAUXtdy0tKa2qZsSJI8YK4qYAC87GCJYADeCUnpAIJgaLJGUHBg3BpaaYkAvqH4SGCYcSlZsWAAcloIFWxVYNh1yQ3Nre3s-upQSABmfBAApNgQYAAUtY3YAJTsQA&html=Q&css=Q)

### Reason

The failing function is the following:

```python
def record_compare_to(self: Record, other: Record) -> int:
    if self is other:
        return 0

    elif hasattr(self, "__dict__") and self.__dict__:
        for name in self.__dict__.keys():
            if self.__dict__[name] < other.__dict__.get(name):
                return -1
            elif self.__dict__[name] > other.__dict__.get(name):
                return 1

    elif hasattr(self, "__slots__") and self.__slots__:
        for name in self.__slots__:
            if getattr(self, name) < getattr(other, name):
                return -1
            elif getattr(self, name) > getattr(other, name):
                return 1

    return 0
```

@freymaurer

**Comment by MangelMaxime** [comment]
This is fixed by https://github.com/fable-compiler/Fable/pull/3606

It will be included in the next Fable release.

**Comment by HLWeil** [comment]
Great to hear 👍
