### ISSUE TITLE
[Python] Python Dictionary remove_from_dict does not work with tuple as dictionary key.

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3615]
Assume the following:

```fsharp
#r "nuget: Fable.Core, 4.2.0"

open System.Collections.Generic

let my_dict_min = Dictionary((Map [for i in 0..10 do yield i, sprintf "Number: %i" i]))

let my_dict = Dictionary((Map [for i in 0..10 do yield (i,i), sprintf "Number: %i" i]))
```

Getting values from key will work for both dictionary, but when i try to remove values by key it will throw an error for tuple as key.

I checked the transpiled code and saw that `my_dict.Remove((0,0))` gets transpiled to: `remove_from_dict(my_dict, (0, 0))`.

Then checking the fable_library source files we find:

```python
def remove_from_dict(di: dict[_K, Any], k: _K) -> bool:
    if k in di:
        del di[k]
        return True

    return False
```

I copied the dictionary creation code to a jupyter notebook and tested the `del` part of `remove_from_dict` and it turns out that it fails as soon as del is called with a tuple as key for the dictionary

![image](https://github.com/fable-compiler/Fable/assets/39732517/dc82d55e-6ac2-4b9f-9740-24d25e4c6206)

As Fable.Python is pretty "cutting edge" i will provide the f# source code without a REPL. It was transpiled using dotnet tool fable `4.6.0`

```fsharp
// source code
#r "nuget: Fable.Core, 4.2.0"

open System.Collections.Generic

let my_dict_min = Dictionary((Map [for i in 0..10 do yield i, sprintf "Number: %i" i]))

let my_dict = Dictionary((Map [for i in 0..10 do yield (i,i), sprintf "Number: %i" i]))

let v = my_dict.[0,0] // This will run

printfn "GET: %A" v

my_dict_min.Remove(0) // This will run
my_dict.Remove((0,0)) // This will fail

let removeEven() =
  let mutable rmvKeys = ResizeArray()
  for KeyValue((i1,i2),v) in my_dict do
      // Remove cells of column
      if i1%2 = 0 then
          rmvKeys.Add((i1,i2)) // add to seperate collection first. Fable.Python does not like altering dictionary while iterating over it.
  printfn "END ADD LIST"
  for key in rmvKeys do
      my_dict.Remove(key) |> ignore

removeEven()

printfn "%A" my_dict
```

@HLWeil

**Comment by andreaschrader** [comment]
Del removes a referencefor a namespace. The reference needs to be there.

I guess the reason is that the tuple is not present as a key int he dictionary. 
If you use your_dict.pop(your_tuple_key), this should not be a problem.
Does this work?

**Comment by MangelMaxime** [comment]
@andreaschrader I tried your solution, but it doesn't work

```
raceback (most recent call last):
  File "/workspaces/Fable/src/Fable.Cli/../quicktest-py/quicktest.py", line 45, in <module>
    main(sys.argv[1:])
  File "/workspaces/Fable/src/Fable.Cli/../quicktest-py/quicktest.py", line 39, in main
    ignore(remove_from_dict(dic_1, (1, 2)))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/workspaces/Fable/src/quicktest-py/fable_modules/fable_library/map_util.py", line 81, in remove_from_dict
    di.pop(k)
    ^^^^^^
AttributeError: 'Dictionary' object has no attribute 'pop'
```

> Del removes a referencefor a namespace. The reference needs to be there.

I am not exactly sure what you mean by that, but `del` is called only if the key is present in the dictionary.

```py
def remove_from_dict(di: dict[_K, Any], k: _K) -> bool:
    if k in di:
        del di[k]
        return True

    return False
```
