### ISSUE TITLE
[Python] Records containing different values return the same hash

### ISSUE THREAD

**Issue by HLWeil** [fable-compiler/Fable#3648]
### Description

Records containing different values return the same hash

#### test.fsx
```fsharp
type X = {ID :int}

let x1 = {ID = 1}
let x2 = {ID = 2}

printfn $"x1:{x1.GetHashCode()}"
printfn $"x2:{x2.GetHashCode()}"
```
#### test.cmd
```shell
dotnet fable . --lang python
python test.py
```

### Expected and actual results

Expected result: Different hashes

Actual result: Same hashes

```shell
x1:5740354900026072187
x2:5740354900026072187
```

### Related information

`Equality` with `=` does work and returns `false`.

* `dotnet fable --version`: 4.5.0
* `dotnet tool list/update/install`: 4.7.0
* Windows11

@freymaurer

**Comment by dbrattli** [comment]
Thanks for the bug report. This issue will be fixed in the next release of Fable
