### ISSUE TITLE
The TypeScript file generated by Fable tries to import a file with a .js extension that does not exist

### ISSUE THREAD

**Issue by eagle-k** [fable-compiler/Fable#3686]
### Description

The TypeScript file generated by Fable imports a `.js` file, for example

```ts
import { int32 } from "../fable_modules/fable-library-ts/Int32.js";
```

However, this is problematic in a non-Vite environment because Fable only generates `.ts` files.
For reference, I got the following build error when I tried to use the Fable generated TypeScript file with [Next.js](https://nextjs.org/).)

```
Module not found: Can't resolve '../fable_modules/fable-library-ts/Int32.js'
```

When Fable generates a TypeScript file, how about omitting the extension of the file to be imported as follows?

```ts
import { int32 } from "../fable_modules/fable-library-ts/Int32";
```

Alternatively, I would like to know if there is a recommended way to use TypeScript files in a non-Vite environment (Next.js in this case).

### Related information

* Fable version: `dotnet fable --version` 4.9.0
* Operating system: Windows

**Comment by MangelMaxime** [comment]
I believe in general when importing files in JavaScript, it is recommended to set the extension.

This is because, resolution of the import is dependant on the runtime and if you are in the browser for example. Then it can't guess the extension of the file because it doesn't have access to the file system.

When generating to TypeScript, Fable should use the `.ts` file path in the import statement as this is the actual name of the file on the disk.

**Comment by eagle-k** [comment]
After additional research, it appears that this is (or should be) considered a bug in Next.js.
https://github.com/vercel/next.js/issues/59744

I am not sure it is reasonable for the Fable compiler to address this issue.

**Comment by MangelMaxime** [comment]
I think when generating TypeScript Fable should import files using `.ts` because this is what you would write manually.

Unless, this is interop import like `import "XX" "file.ext"` then in such cases we need to respect what the user provided.

**Comment by ncave** [comment]
@MangelMaxime 
> I think when generating TypeScript Fable should import files using .ts 

Here is the reason why TypeScript [doesn't want to support](https://github.com/microsoft/TypeScript/issues/49083#issuecomment-1435399267) using `.ts` extensions for imports.

Some runtimes do support imports with `.ts` extensions, e.g Deno.

Perhaps we can introduce another compiler flag just for the TypeScript import extension.
It may provide more flexibility over the generated TS imports, but we should also probably keep the defaults as they are today.

**Comment by MangelMaxime** [comment]
I didn't know about that.

Seems like the current Fable behaviour is the recommended way from TypeScript team. And so indeed if we want to address this issue we should add a new flag. 

The question is it worth adding it?

**Comment by MangelMaxime** [comment]
I am closing this issue for now. It seems like we are doing the correct generation and adding a new flag could be confusing.

We can re-visit in the future if needed.
