### ISSUE TITLE
win7 postbuild output contains spurious blank lines

### ISSUE THREAD

**Issue by markek** [fable-compiler/Fable#369]
### Description
On win 7, the fable postbuild output prints one or two blank lines at unpredictable points between the expected output lines.

### Repro steps
~~~~
for i in 1 .. 10 do
    printfn "%d" i

{"projFile": "index.fsx",
 "scripts": {
   "prebuild": "npm install",
   "postbuild": "node index.js"}}

{"private": true,
 "dependencies": {"fable-core": "^0.5.5"},
 "engines": {"fable": "^0.5.8"}}
~~~~

### Expected behavior
Output from node directly (after of course compiling with fable):
~~~~
$ node index.js
1
2
3
4
5
6
7
8
9
10
~~~~

### Actual behavior
Output from node that is run from fable postbuild:
~~~~
$ fable
npm install
fable-core@0.5.5 node_modules\fable-core

fable-compiler 0.5.8: Start compilation...
Compiled console.fsx at 7:00:39 PM
node index.js
1

2

3
4
5
6

7
8
9

10
~~~~
### Known workarounds
None

### Consequences
Simple compile-and-run node demos that print to the console will make fable appear to be unreliable.

### Related information 

* win 7
* compiler 0.5.8, core 0.5.5

**Comment by alfonsogarciacaro** [comment]
There're many things happening in win7 that are beyond my understanding ;) I cannot reproduce this in my machine. Could you please post the generated JS code? Please find below mine (with `-m commonjs` option).

```js
"use strict";

var _fableCore = require("fable-core");

for (var i = 1; i <= 10; i++) {
  _fableCore.String.fsFormat("%d")(function (x) {
    console.log(x);
  })(i);
}
```

Also, what node version do you have installed? If it's an old one, can you try updating it?

**Comment by markek** [comment]
node 4.4.7, and my js is identical. I think there is a glitch in how node's stdout is processed when node is spawned from fable. Please spend no more time on this - I should be able to fix and PR.

**Comment by markek** [comment]
Update: narrowed down to use of `console.log` being used on every data event. Fix is nearly obvious but requires a little more thought.

**Comment by markek** [comment]
Upgraded to node 4.5.0, still same problem.

Although only observed on windows, the fable.js/runCommand uses stdout.on which is designed to be called multiple times as needed, usually for larger outputs or timing. Using `console.log` each time will add a new line each time. If you luck out and it is only called once, the extraneous new line is hard to notice since it appears at a reasonable place.

It might be possible to observe on another os by trying `postbuild: cat bigfile.txt` using a large text file (say a megabyte or more) and checking `fable > out.txt` for blank lines.

**Just realized you should be able to observe it on another os by:**
~~~~
#  using -- postbuild: echo hi
fable > out1
#  using -- postbuild: echo hi > echo.txt
fable > out2
~~~~
out1 will have an extraneous blank line.

PR imminent.

**Comment by alfonsogarciacaro** [comment]
Ah ok, so this was happening when running the script with fableconfig.json scripts.postbuild. Sorry, for some reason I've been ignoring that detail all this time 😅 Now that I now how to reproduce it correctly I can confirm the problem happens in OSX too and it's fixed after merging your PR 👍 Thanks a lot!
