### ISSUE TITLE
[Python] How to works with `Kind` property on the `DateTime` type?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3690]
### Description

Currently, to represent the `DateTime` type we use `datetime.datetime` in Python.

This works fine until, we need to work with the `kind` property. Is there a way in Python to add a "property" to an existing class?

I tried to look only for how to dynamically add attributes to a class and I found  `setattr(date, "kind", kind or DateKind.Unspecified)` but it doesn't works:

```
AttributeError: 'datetime.datetime' object has no attribute 'kind'
```

I believe this is because `datetime.datetime` doesn't implements `__dict__` or `__slot__` or something like that. 

Does python support implicit conversion? For example, if we do something like `class MyDate(datetime):` does it means that `MyDate` can be use anywhere `datetime` can?

> Note, I was not able to implements `class MyDate(datetime):` I having trouble trying to call the parent constructor.

@dbrattli

**Comment by dbrattli** [comment]
@MangelMaxime It's better to put it in replacements and redirect to a library call, e.g #3691

**Comment by MangelMaxime** [comment]
Yes this was what I tried to do but I was stuck because `kind` should be `Unspecified` by default.

However, I think you unlocked me by showing that `tzinfo` is `_TzInfo | None`. I don't know why I never though it could be `None` and didn't think to check it.
