### ISSUE TITLE
[Fable 4.3.0][F# 7.0] String interpolation shows error (but compiles fine)

### ISSUE THREAD

**Issue by OkayX6** [fable-compiler/Fable#3694]
### Description
Hi,

I don't know why but I am getting this error everywhere in my Fable project in VS Code:
![image](https://github.com/fable-compiler/Fable/assets/1169339/21887e7b-01ab-48c4-8d8c-8ddcf56d37ab)

It used to work before upgrading either Dotnet or Fable.

The compilation works though with `npm start`

### Repro code
My **fsproj** is configured like this:

```xml
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net6.0</TargetFramework>
    <LangVersion>7.0</LangVersion>
  </PropertyGroup>
  <ItemGroup>
```

### Expected and actual results
Should not appear.

### Related information

* Fable version: `dotnet fable --version`: **4.3.0**
* Operating system: Windows 11

**Comment by MangelMaxime** [comment]
Hello @OkayX6,

You seems to report an IDE errors and not a Fable error here.

Beside the `LangVersion` you also needs to checks which version of FSharp.Core you are using I believe string interpolation was introduce in version 5.0.0 or 5.0.2

**Comment by OkayX6** [comment]
Thanks @MangelMaxime 
It appears it is Ionide that keeps referencing version 4.7.2, Rider fixed it automatically...
