### ISSUE TITLE
Compiler generates invalid Javascript when composing functions with partial application

### ISSUE THREAD

**Issue by sWW26** [fable-compiler/Fable#3696]
### Description

Compiler generates invalid Javascript when composing functions with partial application

### Repro code

https://fable.io/repl/#?code=C4TwDgpgBAchDOwIBMAq5oF4oG8CwAUFMVAGoCGANgK4QBcUAlgHbCEC+hhokUAsgHtkESlGz4iJAMIALRpWQM4iFOkgcuBHtD7wA5mMIkoAHygBVMMnJIoAgGZQAFIOGiAtAD5+QkQEpNSghgKABbamByACMgsN9RcShZeWQxXDIqWjSAVih2PMDgqGRGeDAbAGMZZ1CGXT0-Q0liUMrq0KgAd0ZgGSMSM0trW0cvfuMW+KgAHncoR1D4wpDqKxsIZSQ0DHm4tybjHD2RLp7q5IU0hfiAOgvUzgJCIJDQkAAxamYKgFEAJz+Aj+xVK5WAVSgq2GWHGkLWtk83ih602qh2iP4+huQ3WUAxJTKbWWYQ+XwqAHUgQBrFgGAlgiHI2wADwOJCZ0GZsJMSPhGwQWzUEG53nq2L5IpBhPBfSeBDen2+lL+NOYdNBbWc9i+UAAblBWV50qzur0MjQsAabhQLVAANR6vKNACMAAZNGA-ixgPZmFAACQAImVqr0DBwizc7EDmgVZP+gOB9M1Tm1fv1hu8RxNZ3NWWwzOtmWgDv17Bd7rlnu9voDgYTQPg4cjImjhCAA&html=Q&css=Q

### Expected and actual results

Expect `myFuncError` to give the same result as `myFuncWorking`.  It instead throws a null reference exception.

For some reason I looks like it just discards the final argument rather than partially applying it.

### Related information

* Fable version: 4.5.0 & 4.7.0

**Comment by ncave** [comment]
Fixed in #3697.
