### ISSUE TITLE
EqualityComparer<'T>.Default not working.

### ISSUE THREAD

**Issue by goswinr** [fable-compiler/Fable#3701]
Should [`EqualityComparer<'T>.Default`](https://github.com/fable-compiler/Fable/blob/main/src/fable-library/System.Collections.Generic.fs#L16) work in Fable ?

```fsharp
open System.Collections.Generic

let check(a:'T) (b:'T) : bool =
    let cmp = EqualityComparer<'T>.Default
    cmp.Equals(a,b)
```

It fails with SyntaxError: `The requested module 'https://fable.io/repl/js/repl/fable-library/System.Collections.Generic.js' does not provide an export named 'EqualityComparer$1__Equals_5BDDA0'`

see [REPL](https://fable.io/repl/#?code=FAewDgpgdgBAygTwM4BcIFsB0BhEAbPCAYxQEsQolMBxaCAJ1KOGEJRiIAtiBrACgCGALgDkAFQCUMPgCNRkmEJgyQ+GAF5gMbTDYd0YDTACiARwCuAvKRQJcBgfQYAecQD5MAEQgAzAebwULR0iA0wzSzwkQQAaGQkWPXojLl4YAEYYACYYYCA&html=Q&css=Q)
 (same error happens in Fable 4.9)
![image](https://github.com/fable-compiler/Fable/assets/884885/fa1a4df7-98e6-4144-aed7-5700ffc02674)

**Comment by goswinr** [comment]
Thank you @ncave ! 🙏

**Comment by goswinr** [comment]
@ncave could you publish a new version of Fable with this fix?

**Comment by MangelMaxime** [comment]
This will be included in the next version of Fable.

I am preparing it now and in the coming days.

**Comment by goswinr** [comment]
thanks @MangelMaxime ( I am using it in https://github.com/goswinr/ResizeArray that I just published)
