### ISSUE TITLE
Regression in the logging of Exceptions?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3706]
### Description

With the rework of the logging system in #3671 exception message seems to not be formatted anymore.

![CleanShot 2024-01-22 at 21 48 15](https://github.com/fable-compiler/Fable/assets/4760796/11ec1e98-0478-479d-b51b-1384d102a03d)

@nojaf Can the logging library used format the exception if one is happening inside of Fable?

The error seen in the screenshot comes from https://github.com/fable-compiler/Fable/blob/1d053a7b5512f25127125ea7e5b021e6bf6614ee/src/Fable.Transforms/Global/Compiler.fs#L275-L280

### Related information

* Fable version: 4.10.0
* Operating system: OSX

**Comment by ncave** [comment]
@MangelMaxime 
It could be [this line](https://github.com/fable-compiler/Fable/blob/main/src/Fable.Cli/Entry.fs#L618), perhaps you can change it.

**Comment by nojaf** [comment]
I have an idea, and will look into it. Might be near end of the week though.

**Comment by MangelMaxime** [comment]
Thanks you @ncave 

You were faster than me, I saw your edit + PR while stilling working on my comment 🤣
