### ISSUE TITLE
projFile/outDir parameters exhibit different behaviour when used from CLI vs specified in fableconfig.json

### ISSUE THREAD

**Issue by Kimserey** [fable-compiler/Fable#371]
### Description

The following command `fable --outDir "app" --projFile "app/app.fsx"` creates a subfolder `app/app/app.fsx`.
Whereas using a `fableconfig.json` `{  "outDir": "app", "projFile": "app/app.fsx" }` does not create a subfolder.
### Repro steps

1. Create a project with a folder structure `app/app.fsx`.
2. Run `fable --outDir "app" --projFile "app/app.fsx`
3. Create a fableconfig.json `{  "outDir": "app", "projFile": "app/app.fsx" }` and run `fable`

### Expected behavior

I am expecting the same outcome, whether it is creating a folder or not.

### Actual behavior

A subfolder is created when using the fableconfig.json

**Comment by alfonsogarciacaro** [comment]
This is a bit tricky, currently the resolution rule is "use the directory where `projFile` is as the base to resolve relative paths, if fableconfig is detected use its parent directory instead".

So the behaviour you see is not actually bug but if follows the (admittedly not properly undocumented and maybe confusing) spec. I'm not sure what's the best way to "fix" this without breaking current configurations. I wouldn't change the fact that fableconfig becomes the base dir.

We could say that if fableconfig is not detected, the base dir should be the directory from where the command is invoked instead. What do you think?

**Comment by Kimserey** [comment]
>"use the directory where projFile is as the base to resolve relative paths, if fableconfig is detected use its parent directory instead".

Oh okay I think it's fine then, it just needs to be documented.

**Comment by alfonsogarciacaro** [comment]
As this behaviour is a bit confusing, it'll change in v0.7 so arguments passed from the command line are always resolved from the current directory :+1:
