### ISSUE TITLE
Should `Choice.d.ts` be kept?

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#3728]
### Description

Hello @ncave,

I discovered that `Choice.fs` is the only F# file with an associated `.d.ts` file: https://github.com/fable-compiler/Fable/blob/main/src/fable-library/Choice.d.ts

Is it normal that this file has a `d.ts` file or should it be removed?

When targeting TypeScript or JavaScript, because we compile the `.fs` files down to TypeScript I believe we have definition files automatically no?

**Comment by ncave** [comment]
@MangelMaxime 
> When targeting TypeScript or JavaScript, because we compile the .fs files down to TypeScript I believe we have definition files automatically no?

`Choice.d.ts` was needed previously because we were compiling the F# part of `fable-library` to JS first, then invoking `tsc` on the TS portion of the library.

If we now always compile `fable-library` to TS first, then perhaps it's no longer needed.

**Comment by MangelMaxime** [comment]
Indeed, now `fable-library` is done by first compiled `fable-library-ts` and then calling `tsc` on it.

https://github.com/fable-compiler/Fable/blob/33af46d6446f0aaada0c21994b70e2d73012d0b6/src/Fable.Build/FableLibrary/JavaScript.fs#L8-L10
