### ISSUE TITLE
Implement rest of Result module

### ISSUE THREAD

**Issue by zprobinson** [fable-compiler/Fable#3732]
### Description

I recognize that other functions in the [Result module](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-core-resultmodule.html) are not supported today.

### Repro code

Please provide the F# code to reproduce the problem or a link to the [REPL](https://fable.io/repl/).
Ideally, it should be possible to easily turn this code into a unit test.

[REPL here](https://fable.io/repl/#?code=DYUwLgBATiDOCuwwC4ICU6LAHgJYDswAaCWMKAgcwD4IBeCAeQGsIBGABgCgvRIAjAgBMAKnEgMYCJBAA+tDNLAA6QfiEQAFADN4+CAH0IAWlosIAJg4BKHnwgBjAPaEAhgVhiy9aJhnz0PxVnNw92bl5wRyc9MC8JXyU5BSDlZ1i7KKEQbVcsADVXYHgQeJ8pLGTApWVs3IKikogI+zq8pAB1XDAACzLJIKrFLFqc9rAu3q1dfSNTZttIyBAAD1wyT3FywYDhpGVV9bBYab0IFZNaC4BSSx8bTMhtJ2BRLYGk3dTn19P9E4u8xOAGpztZmo8ID8hAAhVwOZj9RKVL41aFwhF-c6kS440ErcHYWQQpZQpxQIrAJEVfwpNHkylYwFXCC3Cz3Rb2bogKDUnZ0kbcqBaAAOFEI2n0ACJrkIpZyogBbVwivmfAX7ZUirSaYHgtgKyBagCiUCg5LVKI1KhNZvJOr1EClPPNUHlkLATgAgmbXABPS206ojT0+il+j1OAAyR0DkFRIejR0jjBFYFwLjjQ1SntT6ZckcKxRAeYz+CzCf2nqLJVLLiAA&html=Q&css=Q)

### Expected and actual results

I would expect the majority of the Result module to be supported. Maybe `toValueOption` doesn't need to be supported yet cuz I'm not sure what a `ValueOption` would look like in some of the targets. I was wondering if it should just cheat and return a normal option so that the API is supported and then transformations can convert it to their representation of a ValueOption at a later point.

### Related information

* Fable version: `dotnet fable --version`
* Operating system

**Comment by zprobinson** [comment]
Majority closed by #3733.

Gonna keep this open until `Result.toValueOption` is implemented in a future PR.

**Comment by ncave** [comment]
Closing as completed. Thank you for contributing!
