### ISSUE TITLE
System.Threading.Timer support

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#374]
As `System.Timers.Timer` is not available atm in .NET Core, perhaps support for `System.Threading.Timer` can be added, as that's probably what will be used [instead](http://stackoverflow.com/questions/1416803/system-timers-timer-vs-system-threading-timer).

**Comment by alfonsogarciacaro** [comment]
At first I thought this would just entail mapping `System.Threading.Timer` to `fable-core/Timer`, but it seems the API identical to `System.Timers.Timer`. I need to have a better look.

**Comment by alfonsogarciacaro** [comment]
Missing classes (including `System.Timers.Timer` are coming to NETStandard 2.0) and apparently the API of `System.Threading.Timer` is very different so it would require considerable work to add it. I'm closing the issue because of these reasons.

**Comment by ctaggart** [comment]
It is indeed coming back for .NET Standard 2.0:
https://github.com/dotnet/standard/blob/master/docs/versions/netstandard2.0.md

I need it for the Fable Elmish subscription example. https://github.com/fable-elmish/elmish/issues/101
