### ISSUE TITLE
Rust tests fail in dev container locally

### ISSUE THREAD

**Issue by zprobinson** [fable-compiler/Fable#3741]
### Description

Creating a tracking issue here for some issues I encountered while working on #3738 

After cloning the repository and opening the dev container, I added some new bindings for the Result module to the Rust compiler. To test my changes, I added tests to `tests/Rust/tests/src/ResultTests.fs` and then ran `./build.sh test rust` from the workspace root.

The F# tests compile successfully. Afterwards, the compilation to rust files failed with a weird error:
```
malloc(): unaligned tcache chunk detected
error: test failed, to rerun pass `--test src`

Caused by:
  process didn't exit successfully: `/workspaces/Fable/temp/tests/Rust/target/debug/deps/src-7c4fdba163c9ac55` (signal: 5, SIGTRAP: trace/breakpoint trap)
Compilation failed
Unhandled exception. SimpleExec.ExitCodeException: The command exited with code 1.
   at SimpleExec.Command.Run(ProcessStartInfo startInfo, Boolean noEcho, String echoPrefix, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 121
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho, String echoPrefix, Action`1 configureEnvironment, Boolean createNoWindow, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 54
   at SimpleExec.Command.Fable.Static(CmdLine args, FSharpOption`1 workingDirectory, FSharpOption`1 noEcho, FSharpOption`1 echoPrefix) in /workspaces/Fable/src/Fable.Build/SimpleExec.Extensions.fs:line 26
   at Build.Test.Rust.handle(FSharpList`1 args) in /workspaces/Fable/src/Fable.Build/Test/Rust.fs:line 104
   at Build.Main.main(String[] argv) in /workspaces/Fable/src/Fable.Build/Main.fs:line 127
```

The weird part is the tests all compile/pass here on remote. Once the merge has been completed, I am fetch/pull down main, and I can run all tests successfully.

### Related information

* Operating system: macOS Sonoma 14.2.1
* Chip: Apple M2
* Rust version (from dev container): rustc 1.75.0 (82e1608df 2023-12-21)

**Comment by ncave** [comment]
@zprobinson Thanks for reporting.
- Can the issue be reproduced reliably? Can you describe the steps to reproduce?
- Are you using an emulator in your dev container? What os/architecture is running in the container?

**Comment by zprobinson** [comment]
It seems that I can reproduce it. Here are the steps I took to reproduce:
1. Open project in the dev container
2. Run `./build.sh test rust` and ensure that it passes
3. Open Rust Result module, delete one function
4. Open Rust Result Test file, delete the test
5. Run `./build.sh test rust` (it passed here, happy news)
6. Open Rust Result module, add back in function that was removed
7. Open Rust Result Test file, add back in test that was removed
8. Run `./build.sh test rust`
9. See the same error as described above and then cry (crying optional, but encouraged)
```
malloc(): unaligned tcache chunk detected
error: test failed, to rerun pass `--test src`

Caused by:
  process didn't exit successfully: `/workspaces/Fable/temp/tests/Rust/target/debug/deps/src-7c4fdba163c9ac55` (signal: 6, SIGABRT: process abort signal)
Compilation failed
Unhandled exception. SimpleExec.ExitCodeException: The command exited with code 1.
   at SimpleExec.Command.Run(ProcessStartInfo startInfo, Boolean noEcho, String echoPrefix, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 121
   at SimpleExec.Command.Run(String name, String args, String workingDirectory, Boolean noEcho, String echoPrefix, Action`1 configureEnvironment, Boolean createNoWindow, Func`2 handleExitCode, CancellationToken cancellationToken) in /_/SimpleExec/Command.cs:line 54
   at SimpleExec.Command.Fable.Static(CmdLine args, FSharpOption`1 workingDirectory, FSharpOption`1 noEcho, FSharpOption`1 echoPrefix) in /workspaces/Fable/src/Fable.Build/SimpleExec.Extensions.fs:line 26
   at Build.Test.Rust.handle(FSharpList`1 args) in /workspaces/Fable/src/Fable.Build/Test/Rust.fs:line 104
   at Build.Main.main(String[] argv) in /workspaces/Fable/src/Fable.Build/Main.fs:line 127
```

---

I'm not doing anything other than opening the container in VSCode. Here is what I get when looking at the `etc` folder from inside the container
```
$ cat /etc/os-release
PRETTY_NAME="Debian GNU/Linux 12 (bookworm)"
NAME="Debian GNU/Linux"
VERSION_ID="12"
VERSION="12 (bookworm)"
VERSION_CODENAME=bookworm
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by zprobinson** [comment]
I also notice that nojaf has added diagnostics into the compilation process. I'm not sure right now how to activate that, but I can dive in and try to utilize that to get more information on what's going on.

**Comment by ncave** [comment]
@zprobinson 
- What does `uname -m` print inside the container?
- After you get to step 9 (right before the crying part), does it fail every time you run the tests from then on, or is it intermittent?

**Comment by zprobinson** [comment]
```
$ uname -m
aarch64
```

It's hard to see through the tears, but it seems like once I make it fail, I'm able to get a succeeding test on attempt 2 and then afterwards. Once I have a passing test run, I made some additional changes and the tests kept passing (as expected). Then performing a `git restore` to bring it back to current made the tests fail. And then running it again let the tests pass. Seems intermittent, but also seems like a pattern is occurring where the 2nd time fixes something?

I ran around a dozen times with about a 80% PASS rate.

**Comment by ncave** [comment]
@zprobinson Right, that makes sense, it might not show up every time if it's a memory issue.
I've tried to reproduce it on the `arm64` hardware I have (Raspberry Pi 4), but no dice, it works just fine. I wonder if it only happens inside of a container.

**Comment by zprobinson** [comment]
Did you mention that this issue occasionally pops up in the CI pipelines running on the github repo? The [latest pipeline failure](https://github.com/fable-compiler/Fable/actions/runs/7812807109/job/21310603106) kind of seems to have an exception thrown that looks very similar. I'd assume that would be ran in a container as well.

All else failing, how much for your ironclad raspberry pi 4? Sounds like its made out of magic :)

**Comment by ncave** [comment]
@zprobinson Doesn't look entirely random. Seems to break most often on a few particular tests, which all have in common that they use F# module let bindings, which are implemented in a particular way for Rust, using static `MutCell`. Perhaps we need a more sound `MutCell.get_or_init` implementation on `arm64` than on `amd64`.

I'll take a look when I have more time, 
Thanks for reporting the issue.

**Comment by zprobinson** [comment]
Thanks for taking a look into it! your intuition is invaluable. I appreciate your time spent troubleshooting.
