### ISSUE TITLE
Bug in DateTime: 03/2024 has 30 days instead of 31

### ISSUE THREAD

**Issue by reneederer** [fable-compiler/Fable#3777]
Hello,

my code is:
```
printf $"{DateTime(2023, 4, 1).AddDays(-1.).Day}" // correctly prints 31
printf $"{DateTime(2024, 4, 1).AddDays(-1.).Day}" // incorrectly prints 30
```

Versions:
![p](https://github.com/fable-compiler/Fable/assets/12987718/6cb0e5b6-d9e0-4aa5-8180-a98d22d91087)

**Comment by zprobinson** [comment]
That seems strange, because 4.14 in the REPL seems to work as intended given your example code.

![image](https://github.com/fable-compiler/Fable/assets/59841145/f2203f06-d927-4db3-a3dc-e23273de232d)

**Comment by MangelMaxime** [comment]
@zprobinson I can confirm that on my side .NET and Fable gives a different output.

It's possible that this is a bug related to the timezone, personally I am in Europe/Paris.
