### ISSUE TITLE
Fable tool install size

### ISSUE THREAD

**Issue by nojaf** [fable-compiler/Fable#3785]
### Description

I noticed on Windows that my extracted `fable 4.14` tool is 483 MB large.
The biggest culprit seems to be `fable-library-rust` (259 MB).

My `fable` folder (all my local tool versions in my NuGet cache) is now 6 GB.
This is a bit ridiculous considering I still only use Fable to compile F# to JS.

In light of https://github.com/fable-compiler/Fable/issues/3725, could we perhaps download the libraries for other languages on demand instead of shipping them to absolutely everyone?

//cc @MangelMaxime @ncave

**Comment by ncave** [comment]
@nojaf Your are right, the problem seems to be that we're packaging up the binary output build folder (`target`) during the build, not just the source code. Without it, `fable-library-rust` is actually smaller than the one for JS, TS or Python. I'll fix the packaging, thanks for reporting.

**Comment by nojaf** [comment]
Oh nice, happy to hear this seems to have an easy fix!
