### ISSUE TITLE
[TypeScript] Option<> to Optional Parameter misses unwrap. 

### ISSUE THREAD

**Issue by Freymaurer** [fable-compiler/Fable#3847]
### Description

I am currently working on typescript transpilation for our library [ARCtrl](https://github.com/nfdi4plants/ARCtrl/tree/typescript_support). I want to do this to offer type support for the js native release.

Sadly i get around 850 errors, which i am now trying to resolve one by one. I started investigating in:

```bash
dist/ts/Spreadsheet/Metadata/Publication.ts:32:65 

error TS2345: Argument of type 'Option<string>' is not assignable to parameter of type 'string | undefined'.

32     const status_1: OntologyAnnotation = new OntologyAnnotation(status, statusTermSourceREF, statusTermAccessionNumber);
```

And i found the following:

```typescript
export function fromString(pubMedID: Option<string>, doi: Option<string>, author: Option<string>, title: Option<string>, status: Option<string>, statusTermSourceREF: Option<string>, statusTermAccessionNumber: Option<string>, comments: Comment$[]): Publication {
    const status_1: OntologyAnnotation = new OntologyAnnotation(status, statusTermSourceREF, statusTermAccessionNumber);
    const pubMedID_1: Option<string> = map<string, string>(URIModule_fromString, pubMedID);
    const status_2: Option<OntologyAnnotation> = Option_fromValueWithDefault<OntologyAnnotation>(new OntologyAnnotation(), status_1);
    return Publication.make(pubMedID_1, doi, author, title, status_2, comments);
}
```

![image](https://github.com/fable-compiler/Fable/assets/39732517/40491b19-2940-42bf-9e07-e9d0d5106209)

I tried to replicate this behavior on the Fable REPL, but the REPL transpiles it using `unwrap` (see REPL below).

Adding `unwrap` by hand to the typescript code seems to resolve the issue. Now i am not sure why this happens.

The F# code in question can be found: [here](https://github.com/nfdi4plants/ARCtrl/blob/81560aa00af3ba0b13cc835c640367c6ae381497/src/Spreadsheet/Metadata/Publication.fs#L21)

### Repro code

[REPL](https://fable.io/repl/#?code=PYBwpgdgBAYghgIwDZgHQGFgCcwChcDaAPAIIAuZcAxgBYCyYAtgmFgM7llYCWCArmTAA+ALq4yAT3BQ6EgCpg2ZdEjhs2ACgD8EOIzAB5EGW7AIALihKeEAOYBKKAF5cUN1H3NWUAG5wkUAByemDOUAAmYABmcHxIZCRYtlC6+kYmZlAARADSYD7cEFlQAO7cZDRQtmBkADRWNfgoZFCCSug4cIJQGqmGxqYWVlyFyaAZEI4u7jLyisqq6tp96YNhKwNm9k01UAAeYW3Knd0aAMrA+tkkSGzAUHkFRdu4oJBQAEJYwCVsrKgAEUu+CoZjuKFQSGAtg0e1QwX09iAA&html=DwCwLgtgNgfAUHUBTAhgE3gAm54ElgqbhgAOAtEgI4CuAlgG4C8ARAMID2AdmEj+QBUAnqSQtMAY268erXgA8wAenDQA3BJAoATgGcCTGmABm5ABwssOYLrBCoSKzhwAjDmiGYA3nGd-MxtLkxigQdFBCAFyYAOScNNp0SNqYAHJIAO4xADSYENwcuqQoEkhqvv44CmDkKFB0AOZc0aU8yeWVmAC+FdjASrb2jogqqBgIwG4eTrhojJh0aKy6UtpimFyhSMurYjD9cwwzwIcLSyz6Ulxo9Vzrm-jLSFc3dHeWB4zHh-sSKFwMFC6M6sP4AoHiDKLMAgVgAVgAjAAmcQgJCNcDw5EfJRgwG6fZKH4jKZCeAjVSwIA&css=Q).

### Expected and actual results

Please provide the expected and actual results.

### Related information

* Fable version: `dotnet fable --version` : **4.19.2**
* Operating system : **Win 11 Pro**

**Comment by ncave** [comment]
@Freymaurer Yes, looks line it doesn't unwrap when you omit some of the optional parameters.
To reproduce, add another optional argument, but keep the caller the same, e.g.:

```fs
[<AttachMembersAttribute>]
type MyTestClass(?nameOption: string, ?otherOption: int) =
    member val Name = defaultArg nameOption "Kevin" with get, set

let testCreate (nameOption: string option) =
    MyTestClass(?nameOption = nameOption)
```

**Comment by HLWeil** [comment]
Thank you for the quick fix, @ncave!

For when is the next release containing this fix planned?

**Comment by MangelMaxime** [comment]
It is available in 4.19.3

**Comment by goswinr** [comment]
@MangelMaxime @ncave I am also working on a library for both TS and .NET. 
I have a lot of compile errors when generating d.ts definitions with TSC after fable compile to TS. 
But so far I could just ignore them and use the generated definitions with the fable compiled JS. 😅
Is there any guide or example on how to best set up `tsconfig.json` for generating d.ts files with via fable and TSC ?

**Comment by Freymaurer** [comment]
Have a look [here](https://github.com/Freymaurer/Siren/blob/main/tsconfig.json), that is at least what worked for me 🙂 but i am by no means an expert for ts.
