### ISSUE TITLE
Cannot find replacement for Microsoft.FSharp.Collections.ListModule.Except

### ISSUE THREAD

**Issue by damonmcminn** [fable-compiler/Fable#385]
### Description

`List.except` is apparently not supported by Fable. I could not find on the compatibility page where this is explicit. Am I missing something?

I'd love the opportunity to implement this and make a PR if this is needed.

### Repro steps

1. Use `List.except` in your code

2. Compile

### Expected behavior

Project compiles.

### Actual behavior

Project fails to compile with error `Cannot find replacement for Microsoft.FSharp.Collections.ListModule.Except`

### Known workarounds

Use `List.filter`

### Related information 

* Fable Version `0.5.5`
* .NET Runtime, CoreCLR or Mono Version `Mono JIT compiler version 4.4.0`
* Operating system `OS X 10.11.4`

**Comment by alfonsogarciacaro** [comment]
Ups, seems I missed that function. We're striving to support everything in the collection modules so it should be added indeed. If you want to implement it yourself, that'd be fantastic! Replacements of .NET BCL/FSharp.Core are in the aptly called [Replacements module](https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Compiler/Replacements.fs). The code is a bit messy so I'll try to explain the process to add a replacement:

1. Decide if the replacement will be inline (e.g. `"".Length` > `"".length`) or with a call to `fable-core` (e.g. [Seq.filter](https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Core/npm/fable-core.ts#L1591-L1599)). For collections, usually `Array` functions are replaced with native JS functions for performance.
2. For collections, if the function is common to `Seq`, `List` & `Array`, unless there're performance reasons, I usually implement it only for `Seq` and then build a list or an array with the result if necessary.
3. Implement tests (e.g. tests for [List.filter](https://github.com/fable-compiler/Fable/blob/master/src/tests/ListTests.fs#L154-L158))

Probably in this case you can add the method to `fable-core`, and then it should work just by adding `except` to [this list](https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Compiler/Replacements.fs#L921-L927). If you need more help to implement the replacement, just tell me. At any rate, implementing the tests would already be tremendously helpful :)

**Comment by damonmcminn** [comment]
Champion! I'll get on this then make a PR. I'll yell if I need help :D

**Comment by damonmcminn** [comment]
Here's the yell for help, and forgive my ignorance: how do I run tests without executing `build.sh` or is everything `build.sh` does necessary for running the tests?

**Comment by alfonsogarciacaro** [comment]
Yes, `build.sh` does everything to run the tests **from scratch**, but it's true it takes some time. I usually do many manual tricks when making quick tests but I just [added a template](https://github.com/fable-compiler/Fable/commit/764451f81871dc5a708a2a66237a591ab46a7165#diff-2733aba8ba2cf7ae50f52246b0b9adc0R1) to make life easier for contributors. Can you rebase with master and give it a try?

Cheers!

**Comment by damonmcminn** [comment]
Works a charm - thanks!
