### ISSUE TITLE
Delegate parameter is invoked when it shouldn't be

### ISSUE THREAD

**Issue by Preston159** [fable-compiler/Fable#3862]
### Description

When a function takes another function as a parameter, which in turn takes a function as a parameter, and attempts to call that function by passing in a function, Fable incorrectly calls the innermost function and passes in its return value rather than passing the function itself.

### Repro code

[REPL](https://fable.io/repl/#?code=LYewJgrgNgpgBAIQgcwLACgMgA4wHZwBiAhgEawB0AwiAE4wUBSAylrgSeQzfRhgNoAeAKLAAlgBcAFACIpAEgAMcALxq4EPGBgAzMXhhgAlDKMA+ALoZYEuGIDOAVS279huFJAAuOCFIArIx9SEBAoVTh-ewA5YgkxADcYARFxaTkJAE9cEB0FRSNVdQByHU0AY3iQPGKTcyt0Gzt7Qgqqgk8fP0Dg0PCVSJi4xOTMdCzcOAARGFhkOJgAFWz4Ae05hd8dDTxJOABaMx3JPkaYW1IPfWwICR8pGY2JJZWDo81JI0KVDDg4Jue9gkrTw5Q83zgYBAcHK1XsYQYUBAyDgMkBwIqMOIUFgYBkvzseButnRIPKpya2yk6x8jxg82ey1w3wJYm2Dmc2j0BjAkNmcAkAAt8AS-rC8PDKEiUTJ1s0dly3HjWeyWm0xNU+eEhSL0H8xXCERRpai5Q44MQ4GVQe18XqtRQAJJ4BIgADW8CkRlOULglx0GCAA&html=Q&css=Q)

#### Expected console output
- `del is a function`
- `testFunc called`

#### Actual console output
- `testFunc called`
- `del is undefined`
- `Uncaught TypeError: del is not a function`

### Related information

* Fable version: `4.19.3`
* Operating system: Windows 11 Pro 22631.3737

**Comment by ncave** [comment]
@Preston159 This seems to only affect delegates, as changing the type from
```fs
type DelegateType = delegate of unit -> unit
```
to
```fs
type DelegateType = unit -> unit
```
, and the call site from `del.Invoke ()` to `del ()` works as expected.

Not a fix, obviously, just a workaround.

**Comment by ncave** [comment]
@Preston159 Thanks for reporting the issue, should be resolved in the next release.

**Comment by Preston159** [comment]
@ncave Happy to help. Thanks for the quick resolution, both the workaround and the fix!

**Comment by OnurGumus** [comment]
@ncave

**Comment by ncave** [comment]
@OnurGumus Perhaps, let me know if yo can find an example. The original code was done to resolve #2400.

**Comment by OnurGumus** [comment]
@ncave Hi,
I reproduced the problem with minimal  example and  created issue. It's not related to this bug I think. 

https://github.com/fable-compiler/Fable/issues/3915
