### ISSUE TITLE
min and max occasionally return the wrong value

### ISSUE THREAD

**Issue by mattgallagher92** [fable-compiler/Fable#3884]
### Description

`max` sometimes, but not always, returns the smaller rather than bigger value. So does `min`.

### Repro code

`max 9m 300m`

### Expected and actual results

Expected: 300
Actual: 9

### Related information

* Fable version: 4.17.0 (and also [Fable REPL v4.19.3](https://fable.io/repl/#?code=PTAECUEsHMAsBcB0BYAUAW0gO1ABkQIzqgDMuuxAPgHygAOATtvAGY4BEmO+Rp56ALlABSAILs06AIYAPPIWJkKoGvSZZWHaXJ6L+QsRNRoQoAOoMA9lmgoM2UAE49y1Y2ZtQnB874UD4pKyTi5UtO4anpzBvkqCIoHGqKZmlgwA1lJWAK5YACZ2ADYApvCgcgC8IWglZQCeoFVxNaWg6DhVkCzloAA8oA3wsMU4csWFAM7FAy1l6JWgXT39g8M4DeNT5WhoEZpe7QHsbVi76vucMkdtMkA&html=DwZwpgNmDGAuAEsCeAHMBeAROKdMD4BYAKBKA&css=Q))
* Operating system: Linux

**Comment by mattgallagher92** [comment]
In case it's not obvious, an easy workaround is to run the check yourself: `if x < y then y else x`

**Comment by MangelMaxime** [comment]
Looking at the generated code, it seems like when using `if x < y then y else x` then Fable will call the `Decimal.cmp` functions instead on relying on `>` or `<` operators.

It is possible that because `Decimal` is a custom implementation via `Big.js` then `>` or `<` operators don't works on it.

**Comment by ncave** [comment]
It's not just occasionally, it's consistently wrong :)

Fixed in #3885.

**Comment by mattgallagher92** [comment]
Thanks @ncave!

Actually, `max 0.1m 300m` seemed to work fine 🤷🏼 so there was some level of inconsistency
