### ISSUE TITLE
Option.filter "secretly" returns ('a list) option

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#390]
### Description

Option.filter should be ``('a -> bool) -> 'a option -> 'a option`` while it returns ``('a list) option``

### Repro steps

```
let optionToString option = 
    match option with | None -> "None" | Some value -> value |> sprintf "Some %A"
Some 7 |> Option.filter (fun _ -> false) |> optionToString |> printfn "%s"
Some 7 |> Option.filter (fun _ -> true) |> optionToString |> printfn "%s"
```

### Expected behavior

```
None
Some 7
```

### Actual behavior

```
Some []
Some [7]
```

### Known workarounds

Overwrite ``Option.filter``:
```
module Option = 
    let filter f o = match o with | Some v when f v -> o | _ -> None
```

(Can easily go wrong when you forget to import namespace)

### Related information 

* fable: 0.5.11
* .NET 4.5.2
* Windows 7

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed bug report and the test code. This will be fixed in next release (probably 0.6.0) :+1:
