### ISSUE TITLE
System.String.EndsWith is not supported by Fable

### ISSUE THREAD

**Issue by laurentpayot** [fable-compiler/Fable#3934]
### Description

I have a project where I use [FSharpPlus](https://fsprojects.github.io/FSharpPlus/).
When pretest-compiling its Fable.Mocha test project with `dotnet fable ./tests/tests.fsproj -o output/tests`, I get the following:

```bash
./output/tests/fable_modules/FSharpPlus.1.6.1/Extensions/String.fs(74,8): (74,72) error FABLE: System.String.EndsWith is not supported by Fable
Compilation failed
```

Is [FSharpPlus `endsWith` code](https://github.com/fsprojects/FSharpPlus/blob/a4819fcb91cbeea8197bfdc155b1e593a344f869/src/FSharpPlus/Extensions/String.fs#L60) the culprit? Or could it be something special in the way `endsWith` is implemented in Fable? 

### Related information

* Fable version: 4.22.0
* Operating system: Ubuntu 24.04.1 LTS

**Comment by laurentpayot** [comment]
Related to https://github.com/fable-compiler/Fable/issues/2601?

**Comment by ncave** [comment]
Fixed by #3935

**Comment by laurentpayot** [comment]
Awesome. Thanks @ncave!

**Comment by ncave** [comment]
@laurentpayot No worries, mate, it's easy when the code is mostly already there, just needs to be enabled.

Once released, you may want to submit a PR for `FSharpPlus` repo to have the conditional [around startsWith](https://github.com/fsprojects/FSharpPlus/blob/master/src/FSharpPlus/Extensions/String.fs#L45) removed too.

**Comment by laurentpayot** [comment]
@ncave Just waiting for the release to do the PR then :wink:
