### ISSUE TITLE
Fable does not optimize tail recursion

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#394]
### Description

Fable does not optimize for tail recursion. It wouldn't be a problem in imperative languages but in F# recursion is bread and butter so we can run into this problem more frequently. For example: recursion is needed to do "break" and "continue" in loops.
### Repro steps

```
let rec sum v m s = if v >= m then s else sum (v + 1) m (s + v)
printfn "%d" (sum 0 100000 0)
```
### Expected behavior

In fsi:

```
Microsoft (R) F# Interactive version 12.0.30815.0
Copyright (c) Microsoft Corporation. All Rights Reserved.

For help type #help;;

> let rec sum v m s = if v >= m then s else sum (v + 1) m (s + v);;

val sum : v:int -> m:int -> s:int -> int

> printfn "%d" (sum 0 100000 0);;
704982704
val it : unit = ()
>
```
### Actual behavior

In chrome:

```
Uncaught RangeError: Maximum call stack size exceeded
```
### Known workarounds

Don't use recursion.
I actually hoped that simulating tail recursion with `seq` might work but for some reason it also fails with "Maximum call stack size exceeded".

```
let rec sumWithSeq v m s = seq {
    if v >= m then yield s 
    else yield! sumWithSeq (v + 1) m (s + v)
}
printfn "%d" (sumWithSeq 0 100000 0 |> Seq.head)
```
### Note

I tried to fiddle with project file but it does not seem to have any effect:

```
<PropertyGroup>
    <Configuration>Release</Configuration>
    <Platform>AnyCPU</Platform>
    ...
</PropertyGroup>
<PropertyGroup Condition=" '$(Configuration)|$(Platform)' == 'Release|AnyCPU' ">
    <DebugType>pdbonly</DebugType>
    <Optimize>true</Optimize>
    <Tailcalls>true</Tailcalls>
    ...
</PropertyGroup>
```
### Related information
- 0.5.11
- 4.5.2
- Windows 7

**Comment by alfonsogarciacaro** [comment]
Unfortunately the AST provided by the F# compiler to Fable is not optimized. Fable does some optimizations by itself but not yet tail-call recursion. However, please note that we do have a trampoline for `async` workflows so, instead of using `seq`, you can do the following:

```fsharp
let rec sumWithAsync v m s = async {
    if v >= m then return s 
    else return! sumWithAsync (v + 1L) m (s + v)
}

async {
    let! x = sumWithAsync 0L 10000L 0L
    printfn "%d" x
} |> Async.StartImmediate
```

> Note you need to use `Async.StartImmediate` to fire up async workflows in Fable

In any case, the wizard @tpetricek is already working in a [plugin to optimize tail-calls](https://github.com/tpetricek/fable-tailcalls) which hopefully will be availble soon 😄

**Comment by MiloszKrajewski** [comment]
Hi,

I absolutely understand that if F# compiler does not help with tail call optimization if is non-trivial to add it. Although, I'm wondering why ``seq`` version overflows as well? Shouldn't fableCore.Seq.delay(...) work as some kind of trampoline?

Anyway, fingers crossed (and holding thumbs) for Tomas :+1:

**Comment by alfonsogarciacaro** [comment]
Hmm, I haven't considered that. Actually our _trampoline_ technique is dead simple: after a number of callbacks has been exceeded, use `setInterval(0, continuation)` to clear the stack. Not sure if something similar could be done with `seq` but it may be a bit tricky as `seq` translates to JS `Iterable` which is synchronous.

In any case, I've sent a [PR](https://github.com/tpetricek/fable-tailcalls/pull/1) to Tomas' plugin with a couple of minor fixes to compile you sample code.

**Comment by alfonsogarciacaro** [comment]
Closing this as it's a bit difficult to optimize tail recursion in all cases. We should focus on Tomas' plugin for the moment... and hope JS VMs implement this too (as per 2015 specs).
