### ISSUE TITLE
fable-compiler-js that consumes and produces raw content 

### ISSUE THREAD

**Issue by PawelStadnicki** [fable-compiler/Fable#3967]
Today I noticed that fable-compile-js was refreshed several months ago.
That is amazing, thank you!

I wonder if something as below could be possible (without too much work):
- call `run` directly from proprietary js code
   https://github.com/fable-compiler/Fable/blob/6498a3da20a3ccdeaf2b20baeb6ca50fa213a180/src/fable-compiler-js/src/app.fs#L390
  I can see it is exported in app.js so I believe this one can be ☑
`export function run(opts, projectFileName, outDir) {`
- extend the function to accept a raw fs code (string), write that content as a dedicated file, add it at the end of *.fsproj, so it will become some sort of  Main.fs,
- execute fable against the *.fsproj and return transpiled js content so it can be further used in JS eval()  

As a context, I would like to play with F# in a place where currently [squint](https://github.com/squint-cljs/squint) (a light-weight version of ClojureScript) is used:

```
import { compileString } from 'squint-cljs';

const f = eval(compileString("(fn [] 1)"
                             , {"context": "expr",
                                "elide-imports": true}
                            ));

console.log(f()); // prints 1
```

Having this example, let's say I'm talking about this `compileString` Fable equivalent.
I'm asking if you see any obstacles or burdens to achieve it.
I can proceed then on my own with PR

**Comment by MangelMaxime** [comment]
I think what you want is to use [@fable-org/fable-standalone](https://www.npmjs.com/package/@fable-org/fable-standalone) which is the actual project which host and expose the compiler API.

This is what `fable-compiler-js` and Fable REPL use, for compiling F# code in different environnement. It will allows you to decide how you want the project file to be resolved, should there be additional API available, etc.

**Comment by PawelStadnicki** [comment]
You are right Maxime, thanks!

btw, can I get autocompletion this way as well? 
this is how Fable REPL does it ?
If yes, how it isolates autocompletions between many users that call REPL at the same time?
I'm not well versed with nodejs, but maybe it is by design there.
