### ISSUE TITLE
#, #line directive output

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#400]
This builds, but does not output any AST:

```
module Test
#line 25 "somefile.fs"
let i = 1
```
If you take the #line directive out, then it works.

**Comment by alfonsogarciacaro** [comment]
Interesting. Fable [builds a file map](https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Compiler/FSharp2Fable.fs#L968) to be able to create the necessary imports between the generated JS files later. However, if you use the `#line` directive, the file location of the entities (`entity.ImplementationLocation.FileName`) and the implementation files (`parsedProject.AssemblyContents.ImplementationFiles`) mismatch (in the sample, the later becomes `somefile.fs`) so the file map breaks down.

I don't think this is an easy fix, why do you need the `#line` directive. Are you generating code?

**Comment by ncave** [comment]
No, I'm compiling generated code with Fable. It's fine, I can just remove the #line directives.

**Comment by alfonsogarciacaro** [comment]
Great, thanks for the clarification. I'll close the issue then. Please feel free to reopen it if needed.
