### ISSUE TITLE
"fable -w" quits on compilation error

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#401]
### Description

Fable in watch mode (``fable -w``) quits if first compilation fails.

### Repro steps

Create *invalid* F# script, let's call it ``test.fsx``:

```
printfn "%s" 7
```

run Fable in watch mode:

```
fable -w test.fsx
```

*NOTE*: if code is valid on first run you are free do do as many mistakes as you like. It wont terminate anymore.

### Expected behavior

Fable reports errors and then waits for file changes.

### Actual behavior

Fable reports errors and terminates.

### Known workarounds

Write valid code. Always :-)

### Related information 

* 0.5.11
* 4.5.2
* Windows 10

**Comment by alfonsogarciacaro** [comment]
I didn't consider this much, but it's probably worth allowing recompilation with `fable -w` even if the first compilation fails, and it shouldn't be difficult to implement. I'll do it.
