### ISSUE TITLE
Using switch statements to translate pattern matching with literal values

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#402]
This fails with StackOverflowException.
```
module Test
let test i = 
  match i with
    | 001 -> 0
    | 002 -> 0
    | 003 -> 0
    ...
    | 648 -> 0
    | 649 -> 0
    | _ -> 1
```
Also, would it be possible to map the simple tests cases to a switch statement instead of chained ternary operators?

**Comment by alfonsogarciacaro** [comment]
This would be an optimization that unfortunately is not provided by FCS but it should be doable. I'll check it :+1:
