### ISSUE TITLE
"downto" in for loop is not properly handled

### ISSUE THREAD

**Issue by MiloszKrajewski** [fable-compiler/Fable#411]
### Description

I guess this is serious one.
``for i = x downto y`` generates JS identical to ``for i = x to y``, which means that in most cases it does not work.

### Repro steps

```
for i = 5 downto 1 do
    printfn "%d" i
```

### Expected behavior

``
5
4
3
2
1
``

### Actual behavior

Nothing.

### Known workarounds

None.

### Related information 

* 0.5.11
* 4.5.2
* Windows 7

**Comment by alfonsogarciacaro** [comment]
Ups, actually this was an easy fix but nobody noticed during all this long... until you did ;) Nice catch! (Fixed in fable-compiler 0.6.4)
