### ISSUE TITLE
BCL implementation

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#418]
For all the missing BCL types, is it a good idea to (optionally, possibly as a plugin) take a dependency on an existing javascript .NET implementation like [Bridge.NET](https://github.com/bridgedotnet/Bridge), instead of reinventing the wheel?
(Assuming license compatibility and notwithstanding their goal to eventually have a F# compiler too...)

**Comment by alfonsogarciacaro** [comment]
This would be very nice! I don't know Bridge.NET, do they have a JS lib that can be called from other JS code?

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, [here](https://github.com/bridgedotnet/Bridge/tree/master/Bridge/Resources) are the individual components, or see the combined library loaded by their [live playground](http://deck.net/).

**Comment by alfonsogarciacaro** [comment]
Great, thanks! I'll have a look :+1: Is there any table showing the BCL classes they're implementing? In the lib there don't seem to be that many (e.g. there're no Streams or WebClient).

**Comment by ncave** [comment]
I don't see a comprehensive list, but take a look at the [.generated](https://github.com/bridgedotnet/Bridge/tree/master/Bridge/Resources/.generated) folder. Yes, not everything seem to be implemented, but there are quite a few useful things there.

**Comment by wizzard0** [comment]
this surely calls for some eager dead code elimination

**Comment by alfonsogarciacaro** [comment]
The new fable-core 0.7 (in 0.7.0 branch atm) is totally modular so people will only pay what they get. We could start copying... I mean taking inspiration from Bridge polyfills. Of course, this is not an easy task, as the format used by Fable will not be the same as Bridge so we'll still have to adapt the code. And ideally we should add tests too.

**Comment by ncave** [comment]
Some of the Bridge.NET polyfills (decimal, int64, etc.) seem to be sources from external projects, so they are available separately as well.

**Comment by alfonsogarciacaro** [comment]
Closing the issue as it's a bit broad, we should probably open individual issues for each type/feature we want to add.
