### ISSUE TITLE
Feature Request: Add compile time to --verbose

### ISSUE THREAD

**Issue by 7sharp9** [fable-compiler/Fable#422]
Would it be possible to output compile times as part of `--verbose`

**Comment by alfonsogarciacaro** [comment]
I already added it some versions ago, but I removed the feature in a refactoring because nobody seemed to find it useful 😄 What would you use compile times for?

**Comment by 7sharp9** [comment]
Mainly as a guide to profiling some changes I was tinkering with :-)

I can see there is a time output but I would like actual ms for the FCS and fable time etc

**Comment by alfonsogarciacaro** [comment]
Ok, I'll implement it. I just commented out the timer in a refactoring because it stopped working, it shouldn't be difficult to bring it back :+1:

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
