### ISSUE TITLE
Is there a way to disabled typed arrays

### ISSUE THREAD

**Issue by ritcoder** [fable-compiler/Fable#433]
### Description

This is not really a bug though. Is there a way to disable typed arrays. In my example below my chart was failing because the array appeared like an int array and was outputted at such. The second scenario was  just fine. I'll not be using typed arrays in the webapp I'm working on so is there a way to turn it off?

### Repro steps

````
#r "./node_modules/fable-core/Fable.Core.dll"

open Fable.Core.JsInterop
let chartOptions =
  createObj [
    "data", box [|
      [| unbox "data1"; 15; 25 |]
      [| unbox "data2"; 19; 32 |]
      [| unbox "data3"; 25; 92 |]
    |]
  ]

let chartOptions2 =
  createObj [
    "data", box [|
      [| box "data1"; box 15; box 25 |]
      [| "data2"; 19; 32 |]
      [| "data3"; 25; 92 |]
    |]
  ]
````

### Expected behavior

Object was arrays

### Actual behavior

    var chartOptions = exports.chartOptions = {
      data: [new Int32Array(["data1", 15, 25]), new Int32Array(["data2", 19, 32]), new Int32Array(["data3", 25, 92])]
    };
    var chartOptions2 = exports.chartOptions2 = {
      data: [["data1", 15, 25], ["data2", 19, 32], ["data3", 25, 92]]
    };

### Known workarounds

Use box instead so it doesn't appear as an int array

### Related information 

* Fable Version
* .NET Runtime, CoreCLR or Mono Version
* Operating system

**Comment by alfonsogarciacaro** [comment]
There's no way to disable typed arrays at the moment. However it shouldn't be difficult to do it and I think yours is a very valid user case. I have already sent a PR for that (#441). The only issue is that unfortunately there's no _single point_ that can be turned on/off to compile Typed Arrays so I hope I'm not missing something. Besides that, I've added a `--noTypedArrays` option to turn the feature off (I wanted it to be `--typedArrays` but then the default would have to be true so it's non-breaking and it couldn't be turned off from the CLI), would that work for you? Please tell me if you've another suggestion.

Cheers!

**Comment by rkosafo** [comment]
The `--noTypedArrays` option is perfect. Thanks.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Why are arrays converted to a typedArray type ?

I made a quick [REPL code](https://goo.gl/44S3oJ) to see the different JS output depending on the F# code used.

```fs
let arrayFromList = [1; 2; 3] |> List.toArray

let array = [|1; 2; 3|]

let resizeArray = ResizeArray([|1; 2; 3|])
```

Having typed array make JS interop harder or less sexy because we either need to use `ResizeArray` or create an helper to use the `List.toArray` way.

I am asking because someone was having problem with that on [gitter](https://gitter.im/fable-compiler/Fable?at=5a290c593a80a84b5bc97232). And I also discovered this while working on [Thot.Json.Decode](https://github.com/MangelMaxime/Thot/blob/master/tests/Tests.Json.Decode.fs#L315-L326)

And last, is the `noTypedArrays` option still supported ? A quick search using github didn't find it in the code files.

**Comment by SCullman** [comment]
Isn't the issue  the typedArray itself, but the fact that an Int32Array is not recognized as an JS Array?

```fsharp
let  ints = [| 1;2;3; |]

[<Emit("Array.isArray($0)")>]
let isArray : obj -> bool = jsNative 

ints |> isArray |> Equal true
```

**Comment by MangelMaxime** [comment]
Yes, probably as I didn't know that `Int32Array` is a JavaScript type and not one introduce by Fable.

**Comment by inosik** [comment]
@MangelMaxime it was renamed to [`typedArrays`](https://github.com/fable-compiler/Fable/blob/23316e144d952fba9c65892f339e0ad2cad6b566/src/dotnet/Fable.Core/Compiler.fs#L6).

**Comment by SCullman** [comment]
How/ where do I set F# compiler options? package.json? webpack.config.js?

**Comment by alfonsogarciacaro** [comment]
In all the places at the same time :wink: Just kidding, @SCullman you can pass options to fable-loader in webpack.config.js, as explained in the [README](https://www.npmjs.com/package/fable-loader):

```js
  module: {
    rules: [
      {
        test: /\.fs(proj|x)?$/,
        use: {
          loader: "fable-loader",
          options: {
            define: ["DEBUG"],
            babel: babelOptions,
            typedArrays: false
          }
        }
```

**Comment by inosik** [comment]
I wonder if it makes sense to do this globally and to make this the default behavior. As a .NET person I didn't expect that numeric arrays in F# would be translated to some special kind of "array", which aren't even "arrays" as of `Array.isArray`.

Should we discuss this in another issue?

**Comment by alfonsogarciacaro** [comment]
Hmm, one could also argue that typed arrays are closer to .NET semantics as they've fixed length and a known memory size. Actually, when I started writing Fable I was hoping typed arrays would be one of the main selling points as they're much more performant (for example, [`Array.map` can be 5x faster for a typed array than a normal array](https://twitter.com/FableCompiler/status/890488515926122496)), but it's true I haven't received much feedback on that regard.

Within Fable boundaries, JS Array and typed arrays are treated equivalently in type checking, JSON serialization, etc... (e.g. we have a [custom `isArray` function](https://github.com/fable-compiler/Fable/blob/433e43ba585c40302c64227be348446971804484/src/js/fable-core/Util.ts#L152-L154)) But I acknowledge it can be problematic when sending them to a JS library that exactly expects a JS Array.

Defaults drive the community so I'm a bit concerned that changing the default make some programs lose performance. But if you want, definitely, please open a discussion issue so we can hear the community voice about this 😸

**Comment by SCullman** [comment]
What about a helper function ``Array.toJsArray``?  
```fsharp
let toJsArray a  = a |> Array.toList |> List.toArray
```
Unfortunately, this function also shows that typedArrays already have symmetry issues:
```fsharp
let  ints = [| 1; 2; 3 |]
let ints' = ints |> toJsArray 
ints' = ints // false

let strings = [| "A"; "B"; "C" |]
let strings' = strings |> toJsArray 
strings' = strings // true
```

**Comment by SCullman** [comment]
One could argue that ``List.toArray`` is broken for numbers and the following should be true, independent of any implementation detail for arrays:
```fsharp
List.toArray [1;2;3]  |> Equal  [|1;2;3|]
```

**Comment by SCullman** [comment]
Also weird:
```fsharp
let intList = [1;2;3]
intList  |> List.toArray  = [|1;2;3|] // true
[1;2;3]  |> List.toArray  = [|1;2;3|] // false
```
