### ISSUE TITLE
StringComparison parameter in String.IndexOf compiles as startIndex 3

### ISSUE THREAD

**Issue by xiety** [fable-compiler/Fable#436]
### Description

Second parameter in method [String.IndexOf (String, StringComparison)](https://msdn.microsoft.com/en-us/library/ms224425(v=vs.110).aspx) compiles as second parameter to [String.IndexOf Method (String, Int32)](https://msdn.microsoft.com/en-us/library/7cct0x33(v=vs.110).aspx) without any warnings or errors. The program starts to behave differently.

### Repro steps
```
let str = "test"
let p = "test"
str.IndexOf(p, System.StringComparison.InvariantCultureIgnoreCase)
```
### Expected behavior

`return str.indexOf(p);` and some warning
or
`s.toLowerCase().indexOf(p.toLowerCase());`

### Actual behavior

`return str.indexOf(p, 3); `

### Known workarounds

Remove `System.StringComparison.InvariantCultureIgnoreCase` parameter from method call

### Related information 

* Fable Version 0.6.7

**Comment by alfonsogarciacaro** [comment]
Thanks for the report. As it's a bit complicated to support all string comparison methods of .NET for the moment Fable will throw an exception as you recommend so there's no unexpected behavior at runtime.
