### ISSUE TITLE
Seq.pairwise does not work properly

### ISSUE THREAD

**Issue by xiety** [fable-compiler/Fable#437]
### Description

Seq.pairwise does not work properly. Extra pair (with zero) added at the beginning.
Test `Seq.pairwise works` doesn't check for this situation.

### Repro steps

`[10; 20; 30] |> Seq.pairwise`

### Expected behavior

`[[10,20],[20,30]]`

### Actual behavior

`[[0,10],[10,20],[20,30]]`

### Known workarounds

`Seq.skip 1`

### Related information 

* Fable Version 0.6.7

**Comment by alfonsogarciacaro** [comment]
Thanks for checking that! Apparently the unit test was not good enough to discover the problem. This will be fixed in the next release of Fable (0.6.8 or 0.7.0, probably by the end of the week).

**Comment by alfonsogarciacaro** [comment]
Fixed in `fable-core@^0.6.4`, please update the dependency to get the fix :+1:
