### ISSUE TITLE
Incorrect this in local let functions

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#438]
### Description

In defining a class, sometime when one let function calls another let function, `this` is incorrectly referenced.

### Repro steps

    type IRenderer =
      abstract member doWork: unit -> unit

    type MyComponent(name) =
      let work () = printfn "Renderer for %s" name
      let create2 () = { new IRenderer with member __.doWork () = work () }
      member __.works () = { new IRenderer with member __.doWork () = work () }
      member __.doesNotWork () = create2()
    MyComponent("Test").doesNotWork().doWork()

### Expected behavior

Both `works` and `doesNotWork` should give same result

### Actual behavior

````
e:\temp\fable>fable test.fsx && node test.js 
fable-compiler 0.5.11: Start compilation... 
Compiled test.fsx at 5:14:16 PM 
E:\temp\fable\test.js:96                                    
          this.work();                                   
               ^     
                                                                                                             
TypeError: this.work is not a function  
````

### Known workarounds

Code from js file

    {
        key: "create2",
        value: function create2() {
          var _ref2;

          var $var2 = this;
          return _ref2 = {}, _defineProperty(_ref2, _fableCore.Symbol.interfaces, ["Test.IRenderer"]), _defineProperty(_ref2, "doWork", function doWork() {
            this.work(); //ERROR: This should have been $var2
          }), _ref2;
        }
      }

    {
        key: "works",
        value: function works() {
          var _ref;

          var $var1 = this;
          return _ref = {}, _defineProperty(_ref, _fableCore.Symbol.interfaces, ["Test.IRenderer"]), _defineProperty(_ref, "doWork", function doWork() {
            $var1.work(); //correctly set
          }), _ref;
        }
      }

### Related information 

* Fable Version: 0.5.11
* .NET Runtime, CoreCLR or Mono Version
* Operating system

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report! This proved to be a bit tricky but hopefully it should be fixed in fable-compiler@0.6.8. It'll be released in a few hours :+1:
