### ISSUE TITLE
Seq.groupBy different values order for each key

### ISSUE THREAD

**Issue by xiety** [fable-compiler/Fable#440]
### Description

Seq.groupBy different values order for each key

### Repro steps

`Seq.groupBy fst [(1, "A"); (1, "B"); (1, "C")]`

### Expected behavior

`[[1,[[1,"A"],[1,"B"],[1,"C"]]]]`

### Actual behavior

`[[1,[[1,"C"],[1,"B"],[1,"A"]]]]`

### Known workarounds

`Seq.map (fun a -> (fst a, snd a |> Seq.rev))`

### Related information 

* Fable Version 0.6.7

**Comment by alfonsogarciacaro** [comment]
Thanks! Again, the unit test wasn't strong enough to catch this 😕 It'll be fixed in fable-core 0.6.6.

**Comment by alfonsogarciacaro** [comment]
`fable-core@0.6.6` has already been published :+1: Please update the dependency to get the fix.
