### ISSUE TITLE
Discriminated unions and interacting with JS

### ISSUE THREAD

**Issue by minedeljkovic** [fable-compiler/Fable#447]
In the two sections of Interacting with JavaScript docs ([Erase attribute](https://github.com/fable-compiler/Fable/blob/2c04fcdca20733e38bc758a2e6a513f55993656d/docs/source/docs/interacting.md#erase-attribute) and [StringEnum attribute](https://github.com/fable-compiler/Fable/blob/2c04fcdca20733e38bc758a2e6a513f55993656d/docs/source/docs/interacting.md#stringenum-attribute)), it is described how to present [simple union](https://www.typescriptlang.org/docs/handbook/advanced-types.html#union-types) and [enum](https://www.typescriptlang.org/docs/handbook/advanced-types.html#string-literal-types) TypeScript types.

In TypeScript 2.0, [tagged union](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#tagged-union-types) has been added, and these types are conceptually very close to F# discriminated unions.

Is there some way to annotate these types?

Example:

[TypeScript Shape example](https://github.com/Microsoft/TypeScript/wiki/What%27s-new-in-TypeScript#example-5)

F# types:

``` F#
type Square = { size: float }
type Rectangle = { width: float; height: float }
type Circle = { radius: float }

type Shape =
    | Square of Square
    | Rectangle of Rectangle
    | Circle of Circle
```

Note: I guess that usage of tuples and simple types instead of records, which are probably more common in F# for this kind of domain, would probably need more fable annotations.

**Comment by alfonsogarciacaro** [comment]
Hehe, I'm afraid we cannot keep up with Typescript new features that fast :wink: Well, actually we're not trying to keep up with Typescript, the `Erase` and `StringEnum` attributes are just there to translate to F# some of the concepts in .d.ts files.

As you say, the new tagged unions are closer to F# unions but the structure remains different (Fable represents F# unions with a JS _class_ with `Case` and `Fields` fields), so trying to adapt them now to the new TS tagged unions can be difficult. Also, adding an annotation to represent F# unions as TS tagged unions may be confusing and error-prone.

It seems tagged unions are there to make some sort of pattern matching possible in TypeScript. What would be the value for F# developers to have union types represented as tagged unions?

**Comment by alfonsogarciacaro** [comment]
With latest Fable it's possible to compile DUs as tagged unions using the `PojoAttribute`, but the tag property will always be named `type` (for compatibility with Redux). Please check the [Redux sample](https://github.com/fable-compiler/Fable/blob/259d71caaa5cfb23c76423d7bd4edc427f8bd0c6/samples/browser/redux-todomvc/redux-todomvc.fsx#L76).

**Comment by ImaginaryDevelopment** [comment]
The `PojoAttribute` doesn't seem to exist anymore, and using `[<Erase>]` on records seems to break any usage of those types

**Comment by alfonsogarciacaro** [comment]
I don't remember exactly, but I think for Fable 2 we tried to reduce the number of magic attributes for the sake of simplicity and `PojoAttribute` was one of the removed ones. There's a similar discussion going on at #2096.
