### ISSUE TITLE
IDeclarePlugin.TryDeclare not invoked on members

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#452]
IDeclarePlugin.TryDeclare not invoked on class members, object expression members.

**Comment by alfonsogarciacaro** [comment]
Sorry, I don't understand this well. Could you give more info or an example? At the moment, `TryDeclare` is invoked [here](https://github.com/fable-compiler/Fable/blob/b69fcc8ca6267a72958a1d9a54f89a9495e2bfbf/src/fable/Fable.Compiler/Fable2Babel.fs#L889), do you see anything wrong?

**Comment by ncave** [comment]
No, nothing wrong, it works, I was just saying it only get executed for module [members](https://github.com/fable-compiler/Fable/blob/b69fcc8ca6267a72958a1d9a54f89a9495e2bfbf/src/fable/Fable.Compiler/Fable2Babel.fs#L894)/entities but not for class [members](https://github.com/fable-compiler/Fable/blob/b69fcc8ca6267a72958a1d9a54f89a9495e2bfbf/src/fable/Fable.Compiler/Fable2Babel.fs#L703) or object expression [members](https://github.com/fable-compiler/Fable/blob/b69fcc8ca6267a72958a1d9a54f89a9495e2bfbf/src/fable/Fable.Compiler/Fable2Babel.fs#L345). So, you can modify a class entity declaration in a module with your plugin if you need to, but you cannot modify a particular class member, so it's a little bit less useful, that's all.

**Comment by alfonsogarciacaro** [comment]
Ah, ok! Sorry, I misunderstood the description at the beginning. You're right, the `IDeclarePlugin` was much Tailored for the NUnit plugin so I missed class/object expression members. It shouldn't be very difficult to extend it, so I'll try to implement it for 0.7.0 :+1:

**Comment by alfonsogarciacaro** [comment]
Not many users are using plugins, so this is not a priority. Let's close it for now and revisit later :+1:
