### ISSUE TITLE
Testing 0.7 alpha

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#474]
Hi Fable users! We need your help to make sure the new v0.7 is ready for release. This is a big update with lots of improvements thanks to community feedback, and I'd like to be sure I didn't break anything in the process :wink: There may be also still room for final adjustments and polishing.

You can install latest fable-compiler and fable-core alpha versions by using the `next` tag as in `npm i fable-compiler@next`. There'll be probably several releases in the next days, so make sure you always have latest alpha until 0.7.x is launched as a stable release.

I still need to update the docs, but here is a rough list of main changes:

- Add type info to classes and improve JSON serialization. See PR #463. Reflection API coming soon!
- `EntryModuleAttribute` to be able to refer Fable packages as `dll`s without using the `--refs` compiler argument. This is used by the new [fable-powerpack](https://github.com/fable-compiler/fable-powerpack/tree/master/src) package. See PR #465.
- Resolve imports with relative paths. See #472. **Attention**: this is a breaking change, particularly for [references](https://github.com/fable-compiler/Fable/issues/472#issuecomment-253975921).
- Make `fable-core` modular: this combined with ES2015 bundlers like Rollup greatly improves dead code removal.
- [Experimental] Mutating update records. See PR #464.
- [Experimental] Add `--bundler` compiler option. See PR #469.

An example using the new fable-powerpack and the experimental bundler option is here: https://github.com/alfonsogarciacaro/fable-pixi-sample1

**Comment by tommes** [comment]
I've tried the fable-pxie-sample1 and ran into an error. 
`0 info it worked if it ends with ok
1 verbose cli [ 'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'build' ]
2 info using npm@2.15.9
3 info using node@v4.6.0
4 verbose run-script [ 'prebuild', 'build', 'postbuild' ]
5 info prebuild fable-pixi-sample1@1.0.0
6 info build fable-pixi-sample1@1.0.0
7 verbose unsafe-perm in lifecycle true
8 info fable-pixi-sample1@1.0.0 Failed to exec build script
9 verbose stack Error: fable-pixi-sample1@1.0.0 build: `fable`
9 verbose stack Exit status 1
9 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\lifecycle.js:217:16)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at EventEmitter.emit (events.js:172:7)
9 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\lib\utils\spawn.js:24:14)
9 verbose stack     at emitTwo (events.js:87:13)
9 verbose stack     at ChildProcess.emit (events.js:172:7)
9 verbose stack     at maybeClose (internal/child_process.js:829:16)
9 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:211:5)
10 verbose pkgid fable-pixi-sample1@1.0.0
11 verbose cwd D:\Projects\fable-pixi-sample1
12 error Windows_NT 10.0.14393
13 error argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
14 error node v4.6.0
15 error npm  v2.15.9
16 error code ELIFECYCLE
17 error fable-pixi-sample1@1.0.0 build: `fable`
17 error Exit status 1
18 error Failed at the fable-pixi-sample1@1.0.0 build script 'fable'.
18 error This is most likely a problem with the fable-pixi-sample1 package,
18 error not with npm itself.
18 error Tell the author that this fails on your system:
18 error     fable
18 error You can get information on how to open an issue for this project with:
18 error     npm bugs fable-pixi-sample1
18 error Or if that isn't available, you can get their info via:
18 error
18 error     npm owner ls fable-pixi-sample1
18 error There is likely additional logging output above.
19 verbose exit [ 1, true ]
`

Steps:
1) clone pixie repo
2) installed node (had it never on this machine)
3) npm install
4) npm run build

How can I help?

**Comment by alfonsogarciacaro** [comment]
Hi @tommes! Do you have .NET/Mono installed on that machine? Sorry, that's also a Fable requirement.

**Comment by tommes** [comment]
@alfonsogarciacaro I have VS2015 installed, node 4.6, MS Build tools 2013. 
just calling `fable` executes the compiler successfully and creates `index.js`and `index.js.map` in out.
However, it doesn't create a `bundle.js`.
running `npm run build` still throws the error as above.

**Comment by alfonsogarciacaro** [comment]
That's probably because the Fable version you have installed globally is not 0.7.x-alpha so it cannot produce bundles yet.

Can you please try updating npm? `npm install --global npm` It may be that the npm version you have cannot run scripts in `package.json`.

**Comment by tommes** [comment]
ok, updated npm and the global fable-compiler.

log, when I run npm run build:
[npm-debug.log.txt](https://github.com/fable-compiler/Fable/files/536058/npm-debug.log.txt)

if I run fable directly I get the following message:
`D:\Projects\fable-pixi-sample1>fable
fable-compiler 0.7.5-alpha.5: Start compilation...
BUNDLE ERROR: Error: Could not resolve 'fable-powerpack/es2015/.//Users/alfonsogarciacaronunez/Documents/Github/fable-powerpack/src/Promise' from D:\Projects\fable-pixi-sample1\out\index.js`

seems to be an absolute path somewhere.

**Comment by alfonsogarciacaro** [comment]
@tommes Thanks a lot for the info! I've updated the packages, can you please pull latest fable-pixi-sample1 and then run `npm i` and `npm run build` again. Cheers!

**Comment by tommes** [comment]
@alfonsogarciacaro Thanks for the update. Now it compiles, but server crashes on start.
`node server` gives:
`D:\Projects\fable-pixi-sample1>node server
module.js:327
    throw err;
    ^

Error: Cannot find module 'fable-core'
    at Function.Module._resolveFilename (module.js:325:15)
    at Function.Module._load (module.js:276:25)
    at Module.require (module.js:353:17)
    at require (internal/module.js:12:17)
    at Object.<anonymous> (D:\Projects\fable-pixi-sample1\server\index.js:24:18)
    at Module._compile (module.js:409:26)
    at Object.Module._extensions..js (module.js:416:10)
    at Module.load (module.js:343:32)
    at Function.Module._load (module.js:300:12)
    at Function.Module.runMain (module.js:441:10)`

seems there is some "startup" missing in fable-core (latest is 0.7.5-alpha.3)

**Comment by alfonsogarciacaro** [comment]
Well, at least that's one step forward :) Are you running the server using `npm start`?

**Comment by tommes** [comment]
I've tried npm start, that crashes as well, so I tried `node server` - that produced the error above. Starting index.html with a browser, however, works. So It's more a server issue.

**Comment by alfonsogarciacaro** [comment]
Ok, I'm an idiot. I forgot to recompile the server script with latest fable-compiler version (now fable-core is modular, not a single file, and that's why it wasn't loaded properly). I fixed that. Can you pull the latest changes and try again? Crossing fingers so everything goes right this time :wink: Thanks a lot for your patience, @tommes!

**Comment by tommes** [comment]
@alfonsogarciacaro works perfectly. I am also an idiot 'cause I've `fable`'d server/index.js but didn't notice that the result was put into the root dir. Still learning...

**Comment by alfonsogarciacaro** [comment]
@tommes Not at all! Actually it was also a bug in alpha that the result was put in the root dir. If `outDir` is not specified, the JS should go in the same directory as the F# project file. It should be fixed in latest alpha :+1:

Alpha versions always lack polishing, that's why I appreciate a lot your collaboration to test it. I'll be updating the docs soon!

**Comment by tommes** [comment]
great, I am happy to help.
btw: does allow fableconfig.json allow for separate compilation of client and server? Any pointers to how that would look like?

**Comment by alfonsogarciacaro** [comment]
If the server is .NET, you must compile it normally with F# build tools (IDEs, FAKE...). If the server code is also supposed to compile to JS, there's no _standard_ way to do something like this. But you can put everything in the same project and just have different entry points, like the [react-tutorial sample](https://github.com/fable-compiler/Fable/tree/master/samples/browser/react-tutorial/src) does. fable-electron samples do something similar by using a `files.fsx` to load both main and renderer scripts and then [configuring webpack to create two different bundles](https://github.com/fable-compiler/fable-electron/blob/master/samples/helloworld/webpack.config.js#L7).

If you're using Visual Studio you can create a multi-project solution, you can have one `fableconfig.json` for each project (and then a script that runs each one) and use the [--refs compiler argument](http://fable.io/docs/compiling.html#Project-references), but note the way to do references is changing a bit with [0.7 alpha](https://github.com/fable-compiler/Fable/issues/472#issuecomment-253975921).

**Comment by tommes** [comment]
Thanks for detailled info, I definitely need to dig deeper here.

**Comment by alfonsogarciacaro** [comment]
Superseded by #516
