### ISSUE TITLE
Three.js as node package breaks [<Emit>]

### ISSUE THREAD

**Issue by aolney** [fable-compiler/Fable#476]
### Description

webGLTerrain loads three.js within `index.html` using a `script` tag:

```
<script src="//cdnjs.cloudflare.com/ajax/libs/three.js/r77/three.js"></script>
```

However, the README for fable-import-three suggests that `three` can be added via `npm`:

```
$ npm install --save fable-core three
```

The problem is that if three.js is added via npm, the `Emit` call in renderer.fsx 

```
[<Emit("new THREE.FirstPersonControls($0...)")>]
```

with `Uncaught ReferenceError: THREE is not defined`

The emitted js in `renderer.js` shows that everywhere else, the three.js reference is represented by `_three` instead of `THREE`. Renaming to `[<Emit("new _three.FirstPersonControls($0...)")>]` only causes the emitted js everywhere else in `renderer.js` to increment to `_three2`
### Repro steps

Please provide the steps required to reproduce the problem
1. Go to webGLTerrain sample
2. In `index.html` comment out script line with three.js
3. Add `three` as an npm dependency
### Expected behavior

The `Emit` command should be able to match the renaming imposed by node.
### Actual behavior

The `Emit` command is not able to match the renaming imposed by node. 

Interestingly everything brought in by fable-import-three is fine.
### Known workarounds

I commented out the offending code to make the rest of the sample run.
### Related information
- Fable Version: 0.6.12
- .NET Runtime, CoreCLR or Mono Version: Mono JIT compiler version 4.6.0 (Stable 4.6.0.245/746756c Wed Sep 21 14:16:42 UTC 2016
- Operating system: Debian unstable, 4.7.0-1-amd64 #1 SMP Debian 4.7.4-2 (2016-09-19) x86_64 GNU/Linux

**Comment by alfonsogarciacaro** [comment]
Sorry for the late reply. There'll be many changes in the new 0.7, so I still need to adapt the code of the samples to it. The problem of this sample is one of the imported scripts was expecting `THREE` to be available globally, but I'll try to modify it so it's not necessary anymore :+1:

**Comment by alfonsogarciacaro** [comment]
The sample has been updated (in the repo, not in the website) to work with Fable 0.7. Can you please check and reopen the issue if it's still not working for you?

**Comment by aolney** [comment]
I can confirm this also works in the electron sample version, but I don't want to commit it b/c I'd rather commit the new syntax
