### ISSUE TITLE
fable-core.ts compilation fails

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#477]
when compiled with TypeScript 2.0 (mostly minor stuff, missing properties here and there)

**Comment by alfonsogarciacaro** [comment]
Thanks for the notice! As fable-core.ts was growing too big (it even made my VS Code freeze) I just made a big refactor to make it modular: https://github.com/fable-compiler/Fable/commit/f56710c7ac5d17dcc2863bc37f47bedd8c2c53b5

The compilation errors should be fixed after merging `0.7.0` with `master` 😄
