### ISSUE TITLE
Automatically transform lambdas to delegates with module functions

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#485]
Pull request #335 discussed full automatic de-currying, which unfortunately does not work in general.

Issue #354 implemented automatic lambda -> delegate in specific situations, which covers the majority of use cases.

But I think there's one more situation where it would be useful to have automatic conversion from lambdas to delegates: module functions.

Consider this code:

```
module Main

let fold (fn: System.Func<_, _, _>) init a = ...

do
    fold (fun x y -> x) ... ...
```

From what I understand, module functions (like `fold`) are actually .NET methods in a class, not lambdas. That's why they are compiled to multi-arg JS functions rather than one-arg curried JS functions.

So it should be possible to support automatic lambda -> delegate conversion for module functions. The above code would compile to this:

```
export function fold(fn, init, a) {
    return ...;
}

export function main() {
    fold(function (x, y) {
        return x;
    }, ..., ...);
}
```

This means that most of the higher-order functions (`map`, `fold`, etc.) can obtain automatic de-currying by simply specifying `System.Func` in their type and using `fn.Invoke`. This should give a nice performance boost without requiring any changes to the caller.

As far as I can see, the only downside is that this breaks compatibility with F#, which does not do automatic conversions. I don't think that's a big deal, but you know the F# ecosystem much better than me, so you might disagree.

**Comment by Pauan** [comment]
P.S. No rush on this, Fable is already really fast (because module functions are uncurried), so this is a very minor issue.

**Comment by alfonsogarciacaro** [comment]
This is already possible with uncurried static methods:

```fsharp
type M =
    static member fold (fn: System.Func<_, _, _>, init: int, a: int) = fn.Invoke(init, a)

M.fold((fun x y -> x), 5, 6)
```

It's a pity F# puts so many restrictions in module functions, but I think it has to do with type inference.

Another alternative is to use type aliases, though both the lib author and the consumer must be explicit on that:

```fsharp
type F2<'a,'b,'c> = System.Func<'a,'b,'c>

let fold (fn: F2<int,int,int>) init a = fn.Invoke(init, a)

fold (F2(fun x y -> x)) 5 6
```

**Comment by alfonsogarciacaro** [comment]
Also please note that Fable already uncurries lambdas for all higher order functions in FSharp.Core.  With custom code this is very difficult, because you never know if the programmer is going to do partially apply the lambda or not.

**Comment by Pauan** [comment]
"because you never know if the programmer is going to do partially apply the lambda or not."

Could you elaborate on that? Why are the built-in `Fable.Core` functions able to handle it correctly, but user-created functions cannot?

**Comment by alfonsogarciacaro** [comment]
This is an example of something that's difficult to foresee: https://github.com/fable-compiler/Fable/pull/335#issuecomment-239495871

**Comment by Pauan** [comment]
@alfonsogarciacaro Doesn't that same problem exist with the built-in functions?

* Input
```
List.fold (fun x y -> x + y) 0 [1; 2; 3]
List.fold (fun x y z -> y + z) (fun _ -> 0) [1; 2; 3]
```

* Output
```
fold(function (x, y) {
    return x + y;
}, 0, ofArray([1, 2, 3]));

fold(function (x, y) {
    return function (z) {
        return y + z;
    };
}, function (_arg1) {
    return 0;
}, ofArray([1, 2, 3]));
```

So why is it okay for built-in functions to uncurry, but not for a user-created function which uses `System.Func`?

**Comment by alfonsogarciacaro** [comment]
TBH, I've forgotten all the intricacies of #335, I'd need to go again through the whole code and discussion to remember exactly what were the show stoppers. But I've tried to do this optimization several times and I've always failed, so I'd rather use my time to improve other aspects of Fable. Of course you are more than welcome to give it a try, you may success where I've failed :wink:

There're already several checks to solve cases like your sample above (which is working) ([example](https://github.com/fable-compiler/Fable/commit/862e21f11a7a5ff6ef2dece31b3e38bfc2a89737)). Built-in functions are manageable because all of them are known but with user code is difficult to cover any possibility (like the [sample](https://github.com/fable-compiler/Fable/pull/335#issuecomment-239495871) in the link above).

Once you do the conversion to `System.Func<>`, the F# compiler won't allow to partially apply the function anymore, that's why it's safe to uncurry it in compiled JS code.

**Comment by Pauan** [comment]
Right, which is why I'm **not** suggesting automatic uncurrying, I'm only suggesting uncurrying when you use `System.Func`. It would use the same system that methods use to uncurry `System.Func`.

I completely understand that this is a minor issue and that you would rather focus on other things. But since "`System.Func` uncurrying with methods" already exists, I figured it would be easy to extend it to "`System.Func` uncurrying with functions".

If it turns out to be too much work, then feel free to ignore this issue.

**Comment by Pauan** [comment]
I might try implementing it myself, since it seems like it shouldn't be too hard. Maybe that will also help me understand the deeper reasons why this is so difficult to implement.

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
