### ISSUE TITLE
`option` is implemented incorrectly

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#487]
Because `option` is erased in Fable, it is impossible to distinguish between `Some None` and `None` (they are the same at runtime).

There are some benefits to this approach:
- Potentially faster at runtime because it does not need to wrap/unwrap values.
- Easier JavaScript interop: a lot of JavaScript functions can be used as-is without a manual conversion step. This is especially convenient for optional fields in an object (e.g. TypeScript).
- Better JSON interop (and smaller JSON file sizes).

But there are downsides as well:
- It is incorrect.
- It is impossible to distinguish between `Some None` and `None`
  
  There are many reasons why an F# program might want to distinguish between `Some None` and `None`, but here is one example:
  
  If you have a dictionary, you might have a [`TryFind`](https://msdn.microsoft.com/en-us/visualfsharpdocs/conceptual/map.tryfind%5b'key,'value%5d-method-%5bfsharp%5d) method which returns an `option`: if the key exists then it returns `Some <value>`, and if the key does not exist then it returns `None`
  
  But because `option` is erased, it is impossible to distinguish between "the key exists with value `None`" and "the key does not exist".
  
  This might seem like a minor issue, but it affects all kinds of things. An example is a cache: if the key exists in the cache, it just returns it. If the key doesn't exist, it will compute the value and then store it in the cache. But if the value is `None` then it will recompute it every time (it will never get cached).

I'm bringing this up because I consider the benefit of `Some None` to be more important than performance or interop.

I hate dealing with `null` in JavaScript, and one of the reasons is because it's impossible to distinguish between "this value is `null`" and "this value does not exist". Over the years, I've run into this problem multiple times in JavaScript.

F# doesn't have that problem: `option` always behaves correctly and sanely. That means fewer bugs and less things to worry about. Peace of mind and correctness are two huge reasons why I love static typing. So I think `option` should **not** be erased in Fable.

However, performance and interop _are_ important, so we should consider an alternative, such as a new `JSNull<'a>` type which is similar to `option` except that it is erased. We can then provide functions to convert from `JSNull` to `option` (and vice versa). We can even have the Fable compiler auto-convert them (for convenience).

This issue doesn't need to be solved immediately, but I wanted to at least get the discussion started so we can consider it for the future.

**Comment by vasily-kirichenko** [comment]
As a consequence, the following code
```fsharp
let (|StartsWith|_|) (pat: string) (str: string)  =
    match str with
    | null -> None
    | _ when str.StartsWith pat -> Some()
    | _ -> None
```
is compiled to
```javascript
var Patterns = exports.Patterns = function ($exports) {
    var $StartsWith$_$ = $exports.$StartsWith$_$ = function $StartsWith$_$(pat, str) {
        return str == null ? null : str.indexOf(pat) === 0 ? null : null;
    };
```
which is totally wrong.

**Comment by alfonsogarciacaro** [comment]
@vasily-kirichenko This has been fixed in latest 0.7 alpha, but admittedly with an ugly patch because now `Some ()` (has to be `unit` type specifically) is compiled to an empty JS object `{}` so it's not a falsy value.

**Comment by wizzard0** [comment]
I would advocate compiling to singleton object, instead of just empty object

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit.
