### ISSUE TITLE
fable-core split

### ISSUE THREAD

**Issue by fdcastel** [fable-compiler/Fable#490]
### Description

The split of `fable-core` in several files was a good choice. However, we need to keep an `index.d.ts` in the package root to keep the compatibility with previous version (and also to keep the imports less verbose).

**Before 0.7.x:**

`import { List } from 'fable-core';`

**After 0.7.x:**

`import * as List from 'fable-core/List';`

Note that in the second form we need to repeat the `List` twice.

I'll work on this one now.

**Comment by fdcastel** [comment]
Hm. Not so simple...

I made the following `index.js`/`index.d.ts` (both files have the same content):

```
export { default as Async } from './Async';
export { default as Choice } from './Choice';
export { default as Event } from './Event';
export { default as GenericComparer } from './GenericComparer';
export { default as Lazy } from './Lazy';
export { default as List } from './List';
export { default as MailboxProcessor } from './MailboxProcessor';
export { default as Map } from './Map';
export { default as Set } from './Set';
export { default as Symbol } from './Symbol';
export { default as Timer } from './Timer';
```

However, this is insufficient to solve the problem. 

Using the first form:

```fsharp
import { List } from 'fable-core';

List.ofArray([])   // property ofArray does not exist on type 'typeof List'
new List()         // ok
```

Using the second form:

```fsharp
import * as List from 'fable-core/List';

List.ofArray([]);   // ok
new List();         // error -- should be new List.default()    (ugh!)
```

We need a better way to split the library which would
 - keep the imports simple; and
 - allow us to use the syntax most similar to F#.

**Comment by fdcastel** [comment]
Found it. 

In fable-core 0.6.x the methods of `List<T>` were declared as static class members:

```js
export declare class List<T> implements IEquatable<List<T>>, IComparable<List<T>>, Iterable<T> {
    head: T;
    tail: List<T>;
    constructor(head?: T, tail?: List<T>);
    static ofArray<T>(args: Array<T>, base?: List<T>): List<T>;
    ...
```

However, in fable-core 0.7.x this was changed to simple functions:

```js
export declare function ofArray<T>(args: Array<T>, base?: List<T>): List<T>;

export default class List<T> implements IEquatable<List<T>>, IComparable<List<T>>, Iterable<T> {
    head: T;
    tail: List<T>;
    constructor(head?: T, tail?: List<T>);
```

Why? 

Problem is: having several `export`s makes it impossible to reconcile them with an `export default` under a common name. We would need to write something like:

```js
import { List } from 'fable-core';
import * as ListModule from 'fable-core/List';

ListModule.ofArray([]);
new List();
```

Or, in other words, "meh!" 😉

**Comment by fdcastel** [comment]
Well... Please just forget the "Why?" part, which you already told me in https://github.com/fable-compiler/Fable/issues/489#issuecomment-254960397 and I manage to completely DOH! it the first time. 😅 

Tree-shaking is definitely a plus! But I find the syntax deviation a bit worrisome. 

What do you think? Or I'm missing something here?

**Comment by alfonsogarciacaro** [comment]
Yeah, that's the problem. I also tried to create an index file but it didn't work because of that. Although being able to use the fable-core library from JS and TS is definitely a plus, I think we should prioritize the use from F# with tree-shaking which will be a strong selling point against other compile-to-JS languages that produce very big bundle sizes.

What do you mind by `syntax deviation`? Actually I think using module functions is a much more natural way in ES6 (it was precisely designed to allow tree-shaking). Static methods are more foreign to JS and are there mainly for programmers used to them from other languages, I guess.

**Comment by alfonsogarciacaro** [comment]
Note you can still use fable-core from JS but importing each function separately (which I admit is not convenient) or importing the whole `List`, `Set`... package, which will give you intellisense with VS Code (an probably also dead code removal when minifying the bundle with uglify-js).

**Comment by fdcastel** [comment]
I fully agree with the prioritization to Tree shaking. The syntax change is a very minor near this one. 

> What do you mind by syntax deviation?

Take `List.partition`, for example.

In F# we would write

```fsharp
List.partition predicate list
```

And, before the split, the equivalent in JS/TS would be

```js
import { List } from 'fable-core';

List.partition(predicate, list);
```

Which is very similar to the original FSharp syntax.

However, after the split, now we have to write 

```js
import { partition } from 'fable-core/List';

partition(predicate, list);
```
I see your point about functions being more "natural" to JS. It's just that when I think in "partition" in F# it's always linked with a type (List.partition, Set.partition, etc). Never a "free" function.

Sure, we could write

```js
import * as List from 'fable-core/List';

List.partition(predicate, list);
```

but this would be in detriment of the `List` class, which now must be referenced as

```js
let list = new List.default();
```

again, a different syntax from the original one.

Well.. I will abuse a bit more of `.d.ts` files and let's see what we can get 😉.

**Comment by fdcastel** [comment]
After some experiments, I decided to let everything as it is now (without an index for fable-core) and  to adopt the following convention:

```js
import { ofArray as List_ofArray, partition as List_partition } from 'fable-core/List';
```

This allows me:

  - to keep the names similar to FSharp; and
  - to import just the required methods (improving tree shaking)

So... I'm closing this one. Thanks for the tips and for the enlightenment 😄 .
