### ISSUE TITLE
Running React with Redux and Fable

### ISSUE THREAD

**Issue by leolorenzoluis** [fable-compiler/Fable#493]
### Description

Trying to run the sample application
### Repro steps

Please provide the steps required to reproduce the problem
1. Run the web application
### Expected behavior

<img width="611" alt="screen shot 2016-10-20 at 6 36 07 pm" src="https://cloud.githubusercontent.com/assets/15150044/19580436/341d6170-96f4-11e6-986b-579d1d59cb78.png">
### Actual behavior

I only greeted with this with error

<img width="289" alt="screen shot 2016-10-20 at 6 36 17 pm" src="https://cloud.githubusercontent.com/assets/15150044/19580424/2078a134-96f4-11e6-9235-39281b1bf5f6.png">

```
[Error] TypeError: _fableCore.Util.toPlainJsObj is not a function. (In '_fableCore.Util.toPlainJsObj(new AppProps(store))', '_fableCore.Util.toPlainJsObj' is undefined)
    (anonymous function) (client.js:688:90)
    execCb (require.js:1693)
    check (require.js:881)
    (anonymous function) (require.js:1136)
    (anonymous function) (require.js:134)
    (anonymous function) (require.js:1186)
    each (require.js:59)
    emit (require.js:1185)
    check (require.js:936)
    enable (require.js:1173)
    init (require.js:786)
    callGetModule (require.js:1200)
    completeLoad (require.js:1587)
    onScriptLoad (require.js:1714)

```

It chokes here

ReactDom.render(
    **_R.com<App,_,_> { Store=store } [],_**
    Browser.document.getElementsByClassName("todoapp").[0]
) |> ignore
### Known workarounds

N/A
### Related information
- Fable Version 6.15
- Mono Version 4.6.1
- Operating system macOS

**Comment by alfonsogarciacaro** [comment]
Strange, can you try with [this version](https://github.com/alfonsogarciacaro/fable-cufp-workshop/tree/master/todomvc-react)? It has a bit more instructions and it's also compatible with hot reloading.

**Comment by leolorenzoluis** [comment]
So I'm comparing it little by little, and it looks like "module": "amd" for the original example found on the site, and it's "commonjs" for your link. How does it affect fable depending on the module?

**Comment by alfonsogarciacaro** [comment]
`amd` modules are compatible with require.js and are used in the web samples. However in the next release we're deprecating it in favour of bundlers.

`commonjs` is Node's module system and it's not compatible directly with the browsers (that's why you get the error). You need first to bundle your code and the dependencies (React, fable-core) with a tool like Webpack in this case.

The Webpack dev server is just used for hot reloading. You can use any static server for this sample so it shouldn't be a problem to use with Suave.

The new 0.7 version will change some things and I need to adapt the samples a bit. This will happen next week probably 👍

**Comment by leolorenzoluis** [comment]
Makes sense. When you say 0.7 version, version of what?

Also, I was able to integrate it now with Suave and have webpack bundle it for me. I started trying to debug. However, it only works like the first debug call and then it dies.

I get this in the console

```http://localhost:8083/learn.json Failed to load resource: The network connection was lost.```

Is there some json that I am not aware that should be generated by a tool?

**Comment by alfonsogarciacaro** [comment]
`fable-compiler` and `fable-core` are coupled, so their major and minor versions are tied. Currently v0.7.x is in alpha both for `fable-compiler` and `fable-core` so we're focusing now on the documentation for this and tutorials for this that should be released next weed.

I don't think that error is causing problems with debugging. That's only React trying to load a tutorial but it doesn't concern your app. To avoid that, use a React production build or configure Webpack so it bundles React for production (with a Google search you can quickly find how to do that).

**Comment by alfonsogarciacaro** [comment]
The [Redux sample](https://github.com/fable-compiler/Fable/tree/master/samples/browser/redux-todomvc) has been updated (in the repo not yet in the website) to work with latest Fable. Please go to `samples` dir and run `npm install`, then go to `samples/browser/redux-todomvc` and first run `npm run build` and then `npm start`.
