### ISSUE TITLE
Postbuild-once w/ watch causes unhandled exception

### ISSUE THREAD

**Issue by MaxWilson** [fable-compiler/Fable#494]
### Description

Postbuild-once script and watch option, when used together, result in unhandled exception. Postbuild script does not have this issue, and neither does postbuild-once without watch. (Fable 0.6.15)

### Repro steps

1.) Clone gist from [https://gist.github.com/MaxWilson/836ff071f2d4fff860fc9a45cd8178b6](https://gist.github.com/MaxWilson/836ff071f2d4fff860fc9a45cd8178b6)

```
{
  "projFile": "Repro.fsx",
  "watch": true,
  "scripts": {
    "postbuild-once": "echo hello"
  }
}
```

2.) Run fable

### Expected behavior

Should watch for changes and echo "hello" every time.

### Actual behavior

Immediately crashes.

```
C:\code\836ff071f2d4fff860fc9a45cd8178b6>fable
fable-compiler 0.6.15: Start compilation...
Compiled Repro.fsx at 11:41:14 PM
echo hello
Watching C:\code\836ff071f2d4fff860fc9a45cd8178b6
Press Enter to terminate process.
**events.js:160
      throw er; // Unhandled 'error' event
      ^**

Error: spawn echo ENOENT
    at exports._errnoException (util.js:1007:11)
    at Process.ChildProcess._handle.onexit (internal/child_process.js:182:32)
    at onErrorNT (internal/child_process.js:348:16)
    at _combinedTickCallback (internal/process/next_tick.js:74:11)
    at process._tickCallback (internal/process/next_tick.js:98:9)

```
### Known workarounds

Don't use postbuild-once. Start your process (e.g. webpack-dev-server) from a separate command line.

### Related information 

* Fable Version 0.6.15
* .NET Runtime 4.6
* Operating system Windows 10

**Comment by alfonsogarciacaro** [comment]
`postbuild-once` has to run in parallel so I cannot use `cmd /C` in Windows. This unfortunately means you can only run executables (.exe) and not scripts (.bat, .cmd) or script commands (like `echo`) 😞 This is in the documentation: http://fable.io/docs/compiling.html#fableconfig-json

**Comment by MaxWilson** [comment]
Ah. I'll dig into the source code to understand the issue; it may be that we can at least improve the error message to explain what you need to do instead.

**Comment by MaxWilson** [comment]
I understand now why the error message can't be improved, but I did find a workaround that unblocks me: install webpack-dev-server locally and then spawn node directly

```
      "scripts": {
        "postbuild-once": "node node_modules/webpack-dev-server/bin/webpack-dev-server.js --colors --hot --config webpack.dev.config --content-base public/"
      },

```

Thanks for the help!
