### ISSUE TITLE
DateTime.TryParse fails at runtime

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#495]
I tried to use DateTime.TryParse and it compiles but fails at runtime.

**Comment by alfonsogarciacaro** [comment]
This is fixed in latest fable-core alpha :+1:

**Comment by forki** [comment]
Cool. Thanks

Am 22.10.2016 12:04 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:
