### ISSUE TITLE
Possible minor optimization for import expressions

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#497]
Consider this F# code:

```
let foo = importMember<string> "./foo.js"
```

It compiles to the following code:

```
import { foo as foo_1 } from "./foo.js";
export var foo = foo_1;
```

However, this [causes an extra indirection](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCU3RCUyQyUyMm1vZHVsZXMlMjIlM0ElNUIlN0IlMjJuYW1lJTIyJTNBJTIybWFpbi5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJpbXBvcnQlMjAlN0IlMjBmb28lMjBhcyUyMGZvb18xJTIwJTdEJTIwZnJvbSUyMCU1QyUyMi4lMkZmb28uanMlNUMlMjIlM0IlNUNuZXhwb3J0JTIwdmFyJTIwZm9vJTIwJTNEJTIwZm9vXzElM0IlNUNuY29uc29sZS5sb2coZm9vKSUzQiUyMiU3RCUyQyU3QiUyMm5hbWUlMjIlM0ElMjJmb28uanMlMjIlMkMlMjJjb2RlJTIyJTNBJTIyZXhwb3J0JTIwdmFyJTIwZm9vJTIwJTNEJTIwJTVDJTIyaGklNUMlMjIlM0IlMjIlN0QlNUQlN0Q=) which has an (extremely minor) performance cost.

Instead, it should compile to the following code:

```
import { foo } from "./foo.js";
export { foo };
```

[This removes the extra indirection](http://rollupjs.org/?version=0.36.3&shareable=JTdCJTIyb3B0aW9ucyUyMiUzQSU3QiUyMmZvcm1hdCUyMiUzQSUyMmVzJTIyJTJDJTIybW9kdWxlTmFtZSUyMiUzQSUyMm15QnVuZGxlJTIyJTJDJTIyZ2xvYmFscyUyMiUzQSU3QiU3RCUyQyUyMm1vZHVsZUlkJTIyJTNBJTIyJTIyJTdEJTJDJTIybW9kdWxlcyUyMiUzQSU1QiU3QiUyMm5hbWUlMjIlM0ElMjJtYWluLmpzJTIyJTJDJTIyY29kZSUyMiUzQSUyMmltcG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUyMGZyb20lMjAlNUMlMjIuJTJGZm9vLmpzJTVDJTIyJTNCJTVDbmV4cG9ydCUyMCU3QiUyMGZvbyUyMCU3RCUzQiU1Q25jb25zb2xlLmxvZyhmb28pJTNCJTIyJTdEJTJDJTdCJTIybmFtZSUyMiUzQSUyMmZvby5qcyUyMiUyQyUyMmNvZGUlMjIlM0ElMjJleHBvcnQlMjB2YXIlMjBmb28lMjAlM0QlMjAlNUMlMjJoaSU1QyUyMiUzQiUyMiU3RCU1RCU3RA==) because it exports the variable directly, rather than creating a new variable.

This also affects `importDefault` and `importAll`

---

However, there is one important caveat:
- With the old code output, if the file `foo.js` mutates the `foo` variable, the mutation will have no effect (F# will use the old value for `foo`)
- With the new code output, if the file `foo.js` mutates the `foo` variable, the mutation will have an effect (F# will use the new value for `foo`)

This is tricky.

On the one hand, we want the mutations to be visible, because that follows ES6 module semantics.

On the other hand, the variable in F# has not been marked as `mutable`, so it's very unusual for a non-`mutable` variable to change.

Because `importMember` is used for JS interop, I think it's better for mutations to be visible, because that matches ES6 module semantics, and there might be JS code which relies upon that.

This is an extremely minor issue, so there's no rush on it at all.

**Comment by alfonsogarciacaro** [comment]
Closing for now, will revisit later.
