### ISSUE TITLE
Abstract Methods with Defaults Incorrectly Named - Breaks "override".

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#505]
### Description

In a class containing an abstract method with a default implementation, the method is incorrectly named (with _0 appended). Overrides of this method in derived classes do not override the same name (no _0 appended).

Fable compiler and core: 0.7.5-alpha

### Repro steps

```fsharp
[<AbstractClass>]
type AbstractClassWithDefaults () =

    abstract MethodWithDefault : unit -> unit
    default x.MethodWithDefault () = () // named "MethodWithDefault_0"

    abstract MustImplement: unit -> unit

    member x.CallMethodWithDefault () =
        x.MethodWithDefault() // calls "MethodWithDefault_0"

type ConcreteClass () =
    inherit AbstractClassWithDefaults()

    override x.MustImplement () = ()
    override x.MethodWithDefault () = () // overrides "MethodWithDefault" (no "_0")
```

```javascript
  function AbstractClassWithDefaults() {
    _classCallCheck(this, AbstractClassWithDefaults);
  }

  AbstractClassWithDefaults.prototype.MethodWithDefault_0 = function MethodWithDefault_0() {};

  AbstractClassWithDefaults.prototype.CallMethodWithDefault = function CallMethodWithDefault() {
    this.MethodWithDefault_0();
  };
...
  ConcreteClass.prototype.MustImplement = function MustImplement() {};

  ConcreteClass.prototype.MethodWithDefault = function MethodWithDefault() {};
```

### Known workarounds

Use an intermediate class to provide defaults. Derive from intermediate class instead of abstract base class.

Possibly related/same as 
https://github.com/fable-compiler/Fable/issues/502 ?

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting this. It should be fixed in the next alpha that I'm planning to release in a few minutes :+1:

**Comment by michaelsg** [comment]
The previous problem seems to be fixed - abstract types with default methods.
I am now (with 0.7.5-alpha.15) getting an error for this:
```fsharp
type ISomeInterface =
    abstract OnlyGetProp: int with get
    abstract OnlyProp: int
    abstract Sender : int with get, set

type XISomeInterface () =
    interface ISomeInterface with
        member x.OnlyGetProp
            with get () = 0
        member x.OnlyProp = 3
        member x.Sender 
            with get () = 0
            and set i = ()
```
Only the one with `get` and `set` causes the error.
[Error] Interface overloads cannot be implemented: fable_abstract_defaults.ISomeInterface.Sender

**Comment by alfonsogarciacaro** [comment]
Ups, thanks for pointing that out. Fix coming as soon as CI server finishes building! ☝️
