### ISSUE TITLE
ts2fable - cannot read property 'kind" of undefined

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#508]
### Description

When parsing the [current file](https://raw.githubusercontent.com/DefinitelyTyped/DefinitelyTyped/36d40a63a05b5cb3413737fbdf7c9a2a26f211fd/pixi.js/pixi.js.d.ts) with ts2fable: it throws this error:

`ERROR: TypeError: Cannot read property 'kind' of undefined`

Stack trace leads to [l635](https://github.com/fable-compiler/Fable/blob/master/src/ts2fable/ts2fable.js#L635):

```
    if (secondParam && secondParam.type.kind == ts.SyntaxKind.StringLiteralType) {
```

Current Node is:

```
NodeObject {
  kind: 139,
  pos: 2935,
  end: 2946,
  flags: 0,
  parent:
   NodeObject {
     kind: 144,
     pos: 2898,
     end: 2948,
     flags: 16,
     parent:
      NodeObject {
        kind: 217,
        pos: 2576,
        end: 3247,
        flags: 2,
        parent: [Object],
        decorators: undefined,
        modifiers: [Object],
        name: [Object],
        typeParameters: undefined,
        heritageClauses: [Object],
        members: [Object] },
     decorators: undefined,
     modifiers: [ [Object], pos: 2898, flags: 16, end: 2918 ],
     asteriskToken: undefined,
     name:
      NodeObject {
        kind: 69,
        pos: 2918,
        end: 2929,
        flags: 0,
        parent: [Circular],
        text: 'createMesh' },
     questionToken: undefined,
     typeParameters: undefined,
     parameters: [ [Object], [Circular], pos: 2930, end: 2946 ],
     body: undefined },
  decorators: undefined,
  dotDotDotToken: undefined,
  name:
   NodeObject {
     kind: 69,
     pos: 2935,
     end: 2946,
     flags: 0,
     parent: [Circular],
     text: 'attachment' },
  questionToken: undefined,
  type: undefined,
  initializer: undefined }
```

`kind` should be the kind of secondParam.type. But `type` is currently undefined. 

[Line ](https://github.com/DefinitelyTyped/DefinitelyTyped/blob/master/pixi-spine/pixi-spine.d.ts#L80)that causes problem in the ts file is the following:

`private createMesh(slot, attachment)` which happens to have no typed parameters. 

Setting it to 

`private createMesh(slot: Slot, attachment: Attachment);`

makes it work.

I don't know if that should be considered as a ts problem or a fable one. 😉 
Thanks!

* Fable Version: Fable 0.6.15
* Operating system: windows 10
* ts version 2.0.6

**Comment by alfonsogarciacaro** [comment]
Thanks for reporting this in such detail. I love the `Cannot read property XX of undefined` JS error :wink: 

I've added a check in the offending line and another similar one (though I haven't tested it, sorry!) and republish the ts2fable package (0.1.22). Can you please give it a try?

As Typescript adds more and more features, it's getting more difficult to convert the declaration files. My idea at the moment is to deprecate the parser and build an F# type provider that interacts with the typescript server to read info about JS libs in real time. But let's see how it goes :)

**Comment by whitetigle** [comment]
ok I confirm it works. 
Parameters are now typed to obj.
