### ISSUE TITLE
fetchAs<T> not recognizing type

### ISSUE THREAD

**Issue by ian-moore** [fable-compiler/Fable#517]
### Description

When calling `fetchAs<T>` , I receive an error instead of the deserialized object of type `T`.

### Repro steps

Please provide the steps required to reproduce the problem

1. Compile the following fsx with Fable:
```
#r "../node_modules/fable-core/Fable.Core.dll"
#load "../node_modules/fable-import-fetch/Fable.Import.Fetch.fs"
#load "../node_modules/fable-import-fetch/Fable.Helpers.Fetch.fs"

open Fable.Core
open Fable.Import.Browser
open Fable.Import.Fetch
open Fable.Helpers.Fetch

type TimeResult =
  { time: string;
    milliseconds_since_epoch: int;
    date: string }

let initAsync () =
    async {
        let greeting = document.getElementById "greeting"
        greeting.innerHTML <- "Async hello from F# and Fable!"
        let! x = fetchAsync ("http://date.jsontest.com/", [])
        let! json = x.json () |> Async.AwaitPromise
        printfn "%A" json // print json for debugging
        let! response = fetchAs<TimeResult> ("http://date.jsontest.com/", []) // error occurs here
        printfn "%s" response.time
        return ()
    }

initAsync () |> Async.StartImmediate
```
2. Step B

Load the compiled js module and run in the browser.

### Expected behavior

I expect `response` to be an instance of my type `TimeResult` with properties matching the fetch'd JSON.

### Actual behavior

Encounter the following error in the browser console.

```
JSON is not of type TimeResult: {
   "time": "12:56:07 PM",
   "milliseconds_since_epoch": 1477745767303,
   "date": "10-29-2016"
}
```

### Known workarounds

Use `fetchAsync` and dynamic property operators.

### Related information 

* Fable Version
```
"dependencies": {
    "core-js": "^2.4.1",
    "fable-core": "^0.6.10",
    "fable-import-fetch": "^0.2.4",
    "requirejs": "^2.3.2"
  }
```
* .NET Runtime, CoreCLR or Mono Version
.NET 4.6
* Operating system
Windows

**Comment by alfonsogarciacaro** [comment]
The current Fable 0.6.x version expects the JSON to contain a `$type` field with the type name (see [this](http://fable.io/docs/interacting.html#JSON-serialization)), but this won't be necessary any more in 0.7.x. You can already test the alpha version: please check #474 and #516

**Comment by ian-moore** [comment]
Thanks for the quick response!! I upgraded fable-core and fable-compiler to the latest 0.7.x builds and it's working correctly, after I updated all of the bundling of course :)
