### ISSUE TITLE
0.7.0 Project references

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#518]
@alfonsogarciacaro Just a suggestion, as there seems to be some inconsistency in how the new multiple projects are handled. There is some code in fable.js that will act differently depending on the number of the projects (it will look elsewhere for fableconfig.json if it's a single project, for example).

Here is the suggestion: Instead of overloading the meaning of projFile, can you just add a projRefs parameter for the project references? You can still make it work the same way underneath, but it will be much simpler and clearer and not require moving fableconfigs and project files around?

I may be misreading your intent with that change, if so please ignore this.

**Comment by alfonsogarciacaro** [comment]
That could be an option but for Fable actually there're no _project references_. It just reads all the source files in the projects and the compiles them together, but you could pass a list of unrelated script files, for example (I'm planning to do that with the web samples).

> There is some code in fable.js that will act differently depending on the number of the projects (it will look elsewhere for fableconfig.json if it's a single project, for example).

This is because many times I don't pass a project file to Fable CLI but just the folder where fableconfig can be found. I think is the same behaviour from the very beginning. Have you find any other inconsistencies?

**Comment by ncave** [comment]
My point was the code makes different [decision](https://github.com/fable-compiler/Fable/blob/0.7.0/src/fable/Fable.Client.Node/js/fable.js#L384) where to read fableconfig settings from, based solely on the number of projects, which makes it a bit unintuitive.

Was the idea to allow for multi-level fableconfig.json that can override specific settings, or just to redirect to the inner fableconfigs? In the first case, you may or may not have a project-specific fableconfig.json in the same folder as the project, while in the second case it has to be there.

**Comment by alfonsogarciacaro** [comment]
Everything needs to be documented for 0.7 😉 

It's not planned that Fable will be able to read several fableconfig.json in one go. If you have several project files they must share the same settings.

These are the use cases I have in mind:

```shell
fable
#  Equivalent to `fable .`, try to look for fableconfig in current directory

fable src/
# Passed a directory, try to look for fableconfig.json there

fable src/fableconfig.json
# Passed the path to fableconfig, read options from there

fable src/MyProject.fsproj
# Passed a path to a project, check if fableconfig.json is there

fable foo/Foo.fsproj bar/Bar.fsproj
# Passed multiple projects, where to look for fableconfig? Working dir, last project dir?
# (At the moment Fable doesn't try to load fableconfig in this case)
```

Makes sense? I think the first two are the most common cases. I'm not sure if many users will try to pass multiple projects directly from the CLI but we could try to read fableconfig from the working dir. Although if you do have a fableconfig it's most convenient to list the projects there.

**Comment by ncave** [comment]
@alfonsogarciacaro Thank you for the clarification, this issue can be closed.
I have submitted a [patch](https://github.com/fable-compiler/Fable/pull/525) for the fable.js issue mentioned above.
