### ISSUE TITLE
Exception Message Testing Bug?

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#519]
I don't know where else this might be an issue. Right now it's just happening when I examine the Message property of an exn.

fsFormat %A will yield "\"PDQ\"" which does not match "PDQ"

```fsharp
    let xxx () =
        try
            failwith "PDQ"
            false
        with ex ->
            ex.Message = "PDQ"
```

```js
    var xxx = function xxx() {
        try {
            throw "PDQ";
            return false;
        } catch (ex) {
            return (0, _String.fsFormat)("%A", ex) === "PDQ";
        }
    };
```

**Comment by alfonsogarciacaro** [comment]
Yeah, this is not desirable but it's the best think I could think of as in JS any object can be thrown as an exception. I thought of using `String(err)` but if it's an error object (as many cases in node), you would just see `[Object object]` so I guess this is preferable. What do you think?

**Comment by alfonsogarciacaro** [comment]
Though it's true that in cases like yours you want to match the message exactly. Ok, I'll create a new `printException` method that first checks if the error is a string :+1:

**Comment by michaelsg** [comment]
It was actually only a unit test that was checking that the correct exception got thrown and caught that was doing the message testing.
But it sounds like what you suggested with printException is a good choice in general just in case real code uses the feature, being that throwing strings is common, albeit, not considered good form nowadays.

So it seems that "failwith" simple throws a string :-) Hmmm.
