### ISSUE TITLE
fable-core 0.7.5-alpha.10 imports (with ".js") break RequireJS bundling.

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#520]
Module references including ".js" extension seem to be the culprit.
Example from fable-core/umd/Util.js:
```js
// Alpha.9
(function (global, factory) {
    if (typeof define === "function" && define.amd) {
        define(["exports", "./Symbol"], factory);
// Alpha.10
(function (global, factory) {
    if (typeof define === "function" && define.amd) {
        define(["exports", "./Symbol.js"], factory);
```

**Comment by alfonsogarciacaro** [comment]
This is tricky, I've never liked the weird conditions Require.js imposes on the paths (like omitting the extension). I just read [here](https://github.com/systemjs/systemjs/blob/master/docs/config-api.md#defaultjsextensions) that the standard is actually to make the extension explicit (which makes more sense to me) so I decided to add the extension to prepare for the future (System.js is just a polyfill for an API that will be later implemented in browsers).

Require seems to be fading away now. Can you upgrade to System.js? See [here an example](https://github.com/fable-compiler/Fable/blob/3f02941b5f3110887ddc11e040ae7684a612b69a/samples/browser/react-todomvc/index.html#L21-L34).

**Comment by michaelsg** [comment]
That's not possible right now. I want to use SystemJS and tried until version 0.17. I never got bundling to work. Finally, I gave up and switched to RequireJS. It's old, but it's reliable. I intend, in the future, to try SystemJS, but not now. 

Can't you please just continue to support RequireJS until 1.0 when you can announce you are dropping support and people can prepare for it? Causing RequireJS bundling to not work is a BIG deal.

**Comment by alfonsogarciacaro** [comment]
You're right, node, other bundlers, loaders, etc... all work without the `.js` extension so I guess keeping compatibility with Require.js is not a big problem. The latest compiler and core versions omit the extension again :+1: Sorry for the inconvenience!

**Comment by xperiandri** [comment]
@michaelsg, maybe https://github.com/frankwallis/plugin-typescript this TypeScript implementation will help you?
I would like to use Fable with JSPM very much if someone will create a loader as I am a newbie to Fable and JS.
