### ISSUE TITLE
Migrating to 0.7

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#522]
Before writing a longer post about the new features, here's a quick check list of things to do to adapt your project to latest 0.7 alpha:

> Remember you can download latest fable-compiler and fable-core alpha versions with the next tag: `npm install fable-compiler@next fable-core@next`.
- **Project references**: If you have a multi-project solution, now you can compile all the projects in one go. To do that, don't use `--refs` and instead pass all project files as an array in `projFile`. _Attention_: projects must be in compilation order. More info #516 ([example](https://github.com/fable-compiler/Fable/blob/f41fe87d64561f1e1a3b01de176b770e5f9eedaa/src/tests/fableconfig.json#L2-L6))

> You probably weren't referencing dlls with 0.6, but if you did, check #516 to learn about how to build and reference Fable dlls in 0.7.
- **JSON Serialization**: It's not needed any more to add the `$type` field to serialized objects. The new serialization functions have the same name (`Fable.Core.JsInterop.toJson/ofJson`) so you may not need to do anything. If you're using Json.NET on the server side, you need to use [this converter](https://www.nuget.org/packages/Fable.JsonConverter/).

> If you still want the old behaviour, for example, when you don't kwnow the type at design time, use `ofJsonWithTypeInfo`.
- **Generic Resolution**: You can still inline functions to resolve generics at compile time, but if you need to do it in runtime (for example, when building a library to be used by other projects or when the function is too big to inline), now you can decorate the function with the `PassGenericsAttribute` to tell Fable it should pass generic info together with the parameters. More info #510.
- **Bundling**: Now Fable comes with [Rollup](http://rollupjs.org/) embedded to make bundling much easier. Furthermore, Rollup can use [ES2015 modules](http://www.2ality.com/2014/09/es6-modules-final.html) to perform good code removal and produce very small bundle sizes. Because of this, fable-core is now distributed with ES2015 modules by default. To activate bundling, use the `rollup` option in fableconfig, where you can pass specific options for Rollup. Check #516 and [Rollup JS API](https://github.com/rollup/rollup/wiki/JavaScript-API#rolluprollup-options-) for more info.

> The biggest drawback is Rollup cannot read commonjs exports (still the most common way for distributing JS code) as well as Webpack. So you many need to specify the [named exports of your external dependencies](https://github.com/rollup/rollup-plugin-commonjs#custom-named-exports).
> 
> This doesn't mean bundling your code is mandatory, you can still load dependencies at runtime. For that [replace `fable-core` with `fable-core/umd` in your loader config](https://github.com/fable-compiler/Fable/blob/f41fe87d64561f1e1a3b01de176b770e5f9eedaa/samples/browser/react-todomvc/index.html#L27) or, for node apps, pass the `--coreLib fable-core/umd` compiler option to Fable.

If you find something missing in this list ☝️ please write a comment and I'll edit it.

Examples:
- [React TodoMVC app with bundling](https://github.com/alfonsogarciacaro/fable-cufp-workshop/blob/next/todomvc-react/fableconfig.json)
- [React TodoMVC app without bundling](https://github.com/fable-compiler/Fable/tree/f41fe87d64561f1e1a3b01de176b770e5f9eedaa/samples/browser/react-todomvc)

**Comment by et1975** [comment]
Just [tried it](https://github.com/et1975/react-angular-ember-elm-performance-comparison/tree/v0.7/implementations/react-elmish) on elmish todomvc, and it's completely borked :D
- the app seems to completely reset the DOM on every state change
- the component names get erased when viewed through React dev tools plugin (your impl has the same issue)
Any suggestions how to troubleshoot?
cc @Pauan

**Comment by alfonsogarciacaro** [comment]
@et1975 Interesting, I need to check. It may be that React doesn't like that much indirections and we still need to find a way to inline calls to `React.createElement`.

**Comment by et1975** [comment]
I tried using previous/stable and new bindings, same behavior. Your TODO works though, so its probably something subtle, but i cant even begin to guess what.

**Comment by et1975** [comment]
Linked non-bundling example doesn't actually target v0.7! :)

**Comment by alfonsogarciacaro** [comment]
@et1975 Sorry, it's a bit confusing because the link is to a specific commit but it should be to 0.7.0 branch. In that branch I'm putting the dependencies in the `samples/browser` directory, to avoid having to download them for every sample. For the moment, I've converted the following samples: pacman, react-todomvc and vue-todomvc.

**Comment by OnurGumus** [comment]
When I try to compile Mario sample I am getting the following error:
C:\...\samples\browser\mario>fable
fable-compiler 0.7.8: Start compilation...
C:\Users\onur\Downloads\Fable-master\Fable-master\samples\browser\mario> npm install
[ERROR] Fable.Core 0.7.7 required, please upgrade the project reference
C:\...\samples\browser\mario>

What can I do ?

**Comment by alfonsogarciacaro** [comment]
Hi @OnurGumus! This is intended because most of the samples haven't been updated yet to 0.7 (as explained in the [migration guide](http://fable.io/blog/Introducing-0-7.html)). At the moment, only pacman, react-todomvc and vue-todomvc have been updated. The other ones will be updated over the next week :)

**Comment by OnurGumus** [comment]
@alfonsogarciacaro Hello I was able to solve it by updating the project config file. Also I needed to use System.js instead of require, so changed the code in index.html accordingly.
