### ISSUE TITLE
MS Build tools update or .NET Core based compilation

### ISSUE THREAD

**Issue by xperiandri** [fable-compiler/Fable#523]
What is the roadmap of evolving dependency on MS Build tools 2013?

I mean why 14.0 (2015) or 15.0 do not work?
And what are the thoughts about .NET Core usage?

**Comment by alfonsogarciacaro** [comment]
Latest alpha version has been freed from MSBuild chains 😄 #516 

There's already a netcore version: fable-compiler-netcore. But it needs a bit of work to be brought on par with 0.7 alpha. @ncave can give more details if needed. BTW, I need to give you publish rights for the netcore npm package, @ncave. Do you have an npm account?

**Comment by ncave** [comment]
@alfonsogarciacaro I don't have an npm account, but AFAIK the netcore version is operational enough to be released (not sure what additional work it needs, it's the same as the main Fable, and it's the only one I'm using).

**Comment by ncave** [comment]
[fable-compiler-netcore](https://www.npmjs.com/package/fable-compiler-netcore) v0.7.7 has been published to npm.

**Comment by alfonsogarciacaro** [comment]
Cool @ncave, thank you!
