### ISSUE TITLE
Ionide-vscode-fable plugin

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#524]
@7sharp9 has proposed to use [VS Code problem matcher](https://code.visualstudio.com/docs/editor/tasks#_processing-task-output-with-problem-matchers) to show Fable errors, and that would indeed very helpful to users.

Though it needs some work, 0.7 alpha already has a [JS API](https://github.com/fable-compiler/fable-react/blob/934de5b5ae3d79eb33a1822c7a92bc51b8c2644f/build.js#L8-L16). It should be possible to use it to integrate Fable better with VS Code. Would it make sense to do this in Ionide or would it be better to create a new plugin? And most importantly, are there good souls willing to help with this? :wink: @Krzysztof-Cieslak @cloudRoutine @MangelMaxime 

BTW, some messages probably need to be made more consistent, but they usually follow a pattern similar to the one below, so it shouldn't be difficult to extract location information from them.

```
[WARNING] This is a warning. (L3,4-L5,6) (/src/MyFile.fs)
[ERROR] This is an error. (L3,4-L5,6) (/src/MyFile.fs)
```

**Comment by Krzysztof-Cieslak** [comment]
Defining problem matcher is super simple - it's just regex expression.

**Comment by Krzysztof-Cieslak** [comment]
Unfortunately, it looks like extensions can't contribute problem matchers, they need to be defined on "user" level. Obviously we could just create command to generate right `tasks.json` but it doesn't sound as most elegant solution.

**Comment by cloudRoutine** [comment]
we could make an ionide-fable plugin

**Comment by 7sharp9** [comment]
Once fable can make the errors/warning consistent and line parsable then I just see it as a forge project to create the required bits.

**Comment by 7sharp9** [comment]
By constant and line readable I meant currently Error is shown on the line the actual error, and warning is surrounded by square brackets.

**Comment by MangelMaxime** [comment]
I have the same opinion than @cloudRoutine, it's probably time to make a Ionible-fable plugin.

**Comment by cloudRoutine** [comment]
Addressing #325 would be of great benefit to this endeavor 😉

**Comment by alfonsogarciacaro** [comment]
Great, thanks for your comments. I'll create an ionide-vscode-fable repo in fable-compiler org and we can start working there. I guess it's not problem in VSCode to show highlights from two different sources (FSAC and Fable) at the same time, right? If you prefer the repo to be in ionide org, can you please create one and give me access?

@cloudRoutine It'd be very nice indeed to have the comments. But I'm realising that parsing TS declarations adds an extra burden of maintenance for projects (you need to be sure the d.ts is correct and update, then parse it, fix the problems, make it idiomatic and then keep it in sync). So right now I'm thinking of deprecating it and focus on a type provider that communicates with the typescript server (same as intellisense works for JS in VS Code).

**Comment by cloudRoutine** [comment]
@alfonsogarciacaro would that be a generative type provider? Would that really address all of the issues?  Could you go into a bit more detail about how that'd work, the manner in which we get some kind of intellisense exploration of the api doesn't really matter to me, as long as we get it someway somehow 😁

**Comment by alfonsogarciacaro** [comment]
Sorry, that's only an idea for the moment, I need more to time to explore the possibility to answer those questions.

> Would that really address all of the issues?

Is there anything in OSS (or in life for what matters) that addresses _all_ of the issues :wink:

**Comment by alfonsogarciacaro** [comment]
Closing this for now as Enrico is currently working to integrate Fable with dotnet SDK which would automatically make Fable work with all dotnet sdk-compatible IDEs :)
