### ISSUE TITLE
Try fable-test sample with error info:  Could not load file or assembly 'Microsoft.Build.Framework...

### ISSUE THREAD

**Issue by ScottHuangZL** [fable-compiler/Fable#527]
### Description

I base on http://kcieslak.io/Getting-Started-with-Fable-and-Webpack to test the 1st fable-test sample
I am use latest VSCode to try build that sample
It failed to build with below Error info, please help on it.

Btw, I have install VS2015 community version with F#4.0 in advance, and able compiel normal F# project in VS2015

### Error Info as Below

npm install
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules\chokidar\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.14: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN fable-test@1.0.0 No description
npm WARN fable-test@1.0.0 No repository field.
fable-compiler 0.6.15: Start compilation...
**ERROR: IO Error trying read project options: Could not load file or assembly 'Microsoft.Build.Framework, Version=12.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.** 
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "build"
npm ERR! node v6.9.1
npm ERR! npm  v3.10.8
npm ERR! code ELIFECYCLE
npm ERR! fable-test@1.0.0 build: `fable`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the fable-test@1.0.0 build script 'fable'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the fable-test package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     fable
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs fable-test
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls fable-test
npm ERR! There is likely additional logging output above.
npm ERR! Please include the following file with any support request:
npm ERR!     c:\Users\scott_huang\fable-test\npm-debug.log

**Comment by alfonsogarciacaro** [comment]
Fable 0.6.x has a dependency on MSBuild (because of F# compiler services), you may try installing MSBuild tools 2013. The current alpha version 0.7.x, to be released soon, won't have the MSBuild dependency, so hopefully this problem shouldn't happen any more.

**Comment by ScottHuangZL** [comment]
Thank you , yeah, the 0.7.x version work well in my window 7.  Thanks for your quickly solution.

**Comment by ScottHuangZL** [comment]
Thank you , yeah, the 0.7.x version work well in my window 7.  Thanks for your quickly solution.
