### ISSUE TITLE
fable-compiler@0.7.5-alpha.22 -w doesn't terminate mono on exit

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#530]
### Description

On OSX the Mono process remains after hitting <enter> and leaving the watch.

### Repro steps

1. Run fable -w

2. Once it's done, hit enter

### Expected behavior

Mono process should terminate.

### Actual behavior

mono-sgen32 remains running and consumes a lot of CPU.

### Known workarounds

Kill it manually.

### Related information 

* Mono Version
4.6.0

**Comment by alfonsogarciacaro** [comment]
I just tried and in my case the mono process was finished properly (I'm also on OSX and I have Mono 4.6.1). Could you please try again and make sure the mono process hasn't been spawned by anything else? (You can check the PIDs, usually the Fable node and mono processes have very similar PIDs.) Also, please check whether the issue happens every time for you and whether there's something in your fableconfig.json than can affect the issue (e.g. a posbuild or postbuild-once script).

**Comment by et1975** [comment]
I looked at the files opened by the process and I had nothing else running, but I can't reproduce it either.
