### ISSUE TITLE
Improve fable watcher

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#531]
### Description

Actually Fable is only watching from the `fableconfig.json` location.

It would be great if Fable could be able to determine the project's location listed in the `fableconfig.json` and set the watcher for all them even if they are in different level of the file system.

**Comment by alfonsogarciacaro** [comment]
Latest alpha (0.7.5-alpha.23) should watch the fableconfig dir **plus** the dirs of all project files. Could you please give it a try and confirm if it works? Cheers!

**Comment by MangelMaxime** [comment]
I just made some test and for me it's good :)

Thanks for you work.
