### ISSUE TITLE
PrintfFormat.Value doens't return a string

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#536]
### Description

`PrintfFormat.Value` doens't return a string i.e. what the compiler expects

### Repro steps

```f#
let pathScanTest (pf:PrintfFormat<_,_,_,_,'t>) s =
    let formatStr  = pf.Value
    printfn "pf.Value = %s" formatStr

pathScanTest "foo %s" "foo bar"
```

### Expected behavior

```
pf.Value = 'foo %s'
```

### Actual behavior

```
pf.Value = 'function (cont) {
            _cont = cont;
            return fsFormatRegExp.test(str) ? makeFn(str) : _cont(str);
        }'
```

### Related information 

* Fable Version: 0.7.5-alpha.22
* .NET Runtime
* Windows

**Comment by davidtme** [comment]
@alfonsogarciacaro did anything ever happen with this, I was hoping to use it to create a suave.io style pathScan for elmish

**Comment by alfonsogarciacaro** [comment]
Ups, it seems this issue got buried by others and forgot about it, sorry! 😅 I need to check it... unless you want to give it a try, of course :wink:

**Comment by davidtme** [comment]
I'm not even sure what PrintfFormat does or how it works really just hoping I can copy and paste my way to victory.

**Comment by alfonsogarciacaro** [comment]
Me neither ;) Anyway I'll have a look. Ping me here again next week if I happen to forget!

**Comment by alfonsogarciacaro** [comment]
Anyone from @fable-compiler/code-maintenance interested in having a look? 😉

**Comment by MangelMaxime** [comment]
Should be close ?

**Comment by alfonsogarciacaro** [comment]
It'd be nice if @davidtme can confirm whether it's working for him. But the test and fix added by @Zaid-Ajaj are working so I guess we can close this.
