### ISSUE TITLE
Watch does not recombine files when using fsproj

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#541]
### Description

Compiling with fable works but with the `watch` flag, it only response to changes to the `fsproj` file and not when the individual files change.

### Repro steps

Please provide the steps required to reproduce the problem

1. Start fable with watch `node ./node_modules/fable-compiler/index.js --verbose --watch`.

2. Make a change to for example `Program.fs` and save.

3. Optionally, make a change to the project file and save

### Expected behavior

The project is rebuilt.

### Actual behavior

Nothing happens. 

### Known workarounds

Manually recompile after a change

### Related information 

* Fable Version: 0.7.5-alpha.30
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Sorry, I added customization of watch directories (so you can pass a string or a string array to `--watch`) but apparently I broke the default directory calculation. Can you please try again with latest alpha? Thanks!

**Comment by rkosafo** [comment]
Just updated and it is working now. Thanks.
