### ISSUE TITLE
Error when bundling when changes are saved one after the other

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#544]
### Description

When fable compiler is in watch mode, it crashes during bundling when errors are corrected.

My `fableconfig.json` file

	{ 
	  "projFile": "clearhud-frontend.fsproj",
	  "sourceMaps": false,
	  "babelPlugins": [
		"transform-runtime"
	  ],
	  "outDir": "out",
	  "targets": {
		"debug": { "watch": true }
	  },
	  "rollup": {
		"entry": "./out/Program.js",
		"external": [ "jquery" ],
		"globals": {
		  "jquery": "jQuery"
		},
		"plugins":[
		  ["replace", {"process.env.NODE_ENV": "'production'"}],
		  ["commonjs", {
			"namedExports": {
			  "react": ["Component", "createElement"],
			  "react-dom": ["render"]
			}
		  }]
		]
	  }
	}

Exact log from command line

	E:\Work\Clearbyte\ClearHud\clearhud-frontend>npm run fwatch

	> clearhud-frontend@1.0.0 fwatch E:\Work\Clearbyte\ClearHud\clearhud-frontend
	> node ./node_modules/fable-compiler/index.js -d

	fable-compiler 0.7.5-alpha.34: Start compilation...
	Compiled Essentials.js at 7:55:38 AM
	Compiled Utilities.js at 7:55:38 AM
	Compiled MessageBus.js at 7:55:38 AM
	Compiled Model.js at 7:55:38 AM
	Compiled SUI.js at 7:55:39 AM
	Compiled Form.js at 7:55:42 AM
	Compiled Http.js at 7:55:42 AM
	Compiled Ports.js at 7:55:42 AM
	Compiled Api.js at 7:55:43 AM
	Compiled Server.js at 7:55:43 AM
	Compiled Store.js at 7:55:43 AM
	Compiled Assets.js at 7:55:43 AM
	Compiled FirmPanel.js at 7:55:43 AM
	Compiled LoginPanel.js at 7:55:44 AM
	Compiled UserProfilePanel.js at 7:55:44 AM
	Compiled HelpPanel.js at 7:55:44 AM
	Compiled ChangePasswordPanel.js at 7:55:45 AM
	Compiled UserInfoPanel.js at 7:55:45 AM
	Compiled TopPanel.js at 7:55:46 AM
	Compiled AppWindow.js at 7:55:46 AM
	Compiled ContentPanelPanel.js at 7:55:47 AM
	Compiled AppPanel.js at 7:55:47 AM
	Compiled LoadingPanel.js at 7:55:47 AM
	Compiled InstancePanel.js at 7:55:47 AM
	Compiled Program.js at 7:55:47 AM
	Bundling...
	Bundled bundle.js at 7:56:02 AM
	Watching E:\Work\Clearbyte\ClearHud\clearhud-frontend
	Press Enter to terminate process.
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Common\Model.fs at 7:57:41 AM
	[ERROR] F# project contains errors:
	The value or constructor 'appWindowPropsWithDefaults' is not defined (L30,24-L30,50) (Ports.fs)
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\App\Ports.fs at 8:00:50 AM
	Compiled Ports.js at 8:00:54 AM
	Bundling...
	[BUNDLE ERROR] 'appWindowPropsWithDefaultss' is not exported by E:/Work/Clearbyte/ClearHud/clearhud-frontend/out/Common/Model.js (imported by E:/Work/Clearbyte/ClearHud/clearhud-frontend/out/App/Ports.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
	Error: 'appWindowPropsWithDefaultss' is not exported by E:/Work/Clearbyte/ClearHud/clearhud-frontend/out/Common/Model.js (imported by E:/Work/Clearbyte/ClearHud/clearhud-frontend/out/App/Ports.js). For help fixing this error see https://github.com/rollup/rollup/wiki/Troubleshooting#name-is-not-exported-by-module
		at Module.trace (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:7739:29)
		at ModuleScope.findDeclaration (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:7361:22)
		at Scope.findDeclaration (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5361:39)
		at Scope.findDeclaration (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5361:39)
		at Scope.findDeclaration (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5361:39)
		at Scope.findDeclaration (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5361:39)
		at Node.bind (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5846:28)
		at E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5155:50
		at Node.eachChild (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5172:5)
		at Node.bind (E:\Work\Clearbyte\ClearHud\clearhud-frontend\node_modules\rollup\dist\rollup.js:5155:7)

### Repro steps

1. Create a new project with two files (FileA.fs and FileB)

2. Add a function(doX) to FileA and call it from file B

3. Start fable with watch and bundling enabled

4. Rename function doX in FileA to doXx and save

5. Go to FileB, fix the error resulting from the renaming before and save.

### Expected behavior

App compiles and bundle.js is generated

### Actual behavior

Process fails with bundle error.

### Known workarounds

Start the complier again when it exists

### Related information 

* Fable Version: 0.7.5-alpha.34
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Interesting, thanks for the detailed report. So this only happens when the changes are very close in time? (Within 5 seconds for example) Maybe we need to make the lapse between changes longer to prevent this.

**Comment by rkosafo** [comment]
Not really sure. In my case, I'm wondering if `Model.fs` was actually compiled. `Ports.fs` has `Compiled Ports.js at 8:00:54 AM` but nothing for `Model.fs`.

**Comment by alfonsogarciacaro** [comment]
Ok, thanks for the info. I'll try to reproduce on my side :+1:

**Comment by alfonsogarciacaro** [comment]
Can you please try with latest version? I should investigate more what this exact error is happening but for now I'm just forcing a rebuild when there're bundling errors and this seems to fix the problem :)

**Comment by rkosafo** [comment]
Just tested and it does rebuild when there is an error. Solves the problem of having to restart whenever the application crashes.  It is working fine now. There is a suspicious `Bundled bundle.js at 7:34:18 PM` in the logs though :)

        ...
	Compiled Components\CommonUi.js at 7:34:12 PM
	Bundling...
	Compiled Components\Cases\CaseFinderPanel.js at 7:34:15 PM
	Bundling...
	[BUNDLE ERROR] Maximum call stack size exceeded
	Triggering full rebuild...
	Compiled Imports\ReactExtras.js at 7:34:15 PM
	Compiled Imports\Feathers.js at 7:34:15 PM
	Compiled Imports\AccountingJs.js at 7:34:15 PM
	Compiled Common\Essentials.js at 7:34:15 PM
	Compiled Common\Utilities.js at 7:34:15 PM
	Compiled Common\MessageBus.js at 7:34:15 PM
	Compiled Common\Model.js at 7:34:15 PM
	Bundled bundle.js at 7:34:18 PM
	Compiled Common\SUI.js at 7:34:19 PM
	Compiled Common\Form.js at 7:34:20 PM
	Compiled Common\Http.js at 7:34:21 PM
	...
	Compiled Program.js at 7:34:31 PM
	Bundling...
	Bundled bundle.js at 7:34:35 PM

**Comment by alfonsogarciacaro** [comment]
That's just indicating the generated bundle (if you set `rollup.dest` explicitly it'll be a different name), but probably it should indicate also the output path.

Thanks for the confirmation it's working!
