### ISSUE TITLE
Type.FullName showing as unknown

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#560]
### Description

`Type.FullName` outputs `'unknown` for the code below. I think it used to work before. Is there something wrong with the code below? If not, are there any workarounds?

### Repro steps

Please provide the steps required to reproduce the problem

    namespace Tests

    open Fable.Core

    module Module1 =  
      let [<PassGenerics>] getName<'t> () =
        typedefof<'t>.FullName  
      let [<PassGenerics>] getName2 (d:'t) =
        typeof<'t>.FullName
      let getName3 (t:System.Type) =
        t.FullName

    module Module2 =
      open Module1
      type Firm = { name: string } with
        static member empty = { name = "" }
      let test =
        printfn "%s, %s, %s" (getName<Firm>()) (getName2 Firm.empty) (getName3 typedefof<Firm>)
        true

### Expected Behavior

Expected the full name of the type to be down three times.

### Actual Behavior

The output is `unknown, unknown, unknown`. 

### Known workarounds

Not sure.

### Related information 

* Fable Version: 0.7.8
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! I changed how the reflection works and I had to rewrite the `getTypeName` function. Apparently `Object.getPrototypeOf(x)` is not always the same as `x.prototype`... javascript /shrug. I thought I had tests for this, but seems it was not the case. Should be fixed by upgrading fable-core to 0.7.9 :)

**Comment by rkosafo** [comment]
Thanks. Just upgraded and it is working a expected.
