### ISSUE TITLE
Cannot reference Fable.Core.dll with VS2015 Community

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#562]
When trying to reference Fable.Core.dll I got this error;

![capture](https://cloud.githubusercontent.com/assets/4760796/20626066/67021d94-b317-11e6-9e5c-bec22dbbdb2b.PNG)

Even, if we try using *Project Reference* we don't access to `Fable` namespace.

**Comment by rkosafo** [comment]
Is there a possibility that the file is correct?
If you create a new project and install the npm packages, do you get the same error?

**Comment by MangelMaxime** [comment]
This is a new project :)

Actually, @alfonsogarciacaro mentions that he got the same error with VS17 under OSX.

**Comment by alfonsogarciacaro** [comment]
Not exactly the same, I get this the following VS for Mac, but I can actually use the assembly without problems: I have intellisense, etc. Using Mono.

<img width="492" alt="screen shot 2016-11-25 at 15 55 51" src="https://cloud.githubusercontent.com/assets/8275461/20628681/be93b4d6-b327-11e6-85d3-3e374193c595.png">

**Comment by MangelMaxime** [comment]
Ah ok...
But perhaps they are related.

**Comment by rkosafo** [comment]
Ok. I opened it in VS2017 without any issue but that is on windows. The F# experience is terrible compared to VS2015 but that is a different story. If the issue still persists, perhaps you can upload the solution somewhere and I can confirm if the same issue exists on windows.

**Comment by alfonsogarciacaro** [comment]
I'm on Windows now. I downloaded fable-core 0.7.9, created a new F# project with VS 2015 Community, added a reference to Fable.Core.dll and didn't have any problem (I could access types in the namespace normally), so I'm not sure what could be going wrong in your case :/

**Comment by MangelMaxime** [comment]
Ok...
Perhaps I have a problem with my computer setup...
I will try on Monday to reinstall all my dev env.

Thanks for the help

**Comment by alfonsogarciacaro** [comment]
@MangelMaxime Could you please confirm if you're still having the issue? I've found that sometimes there're problems in Windows with references if .NET 4.5 SDK (Windows 8) is not installed.

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro Sorry, I forget to comment again.
No I don't have anymore this issue you can close it I think.

**Comment by MangelMaxime** [comment]
I got this error again and was able to sovle it.

Step to fix:
1. In VisualStudio, force the solution/project to be cleaned.
2. Try to add the DLL. It's should be ok

If ever this is not OK after the clean up, make sure to have an `ouput` configure for the project.

**Comment by alfonsogarciacaro** [comment]
Interesting, thanks a lot for sharing the solution. Hopefully it will help users with the same problem :+1:
