### ISSUE TITLE
Bundling issue resulting in error "JavaScript heap out of memory"

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#565]
### Description

I'm having a strange issue with bundling when `fable` compiler is in watch mode. The observations are as follows

1. After the initial compilation, subsequence changes cause bundling to be done twice. The first one from the `fs` file that changed and the second from the `bundle.js` file.
2. After something time and changes (I'm yet to identify when exactly), bundling just keeps repeating and it appears in response to the change in `bundle.js`

### Repro steps

1. Create `fable` in watch mode
2. Continue editing. Bundling is triggered twice
3. Continue editing and saving. At some point, bundling will loop and the process will crash

### Expected behavior

Normal compilation of changed files with bundling being triggered once when the updated files are compiled.

### Actual behavior

Below is the entire log from the command line. Hope it is useful

	E:\Work\Clearbyte\ClearHud\clearhud-frontend>npm run fwatch

	> clearhud-frontend@1.0.0 fwatch E:\Work\Clearbyte\ClearHud\clearhud-frontend
	> node ./node_modules/fable-compiler/index.js -d

	fable-compiler 0.7.9: Start compilation...
	Compiled Imports\ReactExtras.js at 3:46:09 PM
	Compiled Imports\Feathers.js at 3:46:09 PM
	Compiled Imports\AccountingJs.js at 3:46:09 PM
	Compiled Common\Essentials.js at 3:46:09 PM
	Compiled Common\Utilities.js at 3:46:09 PM
	Compiled Common\MessageBus.js at 3:46:10 PM
	Compiled Common\Model.js at 3:46:10 PM
	Compiled Common\SUI.js at 3:46:10 PM
	Compiled Common\Form.js at 3:46:11 PM
	Compiled Common\Http.js at 3:46:11 PM
	Compiled App\Ports.js at 3:46:11 PM
	Compiled App\Api.js at 3:46:11 PM
	Compiled App\Server.js at 3:46:12 PM
	Compiled App\Store.js at 3:46:12 PM
	Compiled App\Assets.js at 3:46:12 PM
	Compiled App\Config.js at 3:46:12 PM
	Compiled Components\CommonUi.js at 3:46:12 PM
	Compiled Components\CrudPanel.js at 3:46:12 PM
	Compiled Components\FirmPanel.js at 3:46:13 PM
	Compiled Components\LoginPanel.js at 3:46:13 PM
	Compiled Components\UserProfilePanel.js at 3:46:13 PM
	Compiled Components\HelpPanel.js at 3:46:13 PM
	Compiled Components\ChangePasswordPanel.js at 3:46:13 PM
	Compiled Components\UserInfoPanel.js at 3:46:13 PM
	Compiled Components\LookupPanel.js at 3:46:14 PM
	Compiled Components\CaseContacts\CaseContactsPanel.js at 3:46:15 PM
	Compiled Components\Cases\PurchasePanel.js at 3:46:15 PM
	Compiled Components\Cases\RefinancePanel.js at 3:46:16 PM
	Compiled Components\Cases\CaseFinderPanel.js at 3:46:16 PM
	Compiled Components\Cases\CaseDashboardPanel.js at 3:46:16 PM
	Compiled Components\TopPanel.js at 3:46:16 PM
	Compiled Components\AppWindow.js at 3:46:16 PM
	Compiled Components\ContentPanelPanel.js at 3:46:16 PM
	Compiled Components\AppPanel.js at 3:46:16 PM
	Compiled Components\LoadingPanel.js at 3:46:16 PM
	Compiled Components\InstancePanel.js at 3:46:16 PM
	Compiled ErrorTest.js at 3:46:16 PM
	Compiled Program.js at 3:46:16 PM
	Bundling...
	Bundled bundle.js at 3:46:26 PM
	Watching E:\Work\Clearbyte\ClearHud\clearhud-frontend
	Press Enter to terminate process.
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Imports\ReactExtras.fs at 3:54:30 PM
	Compiled Imports\ReactExtras.js at 3:54:35 PM
	Bundling...
	Bundled bundle.js at 3:54:38 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 3:54:38 PM
	Bundling...
	Bundled bundle.js at 3:54:40 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Components\Cases\RefinancePanel.fs at 4:42:22 PM
	Compiled Components\Cases\RefinancePanel.js at 4:42:23 PM
	Bundling...
	Bundled bundle.js at 4:42:26 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 4:42:26 PM
	Bundling...
	Bundled bundle.js at 4:42:29 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Imports\ReactExtras.fs at 4:43:25 PM
	Compiled Imports\ReactExtras.js at 4:43:30 PM
	Bundling...
	Bundled bundle.js at 4:43:33 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 4:43:33 PM
	Bundling...
	Bundled bundle.js at 4:43:36 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Components\Cases\RefinancePanel.fs at 4:43:57 PM
	Compiled Components\Cases\RefinancePanel.js at 4:43:59 PM
	Bundling...
	Bundled bundle.js at 4:44:02 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 4:44:02 PM
	Bundling...
	Bundled bundle.js at 4:44:04 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Imports\ReactExtras.fs at 5:03:23 PM
	Compiled Imports\ReactExtras.js at 5:03:30 PM
	Bundling...
	Bundled bundle.js at 5:03:34 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:03:34 PM
	Bundling...
	Bundled bundle.js at 5:03:37 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:03:37 PM
	Bundling...
	Bundled bundle.js at 5:03:40 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\Imports\ReactExtras.fs at 5:08:36 PM
	Compiled Imports\ReactExtras.js at 5:08:42 PM
	Bundling...
	Bundled bundle.js at 5:08:45 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:08:45 PM
	Bundling...
	Bundled bundle.js at 5:08:49 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:08:49 PM
	Bundling...
	Bundled bundle.js at 5:08:52 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:08:52 PM
	Bundling...
	Bundled bundle.js at 5:08:56 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:08:56 PM
	Bundling...
	Bundled bundle.js at 5:09:00 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:09:00 PM
	Bundling...
	Bundled bundle.js at 5:09:04 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:09:04 PM
	Bundling...
	Bundled bundle.js at 5:09:36 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:09:36 PM
	Bundling...
	Bundled bundle.js at 5:10:25 PM
	change: E:\Work\Clearbyte\ClearHud\clearhud-frontend\out\bundle.js at 5:10:25 PM
	Bundling...

	<--- Last few GCs --->

	[14380:0000024795391180]  5126004 ms: Mark-sweep 1409.5 (1594.3) -> 1409.4 (1595.3) MB, 1228.5 / 0.0 ms  allocation failure GC in old space requested
	[14380:0000024795391180]  5127256 ms: Mark-sweep 1409.4 (1595.3) -> 1409.4 (1562.3) MB, 1251.5 / 0.0 ms  last resort gc
	[14380:0000024795391180]  5128675 ms: Mark-sweep 1409.4 (1562.3) -> 1409.3 (1562.3) MB, 1417.6 / 0.0 ms  last resort gc

	<--- JS stacktrace --->

	==== JS stack trace =========================================

	Security context: 0000033D9FDC0D51 <JS Object>
		1: DoJoin(aka DoJoin) [native array.js:~97] [pc=00000095E690FE9C](this=0000033D9FD04311 <undefined>,q=000003C8142F8799 <JS Array[342]>,r=342,F=0000033D9FD043B1 <true>,B=0000033D9FD04471 <String[0]: >,A=0000033D9FD04421 <false>)
		2: Join(aka Join) [native array.js:~122] [pc=00000095E69EBB36](this=0000033D9FD04311 <undefined>,q=000003C8142F8799 <JS Array[342]>,r=342,B=0000033D9FD04471 <S...

	FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory

	npm ERR! Windows_NT 10.0.14393
	npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "fwatch"
	npm ERR! node v7.0.0
	npm ERR! npm  v3.10.8
	npm ERR! code ELIFECYCLE
	npm ERR! clearhud-frontend@1.0.0 fwatch: `node ./node_modules/fable-compiler/index.js -d`
	npm ERR! Exit status 3
	npm ERR!
	npm ERR! Failed at the clearhud-frontend@1.0.0 fwatch script 'node ./node_modules/fable-compiler/index.js -d'.
	npm ERR! Make sure you have the latest version of node.js and npm installed.
	npm ERR! If you do, this is most likely a problem with the clearhud-frontend package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node ./node_modules/fable-compiler/index.js -d
	npm ERR! You can get information on how to open an issue for this project with:
	npm ERR!     npm bugs clearhud-frontend
	npm ERR! Or if that isn't available, you can get their info via:
	npm ERR!     npm owner ls clearhud-frontend
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     E:\Work\Clearbyte\ClearHud\clearhud-frontend\npm-debug.log

### Known workarounds

As this happens periodically, just keep the command window visible so that you can restart the process when it crashes.

### Related information 

* Fable Version 0.7.9
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by davidtme** [comment]
I've also had this problem so it's not just isolated to @rkosafo

**Comment by alfonsogarciacaro** [comment]
Damn, this comes from when I was trying to add to the watcher imported JS files... I didn't revert the change completely :/ Now the watcher should only react to changes in F# files, could you please download fable-compiler 0.7.10 and check if it's fixed? Cheers!

**Comment by rkosafo** [comment]
Watch is no longer watching bundle.js. Thanks.
