### ISSUE TITLE
Watch mode picking up none fs file changes

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#566]
### Description
While using VS2015 with a project under git control this is really noticeable and leads to #565 

```
Bundling...
Bundled app.js at 7:17:05 PM
add: C:\Dev\game2\src\Client2\.git\objects\93\d284a411164c364c3766a0c14c815930d41dda at 7:17:09 PM
```

### Related information 

* Fable Version 7.9.0
* .NET Runtime
* Windows 10

**Comment by MangelMaxime** [comment]
@alfonsogarciacaro This issue failed to be closed by your commit.

**Comment by alfonsogarciacaro** [comment]
Thanks @MangelMaxime! I need to go through the issues and close the old ones :)
