### ISSUE TITLE
Fable+Webpack error: Unexpected token import

### ISSUE THREAD

**Issue by Biarity** [fable-compiler/Fable#570]
### Description

Using Fable with `--module es2015` & webpack causes the error `Uncaught SyntaxError: Unexpected token import` in the js console.

### Repro steps

`npm install fable-compiler -g`,
`npm init`,
`npm install webpack --save-dev`,
create `example.fsx` file with some Fable,
`fable example.fsx --module es2015`,
setup `webpack.config.js`,
`webpack --config webpack.config.js`,
reference webpack's `bundle.js` in an html file,
get error when opening html file.

**Comment by alfonsogarciacaro** [comment]
Hi there! Webpack doesn't support ES2015 modules, so when using webpack you need to use `--module commonjs`. Webpack 2 will support ES2015 modules but it's still in alpha status and it's been reported it doesn't work well yet with Fable.

If you want to take advantage of ES2015 modules and tree shaking when bundling, it's recommend you use the embedded Rollup: http://fable.io/blog/Introducing-0-7.html#ES2015-Modules-and-Bundling

**Comment by Biarity** [comment]
Hello, now using commonjs, and webpack gives this error:
```
bundle.js  30.8 kB       0  [emitted]  main
   [0] ./example.js 6.29 kB {0} [built] [1 error]
   [1] ./fable_external/Fable.Helpers.Virtualdom-414460528.js 22 kB {0} [built] [2 errors]

ERROR in ./example.js
Module not found: Error: Cannot resolve module 'fable-core' in C:\...
 @ ./example.js 9:17-38

ERROR in ./fable_external/Fable.Helpers.Virtualdom-414460528.js
Module not found: Error: Cannot resolve module 'fable-core' in C:\...\fable_external
 @ ./fable_external/Fable.Helpers.Virtualdom-414460528.js 12:17-38

ERROR in ./fable_external/Fable.Helpers.Virtualdom-414460528.js
Module not found: Error: Cannot resolve module 'virtual-dom' in C:\...\fable_external
 @ ./fable_external/Fable.Helpers.Virtualdom-414460528.js 14:18-40
```
Didn't know there was a blog btw!

**Comment by alfonsogarciacaro** [comment]
Are you using latest fable-compiler (0.7.16) and fable-core (0.7.11)?

**Comment by Biarity** [comment]
Yes, using `fable-compiler` 0.7.16 & `fable-core` 0.7.12. Still the same error!

**Comment by alfonsogarciacaro** [comment]
Sorry, I'd need a project sample to reproduce this. Would it be possible for you to create a repo?

**Comment by rkosafo** [comment]
@Biarity I'm using `fable` with `webpack`. I did get some errors with `es2015`. I'm currently using `rollup` to get the `bundle.js` and `webpack` uses this file. I tried using `rollup` for everything but had challenges with aliases and stuff. The current setup with `webpack` does work well.

**Comment by Biarity** [comment]
Resolved by using latest versions, webpack, and commonjs without `fable-import-*`.
