### ISSUE TITLE
ClassAttribute support for records question

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#573]
```
[<Class>]
type Test1 = 
    val Pos : int
    new (pos) = { Pos=pos }

type Test2(pos) = 
    member x.Pos = pos

[<EntryPoint>]
let main argv =
    let t1 = Test1(1)
    let t2 = Test2(2)
    printfn "pos1 = %A" t1.Pos
    printfn "pos2 = %A" t2.Pos
    0
```
output is:
```
pos1 = undefined // there is no Test1.Pos, maybe because [<Class>] is not supported on records yet?
pos2 = 2
```

**Comment by alfonsogarciacaro** [comment]
It's the first time I see this type declaration ;) What is used for?

**Comment by alfonsogarciacaro** [comment]
Ok, thanks. I'll try to have a look when I have time, though this is probably not high priority as I haven't seen any sample of this pattern.

**Comment by ncave** [comment]
Here is a [link](https://docs.microsoft.com/en-us/dotnet/articles/fsharp/language-reference/members/explicit-fields-the-val-keyword) to the syntax.

**Comment by alfonsogarciacaro** [comment]
@ncave Sorry, I don't remember if we did something with this at the end 😅 Is this still an issue?

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, still there.

**Comment by alfonsogarciacaro** [comment]
This seems to be working with latest Fable :+1: Please reopen if you still have issues.
