### ISSUE TITLE
I get a blank body when accessing Fable.io with FF on Linux

### ISSUE THREAD

**Issue by gentauro** [fable-compiler/Fable#574]
### Description

The body is completely blank but I can see the header.

### Repro steps

Just trying to read anything from **samples, docs or blog**. **Fable** and **home** sections work.

### Expected behavior

I guess see some rendered HTML

### Actual behavior

Blank body

### Known workarounds

Use Chromium?

### Related information 

The only message I get in Firefox Debug console is:

        Use of getPreventDefault() is deprecated.  Use defaultPrevented instead.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! This is very strange, now I need a Linux machine with Firefox to debug the problem ;)

**Comment by ncave** [comment]
@gentauro If you use an adblocker, perhaps something on the page is triggering it? Or it could be something else.

**Comment by alfonsogarciacaro** [comment]
There was a code for websockets used during development that was causing problems, but I disabled that some time ago.

**Comment by gentauro** [comment]
@ncave, I disabled ABP for http://fable.io/ and I can now see the body of the blog post ...

I guess there must be something in Fable that triggers ABP?

**Comment by alfonsogarciacaro** [comment]
The tooltips? ;)

**Comment by gentauro** [comment]
I don't know :)

Btw, don't you use ABP yourself? I haven't done anything to the ad-blocker, I just installed it ...

**Comment by rasch** [comment]
Same with [ABP](https://chrome.google.com/webstore/detail/adblock-plus/cfhdojbkjhnklbpkdaibdccddilifddb) in Chrome on Windows. Strangely, ABP does not show anything being blocked. I raised an issue with ABP for Chrome.

**Comment by voronoipotato** [comment]
uBlock also blocks the content, or rather, interferes with the rendering. It says it didn't block anything on the page. It might have to do with the div being named "fb-content" as in facebook-content.

**Comment by voronoipotato** [comment]
Yes, Ublock had an item marked yellow in the logs, for ".fb-content" perhaps change this to fable-content.

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip @voronoipotato. Yes I tried to change `fb-content` to `fable-content` (see #286) but that broke the styles :( Also, it's probably better to use something else than `fable-` as this interferes with links when searching&replacing.

I need to look into this in more depth (PRs are also welcome 😄). I'm going to close this for now so we can continue the discussion on #286.
