### ISSUE TITLE
Assert.AreEqual() doesn't perform F#/structural equality

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#578]
### Description

See this: https://github.com/et1975/fable-aether/commit/7620c2eb4e69514f2752683e4706d543f8034e3b#diff-4ea1dd1229f281c626f874511410263fL11

### Expected behavior

It should use equality capabilities (like `=` operator) if possible.

### Actual behavior

It doesn't

### Known workarounds

Change the check to `AreEqual ((x=y), true`

### Related information 

* Fable: 0.7.x
* Mono Version: 4.6.x
* Operating system: OSX

**Comment by alfonsogarciacaro** [comment]
Can you please update fable-compiler, fable-core and fable-plugins-nunit? This should be fixed now. I've also added the optional message argument: `Assert.AreEqual(x, y, "my message")`

**Comment by et1975** [comment]
Awesome, it works now!
