### ISSUE TITLE
Printf.printfn runtime issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#579]
this works:
 `printfn "%d" 42`

but this does not work:
 `Printf.printfn "%d" 42`

runtime error:
```
[ERROR] C:\Projects\test\src\test\node_modules\fable-core\umd\String.js:103
                return fsFormatRegExp.test(str) ? makeFn(str) : _cont(str);
                                                                ^
TypeError: _cont is not a function
    at C:\Projects\test\src\test\node_modules\fable-core\umd\String.js:103:65
```

**Comment by ncave** [comment]
@alfonsogarciacaro Here is how they get rendered:
```
printfn "%d" 42
   (0, _String.fsFormat)("%d")(x => {console.log(x);})(42);
```
```
Printf.printfn "%d" 42
   (0, _String.fsFormat)((0, _String.fsFormat)("%d"))(42);
```

**Comment by ncave** [comment]
@alfonsogarciacaro Would this fix kprintf as well? (I know, I'm pushing my luck :)

**Comment by alfonsogarciacaro** [comment]
At the moment, [these are the only print format functions available](https://github.com/fable-compiler/Fable/blob/679606af717e7c569c04482b830fa533d72ba4c4/src/fable/Fable.Compiler/Replacements.fs#L462-L470). PRs welcome!
