### ISSUE TITLE
Using printfn in a fsx file produces an error

### ISSUE THREAD

**Issue by lambdakris** [fable-compiler/Fable#581]
### Description

I was trying to follow the Fable section of Ch 7 of Mastering F# but ran into a problem with the HelloWorld.fsx script.

### Repro steps

Here are the steps that lead me to the error:
1. I installed fable-compiler globally through NPM (Already had .NET and Visual F# Tools installed through Visual Studio 2015)
2. I created a file called HelloWorld.fsx in VS Code with the following content
`printfn "Hello World!"`
3. I ran fable on the fsx file
`fable HelloWorld.fsx`
4. I ran node on the js file
`node HelloWorld.js`

### Expected behavior

I expected the terminal to print "Hello World!"

### Actual behavior

The terminal actually printed the following error message

> C:\Users\lambdakris\Code\HelloWorld.js:1
> (function (exports, require, module, __filename, __dirname) { import { fsFormat } from "fable-core/String";
>                                                               ^^^^^^
> SyntaxError: Unexpected token import
>     at Object.exports.runInThisContext (vm.js:78:16)
>     at Module._compile (module.js:545:28)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)
>     at Module.runMain (module.js:607:10)
>     at run (bootstrap_node.js:420:7)
>     at startup (bootstrap_node.js:139:9)
>     at bootstrap_node.js:535:3
> 
> 

### Known workarounds

Replacing printfn "Hello World!" with System.Console.WriteLine("Hello World!")

### Related information 

* Fable Version - 0.7.17
* .NET Fx Version - .NET Framework 4.6.2
* OS - Windows 10

**Comment by lambdakris** [comment]
Ahh, makes sense and simple enough, thanks. Small problem though, another error cropped up. After running `fable HelloWorld.fsx --module commonjs', running `node HelloWorld.js` produces

> module.js:474
>     throw err;
>     ^
> 
> Error: Cannot find module 'fable-core/umd/String'
>     at Function.Module._resolveFilename (module.js:472:15)
>     at Function.Module._load (module.js:420:25)
>     at Module.require (module.js:500:17)
>     at require (internal/module.js:20:19)
>     at Object.<anonymous> (C:\Users\lambdakris\Code\HelloWorld.js:3:15)
>     at Module._compile (module.js:573:32)
>     at Object.Module._extensions..js (module.js:582:10)
>     at Module.load (module.js:490:32)
>     at tryModuleLoad (module.js:449:12)
>     at Function.Module._load (module.js:441:3)

Is it perhaps necessary to incorporate a package.json file and install fable-core dependency in order to run scripts as well as full fledged projects?

**Comment by lambdakris** [comment]
I can confirm that with `npm init -yes` and `npm i fable-core --save` it works

**Comment by alfonsogarciacaro** [comment]
Cool, thank you! That part of the book needs updating... :/
