### ISSUE TITLE
Fable node process not killed on compilation failure

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#585]
### Description

When bundling fails, fable crashes and let the process alive.

![fable_boom](https://cloud.githubusercontent.com/assets/883207/20883319/c3217dba-bae5-11e6-86b5-93533318ea9e.png)

So we need to kill the process by hand.

### Related information 

* Fable Version 0.7.18
* .NET Runtime, CoreCLR or Mono Version 4.4
* windows 10

**Comment by whitetigle** [comment]
...and before you ask, bundling fails when the import directive fails 

`type [<Import("MyNaughtyObject","foo")>] MyNaughtyObject(options:obj) = ...
`
where "foo" is unresolved

![fable_boom](https://cloud.githubusercontent.com/assets/883207/20883526/f6f30e1e-bae6-11e6-9b47-63712861cfde.png)

(there it's "" that's unresolved)

**Comment by alfonsogarciacaro** [comment]
Can you please try with latest version? I changed it so the app doesn't crashes in watch mode when there're bundling errors :)

**Comment by whitetigle** [comment]
⁉️  could not reproduce the error this morning with both 0.7.18 and 0.7.19. 

What I can say is that it does not crash (and it bundles). So I miss some other parameter to reproduce the problem. I should have created a test case... Would you have any idea to make bundling fail so I can test ?

If not let's say it solved.  And if I encounter other bundling error in watch mode I will update this issue to say how things went.

**Comment by MangelMaxime** [comment]
@whitetigle To force a bundle error you could remove a deps from your node_modules or ask to import a fake one. This should force Rollup to failed.

**Comment by alfonsogarciacaro** [comment]
Hehe, I was just thinking I had introduced the possibility of an infinite loop and hoped nobody noticed and then I read your comment ;) Can you please give it a new try with fable-compiler 0.7.20?

**Comment by whitetigle** [comment]
Ok! Seems good now!

![wip](https://cloud.githubusercontent.com/assets/883207/20957145/530c57b0-bc4e-11e6-8e09-975ddd31db8f.png)
