### ISSUE TITLE
Please add sample demonstrating use of Fetch API and toJson/ofJson for client/server shared types

### ISSUE THREAD

**Issue by kevkov** [fable-compiler/Fable#586]
To quote the man:

"Alfonso Garcia-Caro @alfonsogarciacaro 10:15
Hi @kevkov, you can use Fetch API (fable-powerpack) + toJson/ofJson (Fable.Core.JsInterop) on the client side, and Json.NET + Fable.JsonConverter (nuget package) on the client side."

"Alfonso Garcia-Caro @alfonsogarciacaro 10:22
@kevkov Can you please open an issue requesting the sample so I don't forget?"

This is the least I could do.

**Comment by alfonsogarciacaro** [comment]
I still need to implement the sample but Tomas Petricek already has a working Suave/Fable app: https://github.com/tpetricek/fable-tutorial/tree/master/3-drawing

> Please note the sample uses the browser default `JSON.parse/stringify` though

**Comment by et1975** [comment]
Elmish has a react native sample - https://github.com/fable-compiler/fable-elmish/blob/master/samples/react-native/webrequest/src/App.fs#L33
It would work more or less the same way in any environment that supports the fetch api.

**Comment by Banashek** [comment]
**[Here](https://github.com/Banashek/Universal-FSharp-Samples/tree/master/JsonApi)** is a WIP sample showing shared types between the server and the client.

**[Client Request](https://github.com/Banashek/Universal-FSharp-Samples/blob/master/JsonApi/src/client/App.fs#L29)**

**[Server Response](https://github.com/Banashek/Universal-FSharp-Samples/blob/master/JsonApi/src/App.fs#L24)**

_NOTE_ on the server it uses the jsonconverter library found **[here](https://github.com/fable-compiler/Fable/tree/master/src/nuget/Fable.JsonConverter)** as a single file to work around it not targeting netcore at the moment

**Comment by alfonsogarciacaro** [comment]
The [fable-suave-scaffold](https://github.com/fable-compiler/fable-suave-scaffold) also uses the Json converter now with shared types :+1:
