### ISSUE TITLE
Error with inflate on some record types

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#588]
### Description

I got the error below while trying to reproduce some errors I got with `inflate`. I did not get the errors this time (seems to be solved in this new update) but got a new error during the testing.

### Repro steps

Please provide the steps required to reproduce the problem

    #r "./node_modules/fable-core/Fable.Core.dll"

    open Fable.Core
    open Fable.Core.JsInterop
    open Fable.Import

    type Score = { subject: string } 
    type TestRecord<'t> = { data: 't list }
    let someServerData = { data = [] } |> toJson |> ofJson<obj>

    //tests
    let test1 = inflate<TestRecord<int>> someServerData //ok
    let test2 = someServerData |> toJson |> ofJson<TestRecord<Score>> //ok
    let test3 = inflate<TestRecord<Score>> someServerData //error

### Expected behavior

Expected code to run successfully

### Actual behavior

    fable-compiler 0.7.18: Start compilation...
    Compiled GenericTest.js at 1:22:02 PM
    Bundling...
    Bundled bundle.js at 1:22:04 PM
    E:\Playground\FableTests\ErrorTests\bundle.js:1763
                            throw _iteratorError;
                            ^

    TypeError: arr.map is not a function
        at inflateArray (E:\Playground\FableTests\ErrorTests\bundle.js:1650:46)
        at inflate (E:\Playground\FableTests\ErrorTests\bundle.js:1704:28)
        at inflate (E:\Playground\FableTests\ErrorTests\bundle.js:1751:30)
        at inflatePublic (E:\Playground\FableTests\ErrorTests\bundle.js:1775:12)
        at exports.GenericTest (E:\Playground\FableTests\ErrorTests\bundle.js:1866:13)
        at Object.<anonymous> (E:\Playground\FableTests\ErrorTests\bundle.js:1879:2)
        at Module._compile (module.js:573:32)
        at Object.Module._extensions..js (module.js:582:10)
        at Module.load (module.js:490:32)
        at tryModuleLoad (module.js:449:12)

### Known workarounds

Where absolutely needed, `toJson` and `ofJson` will do the trick

### Related information 

* Fable Version: 0.7.18
* .NET Runtime, CoreCLR or Mono Version
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
This is tricky. The only reason `inflate` is exposed is because another user was using a custom serialization method and needed it, but it's really designed for internal use. The error is confusing but this may not be a bug, `inflate` inflates a plain object, so it shouldn't be used on an object already inflated (as those produced by `ofJson`). Another source of confusion is that `inflate` mutates the object argument. This could be fixed but, as `inflate` is mainly intended for internal use, it may make sense to keep it performant.

All in all, your code would pass if edited as follows (note I replaced `ofJson` with `JSON.parse` and I deleted the previous tests to prevent they mutate the object):

```fsharp
type Score = { subject: string } 
type TestRecord<'t> = { data: 't list }
let someServerData = { data = [] } |> toJson |> JS.JSON.parse

//tests
let test3 = inflate<TestRecord<Score>> someServerData //error
```

I tried to improve the comment of `inflate` so it's less confusing (820f088e9009916337b17bd751324ac434484733). Please tell me if you think this is enough or whether you have any other suggestion.

**Comment by rkosafo** [comment]
Following your comment, I did some further tests and realized that the error is because `inflate` mutates the object and it fails for an already inflated object. Changing `someServerData` into a function so a new json is produce everything fixed the error.

The comment is detailed enough. It would have deterred me had I seen it before :).
On the mutation of the object, I think it is ok as long as the user is aware of it.

The current app I'm working is using `FeathersJs` and I do not have control over the serialization and de-serialization process which is why inflate is helpful to convert the pojos after a service call.

One question though:
Since inflate works correctly on pojos, is there a way to determine if an object is a pojo or an f# type? That way I could write `inflate'` which will check this before calling inflate.

**Comment by alfonsogarciacaro** [comment]
`inflate` should work more or less well with records, but be careful with DUs ;)

To tests if x is a plain object, something like this should work in most cases:

```fsharp
[<Emit("typeof $0 == 'object' && $0.constructor == Object")>]
let isPlainObj(o: obj): bool = jsNative
```

Source: http://stackoverflow.com/a/5878101

> Note: The emit expression evaluates the argument twice, so be careful not to pass an expression that should only be evaluated once (like a function call): e.g. `myFunction() |> isPlainObj`. Do `let o = myFunction() in isPlainObj(o)`

> Note 2: Yes, I should probably fix this, I already did for F# inline functions but not yet for emit expressions.

**Comment by rkosafo** [comment]
Thanks.
