### ISSUE TITLE
Fable does not generate Bundle.js. No errors displayed.

### ISSUE THREAD

**Issue by pedromsantos** [fable-compiler/Fable#591]
### Description
Running fable does not generate bundle.js but it does not display any errors.

### Repro steps

1) Fork https://github.com/tpetricek/fable-tutorial
2) Execute npm install on 1-counter folder
3) execute fable (without errors)
4) Open index.html
5) Chrome reports error "Failed to load resource: net::ERR_FILE_NOT_FOUND"

### Related information 

* Fable Version - 0.6.15
* Node version - v7.2.0
* npm version - 3.10.9
* Mono Version - Stable 4.6.2.7/08fd525 Tue Nov 22 22:05:58 GMT 2016
* Operating system - OSX ElCapitan 10.11.6

Note: I'm using this hosts file https://github.com/StevenBlack/hosts

**Comment by alfonsogarciacaro** [comment]
Hi @pedromsantos! The `--rollup` option is only available in Fable 0.7.x. Can you please download latest Fable version and try again? If you have it installed globally, you can update by just reinstalling with `npm install -g fable-compiler`.

**Comment by pedromsantos** [comment]
Hi @alfonsogarciacaro thanks it worked
