### ISSUE TITLE
Missing 'equalsUnions' from 'fable-core'

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#592]
I am trying to update ui-perf to test the performance for fable-arch without inline modifier.

But I am getting this error:
`[BUNDLE ERROR] 'equalsUnions' is not exported by node_modules\fable-core\umd\Util.js `

The code is [here](https://github.com/MangelMaxime/ui-perf/blob/3463d27d841383e39fb0ff1e0292bdc3509a9dd8/benchmarks/todomvc/fable-virtualdom/src/virtualdom.fsx) but I don't know which line is causing this error.

**Comment by alfonsogarciacaro** [comment]
It seems you're using `--module commonjs`. I modified Fable so in that case the default reference to the coreLib is `fable-core/umd`, I guess I should removed that if you're using it together with `--rollup` (as Rollup only understands ES2015 exports). For now the solution would be to remove `--module commonjs` and use `"format": "cjs"` within Rollup options instead.

**Comment by MangelMaxime** [comment]
Oh yes,  I didn't see the `module` line thanks

**Comment by alfonsogarciacaro** [comment]
Latest version (0.7.22) should be able to bundle normally even if you use `--module amd`. Can you please check?

**Comment by MangelMaxime** [comment]
It's working :)
Thank you.
