### ISSUE TITLE
Cannot resolve module 'fable-core'

### ISSUE THREAD

**Issue by scitesy** [fable-compiler/Fable#595]
While using Web Pack 1.13.3 with fable-compiler 0.7.22, fable-core 0.7.15 and Commonjs without Rollup references to fable-core in F# script files do not resolve.

### Repro steps

Please provide the steps required to reproduce the problem

1. Step A
run fable in the root directory

### Expected behavior
WebPack begins to watch f# scripts for changes

### Actual behavior
Error:
Version: webpack 1.13.3
Time: 5942ms
        Asset     Size  Chunks             Chunk Names
    bundle.js  2.26 MB       0  [emitted]  main
bundle.js.map  2.67 MB       0  [emitted]  main
   [0] multi main 52 bytes {0} [built]
    + 882 hidden modules

ERROR in ./public/js/main.js
Module not found: Error: Cannot resolve module 'fable-core' in....

### Known workarounds

Go back to 0.6.* version of fable.

### Related information 

* Fable Version - 0.7.22
* .NET Runtime, CoreCLR or Mono Version Mono 4.4.2
* Operating system FreeBSD

**Comment by alfonsogarciacaro** [comment]
Do you have `fable-core` installed in `node_modules` in the same directory (or a parent directory) of `outDir` (that is, the folder where you put the generated JS files)? If you select `--module commonjs` Fable should automatically change the reference to `fable-core/umd` but if it doesn't work please add `--coreLib fable-core/umd` to your config. You can also set explicitly the path to fable-core files, e.g. `--coreLib ../node_modules/fable-core/umd` (the path must be relative to the working directory if passed through the CLI, or to fableconfig.json if it's there instead).

If nothing of this works, can you please post your fableconfig.json, webpack.config.js and your project structure (source folder, outDir...)?

**Comment by scitesy** [comment]
Thank you! I will look at this tonight.

**Comment by scitesy** [comment]
After looking at this again, I don't think this is a fable issue. I think this is an issue of WebPack not resolving fable-core. I'll do more research on this.
