### ISSUE TITLE
Better docs for JS beginners

### ISSUE THREAD

**Issue by latkin** [fable-compiler/Fable#599]
### Description

The current docs seem geared toward folks who are already fluent in the JS/Node world. I'm coming to Fable as a desktop/backend F# dev with minimal web experience, and it's been quite difficult.  I just want to use F# to write code that can power something in the browser (e.g. for my blog).

Specific snags:
  - Default output can't be run in the browser, docs don't make it clear how to fix that
    - https://github.com/fable-compiler/Fable/pull/598 at least corrects misleading error that makes you think the default (unusable) output is "common js"
    - Even after targeting "common js", output is still not usable. In Chrome dev tools I get an error "Uncaught ReferenceError: exports is not defined" on the line `Object.defineProperty(exports, "__esModule", {`. I finally worked around this by copy/pasting the line `define(["exports", "fable-core"], function (exports, _fableCore) {` from the Mario sample, but I don't know what this does or why it's not generated by the compiler for me.
  - All samples are Node-oriented
    - Is there no way to use Fable except with Node? I don't know much about Node or Node packages, I just want some .html and .js files I can upload to my web server. Would be great to have a "bare bones" walkthrough that starts with plain helloworld.fsx file and shows how to get to helloworld.html that can be loaded in a browser.
 - Fable-core not packaged as described in the docs
    - Docs suggest using `requirejs` (not the same as `require.js`?) and configuring with `'fable-core': '../node_modules/fable-core/fable-core.min'`, but the `fable-core` Node package does not contain a file `fable-core.min.js`. Where do I download this file?

Apologies, I know this is all total n00b stuff.

**Comment by MangelMaxime** [comment]
Hello @latkin the documentation for Fable is a middle state because we updated Fable to 0.7 but documentation is still for Fable 0.6.

We have a `Getting started` repo [here](https://github.com/fable-compiler/fable-getting-started) perhaps this can help you :).

Also don't hesitate to come to the Gitter channel is you need more help :)

**Comment by MaxWilson** [comment]
Are you aware of the browser samples? https://github.com/fable-compiler/Fable/tree/master/samples

It sounds like that is exactly what you're looking for. Just go to a directory, run "npm start" to start a web server, and then point your browser at localhost:8080 to run the Fable-generated JS in your browser.

**Comment by alfonsogarciacaro** [comment]
The documentation still needs to be updated (now to match Fable 1.0), but let's do it at the same time we create the new site #887.
