### ISSUE TITLE
F# lib and Fable Support

### ISSUE THREAD

**Issue by whitetigle** [fable-compiler/Fable#605]
### Description

When trying to use this F# lib: [Vaughan](https://github.com/pedromsantos/vaughan/blob/master/Vaughan/Vaughan.fs), be it from github directly using the .fs file or the.dll from the [nuget package](https://www.nuget.org/packages/Vaughan/0.1.0) I get the following error from Fable compiler:

`[ERROR] Cannot find replacement for Vaughan.ScaleHarmonizer.triadsHarmonizer`

The Error seems to come from the fact that modules are padded under the namespace Vaughan ([sample](https://github.com/pedromsantos/vaughan/blob/master/Vaughan/Vaughan.fs#L3))

```f#
namespace A
   module B = ... // tab padding

```
In order to get the lib work, I just need to put modules with the same padding as namespace like this

```f#
namespace A
module B = // no tab make the whole thing work
```

Is this a bug? Would you have more information regarding this problem? Is padding important?
Thanks for your answer!

**Comment by alfonsogarciacaro** [comment]
Interesting. Yeah, this is a bug. Padding shouldn't affect the compilation. I'll have a look, thanks for reporting!

**Comment by alfonsogarciacaro** [comment]
Hmm, this is weird. I think I was able to reproduce this before, but I cannot do it with the latest version. Maybe it has fixed by itself? :wink: Can you please check with fable-compiler 0.7.23?

**Comment by alfonsogarciacaro** [comment]
@whitetigle Are you still having this issue?

**Comment by whitetigle** [comment]
It compiles with 0.7.30. 
I did not try with 1.0 though.
