### ISSUE TITLE
--refs option does not work

### ISSUE THREAD

**Issue by irium** [fable-compiler/Fable#606]
### Description

Using compiled F# `dll`s from *.fsx is broken.
Even provided `fable-helpers-sample` doesn't work too. 
Simplest repro is attached.

Also I tried passing `--refs` option by command-line too. Same result.

### Repro steps

1. Unpack archive.
2. `npm install`
3. `fable`

### Expected behavior

Compilation completed successfully.

### Actual behavior

```
C:\src\fable-error-repo>fable
fable-compiler 0.7.22: Start compilation...
[ERROR] Cannot find replacement for Fable.Helpers.Sample.MyLib.printPairsPadded (L7,7-L7,28) (C:\src\fable-error-repo\test.fsx)
```

### Known workarounds

Please provide a description of any known workarounds.

### Related information 

* Fable Version - latest from NPM : `fable-compiler 0.7.22`
* .NET Runtime: 4.5.1
* OS: Windows 10

[fable-refs-error.zip](https://github.com/fable-compiler/Fable/files/658615/fable-refs-error.zip)

**Comment by alfonsogarciacaro** [comment]
Sorry, I still need to update `fable-helpers-sample`. Actually, with latest fable-compiler version, if you're referencing directly from F# a `.dll` compiled with Fable's `--dll` option, in most cases you don't even need to use the `--refs` option when consuming the library.

More info about the `--dll` option [here](http://fable.io/blog/Introducing-0-7.html#References).
A sample of referencing assemblies compiled with Fable [here](https://github.com/fable-compiler/Fable/blob/master/samples/browser/redux-todomvc/redux-todomvc.fsx).
