### ISSUE TITLE
Replacement for Double.TryParse

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#608]
Currently there is no "replacement" for Double.TryParse and similar functions. It would be useful for many kinds of input validation.

**Comment by alfonsogarciacaro** [comment]
I'm not completely opposed to this, but it raises the same concerns as #348 in the sense that it feels a bit inconsistent to implement just some methods and not the whole BCL class.

That said, thanks to @ncave and @davidtme there are already reliable parsing methods to parse numbers (used with `int`, `float`... and `System.Convert`) so I should probably just implement the replacement and stop complaining :wink:
