### ISSUE TITLE
Event unsubscription

### ISSUE THREAD

**Issue by baks** [fable-compiler/Fable#609]
### Description

Actual handler removing code in Event module doesn't work very well. It cannot handle situation when handler with the same body is added multiple times because it is comparing handlers by comparing handler body string.

### Repro steps

Run this script in browser:
```
#r "node_modules/fable-core/Fable.Core.dll"
 
open Fable.Core
 
let test = new Event<_>()
 
let firstSubscriber =
    test.Publish
    |> Observable.filter (fun x -> x < 25)
    |> Observable.subscribe (fun _ -> printfn "first subscription")
 
let secondSubscriber =
    test.Publish
    |> Observable.filter (fun x -> x > 25)
    |> Observable.subscribe (fun _ -> printfn "second subscription")
 
 
secondSubscriber.Dispose()
 
for i in [1..50] do
    test.Trigger(i)
```

### Expected behavior

Only string "first subscription" is printed on the console

### Actual behavior

"second subscription" string is printed on the console

### Known workarounds

I have examined [Event.ts](https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Core/ts/Event.ts) source code and changing function equality check from that one based on string comparison to that one based on strict equality check seems like it solves the issue.
However, it might be a breaking change if someone's else code was leaning on that behavior (for example implicitly).

### Related information 

* Fable Version - 0.7.9
* .NET Runtime, CoreCLR or Mono Version - .NET Framework 4.6.1
* Operating system - Windows 7

**Comment by alfonsogarciacaro** [comment]
I think this was done to allow adding/removal of .NET event handlers (with `(sender, argument) => void` signature and also to emulate .NET behaviour where (if I'm not mistaken) you can remove a handler passing a new lambda with the same body even if it has not the same reference.

But I agree that in F# the most common way to dispose the handlers is by using the `IDisposable` returned by `Subscribe` and in any case it's probably more intuitive to manage handlers by reference that by unreliably converting the body of the function to string :+1:
