### ISSUE TITLE
Why use System.Func and not FSharp.Core.FSharpFunc ?

### ISSUE THREAD

**Issue by rfrerebe** [fable-compiler/Fable#620]
### Description

I would like to implement PositionCallback
https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Core/Import/Fable.Import.Browser.fs#L10366
it's a **Sytem.Func<Position,unit>**

Could it be a **FSharp.Core.FSharpFunc** ?

### Repro steps

Paste this code in a repo using fable

```
    open Fable.Import
    open Fable.Import.Browser

    let getPosition (pos : Position) : PositionCallback =
        console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString())
```
getPosition can't be compiled in F#

### Expected behavior

The function
 ```
let getPosition (pos : Position) : PositionCallback =
        console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString())
```
does compile
:-)
ideally both Position and PositionCallback can be removed in signature

### Actual behavior

The function
```
let getPosition (pos : Position) : PositionCallback =
        console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString())
```
doesn't compile

### Known workarounds

The below function works
```
    let getPosition : PositionCallback =
        System.Func<Position, unit>(fun pos -> console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString()))
```
but is less idiomatic

### Related information 

* Fable Version 0.7

**Comment by alfonsogarciacaro** [comment]
Sorry, I can't see any difference between the code in Expected and Actual behaviors. What is exactly the error you get?

`System.Func` is used to represent delegates, that is, multiargument functions, while F# lambdas (`FSharp.Core.FSharpFunc`) are always curried.

**Comment by rfrerebe** [comment]
Hello Alfonso,

Thanks for your time.
I expected this code (in "Expected" and "Actual") to compile, but it doesn't.

Is curried an issue when delegates take one argument ?

Rémy

**Comment by alfonsogarciacaro** [comment]
Hi Rémy!

I tried to compile the code your posted and indeed it didn't compile, though apparently the problem was not on Fable but on the F# type checking. As `console.log` returns `unit`, if you change the signature of `getPosition` to:

```fsharp
let getPosition (pos : Position) : PositionCallback =
```

then it should work :smile:

**Comment by rfrerebe** [comment]
Hi Alfonso,

Thanks for your help, I see my silly mistake.

Rémy

**Comment by alfonsogarciacaro** [comment]
Hehe, no worries. There're no silly mistakes. Actually I made a mistake because the signature I posted above was still wrong, I fixed it :+1:

**Comment by rfrerebe** [comment]
Hello,

Here is how wrote it

`    let toFunc<'I, 'T> f =
        System.Func<'I,'T>(f)

    let getPosition (pos : Position) = 
        console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString()))
        |> toFunc<Position,unit>
`

**Comment by alfonsogarciacaro** [comment]
Hmm, I don't think you need `toFunc` here. Can you try the following?

```fsharp
let getPosition (pos : Position) = 
    console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString()))
```

**Comment by rfrerebe** [comment]
Hello Aflonso,

I believe I should reopen this issue.
I tried what you advised.

Here is the code, and some screenshot from VSCode

```

    open FSharp.Core
    open Fable.Core
    open Fable.Core.JsInterop

    open Fable.Import
    open Fable.Import.Browser
    open Fable.PowerPack
    open Fable.PowerPack.Result

    let toFunc<'I, 'T> f =
        System.Func<'I,'T>(f)

    let getPosition (pos : Position) = 
        console.log("Latitude " + pos.coords.latitude.ToString() + ". Longitude " +  pos.coords.longitude.ToString()))

    let getPosition2 : PositionCallback =
        getPosition
        |> toFunc<Position,unit>

    let getPosition3 : PositionCallback =
        getPosition
  
```
getPosition2 is OK, while getPosition3 is not Ok

![image](https://cloud.githubusercontent.com/assets/12632865/21783872/67e4208e-d6b9-11e6-9a56-81e703ebd125.png)

![image](https://cloud.githubusercontent.com/assets/12632865/21783963/e2b2ff4c-d6b9-11e6-8c4e-fd315c7978c9.png)

Any ideas ?

I don't know if anyone has used this API before.

**Comment by alfonsogarciacaro** [comment]
This is not related with Fable but with the F# type checker (operated by the [F# compiler](http://fsharp.github.io/FSharp.Compiler.Service/)) so there's little I can do here. I'd recommend reading about the F# language to understand better how the type checker works. The site http://fsharpforfunandprofit.com/ is a great place to start.

**Comment by rfrerebe** [comment]
Hello Alfonso,

I do understand F# a bit :-)

I believe I do need the **toFunc** function, for this code to compile currently.
My understanding is that it needs to compile with F# to compile with Fable to JS correctly.

Here is a quick repro :
https://github.com/rfrerebe/fable-geolocation

Fable fails with (as the regular F# compiler fails and as expected)

```
[ERROR] F# project contains errors:
This expression was expected to have type
    'PositionCallback'
but here has type
    ''a -> unit'     (L23,4-L23,15) (C:\DEV\fable-geolocation\src/fs/Main.fs)
```

now, back to why I raised an issue initially :

>  https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Core/Import/Fable.Import.Browser.fs#L10366
> it's a Sytem.Func<Position,unit>
> 
> Could it be a FSharp.Core.FSharpFunc ?

An other way to put it is why do I need this **toFunc** function that you seems to also dislike ?

Rémy

**Comment by alfonsogarciacaro** [comment]
Ah, ok. I think I misunderstood you. I guess you want to pass `getPosition` as an argument to some other function. It'd be helpful if you posted the code where you want to use `getPosition` but I'll try to give some info.

> Why use System.Func and not FSharp.Core.FSharpFunc ?

As commented above `System.Func` is used to represent delegates, that is, multiargument functions (which correspond to JS functions), while F# lambdas (`FSharp.Core.FSharpFunc`) are always curried (which in JS are represented as nested functions). I need to update the docs, but you can find more info about the issue [here](http://fable.io/docs/interacting.html#Calling-F-code-from-JavaScript).

Converting an F# function to a delegate is not difficult and it's usually done in the call site. Example:

```fsharp
open System
open Fable.Core
open Fable.Import.Browser

let handlePosition (pos: Position) =
    console.log(pos.coords.latitude.ToString())

let fetchPosition (callback: PositionCallback) =
    failwith "Not implemented"

// You can convert handlePosition when passing it as an argument
fetchPosition(PositionCallback handlePosition)

// You can use Func directly
fetchPosition(Func<_,_> handlePosition)

// It can be cumbersome to write the generic placeholders
// (especially when you have many) so Fable.Core contains
// Func aliases including the number of arguments
fetchPosition(JsFunc1 handlePosition)
```

**Comment by rfrerebe** [comment]
Hello Alfonso,

Thanks a lot for your explantation

Remy
