### ISSUE TITLE
Match expression for discriminated union does not produce correct transpiled code for fallback case

### ISSUE THREAD

**Issue by kevkov** [fable-compiler/Fable#621]
### Description

The transpiled code for the fallback case is either missing or returns the value for the last specific case.

### Repro steps

Given the code:

    type DU =
        | One
        | Two
        | Three
        | Four
        | More of char

    let DUFunc du =
        let x = 
            match du with
            | One 
            | Three -> Some "one"
            | Two -> Some "two"
            | _ -> None
        x

the transpiled match expression function looks like this:

	function DUFunc(du) {
	  var x = function () {
		var _target0 = function _target0() {
		  return "one";
		};

		if (du.Case === "One") {
		  return _target0();
		} else if (du.Case === "Three") {
		  return _target0();
		} else if (du.Case === "Two") {
		  return "two";
		}
	  }();

	  return x;
	}

The null return for the fallback case is missing. The trigger appears to be coalescing specific cases, e.g. `| One | Two ->`

In 'workiing' code for which I have not been able to produce a simplified version the match expression in

    let wordColour tag =
        printfn "tag=%A" tag
        let colour = match tag with
        | NNP | NN | PRP  -> Some "#ff0000"
        | DT   -> Some "#ff99ff"
        | VB | VBD | VBZ | MD  -> Some "#3333cc"
        | AD   -> Some "#00cc99"
        | P  -> Some "#ffff00"
        | RB   -> Some "#663300"
        | CC  -> Some "#cc00ff"
        | _ -> None
        printfn "colour=%A" colour
        colour

produces the transpiled code

	function wordColour(tag) {
	  fsFormat("tag=%A")(function (x) {
		console.log(x);
	  })(tag);

	  var colour = function () {
		var _target0 = function _target0() {
		  return "#ff0000";
		};

		var _target2 = function _target2() {
		  return "#3333cc";
		};

		var _target3 = function _target3(AD) {
		  return "#00cc99";
		};

		if (tag.Case === "NNP") {
		  return _target0();
		} else if (tag.Case === "NN") {
		  return _target0();
		} else if (tag.Case === "PRP") {
		  return _target0();
		} else if (tag.Case === "DT") {
		  return "#ff99ff";
		} else if (tag.Case === "VB") {
		  return _target2();
		} else if (tag.Case === "VBD") {
		  return _target2();
		} else if (tag.Case === "VBZ") {
		  return _target2();
		} else if (tag.Case === "MD") {
		  return _target2();
		} else if (tag.Case === "RB") {
		  return _target3(tag);
		} else if (tag.Case === "CC") {
		  return _target3(tag);
		} else {
		  return _target3(tag);
		}
	  }();

	  fsFormat("colour=%A")(function (x) {
		console.log(x);
	  })(colour);
	  return colour;
	}

The fallback case produces the same result as the `CC` case.

### Expected behavior

The fallback case should return the correct value.

### Related information 

* Fable Version: 0.7.24, 23
* .NET Runtime: 4.5.2
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
This is (more or less) intended. Basically, Fable ignores the `else` branch when it's equivalent to `null`. This is because in the F# AST the `if .. then .. else` expression always has an else clause even if the source code doesn't (e.g. `if true then printfn "foo"`), so I'm just ignoring the `else` branch when it's empty (that is, equals null).

In any case, this shouldn't have any practical effect as `None`, `null` and `undefined` are the same thing for Fable. So a check like `DUFunc Four = None` must hold true.

In your first example, `One` and `Three` are indeed coalescing but this is correct. If the second example coalesces `CC` and the default case that does look like an error. Could you please post the DU declaration so I can try to reproduce the problem?

**Comment by kevkov** [comment]
DU for the second case, thanks to Sergey Tihon for the original:

    type POSTag =
        | ROOT
        /// <summary>
        /// Adjective Phrase.
        /// <para> Phrasal category headed by an adjective (including comparative and superlative adjectives). </para>
        /// <para> Example: outrageously expensive.</para>
        /// </summary>
        | ADJP 
        /// <summary>
        /// Adverb Phrase.
        /// <para> Phrasal category headed by an adverb (including comparative and superlative adverbs).</para>
        /// <para> Examples: rather timidly, very well indeed, rapidly. </para>
        /// </summary>
        | ADVP 
        /// <summary>
        /// Coordinating conjunction
        /// <para>This category includes 'and', 'but', 'nor', 'or', 'yet' (as in 'Yet it's cheap', 'cheap yet good'), as well as the
        /// mathematical operators 'plus', 'minus', 'less', 'times' (in the sense of "multiplied by") and 'over' (in the sense of
        /// "divided by"), when they are spelled out.</para>
        /// <para>For in the sense of "because" is a coordinating conjunction (CC) rather than a subordinating conjunction (IN).</para>
        /// <para> He asked to be transferred, for/CC he was unhappy.</para>
        /// <para> So in the sense of "so that," on the other hand, is a subordinating conjunction (IN).</para>
        /// </summary>
        | CC 
        /// Cardinal number
        | CD 
        /// <summary>
        /// Conjunction Phrase.
        /// <para> Used to mark certain "multi-word" conjunctions, such as 'as well as', 'instead of'.</para>
        /// </summary>
        | CONJP 
        /// <summary>
        /// Determiner
        /// <para> This category includes the articles a(n), every, no and the, the indefinite determiners another, any and
        /// some, each, either (as in either way), neither (as in neither decision), that, these, this and those, and
        /// instances of all and both when they do not precede a determiner or possessive pronoun (as in all roads or
        /// both times). (Instances of all or both that do precede a determiner or possessive pronoun are tagged as
        /// predeterminers (PDT).) Since any noun phrase can contain at most one determiner, the fact that such can
        /// occur together with a determiner (as in the only such case) means that it should be tagged as an adjective
        /// (JJ), unless it precedes a determiner, as in such a good time, in which case it is a predeterminer (PDT).</para>
        /// </summary>
        | DT 
        /// <summary>
        /// Existential there
        /// <para> Existential there is the unstressed there that triggers inversion of the inflected verb and 
        /// the logical subject of a sentence. </para>
        /// <para> EXAMPLES: There/EX was a party in progress.; There/EX ensued a melee.</para>
        /// </summary>
        | EX 
        /// Fragment.
        | FRAG 
        /// <summary>
        /// Foreign word
        /// <para>Use your judgment as to what is a foreign word. For me, yoga is an NN, while 'bete noire' and 'persona non
        /// grata' should be tagged bete/FW noire/FW and persona/FW non/FW grata/FW, respectively. </para>
        /// </summary>
        | FW 
        /// <summary>
        /// Preposition or subordinating conjunction
        /// <para> We make no explicit distinction between prepositions and subordinating conjunctions. (The distinction is
        /// not lost, however - a preposition is an IN that precedes a noun phrase or a prepositional phrase, and a
        /// subordinate conjunction is an IN that precedes a clause.) </para>
        /// <para> The preposition to has its own special tag TO. </para>
        /// </summary>
        | IN 
        /// <summary>
        /// Interjection. 
        /// <para> Corresponds approximately to the part-of-speech tag UH.</para>
        /// </summary>
        | INTJ 
        /// <summary>
        ///  Adjective
        /// <para>Hyphenated compounds that are used as modifiers are tagged as adjectives (JJ).</para>
        /// <para>EXAMPLES: happy-go-lucky/JJ; one-of-a-kind/JJ; run-of-the-mill/JJ; </para>
        /// <para>Ordinal numbers are tagged as adjectives (JJ), as are compounds of the form n-th X-est, like fourth-largest.</para>
        /// </summary>
        | JJ 
        /// <summary>
        /// Adjective, comparative
        /// <para>Adjectives with the comparative ending -er and a comparative meaning are tagged JJR. More and less
        /// when used as adjectives, as in more or less mail, are also tagged as JJR. More and less can also be tagged
        /// as JJR when they occur by themselves. Adjectives with a comparative meaning but without the comparative ending -er, 
        /// like superior, should simply be tagged as JJ. Adjectives with the ending -er but without a strictly comparative meaning 
        /// ("more X"), like further in further details, should also simply be tagged as JJ.</para>
        /// </summary>
        | JJR 
        /// <summary>
        /// Adjective, superlative
        /// <para> Adjectives with the superlative ending -est (as well as worst) are tagged as JJS. Most and least when used
        /// as adjectives, as in the most or the least mail, are also tagged as JJS. Most and least can also be tagged as
        /// JJS when they occur by themselves. Adjectives with a superlative meaning but without the superlative ending -est, 
        /// like first, last or unsurpassed, should simply be tagged as JJ.</para>
        /// </summary>
        | JJS 
        /// <summary>
        /// List item marker
        /// <para> This category includes letters and numerals when they are used to identify items in a list. </para>
        /// </summary>
        | LS 
        /// <summary>
        /// List marker. 
        /// <para>Includes surrounding punctuation.</para>
        /// </summary>
        | LST 
        /// <summary>
        /// Modal
        /// <para> This category includes all verbs that don't take an -s ending in the third person singular present: 
        /// 'can', 'could,' '(dare)', 'may', 'might', 'must', 'ought', 'shall', 'should', 'will', 'would'. </para>
        /// </summary>
        | MD 
        /// <summary>
        /// Not a Constituent
        /// <para> used to show the scope of certain prenominal modifiers within an NP.</para>
        /// </summary>
        | NAC 
        ///Noun, singular or mass
        | NN 
        /// Noun, plural
        | NNS 
        ///Proper noun, singular
        | NNP 
        ///Proper noun, plural
        | NNPS 
        /// <summary> 
        /// Noun Phrase. 
        /// <para>Phrasal category that includes all constituents that depend on a head noun.</para>
        /// </summary>
        | NP 
        /// Used within certain complex noun phrases to mark the head of the noun phrase. Corresponds very roughly to N-bar level 
        /// but used quite differently.
        | NX 
        /// <summary>
        /// Predeterminer
        /// <para> This category includes the following determiner like elements when they precede an article or possessive pronoun. </para>
        /// <para> EXAMPLES: all/PDT his marbles; nary/PDT a soul;
        ///                     both/PDT the girls; quite/PDT a mess;
        ///                     half/PDT his time; rather/PDT a nuisance;
        ///                     many/PDT a moon; such/PDT a good time;</para>
        /// </summary>
        | PDT 
        /// <summary>
        /// Possessive ending
        /// <para> The possessive ending on nouns ending in 's or ' is split off by the tagging algorithm and 
        /// tagged as if it were a separate word.</para>
        /// <para> EXAMPLES: John/NNP 's/POS idea; the parents/NNS '/POS distress</para>
        /// </summary>
        | POS 
        /// <summary>
        /// Prepositional Phrase.
        /// <para> Phrasal category headed by a preposition. </para>
        /// </summary>
        | PP 
        /// Parenthetical.
        | PRN 
        /// <summary>
        /// Personal pronoun
        /// <para> This category includes the personal pronouns proper, without regard for case distinctions ('I', 'me', 'you', 'he',
        /// 'him', etc.), the reflexive pronouns ending in -self or -selves, and the nominal possessive pronouns 'mine',
        /// 'yours', 'his', 'hers', 'ours' and 'theirs'. The adjectival possessive forms 'my', 'your', 'his', 'her', 'its', 'our' and 
        /// 'their', on the other hand, are tagged PRPS. </para>
        /// </summary>
        | PRP 
        /// <summary>
        /// Possessive pronoun (prolog version PRP-S)
        /// <para> This category includes the adjectival possessive forms 'my', 'your', 'his', 'her', 'its', 'one's', 'our' and 'their'. 
        /// The nominal possessive pronouns 'mine', 'yours', 'his', 'hers', 'ours' and 'theirs' are tagged as personal pronouns (PRP). </para>
        /// </summary>
        | PRPS
        /// <summary>
        /// Particle. 
        /// <para>Category for words that should be tagged RP. </para>
        /// </summary>
        | PRT 
        ///Quantifier Phrase (i.e. complex measure/amount phrase); used within NP.
        | QP 
        /// <summary>
        /// Adverb
        /// <para>This category includes most words that end in -ly as well as degree words like quite, too and very,
        /// posthead modifiers like enough and indeed (as in good enough, very well indeed), and negative markers like
        /// 'not', 'n't' and 'never'.</para>
        /// </summary>
        | RB 
        /// <summary>
        /// Adverb, comparative
        /// <para> Adverbs with the comparative ending -er but without a strictly comparative meaning, like later in We can
        /// always come by later, should simply be tagged as RB. </para>
        /// </summary>
        | RBR 
        /// Adverb, superlative
        | RBS 
        /// <summary>
        /// Particle
        /// <para> This category includes a number of mostly monosyllabic words that also double as directional adverbs and prepositions.</para>
        /// </summary>
        | RP 
        /// Reduced Relative Clause.
        | RRC
        /// Simple declarative clause, i.e. one that is not introduced by a (possible empty) subordinating conjunction or a wh-word and 
        /// that does not exhibit subject-verb inversion. 
        | S 
        ///Clause introduced by a (possibly empty) subordinating conjunction.
        | SBAR 
        ///Direct question introduced by a wh-word or a wh-phrase. Indirect questions and relative clauses should be bracketed as SBAR, not SBARQ.
        | SBARQ 
        ///Inverted declarative sentence, i.e. one in which the subject follows the tensed verb or modal.
        | SINV 
        ///Inverted yes/no question, or main clause of a wh-question, following the wh-phrase in SBARQ.
        | SQ 
        /// <summary>
        /// Symbol
        /// <para> This tag should be used for mathematical, scientific and technical symbols or expressions that aren't words
        /// of English. It should not used for any and all technical expressions. For instance, the names of chemicals,
        /// units of measurements (including abbreviations thereof) and the like should be tagged as nouns. </para>
        /// </summary>
        | SYM 
        /// <summary>
        /// to
        /// <para>To is tagged TO, regardless of whether it is a preposition or an infinitival marker </para>
        /// </summary>
        | TO 
        /// Unlike Coordinated Phrase
        | UCP 
        /// <summary>
        /// Interjection
        /// <para> This category includes 'my' (as in 'My, what a gorgeous day'), 'oh', 'please', 'see' (as in 'See, it's like this'), 
        /// 'uh', 'well' and 'yes', among others. </para>
        /// </summary>
        | UH 
        /// <summary>
        /// Verb, base form
        /// <para> This tag subsumes imperatives, infinitives and subjunctives.</para>
        /// <para> EXAMPLES: Imperative: Do/VB it.</para>
        /// <para> EXAMPLES: Infinitive: You should do/VB it.; We want them to do/VB it.; We made them do/VB it.; </para>
        /// <para> EXAMPLES: Subjunctive: We suggested that he do/VB it. </para>
        /// </summary>
        | VB 
        /// <summary>
        /// Verb, past tense
        /// <para> This category includes the conditional form of the verb to be. </para>
        /// <para> EXAMPLES: If I were/VBD rich, ... ; If I were/VBD to win the lottery, ... </para>
        /// </summary>
        | VBD 
        /// Verb, gerund or present participle
        | VBG 
        /// Verb, past participle
        | VBN 
        ///Verb, non-3rd person singular present
        | VBP 
        ///Verb, 3rd person singular present
        | VBZ 
        /// <summary>
        /// Verb Phrase. 
        /// <para> Phrasal category headed a verb.</para>
        /// </summary>
        | VP 
        /// <summary> 
        /// Wh-determiner
        /// <para> This category includes which, as well as that when it is used as a relative pronoun. </para>
        /// </summary>
        | WDT 
        /// <summary>
        /// Wh-adjective Phrase. 
        /// <para> Adjectival phrase containing a wh-adverb, as in 'how hot'. </para>
        /// </summary>
        | WHADJP 
        /// <summary>
        /// Wh-adverb Phrase. 
        /// <para> Introduces a clause with an NP gap. May be null (containing the 0 complementizer) or lexical, 
        /// containing a wh-adverb such as 'how' or 'why'. </para>
        /// </summary>
        | WHADVP 
        /// <summary>
        /// Wh-noun Phrase. 
        /// <para> Introduces a clause with an NP gap. May be null (containing the 0 complementizer) or lexical, 
        /// containing some wh-word, e.g. 'who', 'which book', 'whose daughter', 'none of which', or 'how many leopards'. </para>
        /// </summary>
        | WHNP 
        /// <summary>
        /// Wh-prepositional Phrase. 
        /// <para>Prepositional phrase containing a wh-noun phrase (such as 'of which' or 'by whose authority') 
        /// that either introduces a PP gap or is contained by a WHNP.</para>
        /// </summary>
        | WHPP 
        /// <summary>
        /// Wh-pronoun
        /// <para> This category includes 'what', 'who' and 'whom'. </para>
        /// </summary>
        | WP 
        /// <summary>
        /// Possessive wh-pronoun (prolog version WP-S)
        /// <para> This category includes the wh-word 'whose' </para>
        /// </summary>
        | WPS 
        /// <summary>
        /// Wh-adverb
        /// <para> This category includes 'how', 'where', 'why', etc. </para>
        /// <para> When in a temporal sense is tagged WRB. In the sense of "if", on the other hand, it is a subordinating conjunction (IN). </para>
        /// <para> EXAMPLES: When/WRB he finally arrived, I was on my way out.; I like it when/IN you make dinner for me.</para>
        /// </summary>
        | WRB 
        ///Unknown, uncertain, or unbracketable. X is often used for bracketing typos and in bracketing 'the...the'-constructions.
        | X

        /// Punctuation mark, sentence close: '.',';','?','!'
        | SentenceCloser
        /// Punctuation mark, comma: ','.
        | Comma
        /// Punctuation mark, colon: ':'.
        | Colon
        /// Contextual separator, left parenthesis: '(','{','['
        | LRB
        /// Contextual separator, right parenthesis: ')','}',']'
        | RRB
        /// Start quote
        | SQT
        /// End quote
        | EQT

        /// One of special symbols like: '#'
        | Symbol of char

**Comment by alfonsogarciacaro** [comment]
Ok, this puzzles me completely. First, the behavior is consistent with standard F#. If you run this in F# Interactive you'll get the same result:

```
wordColour CC
wordColour SQT
````

Also, when compiling the code, the F# compiler warns you that the last four rules will never be matched. I'm not sure where the `AD` and `P` rules come from (they're not in the DU you posted) but apparently they swallow everything. If you comment out these rules then the pattern matching works as expected.

**Comment by kevkov** [comment]
I had seen the warnings before but just put it down as something I would need to get round to fixing later, the function I had copied from another piece of work which I thought used the same DU. obviously not. But it is bizarre and a bit worrying. Intellisense (FCS I suppose) thinks AD and P are POSTags. I will take the issue elsewhere. Please close this if you want. If I find out why this code is OK I will let you know,

**Comment by kevkov** [comment]
From page 78 of F# 4.0 Design Patterns (Packt)

"To begin with, the omission of the literal didn't blow up the script, producing just a benign
warning that THREE might be a misspelled pattern name. Applying the function to the
argument 50 that is completely off produces the same result as before for the legitimate
argument value 3. What gives?

No magic here; in accordance with the description identifier, THREE was not recognized as a
named literal, discriminated union case, exception type, or active pattern. This finding
turned it into a variable pattern playing the role of a match-all pattern case, which result-expression
just blindly outputs as string "3".

In my experience as an F# developer, I faced at least one occasion when this seemingly
innocuous pattern type transformation typo turned into a nasty bug.

The moral: handle with care, and do not disregard F# compiler warnings!"

I've learnt my lesson.
