### ISSUE TITLE
Code from fable-core is being duplicated when bundling with Rollup

### ISSUE THREAD

**Issue by kevkov** [fable-compiler/Fable#622]
### Description

Changes to makeGeneric (Serialize.ts) mean that inflate() does not how to handle deserialization that previously worked

### Repro steps

In 0.7.23 a call such as `tryFetchAs<Part list>` would cause makeGeneric to execute this:

    return class extends typeDef { [FSymbol.generics]() { return genArgs; } };

which would in turn cause in the test in inflate():

    else if (typeof typ === "function") {

(Serialize.ts:156) to succeed and deserialize the json. In 0.7.24 makeGeneric now does this:

    return new NonDeclaredType("GenericType", typeDef, genArgs);

but the corresponding line in inflate():

    else if (typ instanceof NonDeclaredType) {

(Serialize.ts:143) does not succeed (verified in Chrome debugger) and instead an exception is thrown because no match is found. Please note that I don't believe that the error is a function of the JSON received and thus the F# type and how it is serailized on the server side is irrelevant to the problem.

### Known workarounds

None known.

### Related information 

* Fable Version: 0.7.24
* .NET Runtime: 4.5.2
* Operating system: Windows 10

**Comment by kevkov** [comment]
Furthermore in the js bundle, makeGeneric looks like this:

    function makeGeneric(typeDef, genArgs) {
        return new NonDeclaredType("GenericType", typeDef, genArgs);
    }

while the test in inflate() looks like this:

    else if (typ instanceof NonDeclaredType$1) {

where NonDeclaredType$1 is defined like this:

    var NonDeclaredType$1 = (function () {
        function NonDeclaredType(kind, definition, generics) {
            this.kind = kind;
            this.definition = definition;
            this.generics = generics;
        }
        NonDeclaredType.prototype.Equals = function (other) {
            if (this.kind === other.kind && this.definition === other.definition) {
                return typeof this.generics === "object"
                    ? equalsRecords$1(this.generics, other.generics)
                    : this.generics === other.generics;
            }
            return false;
        };
        return NonDeclaredType;
    }());

While I think I understand why the test fails, I know next to nothing about ts -> js and why the code is generated this way.

**Comment by alfonsogarciacaro** [comment]
I had to change the `makeGeneric` function because extending ES2015 classes didn't work when compiling fable-core code to ES5 (as it's being distributed at the moment) 😕 

The JSON unit tests are passing after the change though. Could you please post the actual F# code that is failing for you (so we can turn it into a unit test) and the compilation options you're using? Also, please make sure you're using the latest fable-core and fable-compiler versions.

**Comment by kevkov** [comment]
The issue is due to my solution setup which is like this:
- Domain: standard F# library for sharing types between front and back end
- Client: Fable front end
- Web: Suave and Fable
There was originally a technical reason for having the Web project setup as Suave/Fable (though I can't recall it now). In the end it was just convenience (laziness) to build the js bundle in the Web project, i.e. fableconfig.json has this:

    "projFile": [
            "../Domain/Domain.fsproj",
            "../Client/Client.fsproj"
        ],
        "outDir": "out",

With 0.7.23 all was OK but with 0.7.24 it looks like there is some double bundling going on. Note the js bundle in the Client project is OK (so maybe I should jst use that ;). If you feel this a corner case or abuse of configuration, that's fine, please close. Otherwise I will produce a small example, evemtually :)

Related to the work I was doing here, is UnionTypeInfoConverter() now obsolete in 0.7.24?

**Comment by alfonsogarciacaro** [comment]
Hmm, this is weird. I followed your instructions but I didn't find `NonDeclaredType$1` in the generated bundle (either compiling from `src\Web` or `src\Client`). Can you please try removing the `node_modules` folder and installing the dependencies again?

BTW, interestingly I had a conflict with the `Result` type in fable-powerpack as apparently Ionide was using an FSharp.Core version that already includes `Result`. I guess will have to move to that one soon.

**Comment by kevkov** [comment]
Had already removed node_modules and now have reinstalled node (and removed all local node files) to no avail. Just now, I have tried the project on a fresh windows machine (and fixed the project refs, apologies) and still have the same problem. Attached is the js bundle if it might provide some clues.


[bundle.zip](https://github.com/fable-compiler/Fable/files/687137/bundle.zip)

**Comment by alfonsogarciacaro** [comment]
Thanks for the additional info! Ok, I tried now on Windows and I could reproduce the problem (I was on a Mac before). Apparently the issue comes from the way the commonjs rollup plugin is locating `fable-core`. As `fable-core` is installed both in `src\Client\node_modules` and  `src\Web\node_modules`, for some reason `NonDeclaredType` is sometimes taken from one copy of `fable-core` and sometimes from the other, thus the duplication.

My recommendation would be to put `package.json` on the root folder (next to `paket.dependencies`). This way there will be only one copy of `fable-core` so Rollup won't get confused :wink:

**Comment by kevkov** [comment]
Thanks for your efforts, I'll do as you recommend
