### ISSUE TITLE
Fable 0.7.24 break Aether

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#624]
When trying to build web app sample for Fable-arch I dot this error: 

`[ERROR] Cannot resolve trait call op_GreaterMinusGreater (L60,14-L60,17) (I:\Github\fable-compiler\fable-arch\samples\web_app\src\App.fs)`

You can reproduce the problem by running `node build.js` on [this project](https://github.com/fable-compiler/fable-arch/tree/feature/web_app_sample/samples/web_app)

**Comment by alfonsogarciacaro** [comment]
This should be fixed in fable-compiler 0.7.25 :+1:

**Comment by MangelMaxime** [comment]
Thanks :)
I will test it with Fable-arch :)

**Comment by MangelMaxime** [comment]
It's fixed perfect :)
