### ISSUE TITLE
[<Import>]s from 'fable-core' break depending on coreLib option used when compiling

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#626]
### Description
Fable-Compiler: 0.7.24
Fable-Core: 0.7.17

During compilation `fable-core` might really be equal to `fable-core/umd` or some other value depending on the `coreLib` option chosen for compilation.

Imports against `fable-core` must be written to agree with the `coreLib` setting or the imports fail at runtime.

Could Fable compiler automatically replace imports from `fable-core` with the correct path during compilation?

### Repro code
```fsharp
[<Import("getType", "fable-core/Symbol">]
let getType fullname:string = jsNative
```
Above doesn't work because my `coreLib=fable-core/umd`.

```fsharp
[<Import("getType", "fable-core/umd/Symbol">]
let getType fullname:string = jsNative
```
This works but would have to be changed if I compile with a different `coreLib` option.

*Happy New Year*

**Comment by alfonsogarciacaro** [comment]
Happy New Year to you too! 😄 :tada:

This should be possible though ideally you shouldn't access internal `fable-core` methods as these are subject to changes.

Right now you can do something similar by emitting AST, though it's a bit more cumbersome and I still need to document it:

```fsharp
open Fable.AST
open Fable.AST.Fable.Util

type Emitter() =
    member x.CoreImport(_com: Fable.ICompiler, i: Fable.ApplyInfo, path: string) =
        let meth =
            match path.Split('/') with
            | [|moduleName|] -> makeCoreRef moduleName None
            | [|moduleName; memberName|] -> makeCoreRef moduleName (Some memberName)
        Fable.Apply(meth, i.args, Fable.ApplyMeth, i.returnType, i.range)

[<Emit(typeof<Emitter>, "CoreImport", "Symbol/getType")>]
let getType (fullname: string): string = jsNative
```

**Comment by michaelsg** [comment]
Well, I definitely will look into Emit.
I wasn't crazy about pulling in that fn from fable-core, but there doesn't seem to be any access to the metadata information.
* get type by full name
* get field/case/type information about a type

Or did I miss it?

**Comment by alfonsogarciacaro** [comment]
Yes, you're right. The reflection API is not implemented yet. I'm still considering how to do it. I think it's probably better not to just add replacements for the F#/.NET reflection methods (as the information available in Fable is much more limited) and create a specific and easy-to-use Fable reflection API instead.

If you have any suggestion on how this API should look like, linking it to the actual `fable-core` methods wouldn't be too difficult.
