### ISSUE TITLE
Suggestion - Visual Studio compatible error messages.

### ISSUE THREAD

**Issue by rhozee** [fable-compiler/Fable#629]
Unless there's already a method to the error messages produced by the Fable compiler, it would be great if they were formatted such that Visual Studio would automatically pick them up to display in the errors list, allow double-clicking to go straight to the source line, etc.

The format is pretty simple:
filename(line,char): error <error-id-string>: text

**Comment by alfonsogarciacaro** [comment]
This is a nice suggestion, thank you! I implemented it in fable-compiler 0.7.27. Could you please give it a try and confirm if it's working?

Also, if you don't mind me asking, how do you set up the Fable custom build with VS? Is it compatible with `--watch` mode? And do you know if the same can be done with VS Code?
