### ISSUE TITLE
New UMD Header Breaks r.js Bundling

### ISSUE THREAD

**Issue by michaelsg** [fable-compiler/Fable#635]
In fable-core 0.7.17 the umd header on the fable-core/umd/*.js files changed.
It works for dynamic loading, but causes r.js to emit a malformed bundle.

Here is an example of the incorrect format produced by r.js when comsuming fable-core/umd/Symbol.js:
```javascript
define("fable-core/umd/Symbol", function(){});
(function (dependencies, factory) {
    if (typeof module === 'object' && typeof module.exports === 'object') {
        var v = factory(require, exports); if (v !== undefined) module.exports = v;
    }
    else if (typeof define === 'function' && define.amd) {
        define(dependencies, factory);
    }
})(["require", "exports"], function (require, exports) {
    "use strict";
      ...
```

Unfortunately, the fable-compiler that works with fable-core 0.7.16 produces incorrectly named overloads.

**Comment by alfonsogarciacaro** [comment]
Sorry, I'm not familiar with r.js. We recently changed `fable-core`'s build process. Before there were two steps: TypeScript and Babel compilation, and now the Babel compilation has been removed. But I haven't checked if the UMD outputs for TypeScript and Babel are different.

Do you know what's exactly the problem in the UMD headers of fable-core 0.7.17?

**Comment by michaelsg** [comment]
I have no idea. Just know I can't bundle my app nor deploy it now.

**Comment by alfonsogarciacaro** [comment]
If you want to bundle your app, can't you use Webpack 2 (`npm i webpack@beta`) or the embedded Rollup? I guess you'd get much better bundle results with ES2015 modules, as you'll only get the code you actually use not the whole module.
