### ISSUE TITLE
An implementation of the file or module 'Fable.Import.Meteor' has already been given

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#639]
### Description

I've got few files
```sh
.\index.fsx
.\common\imports\collections.fsx
.\client\imports\client_index.fsx
```

head of index.fsx
```fs
#r "node_modules/fable-core/Fable.Core.dll"
#load "common/imports/collections.fsx"
#load "client/imports/client_index.fsx"
```
client_index.fsx
```fs
#load "../../../../Feteor/lib/Fable.Import.Meteor.fs"
#load "../../common/imports/collections.fsx"
```
collection.fsx
```fs
#load "../../../../Feteor/lib/Fable.Import.Meteor.fs"
```

and when I run fable
I catch an error:
```sh
[ERROR] F# project contains errors:
An implementation of the file or module 'Fable.Import.Meteor' has already been given (L2,0-L217,99) (C:\Users\rmelnikov\Documents\dev\feteor\ExampleApplication\fsx_example\client\imports\../../../../Feteor/lib/Fable.Import.Meteor.fs)
Two modules named 'Fable.Import.Meteor.Email' occur in two parts of this assembly (L202,7-L202,12) (C:\Users\rmelnikov\Documents\dev\feteor\ExampleApplication\fsx_example\common\imports\../../../../Feteor/lib/Fable.Import.Meteor.fs)
```

### Expected and actual results

I think that I can load Fable.Import.Meteor.fs file anywhere in `fsx` files.

### Related information 

* fable-compiler version: 0.7.26
* fable-core version: 0.7.19
* Operating system: Windows 8.1 Enterprise

**Comment by Neftedollar** [comment]
I've remove `#load "../../../../Feteor/lib/Fable.Import.Meteor.fs"` from client_index.fsx and I've catch the same error. I think it's happen because `index.fsx` have 
```fs
#load "common/imports/collections.fsx"
#load "client/imports/client_index.fsx"
```

**Comment by alfonsogarciacaro** [comment]
This is caused by the F# compiler not by Fable itself so there's little I can do here :confused:

I thought diamond dependencies in F# scripts were already resolved (see https://github.com/Microsoft/visualfsharp/issues/1362) so I'm not sure what's the problem here. In any case when you start to have a more complicated structure is usually recommended to use an F# project (.fsproj) instead.

**Comment by Neftedollar** [comment]
Ok, thank you.
