### ISSUE TITLE
Image Smoothing Enabled is only supported for IE

### ISSUE THREAD

**Issue by paytonrules** [fable-compiler/Fable#644]
### Description

In CanvasRenderingContext2D (in Fable.Import.Browser) the msImageSmoothingEnabled property is supported, however imageSmoothingEnabled is not. imageSmoothingEnabled is the field supported by Chrome and is in the living standard. See here:

https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/imageSmoothingQuality#Browser_compatibility

### Repro code

    ctx.msImageSmoothingEnabled <- false
    ctx.imageSmoothingEnabled <- false

Both of the above should compile.

 ### Expected and actual results

See above. You may also want to consider webkitImageSmoothingEnabled and mozImageSmoothingEnabled as I haven't tested those browsers.

### Related information 

* fable-compiler version:
 0.7.17
* fable-core version:
0.7.6
* Operating system:
macOs

**Comment by paytonrules** [comment]
Quick follow up - using this: 

```
    ctx?imageSmoothingEnabled <- false
    ctx?mozImageSmoothingEnabled <- false
```

Will enable smoothing on Chrome and Firefox.

**Comment by alfonsogarciacaro** [comment]
Thanks for the report, I need to update the JS/Browser and Node bindings but I'd like to improve `ts2fable` first (I had to do a lot of manual editing before).

If possible, could you please send a PR to correct the binding? Anyways, it's ok to use dynamic programming in these cases as you noted.
