### ISSUE TITLE
Building elmish fails

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#651]
### Description

Trying to consolidate the dev dependencies for building elmish components I'm getting an exception:

> Error when invoking Emitter.Com (L34,8-L38,14): Exception has been thrown by the target of an invocation. (/home/travis/build/fable-compiler/fable-elmish/src/elmish-react/common.fs)
  at (wrapper managed-to-native) System.Reflection.MonoMethod:InternalInvoke (System.Reflection.MonoMethod,object,object[],System.Exception&)
  at System.Reflection.MonoMethod.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) [0x00038] in <8f2c484307284b51944a1a13a14c0266>:0 

https://travis-ci.org/fable-compiler/fable-elmish#L1142
https://ci.appveyor.com/project/et1975/fable-elmish

Edit: apparently Windows build fails too, I was looking at an older build log :/

### Repro code

et1975/fable-elmish

### Expected and actual results

Expect it to build.

### Related information 

* fable-compiler version: 0.7.30
* fable-core version: 0.7.22
* Operating system: OSX, Linux.

**Comment by alfonsogarciacaro** [comment]
Not sure if that's the problem but I had a similar issue with AST emitters in fable-react. The emitter must be in a different assembly so the runtime can load the compiled code. In fable-react I put the emitter code in a [shared **file]()** between the fable-react project and the [plugin](https://github.com/fable-compiler/fable-react/blob/master/src/plugins/Replacer.fsx) which is then passed in the [fableconfig options](https://github.com/fable-compiler/fable-react/blob/master/fableconfig.json). Could you please try if a similar approach works for you too?

**Comment by et1975** [comment]
With nested exception reported:

> Method 'Fable.AST.Fable.Util.makeNonGenTypeRef' not found.

and Windows build reporting the caller:

> at Fable.React.Internal.Emitter.Com(ICompiler _com, ApplyInfo i)

It's telling us that the method with that signature can not be found. Which suggests the React bindings need to be rebuilt with the latest compiler and core.

And this is the exception I'm getting when trying to recompile the bindings:

> fable-react/src/plugins/../react/Fable.React.Internal.fs(L25,40) : error FSHARP: The type 'Fable.Type' is not compatible with the type 'ICompiler'
fable-react/src/plugins/../react/Fable.React.Internal.fs(L27,41) : error FSHARP: This expression was expected to have type
    'Fable.Type -> Fable.Expr'    
but here has type
    'Fable.Expr'

**Comment by alfonsogarciacaro** [comment]
Damn! I need to be more careful with the exposed methods in Fable.Core.dll, sorry! Thanks a lot for catching and fixing this!
