### ISSUE TITLE
Minor optimization for string slices: detect half-open ranges

### ISSUE THREAD

**Issue by rmunn** [fable-compiler/Fable#653]
### Description

Now that #358 is fixed and F# string slicing compiles nicely to Javascript (`text.[3..5]` => `text.slice(3, 5 + 1)`), I'd like to request a couple of minor optimizations.

First, I was recently writing some code that did string slicing using Python-style half-open ranges (or `[a,b)` in mathematical notation). In F#, I have to write this as `text.[a .. b - 1]`, which Fable then compiles to `text.slice(a, b - 1 + 1)`. It would be nice if Fable could detect the presence of `- 1` in the F# AST and treat that as a special case, where instead of adding 1 as it normally does, it would simply strip the "minus 1" expression out of the AST, so that the generated Javascript could be `text.slice(a,b)`.

Second, as another special case (a "specialer" case, if you will) of string slicing, when the second index of the slice is an integer literal like 5, Fable currently generates the expression `5 + 1`. The Javascript JITter will probably optimize that into `6` before running the code, so this isn't a huge loss, but that's one bit of math that the Fable compiler could probably do instead: if the second index is an integer literal, then we might as well generate a single integer literal in the Javascript instead of an expression "some_literal + 1" that the Javascript JITter will have to resolve.

### Repro code

```fsharp
let text = "abcdef"
Browser.console.log(text.[2..4])  // Should print "cde"
```

### Expected and actual results

Actual Javascript output: `console.log("Text: ", text.slice(2, 4 + 1));`

Desired Javascript output: `console.log("Text: ", text.slice(2, 5));`

### Related information 

* fable-compiler version: 0.7.30
* fable-core version: 0.7.22
* Operating system: Linux Mint Debian Edition (based on Debian Jessie)

**Comment by alfonsogarciacaro** [comment]
Yes, constant folding is a good opportunity for optimising the final JS code, not only here but also in other places. One of the advantages of integrating with Babel pipeline is we can take advantage of already existing tools. I haven't checked myself but I think minifiers like `uglify-js` can already do this (maybe with the `evaluate` option), you may also want to check the [minify-constant-folding](https://babeljs.io/docs/plugins/minify-constant-folding/) Babel plugin.

**Comment by Pauan** [comment]
Unfortunately the `minify-constant-folding` plugin isn't smart enough to handle `b - 1 + 1`, but that may change in the future.

**Comment by alfonsogarciacaro** [comment]
This tool looks like capable of fixing issues like this :smile:

https://prepack.io/
