### ISSUE TITLE
Erased types cannot contain members or receive augmentations

### ISSUE THREAD

**Issue by Dessix** [fable-compiler/Fable#655]
### Description

Pojo types fail to compile with an error "Erased types cannot have members" when they have members. These should be treated as augmentations to an erased type, replacing their calls with those to a static object.

Erased types produce calls to an invalid property when invoking both members and augmented members, as seen in https://github.com/fable-compiler/Fable/issues/654.

### Repro code
```FSharp
//Declarations
module TypeModule =
    [<Pojo>] type A = { y: int };;
    [<Erase>] type B = { y: int };;
    [<Pojo>] type C = { y: int } member __.q = (__.y * 3).ToString();;
    [<Erase>] type D = { y: int } member __.q = (__.y * 4).ToString();;
    
open TypeModule

//Augmentations
type A with member self.z: string = self.y.ToString()
type B with member self.z: string = self.y.ToString()


[<EntryPoint>]
let main args =

    let a, b, c, d = { A.y = 3 }, { B.y = 4 }, { C.y = 5 }, { D.y = 7 }
    
    if a.z <> a.y.ToString() || a.z <> "3" then failwith "Should be able to call augmentation to [<Pojo>] type"
    if b.z <> b.y.ToString() || b.z <> "4" then failwith "Should be able to call augmentation to [<Erase>] type"
    if c.q <> (c.y * 3).ToString() || c.y <> 5 then failwith "Should be able to have and call members on [<Pojo>] type"
    if d.q <> (d.y * 4).ToString() || c.y <> 7 then failwith "Should be able to have and call members on [<Erase>] type"

    0
```

### Expected and actual results
Expected:
Code should compile successfully. Members of erased types should be supplanted to a new object, similarly to augmentations. Existing augmentations should be correctly utilized.

I'd provide the compiled result, but it ... Well... doesn't.

### Related information

* fable-compiler version: 0.7.30
* fable-core version: 0.7.22
* Operating system: Win10x64

**Comment by alfonsogarciacaro** [comment]
This is tricky. There are some problems to use members with `Pojo` types. I think they're not unsolvable, but the point is that `Pojo` types are designed to serve a specific purpose (interact in a safe type manner with JS libs that expect a plain JS object) and making them as capable as _normal_ types poses a burden on maintenance. Please check #558 where this has also been discussed.
