### ISSUE TITLE
How do call a jquery method that is a keyword in F#

### ISSUE THREAD

**Issue by lefthandedgoat** [fable-compiler/Fable#661]
### Description

Using the below code I want to call the `val()` method on an object returned from jquery call.
Won't work in what I think would be the most straightforward way because `val` is a keyword.

### Repro code

```
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import

let jq = importDefault<obj> "jquery"
let go = jq $ ("#go")
go ? click(fun _ ->   
  let selector = jq $ ("#selector")
  let value = selector?val() //invalid, tried ``val`` and ``val``()
  printfn "%A" value) |> ignore
```

### Expected and actual results

to generate js like

```
var value = selector.val();
```

### Related information 

* fable-compiler version: latest
* fable-core version: latest
* Operating system: windows 10

**Comment by alfonsogarciacaro** [comment]
Yeah, it's a bit annoying that F# doesn't let you use keywords for members or in cases like this. But for me `selector?``val``()` (or `selector?("val")()`) compiles just fine. What error do you get?

**Comment by lefthandedgoat** [comment]
```let value = selector?``val``()``` compiles to ```var value = selector.val(null);``` which blanks out the value.

The other option does the same.  I need it to call `val()` without an argument.

**Comment by alfonsogarciacaro** [comment]
I just noticed the same when reproducing your code. That's a different issue but in any case I fixed it and published a new version, can you please give it a try?

**Comment by lefthandedgoat** [comment]
Yep I got 0.7.34 and it is now generation ```val();``` when from ```?``val``()```

Many thanks!!!
