### ISSUE TITLE
Different binding behaviour

### ISSUE THREAD

**Issue by lefthandedgoat** [fable-compiler/Fable#664]
### Description

When I do a let binding of a property of a javascript object, it is type `('a -> obj)` but when you assign it to an existing value it is of type `obj`

### Repro code
```
open Fable.Core
open Fable.Core.JsInterop
open Fable.Import.Browser

let jq = importDefault<obj> "jquery"
let element = jq $ "div"
let position = element?offset()
let yada = position?top
//does not work here, error is:  The type '('a -> obj)' does not support the 'equality' constraint because it is a function type
let someyada = if yada = null then None else Some(yada)

//this works though
let mutable someyada2 : obj = null
someyada2 <- position?top
```

### Expected and actual results

I would expect `element?property` to return an `obj`

If its a known thing or normal, then I can work around it.

### Related information 

* fable-compiler version: 0.7.34
* fable-core version: 0.7.34 ? 
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Yeah, making they type returned by `?` be `'a->obj` was the only idea a could come up with (I'm open to suggestions) to remove the need of an operator like `$` for application and make things look more like dynamic programming.

But it's true this is annoying when assigning the result of dynamic access directly to a value. The best solution is to cast the result to your desired type (it can be `obj`):

```fsharp
// Actually here `box` has the same effect
// Both `unbox` and `box` are removed in generated JS code
let yada: obj = unbox position?top
```

For convenience, the `!!` operator is also available with the same effect as `unbox`:

```fsharp
let yada: obj = !!position?top
```

**Comment by lefthandedgoat** [comment]
!! works.  Thanks!
