### ISSUE TITLE
F# Record structural equality and comparison include fields added dynamically

### ISSUE THREAD

**Issue by valery-vitko** [fable-compiler/Fable#666]
### Description

Utils.ts function ``equalsRecords`` gets record object members with ``Object.getOwnPropertyNames`` thus comparing all fields even if they were not declared in F# Record but added dynamically. Same goes for ``compareRecords``. This leads to a confusing behavior sometimes when a UX framework, for example, adds a member to an object for its own purposes.

### Repro code

``` F#
[<Test>]
let ``Record equality ignores dynamic fields``() =
    let r1 = { a = 1; b = 2 }
    r1?c <- 1
    let r2 = { a = 1; b = 2 }
    r2?c <- 2
    equal true (r1 = r2)
```

### Expected and actual results

``equalsRecords`` and ``compareRecords`` uses ``[Symbol.reflection].properties`` to check fields declared in F# only.

### Related information 

* fable-compiler version: 0.7.37
* fable-core version: 0.7.25
* Operating system: Win10x64

**Comment by valery-vitko** [comment]
@alfonsogarciacaro, if you agree that this is a bug, I'd be happy to provide a pr.

**Comment by alfonsogarciacaro** [comment]
I think you're right. It'd be very nice to have a PR, thank you!
