### ISSUE TITLE
Proposition new helper JSInterop

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#667]
Currently, when we want to call a JavaScript function using dynamic programming we can use:

```fsharp
  /// Destructure and apply a tuple to an arbitrary value.
  /// E.g. `myFn $ (arg1, arg2)` in JS becomes `myFn(arg1, arg2)`
  let ($) (callee: obj) (args: obj): obj = jsNative
```

This is nice but when we want to call a function returning nothing we need to add an extra `|> ignore` . 

Could we add another helper having this signature:
```fsharp
  let ($) (callee: obj) (args: obj): unit= jsNative
```

I have no idea for the helper symbol ^^.

**Comment by alfonsogarciacaro** [comment]
The `!!` operator has been introduced to fix issues like this. It works very well in combination with `?`, with `$` you may need some extra brackets. It's the same as using `unbox` (or `ignore` in your case), but the operator syntax is less verbose:

```fsharp
let test(o: obj) =
    // We don't need to write `unbox<unit>`, the compiler
    // detects it, as we're discarding the value
    o?sideEffect(5,4) |> unbox

    // Same as line above
    !!o?sideEffect(5,4)

    !!(o $ "sideEffect")

    5 // return value
```

Would that work for you?

**Comment by MangelMaxime** [comment]
Oh, yes this would work for my case :)
Thanks you ^^
