### ISSUE TITLE
Need 4.5.2 support

### ISSUE THREAD

**Issue by caindy** [fable-compiler/Fable#683]
### Description

.NET 4.5 is out of support, and there is no equivalent for the .NET 4.5.2 Developer Pack [available](https://www.microsoft.com/net/targeting). I cannot build Fable or use it from npm without getting errors about missing assemblies. When building, the "Plugins" FAKE target fails when using FSharp.Compiler.Service due to assembly resolution errors.

### Workaround

I have a [simple hack on a fork](https://github.com/fable-compiler/Fable/compare/master...caindy:master) to make it work with 4.5.2. Unfortunately, this is not a fix since I hardcoded the path to the reference assemblies.

### Visual Studio 2015

I suspect installing Visual Studio 2015 (Community Edition) might resolve this issue, but that is undesirable for a number of reasons.

**Comment by alfonsogarciacaro** [comment]
Hi @caindy! There's a `FableCompilerNetcore` FAKE target that compiles Fable using netcore (you can find the `project.json` files in `src/netcore`, dotnet sdk preview 2 is necessary to compile them), but the plan is to merge both targets for the next major and compile Fable directly as a netcore app using the new .fsproj format :+1:
