### ISSUE TITLE
DateTime.ParseExact should be supported

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#693]
"export 'parseExact' was not found in 'fable-core/Date'

**Comment by alfonsogarciacaro** [comment]
Hmm, this is going to be tricky because right now we're defaulting to native JS parsing :/

**Comment by alfonsogarciacaro** [comment]
It's complicated to support this as the parsing operation in .NET is quite convoluted ([reference](https://referencesource.microsoft.com/#mscorlib/system/globalization/datetimeparse.cs,f1835935628e4a2f)) so I'm closing it. But please feel free to reopen if you find a library or another way to port that code to JS.
