### ISSUE TITLE
Flatten lambdas regression in narumi

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#704]
```
let test xs =
    let f = (+) >> id
    List.foldBack f xs 0

[<EntryPoint>]
let main argv =
    printfn "%A" (test [1;2;3;4])
    0
```
dotnet prints 10  -- correct
master prints 10  -- correct
narumi prints 0   -- incorrect

**Comment by alfonsogarciacaro** [comment]
Thanks for catching this! It was due to a sloppy replacement of the composition operators. Hopefully we don't find many issues like this because of the lambda flattening... or maybe we do and it helps improve the code generation as with the tailcall optimization ;)
