### ISSUE TITLE
Lazy lists regression in narumi

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#705]
This works in dotnet and master but not narumi:
```
[<EntryPoint>]
let main argv =
    let items = Lazy<_>(fun () -> ["a";"b";"c"])
    let search e = items.Value |> List.tryFind (fun m -> m = e)
    printfn "%A" (search "b")
    0
```
Runtime error:
```
\Projects\fable-test\src\fable-test\node_modules\fable-core\umd\Seq.js:676
       for (var i = 0, iter = xs[Symbol.iterator]();; i++) {
                                                 ^
TypeError: xs[Symbol.iterator] is not a function
```

**Comment by ncave** [comment]
Thanks!

**Comment by alfonsogarciacaro** [comment]
No problem! Thanks to you for catching the issues and providing code to reproduce. I assume they're surfacing when compiling FCS? I hope you don't have to hunt down too many ;)

**Comment by ncave** [comment]
@alfonsogarciacaro Yes, they're sometimes tough to narrow down and extract a minimal repro, but it's getting better. Hopefully when it's stable enough we can turn to performance tuning.
