### ISSUE TITLE
DU codegen optimization (narumi)

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#710]
Here is what the current DU codegen looks like:
```
    const $var2339 = matchValue.tag === 4 ? [0] : matchValue.tag === 1 ? [1] : matchValue.tag === 0 ? [2] : matchValue.tag === 3 ? [2] : [0];

    switch ($var2339[0]) {
      case 0: ...
```
Is there an opportunity here to not allocate arrays and just switch on tag with case fall-through?

**Comment by ncave** [comment]
It's unclear what to do if there are tupled parameters though.

**Comment by alfonsogarciacaro** [comment]
Maybe we can do it for DUs without data fields, although this can bring back the question whether we should optimize these DUs as integers, which I'm not very kind of as it would complicate reflection and method implementation.
