### ISSUE TITLE
U2 match codegen issue (narumi)

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#711]
[This U2 match](https://github.com/fable-compiler/Fable/blob/narumi/src/dotnet/Fable.Compiler/Fable2Babel.fs#L1020-L1022):
```
            transformModDecls com ctx declareNestedModMember (Some modIdent) entDecls
            |> List.map (function
                | U2.Case1 statement -> statement
                | U2.Case2 _ -> failwith "Unexpected export in nested module")
```
results in codegen that does not look right (will always throw):
```
    modDecls = (0, _List.map)(function (_arg1) {
      if (true) {
        throw new Error("Unexpected export in nested module");
      } else {
        return _arg1;
      }
    }, transformModDecls(...
```

**Comment by alfonsogarciacaro** [comment]
Hehe, this is what happens for using the same type (U2) with two different purposes in JS and .NET. Well, actually it **should** work (type testing in union erased types default to test the generic type). The problem seemed to be that the F# compiler had automatically generalized the `U2.Case2` argument so Fable didn't know what to test for. I'll fix that :+1:

**Comment by ncave** [comment]
@alfonsogarciacaro This was fixed, wasn't it? Can I close it?

**Comment by alfonsogarciacaro** [comment]
Yep, sorry. TBH, I'm not sure what caused this problem specifically but I think it was because in some cases one of the type parameters of U2 remained generic. Anyways, it's not happening now so I'll close the issue :) Thanks for the reminder!
