### ISSUE TITLE
COSMETICS: try to use x,y,z as lambda parameters when possible

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#713]
I'm compiling the Sudokusolver https://gist.github.com/alfonsogarciacaro/e9cfd5fbf18937cd132b4781ffc85ece with Fable v1.0.0-narumi, FCS v10.0.1, Babel v6.22.1 in the browser

![image](https://cloud.githubusercontent.com/assets/57396/22983037/2ad86a6a-f3a1-11e6-844b-affda013ed82.png)

**Comment by alfonsogarciacaro** [comment]
Those names are being generated by the F# compiler (variables auto generated by Fable are like `$var43`). It think it takes the actual name of the argument for F# functions, but auto generates it for methods from the BCL.

I'm not sure how difficult would be to change this. But given that it's not trivial and there're other priorities, I'm going to close it for now. We can revisit later :)

**Comment by forki** [comment]
so it should be done in compiler?

**Comment by forki** [comment]
Here is what dotpeek shows for

    open System
    open System.Collections.Generic

    let allUnique numbers =    
        let set = new HashSet<_>()
        numbers
        |> Seq.filter ((<>) 0)
        |> Seq.forall set.Add

as you can see it indeed has y and arg00. weird

    using Microsoft.FSharp.Collections;
    using Microsoft.FSharp.Core;
    using System;
    using System.Collections.Generic;
    
    [CompilationMapping(SourceConstructFlags.Module)]
    public static class Program
    {
      public static bool allUnique(IEnumerable<int> numbers)
      {
        return SeqModule.ForAll<int>((FSharpFunc<int, bool>) new Program.allUnique\u00408(new HashSet<int>()), SeqModule.Filter<int>((FSharpFunc<int, bool>) new Program.allUnique\u00407\u002D1(0), numbers));
      }
    
      [Serializable]
      internal class allUnique\u00408 : FSharpFunc<int, bool>
      {
        public override bool Invoke(int arg00)
        {
          // ISSUE: reference to a compiler-generated field
          return this.objectArg.Add(arg00);
        }
      }
    
      [Serializable]
      internal class allUnique\u00407\u002D1 : FSharpFunc<int, bool>
      {
        public override bool Invoke(int y)
        {
          // ISSUE: reference to a compiler-generated field
          return this.x != y;
        }
      }
    }

**Comment by alfonsogarciacaro** [comment]
Yeah, if you have something like this:

```fsharp
let add5 a e i o u = a + e + i + o + u

let test() =
    5 |> add5 1 2 3 4
```

The typed ast (that Fable tries to optimize) looks like:

```fsharp
let test() =
    (|>)
        5
        (let a = 1
         let e = 2
         let i = 3
         let o = 4
         fun u -> add5 a e i o u)
```

**Comment by forki** [comment]
that could actually work. 

![image](https://cloud.githubusercontent.com/assets/57396/22987267/748e144a-f3ae-11e6-834a-12e2305b682d.png)
