### ISSUE TITLE
Dockerfile

### ISSUE THREAD

**Issue by codec-abc** [fable-compiler/Fable#723]
It might be nice to provide a ready to use Dockerfile with Mono and NPM so users can use a container rapidly without having to install a lot of things in their computer. That way, testing Fable will always be one command away which should be quite cool especially since the Try Fable site is not currently working.

**Comment by alfonsogarciacaro** [comment]
It does work :wink: http://fable.io/repl.html

**Comment by codec-abc** [comment]
Indeed, but I saw an issue where it was written it was down and I found no link on the website so I thought it was still down. Is it normal that is not advertised?

**Comment by alfonsogarciacaro** [comment]
We uploaded the current REPL just around a week ago is still a bit experimental (it's done with the F# compiler compiled with Fable) so we're polishing it before adding the link to the main page :)

**Comment by alfonsogarciacaro** [comment]
Closing the issue for now, we may add a dockerfile in the future, especially when we move to netcore :+1:

**Comment by alfonsogarciacaro** [comment]
@xtuc has been kind enough to create a docker container for Fable, maybe you could give it a try @codec-abc?

**Comment by codec-abc** [comment]
Sorry for the late answer. I tested [this one](https://github.com/xtuc/Dockerfiles/blob/master/Fable/Dockerfile) (I think that the Docker image you are talking about right ?) on Windows 10.

Using those two commands 
```bash
docker build . -t fable
docker run -it -v p::\/home/fable-code fable
```

I was able to log in the container and build my (quite old) project [toy project](https://github.com/codec-abc/human-resource-machine-program-evaluator-fable-version) from the first try. So thanks, @alfonsogarciacaro  and @xtuc for the work. I don't know if you talk about it on the fable site but I think it worth a few words. By the way, with that we have a reliable way to run a sand-boxed fable compiler, you may wish to put some lights on the fable REPL.

**Comment by MangelMaxime** [comment]
Ping @mike-morr
