### ISSUE TITLE
Uncaught Exception in Async with do!

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#724]
### Description

In working with `Fable-Elmish`, I encountered an issue where `exceptions` thrown in `async` are not caught thereby making `Cmd.ofAsync` behave incorrectly.

### Repro code

    let task1 name = async {
      printfn "testing with %s" name
      if name = "fail" then
        failwith "Invalid access credentials"
      return "Ok" }

    let task2 name = async {
      printfn "testing with %s" name
      do! Async.Sleep 1000 //difference between task1 and task2
      if name = "fail" then
        failwith "Invalid access credentials"
      return "Ok" }

    let doWork name task = 
      printfn "doing work - %s" name
      async {
        let! a = task "work" |> Async.Catch
        printfn "work - %A" a
        let! b = task "fail" |> Async.Catch
        printfn "fail - %A" b
      } 
  
    doWork "task1" task1 |> Async.StartImmediate
    doWork "task2" task2 |> Async.StartImmediate

### Expected and actual results

Expected `task2` to work but it fails 

### Related information 

* fable-compiler version: 0.7.42
* fable-core version: 0.7.26
* Operating system: Windows 10

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for reporting this! I've released a new version of **fable-core** (0.7.28) to fix the issue, can you please check and reopen if you still have problems?

**Comment by rkosafo** [comment]
It work now. Thanks.
