### ISSUE TITLE
Error using ? with functions that use this

### ISSUE THREAD

**Issue by rkosafo** [fable-compiler/Fable#726]
### Description

In writing the f# definition for an imported library, I encountered an error with a scenario

Part of the structure of the import is as follows

- Menu
- Menu.Header
- Menu.Menu
- Menu.Item

The code is as below

    let Menu : Props -> ReactElement = importMember package
    let Header : HeaderProps -> ReactElement = unbox Menu?Header
    let SubMenu: MenuProps -> ReactElement = unbox Menu?Menu
    let Item: ItemProps -> ReactElement = unbox Menu?Item

The problem I encountered has to do with `Item`. Its code above translates to

    var Item = __exports.Item = function () {
      var clo1 = Menu.Item;
      return function (arg10) {
        return clo1(arg10);
      };
    }();

It took a while to figure it out but the translation above introduced a problem because it turned out that the definition for `MenuItem` is a `typescript` class. In JS, the constructor uses `this` which turns to be invalid in the above definition.

The way around it was to force Fable to not wrap the call in a function.

    let inline unbox' x = unbox<obj> x |> unbox
    ...

    let Menu : Props -> ReactElement = importMember package
    let Header : HeaderProps -> ReactElement = unbox' Menu?Header
    let SubMenu: MenuProps -> ReactElement = unbox' Menu?Menu
    let Item: ItemProps -> ReactElement = unbox' Menu?Item

which resulted in the javascript below

    var Menu = __exports.Menu = Menu_1;
    var Header_1 = __exports.Header = Menu.Header;
    var SubMenu = __exports.SubMenu = Menu.Menu;
    var Item = __exports.Item = Menu.Item;

### Expected and actual results

Code compiles just fine but got issues at runtime. React did not give any valid error message so was quite difficult to diagnose.

### Related information 

I'm not sure if it is a bug or a limitation. If it is a limitation, it will be nice if it is documented.

* fable-compiler version: 0.7.43
* fable-core version: 0.7.28
* Operating system: Windows 10

**Comment by rkosafo** [comment]
Repro

    let x = createObj ["a", box 45] //to represent some imported js stuff
    let test1 : string -> int = unbox x?a
    let test2 : string -> int = unbox <| unbox<obj> x?a

translates to

    export var x = {
      a: 45
    };
    export var test1 = function () {
      var clo1 = x.a;
      return function (arg10) {
        return clo1(arg10);
      };
    }();
    export var test2 = x.a;

The way `test1` is structured is what causes the problem.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed report @rkosafo. Sometimes the F# compiler is creating closures and I'm still not sure why :/ Thanks to the repro code it'll be easier to investigate to this. For now, I'd recommend for this cases to define a simple interface. This should solve the problem and hopefully make the code a bit more elegant:

```fsharp
type IMenu =
    [<Emit("$0($1)")>]
    abstract Invoke: Props -> ReactElement
    abstract Header: HeaderProps -> ReactElement
    abstract Menu: MenuProps -> ReactElement
    abstract Item: ItemProps -> ReactElement

let Menu: IMenu = importMember "package"
```

Note whe only need the `Emit` attribute if we want to apply directly the object as this is not allowed in F# (we could use it also to change the name of a method like `Menu` > `SubMenu`), for the other cases Fable will just pick the name of the interface method.

**Comment by rkosafo** [comment]
Noted. Will use the interface approach should I encounter the scenario again. Thanks.
