### ISSUE TITLE
Bootstrap Fable

### ISSUE THREAD

**Issue by lilred** [fable-compiler/Fable#727]
It would be nice if Fable could bootstrap itself. It would be lovely to use it as a REPL.

**Comment by ncave** [comment]
@lilred Something like [that](http://fable.io/repl)?

**Comment by lilred** [comment]
That's fantastic, can it be embedded?

**Comment by ncave** [comment]
@lilred there is some ongoing work in progress on that to bring additional functionality, but it's not there yet

**Comment by viebel** [comment]
@ncave any update on Bootstrapping Fable. 
I'd like to add F# support into [klipse](https://github.com/viebel/klipse), like I did for [clojure](https://book.klipse.tech/interactive_clojure%5Bscript%5D_code_snippets.html), [lua](http://blog.klipse.tech/lua/2017/03/19/blog-lua.html), [scheme](http://blog.klipse.tech/scheme/2016/09/11/scheme-tutorial-1.html), [ruby](http://blog.klipse.tech/ruby/2016/06/20/blog-ruby.html) etc...

**Comment by alfonsogarciacaro** [comment]
Hi @viebel, klipse looks awesome! It'd be very nice to add support to F#. For what I've seen in the README and the samples, with klipse code snippets can make reference to previous snippets. This would be more or less like F# interactive works, though at the moment the Fable REPL compiles each snippet as if it were a different program.

@ncave Do you think it would be possible to compile FSI to JS with Fable and embed it into the browser?

**Comment by ncave** [comment]
@viebel We're almost there with the REPL working on the new Fable 1.0 beta, so it's not going to be long.

@alfonsogarciacaro Having fsi-like incremental compilation is definitely possible, bit I'm not sure on the time line, as that is a hefty chunk of functionality to add. On the other hand, all the auto-complete support is already there, so the next step for the REPL should probably be to move from Ace to the Monaco editor (ionide-web) and support FSAC, tooltips, etc., that would be awesome.

**Comment by viebel** [comment]
That's great news @ncave 
As soon as you have something I can test, please ping me.

**Comment by alfonsogarciacaro** [comment]
I would love to see F#/Fable and klipse integration. I think this is already possible, we just need to repackage the Fable REPL into a standalone npm pure-JS package? Anyone from @fable-compiler/code-maintenance, @fable-compiler/infrastructure or @fable-compiler/community teams wants to help with that?

**Comment by viebel** [comment]
@alfonsogarciacaro Klipse now supports Ocaml. See http://blog.klipse.tech/ocaml/2017/10/05/blog-ocaml.html. If you guys provide a Fable standalone js compiler, I can add F# in Klipse.

**Comment by ncave** [comment]
@viebel This is awesome
++ @MangelMaxime

**Comment by MangelMaxime** [comment]
@ncave I already started the architecture rework of fable-repl repo.

I think after that we should have what we need for Kilpse. Because it should be simple to generate an npm package from it.

**Comment by alfonsogarciacaro** [comment]
Closing this in favor of #1651
