### ISSUE TITLE
Fable watch crashing sometime

### ISSUE THREAD

**Issue by codec-abc** [fable-compiler/Fable#734]
Hi,

In my current setup I use `fable -w` to auto-compile on changes.  Sometime the compilation fails and cause fable to stop. It seems related to files permission (locking ?) issue.

This is what I got when it crash :
```bash
events.js:160
      throw er; // Unhandled 'error' event
      ^

Error: EPERM: operation not permitted, stat 'P:\myproject\.git\index.lock'
    at Error (native)
```

### Expected and actual results
No crash or auto-restart on failure.

### Related information 

* fable-compiler version: 0.7.43
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Closing as now Fable relies on Webpack watch which is more stable.
