### ISSUE TITLE
ts2fable following exports from index.d.ts eg in office-fabric-ui-react

### ISSUE THREAD

**Issue by richardjharding** [fable-compiler/Fable#740]
### Description

I'm trying to generate interfaces for the [office-fabric-ui-react component](https://dev.office.com/fabric#react)s using the ts2fable tool

As an example the type definitions for the button are defined in multiple files and then an index.d.ts is included eg

``
export * from './BaseButton';

export * from './Button.Props';

export * from './Button';

export * from './CommandButton/CommandButton';

export * from './CompoundButton/CompoundButton';

export * from './DefaultButton/DefaultButton';

export * from './PrimaryButton/PrimaryButton';

export * from './IconButton/IconButton';
``

When ts2fable is run it doesn't "follow" the exports to read the definitions in the other files - should it be able to do that

What would I need to do to add that capability if feasible?

**Comment by alfonsogarciacaro** [comment]
Hmm, this is tricky, I need to think about it. Do you have an idea of the F# code you'd like to be generated? The problem is the F# type checker cannot follow import statements the same way as the Typescript compiler does, so ts2fable will have to copy all the imported methods into a single (and potentially very big) file. Is that what you're aiming for?

**Comment by richardjharding** [comment]
I guess the options are to replicate the file structure of the js package (or its typings) that you want to convert - but that could lead to problems with file ordering in F#

One big file wouldn't be so bad (assuming you wouldn't need to edit often)

I guess many files wouldn't be so bad as you may only want to import a subset of the definitions (eg button, datepicker in my office fabric example) and therefore take advantage of possible tree shaking when bundling

I think this is going to be an issue for any large library you may want to use with fable - if it needs hand editing keeping it in sync with releases of the js/ts lib will be a chore

**Comment by mizzle-mo** [comment]
@alfonsogarciacaro Can this issue be moved to ts2fable repo, so we can track it easier?

**Comment by alfonsogarciacaro** [comment]
@mizzle-mo Sure!
