### ISSUE TITLE
Javascript output is referencing fable-imports and adding them to outDir

### ISSUE THREAD

**Issue by Korbin73** [fable-compiler/Fable#742]
### Description
When compiling to js the output creates arbitrary directories including fable import files.
Please provide a succinct description of your issue.

### Repro code
1. Created a new vscode extension project
2. Added fable-import-vscode
3. Created fsx file
4. Compiled to js
js output includes the import files:
![fable_screenshot](https://cloud.githubusercontent.com/assets/885138/23576719/5c39ed56-006a-11e7-979b-4234e9c124c9.png)

Please provide the F# code to reproduce the problem.
Ideally, it should be possible to easily turn this code into a unit test.

### Expected and actual results
I expected the import files to not be included in the output and the files that consume the import files should not have a import reference to them.
Please provide the expected and actual results.
I recently update my project to the latest fable compiler and noticed this, but I could not find anything in the latest changes that would indicate the compilation behavior changed. I'm sure I'm missing something simple...
### Related information 

* fable-compiler version: 0.7.48
* fable-core version: 0.7.15
* Operating system: Ubuntu 16.04

**Comment by alfonsogarciacaro** [comment]
Sorry for the late, late response. Unfortunately this is a problem of Fable 0.7 but it should have no practical consequences as the extra file is not being referenced. In Fable 1.0 this problem should not happen thanks to default bundling :+1:
