### ISSUE TITLE
fable --help doesn't work

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#744]
### Description

`fable --help` doesn't print Fables help page.

### Repro code

``` sh
$ fable --help
```

### Expected and actual results

`fable --help` should print the help page. Instead, Fable tries to build the project. v0.7.45 is the last version which behaves like expected.

### Related information 

* fable-compiler version: > 0.7.45
* Operating system: Windows 7

**Comment by alfonsogarciacaro** [comment]
Hi @inosik! Thanks a lot for pointing this out. It seems that the new command-line-args version translates empty CLI flags as `null` values instead of `true` as before, but I didn't notice. This should be fixed, can you please check with fable-compiler 0.7.49?

**Comment by inosik** [comment]
Fixed in 0.7.49. Thanks! :heart:
