### ISSUE TITLE
Cannot resolve trait error

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#750]
### Description

error FABLE: Cannot resolve trait call op_HatDot

Everything worked when `Action` was specific for `RecordB`, when I made it generic, it started throwing that.

### Repro code

Doesn't work: http://www.fssnip.net/7Su
Work: http://www.fssnip.net/7Sv

### Expected and actual results

Should work

### Related information 

* fable-compiler version: 0.7.50
* fable-core version: 0.7.29
* fable-arch version: 0.10.1
* fable-aether version: 0.1.1
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
@FrankBro I've pushed a new Fable 1.0 beta version (1.0.0-narumi-905) to fix the problem, you should be able to download it by running `dotnet restore --no-cache`, can you please give it a try? You also need to update the fable-core and fable-loader npm packages.

Crossing fingers :)

**Comment by MangelMaxime** [comment]
Hum, this is a really great news. I will test it also :)

**Comment by FrankBro** [comment]
For me this looks fixed. It's compiling on my side. I'll wait for @MangelMaxime to confirm too before closing.

**Comment by MangelMaxime** [comment]
The issue seems fixed on my side too.
