### ISSUE TITLE
[narumi] Records signature codegen regression

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#754]
There seems to be a codegen regression for records with signatures, this used to work before:

test.fsi
```
module Test

[<Sealed>]
type TRec =
    static member Create : string * string -> TRec
```
test.fs
```
module Test

type TRec =
    { a: string; b: string }
    static member Create (a, b) = { a=a; b=b }
```
Program.fs
```
module Program
open Test

[<EntryPoint>]
let main argv =
    let t = TRec.Create("1", "2")
    printfn "%A" t
    0
```
project.fsproj
```
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>netcoreapp1.0</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <!--<Compile Include="test.fsi" />--> <!-- if you uncomment this it will stop working -->
    <Compile Include="test.fs" />
    <Compile Include="Program.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <PackageReference Include="FSharp.Core" Version="4.1.*" />
  </ItemGroup>
</Project>
```
Here is what gets generated without the signature file (correct):
```
var TRec = function () {
  function TRec(a, b) {
    _classCallCheck(this, TRec);
    this.a = a;
    this.b = b;
  }
```
Here is what gets generated with the signature file (incorrect):
```
var TRec = function () {
  function TRec() {
    _classCallCheck(this, TRec);
  }
```

**Comment by alfonsogarciacaro** [comment]
Hi @ncave. I'm still concerned about the .fsi files, particularly because there is no progress with https://github.com/fsharp/FSharp.Compiler.Service/issues/676. The easiest solution would be if Fable just ignore .fsi files, but you said they're necessary sometimes, right? Do you have an example?

**Comment by ncave** [comment]
@alfonsogarciacaro The thing is, this was working fine fairly recently in narumi.
The .fsi signature files are used to define access (visibility), so removing them would require reworking pretty much every code base that uses signature files. As much as I would like for the [FCS/#676](https://github.com/fsharp/FSharp.Compiler.Service/issues/676) to be fixed, it was more or less the only issue with signature files before this one.

**Comment by alfonsogarciacaro** [comment]
I've committed a fix, could you please check? Incidentally, I may have found a workaround for [FCS/#676](https://github.com/fsharp/FSharp.Compiler.Service/issues/676), I need to check...
