### ISSUE TITLE
Two .fsproj crashes dotnet fable

### ISSUE THREAD

**Issue by davidtme** [fable-compiler/Fable#757]
### Description

Having 2 .fsproj files in a folder crashes the fable compiler

### Repro code

```
mkdir myfableapp
cd myfableapp
dotnet new fable
dotnet restore
npm install
copy .\myfableapp.fsproj .\myfableapp2.fsproj
dotnet fable npm-run build
```

**Comment by alfonsogarciacaro** [comment]
@davidtme Sorry, I forgot to check this 😅 Is it still happening? Is there any message error?

**Comment by davidtme** [comment]
@alfonsogarciacaro It's still happening.  The error message is:

	C:\Dev\myfableapp>dotnet fable npm-run build

	Unhandled Exception: System.InvalidOperationException: Specify which project fil
	e to use because this 'C:\Dev\myfableapp' contains more than one project file.
	   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProjPath(String projec
	tDirectory)
	   at Microsoft.DotNet.Cli.Utils.ProjectFactory.GetMSBuildProj(String projectDir
	ectory, NuGetFramework framework, String configuration, String outputPath)
	   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.ResolveFromProjectT
	ools(CommandResolverArguments commandResolverArguments)
	   at Microsoft.DotNet.Cli.Utils.ProjectToolsCommandResolver.Resolve(CommandReso
	lverArguments commandResolverArguments)
	   at Microsoft.DotNet.Cli.Utils.CompositeCommandResolver.Resolve(CommandResolve
	rArguments commandResolverArguments)
	   at Microsoft.DotNet.Cli.Utils.CommandResolver.TryResolveCommandSpec(ICommandR
	esolverPolicy commandResolverPolicy, String commandName, IEnumerable`1 args, NuG
	etFramework framework, String configuration, String outputPath, String applicati
	onName)
	   at Microsoft.DotNet.Cli.Utils.Command.Create(ICommandResolverPolicy commandRe
	solverPolicy, String commandName, IEnumerable`1 args, NuGetFramework framework,
	String configuration, String outputPath, String applicationName)
	   at Microsoft.DotNet.Cli.Utils.Command.Create(String commandName, IEnumerable`
	1 args, NuGetFramework framework, String configuration, String outputPath, Strin
	g applicationName)
	   at Microsoft.DotNet.Cli.Program.ProcessArgs(String[] args, ITelemetry telemet
	ryClient)
	   at Microsoft.DotNet.Cli.Program.Main(String[] args)

**Comment by alfonsogarciacaro** [comment]
Ah, right. Thanks for the clarification. Then unfortunately there is little we can do here as this is coming from the dotnet SDK. It actually makes sense, you're invoking a CLI tool but the dotnet SDK doesn't know which project it belongs too, which may lead to version conflicts. A possible solution for cases where you have several projects and want to use a common `dotnet-fable` instance for all of them is to create a `.proj` (note is not an .fsproj) file in a common parent directory just for the purpose of downloading the CLI tool as in [this example](https://github.com/fable-compiler/fable-electron/blob/737baef8a47abe4f82f8ce25691fb53b6484364e/samples/material-ui/Fable.proj).
