### ISSUE TITLE
Adding rollup stops generating intermediate javascript

### ISSUE THREAD

**Issue by ericharding** [fable-compiler/Fable#766]
### Description

I'm probably missing something obvious but I can't seem to get rollup working with fable 0.7.50.  

If I use this simple fableconfig.json everything works great.
```
{
   "projFile": "PomelloExport/PomelloExport.fsproj",
   "sourceMaps": true,
   "outDir": "out",
   "verbose": true,
   "watch": true
}
```

As soon as I add a rollup section the fable console output indicates that it is updating the output files but it just doesn't.

```
{
   "projFile": "PomelloExport/PomelloExport.fsproj",
   "sourceMaps": true,
   "outDir": "out",
   "verbose": true,
   "rollup": {
    "entry": "./out/Main.js",
    "entry": "./out/Trello.js",
    "dest": "./out/bundle.js",
    "format": "cjs"
   },
   "watch": true
}
```

### Expected and actual results

My project has 2 files "Main.js" and "Trello.js" when the js files are touched I expected Main.js and Trello.js to get updated followed by bundle.js.  What actually happens is bundle.js is touched but not the inputs to it.

### Related information 

* fable-compiler version: 0.7.50
* fable-core version: 0.7.29
* Operating system: Windows 10

Console output from run:

c:\hg\PomelloExport>node node_modules\fable-compiler
fable-compiler 0.7.50: Start compilation...

WORKING DIR: c:\hg\PomelloExport
PROJECT FILE: PomelloExport/PomelloExport.fsproj
OUTPUT DIR: out

FABLE COMMAND: cmd /S /C "c:\users\eric\documents\hg\PomelloExport\node_modules\fable-compiler\bin\Fable.Client.Node.exe --projFile PomelloExport
/PomelloExport.fsproj --outDir out --rollup true --watch true --module iife"

F# COMPILER OPTIONS:
--simpleresolution
--noframework
--optimize-
--warn:3
--fullpaths
--flaterrors
--target:library
--define:FABLE_COMPILER
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\mscorlib.dll
-r:C:\Windows\Microsoft.NET\assembly\GAC_MSIL\System.Runtime\v4.0_4.0.0.0__b03f5f7f11d50a3a\System.Runtime.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Core.dll
-r:C:\Program Files (x86)\Reference Assemblies\Microsoft\Framework\.NETFramework\v4.5.1\System.Numerics.dll
-r:c:\users\eric\documents\hg\PomelloExport\node_modules\fable-compiler\bin\FSharp.Core.dll
-r:c:\hg\PomelloExport\PomelloExport\../packages/System.ValueTuple.4.3.0/lib/netstandard1.0/System.ValueTuple.dll

F# SOURCE FILES:
c:\hg\PomelloExport\PomelloExport\Trello.fs
c:\hg\PomelloExport\PomelloExport\Main.fs

JS TARGET FILES:
c:\hg\PomelloExport\out\Main.js
c:\hg\PomelloExport\out\Trello.js

F# compilation complete. Starting Fable...
Compiled Trello.js at 10:40:21 PM
Compiled Main.js at 10:40:21 PM
Bundling...
Bundled out\bundle.js at 10:40:21 PM
Watching c:\hg\PomelloExport\PomelloExport
Press Enter to terminate process.
change: c:\hg\PomelloExport\PomelloExport\Main.fs at 10:41:18 PM
F# compilation complete. Starting Fable...
Compiled Main.js at 10:41:18 PM
Bundling...
Bundled out\bundle.js at 10:41:18 PM

Resulting timestamps in out\
03/23/2017  10:40 PM            22,740 bundle.js
03/23/2017  10:40 PM            80,259 bundle.js.map
03/23/2017  10:26 PM             2,108 Main.js
03/23/2017  10:26 PM               979 Main.js.map
03/23/2017  10:25 PM             6,617 Trello.js
03/23/2017  10:25 PM             4,823 Trello.js.map

If I comment out the rollup section in fableconfig.json Main.js and Trello.js are updated.  

### I'm happy to provide a repo you can pull and build from if it turns out I'm not just missing some key flag

**Comment by alfonsogarciacaro** [comment]
I think [Rollup doesn't support multiple entries](https://github.com/rollup/rollup/wiki/JavaScript-API#entry). In any case, you shouldn't need to set `entry`, when you add `rollup` in fableconfig, Fable creates the JS files in memory and uses Rollup to create the bundle before writing anything to disk.

On the other hand in Fable 1.0 beta we're discarding Rollup for the moment and [improving integration with Webpack](http://fable.io/blog/Introducing-1-0-beta.html#Integration-with-Webpack), which does support multiple entries in case you need them, maybe you could give it a try?

**Comment by ericharding** [comment]
That works. Removing the entries from the rollup makes it generate the right bundle.  I don't really need the intermediate outputs- fable is even more slick thank I thought it was.

I'll definitely check out the improved integration with webpack.  It looks like a promising way of streamlining the config for a new fable project. Thanks.
