### ISSUE TITLE
Fetching fable templates doesn't work as expected in fish shell

### ISSUE THREAD

**Issue by slifin** [fable-compiler/Fable#768]
### Description

```
~/C/myfableapp  dotnet new -i Fable.Template::*
No matches for wildcard 'Fable.Template::*'.  (Tip: empty matches are allowed in 'set', 'count', 'for'.)
fish: dotnet new -i Fable.Template::*
```

A work around is to step into bash from fish and then execute the command there seems to work ok

**Comment by alfonsogarciacaro** [comment]
Hi @slifin! Could you please report the issue in this repo? Thanks! https://github.com/dotnet/templating

**Comment by slifin** [comment]
I've reported it here: https://github.com/dotnet/templating/issues/482
