### ISSUE TITLE
[narumi] Published fable-plugins-nunit@next package has multiple dlls where one doesn't work

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable#775]
### Description

When you install the `fable-plugins-nunit` package there are currently multiple Fable.Plugins.NUnit.dll's distributed. One under the root folder for the package and others under bin/obj. 

When you use the one in the root of the package, the fable server throws an exception. After restarting the sever and changing webpack.config.js to use one from the package's `bin\Release\netstandard1.6` folder, everything worked and I could run tests via webpack + mocha.

### Expected and actual results

Expected that the root dll distributed with npm package would work. Instead fable server shows the following when it is being used:

`Cannot load plugin D:/Development/fablev1testapp/client/node_modules/fable-plugins-nunit/Fable.Plugins.NUnit.dll: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.`

Actually needed to use one from the build folder.

### Related information 

* fable-plugins-nunit version: 1.0.0-narumi-1
* fable-compiler version: 1.0.0-narumi-904
* fable-core version: 1.0.0-narumi-15 (npm) | 1.0.0-narumi-904 (nuget)
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Ups, you're right. Sorry! I republished the plugin, could you please try again? I removed the bin and obj folders and now the .dll in the root should work.

**Comment by johlrich** [comment]
👍  all working now with root folder's dll. Thanks
