### ISSUE TITLE
Seq.collect on Option seq seq stops on first None value

### ISSUE THREAD

**Issue by devcrafting** [fable-compiler/Fable#776]
### Description

When using Seq.collect on (Option seq seq), it stops collection on first None value, because it transpiles to null and causing weird behavior in concat function https://github.com/fable-compiler/Fable/blob/master/src/fable/Fable.Core/ts/Seq.ts, line 114 to 122
line 115, output is null (since Option.None is null), then line 122, it returns null => up in the stack, the unfold function receive null (line 719), then it stops...

### Repro code

let optionSeqSeq = [[Some 2; Some 4]; [Some 1; Some 3]]
let collect = optionSeqSeq |> Seq.collect id
printfn "collected nb = %i" (Seq.length collect) // output "collected nb = 4"

let optionSeqSeq = [[None; None]; [Some 1; Some 3]]
let collect = optionSeqSeq |> Seq.collect id
printfn "collected nb = %i" (Seq.length collect) // output "collected nb = 0"

let optionSeqSeq = [[Some 1; Some 3]; [None; None]]
let collect = optionSeqSeq |> Seq.collect id
printfn "collected nb = %i" (Seq.length collect) // output "collected nb = 2"

### Expected and actual results

I should always collect the 4 values (i.e always display "collected nb = 4")

### Related information 

* fable-compiler version: 0.7.50
* fable-core version: 0.7.29
* Operating system: Windows 10

**Comment by Zaid-Ajaj** [comment]
Nice catch @devcrafting the following also fails:

```fsharp
let concat xss = seq {
  for xs in xss do
    for x in xs do
      yield x
} 

[[Some 1; Some 3]; [None; None]]
|> concat 
|> Seq.length
|> printfn "length = %i" 
```
