### ISSUE TITLE
Q: chain of Fable npmjs published packages (A->B->C) 

### ISSUE THREAD

**Issue by davidpodhola** [fable-compiler/Fable#777]
Another more question-less issue.

### Description

I have 2 Fable `npmjs` published packages `A` and `B`. Package `B` uses package `A` through `package.json`, DLL from package `A` is referenced in `B.fsproj`.
I have Fable application `C` consuming package `B` in the same manner (`B` referenced in `package.json`, DLL from `B` referenced in `C.fsproj`)

### Repro code

(not yet)

### Expected and actual results

In package `B` files from package `A` are referenced using the relative path like `"../node_packages/A/a.js"`. These files are then not available on this path when running `webpack` on `C`.

I would expect to use the path `"A/a.js"`.

Please advise. If this is actually a bug, I can provide a simplified repro code. I will of course also happily accept any explanation what I am doing wrong :-)

**Comment by alfonsogarciacaro** [comment]
The way to distribute Fable packages is changing in Fable 1.0. Now Fable libraries will distribute F# sources directly and it's up to the final user to build a JS app with them and distribute it if necessary (in Fable 0.7 a .fablemap file is used to relate the .dll and the precompiled JS files but this will be deprecated soon).

If I understand you correctly, you want to distribute two JS packages (say A and B) compiled with Fable and distribute them through npm, but you want to keep B dependencies on A working in JS as well. At the moment there's no mechanism to automatically translate F# dependencies across projects into npm dependencies, the default in Fable 1.0 is to bundle all files from every project into a single JS file.

I'd recommend compiling and bundling A as a [JS library](https://webpack.js.org/concepts/output/#output-library) (in this case the last file in project A will determine which methods are exposed by the JS library). Then you can import it in project B as if it were a normal JS package, the only thing is you'll have to define the interface in project B.

```fsharp
// Last file in project A
// In package.json you must set the compiled bundle.js as the main file
let add x y = x + y

// Project B
type A =
    abstract add: int -> int -> int

let myLib: A = import "*" "A"

myLib.add 5 4
```
