### ISSUE TITLE
Compiled unicode string

### ISSUE THREAD

**Issue by whitglint** [fable-compiler/Fable#784]
### Description

```
let aaa = "你好"
```
compiles to
```
export var aaa = "\u4F60\u597D";
```
How to compile to
```
export var aaa = "你好";
```
?

### Expected and actual results

Expected result:
```
export var aaa = "你好";
```
Actual result:
```
export var aaa = "\u4F60\u597D";
```

### Related information 

* fable-compiler version: 0.7.50
* Operating system: Ubuntu Linux 16.04

**Comment by alfonsogarciacaro** [comment]
This is has been really tricky to fix, but I think I got it. Could you please update the `fable-loader` npm package to 1.0.0-narumi-908 and try again?

**Comment by whitglint** [comment]
The output is correct!
