### ISSUE TITLE
Add README to fable-loader

### ISSUE THREAD

**Issue by haf** [fable-compiler/Fable#786]
At https://www.npmjs.com/package/fable-loader there's the loader that makes it possible to add F# to JS projects (for real development, imo) – but where are the docs? The readme just states to look at fable.io, but the only mention I find of `webpack` there is the "if not using webpack ..." string.

Webpack is used whenever you have a modern JS project, so the JS story with Fable and Webpack is a very important one to get right to get uptake.

 - [ ] fable-loader needs a README
 - [ ] The project link on npm links to the main repo (this one) but there's no mention of the loaded in this project's readme
 - [ ] I can't find the loader by spending a few minutes clicking around in the file browser – make it discoverable.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for this @haf. I released Fable 1.0 beta mainly to get feedback from power users so we're still short on documentation. But these points have to be addressed indeed :+1:

**Comment by alfonsogarciacaro** [comment]
Someone from @fable-compiler/documentation team willing to write fable-loader's README? [rollup-plugin-fable README](https://github.com/jgrund/Fable/blob/dba91bab7bb438dce8a0b5c46b05d0271c202321/src/typescript/rollup-plugin-fable/README.md) can be used as reference.

**Comment by alfonsogarciacaro** [comment]
This is done now 😄
