### ISSUE TITLE
.NET core version of JsonConverter

### ISSUE THREAD

**Issue by jmmk** [fable-compiler/Fable#794]
### Description

Fable.JsonConverter package has not yet been released with the new Fable beta

**Comment by alfonsogarciacaro** [comment]
You're right @jmmk. I forgot to publish it, sorry! I've published Fable.JsonConverter 1.0.0-narumi-908 for netstandard1.6, could you please check it works? ...in a few minutes ;)

**Comment by jmmk** [comment]
- Installed with Paket
- `dotnet restore` works with .net core app
- Serialize and Deserialize from Fable to server

The type I'm working with is pretty simple, just a record with `string`, `int`, and `string option` fields so it's not a comprehensive test, but it works for me.

Thanks @alfonsogarciacaro
