### ISSUE TITLE
Pass current instance as first argument to imported extension methods

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#797]
### Description
When writing a binding (function import) as an extension method, the current instance (`self`) should be *created* and *passed* as first argument to the imported function. 

for example, here I am just importing an existing function `toUniversalTime` from `fable-core/Date`:
```fsharp
open System
open Fable
open Fable.Core
open Fable.Core.JsInterop

[<AutoOpen>]
module Extensions = 
  type System.DateTime with
    [<Import("toUniversalTime", "fable-core/Date")>]
    member self.ToVerySpecialUniversalTime() : DateTime = jsNative

let x = DateTime(2015, 1, 1).ToVerySpecialUniversalTime()
```

See [sample here](http://fable.io/repl#?code=open%20System%0Aopen%20Fable%0Aopen%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0A%5B%3CAutoOpen%3E%5D%0Amodule%20Extensions%20%3D%20%0A%20%20type%20System.DateTime%20with%0A%20%20%20%20%5B%3CImport(%22toUniversalTime%22%2C%20%22fable-core%2FDate%22)%3E%5D%0A%20%20%20%20member%20self.ToVerySpecialUniversalTime()%20%3A%20DateTime%20%3D%20jsNative%0A%0Alet%20x%20%3D%20DateTime(2015%2C%201%2C%201).ToVerySpecialUniversalTime()%0A) 

### Why
Extension methods can be overloaded, perfect for importing foreign functions with different parameters instead of using U1, U2 ....etc.

I am not sure how the compiled code should look like, in the compilation in seems that Babel has detected that `DateTime_ToVerySpecialUniversalTime` is just the same as `toUniversalTime` and reduced the call to `toUniversalTime` (see code below). That doesn't matter as long as the instance of of the `DateTime` is created and passes as first argument which is not the case:

### Actual
```javascript
import { toUniversalTime } from "fable-core/Date";

export const Extensions = function (__exports) {
  const DateTime_ToVerySpecialUniversalTime = __exports["DateTime.ToVerySpecialUniversalTime"] = toUniversalTime;
  return __exports;
}({});

// Missing definition of DateTime(2015, 1, 1)
export const x = toUniversalTime();
```

### Expected
```javascript
import { toUniversalTime } from "fable-core/Date";
import { create } from "fable-core/Date";

export const Extensions = function (__exports) {
  const DateTime_ToVerySpecialUniversalTime = __exports["DateTime.ToVerySpecialUniversalTime"] = toUniversalTime;
  return __exports;
}({});

export const x = toUniversalTime(create(2015, 1, 1));
// or 
// export const x = Extensions["DateTime.ToVerySpecialUniversalTime"](create(2015, 1, 1))
```
Notice that creation of `Date(2015, 1, 1)` is skipped in the actual compiled code. If I define the type seperately, it is created but not passed to the extension method:
```fsharp
let x = DateTime(2015, 1, 1)
let y = x.ToVerySpecialUniversalTime()
```
compiles to:
```javascript
export const x = create(2015, 1, 1);
export const y = toUniversalTime();
```
It should be:
```javascript
export const x = create(2015, 1, 1);
export const y = toUniversalTime(x);
```

**Comment by alfonsogarciacaro** [comment]
Sorry for replying late, @Zaid-Ajaj. I didn't think of combining extension methods and the `Import` attribute, clever! At the moment Fable binds the extension methods to the caller (e.g. `Extensions["DateTime.ToVerySpecialUniversalTime"].bind(create(2015, 1, 1))`) so it replaces `this` references within the extension method body.

I'll try to have a look at this. If you want to give it a shot, you can try checking for the `Import` attribute in the [ExtensionMember active pattern](https://github.com/fable-compiler/Fable/blob/7c49f2503479080aa5defe920e51af3618d96ec8/src/dotnet/Fable.Compiler/FSharp2Fable.Util.fs#L1299-L1315) and pass the `callee` as first argument in that case. [A similar combination happens with `Import` and `Emit` attributes](https://github.com/fable-compiler/Fable/blob/7c49f2503479080aa5defe920e51af3618d96ec8/src/dotnet/Fable.Compiler/FSharp2Fable.Util.fs#L1228-L1230) (though in opposite order), so you can use it as reference.

**Comment by alfonsogarciacaro** [comment]
Also, you can use src/tools/QuickTest.fsx for quick testing :)

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro I will take a look at it :+1: 
An easy workaround was just to define the foreign function somewhere other than the extension method and call it from the extension method:
```fsharp
module ExternalFuncs = 
  let toSpecialUniversalTime (time: obj) = import "toUniversalTime" "fable-core/Date"

[<AutoOpen>]
module Extensions = 
  type System.DateTime with
    member self.ToVerySpecialUniversalTime() : DateTime = ExternalFuncs.toSpecialUniversalTime self

let x = DateTime(2015, 1, 1).ToVerySpecialUniversalTime()
```

[Here is a sample](http://fable.io/repl#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0Aopen%20System%0A%0Amodule%20ExternalFuncs%20%3D%20%0A%20%20let%20toSpecialUniversalTime%20(time%3A%20obj)%20%3D%20import%20%22toUniversalTime%22%20%22fable-core%2FDate%22%0A%0A%5B%3CAutoOpen%3E%5D%0Amodule%20Extensions%20%3D%20%0A%20%20type%20System.DateTime%20with%0A%20%20%20%20member%20self.ToVerySpecialUniversalTime()%20%3A%20DateTime%20%3D%20ExternalFuncs.toSpecialUniversalTime%20self%0A%0Alet%20x%20%3D%20DateTime(2015%2C%201%2C%201).ToVerySpecialUniversalTime()), so it is of low priority now :)

**Comment by alfonsogarciacaro** [comment]
@Zaid-Ajaj Is this still an issue? If so, do you want to give a try at solving it (with guidance of course)?

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro It's not an issue for me since I found a workaround, but should probably be supported anyway, becuase it is valid F#. It is a very low priority for now.

**Comment by valery-vitko** [comment]
@Zaid-Ajaj, @alfonsogarciacaro, don't you mind if I grab this?

**Comment by alfonsogarciacaro** [comment]
@valery-vitko That'd be great! However, please note that for Fable 2.0 all methods will become static methods so `this` will be always passed as the first parameter. I don't remember the details of the discussion so I'm not sure how that will affect this but it could happen that it's automatically fixed :)

I'll be writing a few up-for-grabs issues for Fable 2.0. It'd be great if you could help with any of them!

**Comment by valery-vitko** [comment]
@alfonsogarciacaro, great, looking forward to Fable 2.0 up-for-grabs then. And will revisit this one after 2.0 methods generation change, if it's OK with you.

**Comment by alfonsogarciacaro** [comment]
Absolutely! BTW, here's the first up-for-grabs issue :) https://github.com/fable-compiler/Fable/issues/1323

**Comment by alfonsogarciacaro** [comment]
This should be working with latest Fable :+1: Please reopen if you still have problems.
