### ISSUE TITLE
Fable 1.x: Node interop Issues

### ISSUE THREAD

**Issue by jmmk** [fable-compiler/Fable#801]
### Description

When trying to work with `Node.stream.Readable`, `Readable` is missing all inherited and interface methods.

### Repro code

```fsharp
module ReadableInterop

open Fable.Import

let r = Node.stream.Readable()
// r.<any symbol here from EventEmitter or ReadableStream>
r.on("data", !!(fun () -> ())) // The field, constructor, or member 'on' is not defined
r.pause() // The field, constructor, or member 'pause' is not defined

// My actual use case:
let p = Node.child_process.spawn(executable, args)
p.stdout.on("data", // do something...
```

### Related information 

* fable-compiler version: `"fable-loader": "^1.0.0-narumi-905"`
* fable-core version: `Fable.Core 1.0.0-narumi-908`
* Operating system: `macOS Sierra 10.12.4`

**Comment by alfonsogarciacaro** [comment]
Maybe this has to do with #753, do you have any hint, @jgrund?

**Comment by jgrund** [comment]
Hi @jmmk 

With the current bindings, there seems to be a bunch of casting needed to make things work.
I can get your example code to have 0 error / warnings if I change it to this:

```
open Fable.Import
open Fable.Import.JS

let r = Node.stream.Readable()
let ee = r :> Node.NodeJS.EventEmitter
ee.on("data", unbox(fun () -> ())) |> ignore
let s = r :> Node.NodeJS.ReadableStream
s.pause()

let p = Node.child_process.spawn("ls",  ResizeArray<string>[|"-lh"; "/usr"|])
let ee2 = p.stdout :> Node.NodeJS.EventEmitter

ee.on("data", unbox(fun () -> ())) |> ignore
```

The key is when you call a method from an inherited type, you need to cast it to the type with the method.

@alfonsogarciacaro Yes, with #753 I am attempting to update the bindings to go with the new prefered interface format for 1.0. I'm diverging from what's there in the TS interfaces as I'm finding they are not complete enough for my uses in some cases.

That said, it's a pretty large change. In the interim I'm publishing to: https://github.com/jgrund/fable-node6 . Once that is good enough, I plan to update #753 with my changes.

@jmmk You can use https://github.com/jgrund/fable-node6 for your code now if you'd like. With that repo, the code becomes:

```
open Node.Stream
open Node.ChildProcess

let r = stream.Readable.Create()
r.on("data", fun () -> ()) |> ignore
r.pause() |> ignore

let p = child_process.spawn("ls",  ResizeArray<string>[|"-lh"; "/usr"|])
p.stdout.on("data", fun (e) -> e) |> ignore
```

With the new interface ideas for ts2fable, you can see there is no more casting / unboxing needed.

**Comment by jmmk** [comment]
@jgrund Thanks, I'll try out the `fable-node6` bindings.

Closing since it sounds like #769 will solve this.
