### ISSUE TITLE
Enable DocumentDB server-side programming

### ISSUE THREAD

**Issue by jbeeko** [fable-compiler/Fable#802]
## Enable DocumentDB server-side programming

This issue suggests adding Azure DocumentDB server side scripts as a Fable execution target. Since Azure functions support F# and there is good Functions-DocumentDB integration this will enable a "full-stack" F# programming experiance Fable SPA->Functions->DocumentDB hopefully passing F# records all the way. 

Document DB is Azure's No-SQL database offering. It's native storage format is JSON and it's language for serverside scripting (stored procedures, triggers, post save actions userdefined functions) is JavaScript, specifically ECMA-262. See https://docs.microsoft.com/en-us/azure/documentdb/documentdb-programming. 

## Creating Stored Procedures in JavaScrip
Using a DocumentDB server-side script involves the following steps:
1. Writing a JavaScript function. The function must include in its body all code needed for the script, there is no way to reference external libraries or files.
2. Registering the function with a DocumentDB. One way of doing this is POSTing the JavaScript source to the Database. 
3. Calling the function. For exmaple a stored procedure may be called by exeuting a POST request against its URI passing any parameters as a JSON Array of JSON object.

JavaScript scripts can be created, registred and called using a number of DocumentDB SDKs:
* [Node.js client with Q Promises](http://azure.github.io/azure-documentdb-node-q/)
* .Net SDKs
* Straight JavaScript
* REST API

The following is an example of how to register and execute a stored procedure using the REST API:

```
POST https://dbs/testdb/colls/testColl/sprocs/sprocs/ HTTP/1.1
authorization: <<auth>>
x-ms-date: Thu, 07 Aug 2014 03:43:10 GMT


var x = {
"name": "createAndAddProperty",
"body": function (docToCreate, addedPropertyName, addedPropertyValue) {
            var collectionManager = getContext().getCollection();
            collectionManager.createDocument(
                collectionManager.getSelfLink(),
                docToCreate,
                function(err, docCreated) {
                if(err) throw new Error('Error:  ' + err.message);
                docCreated[addedPropertyName] = addedPropertyValue;
                getContext().getResponse().setBody(docCreated);
                });
        }
}
```
Notice the stored procedure is registered by executing a POST request against the URI dbs/testdb/colls/testColl/sprocs with the body containing the stored procedure to create. Triggers and UDFs can be registered similarly by issuing a POST against /triggers and /udfs respectively. 

Once registered this stored procedure can then be executed by issuing a POST request against its resource link:
```
POST https://<url>/sprocs/<sproc> HTTP/1.1
authorization: <<auth>>
x-ms-date: Thu, 07 Aug 2014 03:43:20 GMT


[ { "name": "TestDocument", "book": "Autumn of the Patriarch"}, "Price", 200 ]
```
Here, the input to the stored procedure is passed in the request body. Note that the input is passed as a JSON array of input parameters. The stored procedure takes the first input as a document that is a response body. The response we receive is as follows:
```
HTTP/1.1 200 OK

{ 
  name: 'TestDocument',
  book: ‘Autumn of the Patriarch’,
  id: ‘V7tQANV3rAkDAAAAAAAAAA==‘,
  ts: 1407830727,
  self: ‘dbs/V7tQAA==/colls/V7tQANV3rAk=/docs/V7tQANV3rAkDAAAAAAAAAA==/’,
  etag: ‘6c006596-0000-0000-0000-53e9cac70000’,
  attachments: ‘attachments/’,
  Price: 200
}
```

### F# "shim types" to support writing scripts
The DocumentDB scripting environment exposes a Context and a number of other types for doing things like setting response, reading parameters etc. Even the simple HelloWorld stored procedure below needs access to the Response type to set the response.

```
POST https://dbs/testdb/colls/testColl/sprocs/sprocs/ HTTP/1.1
authorization: <<auth>>
x-ms-date: Thu, 07 Aug 2014 03:43:10 GMT

var x = {
"name": "helloWorldStoredProc",
"body": function () {
        var context = getContext();
        var response = context.getResponse();

        response.setBody("Hello, World");
        }
}
```

These would be be something like:
```
// shim types
type Request = {
    content : string
}
type Response = {
    body : string
} with
    member this.setBody output = 
        this.body = output

type Context = {
    request : Request
    response : Response
} with 
    member this.getRequest =
        this.request
    member this.getResponse =
        this.response

let getContext = {
    request = {content = ""}
    response = {body = ""}
}
```
These types will let us write the stored procedure as:
```
let helloWorldStoredProc = 
    let context = getContext
    let response = context.getResponse
    response.setBody "Hello World"
```
A full list of these types is [here]( http://azure.github.io/azure-documentdb-js-server/). 

### Post packaging
Because DocumentDB scripts can't reference any external libraries the JavaScrip Fable generates needst to be embedded into the function that will be registered with DocumentDB. Something like this:
```
var helloWorldStoredProc = {
    id: "helloWorld",
    serverScript: function () {
        <All the JS functions created to support f# features used
        ...>

        var context = getContext();
        var response = context.getResponse();

        response.setBody("Hello, World");
    }
}
```
This can then be posted to the desired URI to register the stored procedure.

### Workflow
It is not clear what the best workflow for creating stored procedures will be.

**Comment by alfonsogarciacaro** [comment]
Thanks for the summary @jbeeko, it will be very interesting to use Fable with DocumentDB. For what I've seen in the documents, using the Node.js client seems to be the easiest way. Actually, translating the sample to F# and compile it with Fable should "just work". I'll try to see if I can reproduce the tutorial in F#.

**Comment by alfonsogarciacaro** [comment]
This is low priority right now, but maybe someone from the @fable-compiler/code-maintenance or @fable-compiler/community teams wants to give a try.
