### ISSUE TITLE
Creating a page to list all Fable-* lib

### ISSUE THREAD

**Issue by kunjee17** [fable-compiler/Fable#811]
### Description

As Fable is moving toward 1.0 and going solid. It would be great if have list of Fable-* packages. Searchable list would be even better. Elm do have it's own package manager and way to manage it. We also have powerful paket and also dotnet core restore and npm. 

As things are growing, it would be great to F# specific projects (like elmish, aether). So, this would help other people coming to Fable.

**Comment by MangelMaxime** [comment]
We was discussing it in the past. Here is the [discussion](https://github.com/fable-compiler/fable-graphics/issues/8#issuecomment-265468760).

I agree this would be a great thing to have.

**Comment by alfonsogarciacaro** [comment]
I like the idea of creating an "awesome-fable" list as other communities are doing to add links to everything that can be useful for Fable users: libraries, tools, tutorials, samples... I think we have three options for that:

- A page in Fable website: maybe more easily discoverable but also more difficult to keep up to date (users have to PR, then the new site must be rebuilt).
- An independent repo ([example](https://github.com/enaqx/awesome-react)): the maintainer of the repo should take care of keeping the list up to date.
- A wiki page: this maybe the easiest way, as the wiki can be made freely editable by any one.

What do you think?

**Comment by MangelMaxime** [comment]
Personaly, I prefer a page in the Fable website.
As we are going to rewrite it, we could make the build/deploy process easy enough to done in one command line for example.

Otherwise, between the latest two I prefer the independent repo. :)

**Comment by kunjee17** [comment]
I personally like something like elm packages. Searchable page with their read me as documentation. 

Otherwise I agree with @mangelMaxime . A page on home site would be preferable but separate repo is also good.

**Comment by alfonsogarciacaro** [comment]
@kunjee17 That'd be nice but it may be a long shot because we don't have a custom package manager for Fable. Also, one of the advantages of Fable is the interoperability with Javascript is very good so we don't need to have many Fable-specific packages for every thing. Our goal is to automate the process of creating bindings for the most used JS libraries more or less the same way Typescript does, this is being tracked in https://github.com/fable-compiler/ts2fable/issues/1

Ok, we'll add it to the web site :+1: It may take a bit because currently updating the docs has priority but a "Fable resources" page will definitely go into the new website.

**Comment by kunjee17** [comment]
@alfonsogarciacaro  thanks for Fable resources page. And just to say thanks I did created [awesome-fable](https://github.com/kunjee17/awesome-fable) page. 

Have added you, @MangelMaxime  and @forki as collaborators just to keep response time as small as possible. And I am very much open if you like to move this to fable-compiler projects. 

Whatever you guides decides just let me know. And once finalise we can make it full public (public aware).

**Comment by alfonsogarciacaro** [comment]
Idem (i.e. awesome) @kunjee17, thanks a lot for this! Ok, let's keep the issue open until the resources page is added to Fable website so I don't forget ;) Maybe we could generate it automatically from @kunjee17's awesome-fable list to make sure both lists are kept in sync (one advantage of keeping the repo is people can suscribe to changes), what do you think?

**Comment by alfonsogarciacaro** [comment]
This has been solved by awesome-fable, thanks a lot! :tada: In the new web site we'll try also to extract the information and present it formatted :+1:
