### ISSUE TITLE
Currying annotation

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#815]
The uncurrying optimization is fantastic, but there are certain very rare circumstances where you don't want it.

Consider [this F# file](https://github.com/fable-compiler/fable-powerpack/blob/4e25424ab39a0bb358dd8b7340303d7a8ac7394b/src/Json.fs#L26) and [this JavaScript file](https://github.com/fable-compiler/fable-powerpack/blob/4e25424ab39a0bb358dd8b7340303d7a8ac7394b/src/Json.js)

The above F# file compiles into something similar to this:

```js
var ofString = function ofString($var1) {
    return _ofString(function (arg0) {
        return new Json(0, arg0);
    }, function (arg0_1) {
        return new Json(1, arg0_1);
    }, function (arg0_2) {
        return new Json(2, arg0_2);
    }, function (arg0_3) {
        return new Json(3, arg0_3);
    }, function (arg0_4) {
        return new Json(4, arg0_4);
    }, new Json(5), function (arg0_5) {
        return new __WEBPACK_IMPORTED_MODULE_5__node_modules_fable_core_Result__["a" /* default */](0, arg0_5);
    }, function (arg0_6) {
        return new __WEBPACK_IMPORTED_MODULE_5__node_modules_fable_core_Result__["a" /* default */](1, arg0_6);
    }, $var1);
};
```

Notice that it's uncurried. However the JS file [returns a closure](https://github.com/fable-compiler/fable-powerpack/blob/4e25424ab39a0bb358dd8b7340303d7a8ac7394b/src/Json.js#L31), so this uncurrying is incorrect.

It would be nice if there was some sort of annotation I could add in F# that would disable uncurrying, for this specific situation.

**Comment by alfonsogarciacaro** [comment]
Sorry, it's a bit difficult for me to follow the code (I'm getting old...), would it be possible to have a minimal F# sample with the actual and expected JS outputs?

In any case, it's going to be difficult to add an annotation to disable uncurrying selectively. TBH, I had to add so many patches in so many places (lambda creation, lambda passing, application, construction...) for this feature that it would be a real challenge to remove it now ;)

**Comment by Pauan** [comment]
@alfonsogarciacaro Sure, here's a minimal example:

```fsharp
// Foo.fs

[<Import("_foo", "./Foo.js")>]
let private _foo:
    (int -> Result<int, string>) ->
    (string -> Result<int, string>) ->
    bool -> Result<int, string> = jsNative

let foo: bool -> Result<int, string> = _foo Ok Error
```

```js
// Foo.js

export const _foo = (Ok, Error) => {
    return (x) => {
        if (x) {
            return Ok(5);
        } else {
            return Error("fail!");
        }
    };
};
```

This is a contrived example, but it gives the right idea.

Here is the expected output:

```js
var _foo = function _foo(Ok, Error) {
    return function (x) {
        if (x) {
            return Ok(5);
        } else {
            return Error("fail!");
        }
    };
};

var foo = _foo(function (arg0) {
    return new Result(0, arg0);
}, function (arg0_1) {
    return new Result(1, arg0_1);
});
```

Here is the actual output:

```js
var _foo = function _foo(Ok, Error) {
    return function (x) {
        if (x) {
            return Ok(5);
        } else {
            return Error("fail!");
        }
    };
};

var foo = function foo($var1) {
    return _foo(function (arg0) {
        return new Result(0, arg0);
    }, function (arg0_1) {
        return new Result(1, arg0_1);
    }, $var1);
};
```

The reason for this coding pattern is that the `_foo` function (in JavaScript) needs to return an F# discriminated union.

But I can't rely upon Fable's implementation of discriminated unions, so instead I pass in the union constructors `Ok` and `Error` as arguments to `_foo`. That way `_foo` can call them, and so it doesn't rely upon Fable's internal implementation details. This is the only robust way to use F# discriminated unions in JavaScript.

But in the actual output, this doesn't work, because the `_foo` function takes two arguments (`Ok` and `Error`) and returns a function which takes one argument, but Fable's uncurrying optimization treats it as a function that takes three arguments.

This is both incorrect and inefficient. Fable creates the `function (arg0) { return new Result(0, arg0); }` and `function (arg0_1) { return new Result(1, arg0_1); }` closures every time `foo` is called, whereas in the expected output it only creates them once.

However, I have found a great workaround. If I use `System.Func`, then everything works perfectly:

```fsharp
[<Import("_foo", "./Foo.js")>]
let private _foo:
    System.Func<int -> Result<int, string>,
                string -> Result<int, string>,
                bool -> Result<int, string>> = jsNative

let foo: bool -> Result<int, string> = _foo.Invoke(Ok, Error)
```

This is even better than a currying annotation, because it works with multi-argument functions:

```fsharp
// This does NOT work, because it will curry `bool -> int -> string -> Result<int, string>`, but it's not supposed to
[<Import("_foo", "./Foo.js")>]
let private _foo:
    (int -> Result<int, string>) ->
    (string -> Result<int, string>) ->
    bool -> int -> string -> Result<int, string> = jsNative

[<Curry(true)>]
let foo: bool -> int -> string -> Result<int, string> = _foo Ok Error
```
```fsharp
// This works perfectly
[<Import("_foo", "./Foo.js")>]
let private _foo:
    System.Func<int -> Result<int, string>,
                string -> Result<int, string>,
                bool -> int -> string -> Result<int, string>> = jsNative

let foo: bool -> int -> string -> Result<int, string> = _foo.Invoke(Ok, Error)
```

So this problem has been solved.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot for the detailed info @Pauan, I understand the problem much better now 😄 I'm glad you found a workaround by using `System.Func`, also because we'll probably find this when translating Typescript declarations.

Another alternative solution is to take advantage of the fact that the F# compiler internally does differentiate methods and function values and declare `_foo` as a method instead of a function value, this can be done simply by specifying the arguments. Same as with `System.Func` you avoid the effect of the uncurrying optimization:

```fsharp
[<Import("_foo", "./Foo.js")>]
let private _foo
    (f1: int -> Result<int, string>)
    (f2: string -> Result<int, string>)
    : bool -> int -> string -> Result<int, string> = jsNative

// You can also use an import expression instead of the attribute
// let private _foo
//     (f1: int -> Result<int, string>)
//     (f2: string -> Result<int, string>)
//     : bool -> int -> string -> Result<int, string>
//     = import "_foo" "./Foo.js"
```

**Comment by Pauan** [comment]
@alfonsogarciacaro That's good to know, and it's certainly a lot cleaner, but I don't like the idea of relying upon implementation details which might change.

Are the differences between functions/methods guaranteed by the F# language, and is Fable guaranteed to distinguish them correctly both now and in the future?

In particular, what about when you call a method with too few arguments? It seems in that situation it reverts back to the uncurrying optimization:

```fsharp
[<Import("_foo", "./Foo.js")>]
let private _foo
    (a: int -> Result<int, string>)
    (b: string -> Result<int, string>):
    bool -> Result<int, string> = jsNative

let foo1 = _foo Ok

let foo: bool -> Result<int, string> = foo1 Error
```

```js
// This is the compiled output for the above F# code
// The `foo1` function is uncurried, which causes it to break

var foo1 = function () {
  var a = function a(arg0) {
    return new Result(0, arg0);
  };

  return function (b) {
    return _foo(a, b);
  };
}();

var foo = function foo($var14) {
  return foo1(function (arg0) {
    return new Result(1, arg0);
  }, $var14);
};
```

So it seems to me that `System.Func` is the most robust, since its implementation will *always* be correct, and it will never change.

But I guess as long as `_foo` is `private`, and you make sure to never call it with too few arguments, then it can also be a useful alternative.

**Comment by alfonsogarciacaro** [comment]
I found the actual difference between methods and function values in F# when inspecting the AST. I'm not sure if it's in F# specs but I think it's part of F# nature: an ML language that compiles to .NET IL designed for Object Oriented languages, so modules are represented as classes with static methods. We can check, but I think the chances this changes in future F# versions are very low. Likewise, it will be difficult that the uncurrying optimization in Fable changes, as I foresee many Fable programs will rely on this from now to interact with JS.

You're right that this breaks when applying less arguments than expected to the method. This is because in these situations the F# compiler converts the method to a function value, and then Fable's uncurrying optimization applies. I guess we can avoid this by using tuple arguments instead which cannot be curried (again, the F# compile make them look as a tuple argument to the user, but they're actually represented as normal method arguments:

```fsharp
[<Import("_foo", "./Foo.js")>]
let private _foo(a: int -> Result<int, string>, b: string -> Result<int, string>): bool -> Result<int, string> = jsNative

let foo1 b = _foo(Ok, b)

let foo = foo1 Error
```

**Comment by Pauan** [comment]
@alfonsogarciacaro Oh boy, so now we have 3 different ways to avoid uncurrying, each with their own pros and cons. :stuck_out_tongue: 

Using tupled arguments seems to offer the same benefits as `System.Func`, but it's less noisy, thanks!
