### ISSUE TITLE
[BUG] TryParse gives an incorrect result

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#817]
### Repro code

```fsharp
System.Int32.TryParse("9X")
```

### Description

In `fsharpi` the above returns `(false, 0)` but with Fable it [returns `(true, 9)`](http://fable.io/repl.html#?code=printfn%20"%25A"%20<|%20System.Int32.TryParse("9X")&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2)

In the generated code, it uses `Number.parseInt("9X", 10)`, but the JavaScript `parseInt` function has different behavior from the F# `TryParse` method.

This can be fixed by replacing `Number.parseInt("9X", 10)` with `+"9X"` and adding an integer check, which should give the correct result.

(Also we should add some unit tests for this behavior, e.g. `System.Int32.TryParse("X9TRE34")` and `System.Int32.TryParse("9SayWhat12Huh")`)

If you want, I can probably send a PR to fix this.

### Related information 

* fable-compiler version: 1.0.0-narumi-909
* fable-core version: 1.0.0-narumi-909
* Operating system: Debian GNU/Linux Testing (64-bit)

**Comment by alfonsogarciacaro** [comment]
Related to #725. Yes, we need a proper function to parse numbers instead of just delegating to JS `parseInt` and `parseFloat`. It'd be really awesome if you could PR this.

**Comment by alfonsogarciacaro** [comment]
Reference: [replacement for number parsing](https://github.com/fable-compiler/Fable/blob/73e034a36e8b855bebcd1395f83f4e7a000fc1f1/src/dotnet/Fable.Compiler/Replacements.fs#L986-L1026)

To fix this, I guess we need to create a custom function in fable-core that better replicates the .NET semantics and call it instead (beware we need to be able to parse numbers with different bases too).

**Comment by Pauan** [comment]
@alfonsogarciacaro Thanks, that'll help out a lot!
