### ISSUE TITLE
"export 'chars' was not found

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#820]
The following code emit a warning from webpack:

```fs
let validateBirthday =
  let t = "hello"
  t.Chars(2)
  field
```

Warning:
`"export 'chars' was not found in '../../../node_modules/fable-core/String'`

I suspect it's coming from [this line](https://github.com/fable-compiler/Fable/blob/master/src/typescript/fable-core/String.ts#L361)

```ts
export function trim(str: string, side: "start" | "end" | "both", ...chars: string[]) {
```

**Comment by alfonsogarciacaro** [comment]
Fixed by #821
