### ISSUE TITLE
feature request System.Random (FABLE: Cannot find replacement for System.Random.NextDouble)

### ISSUE THREAD

**Issue by raould** [fable-compiler/Fable#822]
### Description

I guess System.Random is not supported yet in Fable?

* fable-compiler version: 0.7.50  (hmm how about supporting a "--version" command? :-)
* fable-core version: 0.7.30
* Operating system: Linux Ubuntu 16.04 AMD/Intel 64 bit

**Comment by alfonsogarciacaro** [comment]
System.Random is supported but I forgot to add `NextDouble` 😅 Maybe you could send a PR to add it? The replacements for the Random class are [here](https://github.com/fable-compiler/Fable/blob/62856c33e92cbb9c9c8977374db1e830243c5857/src/dotnet/Fable.Compiler/Replacements.fs#L1855-L1868). Probably adding something like this should work but I haven't tested it:

```fsharp
        | "nextDouble" ->
            GlobalCall ("Math", Some "random", false, [])
            |> makeCall info.range info.returnType |> Some
```

You can test if it works using the [QuickTest](https://github.com/fable-compiler/Fable/blob/426061c92722f75493d9fab439bc93a7ab4a3427/src/tools/QuickTest.fs). It'd be great if you could also add a test with the PR (the current test for Random is [here](https://github.com/fable-compiler/Fable/blob/426061c92722f75493d9fab439bc93a7ab4a3427/src/tests/Main/ArithmeticTests.fs#L361)).

> Alternatively you can just call `Fable.Import.JS.Math.random()` directly.

**Comment by Zaid-Ajaj** [comment]
@raould As a workaround for now, you can use either `Fable.Import.JS.Math.random()` but if you want to use ranges like "a random number between 20 and 50" you can use the following:

```fsharp
open Fable.Core.JsInterop

[<Emit("Math.random()")>]
let getRandomNumber() : float = jsNative

[<Emit("Math.floor($0)")>]
let floorOf (x: float) : float  = jsNative

let randomNumberBetween (a: float) (b: float) : float = 
    floorOf (getRandomNumber() * (b - a)) + a 
```

where the function `randomNumberBetween` is your `Random.GetNextDouble` with range from `a` to `b`
