### ISSUE TITLE
fable + edge js (F# frontend for js + .net world)

### ISSUE THREAD

**Issue by Neftedollar** [fable-compiler/Fable#827]
Hi!
Fable is awesome. All around know about it. 
I thought about Fable on a server(node js [and meteor for example]) and call to mind about [edge js](https://github.com/tjanczuk/edge), edgejs is awesome too!

What if we can write f# code and use all power of nodejs and .net in on file?!
What it can be look like?
What about this:
```fs
[<dotnet/fsharp/etc>]
let myFunction:obj -> Async<obj> = fun x ->  async { return x  }
let runWithDotNet somObj   myCb= async {
  return!  = prepare someObj |> myFunction |> myCb
}
```
which can translate into
```js
var myFunction = edge.func('fs', function () {/*
    fun x -> async { 
        return x
    }
*/}); //or we can use another method (https://github.com/tjanczuk/edge#how-to-specify-additional-clr-assembly-references-in-c-code)
var runWithDotNet   = function(someObject) {
   function(myCb){
      myFunction(prepare(someObject), myCb)
   }
}
```
It's just concept! But the idea of using Fable on a server with cool features of both worlds making me crazy!

**Comment by Neftedollar** [comment]
There are some problems with type safety. But I think they can be solved via some code generation.

**Comment by alfonsogarciacaro** [comment]
Thanks for the kind words @Neftedollar! Actually I was considering Edge.js when I started to write Fable, but I had to discard it because it's not possible to call JS code from a .NET app in Unix. We had some discussions about combining Edge and Fable and there are cases where this could make sense, for example in Ionide where a JS process has to call .NET with low overhead. However I cannot dedicate time to explore this as it's not a priority in Fable development, but I can provide some guidance if you'd like to give it a try :)

**Comment by Neftedollar** [comment]
@alfonsogarciacaro  thanks. Your recommendations would be useful. I'll give it a try after meteor-fable-compiler. Thanks. 
Do you have any repository about ideas? Maby someone will take it while I'm busy with meteor.

**Comment by alfonsogarciacaro** [comment]
No, sorry. I don't know Edge.js well so I cannot give a head start 😕 I can try to answer to some more specific questions though :wink;

**Comment by Neftedollar** [comment]
@alfonsogarciacaro  Sorry, I think I said something wrong. I'd want to thank you for your answer, and thank you for readiness to answer questions. 
About repository, I'd mean a public list of ideas where I can place idea about edgejs and fable.

**Comment by alfonsogarciacaro** [comment]
Ah, sorry, I didn't understand you correctly 😅 We don't have something like a roadmap atm, though it could be a nice thing to have. In these cases we usually write an issue with the proposal, add the `help wanted` tag and ask for help in the Gitter chat or Twitter 😄
