### ISSUE TITLE
Allow fable server to run arbitrary commands

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#828]
Currently the fable server is limited to running commands via npm scripts.

It would be useful to start the server, run an arbitrary script, and shutdown the server after the script finishes.

**Comment by alfonsogarciacaro** [comment]
You can do that, just you need two terminal windows. In the first terminal type: `dotnet fable start`, in the second one run the script you want. When you're finished, just interrupt the process in the first terminal. You can also type `dotnet fable --help` to see the options available.

It could be possible to add another command that runs an arbitrary script (`dotnet fable shell-run` maybe?). In Windows, we can just call `cmd` + script, but I'm not sure in Linux/macOS: `sh`, `bash`?

**Comment by jgrund** [comment]
Right, so my use case is to run in CI. I'd like to execute arbitrary rollup commands over several sub-packages using https://github.com/lerna/lerna.

Regarding adding another command, seems like we could reuse `startServerWithProcess` and just add another match to `main`?

**Comment by alfonsogarciacaro** [comment]
Thanks for the PR! That should do it, but for your info, in Fable's CI I do something like this to start a Fable server, run some arbitrary code and then stop it: https://github.com/fable-compiler/Fable/blob/056b3e48995a8df2e150b9e0b9f9323ae4590363/build.fsx#L363-L364

**Comment by jgrund** [comment]
Cool, makes sense to run it as a subprocess. I have an interesting use-case in that I'm running a bunch of fable servers in parallel as I want to build out a bunch of sub-projects.

So given this change, I can either spin up a subprocess (with a random available port) or call `dotnet fable shell-run` for each subproject.

**Comment by alfonsogarciacaro** [comment]
Hmm, that sounds interesting. At the moment you can start a Fable server and use to compile different projects but only one project can be compiled at a time (though several files of the same project can be compiled in parallel), but you can spawn different Fable servers in different ports to compile multiple projects in parallel.

Let me know how it goes and feel free to PR new commands for your use case :+1:

**Comment by jgrund** [comment]
Thanks. I thought about abstracting (or creating a PR) that would allow the server to operate over multiple project (perhaps by keying off of path or something).
