### ISSUE TITLE
[ERROR] This expression was expected to have type Result but has type Severity

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#836]
### Repro code

```fsharp
module Fable.Foo

type Foo =
    | Foo of Result<int, string>

let foo (a: Foo): bool =
    match a with
    | Foo(Error(_)) -> true
    | _ -> false

let bar: Foo = Foo(Error("foo"))
```

### Description

I get these errors:

```
ERROR in ./Main.fsproj
/home/pauan/Programming/fsharp/fable-getting-started/src/fs/Main.fs(8,10,8,18) : error FSHARP: This expression was expected to have type
    'Result<int,string>'    
but here has type
    'Severity'    
 @ multi ./Main.fsproj

ERROR in ./Main.fsproj
/home/pauan/Programming/fsharp/fable-getting-started/src/fs/Main.fs(11,19,11,24) : error FSHARP: This value is not a function and cannot be applied
 @ multi ./Main.fsproj
```

It seems the problem is caused by [this type](https://github.com/fable-compiler/Fable/blob/c60877758a1c4d0ee6657ee4646d099b3c504f4b/src/dotnet/Fable.Core/Compiler.fs#L9)

I ran into this because I'm using the `Fable.UnitTest` namespace for the `fable-unit-test` library, but this causes the `Result` type to break.

If I don't use the `Fable` namespace then it works fine.

I'm not sure what the best course of action is. I can use `Result.Error` to fix the problem, but we'll probably run into this problem again in the future as we add more Fable libraries.

### Related information 

* fable-compiler version: 1.0.0-narumi-910
* fable-core version: 1.0.0-narumi-910
* Operating system: Debian GNU/Linux Testing (64-bit)

**Comment by alfonsogarciacaro** [comment]
Crap, this happens because of my great idea to mix compiler and end-user stuff in Fable.Core (back in the day I though this would be easier for plugin authors). I added the `RequireQualifiedAccess` attribute to Severity and republished the package. Hopefully this will solve the problem, could you please check?

**Comment by Pauan** [comment]
Yup, it works now, thanks!
