### ISSUE TITLE
[BUG] System.Text.RegularExpressions.Group.Value is incorrect

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#838]
### Repro code

```fsharp
open System.Text.RegularExpressions

for m in Regex.Matches("\n\n\n", @"(?:([^\n\r]+)|\r\n|\n\r|\n|\r)") |> Seq.cast<Match> do
    printfn "%A" m.Groups.[1].Value
```

### Expected and actual results

Expected:

```js
import { matches } from "fable-core/RegExp";
import { fsFormat } from "fable-core/String";
const inputSequence = matches("\n\n\n", "(?:([^\\n\\r]+)|\\r\\n|\\n\\r|\\n|\\r)");

for (let m of inputSequence) {
  fsFormat("%A")(x => {
    console.log(x);
  })(m[1] || "");
}
```
```
""
""
""
```

[Actual](http://fable.io/repl.html#?code=open%20System.Text.RegularExpressionsfor%20m%20in%20Regex.Matches("\n\n\n"%2C%20%40"(%3F%3A([^\n\r]%2B)|\r\n|\n\r|\n|\r)")%20|>%20Seq.cast<Match>%20do%20%20%20%20printfn%20"%25A"%20m.Groups.[1].Value&astInput=false&babili=false&evaluate=false&lineWrap=false&presets=es2015%2Creact%2Cstage-2):

```js
import { matches } from "fable-core/RegExp";
import { fsFormat } from "fable-core/String";
const inputSequence = matches("\n\n\n", "(?:([^\\n\\r]+)|\\r\\n|\\n\\r|\\n|\\r)");

for (let m of inputSequence) {
  fsFormat("%A")(x => {
    console.log(x);
  })(m[1]);
}
```
```
"undefined"
"undefined"
"undefined"
```

### Description

The [`System.Text.RegularExpressions.Group.Value`](https://msdn.microsoft.com/en-us/library/system.text.regularexpressions.capture.value(v=vs.110).aspx) property is always a string. If it doesn't match, then it will be the empty string `""`

However, Fable compiles it to `m[1]`, which is sometimes `undefined` (because regexp matches in JS *sometimes* return `""` and *sometimes* return `undefined`). This can be fixed by using `m[1] || ""` instead.

I can probably send a PR to fix this.

**Comment by alfonsogarciacaro** [comment]
That would be really helpful, thanks! (And thank you also for spotting the problem.)

**Comment by alfonsogarciacaro** [comment]
@Pauan Are you still planning to send the PR? Please ask me if you have any question.

**Comment by Pauan** [comment]
@alfonsogarciacaro Sorry, I've been busy with other things.

I'm not sure when I'll be able to get around to this, so if somebody else wants to tackle it they can.

It might be a good pull request for somebody to get their feet wet with the compiler.
