### ISSUE TITLE
Implementation of interface in a private module causes "TypeError: [thing] is not a constructor" error in JS

### ISSUE THREAD

**Issue by ronniebarker** [fable-compiler/Fable#841]
### Description

With an interface definition in a module, having the implementation in a private sub-module causes a run-time error in Javascript: "TypeError: [thing] is not a constructor"

### Repro code

``` fs
type IInterface =
  abstract member Member : thing:string -> unit

module private Implementation =
    type Concrete() =
        interface IInterface with
            member this.Member thing =
                printfn "%s" thing

let Thing = Implementation.Concrete() :> IInterface

Thing.Member "Hello, World"
```

### Expected and actual results

Fails in browser:

App.fs:55 Uncaught TypeError: Implementation.Concrete is not a constructor

### Related information 

* fable-compiler version:
* fable-core version: 1.0.0-narumi-911
* Operating system: osx

**Comment by alfonsogarciacaro** [comment]
Thanks for the report! Related to #696, same problem but affecting types instead of methods. I added a fix, it'll be included in the next release by the end of the week :+1:
