### ISSUE TITLE
List.mapFold / mapFoldBack issue

### ISSUE THREAD

**Issue by ncave** [fable-compiler/Fable#842]
```
module Program

[<EntryPoint>]
let main argv =
    let f x y = x,y
    let xs,_ = List.mapFold f "a" ["b"]
    printfn "head: %A" xs.Head
    0
```
on dotnet prints: `"a"`
on fable/js prints: `undefined`

```
    Fable version: 1.0.0-narumi-911
    "fable-core": "^1.0.0-narumi-910"
    "fable-loader": "^1.0.0-narumi-912",
```
This is impacting FCS-Fable / Fable REPL

**Comment by alfonsogarciacaro** [comment]
Hmm, I'm delegating many functions for the collections to the `Seq` module and building another collection type from the result if necessary. But in the case of `mapFold/mapFoldBack` the result is a tuple so I didn't include them in the _implementedSeqBuildFunctions_. Maybe the best solution is to implement these functions (and others) in the proper collection modules, but for now I just added an optional argument with a transformation for the first member of the result tuple :+1:
