### ISSUE TITLE
dotnet fable add doesn't work if there is spaces in the folder path.

### ISSUE THREAD

**Issue by FrankBro** [fable-compiler/Fable#844]
### Description

Will fail if there's spaces in the folder path

### Repro code

`dotnet fable add fable-powerpack@next fable-react@next fable-elmish@next fable-elmish-react@next fable-elmish-browser@next`

In a folder like `D:\Fable Test\`

### Expected and actual results

Should work

### Related information 

* fable-compiler version:
* fable-core version: 1.0.0-narumi-910
* Operating system: Win10

**Comment by alfonsogarciacaro** [comment]
Thanks for spotting this @FrankBro! Can you please try with the just published dotnet-fable 1.0.0-narumi-912 (remember to use `dotnet restore --no-cache` to upgrade). You'll have to update the fable-core npm package as well.
