### ISSUE TITLE
Async<T> does not encode type information of T

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#846]
### Description
Generic argument of Async is not encoded in the type definition

### Repro code
Given the definition of the record:
```fsharp
type Record = {
  asyncProp : Async<string>
}
```
### Expected Compilation Result
```js
  [_Symbol.reflection]() {
    return {
      type: "Stdin.Record",
      interfaces: ["FSharpRecord"],
      properties: {
        asyncProp: makeGeneric(Async, {
            a:  "string"
        })
      }
    };
  }
```
### Actual 
```js
  [_Symbol.reflection]() {
    return {
      type: "Stdin.Record",
      interfaces: ["FSharpRecord"],
      properties: {
        asyncProp: Async
      }
    };
  }
```

[Sample code](http://fable.io/repl#?code=open%20Fable.Core%0Aopen%20Fable.Core.JsInterop%0A%0Atype%20Maybe%3C%27a%3E%20%3D%20%0A%20%20%20%20%7C%20Just%20of%20%27a%0A%20%20%20%20%7C%20Nothing%0A%20%20%20%20%0A%20%20%20%20%0Atype%20Record%20%3D%20%7B%0A%20%20asyncProp%20%3A%20Async%3Cstring%3E%20%2F%2F%20generic%20argument%20string%20is%20lost%20%0A%20%20maybe%20%3A%20Maybe%3Cstring%3E%20%2F%2F%20encoded%20generic%20type%20%0A%7D)

**Comment by alfonsogarciacaro** [comment]
Ups, that was a bug that went under the radar. Thanks for reporting! `Type.GenericArguments` should also work now :+1:

**Comment by Zaid-Ajaj** [comment]
WOW that was ultra fast ❤️ ❤️ thanks!!! Will test right away :smile:
