### ISSUE TITLE
Publish fable.jsonconverter for net45 again

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#847]
would it be possible to publish fable.jsonconvert-narumi for net45 AND netstandard?

The old package contained only net45:
![image](https://cloud.githubusercontent.com/assets/4236651/25334927/0f2c1a0c-28f1-11e7-9c3b-fde4ee7c732c.png)

The new package contains only netstandard1.6:
![image](https://cloud.githubusercontent.com/assets/4236651/25334961/2772c354-28f1-11e7-8340-0a00e0040d2d.png)

I want to use both Akka and fable.jsonconverter in one project, Akka supports only net45, fable only netstandard.

**Comment by alfonsogarciacaro** [comment]
Yes, that should be no problem. Maybe you could send a PR to create both builds and package them (I haven't done something like that yet). BTW, the JsonConverter is a [single file](https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.JsonConverter/Fable.JsonConverter.fs) without dependencies so it's also easy to just add it to your project if needed.

**Comment by 0x53A** [comment]
For now I have added the file as a paket github dependency, so solved for me! Thanks!

Afaik this should be easy with the new sdk, probably something like this:

![image](https://cloud.githubusercontent.com/assets/4236651/25411685/6eecaf8c-2a1e-11e7-860d-f52451a47e5c.png)

note TargetFrameworks (plural)
I tried to test it, but couldn't:

When i run ``build PublishJsonConverter``:

![image](https://cloud.githubusercontent.com/assets/4236651/25411711/8bf62dec-2a1e-11e7-848f-bbca1933cfd2.png)

before that I got an error about a missing __RELEASE_NOTES.md__ which I was able to work around by creating it.

The gitignore excludes all directories named nuget, and so also excludes ``src\nuget\Fable.JsonConverter`` could it be that this file only exists locally on your computer?

Or am I missing another step?

**Comment by alfonsogarciacaro** [comment]
Sorry. the `PublishJsonConverter` target is a remnant of the old structure before converting the projects to netcore. Now `PublishPackages` should be used.

I tried to follow your kind instructions but I'm facing several problems:

- Paket fails with the multiple `TargetFrameworks` (pinging @forki). I get many errors like these when trying to `dotnet restore`:

```
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error : Package System.Reflection.TypeExtensions 4.3.0 is not compatible with net45 (.NETFramework,Versi
on=v4.5). Package System.Reflection.TypeExtensions 4.3.0 supports:\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotnet\Fable.JsonConverter\Fable.JsonConverte
r.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - monoandroid10 (MonoAndroid,Version=v1.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotn
et\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - monotouch10 (MonoTouch,Version=v1.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotnet\F
able.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - net46 (.NETFramework,Version=v4.6)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotnet\Fab
le.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - net462 (.NETFramework,Version=v4.6.2)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotnet\
Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - netcore50 (.NETCore,Version=v5.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotnet\Fabl
e.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - netstandard1.3 (.NETStandard,Version=v1.3)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\do
tnet\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - netstandard1.5 (.NETStandard,Version=v1.5)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\do
tnet\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - xamarinios10 (Xamarin.iOS,Version=v1.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotne
t\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - xamarinmac20 (Xamarin.Mac,Version=v2.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dotne
t\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - xamarintvos10 (Xamarin.TVOS,Version=v1.0)\r [C:\Users\Alfonso\Documents\GitHub\Fable\src\dot
net\Fable.JsonConverter\Fable.JsonConverter.fsproj]
C:\Program Files\dotnet\sdk\1.0.3\NuGet.targets(97,5): error :   - xamarinwatchos10 (Xamarin.WatchOS,Version=v1.0) [C:\Users\Alfonso\Documents\GitHub\Fable\src
\dotnet\Fable.JsonConverter\Fable.JsonConverter.fsproj]
```

- If I don't use Paket it works, but then I get this when trying to push to Nuget:

```
dotnet nuget push .\bin\Release\Fable.JsonConverter.1.0.0-narumi-909.nupkg -s nuget.org
info : Pushing Fable.JsonConverter.1.0.0-narumi-909.nupkg to 'https://www.nuget.org/api/v2/package'...
info :   PUT https://www.nuget.org/api/v2/package/
info :   Conflict https://www.nuget.org/api/v2/package/ 953ms
error: Response status code does not indicate success: 409 (The package ID 'Fable.JsonConverter' is not available.).
```

I guess will have to use the Github dependency for the moment :/

**Comment by 0x53A** [comment]
Well that TargetFrameworks  was just a blind guess, I haven't actually used netcore much.

I will try again with PublishPackages a little bit ...

**Comment by alfonsogarciacaro** [comment]
The build and `dotnet pack` commands run successfully and both targets were included in the package. It's just the problem with Nuget, not sure if it's related to the fact of including a different build in the package or not.

Also, please note that I'm pushing the packages from my local machine so the `PublishPackages` target won't work if the API keys are not installed.

**Comment by 0x53A** [comment]
I wanted to test whether there was an actual issue with the package, so I

1) modifed Fable.JsonConverter.fsproj to include the second framework
2) renamed it to 0x53A.Fable.JsonConverter.fsproj
3) deleted bin/obj
4) ``dotnet restore``
5) ``dotnet pack -c Release``
6) uploaded the nupkg via the web gui to nuget

Nuget accepted the package:
![image](https://cloud.githubusercontent.com/assets/4236651/25461081/3ec881b8-2ae7-11e7-91bd-488080682a6c.png)


I have unlisted it directly again, so that there is no confusion, just wanted to test whether the fsproj was correctly authored.

----------------

Anyway, the github dependency thing works well, so ...

**Comment by alfonsogarciacaro** [comment]
Sorry, I gave this a new try, I think the last time it happened because I didn't set the Nuget key properly (though the error message was misleading). But it seems I have no luck with this. Now I get:

```
/usr/local/share/dotnet/sdk/1.0.1/Microsoft.Common.CurrentVersion.targets(1111,5): error
 MSB3644: The reference assemblies for framework ".NETFramework,Version=v4.5" were not
found. To resolve this, install the SDK or Targeting Pack for this framework version or retarget
your application to a version of the framework for which you have the SDK or Targeting Pack
installed. Note that assemblies will be resolved from the Global Assembly Cache (GAC)
and will be used in place of reference assemblies. Therefore your assembly may not be 
correctly targeted for the framework you intend.
```

If you're still interested, could you please send a PR? Thanks!

**Comment by 0x53A** [comment]
Well, it did work on my computer, and I did just the same as you, so I don't think sending that as PR would make a difference ...

From the path, it looks like you use linux or osx? Any chance to retry on Windows and install something from here? http://getdotnet.azurewebsites.net/target-dotnet-platforms.html

I have absolutely no clue how targeting full-fx from the new sdk is supposed to work (it "just works" for me, on Windows with Visual Studio installed ...).

Anyway, __managing that file with paket works fine for me__, so from my side this can be closed as "resolved".

Thank you =)

**Comment by alfonsogarciacaro** [comment]
You're right. Yes I was on macOS, I'll try on Windows :+1:

**Comment by alfonsogarciacaro** [comment]
Sorry I finally had a moment to check this on Windows, I used the multiple `TargetFrameworks` property as you kindly described above and got many errors like those below when restoring with Paket (v5.1.6, cc @forki). However, apparently worked when restoring with Nuget. If you have moment, could you please if check the latest Nuget package works for your net45 project? Cheers!

**Comment by 0x53A** [comment]
Thanks, I did a quick test and it looks good. 👍

A different thing:

Do you really need the latest version of FSharp.Core and Newtonsoft?
![image](https://user-images.githubusercontent.com/4236651/27304561-b3a61ed8-553e-11e7-82f9-b8e35fd2839e.png)

It's not really an issue for me, I want to stay current as far as possible anyway, but in general libraries should rather target the lowest version they are compatible with.

**Comment by alfonsogarciacaro** [comment]
Thanks for the ultra-fast check @0x53A! 🏃 

You're right, it also crossed my mind for a moment but I just used the `dotnet add package` command and didn't think much about it. Which versions do you think should be good to target?

**Comment by alfonsogarciacaro** [comment]
Ok, after checking the listing for the dependencies I'm using FSharp.Core 4.1.17 (lower is not compatible with netstandard) and Newtonsoft.Json 9.0.1 (I think there was a bug with F# lists before that). That should be a bit better :+1:

**Comment by 0x53A** [comment]
Well, for me it would be FSharp.Core 4.1.0 and Newtonsoft.Json 9.0.1, because I had these versions before :D

In general I think it would be reasonable to support at the least versions that are 1/2 a year to a year old, so that would be FSharp.Core/4.0.0.1 and Newtonsoft.Json/8.0.3. But if it also works with Newtonsoft 4.x (from 2012), then why not target that?

**Comment by vasily-kirichenko** [comment]
1.0.6 targets netstandard1.6 only.

**Comment by alfonsogarciacaro** [comment]
Yes, sorry, this is a bit of pain. I don't have access to a Windows computer right now and targeting multiple frameworks doesn't work on macOS (see comment https://github.com/fable-compiler/Fable/issues/847#issuecomment-301086834 above) so for the last two releases I just removed the net45 framework, but didn't commit the change. I'd probably should do the publishing from Appveyor...

**Comment by alfonsogarciacaro** [comment]
The library it's a single file, so you can reference it in the meantime.

**Comment by vasily-kirichenko** [comment]
I've pinned it to 1.0.3 for now. No rush. Thanks.

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro I had the same problem when publishing from linux, however, if you set [this line](https://github.com/TheAngryByrd/MiniScaffold/blob/master/build.sh#L24) in your build.sh script then multi-targeting should work outside windows, given that you have mono as well. Not sure if it works the same macOS though

**Comment by alfonsogarciacaro** [comment]
Oh, it worked! 😮 Awesome, thanks a lot @Zaid-Ajaj! :clap: 🥇 👏

**Comment by alfonsogarciacaro** [comment]
Version 1.0.7 targets net45 again 👍

**Comment by vasily-kirichenko** [comment]
Thank you! :)
