### ISSUE TITLE
[Dev] Can't restore

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#848]
When I call paket restore:

![image](https://cloud.githubusercontent.com/assets/4236651/25350089/44782fd8-2924-11e7-8690-8dc23b7ea32c.png)

The error message seems correct, the project https://github.com/fable-compiler/Forge/ returns a 404.

**Comment by alfonsogarciacaro** [comment]
Which branch are you using? The Forge dependency is already removed from [latest master](https://github.com/fable-compiler/Fable/blob/7287cd7d053dc5a08299cdd5290248ced5c02b33/paket.dependencies).

**Comment by 0x53A** [comment]
Sorry, I messed up.

I had two different clones of fable, and was working on the old one.

**Comment by alfonsogarciacaro** [comment]
NP! Feel free to ask any question you may have :)
