### ISSUE TITLE
dotnet fable - allow an alternative to npm to be specified

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#857]
### Description
Various possibilities would open, but at the moment I have an issue:
`npm` being `.cmd` script under Windows [fails](https://github.com/npm/npm/issues/2938) when run from other scripts. I have a workaround I've been using with my build scripts where I lookup the node and use it to run the js directly, but fable running npm from inside of `dotnet` takes that away.

### Repro code
N/A

### Expected and actual results

I'd like to be able to specify the command to be used to execute the npm scripts.

### Related information 

* fable-compiler version: narumi
* fable-core version: n/a
* Operating system: Windows

**Comment by alfonsogarciacaro** [comment]
Recently `shell-run` was added to allow arbitrary execution. E.g. `dotnet fable shell-run node --args path/to/my/script.js`. Although [in Windows it still uses `cmd`](https://github.com/fable-compiler/Fable/blob/f25e57e84a7771eb1b46511142a71b1ef381975a/src/dotnet/Fable.Tools/Main.fs#L26-L28), so I'm not sure if it will solve your problem. (We could add an option to check if that's a true executable or not, before using `cmd`.)

You also have the option of starting the Fable server separately and the other process independently, [Fable tests do something similar](https://github.com/fable-compiler/Fable/blob/f25e57e84a7771eb1b46511142a71b1ef381975a/build.fsx#L401-L402).

**Comment by et1975** [comment]
Didn't know about `shell-run`, thank you, will try.

**Comment by et1975** [comment]
`shell-run` ignores the arguments, I'll try separate fable process.

**Comment by alfonsogarciacaro** [comment]
@et1975 Did you try using `--args`? It's not very intuitive but it's the only way I could think to differentiate between Fable args (like `--port`) and subprocess args. So, if you want to run `node myscript.js foo` from Fable, you should do this: `dotnet fable shell-run node --args "myscript.js foo"`.

**Comment by et1975** [comment]
Thanks, `shell-run` addresses the original request, so I've closed it. 

I still have a problem, but it's unrelated ...

**Comment by Pauan** [comment]
@alfonsogarciacaro I think the idiomatic way of handling this is to use `--` to separate the Fable args from the command args.

As an example, you would use `dotnet fable shell-run --port 8080 -- foo --bar --qux`

I'm not sure if that will work, though: `dotnet` might have its own custom handling of `--`

----

Alternatively, you could require arguments like `--port` to occur immediately after `shell-run`:

```
// Okay
dotnet fable shell-run --port 8080 node myscript.js foo

// Wrong
dotnet fable shell-run node --port 8080 myscript.js foo
```

That way there's no ambiguity between the args and the command.

**Comment by alfonsogarciacaro** [comment]
@Pauan That can work. I don't want to break current build scripts of users (although hopefully there are not many using this pattern yet). We can check if `--args` is being used and raise a warning, but something like `dotnet fable shell-run make --port free` is trickier to detect (as in theory `--port` could be an argument for `make`).

TBH, I didn't think it very much when quickly putting together the CLI. If this is more intuitive for users we can still change while we're in beta.
