### ISSUE TITLE
1.0 issues with Ionide

### ISSUE THREAD

**Issue by aolney** [fable-compiler/Fable#861]
### Description

Moving from 6.x to 1.0, some compatibility with Ionide in vscode seems to no longer work:
- `The namespace or module 'Fable' is not defined`

**I'm not sure if this is an Ionide problem or a configuration problem on the Fable side**

### Repro code

1. Clone [getting started repo](https://github.com/fable-compiler/fable-getting-started)
2. `yarn install` and `dotnet restore GettingStarted` etc
3. Open folder with vscode, open `Main.fs`

### Expected and actual results

- Ionide should not red underline "Fable" in `open Fable.Import`. In general namespace loading is broken even though code compiles. Is it due to shift of `fable-core` to pure js from dll?

### Related information 
```
    "fable-loader": "^1.0.0-narumi-912",
    "fable-core": "^1.0.0-narumi-914",
    "fable-powerpack": "^1.0.0-narumi-5",
```

* Operating system: duplicated on Debian unstable and Ubuntu 16.04

**Comment by alfonsogarciacaro** [comment]
I assume you're using latest Ionide, also be sure to have latest FSharp.NET.Sdk (you can update it using `dotnet restore --no-cache`). It seems sometimes Ionide takes a bit log before the language service starts working correctly. I'm not sure if it's an issue with the new project format or the F# project references (which take longer to resolve than .dll references).

Can you please make sure of the points above and try again?  Please also wait 1 or 2 minutes if intellisense is not working and check if the language service starts working after that time.

**Comment by aolney** [comment]
If `FSharp.NET.Sdk` is needed, that might be my problem. I've started using a docker image as a build environment. In that image, `FSharp.NET.Sdk` is in `$HOME/.nuget/packages`. When I run vscode, I'm on the host OS (Debian unstable), and Ionide has no access to `$HOME` on the guest OS. 

I did `dotnet restore --no-cache --packages .nuget/packages projfile` in the project directory and opened up in vscode, but the underline issue was not resolved. Should I be doing something else?

**Comment by alfonsogarciacaro** [comment]
If you're using containers and such this is starting to get out of my league ;) Pinging @enricosada in case he can help (he always does).

**Comment by aolney** [comment]
It works for me on Ubuntu 16.04, so I think it is a container or dotnet issue. Does vscode require dotnet to be installed, or can I just put the libraries on the correct path?

**Comment by alfonsogarciacaro** [comment]
@Krzysztof-Cieslak can confirm, but I think Ionide requires mono and probably the `dotnet` command to be in the PATH, meaning you can just unzip the dotnet SDK anywhere but then you should add the directory to your PATH before starting vscode.

**Comment by aolney** [comment]
Hmm... that all makes the container approach start to get ugly, as I then need to run vscode from the container and map X11, etc. I think I will abandon the container and just accept that every time I update sid it will break :)
