### ISSUE TITLE
FileSystem type provider

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#863]
Images are super important for Websites and React Native. Unfortunately only on runtime the links fail.
Can we somehow integrate the file system provider in fable or at least would it be possible to make it work?

/cc @alfonsogarciacaro @Krzysztof-Cieslak

**Comment by alfonsogarciacaro** [comment]
As type providers with Fable are somewhat borked because of the NET Core integration, we'll revisit this when F# type providers work with NET Core 2.0.

**Comment by forki** [comment]
"if"

Am 11.05.2017 21:42 schrieb "Alfonso Garcia-Caro" <notifications@github.com
