### ISSUE TITLE
adding a `dotnet new fable-vscode` template

### ISSUE THREAD

**Issue by acormier** [fable-compiler/Fable#867]
It's not clear how to setup a visual studio code extension project for Fable 1.0 but it seems that what's needed is a template that will create the structure of such a project.  Could such a template be created?  I don't know how to do this but I'm very happy to take it on with some guidance.

**Comment by MangelMaxime** [comment]
Hello, for creating a template you can take a look [here](https://github.com/fable-elmish/templates)

To create the template, you can then do `dotnet pack path/to/file.proj`
You can then install it by using: `dotnet new -i path/to/nugetfile` (the one generated by the previous command).

**Comment by acormier** [comment]
Thanks.  That's very useful.  Next step I have to figure out what files / structure / build scripts are needed for a vscode extension project

**Comment by alfonsogarciacaro** [comment]
It's using an old Fable version, but here's a post by @Krzysztof-Cieslak on building VS Code extensions with Fable: http://kcieslak.io/Creating-VS-Code-plugins-with-F-and-Fable

**Comment by acormier** [comment]
I did read that post.  Thanks.  I'm also looking at the Ionide source code.  I converted one of the vscode samples and I incorporated Paket and FAKE: [https://github.com/acormier/vscode-fable-sample](https://github.com/acormier/vscode-fable-sample).  I'm not sure if that's overkill or not.  Once I got the scaffolding figured out I could maybe make 2 templates.  One with Paket & FAKE and one without?  The biggest problem with my sample is that it's still using an old version of Fable.  If someone could tell me how to make it use Fable 1.0 that would be great.

**Comment by Krzysztof-Cieslak** [comment]
I doubt that Paket and FAKE are necessary at all.

**Comment by alfonsogarciacaro** [comment]
Nice. @acormier, there's a [blog post](http://fable.io/blog/Introducing-1-0-beta.html) about using Fable 1.0 beta. You can see Fable 1.0 templates [here](https://github.com/fable-compiler/Fable/tree/290a7b7b94dd8304319b514205bbe6c03f1da2ea/src/templates/simple) (simple) and [here](https://github.com/fable-elmish/templates/tree/master/src/react) (fable-elmish-react, more complex).

About Paket, we're currently considering better integration between Paket and Fable but it's not done yet. About FAKE, it depends. For simple things like building and starting a Webpack dev server, the dotnet-fable CLI tools should be enough. If you need more complex stuff FAKE can indeed very useful.

**Comment by acormier** [comment]
Hi.  Thanks for the feedback.  I'm still confused about how to hookup the fable compiler and how webpack (I never used it before) fits into all this.  I update the project (https://github.com/acormier/vscode-fable-sample) to try to use Fable 1.0 but I'm getting a "The namespace 'vscode' is not defined" error.  Is there something wrong with my paths or with Fable.Import.VSCode.fs? (I'm using the one from Ionide).
Alain

**Comment by alfonsogarciacaro** [comment]
Hmm, probably @Krzysztof-Cieslak can confirm, but I think you need to [tell Webpack not to put the `vscode` module in the bundle](https://webpack.js.org/configuration/externals/). You can do this by adding the following to the Webpack config:

```js
  externals: {
    vscode: 'commonjs vscode'
  },
```

I'll try to clone your project later and see if I can make it work :+1:

**Comment by acormier** [comment]
Thanks.  Much appreciated.

**Comment by acormier** [comment]
@alfonsogarciacaro , I added the webpack config like you suggest above plus added libraryTarget: commonjs2 like suggested by @vasyl-purchel and the sample now runs!  Thanks everyone.

**Comment by acormier** [comment]
I created a very simple sample that doesn't use Paket or FAKE.  I defined vscode tasks for fetch (get dependencies), clean, and build: https://github.com/acormier/vscode-extension-fable-simple.

I tried creating a template but couldn't get it to work.  I'll get back to it when I have more time.

**Comment by alfonsogarciacaro** [comment]
Awesome @acormier, thanks for that! A template would be nice, but I guess a repo is fine for now. Could you please send a PR to add a link to [awesome-fable](https://github.com/kunjee17/awesome-fable)?

**Comment by alfonsogarciacaro** [comment]
As we already have the sample repo working, we can close this issue 😄 It'd be great to include a link in awesome-fable repo to improve visibility within the Fable community :+1:
