### ISSUE TITLE
Fable doesn't use fableconfig.json automatically

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#871]
### Description

Until 0.7.45 fable.cmd was using the fableconfig.json file that was lying around in current dir. With 0.7.46 and above it doesn't anymore. This breaks our builds.

### Related information 

* fable-compiler version: 0.7.46 and above
* Operating system: win

**Comment by forki** [comment]
http://fable.io/docs/compiling.html#fableconfig-json 

> "If you omit the path, the compiler will assume it's in the current directory."

**Comment by MangelMaxime** [comment]
@forki Should be fixed in Fable 0.7.51

Can you please confirm ?

**Comment by forki** [comment]
confirmed, fixed. thanks
