### ISSUE TITLE
Fable release doesn't push tags to github

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#872]
### Description

it's extremely hard to see what changed between two releases if we don't push tags to github.

**Comment by alfonsogarciacaro** [comment]
@fable-compiler/infrastructure 

There's a [FAKE target here](https://github.com/fable-compiler/Fable/blob/cbe501695e115f3c7ca179ab98d1864434f8b80e/build.fsx#L494) which I basically copied from FCS repo, we can adapt that.

**Comment by alfonsogarciacaro** [comment]
Anybody from the @fable-compiler/infrastructure team volunteering for this?

**Comment by leolorenzoluis** [comment]
I can take a look at it. @alfonsogarciacaro  Do you already have an idea in mind on how you want to implement this? I assume it's not just doing Github tags, but also reading the md files for the release notes?

**Comment by alfonsogarciacaro** [comment]
Awesome @leolorenzoluis, thanks! I don't have any idea specifically. The most important thing is the tags so we can make git diffs when we find a regression bug after a new version is published. Reading the release notes would be nice. As we'll be pushing the 3 Nuget packages at the same time (and I also plan to put the fable-core JS files directly into the Fable.Core nuget package), maybe it's easier to merge the release notes files (currently there's one release notes file, all in the repo root, for each of the packages).

About uploading a binary or the nuget package to Github I don't think it's very important for now.

**Comment by forki** [comment]
If you look into paket's own build script you can see how to create git
tags, github tags and how to upload files and release notes to github.

Am 11.05.2017 11:37 nachm. schrieb "Alfonso Garcia-Caro" <
notifications@github.com>:

**Comment by leolorenzoluis** [comment]
Thanks @forki. I assume it is just on build.fsx, but do you have some specifics where I can look at? Is it just the "ReleaseGithub"?

**Comment by forki** [comment]
Yeah only build.fsx

Am 12.05.2017 7:05 nachm. schrieb "xyz" <notifications@github.com>:

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro This one can be closed, right?

**Comment by alfonsogarciacaro** [comment]
That's right @Zaid-Ajaj, thanks for pointing it out!
