### ISSUE TITLE
Fable 0.7.50 goes automatically into watch mode and no way to disable that

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#873]
In don't have watch mode enabled in the fableconfig.json but:

![watch](https://cloud.githubusercontent.com/assets/57396/25698932/4710e592-30c1-11e7-824b-b1ca5e6dcfd7.png)

**Comment by forki** [comment]
Note downgrade to 0.7.45 works

**Comment by alfonsogarciacaro** [comment]
can you post the fableconfig.json?

**Comment by forki** [comment]
{
            "module": "commonjs",
            "ecma": "es2015",
            "outDir": "out",
            "sourceMaps": true,
            "projFile": "src/msuReading.fsproj", 
            "refs": {
                "Fable.Core": "fable-core/umd",
                "Fable.PowerPack": "fable-powerpack/umd",
                "Fable.React": "fable-react/umd",
                "Fable.Elmish": "fable-elmish/umd",
                "Fable.Elmish.React": "fable-elmish-react/umd"
            }
        }

nothing sepcial...

**Comment by MangelMaxime** [comment]
@forki Should be fixed in Fable 0.7.51

Can you please test ?

**Comment by forki** [comment]
confirmed, fixed. thanks
