### ISSUE TITLE
Maintainers wanted dead or alive! (But preferably alive.)

### ISSUE THREAD

**Issue by alfonsogarciacaro** [fable-compiler/Fable#874]
We're looking for core maintainers of the Fable compiler. Right now we have many wonderful contributions from the community but we cannot say there is any other core maintainer than me, and that's something very important for the survival of the project. Also I'm currently somewhat overwhelmed by work, OSS, conferences and other personal stuff, and I'm starting to realize I cannot keep constant Fable evolution just by myself.

I keep telling myself that once the tool stabilizes I'll work on the developer documentation to make it easy for contributors to jump in, but with the constant suggestions from the community to improve the tooling (which is something very good) this is something that obviously won't happen any time soon. Managing a successful OSS project is fairly new to me and I'm sure I've made tons of mistakes that have caused the current situation in which my direct intervention is needed in almost every part of the Fable ecosystem (with the happy exception of fable-elmish). We need to change that.

This is not to say I want to step down as a maintainer, I'll still be here doing as much as I can. But it's important to start transferring the knowledge so it's not only me taking always all the decisions so we can be sure things keep on track in the moments when I don't have much time available for OSS.

You don't need to know the project that well, I will help you with that. Of course it's necessary that you have interest in it and also that you're willing to support the community. If you always wanted to know how driving a community feels like, this is your chance. Fable welcomes you!

**Comment by MangelMaxime** [comment]
I am interested in helping on Fable compiler side.
I sent you a message on gitter about that :)

**Comment by clarenced** [comment]
Hi, I am not a F# developer but I have functional programming like Ocaml, Scala. I am also a JS developer. How can I help ?

**Comment by Zaid-Ajaj** [comment]
I am in :smile:

**Comment by nelak** [comment]
I can try and give a hand with development

**Comment by andredublin** [comment]
Count me in!

**Comment by whitetigle** [comment]
I'm not quite the best fit for the compiler side, however quoting you

> I'll work on the developer documentation to make it easy for contributors to jump in

would any help be needed with the documentation and bindings and samples, count me in!

**Comment by et1975** [comment]
As a maintainer, does one get to discover the secret identity of @ncave ?

**Comment by forki** [comment]
I think we should all chip in to get him to FableConf

Am 04.05.2017 8:20 nachm. schrieb "Eugene Tolmachev" <
notifications@github.com>:

**Comment by ncave** [comment]
Thank you, a little bit overblown perhaps, but not really a secret anymore ever since Marcus [nailed it](https://twitter.com/neoeinstein/status/851569628568584194) :).
But back on topic, I'd also gladly share some responsibility for projects in this org, even though, you know, too many cooks, etc.

**Comment by jgrund** [comment]
I'd like to help out as well

**Comment by rkosafo** [comment]
I'm in.

**Comment by alfonsogarciacaro** [comment]
Thanks a lot everybody for volunteering. I'm thinking we can create four teams for different maintenance aspects. Please tell where would you like to contribute and I'd add them to the teams.

- **Infrastructure**:
  Make the structure of the repo easier to contribute and maintain, build scripts, CI, package publishing, etc. For example, this related issue is very important at the moment: #872

- **Web, documentation, samples**:
  Update the web using Fable itself and making it easier to add samples (like the fable-arch site), update the documentation to Fable 1.0 (I'll take care of this for now), write and keep samples documented and up-to-date, etc.

- **Code maintenance**:
  Getting to know well the code base (it's actually not that complicated) for bug fixing and implementing new features. I'll improve the internal documentation and provide guidance for this team.

- **Community support and long term planning**:
  Taking the pulse of the community to decide where the development resources should be focused on and elaborating a roadmap for the project (related issues right now: #856, #868)

Of course, these won't be isolated teams as they'll have to collaborate in many situations. If you can think of another way of organizing things please tell me. Also note, that there are other tasks pending that are not directly related to the core maintenance but are very important for the community, like [improving ts2fable](https://github.com/fable-compiler/ts2fable/issues/1) or writing a [React Native package](https://github.com/fable-compiler/Fable/issues/804), so help there would also be very appreciated.

**Comment by MangelMaxime** [comment]
Count me for the code maintenance :)

**Comment by rkosafo** [comment]
Code maintenance for me. I could help out with documentation and samples later.

**Comment by whitetigle** [comment]
Web,doc,samples for me :)

**Comment by ChrisDobby** [comment]
I'll volunteer for web, doc and samples....




Get Outlook for Android







On Sun, May 7, 2017 at 11:21 AM +0100, "Whitetigle" <notifications@github.com> wrote:












Web,doc,samples for me :)



—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or mute the thread.


  
  







______________________________________________________________________

This email has been scanned by the Symantec Email Security.cloud service.

For more information please visit http://www.symanteccloud.com

______________________________________________________________________







______________________________________________________________________
This email has been scanned by the Symantec Email Security.cloud service.
For more information please visit http://www.symanteccloud.com
______________________________________________________________________

**Comment by johlrich** [comment]
I can help with docs / samples as well

**Comment by jgrund** [comment]
Please add me for code maintenance and community support.

**Comment by gfritz** [comment]
I'd like to start in infrastructure. Build scripts are somehow interesting.

**Comment by ncave** [comment]
Code maintenance, if it's not already too crowded.

**Comment by mizzle-mo** [comment]
Community Support/Roadmap for me, but I would like to stay looped in with all the teams.  I think it would be helpful to have a monthly or bi-weekly (better) call to discuss the roadmap and have @alfonsogarciacaro demo/explain different parts of the infrastructure and code so everyone can get up to speed more quickly and have the opportunity to ask questions in real-time.  Thoughts?

**Comment by leolorenzoluis** [comment]
Infrastructure, Web, documentation, samples or code maintenance for me.

**Comment by alfonsogarciacaro** [comment]
@mizzle-mo I think having meetings once or twice a month is a good idea. I don't mind using a call/chat tool, but ideally we should have some summary recorded somewhere. Does anyone know an easy way to do that?

**Comment by alfonsogarciacaro** [comment]
Thanks a lot everybody for volunteering! ❤️  I already created the teams so I'm closing this issue. I will be mentioning the teams from now on in different issues to cry for help ;)

If you didn't receive the invitation please check [the fable-compiler org page](https://github.com/fable-compiler) or comment again in this issue.

**Comment by nelak** [comment]
I missed the updates to this thread, count me in for code maintenance

**Comment by Krzysztof-Cieslak** [comment]
Where is evangelization team? ;]

**Comment by alfonsogarciacaro** [comment]
@Krzysztof-Cieslak That's a good one! I actually thought everybody in the F# community was already a Fable evangelist ;) Maybe this could be one of the responsibilities of the community team? In any case, at the moment the best evangelization effort we can do is promoting FableConf :)
