### ISSUE TITLE
Cache output of Fable compiler

### ISSUE THREAD

**Issue by Pauan** [fable-compiler/Fable#882]
Right now, whenever doing a build of a Fable project, it will compile everything from scratch, including your code and library code.

Webpack's watch mode helps out a lot, but every time you restart watch mode it has to compile everything from scratch again.

This is especially a problem if you have many libraries, because even though the library code hasn't changed at all, it still has to be recompiled, which makes the initial startup time for watch mode very long.

Therefore, I propose to cache the JavaScript output of Fable, so that way if a file hasn't changed, it can simply use the cache. This should speed up build times significantly.

This caching is done in the application, not in the library, so the behavior should be backwards compatible, and it doesn't put additional pressure on library authors.

**Comment by Pauan** [comment]
From @alfonsogarciacaro:

> That said, if you want to improve full recompilations, we can try to do some caching as @Pauan suggested. I guess the easiest way to do it for now would be to keep a copy of the [transformed code](https://github.com/fable-compiler/Fable/blob/7217e20b7d9ea8f6c0ad465343fd021af4722c61/src/typescript/fable-loader/index.js#L99-L100) somewhere and then [when Webpack requires compilation of an F#](https://github.com/fable-compiler/Fable/blob/7217e20b7d9ea8f6c0ad465343fd021af4722c61/src/typescript/fable-loader/index.js#L39) check if a cache exists and if the timestamp is more recent than the F# source.

**Comment by jmmk** [comment]
https://github.com/s-panferov/awesome-typescript-loader might be a good reference

**Comment by alfonsogarciacaro** [comment]
Someone from @fable-compiler/code-maintenance volunteering for this? ;)

I think we can follow @jmmk and follow the typescript loader to implement the cache in the fable-loader :+1:

**Comment by alfonsogarciacaro** [comment]
I just remember one important thing, just comparing timestamps of files is not enough for the cache because of inline functions. Imagine this situation:

```
File A
File B (calls inline function of A)
```

If we compile once, B gets cached, but if later we modify the inline function in A, we want B to be recompiled again too (if we just check the file timestamp this won't happen as B hasn't changed).

This means we need to keep the list of project files and every time a file changes, we must also invalidate all the other files down the list.

> We should also provide a --no-cache function when something external like a plugin has changed.

**Comment by Pauan** [comment]
@alfonsogarciacaro Yes, but it may only need to keep track of the dependencies in the case of inline functions, which are rare. So most of the time we get to use the fast path.

If you wanted to get extremely fancy, you can have it cache *expressions* rather than files. A file would be a list of expressions.

When an inline expression changes, all expressions that use that expression will be recompiled. This means that it can cache as much as possible, since it can cache the parts of the file which haven't changed.
