### ISSUE TITLE
interacting.md

### ISSUE THREAD

**Issue by ImaginaryDevelopment** [fable-compiler/Fable#889]
### Description

https://github.com/fable-compiler/Fable/blob/master/docs/source/docs/interacting.md
says it is only for 0.6.0 and for migration I should click the https://github.com/fable-compiler/Fable/blob/master/docs/source/blog/Introducing-0-7.html link, which is dead.

### Expected and actual results

I click the link and it goes to a migration guide

Instead I get a 404

**Comment by alfonsogarciacaro** [comment]
Ups, the link is for the web, [it should work there](http://fable.io/docs/interacting.html). Actually, we have already released Fable 1.0 beta. You can also find a [post about it](http://fable.io/blog/Introducing-1-0-beta.html) in the blog.

Yeah, we need to update the docs, sorry! 😅 Actually the way to interact with JS hasn't changed much. You can also read [this article](https://medium.com/@zaid.naom/f-interop-with-javascript-in-fable-the-complete-guide-ccc5b896a59f) by @Zaid-Ajaj for more info.
