### ISSUE TITLE
Error: "Can't find variable: performance" on Safari

### ISSUE THREAD

**Issue by inosik** [fable-compiler/Fable#902]
### Description

When I try to use to the REPL on my Mac with Safari or on my iPhone (followed a link on Twitter 😄), I get the error message "Can't find variable: performance" from [worker.js:58:37][code-line]. That's strange, because this variable exists in the developer tools console and I can use `performace.now()`, for example.

  [code-line]: https://github.com/fable-compiler/Fable/blob/2888fe0391755ee1001735c3a8709c1f3ebdbea2/src/dotnet/Fable.Client.Browser/demo/worker.js#L58

### Repro

Try to use the REPL with Safari on macOS, apparently. Chromium works fine.

### Expected and actual results

I'd expect that the REPL works, instead I get the error message, mentioned above.

### Related information 

* fable-compiler version: REPL
* fable-core version: Whatever the REPL uses
* Operating system: macOS 10.12.4 with Safari 10.1 (12603.1.30.0.34)

**Comment by alfonsogarciacaro** [comment]
Thanks for the tip! That's what I love of JS, write once and run everywhere ;) It fixed it, the REPL is running on Safari now :+1:
