### ISSUE TITLE
Where to put external binding contributions

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#911]
Where is the best place to put external binding contributions?

I see that some have their own repos under this org, but is that an approach that would scale for many libs?

Should we:

a) Have something like DefinitelyTyped where all interfaces are grouped together?
b) Just push them individually and have them discoverable via yarn / npm?

**Comment by MangelMaxime** [comment]
I think @mizzle-mo is working at the moment on something equivalent to DefinitelyTyped and @typed behavior provided by npm/ts

**Comment by mizzle-mo** [comment]
@jgrund Not even close to being ready yet, but you can PR here if you want.  Right now it is just all the ones I could find dumped in a repo, but the idea is to get it working similar to the TypeScript ecosystem.

https://github.com/fable-typed/types

**Comment by alfonsogarciacaro** [comment]
So far I've been encouraging Fable binding authors to have their own repo so they take more responsibility in maintaining them 😉 But I do agree it's much better for the visibility of the binding to have them in a single repo.

In any case, we need to improve ts2fable so most of the work can be done automatically and the maintenance overhead is minimal. Ideally, as @mizzle-mo envisioned, we should be able to run ts2fable periodically against the 100-200 most popular declarations in DefinitelyTyped.

**Comment by jgrund** [comment]
@alfonsogarciacaro @mizzle-mo  Sounds good. 

Running periodically makes sense, but what about wanting / landing changes that are not in the upstream ts interfaces? 

I guess in that model, one would push for changes to the ts interfaces, that would get pulled back into fable bindings.

**Comment by alfonsogarciacaro** [comment]
Yes, we could probably add an option to ts2fable to leave manually edited parts of the bindings untouched, so we can freely update the bindings from latest Typescript declarations.
