### ISSUE TITLE
Unable to run `dotnet fable npm-run start`: "The given path's format is not supported" [1.0 beta]

### ISSUE THREAD

**Issue by pittsw** [fable-compiler/Fable#912]
### Description

I was able to make a new Fable project using the template system, add fable-elmish and its various dependencies, and get it working just fine.  Then I switched to a new local clone of my repo, and I get this error ([full log here](https://github.com/fable-compiler/Fable/files/1003379/scratch.txt)):

```
ERROR in ./src/App.fs
Module build failed: Error: The given path's format is not supported. (c:\Users\Will\Projects\Practice\fable\carwars\src\App.fs)
    at client.send.then.data (c:\Users\Will\Projects\Practice\fable\carwars\node_modules\fable-loader\index.js:55:26)
```

I then created a new Fable project following the instructions at http://fable.io/blog/Introducing-1-0-beta.html, and was able to successfully build.

Since my git clone couldn't build but my new project from scratch could, I checked my files to see if I had missed adding any to git, but both projects have the following files:
* `projectname.fsproj`
* `package.json`
* `README.md`
* `webpack.config.js`
* and then the various `src/` files

So now I'm not sure what it is, since that seems like it would be the most likely difference between a newly-created project and one cloned from git.

### Repro code

I'm not sure what would really be a good repro here other than following these (unfortunately manual) steps:
* Create a new Fable project
* Add it to git
* Clone that project
* Build

### Expected and actual results

Expected results: the project should build.
Actual results: the project fails with an exception in `Path.GetFullPath()`

### Related information 

* fable-compiler version:  N/A
* fable-core version:  ^1.0.0-narumi-905
* Operating system:  Windows 10 Creators Update

**Comment by MangelMaxime** [comment]
Hello @pittsw would it be possible to share the repo giving this error ?

Like so we would have the same environnement :)

**Comment by pittsw** [comment]
Oh, right.  That would be useful.  Here's my zipped project (with all dependencies too): [link](https://1drv.ms/u/s!AsAsWqAjuFFusvUc3MlIFQwTEAsPbQ).  I made a full zip because I figured that would be more useful because it would have everything self-contained, but I can also share just the code with you if you don't want to download a 40 MB zip file.

To repro, just extract then run `dotnet fable npm-run start`.  You might need to `dotnet restore`, but you shouldn't need to `npm install`.

I also noticed that the error message is different based off whether I'm running in VS Code or not.  When I run in VS Code, I get the invalid path exception called out above.  When I run directly in PowerShell, I get this error instead:

```
ERROR in ./~/fable-elmish/cmd.fs
Module not found: Error: Can't resolve '../../../../../../.nuget/packages/fsharp.core/4.1.17/fable-core/Async' in 'C:\Users\Will\Projects\Practice\scratch\carwars\node_modules\fable-elmish'
 @ ./~/fable-elmish/cmd.fs 3:0-115
 @ ./~/fable-elmish/program.fs
 @ ./src/App.fs
 @ ./carwars.fsproj
 @ multi (webpack)-dev-server/client?http://localhost:8080 ./carwars.fsproj
```

Full log available [here](https://github.com/fable-compiler/Fable/files/1005042/log.txt).

**Comment by alfonsogarciacaro** [comment]
We have update the Elmish template, could you please give it a try and check if it works now?

```shell
# Install template, only first time (quote the last arg if necessary)
dotnet new -i Fable.Template.Elmish.React::*

# Create a project
dotnet new fable-elmish-react -n MyProject

# Follow the instructions in the README
cd MyProject
yarn install
dotnet restore
dotnet fable npm-run start
```

**Comment by pittsw** [comment]
This isn't serious, right?  Got it from `yarn install`:

```
warning fsevents@1.1.1: The platform "win32" is incompatible with this module.
```

Everything else works.  Thanks!

**Comment by alfonsogarciacaro** [comment]
Great, thanks a lot for the confirmation!

Yes, the `fsevents` module is always giving warnings, not sure why and even where the module comes from. But it doesn't seem to be a problem :)
