### ISSUE TITLE
Passing tuple as an arg type expands parameters

### ISSUE THREAD

**Issue by jgrund** [fable-compiler/Fable#920]
Not sure if this is expected behavior or not but passing:

```
type TupleType =  string * string
let fn a (b:TupleType) = b
```

Yields:

```
export function fn(a, b_0, b_1) {
  const b = [b_0, b_1];
  return b;
}
```

Given that, I'm not sure how to pass in a parameter that is a tuple without effecting function arity.

**Comment by Pauan** [comment]
It's possible to workaround this by using `System.Func`:

```fsharp
type TupleType = string * string
let fn = System.Func<'a, TupleType, TupleType>(fun a b -> b)

let x = ("foo", "bar")
fn.Invoke(1, x)
```

But this generates really inefficient code:

```js
export function fn() {
  return function (a, b) {
    return b;
  };
}
export const x = ["foo", "bar"];
fn()(1, x);
```

Notice that it recreates the `fn` function every time it's called.

**Comment by jgrund** [comment]
@Pauan Thanks much.

**Comment by Pauan** [comment]
It's also possible to use tupled arguments to the function, which is a lot less verbose than `System.Func`:

```fsharp
type TupleType = string * string
let fn(a: 'a, b: TupleType): TupleType = b

let x = ("foo", "bar")
fn(1, x)
```

This generates the following JS code:

```js
export function fn(a, b) {
  return b;
}
export const x = ["foo", "bar"];
fn(1, x);
```

These are the key differences:

* `let fn (a: 'a) (b: TupleType): TupleType = b`
* `let fn(a: 'a, b: TupleType): TupleType = b`
