### ISSUE TITLE
Unable to run example app

### ISSUE THREAD

**Issue by KarandikarMihir** [fable-compiler/Fable#921]
I'm trying to run [`react-todomvc`](https://github.com/fable-compiler/Fable/tree/master/samples/browser/react-todomvc). When I fire up the server it says-

>Uncaught Error: Module build failed: Error: connect ECONNREFUSED 127.0.0.1:61225
Make sure Fable server is running on port 61225

Repro steps-
1. Download example apps folder
2. Run `npm install fable-compiler -g`
3. Run `npm install` in the [root folder](https://github.com/fable-compiler/Fable/tree/master/samples).
4. Run `npm install` in [react-todomvc](https://github.com/fable-compiler/Fable/tree/master/samples/browser/react-todomvc).
5. Run `npm run build`.
6. Run `npm start`

**Comment by MangelMaxime** [comment]
@KarandikarMihir

We are in the process of updating the samples. To the latest version of Fable. In the current state of the sample, I believe there is no easy way to make it run. Sorry for the inconvenience.

Was you interested only in this sample ? Or more in playing with Fable ?

**Comment by KarandikarMihir** [comment]
@MangelMaxime Thanks for the prompt reply! 

No, any running example would work. I'm just playing around 😄

**Comment by alfonsogarciacaro** [comment]
Sorry, we're integrating with Paket at the moment and unfortunately a couple of broken versions (for Fable 1.0 beta) were released. I've just pushed a new template and this is probably the best way to start playing with Fable, could you please give it a try?

```shell
# Install template, only first time (quote the last arg if necessary)
dotnet new -i Fable.Template::*

# Create a project
dotnet new fable -n MyProject

# Follow the instructions in the README
cd MyProject
yarn install
dotnet restore
dotnet fable npm-run start
```

**Comment by KarandikarMihir** [comment]
@alfonsogarciacaro Okay I'll give it a try today. Thanks for all the awesome work btw! :)

**Comment by Zaid-Ajaj** [comment]
@KarandikarMihir I assume this is solved and will close the issue. You can find the updated samples (for Fable 1.0-beta) [here](https://github.com/fable-compiler/samples)
