### ISSUE TITLE
React attribute is not list-wrapped when it should be in compiled javascript

### ISSUE THREAD

**Issue by prozacchiwawa** [fable-compiler/Fable#928]
### Description

When I use List.concat to concatenate an empty list with a list containing a react attribute, concatenating the lists fails in List.concat.

### Repro code

https://gist.github.com/prozacchiwawa/672ffcde2d511749e7fd0699fb7c5445

### Expected and actual results

Expected to execute properly and render an li element.

Actually got an exception:

Seq.js:255 Uncaught TypeError: xs[Symbol.iterator] is not a function
    at fold (Seq.js:255)
    at reverse (List.js:57)
    at append (List.js:10)
    at List.js:20
    at fold (Seq.js:259)
    at collect (List.js:20)
    at concat (List.js:23)
    at view (test.js:12)
    at test.js:24
    at Object.render (common.js:69)

### Related information 

* fable-compiler version: 0.7.50
* fable-core version: 0.7.30
* Operating system: fedora-25

**Comment by Zaid-Ajaj** [comment]
@prozacchiwawa Hi there
React attributes are represented as lists in code but are compiled to object literals because it is very convenient to do so. concatenation as lists won't work by design. You should use native `Object.assign` if you want to concatenate React attributes:

```fs
open Fable.Core.JsInterop
open Fable.Core

[<Emit("Object.assign({ }, $0, $1)")>] 
let (++) (x: 'a list) (b: 'a list) = jsNative

// then
[ ClassName "fancy" ] ++ [ Key "some-key" ]
```

**Comment by prozacchiwawa** [comment]
Ahh sorry.  It'd be nice if they were a different type in that case though.

**Comment by prozacchiwawa** [comment]
In defense of ceremony, that's kind of what one signs up for writing a
typed language.  I might be alone, but i expect runtime exceptions to be
rare in well-typed code.  Would you consider a change that used a
camlp4-like preprocessor to make a specialized list with a different brace
style (like [< ... >] for streams in ocaml)?

**Comment by alfonsogarciacaro** [comment]
Hi there! Your concerns are valid, @prozacchiwawa, and actually the behaviour of React attributes is changing in Fable 1.0 so they remain an actual F# list (so operations like concat are possible) until being sent to React. Can you please try with the latest `Fable.Template.Elmish.React`?
