### ISSUE TITLE
Express: The namespace or module 'http_types' is not defined.

### ISSUE THREAD

**Issue by aolney** [fable-compiler/Fable#931]
### Description

In updating the express sample to Fable 1.0 with Paket, `dotnet fable npm-run build` yields two types of errors:

- `unknown(1,0,1,0) : warning FSHARP: p_typar_spec: from error`
- `Fable.Import.Express.fs(76,16,76,26) : error FSHARP: The namespace or module 'http_types' is not defined.`

### Repro code

I made a [minimal example](https://github.com/aolney/fable-express-sample)

### Expected and actual results

Code should compile without errors; errors are thrown. Previously `fable-import-express` worked with 1.0 narumi, so suspect Node related refactoring in fable-compiler might be the cause.

### Related information 

* fable-compiler version: 1.0.4?
* fable-core version: 1.0.4
* Operating system: Debian unstable.

**Comment by alfonsogarciacaro** [comment]
Yeah, sorry, we're updating the Node bindings and we're breaking some things in the process 😅 But hopefully the result will be much cleaner, it should be ready in a few days 😸

**Comment by aolney** [comment]
If there's anything I can do to update `Fable.Import.Express.fs` to match your efforts with Node, just let me know.
