### ISSUE TITLE
How to reference local build?

### ISSUE THREAD

**Issue by jmmk** [fable-compiler/Fable#932]
In https://github.com/fable-compiler/Fable/pull/884, @MangelMaxime asked about using a local build of Fable, and @forki mentioned that it might be possible to use [paket.local](https://fsprojects.github.io/Paket/local-file.html) for this.

In the documentation they give an example based on a `NuGet` target in the FAKE script which generates a NuGet package that can then be referenced. Fable has no such target, and the NuGet build seems to be nested inside `pushNuget`, which is part of the `PublishPackages` target.

Now that Fable is using Paket, what's the best way to install a custom build into a project (for testing purposes or otherwise)?

**Comment by mizzle-mo** [comment]
I think it would be helpful to put together some contributing docs and include this with the move to Paket.

**Comment by alfonsogarciacaro** [comment]
I think in #884 @MangelMaxime was talking about referencing other projects locally as if they were packages. But if you want to use a version of the Fable compiler build locally you can take a look at the [QuickTest](https://github.com/fable-compiler/Fable/blob/8253562eedf2a4abb1d498b747f070d085260ecf/src/tools/QuickTest.fsx). The only thing you need to do is [call directly the `dotnet-fable.dll`](https://github.com/fable-compiler/Fable/blob/8253562eedf2a4abb1d498b747f070d085260ecf/build.fsx#L404) and if you also want to a local fable-core, [pass the path to the Fable options](https://github.com/fable-compiler/Fable/blob/8253562eedf2a4abb1d498b747f070d085260ecf/src/tools/rollup.config.js#L17) :+1:

**Comment by jmmk** [comment]
@alfonsogarciacaro I'm not sure I understand. I'll try to clarify exactly what I'm asking:

- I have a `paket.dependencies` that includes `nuget Fable.Core` and a `paket.references` that includes `Fable.Core`

- I have cloned the Fable repository, and I want to make a change to `Fable.Core` and test that change in the context of my project

What's the best way to: 

1. build `Fable.Core` locally

2. Reference this local `Fable.Core`in another project?

**Comment by alfonsogarciacaro** [comment]
Ok, that's more or less the same :+1:

> build Fable.Core locally

After cloning the project, if you touch any of the dotnet files, run `build FableTools`. If you touch any of the fable-core Typescript/JS files, run `build FableCoreJs` (in the latter case remember to pass the fableCore path to the loader options).

> Reference this local Fable.Corein another project?

Just remove `Fable.Core` from your paket.dependencies and add a direct reference to the library, [as the Fable tests do](https://github.com/fable-compiler/Fable/blob/8253562eedf2a4abb1d498b747f070d085260ecf/src/tests/Main/Fable.Tests.fsproj#L7-L9).

I hope this helps you, please tell me if you have more questions :)

**Comment by 0x53A** [comment]
> Just remove Fable.Core from your paket.dependencies and add a direct reference to the library, as the Fable tests do.

The paket.local feature is there so that changing paket.dependencies is not required. (https://fsprojects.github.io/Paket/local-file.html)

I think it would be enough to just separate the nupkg creation and the push in the fake script into two targets. That way a local build can create the nupkg and paket can then reference that.
