### ISSUE TITLE
Fable can't build more than 3 project at a time

### ISSUE THREAD

**Issue by MangelMaxime** [fable-compiler/Fable#940]
### Description

I am working on the http://github.com/fable-compiler/samples repo.
Where we are compiling a lot of project at the same time in webpack.

When I have more than [3 projects active](https://github.com/fable-compiler/samples/blob/migrate-samples/webpack.config.js#L21) in webpack.config.js then fable failed to compile and seems to mess up the files between the project.

### Repro code

Try to build [migrate-samples](https://github.com/fable-compiler/samples/tree/migrate-samples) branch from the samples repo.

### Example of error

```
ERROR in ./ozmo/Main.fs
Module build failed: 
Error: File C:/Users/mange/Workspace/Github/fable-compiler/samples/ozmo/Main.fs 
doesn't belong to parsed project 
C:\Users\mange\Workspace\Github\fable-compiler\samples\samegame\SameGame.fsproj (C:/Users/mange/Workspace/Github/fable-compiler/samples/ozmo/Main.fs)
```

**Comment by forki** [comment]
"doesn't belong to parsed project" ;-)

**Comment by MangelMaxime** [comment]
@forki I think this is a side effect.
If I try to compile, each sample one by one, or 3 by 3 (in whatever combinaison) the compilation is working.

**Comment by alfonsogarciacaro** [comment]
This is weird, [the error message changed](https://github.com/fable-compiler/Fable/blob/c6b76f80655442e3c68f53028eaad110d93406ee/src/dotnet/Fable.Tools/State.fs#L245) when parallel compilation was added. But you're using 1.0.4, right? Can you please check with `dotnet fable --version`?

**Comment by MangelMaxime** [comment]
Yes I am using `1.0.4`

**Comment by alfonsogarciacaro** [comment]
It's too hot in Madrid and I can't sleep so I didn't find anything better to do than fixing this :wink: With latest Fable build, now all samples can build in parallel :smile: Thanks a lot for migrating them and also for the index.html, @MangelMaxime :+1:

Note to myself: Immutable structures, Alfonso, we're using F# for a reason.

BTW, @MangelMaxime, when reproducing the issue with your migrate-samples branch, the `dotnet restore Fable.Samples.sln` command didn't work (dotnet SDK 1.0.4 on macOS) so I had to restore all projects individually 😕

**Comment by MangelMaxime** [comment]
Thanks for the fix, I will test it :)

Strange `dotnet restore Fable.Samples.sln` that don't work for you... I will test it again under windows just to be sure.

And we can always go back to listing all the `.fsproj` in the batch file.

**Comment by MangelMaxime** [comment]
Restoring via the sln work on windows seems to work under windows.

Perhaps there is a bug on Unix systems ? To be sure, I will list all the fsproj into the `.sh` and `.cmd` file. Not like it's requiring a lot of jobs later. (as we will add them one by one :) )

**Comment by alfonsogarciacaro** [comment]
Yeah, it seems to be a problem only on Unix systems (I think my colleague in my project also had the same in Linux). I'll try to report it.
