### ISSUE TITLE
Problem with SourceMaps

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#941]
### Description

I'm having problems with my sourcemaps bing almost useless. Sample [here](https://sokra.github.io/source-map-visualization/#base64,J3VzZSBzdHJpY3QnOwoKZnVuY3Rpb24gX2ludGVyb3BEZWZhdWx0IChleCkgeyByZXR1cm4gKGV4ICYmICh0eXBlb2YgZXggPT09ICdvYmplY3QnKSAmJiAnZGVmYXVsdCcgaW4gZXgpID8gZXhbJ2RlZmF1bHQnXSA6IGV4OyB9Cgp2YXIgYXZhID0gX2ludGVyb3BEZWZhdWx0KHJlcXVpcmUoJ2F2YScpKTsKCmF2YSgidGVzdDEiLCBmdW5jdGlvbiAoQXNzZXJ0KSB7CiAgQXNzZXJ0LnBhc3MoIk5vIHByb2JsZW0iKTsKICBBc3NlcnQucGFzcygiTmVtbyBwcm9ibGVtbyIpOwp9KTsKYXZhKCJ0ZXN0MiIsIGZ1bmN0aW9uIChBc3NlcnRfMSkgewogIEFzc2VydF8xLnRydWUodHJ1ZSwgIkkgcGFzcyB3aXRoIGZseWluZyBjb2xvcnMgOikiKTsKICBBc3NlcnRfMS5mYWxzZShmYWxzZSk7Cn0pOwovLyMgc291cmNlTWFwcGluZ1VSTD10ZXN0LmpzLm1hcAo=,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZXMiOlsiLi4vLi4vdGVzdC5mcyJdLCJzb3VyY2VzQ29udGVudCI6WyJtb2R1bGUgWW9sb0Rldi5HaXRIdWIuQ29yZS5UZXN0XG5cbm9wZW4gRmFibGUuSW1wb3J0LkF2YVxuXG50ZXN0IFwidGVzdDFcIiAoZnVuIEFzc2VydCAtPlxuICBBc3NlcnQuUGFzcyBcIk5vIHByb2JsZW1cIlxuICBBc3NlcnQuUGFzcyBcIk5lbW8gcHJvYmxlbW9cIlxuKVxuXG50ZXN0IFwidGVzdDJcIiAoZnVuIEFzc2VydCAtPlxuICBBc3NlcnQuVHJ1ZSAodHJ1ZSwgXCJJIHBhc3Mgd2l0aCBmbHlpbmcgY29sb3JzIDopXCIpXG4gIEFzc2VydC5GYWxzZSBmYWxzZVxuKSJdLCJuYW1lcyI6W10sIm1hcHBpbmdzIjoiOzs7Ozs7YUFLRTs7OzthQUtBOzs7In0=,bW9kdWxlIFlvbG9EZXYuR2l0SHViLkNvcmUuVGVzdAoKb3BlbiBGYWJsZS5JbXBvcnQuQXZhCgp0ZXN0ICJ0ZXN0MSIgKGZ1biBBc3NlcnQgLT4KICBBc3NlcnQuUGFzcyAiTm8gcHJvYmxlbSIKICBBc3NlcnQuUGFzcyAiTmVtbyBwcm9ibGVtbyIKKQoKdGVzdCAidGVzdDIiIChmdW4gQXNzZXJ0IC0+CiAgQXNzZXJ0LlRydWUgKHRydWUsICJJIHBhc3Mgd2l0aCBmbHlpbmcgY29sb3JzIDopIikKICBBc3NlcnQuRmFsc2UgZmFsc2UKKQ==).

I'm trying to build pseudo-unbundled code using rollop on a per-file basis. The code is small currently, but I'm not sure if it's my rollup setup or fable itself that's causing problems. I was told on gitter to make an issue on it so it could be investigated. Rollup is ran like this: https://github.com/YoloDev/fable-github-client/blob/master/test/build.js#L70.

### Related information 

* fable-compiler version: 1.0.4
* fable-core version: 1.0.4
* Operating system: OSX

**Comment by alfonsogarciacaro** [comment]
Yes, source maps are not perfects. There are many transformations in the AST and each of them has to carry the range information correctly for everything to work. Is this happening in the whole code in general or only in the linked case? I wonder if it's a problem with imports, I'll have a look.

Thanks a lot for the link to the source map check tool, I didn't know it and it'll be very useful 👍

**Comment by Alxandr** [comment]
Didn't know it either. I was just stumped by the fact that it printed so wrong information so I went looking for a visualizer :)

**Comment by alfonsogarciacaro** [comment]
I removed the range info for most identifiers to simplify code generation, bringing this back will hopefully improve source maps.

**Comment by alfonsogarciacaro** [comment]
There've been several improvements in source maps in latest Fable, although they will likely be never perfect. Please reopen (or open a new issues) if you have some specific examples where the source maps can be improved.

**Comment by jpierson** [comment]
I haven't started any code yet on this but I'm keeping my eye on this. My first inclination is the do a direct port of https://github.com/mozilla/source-map assuming that this is precisely what is needed but then I'm wondering if we'd be better to go with C# or F# for the port, I'd prefer to write it in F# myself but there is some benefits in choosing C#. Either way porting the library would provide a native .NET implementation for working with source-maps in general which may be a useful thing for the .NET ecosystem. For now I've [forked the project](https://github.com/jpierson/source-map) with some intent of giving this option a shot in my limited spare time.

Another option perhaps that just occurred to me would be to use WebAssembly support for https://github.com/mozilla/source-map library to compile to WebAssembly and then [embed the WASM into a .NET library using Wasmtime](https://www.thinktecture.com/en/webassembly/with-dotnet/). I'm not that familiar with this option but if it works and performs reasonably it may be an easier way to keep the implementation in sync with the original source-maps library in Javascript.
