### ISSUE TITLE
Import and Emit on same function

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#944]
### Description

The following gives me compile errors (from fable when compiling to js):

```fsharp
module Test =
  [<Import("default", from="ava"); Emit("$0($1)")>]
  let create' (impl: TestImpl): unit = jsNative
```

The error is:

```
Error: /Users/alxandr/hub/Fable.Ava/src/Fable.Ava/bindings.fs(50,6,50,13) : error FABLE: Fable.Core.EmitAttribute cannot be combined with Fable.Core.ImportAttribute for relative paths
```

If I add the same `Import` attribute to the module, the error goes away, but the `Import` attribute is also ignored.

### Related information 

* fable-compiler version: 1.0.4
* fable-core version: 1.0.4
* Operating system: OSX

**Comment by Zaid-Ajaj** [comment]
How does the code look like that you are trying to generate?

**Comment by Alxandr** [comment]
```js
import someRandomName from 'ava';
someRandomName($0);
```

The funny thing is, it works if I ignore the error I get. It produces the correct output. But it also throws an error in my face :-/

**Comment by Alxandr** [comment]
Basically, intuitively to me this should work:

```fsharp
[<Import("default", from="ava")>]
module Test =
  [<Emit("$0($1)")>]
  let create' (impl: TestImpl): unit = jsNative

Test.create (fun _ -> ())
```

```js
import ava from 'ava';
ava(function() {});
```

**Comment by Zaid-Ajaj** [comment]
Instead of `[<Import("default", from="ava")>]` you can use `importDefault "ava"` directly
```fs
open Fable.Core
open Fable.Core.JsInterop

module Test =
  let create (impl: obj): unit = importDefault "ava"

Test.create (fun _ -> ())
```

Will generate:
```js
import ava from "ava";
export const Test = function (__exports) {
  const create = __exports.create = ava;
  return __exports;
}({});
Test.create(function (_arg1) {});
```

**Comment by Zaid-Ajaj** [comment]
Also, you are using `[<Emit>]` with a function `create`. That function only take one argument (of type `TestImpl`) and returns unit. But you are putting 2 arguments inside that `[<Emit>]` expression, namely `$0` and `$1`. So unless `create` is used within a class/interface, that `$0` will not be the reference to the instance (self/this) but rather only be the first argument.

**Comment by Alxandr** [comment]
That's fine for when I only have one function, but my actual module have 30 or so. I just shortened it down to a minimal case. Also, you end up with an annoying indirection you shouldn't need, or you end up with non-idiomatic F# code with instances staring with capital letter (as done on the `Fable.Core` library).

But not to get sidetracked, there are a few actual issues here. First of all, the release notes explicitly says that emit and import can be combined: https://github.com/fable-compiler/Fable/blob/master/RELEASE_NOTES.md#075-alpha23

Second, the error message says I can't combine them for a relative path (which I am not using).

Thirdly, it produces the right output that I want, it just also produces an error. In other words, this works, it's just turned off basically.

Forth, if you have `[<Import>]` on both a module and a function within that module, both seem ignored. If you only have it on the module that also seem ignored. That might just me not producing the right code though.

And fifth, I'd argue that having `[<Import>]` on a module and `[<Emit>]` on the functions is a really good and clean way of creating import libraries and should be supported, but that probably warrants a new issue.

**Comment by Alxandr** [comment]
The error (as far as I can understand) originates here: https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1037

I would think someone forgot to add `&& pathIsRelativeCheckSomehow` and that would solve that bug.

**Comment by Zaid-Ajaj** [comment]
If it generating an error while the output is correct, that is definitely a bug. Also, I just checked the [JsInteropTests](https://github.com/fable-compiler/Fable/blob/master/src/tests/Main/JsInteropTests.fs) and couldn't see any examples of using both attributes. So it could have been removed in latest version and in the one you are using

**Comment by alfonsogarciacaro** [comment]
Hmm, this should work in the latest fable version (which apparently you're using). I tried to reproduce and it worked for me 😕 The combination of Import and Emit happens here: https://github.com/fable-compiler/Fable/blob/6fe601e6601b04ad040ccc88b97ed62ce4c1f000/src/dotnet/Fable.Compiler/FSharp2Fable.Util.fs#L1248-L1250

Actually we should have a test as @Zaid-Ajaj says. Would you mind PRing a failing test to [ImportTests](https://github.com/fable-compiler/Fable/blob/6fe601e6601b04ad040ccc88b97ed62ce4c1f000/src/tests/Main/ImportTests.fs) so I can reproduce in my machine?

**Comment by Alxandr** [comment]
@alfonsogarciacaro as stated, it works, but it produces an error (the result from the fable server includes a `logs.error`). So I don't know whether or not the importtests would catch that.

To produce this error should be as simple as slapping `[<Import("foo", "bar"); Emit("$0($1)")>]` on any old function. Unless I have any problems running fable locally I can probably make a PR with a failing test later today (if the tests catch diagnostic errors produced by fable).

**Comment by alfonsogarciacaro** [comment]
Sorry, I read the issue too quickly 😅 

After a more careful line, it seems [those lines](https://github.com/fable-compiler/Fable/blob/9266d2850e1db56422dcd4d697520845efa4bd1a/src/dotnet/Fable.Compiler/FSharp2Fable.fs#L1037-L1041) are outdated, I'll remove them :+1:

**Comment by Alxandr** [comment]
> After a more careful line

I assume you also write too quickly? :P 
Please let me know when a release with this fixed is out so I can remove my code that ignores errors.
