### ISSUE TITLE
Fable cannot compile project referencing a file from relative directory

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#945]
### Description
When a project referencing a fsharp file (.fs) from a relative directory, Fable fails to compile that project becuase fable-loader cannot find `paket.dependencies` in that relative directory:

![repro](https://cloud.githubusercontent.com/assets/13316248/26372311/ccf2e48a-3ffd-11e7-9790-bb113ab712b9.png)

# Repro 
Create the following directory structure:
```
root
  |
  | -- App
        | 
        | -- [ here the files of Simple template from "dotnet new fable" ]

  | -- Other
        |
        | -- Code.fs
```

reference file Code.fs from App.fsproj
```xml
<Project Sdk="FSharp.NET.Sdk;Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>netstandard1.6</TargetFramework>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="../Other/Code.fs" />
    <Compile Include="src/App.fs" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="FSharp.NET.Sdk" Version="1.0.*" PrivateAssets="All" />
    <DotNetCliToolReference Include="dotnet-fable" Version="1.0.4" />
  </ItemGroup>
  <Import Project=".paket\Paket.Restore.targets" />
</Project>
```

Then install the project App.fsproj:
```
cd App
yarn install
dotnet restore 
dotnet fable npm-run build
```

Project from the screen shot
[Project.zip](https://github.com/fable-compiler/Fable/files/1023503/Project.zip)

**Comment by MangelMaxime** [comment]
@Zaid-Ajaj You probably should use `Project References`.

When sharing code in .Net world, you references différentes projects.

**Comment by Zaid-Ajaj** [comment]
@MangelMaxime I could do that but there shouldn't be a requirement to have another project just because  I am referencing a fsharp file from different directory. Fable as able to resolve that file the same way it is resolving the `App.fs` from the `src` directory.

In .NET it is the same, you could link files from anywhere and put them in one project file. 

The fact that fable is looking for `paket.dependencies` in that project is incorrect.

**Comment by Zaid-Ajaj** [comment]
After adding some logging to this function:
```fs
let rec findPaketDependenciesDir dir =
    if File.Exists(Path.Combine(dir, "paket.dependencies")) then
        dir
    else
        match Directory.GetParent(dir) with
        | null -> failwith "Couldn't find paket.dependencies directory"
        | parent -> findPaketDependenciesDir parent.FullName
```
and turning it into this, running Fable daemon locally from sources
```fs
let rec findPaketDependenciesDir dir =
    let path = Path.Combine(dir, "paket.dependencies")
    printfn "Looking for paket.dependencies inside %s" dir
    if File.Exists(path) then
        printfn "paket.dependencies found inside directory %s" dir
        dir
    else
        match Directory.GetParent(dir) with
        | null -> failwith "Couldn't find paket.dependencies directory"
        | parent -> findPaketDependenciesDir parent.FullName
```

It seems that Fable daemon is trying to find paket.dependencies after it compiles EACH .fs FILE! see screen shot log down below

@alfonsogarciacaro Please check this

![recursive-deps](https://cloud.githubusercontent.com/assets/13316248/26405559/f9b71fc0-4095-11e7-9b74-b3f6d0d1aa6b.png)

I understand what it is doing, making sure the Fable.Core version is in-sync with dotnet-fable. But it is only checking parent directories and not _sibling_ directories which is why it couldn't find paket.dependencies when referencing a lonely fsharp file from another directory.

What is the best course of action here?

**Comment by alfonsogarciacaro** [comment]
I agree that we should fix this problem, I did it like this to solve `fable-core` location in [the Parser module](https://github.com/fable-compiler/Fable/blob/9266d2850e1db56422dcd4d697520845efa4bd1a/src/dotnet/Fable.Tools/Parser.fs#L95) which has no information about the state, the current project, etc. We could postpone the resolution to the `State` module which does have this kind of information.

**Comment by alfonsogarciacaro** [comment]
We could do it like this:

- Search (and store) paketDir when [creating a Project](https://github.com/fable-compiler/Fable/blob/9266d2850e1db56422dcd4d697520845efa4bd1a/src/dotnet/Fable.Tools/State.fs#L31)
- [Right before compiling](https://github.com/fable-compiler/Fable/blob/9266d2850e1db56422dcd4d697520845efa4bd1a/src/dotnet/Fable.Tools/State.fs#L263) check if `com.Options.fableCore = "fable-core"` and in that case create a new compiler with new options calculating the fable-core location as [in here](https://github.com/fable-compiler/Fable/blob/9266d2850e1db56422dcd4d697520845efa4bd1a/src/dotnet/Fable.Tools/Parser.fs#L96)

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro Sent a PR, please review :pray:
