### ISSUE TITLE
error FABLE: Cannot find replacement for System.Environment.get_NewLine

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#947]
### Description

error FABLE: Cannot find replacement for System.Environment.get_NewLine

### Repro code

    printfn "%s" System.Environment.NewLine

**Comment by alfonsogarciacaro** [comment]
This should be an easy one. Anyone in @fable-compiler/code-maintenance team interested in taking it? I can point out where it should be added in `Replacements` so it's a good way to get in touch with that module.

**Comment by Zaid-Ajaj** [comment]
For reference: https://stackoverflow.com/questions/10864486/node-js-constant-for-platform-specific-new-line

**Comment by alfonsogarciacaro** [comment]
I would just use `\n` as most of the times the code will be run in the web.

**Comment by forki** [comment]
+1 for \n

**Comment by ncave** [comment]
In general, +1 for matching the BCL functionality as close to documented as possible to minimize surprises.
This may or may not be one of the exceptions, but IMO it's not, just use the string literal if you need to.
But I can see this very rapidly evolving into spaces-vs-tabs-like argument, so I'll stop here, please ignore...

**Comment by forki** [comment]
Ok. Let me correct myself. I'm personally fine with simple line breaks but
yes doing it properly will give bonus points.

Am 25.05.2017 5:46 nachm. schrieb "ncave" <notifications@github.com>:
