### ISSUE TITLE
fetch available from nuget gallery?

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#951]
Hey guys, just getting started with Fable. I'm trying it out for an internal work project. I really liked the recent [blog post](http://fable.io/blog/Paket-integration.html) about moving to Paket & Yarn since those are the tools we use. I'd like to be able to use the Fetch API as described in https://www.npmjs.com/package/fable-import-fetch and in http://www.navision-blog.de/blog/2016/08/10/fable-fetch-http-calls-in-javascript-apps-with-fsharp/. Is there plan to migrate npm code over to nuget as described in that post? Should that code be moved? Do you need help?

cc @7sharp9, @forki

**Comment by alfonsogarciacaro** [comment]
Hi @ctaggart! Actually we added the Fetch API with some additional helpers to Fable.PowerPack, and that library is already available in Nuget, so you can use Paket to download it. You can check [the fetch tests](https://github.com/fable-compiler/fable-powerpack/blob/5ee628ccd1625bbe1eb9da1cfbd2b97b7ec14130/tests/FetchTests.fs) for samples :)

**Comment by ctaggart** [comment]
That is what I was looking for. Thanks!
