### ISSUE TITLE
[Feature] Allow ImportAttribute on modules to affect it's members

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#953]
### Description

Please make the following equivalent:

```fsharp
[<Import("foo", from="bar")>]
module Foo =
  [<Emit("$0.foo($1)")>]
  let foo (v: string): unit = jsNative

  [<Emit("$0.bar($1)")>]
  let bar (v: string): unit = jsNative
```

```fsharp
module Foo =
  [<Import("foo", from="bar"); Emit("$0.foo($1)")>]
  let foo (v: string): unit = jsNative

  [<Import("foo", from="bar"); Emit("$0.bar($1)")>]
  let bar (v: string): unit = jsNative
```

If we are worried about braking stuff, a new property on the `ImportAttribute` could be introduced, something like this:

```fsharp
[<Import("foo", from="bar", implicit=true)>]
module Foo =
  [<Emit("$0.foo($1)")>]
  let foo (v: string): unit = jsNative

  [<Emit("$0.bar($1)")>]
  let bar (v: string): unit = jsNative
```

**Comment by alfonsogarciacaro** [comment]
Actually you shouldn't need the `Emit` attributes, just the `Import` attribute on top of the module would be enough for your purposes:

```fsharp
[<Import("foo", from="bar")>]
module Foo =
  let foo (v: string): unit = jsNative
  let bar (v: string): unit = jsNative

Foo.foo("bar")
Foo.bar("foo")

// import { foo } from "bar"
// foo.foo("bar")
// foo.bar("foo")
```

However, in these cases, I usually recommended defining an interface and use import expresions

```fsharp
type IFoo =
    abstract foo: string -> unit
    abstract bar: string -> unit

let foo: IFoo = importMember "bar"
```

**Comment by Alxandr** [comment]
True for that case, but how about this one?

```fsharp
[<RequireQualifiedAccess>]
module Sinon =
  [<Import("default", from="sinon"); Emit("$0.spy()")>]
  let spy<'a, 'b> : Spy1<'a, 'b> = jsNative

  [<Import("default", from="sinon"); Emit("$0.spy()")>]
  let spy2<'a, 'b, 'c> : Spy2<'a, 'b, 'c> = jsNative

  [<Import("default", from="sinon"); Emit("$0.spy()")>]
  let spy3<'a, 'b, 'c, 'd> : Spy3<'a, 'b, 'c, 'd> = jsNative

  [<Import("default", from="sinon"); Emit("$0.stub()")>]
  let stub<'a, 'b> : Stub1<'a, 'b> = jsNative

  [<Import("default", from="sinon"); Emit("$0.stub()")>]
  let stub2<'a, 'b, 'c> : Stub2<'a, 'b, 'c> = jsNative

  [<Import("default", from="sinon"); Emit("$0.stub()")>]
  let stub3<'a, 'b, 'c, 'd> : Stub3<'a, 'b, 'c, 'd> = jsNative
```

I don't want to do `let Sinon = importDefault "sinon"` for several reasons. One, because you end up with a let binding with a capital case, which is non-idiomatic. Two, conceptually what I import from sinon is not a instance of an interface. It's a module. Also, I use `Emit` a lot to enable different names on the F# side than on the js side.

The following does not work:

```fsharp
[<RequireQualifiedAccess; Import("default", from="sinon")>]
module Sinon =
  [<Emit("$0.spy()")>]
  let spy<'a, 'b> : Spy1<'a, 'b> = jsNative

  [<Emit("$0.spy()")>]
  let spy2<'a, 'b, 'c> : Spy2<'a, 'b, 'c> = jsNative

  [<Emit("$0.spy()")>]
  let spy3<'a, 'b, 'c, 'd> : Spy3<'a, 'b, 'c, 'd> = jsNative

  [<Emit("$0.stub()")>]
  let stub<'a, 'b> : Stub1<'a, 'b> = jsNative

  [<Emit("$0.stub()")>]
  let stub2<'a, 'b, 'c> : Stub2<'a, 'b, 'c> = jsNative

  [<Emit("$0.stub()")>]
  let stub3<'a, 'b, 'c, 'd> : Stub3<'a, 'b, 'c, 'd> = jsNative
```

The output reads `null.stub()` which I find somewhat amusing.

**Comment by Alxandr** [comment]
Also, I think it's a bad idea to recommend using interfaces. I had some serious issues with using an interface and then creating another class that implemented it, where all the js calls became completely wrong. The types you import from JS should be sealed classes IMHO.

See https://github.com/YoloDev/Fable.Ava/blob/master/src/Fable.Ava/bindings.fs#L7

While the interfaces is probably more convenient, it is also a footgun, and recommending the community to go down that path is likely to lead to a lot of headaches. Alternatively, `[<Emit>]` should be disallowed for abstract members.

**Comment by jgrund** [comment]
Hi @Alxandr,

Do you have an example of a case where implementing an interface broke things?

Also, if we were to go with sealed classes, then how would one use a binding that is expected to be extended?

**Comment by Alxandr** [comment]
@jgrund the problem is not actually the interface in and of themselves, the problem is `[<Emit>]`.

I had something like the following in my code:

```fsharp
type IExternal =
  [<Emit("$0.foo()")>]
  abstract Foo: unit -> unit

type CustomExternal ()
  interface IFoo with
    member Foo = ()
```

If you compile this to JS, you get a `CusomtExternal` class with member `Foo` (capital F), that you can never invoke, because any call to `IFoo::Foo` gets compiled to `inst.foo()` instead.

**Comment by alfonsogarciacaro** [comment]
You can use `CompiledName` :)

```fsharp
[<RequireQualifiedAccess; Import("default", from="sinon")>]
module Sinon =
  [<CompiledName("spy")>]
  let spy1<'a, 'b> : obj = jsNative // Note change to `spy1` here

  [<CompiledName("spy")>]
  let spy2<'a, 'b, 'c> : obj = jsNative

  [<CompiledName("spy")>]
  let spy3<'a, 'b, 'c, 'd> : obj = jsNative

// import sinon from "sinon";
// sinon.spy();
```

Funny enough, accessing the members is being translated as a call, which seems to be what you need but it's probably a bug ;)

If I can give another piece of advice, I'd say the `Emit` attribute is not to be abused. I'm sure you have very good reasons for it and I know it's tempting to fix everything with it but I've always tried to limit its use as much as possible. There may be corner cases where `Emit` doesn't work as expected, and we probably won't be able to fix them all.

About the idiomatic use of upper and lower case in F# and JS, at the beginning I tried to do automatic conversions but this caused several problems so I decided to avoid name mangling (especially for interfaces). I personally don't see it as a problem that types coming from JS are lowered-case, but I understand some people find it annoying :)

**Comment by Alxandr** [comment]
My point with the casing was that I do not want to do this:

```
let Sinon = importDefault "sinon"
```

That's a let-binding with a capital case.

Also, `CompiledName` is obviously a nogo, as that wouldn't even compile (you have 3 members with the same name).

**Comment by Alxandr** [comment]
Btw; if you don't want `Emit`, how about a `[<JsName>]`?

**Comment by ncave** [comment]
I've probably missed the point, but what's wrong with Emit (without parameters)?
```
[<RequireQualifiedAccess; Import("default", from="sinon")>]
module Sinon =
  [<Emit("spy")>]
  let spy1<'a, 'b> : obj = jsNative // Note change to `spy1` here

  [<Emit("spy")>]
  let spy2<'a, 'b, 'c> : obj = jsNative

  [<Emit("spy")>]
  let spy3<'a, 'b, 'c, 'd> : obj = jsNative

```

**Comment by Alxandr** [comment]
That will just emit `spy`. As an identifier.

**Comment by Alxandr** [comment]
@alfonsogarciacaro if you wanted to get fancy with the emit (without using `[<Emit>]`) you could use quotations. Something like this:

```fsharp
let spy1<'a, 'b>: obj = jsEmit <@ this?spy () @>
```

The compiler could take the quotation and produce babel ASTs from it, that way you wouldn't have the problems you generally do with strings.

**Comment by ncave** [comment]
@Alxandr Sorry, what I actually meant was using Emit with Func<>:
```
[<RequireQualifiedAccess; Import("default", from="sinon")>]
module Sinon =

  [<Emit("spy")>]
  let spy1: System.Func<'a, 'b, 'T> = jsNative // Note change to `spy1` here

  [<Emit("spy")>]
  let spy2: System.Func<'a, 'b, 'c, 'T> = jsNative

  [<Emit("spy")>]
  let spy3: System.Func<'a, 'b, 'c, 'd, 'T> = jsNative

let r1: obj = Sinon.spy1.Invoke (1, 2)
let r2: obj = Sinon.spy2.Invoke (1, 2, 3)
let r3: obj = Sinon.spy3.Invoke (1, 2, 3, 4)
```
I know, 1) Not very F#-like, and 2) some compiler warnings (which go away if not using generic types)

May not be what you're looking for, just wanted to mention it.

**Comment by Alxandr** [comment]
And still wouldn't work, because there is no global `spy` defined. What you effectively want is something like `Emit("sinon.spy")`, except you don't know the sinon name cause it's auto-generated.

**Comment by ncave** [comment]
@Alxandr Yes, that's what I meant, Emit("sinon.spy") (updated above). How is it auto-generated when you have it hardcoded here: Import("default", from="sinon")>] ?

**Comment by Alxandr** [comment]
Cause what's actually generated is `_sinon1.default.spy`.

`[<Import("default", from="sinon")>]` could perfectly validly generate `import myVar from 'sinon';`. And then just use `myVar`. What if the name `sinon` is already taken?

**Comment by ncave** [comment]
@Alxandr I agree, hard to match the mangled name, so not an option.
