### ISSUE TITLE
published npm package Fable.Plugins.NUnit@next does not work with Fable 1.0.4

### ISSUE THREAD

**Issue by johlrich** [fable-compiler/Fable#957]
The currently published npm package for Fable.Plugins.NUnit@next (1.0.0-narumi-2) does not work with Fable 1.0.4

Exception:
ERROR: Cannot load plugin C:/Development/spikes/fable-testing/node_modules/fable-plugins-nunit/Fable.Plugins.NUnit.dll: Unable to load one or more of the requested types. Retrieve the LoaderExceptions property for more information.
   at Fable.Tools.State.loadPlugins@147-3.Invoke(String message)
   at Fable.Tools.State.loadPlugins@134.Invoke(String path)
...

If I build the plugin from source and replace the npm package's dll with it, everything works fine. Probably just needs a republish.

**Comment by alfonsogarciacaro** [comment]
Thanks for the heads up! To follow what we're doing with other libraries, I have pushed the code to Nuget this time and wrote [a README with installlation/usage documentation](https://github.com/fable-compiler/Fable/blob/569f2fadac2e0391cb4b5480d11d70f5937b6791/src/plugins/nunit/README.md).

Can you please try the package and see it woks?

**Comment by johlrich** [comment]
Package worked.

Out of habit I included the file in my `paket.references` file, but this will cause an exception with `fable-loader`. This makes sense, but probably worth mentioning in the install page?

> Module build failed: Error: File does not exist: C:\Development\spikes\fable-testing\packages\Fable.Plugins.NUnit\fable\Fable.Plugins.NUnit.fsproj
>     at client.send.then.data (C:\Development\spikes\fable-testing\node_modules\fable-loader\index.js:55:26)
> 

What would the path be for someone who doesn't use paket? Is using fable without paket unsupported now? (I personally plan on continuing with paket+yarn, but asking for documentation completeness sake)

**Comment by alfonsogarciacaro** [comment]
> Package worked.

Great! :tada:

> Out of habit I included the file in my paket.references file, but this will cause an exception with fable-loader. Removing it from the references file makes everything work fine.

You shouldn't need to add it to `paket.references` as you don't have to reference the plugin directly from your project, but anyways I've to fix the error when there's no `fable` folder in the Nuget package.

> What would the path be for someone who doesn't use paket?

Wherever you decide to install it :smile: I guess if you're just using Nuget, it'll be the .nuget cache directory.

> Is using fable without paket unsupported now?

Yes, now Paket is needed to resolve Fable dependencies (not the plugins, but libraries directly referenced by your project)
