### ISSUE TITLE
Proposal: Move Imports out of Fable.Core

### ISSUE THREAD

**Issue by et1975** [fable-compiler/Fable#958]
### Description
I find myself updating something that depends on node imports 3rd time in about a week.
Normally, for any import not in the core it wouldn't be an issue, as we can reference specific version of the bindings. Core however comes as a compiler dependency and is special that way.

Obviously there are other ways to deal with this specific instance, but why not move the imports out?

**Comment by johlrich** [comment]
There's a discussion about this in https://github.com/fable-compiler/Fable/issues/930

**Comment by et1975** [comment]
thanks, closing as duplicate.
