### ISSUE TITLE
UnionTypeConverter not working with option

### ISSUE THREAD

**Issue by ctaggart** [fable-compiler/Fable#971]
I'm getting an error when I try to serialize this for returning via webapi. It appears to be chocking on the `option`.  I'm using the code `UnionTypeConverter`. There is no `+`. Should I be using the `UnionTypeConverter` as documented?

http://fable.io/docs/interacting.html#JSON-serialization

``` fs
type Batch = {
    Name: string
    Timestamp: DateTimeOffset
    RunTimeMinutes: int option
}
```

![image](https://cloud.githubusercontent.com/assets/80104/26594178/f3ca1380-4566-11e7-8d5a-9621ef932e3b.png)

**Comment by Zaid-Ajaj** [comment]
Hmm maybe try [Fable.JsonConverter](https://www.nuget.org/packages/Fable.JsonConverter/1.0.0-narumi-908)? the docs could be outdated

**Comment by ctaggart** [comment]
Thanks @Zaid-Ajaj, I spotted that and I've been trying to add it. I've resorted to building the [source file](https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.JsonConverter/Fable.JsonConverter.fs) instead of including the NuGet package since my web project is not a dotnet project yet. I ran into a few hours of dependency hell trying to include the netstandard1.6\Fable.JsonConverter.dll binary. It may be a good idea to also compile it for `net461`. I'll see if this works and may be try that out later.

**Comment by Zaid-Ajaj** [comment]
Compiling the sources is also what I had to do to get it working :smile:

**Comment by ctaggart** [comment]
What worked for me for with ASP.NET is:
``` fs
let config = new System.Web.Http.HttpConfiguration()
config.Formatters.Remove(config.Formatters.XmlFormatter) |> ignore
config.Formatters.JsonFormatter.SerializerSettings.Converters <- [| Fable.JsonConverter() |]
config.Formatters.JsonFormatter.SerializerSettings.ContractResolver <- Newtonsoft.Json.Serialization.DefaultContractResolver()
```
