### ISSUE TITLE
Automate updating the simple template whenever Fable.Core and dotnet-fable are patched

### ISSUE THREAD

**Issue by Zaid-Ajaj** [fable-compiler/Fable#972]
### Expected 
Fable.Core and dotnet-fable to up to date whenever a patch is released
### Actual
That is not the case: Fable.Core/dotnet-fable are 1.0.4 in the template but should be 1.0.7 (latest) 

cc @fable-compiler/code-maintenance

**Comment by ncave** [comment]
It's a template, can they just be "1.0.*" or is that frowned upon?

**Comment by alfonsogarciacaro** [comment]
Actually we added the lock files precisely so templates **did not automatically update** the Fable version (in case there were regression bugs) :wink:

If we want to automatically update the templates, probably we should add some tests to be sure the template doesn't break with the latest Fable version.

**Comment by Zaid-Ajaj** [comment]
@alfonsogarciacaro I meant to update the versions in the template with their lock files to latest after testing. This does _not_ mean that the user will update his/her versions everytime they build a template (that would happen if the version is set to "get the latest" and that we are trying to avoid)  but only when they _update_ the template itself. 

@ncave I don't think we want users to update automatically to whatever version is the latest. 

So I think we just make sure the new patches don't break the template and update it

**Comment by alfonsogarciacaro** [comment]
Then we just need somebody to PR integration tests for the template :wink: That'd be something actually also nice to have for the final user. Maybe using Canopy as the fable-suave-scaffold.

**Comment by ncave** [comment]
> So I think we just make sure the new patches don't break the template and update it
semver something something ... backwards-compatible ... no-breaking changes ... etc.
I mean, it's a template after all, people are supposed to change it.
I know I'm on the wrong side of history here, so please ignore :)
