### ISSUE TITLE
Decorator proposal

### ISSUE THREAD

**Issue by Alxandr** [fable-compiler/Fable#981]
It was just asked on gitter how do do the following in fable:

```js
@Component( {“selector”: “my-app”})
class Foo { }
```

Decorators are used quite a bit in JS today by certain communities, and not supporting them in Fable is probably a bad idea. It's also however a rather tricky subject to deal with, but I believe I have a solution that should work, and be fairly idiomatic using F# attributes.

If we introduce the following interface/abstract base attribute class:

```fsharp
type IDecoratorAttribute =
  abstract Target: obj
  abstract Args: obj list
```

Which can be used like this:

```fsharp
module AngularBindings

// I don't know these functions, but you should get 
let compDec = import "Component" "angular"the point

[<AttributeUsage(AttributeTarget.Class)>]
type ComponentAttribute () =
  let mutable selector: String option
  // Don't know if this works, haven't used attributes in F# in forever
  member x.Selector with set v = selector <- Some v

  interface IDecoratorAttribute with
    member x.Target = compDec
    member x.Args =
      [ "selector", selector ]
      |> List.map (fun (k, v) -> Option.map (fun v -> k, v) v)
      |> List.choose id
      |> createObj

// later
[<Component(Selector = "my-app")>]
type Foo =
  ...
```

This could compile into something like this:

```js
import toDecorator from 'fable-core/decorator';

@toDecorator(() => {
  const attr = new ComponentAttribute();
  attr.Selector = 'my-app';
  return attr;
}())
class Foo {}
```

It's not exactly pretty, but it would work, and enable support for a bunch of angular stuff, and some react stuff (like mobx) etc.

**Comment by mizzle-mo** [comment]
Related #347
