### ISSUE TITLE
Canvas.ToBlob fails with a type error

### ISSUE THREAD

**Issue by 0x53A** [fable-compiler/Fable#982]
![image](https://cloud.githubusercontent.com/assets/4236651/26767578/a7645232-49a1-11e7-8906-37f40225322f.png)

see https://github.com/fable-compiler/Fable/blob/master/src/dotnet/Fable.Core/Import/Fable.Import.Browser.fs#L2959

I *think* it should instead take a callback and not return anything:

https://developer.mozilla.org/en-US/docs/Web/API/HTMLCanvasElement/toBlob

**Comment by Zaid-Ajaj** [comment]
Hello @0x53A, the browser bindings are a bit outdated. Should be easy to fix
