### ISSUE TITLE
Fable should warn on the use of nested Option

### ISSUE THREAD

**Issue by generalelectrix** [fable-compiler/Fable#987]
### Description

Since Fable compiles Option down into a nullable object, using nested options will produce unexpected behavior as `Some(None)` compiles to `null`, so `Some(None) = None` evaluates to true in Fable yet false in regular F#.  Pattern matching of course has the same issue.

### Expected and actual results

This can lead to pretty heinous bugs if you are using existing F# code that expects nested options to work.  It is possible to work around by essentially defining a fresh version of Option with a different name, thus lacking Fable's nullable representation, but it would probably be good to issue a compiler warning on the use of nested options.

**Comment by alfonsogarciacaro** [comment]
Hi @generalelectrix! This is a nice suggestion and shouldn't be too difficult to implement, though it probably won't make it into the first Fable 1.0 stable version. We'll try to implement it in future versions or, if you want to give it a try, we can provide you some guidance on how to do it.

Cheers!

**Comment by generalelectrix** [comment]
If you think it wouldn't be too hard, I could dive in with some guidance presuming the coding to be done is on the F# side (I'm here because I'm a JS ignoramus).

**Comment by alfonsogarciacaro** [comment]
Relevant: https://github.com/fsharp/fslang-suggestions/issues/546

Closing as this is fixed thanks to @coolya's PR! :clap: :clap:

Please note, this has been made a warning and not an error at the end as it affected Fable self-compilation (to create the REPL).
