### ISSUE TITLE
Show relative path during compile

### ISSUE THREAD

**Issue by forki** [fable-compiler/Fable#988]
create the fable react template and start fable.

![image](https://user-images.githubusercontent.com/57396/26923763-6ea48d6e-4c43-11e7-897c-1f0d4bb220ce.png)

It would be nice if fable would show `Counter\Types.fs" and so on

**Comment by MangelMaxime** [comment]
I believe it's been fixed now ?

![image](https://user-images.githubusercontent.com/4760796/28250278-b253b910-6a64-11e7-8ff6-61a56702b797.png)

**Comment by alfonsogarciacaro** [comment]
Yeah, it is. Thanks!
